Repository keycloak/keycloak, pull requests merged in 2018-10, with the labels that each got.

#5620 KEYCLOAK-8509 Improvements to session iframe
  adapters/oidc/js/src/main/resources/keycloak.js
  adapters/oidc/js/src/main/resources/login-status-iframe.html
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LoginStatusIframeEndpoint.java
Labels: Hold

#5644 [KEYCLOAK-8580] Add Nginx certificate lookup provider
  services/src/main/java/org/keycloak/services/x509/AbstractClientCertificateFromHttpHeadersLookup.java
  services/src/main/java/org/keycloak/services/x509/NginxProxySslClientCertificateLookup.java
  services/src/main/java/org/keycloak/services/x509/NginxProxySslClientCertificateLookupFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.services.x509.X509ClientCertificateLookupFactory
  testsuite/integration-arquillian/tests/base/src/test/resources/META-INF/keycloak-server.json
Labels: Missing Docs

#5659 KEYCLOAK-8637 Add support for OIDC multitenancy adapter test for jbos…
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/MultiTenantResolver.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/AbstractServletsAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/MultiTenancyTest.java
Labels: Ready

#5660 KEYCLOAK-8632 Configuration of keycloak server in performance testsuite fails
  testsuite/performance/db-failover/README.md
  testsuite/performance/docker-compose-db-failover.yml
  testsuite/performance/infinispan/infinispan.xml
  testsuite/performance/infinispan/pom.xml
  testsuite/performance/infinispan/src/main/scripts/jboss-cli/add-private-network-interface.cli
  testsuite/performance/keycloak/configure.xml
  testsuite/performance/keycloak/pom.xml
  testsuite/performance/keycloak/src/main/resources/module.xml
  testsuite/performance/keycloak/src/main/scripts/jboss-cli/add-remote-cache-stores.cli
  testsuite/performance/keycloak/src/main/scripts/jboss-cli/set-keycloak-ds-batch.cli
  testsuite/performance/tests/src/main/docker-compose/crossdc/docker-compose-keycloak_dc1.yml
  testsuite/performance/tests/src/main/docker-compose/crossdc/docker-compose-keycloak_dc2.yml
Labels: Ready

#5649 [KEYCLOAK-8621] The Keycloak JS adapter should not mutate browser history state
  adapters/oidc/js/src/main/resources/keycloak.js
Labels: Missing JIRA
