Repository keycloak/keycloak, pull requests merged in 2019-11, with the labels that each got.

#6428 KEYCLOAK-8785 remove k_version endpoint
  adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/PreAuthActionsHandler.java
  adapters/oidc/spring-security/src/main/java/org/keycloak/adapters/springsecurity/filter/KeycloakCsrfRequestMatcher.java
  adapters/oidc/spring-security/src/test/java/org/keycloak/adapters/springsecurity/filter/KeycloakCsrfRequestMatcherTest.java
  core/src/main/java/org/keycloak/constants/AdapterConstants.java
  testsuite/integration-arquillian/test-apps/cors/angular-product/src/main/webapp/js/app.js
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/example/cors/CorsExampleAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/DemoServletsAdapterTest.java
Labels: Prioritize

#6412 KEYCLOAK-6073 Make adapters use discovery endpoint for URLs instead of hardcoding
  adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/KeycloakDeployment.java
  adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/KeycloakDeploymentBuilder.java
  adapters/oidc/adapter-core/src/test/java/org/keycloak/adapters/KeycloakDeploymentBuilderTest.java
  adapters/oidc/adapter-core/src/test/java/org/keycloak/adapters/KeycloakDeploymentTest.java
  adapters/oidc/osgi-adapter/pom.xml
  core/src/main/java/org/keycloak/constants/ServiceUrlConstants.java
  core/src/main/java/org/keycloak/protocol/oidc/representations/OIDCConfigurationRepresentation.java
Labels: Prioritize

#6454 [KEYCLOAK-11971] Remove credentials option from configuration
  adapters/oidc/js/src/main/resources/keycloak.js
Labels: Missing Docs

#6460 KEYCLOAK-11983 Use diamond operator for collections in module core
  core/src/main/java/org/keycloak/representations/AccessToken.java
  core/src/main/java/org/keycloak/representations/AccessTokenResponse.java
  core/src/main/java/org/keycloak/representations/RefreshToken.java
  core/src/main/java/org/keycloak/representations/adapters/action/GlobalRequestResult.java
  core/src/main/java/org/keycloak/representations/idm/AuthenticatorConfigRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/IdentityProviderMapperRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/IdentityProviderRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/ProtocolMapperRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/RealmRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/RequiredActionProviderRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/ScopeMappingRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/UserSessionRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/authorization/PermissionRequest.java
Labels: Missing JIRA

#6473 KEYCLOAK-9129 Don't expose Keycloak version in resource paths
  common/src/main/java/org/keycloak/common/Version.java
  common/src/main/resources/keycloak-version.properties
  model/jpa/src/main/java/org/keycloak/models/jpa/MigrationModelAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/MigrationModelEntity.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-8.0.0.xml
  server-spi-private/src/main/java/org/keycloak/migration/MigrationModelManager.java
  server-spi/src/main/java/org/keycloak/migration/MigrationModel.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/MigrationModelTest.java
Labels: Prioritize

#6402 KEYCLOAK-11772 Fix temporary credential property to work correctly
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
Labels: Discuss

#6486 KEYCLOAK-10780 Stop creating placeholder e-mails for service accoun…
  examples/demo-template/testrealm.json
  services/src/main/java/org/keycloak/services/managers/ClientManager.java
  testsuite/integration-arquillian/test-apps/photoz/photoz-realm.json
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ClientTest.java
Labels: Prioritize
