Repository keycloak/keycloak, pull requests merged in 2019-12, with the labels that each got.

#6569 [KEYCLOAK-12341] Replace references to Keycloak dev mailing list in the repositories
  CONTRIBUTING.md
  GOVERNANCE.md
Labels: Prioritize

#6396 KEYCLOAK-11770 add an hardcoded attribute mapper for ldap provider
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPUtils.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/HardcodedAttributeMapper.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/HardcodedAttributeMapperFactory.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/UserAttributeLDAPStorageMapper.java
  federation/ldap/src/main/resources/META-INF/services/org.keycloak.storage.ldap.mappers.LDAPStorageMapperFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPHardcodedAttributeTest.java
Labels: Missing Docs

#6585 KEYCLOAK-12425 Encode userid with Base64Url.
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnRegister.java
Labels: Missing Tests
