Repository keycloak/keycloak, pull requests merged in 2020-06, with the labels that each got.

#7129 [KEYCLOAK-11330] - Properly handling POST formdata and UriInfo
  services/src/main/java/org/keycloak/authentication/DefaultAuthenticationFlow.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/X509ClientAuthenticator.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
  services/src/main/java/org/keycloak/services/resources/account/AccountLoader.java
  services/src/main/java/org/keycloak/services/resources/account/resources/AbstractResourceService.java
  services/src/main/java/org/keycloak/services/resources/account/resources/ResourcesService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ResourceOwnerPasswordCredentialsGrantTest.java
Labels: Quarkus

#7123 [KEYCLOAK-14335] - Not initializing entity associations and removing bi-directional ones
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/AuthenticationFlowEntity.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/ClientEntity.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/ClientScopeEntity.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/ComponentEntity.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/GroupEntity.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/RealmEntity.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/RoleEntity.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/UserConsentEntity.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/UserEntity.java
Labels: Quarkus

#7133 [KEYCLOAK-11330] - Initial changes to get testsuite working for Quarkus
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/connections/jpa/QuarkusJpaConnectionProviderFactory.java
  quarkus/runtime/src/main/java/org/keycloak/provider/quarkus/QuarkusFilter.java
  quarkus/server/src/main/resources/application.properties
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/AuthServerTestEnricher.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/annotation/AuthServerContainerExclude.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/decider/AuthServerExcludeExecutionDecider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/openshift/OpenshiftClientStorageTest.java
Labels: Quarkus

#7137 [KEYCLOAK-11330] - Data and conf directory on distribution
  distribution/server-x/src/main/content/bin/kc.sh
  distribution/server-x/src/main/content/conf/keycloak.properties
  quarkus/runtime/src/main/java/org/keycloak/provider/quarkus/KeycloakConfigSourceProvider.java
  quarkus/runtime/src/main/java/org/keycloak/provider/quarkus/KeycloakPropertiesConfigSource.java
Labels: Quarkus

#7143 [KEYCLOAK-11330] - SSL Support
  quarkus/runtime/src/main/java/org/keycloak/QuarkusKeycloakSessionFactory.java
  quarkus/runtime/src/main/java/org/keycloak/UserProviderLoader.java
  quarkus/runtime/src/main/java/org/keycloak/runtime/KeycloakRecorder.java
  testsuite/integration-arquillian/HOW-TO-RUN.md
  testsuite/integration-arquillian/servers/auth-server/quarkus/src/main/content/conf/client.jks
  testsuite/integration-arquillian/servers/auth-server/quarkus/src/main/content/conf/keycloak.jks
  testsuite/integration-arquillian/servers/auth-server/quarkus/src/main/content/conf/keycloak.properties
  testsuite/integration-arquillian/servers/auth-server/quarkus/src/main/content/conf/keycloak.truststore
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestApplicationResourceProvider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusConfiguration.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ServerInfoTest.java
  testsuite/integration-arquillian/tests/pom.xml
Labels: Quarkus

#7120 KEYCLOAK-14218 Fixes some missing localizations in admin console.
  themes/src/main/resources-community/theme/base/admin/messages/admin-messages_de.properties
  themes/src/main/resources/theme/base/admin/messages/admin-messages_en.properties
  themes/src/main/resources/theme/base/admin/resources/js/app.js
  themes/src/main/resources/theme/base/admin/resources/js/authz/authz-controller.js
  themes/src/main/resources/theme/base/admin/resources/js/controllers/groups.js
  themes/src/main/resources/theme/base/admin/resources/js/controllers/users.js
  themes/src/main/resources/theme/base/admin/resources/js/services.js
  themes/src/main/resources/theme/base/admin/resources/partials/client-initial-access.html
  themes/src/main/resources/theme/base/admin/resources/partials/realm-events-admin.html
  themes/src/main/resources/theme/base/admin/resources/partials/realm-events.html
  themes/src/main/resources/theme/base/admin/resources/partials/user-detail.html
Labels: Run UI Tests

#7156 [KEYCLOAK-11330] - Fixing build when using empty repository
  pom.xml
  quarkus/pom.xml
  quarkus/runtime/pom.xml
  quarkus/server/pom.xml
  testsuite/integration-arquillian/servers/auth-server/quarkus/pom.xml
Labels: Quarkus

#6877 Update user-credentials.html
  themes/src/main/resources/theme/base/admin/resources/partials/user-credentials.html
Labels: Missing JIRA

#7153 [KEYCLOAK-11330] - Quarkus clustering tests
  common/src/main/java/org/keycloak/common/util/Retry.java
  testsuite/integration-arquillian/HOW-TO-RUN.md
  testsuite/integration-arquillian/servers/auth-server/quarkus/assembly.xml
  testsuite/integration-arquillian/servers/auth-server/quarkus/pom.xml
  testsuite/integration-arquillian/servers/auth-server/quarkus/src/main/content/conf/cluster-ha.xml
  testsuite/integration-arquillian/servers/auth-server/quarkus/src/main/content/conf/cluster-local.xml
  testsuite/integration-arquillian/servers/auth-server/quarkus/src/main/content/conf/keycloak.properties
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusConfiguration.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cluster/AbstractClusterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cluster/AuthenticationSessionClusterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cluster/AuthenticationSessionFailoverClusterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cluster/ClientInvalidationClusterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cluster/GroupInvalidationClusterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cluster/RealmInvalidationClusterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cluster/RoleInvalidationClusterTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
  testsuite/integration-arquillian/tests/pom.xml
Labels: component/quarkus

#7147 KEYCLOAK-14370 Client selection shortcut
  themes/src/main/resources/theme/base/admin/resources/js/services.js
Labels: Run UI Tests

#7079 KEYCLOAK-14132 DefaultSecurityHeadersProvider should support 307 as r…
  services/src/main/java/org/keycloak/headers/DefaultSecurityHeadersProvider.java
Labels: area/server, component/core, impact/low, kind/bug

#7148 KEYCLOAK-14235 Support for running broker tests with different hostnames for auth server and IdP
  testsuite/integration-arquillian/HOW-TO-RUN.md
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginExpiredPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/UpdateAccountInformationPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/BrokerLinkAndTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/ClientInitiatedAccountLinkTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractAdvancedBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractFirstBrokerLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractIdentityProviderMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractInitializedBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractRoleMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractUserAttributeMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractUsernameTemplateMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AccountLinkTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/BrokerConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/BrokerTestTools.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/HardcodedUserAttributeMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/JsonUserAttributeMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOIDCBrokerWithSignatureTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerAcrParameterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerClientSecretBasicAuthTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerClientSecretJwtTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerFrontendUrlTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerHiddenIdpHintTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerIdpHintTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerLoginHintTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerLogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerNoLoginHintTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerNonceParameterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerParameterForwardTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerPrivateKeyJwtTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerPromptNoneRedirectTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerPromptParameterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerSubMatchIntrospectionest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerUiLocalesDisabledTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerUiLocalesEnabledTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerVaultConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerWithConsentTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcFirstBrokerLoginNewAuthTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcFirstBrokerLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlBrokerAllowedClockSkewTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlBrokerConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlBrokerSessionNotOnOrAfterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlSignedBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlSignedDocumentOnlyBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/saml/AbstractSamlTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
  testsuite/integration-arquillian/tests/base/src/test/resources/firefox-cookies-prefs.js
  testsuite/integration-arquillian/tests/pom.xml
Labels: area/testsuite, impact/medium, priority/critical

#7169 KEYCLOAK-14476 revert location change of base64url.js
  themes/src/main/resources/theme/base/login/webauthn-authenticate.ftl
  themes/src/main/resources/theme/base/login/webauthn-register.ftl
Labels: area/ui, component/themes, impact/medium, kind/bug, priority/important

#7172 KEYCLOAK-14490: Use snowpack optimze flag
  themes/src/main/resources/theme/keycloak-preview/account/src/package.json
Labels: Run UI Tests, area/ui, impact/medium, kind/enhancement, status/in-review

#7146 [KEYCLOAK-13202] Reset password redirects to account client
  services/src/main/java/org/keycloak/protocol/oidc/utils/RedirectUtils.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/BrowserTabUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
Labels: area/authentication, impact/medium, kind/bug, status/in-review

#7178 KEYCLOAK-14497 Compilation error in UsernameTemplateMapperTest
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/UsernameTemplateMapperTest.java
Labels: area/testsuite, impact/medium, kind/bug, priority/critical

#7171 [KEYCLOAK-11330] - Quarkus GitHub Actions
  .github/workflows/ci-x.yml
Labels: area/server, component/quarkus, impact/medium, priority/important

#6953 KEYCLOAK-13029 kcadm composite role creation fails
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/util/HttpUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmSessionTest.java
Labels: kind/bug

#7185 [KEYCLOAK-14482] Fixed rendering for "Resources shared with me" on missing baseUri
  themes/src/main/resources/theme/base/account/resources.ftl
Labels: area/authorization, kind/bug

#7181 KEYCLOAK-14507: Fix typos in es locales
  themes/src/main/resources-community/theme/base/admin/messages/admin-messages_es.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
Labels: area/ui, component/translations, impact/low, kind/bug, missing/jira, priority/critical

#7182 KEYCLOAK-14499 added toggle menu back on welcome screen
  themes/src/main/resources/theme/keycloak-preview/account/index.ftl
  themes/src/main/resources/theme/keycloak-preview/account/resources/welcome-page-scripts.js
Labels: area/ui, component/themes, kind/bug, priority/critical

#7168 KEYCLOAK-14496 Use KeycloakAdapter interface for 'adapter' option
  adapters/oidc/js/src/main/resources/keycloak.d.ts
Labels: priority/critical

#7163 KEYCLOAK-13978 onTokenExpired + onAuthRefreshError
  themes/src/main/resources/theme/keycloak-preview/account/src/app/App.tsx
  themes/src/main/resources/theme/keycloak-preview/account/src/app/Main.tsx
  themes/src/main/resources/theme/keycloak-preview/account/src/app/account-service/AccountServiceContext.tsx
  themes/src/main/resources/theme/keycloak-preview/account/src/app/account-service/account.service.ts
  themes/src/main/resources/theme/keycloak-preview/account/src/app/content/account-page/AccountPage.tsx
  themes/src/main/resources/theme/keycloak-preview/account/src/app/content/aia-page/AppInitiatedActionPage.tsx
  themes/src/main/resources/theme/keycloak-preview/account/src/app/content/applications-page/ApplicationsPage.tsx
  themes/src/main/resources/theme/keycloak-preview/account/src/app/content/device-activity-page/DeviceActivityPage.tsx
  themes/src/main/resources/theme/keycloak-preview/account/src/app/content/linked-accounts-page/LinkedAccountsPage.tsx
  themes/src/main/resources/theme/keycloak-preview/account/src/app/content/my-resources-page/EditTheResource.tsx
  themes/src/main/resources/theme/keycloak-preview/account/src/app/content/my-resources-page/MyResourcesPage.tsx
  themes/src/main/resources/theme/keycloak-preview/account/src/app/content/my-resources-page/PermissionRequest.tsx
  themes/src/main/resources/theme/keycloak-preview/account/src/app/content/my-resources-page/ResourcesTable.tsx
  themes/src/main/resources/theme/keycloak-preview/account/src/app/content/my-resources-page/ShareTheResource.tsx
  themes/src/main/resources/theme/keycloak-preview/account/src/app/content/signingin-page/SigningInPage.tsx
  themes/src/main/resources/theme/keycloak-preview/account/src/app/keycloak-service/KeycloakContext.tsx
  themes/src/main/resources/theme/keycloak-preview/account/src/app/keycloak-service/keycloak.service.ts
  themes/src/main/resources/theme/keycloak-preview/account/src/app/util/AIACommand.ts
  themes/src/main/resources/theme/keycloak-preview/account/src/app/widgets/Logout.tsx
Labels: Run UI Tests

#7092 KEYCLOAK-14156 - Passive authentication emits incomplete LOGIN event
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
Labels: area/authentication, component/core, impact/low, kind/bug

#7166 KEYCLOAK-13205 Apply locale resolution strategy to admin console.
  services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminConsoleWhoAmILocaleTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/RealmBuilder.java
  themes/src/main/resources/theme/base/admin/resources/js/app.js
Labels: Run UI Tests, area/ui, component/translations, impact/low, kind/bug

#7064 KEYCLOAK-14113 Support for exchanging to SAML 2.0 token
  core/src/main/java/org/keycloak/OAuth2Constants.java
  saml-core/src/main/java/org/keycloak/saml/common/util/DocumentUtil.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientTokenExchangeSAML2Test.java
Labels: area/oidc, component/token-exchange, kind/feature, missing/docs, status/in-review

#7191 KEYCLOAK-14516 app-server-eap6 tests fails due to compilation error
  testsuite/integration-arquillian/tests/base/pom.xml
Labels: area/adapters, impact/low, kind/bug, priority/important

#7145 KEYCLOAK-14394 Update to WebAuthn4J 0.12.0.RELEASE
  distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/licenses.xml
  distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/licenses.xml
  pom.xml
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnRegister.java
  services/src/main/java/org/keycloak/credential/WebAuthnCredentialProvider.java
Labels: area/authentication, impact/medium, kind/enhancement, status/in-review

#7158 KEYCLOAK-14129 0 downtime upgrade test - eap
  testsuite/integration-arquillian/servers/auth-server/jboss/legacy/pom.xml
  testsuite/integration-arquillian/servers/auth-server/jboss/pom.xml
Labels: area/testsuite, impact/medium, kind/enhancement

#7183 [KEYCLOAK-11330] - Clustering tests for GA
  .github/workflows/ci-x.yml
  lsp/conf/properties.json
  testsuite/integration-arquillian/servers/auth-server/pom.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
Labels: area/testsuite, component/quarkus

#7080 KEYCLOAK-14536 UserModel preparation for UserProfile
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/FullNameLDAPStorageMapper.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/UserAttributeLDAPStorageMapper.java
  federation/sssd/src/main/java/org/keycloak/federation/sssd/ReadonlySSSDUserModelDelegate.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedUser.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/UserAdapter.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi-private/src/main/java/org/keycloak/storage/adapter/InMemoryUserAdapter.java
  server-spi/src/main/java/org/keycloak/models/UserModel.java
  server-spi/src/main/java/org/keycloak/models/UserModelDefaultMethods.java
  server-spi/src/main/java/org/keycloak/storage/adapter/AbstractUserAdapter.java
  server-spi/src/main/java/org/keycloak/storage/adapter/AbstractUserAdapterFederatedStorage.java
  services/src/main/java/org/keycloak/authentication/authenticators/broker/util/SerializedBrokeredIdentityContext.java
  services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  services/src/main/java/org/keycloak/theme/FreeMarkerUtil.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/FailableHardcodedStorageProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/util/LDAPTestUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/PolicyEvaluationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPBinaryAttributesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPLegacyImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPProvidersIntegrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserModelTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/model/testrealm.json
  testsuite/utils/src/main/java/org/keycloak/testsuite/util/cli/LdapManyObjectsInitializerCommand.java
Labels: area/server, component/core, impact/high, kind/feature, missing/docs, status/in-review

#7199 KEYCLOAK-13981 use a dropdown on smaller devices
  themes/src/main/resources/theme/keycloak-preview/account/src/app/content/signingin-page/SigningInPage.tsx
Labels: Run UI Tests, area/ui

#7198 KEYCLOAK-6304: Czech translation
  themes/src/main/resources-community/theme/base/account/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/account/theme.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/email/theme.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/login/theme.properties
  themes/src/main/resources/theme/base/account/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: area/ui, component/translations, impact/low, kind/enhancement, status/in-review

#7206 [KEYCLOAK-14344] Cannot revoke offline access for an app if the app d…
  services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/ApplicationsTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/page/ApplicationsPage.java
  themes/src/main/resources/theme/keycloak-preview/account/src/app/content/applications-page/ApplicationsPage.tsx
Labels: Run UI Tests, area/ui, missing/tests

#7208 KEYCLOAK-14584: Client w/ empty str as Base URL displayed in NAC
  services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
Labels: Run UI Tests, area/ui

#7209 KEYCLOAK-14585: effectiveUrl wrongly formatted
  themes/src/main/resources/theme/keycloak-preview/account/src/app/content/applications-page/ApplicationsPage.tsx
Labels: area/ui
