Repository keycloak/keycloak, pull requests merged in 2020-02, with the labels that each got.

#6613 [KEYCLOAK-9600] - Find by name in authz client returning wrong resource
  authz/client/src/main/java/org/keycloak/authorization/client/resource/ProtectedResource.java
  model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAResourceStore.java
  server-spi-private/src/main/java/org/keycloak/authorization/model/Resource.java
  services/src/main/java/org/keycloak/authorization/admin/ResourceSetService.java
  services/src/main/java/org/keycloak/authorization/protection/resource/ResourceService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/AuthzClientCredentialsTest.java
Labels: Bug fix, Prioritize

#6629 [KEYCLOAK-9666] - Entitlement request with service account results in server error
  authz/client/src/main/java/org/keycloak/authorization/client/resource/AuthorizationResource.java
  services/src/main/java/org/keycloak/authorization/authorization/AuthorizationTokenService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/EntitlementAPITest.java
Labels: Bug fix, Prioritize

#6140 [KEYCLOAK-10735] implement search and filter for count endpoint
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/UsersResource.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/UserEntity.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/UserGroupMembershipEntity.java
  server-spi/src/main/java/org/keycloak/storage/user/UserQueryProvider.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
  services/src/main/java/org/keycloak/storage/UserStorageManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UsersTest.java
Labels: Prioritize

#6668 KEYCLOAK-12340 KEYCLOAK-12386 Regression in credential handling when …
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/UserResource.java
  server-spi/src/main/java/org/keycloak/models/UserCredentialManager.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/OTPFormAuthenticator.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateTotp.java
  services/src/main/java/org/keycloak/credential/OTPCredentialProvider.java
  services/src/main/java/org/keycloak/credential/UserCredentialStoreManager.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/DummyUserFederationProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/AbstractLDAPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPProvidersIntegrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageOTPTest.java
  themes/src/main/resources/theme/base/admin/messages/admin-messages_en.properties
  themes/src/main/resources/theme/base/admin/resources/js/controllers/users.js
  themes/src/main/resources/theme/base/admin/resources/js/services.js
  themes/src/main/resources/theme/base/admin/resources/partials/user-credentials.html
Labels: Prioritize

#6709 [KEYCLOAK-12168] Various setup TOTP screen usability improvements
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateTotp.java
  services/src/main/java/org/keycloak/forms/login/freemarker/model/TotpBean.java
  services/src/main/java/org/keycloak/services/messages/Messages.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/KcinitTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetCredentialsAlternativeFlowsTest.java
  themes/src/main/resources/theme/base/account/messages/messages_en.properties
  themes/src/main/resources/theme/base/account/totp.ftl
  themes/src/main/resources/theme/base/login/login-config-totp.ftl
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/template.ftl
  themes/src/main/resources/theme/keycloak/login/resources/css/login.css
Labels: Prioritize

#6684 KEYCLOAK-12693 Upgrade to zxing 3.4.0
  distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/com.google.zxing,core,3.4.0,Apache Software License 2.0.txt
  distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/com.google.zxing,javase,3.4.0,Apache Software License 2.0.txt
  distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/licenses.xml
  distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/com.google.zxing,core,3.4.0.redhat-00001,Apache Software License 2.0.txt
  distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/com.google.zxing,javase,3.4.0.redhat-00001,Apache Software License 2.0.txt
  distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/licenses.xml
  pom.xml
Labels: Prioritize

#6710 KEYCLOAK-12177 KEYCLOAK-12178 WebAuthn: Improve usability
  server-spi-private/src/main/java/org/keycloak/forms/login/LoginFormsPages.java
  server-spi-private/src/main/java/org/keycloak/forms/login/LoginFormsProvider.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/WebAuthnAuthenticator.java
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnRegister.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/forms/login/freemarker/Templates.java
  services/src/main/java/org/keycloak/services/messages/Messages.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/webauthn/WebAuthnErrorPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/webauthn/WebAuthnLoginPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnRegisterAndLoginTest.java
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/template.ftl
  themes/src/main/resources/theme/base/login/webauthn-authenticate.ftl
  themes/src/main/resources/theme/base/login/webauthn-error.ftl
  themes/src/main/resources/theme/base/login/webauthn-register.ftl
  themes/src/main/resources/theme/keycloak/login/theme.properties
Labels: Prioritize

#6661 KEYCLOAK-12654: Data to sign is incorrect in redirect binding when URI has parameters
  saml-core/src/main/java/org/keycloak/saml/BaseSAML2BindingBuilder.java
  services/src/main/java/org/keycloak/protocol/saml/SamlProtocolUtils.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/SamlClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/saml/SamlRedirectBindingTest.java
Labels: Bug fix

#6714 KEYCLOAK-12877 Fix ModelVersion for testing pipeline
  server-spi-private/src/main/java/org/keycloak/migration/ModelVersion.java
  server-spi-private/src/test/java/org/keycloak/models/MigrationVersionTest.java
Labels: Bug fix, Prioritize

#6680 KEYCLOAK-12692 Upgrade to twitter4j 4.0.7
  distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/licenses.xml
  distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/org.twitter4j,twitter4j-core,4.0.7,Apache Software License 2.0.txt
  distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/licenses.xml
  distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/org.twitter4j,twitter4j-core,4.0.7.redhat-00002,Apache Software License 2.0.txt
  pom.xml
Labels: Prioritize

#6338 Keycloak-11526 search and pagination for roles
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/RolesResource.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/ClientAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
  model/jpa/src/main/java/org/keycloak/models/jpa/ClientAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/RoleEntity.java
  server-spi-private/src/main/java/org/keycloak/storage/client/UnsupportedOperationsClientStorageAdapter.java
  server-spi/src/main/java/org/keycloak/models/RealmProvider.java
  server-spi/src/main/java/org/keycloak/models/RoleContainerModel.java
  services/src/main/java/org/keycloak/services/resources/admin/RoleContainerResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/ClientRolesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmRolesTest.java
  themes/src/main/resources/theme/base/admin/messages/admin-messages_en.properties
  themes/src/main/resources/theme/base/admin/resources/js/app.js
  themes/src/main/resources/theme/base/admin/resources/js/controllers/clients.js
  themes/src/main/resources/theme/base/admin/resources/js/controllers/realm.js
  themes/src/main/resources/theme/base/admin/resources/js/loaders.js
  themes/src/main/resources/theme/base/admin/resources/js/services.js
  themes/src/main/resources/theme/base/admin/resources/partials/client-role-list.html
  themes/src/main/resources/theme/base/admin/resources/partials/role-list.html
Labels: Prioritize

#6733 [KEYCLOAK-12897] - Policy enforcer should just deny when bearer is invalid
  adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/authorization/KeycloakAdapterPolicyEnforcer.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/authorization/PolicyEnforcerTest.java
Labels: Bug fix

#6750 KEYCLOAK-12193 Internal error message returned in error response
  services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/error/UncaughtErrorPageTest.java
Labels: Bug fix, Prioritize

#6766 KEYCLOAK-9563 Improve access token checks for userinfo endpoint
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/UserInfoEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/UserInfoTest.java
Labels: Bug fix

#6722 KEYCLOAK-10931 Trigger UPDATE_PASSWORD event on password update via AccountCredentialResource
  services/src/main/java/org/keycloak/services/resources/account/AccountCredentialResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
Labels: Bug fix

#6739 KEYCLOAK-12821 Check if action is disabled in realm before executing
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionTotpSetupTest.java
Labels: Bug fix

#6730 Keycloak 12186 Improve the OTP login form
  server-spi-private/src/main/java/org/keycloak/events/Details.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/OTPFormAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginTotpPage.java
  themes/src/main/resources/theme/base/login/login-otp.ftl
  themes/src/main/resources/theme/keycloak/login/resources/css/login.css
  themes/src/main/resources/theme/keycloak/login/theme.properties
Labels: Prioritize

#6607 [KEYCLOAK-8049] - Prevent users from not choosing a group
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/group/GroupPolicyProviderFactory.java
  testsuite/integration-arquillian/tests/other/console/src/test/java/org/keycloak/testsuite/console/authorization/GroupPolicyManagementTest.java
  themes/src/main/resources/theme/base/admin/resources/js/authz/authz-controller.js
Labels: Bug fix

#6737 [KEYCLOAK-12864] - OIDCIdentityProvider with Reverse Proxy
  services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
  testsuite/integration-arquillian/servers/auth-server/undertow/src/main/java/org/keycloak/testsuite/arquillian/undertow/lb/SimpleUndertowLoadBalancer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/AuthServerTestEnricher.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerFrontendUrlTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ReverseProxy.java
Labels: Bug fix

#6782 KEYCLOAK-12993 AuthorizationBean invokes ResolveRelative.resolveRelat…
  services/src/main/java/org/keycloak/forms/account/freemarker/model/AuthorizationBean.java
Labels: Bug fix, Prioritize

#6743 KEYCLOAK-9632 Improve handling of user locale
  adapters/oidc/js/src/main/resources/keycloak.d.ts
  adapters/oidc/js/src/main/resources/keycloak.js
  server-spi-private/src/main/java/org/keycloak/migration/migrators/MigrateTo9_0_0.java
  server-spi-private/src/main/java/org/keycloak/models/utils/DefaultRequiredActions.java
  server-spi/src/main/java/org/keycloak/locale/LocaleSelectorProvider.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateUserLocaleAction.java
  services/src/main/java/org/keycloak/locale/DefaultLocaleSelectorProvider.java
  services/src/main/java/org/keycloak/locale/LocaleNegotiator.java
  services/src/main/java/org/keycloak/locale/LocaleSelection.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthorizationEndpointRequest.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthzEndpointRequestParser.java
  services/src/main/java/org/keycloak/services/DefaultKeycloakContext.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  services/src/main/java/org/keycloak/services/resources/account/AccountFormService.java
  services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java
  services/src/main/resources/META-INF/services/org.keycloak.authentication.RequiredActionFactory
  services/src/test/java/org/keycloak/locale/LocaleNegotiatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/RequiredActionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/EmailTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/LoginPageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  themes/src/main/resources/theme/keycloak-preview/account/index.ftl
Labels: Bug fix

#6776 KEYCLOAK-12860 KEYCLOAK-12875 Fix for Account REST Credentials to wor…
  server-spi-private/src/main/java/org/keycloak/authentication/AuthenticationSelectionOption.java
  server-spi/src/main/java/org/keycloak/credential/CredentialProvider.java
  server-spi/src/main/java/org/keycloak/credential/CredentialTypeMetadata.java
  server-spi/src/main/java/org/keycloak/credential/CredentialTypeMetadataContext.java
  services/src/main/java/org/keycloak/credential/OTPCredentialProvider.java
  services/src/main/java/org/keycloak/credential/PasswordCredentialProvider.java
  services/src/main/java/org/keycloak/credential/WebAuthnCredentialProvider.java
  services/src/main/java/org/keycloak/credential/WebAuthnPasswordlessCredentialProvider.java
  services/src/main/java/org/keycloak/services/resources/account/AccountCredentialResource.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/resources/org/keycloak/testsuite/integration-arquillian-testsuite-providers/main/module.xml
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPAccountRestApiTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/SigningInTest.java
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
  themes/src/main/resources/theme/keycloak-preview/account/messages/messages_en.properties
Labels: Bug fix

#6761 [KEYCLOAK-10696] - fixed missing client role attributes after import
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/testrealm.json
Labels: Bug fix, Prioritize

#6788 KEYCLOAK-12960 Use Long for time based values in JsonWebToken
  core/src/main/java/org/keycloak/representations/IDToken.java
  core/src/main/java/org/keycloak/representations/JsonWebToken.java
  services/src/main/java/org/keycloak/authentication/actiontoken/DefaultActionTokenKey.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenIntrospectionTest.java
Labels: Docs

#6780 KEYCLOAK-12958 Preview feature profile for WebAuthn
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
  server-spi-private/src/main/java/org/keycloak/authentication/AuthenticatorSpi.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/WebAuthnAuthenticatorFactory.java
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnRegisterFactory.java
  services/src/main/java/org/keycloak/credential/WebAuthnCredentialProviderFactory.java
  services/src/main/java/org/keycloak/credential/WebAuthnPasswordlessCredentialProviderFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/util/FeatureDeployerUtil.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/annotation/DisableFeature.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/annotation/EnableFeature.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakContainerFeaturesController.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/ExecutionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/ProvidersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/RequiredActionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BrowserFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultiFactorAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/openshift/OpenShiftTokenReviewEndpointTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/openshift/OpenshiftClientStorageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnRegisterAndLoginTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/SigningInTest.java
  themes/src/main/resources/theme/base/admin/resources/js/app.js
  themes/src/main/resources/theme/base/admin/resources/js/controllers/realm.js
  themes/src/main/resources/theme/base/admin/resources/partials/webauthn-policy-passwordless.html
  themes/src/main/resources/theme/base/admin/resources/partials/webauthn-policy.html
  themes/src/main/resources/theme/base/admin/resources/templates/kc-tabs-authentication.html
Labels: Missing Docs

#6660 KEYCLOAK-12689 - Improvements for camelCase config properties
  quarkus/extensions/pom.xml
  quarkus/extensions/src/main/java/org/keycloak/provider/quarkus/MicroProfileConfigProvider.java
  quarkus/extensions/src/test/java/org/keycloak/provider/quarkus/MicroProfileConfigProviderTest.java
  quarkus/pom.xml
Labels: Missing Tests

#6723 KEYCLOAK-7961 Avoid sending back-channel logout requests to disabled clients
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/managers/ResourceAdminManager.java
Labels: Bug fix, Missing Tests

#6719 KEYCLOAK-10953 Avoid NPE when Updating Clients via Admin REST API
  services/src/main/java/org/keycloak/services/resources/admin/ClientResource.java
Labels: Bug fix, Missing Tests
