Repository keycloak/keycloak, pull requests merged in 2020-04, with the labels that each got.

#6950 [KEYCLOAK-7450] - Match subject when validating id_token returned from external OP
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/UserInfoEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractPairwiseSubMapper.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/UserInfoClientUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerSubMatchIntrospectionest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/UserInfoTest.java
Labels: Bug fix

#6947 [KEYCLOAK-8789] Fix getAttribute(String name) implementations so they…
  server-spi/src/main/java/org/keycloak/storage/adapter/AbstractUserAdapter.java
  server-spi/src/main/java/org/keycloak/storage/adapter/AbstractUserAdapterFederatedStorage.java
Labels: Bug fix

#6976 KEYCLOAK-13285 Enable check identity for email
  services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/ssl/TrustStoreEmailTest.java
Labels: Bug fix

#6956 KEYCLOAK-13303 NPE importing realm if authenticatorConfig has null alias
  server-spi-private/src/main/java/org/keycloak/migration/MigrationModelManager.java
  server-spi-private/src/main/java/org/keycloak/migration/migrators/MigrateTo9_0_4.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
Labels: Bug fix

#6955 [KEYCLOAK-13589] - Can't add user in admin console when 'Email as username' is enabled
  testsuite/integration-arquillian/tests/other/console/src/main/java/org/keycloak/testsuite/console/page/users/UserAttributesForm.java
  testsuite/integration-arquillian/tests/other/console/src/test/java/org/keycloak/testsuite/console/users/UserAttributesTest.java
  themes/src/main/resources/theme/base/admin/resources/partials/user-detail.html
Labels: Bug fix

#6945 KEYCLOAK-12934 LOAD_ROLES_BY_MEMBER_ATTRIBUTE_RECURSIVELY user roles …
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapperFactory.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/role/RoleLDAPStorageMapperFactory.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ComponentResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserStorageRestTest.java
Labels: Bug fix

#6948 KEYCLOAK-13635: Can't make mapper with certain chars
  themes/src/main/resources/theme/base/admin/resources/js/app.js
  themes/src/main/resources/theme/base/admin/resources/templates/kc-provider-config.html
Labels: Bug fix

#6881 [KEYCLOAK-13187] - Concurrency issue when refreshing tokens and updating security context state
  adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/RefreshableKeycloakSecurityContext.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/adapter/page/TokenRefreshPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/DemoServletsAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/demorealm.json
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/token-refresh/META-INF/context.xml
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/token-refresh/WEB-INF/jetty-web.xml
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/token-refresh/WEB-INF/keycloak.json
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/token-refresh/WEB-INF/web.xml
Labels: Bug fix

#6940 KEYCLOAK-13247 NPE during migration when manage-account role missing
  server-spi-private/src/main/java/org/keycloak/migration/migrators/MigrateTo9_0_0.java
Labels: Bug fix

#6972 KEYCLOAK-10852 Inconsistency when using 'forgot password' after chang…
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  services/src/main/java/org/keycloak/storage/UserStorageManager.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/resources/org/keycloak/testsuite/integration-arquillian-testsuite-providers/main/module.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/MailUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPNoCacheTest.java
Labels: Bug fix

#6979 KEYCLOAK-13306 Model fixes for check realm when lookup by ID
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/OwnerReplacementTest.java
Labels: Bug fix

#6961 KEYCLOAK-13714 Add missing type definition for logout options
  adapters/oidc/js/src/main/resources/keycloak.d.ts
Labels: Bug fix

#6959 KEYCLOAK-12842 Not possible to update user with multivalued LDAP RDN
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/model/LDAPDn.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/model/LDAPObject.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPIdentityStore.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPOperationManager.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/MembershipType.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/UserRolesRetrieveStrategy.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapper.java
  federation/ldap/src/test/java/org/keycloak/storage/ldap/idm/model/LDAPDnTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPNoMSADTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPSyncTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LdapUsernameAttributeTest.java
Labels: Bug fix

#6943 [KEYCLOAK-8071] - Properly validating requested scopes
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthGrantTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthScopeInTokenResponseTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCScopeTest.java
Labels: Bug fix

#6939 [KEYCLOAK-13586] Fix typos related to QueryParamterTokenRequestAuthenticator
  adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/QueryParameterTokenRequestAuthenticator.java
  adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/RequestAuthenticator.java
Labels: Bug fix

#6720 KEYCLOAK-11003 Remove UPDATE_PASSWORD RequiredAction on non-temporary password reset
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/admin/ApiUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BrowserButtonsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultipleTabsLoginTest.java
Labels: Bug fix

#6993 KEYCLOAK-13922 MigrationModelTest failing in latest master
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/MigrationModelTest.java
Labels: Bug fix

#6977 KEYCLOAK-9623 Disabling logged in user will not allow other user to l…
  services/src/main/java/org/keycloak/protocol/AuthorizationEndpointBase.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java
Labels: Bug fix

#6954 [KEYCLOAK-11317] - IDP review profile allows empty username
  services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpReviewProfileAuthenticator.java
  services/src/main/java/org/keycloak/services/validation/Validation.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcFirstBrokerLoginTest.java
Labels: Bug fix

#7000 [KEYCLOAK-9896] - Authorization Scope modified improperly when updating Resource
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/authorization/ScopeManagementTest.java
Labels: Bug fix

#6958 [KEYCLOAK-13656] - Deny request if requested scope is not associated to resource or any typed resources
  services/src/main/java/org/keycloak/authorization/authorization/AuthorizationTokenService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/authorization/PolicyEnforcerTest.java
Labels: Bug fix

#6990 [KEYCLOAK-12097] Fix NPE when trying to obtain the cache container na…
  adapters/saml/as7-eap6/subsystem/src/main/java/org/keycloak/subsystem/saml/as7/KeycloakClusteredSsoDeploymentProcessor.java
  adapters/saml/wildfly/wildfly-subsystem/src/main/java/org/keycloak/subsystem/adapter/saml/extension/KeycloakClusteredSsoDeploymentProcessor.java
Labels: Bug fix

#6964 [KEYCLOAK-13005] Make sure the master URL is used if the consumer POS…
  services/src/main/java/org/keycloak/protocol/saml/SamlService.java
  services/src/main/java/org/keycloak/protocol/saml/installation/SamlSPDescriptorClientInstallation.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java
Labels: Bug fix

#7011 KEYCLOAK-13976 limit field length
  themes/src/main/resources/theme/keycloak-preview/account/resources/app/content/account-page/AccountPage.tsx
Labels: Run UI Tests

#6581 KEYCLOAK-12406 Add "Client Session Max" and "Client Session Idle" for…
  core/src/main/java/org/keycloak/representations/idm/RealmRepresentation.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedRealm.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/RealmAttributes.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  server-spi/src/main/java/org/keycloak/models/RealmModel.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCConfigAttributes.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/RealmBuilder.java
  themes/src/main/resources/theme/base/admin/messages/admin-messages_en.properties
  themes/src/main/resources/theme/base/admin/resources/js/controllers/clients.js
  themes/src/main/resources/theme/base/admin/resources/js/controllers/realm.js
  themes/src/main/resources/theme/base/admin/resources/partials/client-detail.html
  themes/src/main/resources/theme/base/admin/resources/partials/realm-tokens.html
Labels: Docs, Prioritize

#6951 [KEYCLOAK-13579] - Ignore exceptions when shutting down loopback server
  adapters/oidc/installed/src/main/java/org/keycloak/adapters/installed/KeycloakInstalled.java
Labels: Bug fix

#7025 KEYCLOAK-14007 Missing RHSSO 7.4 version in MigrationModelManager
  server-spi-private/src/main/java/org/keycloak/migration/MigrationModelManager.java
  server-spi-private/src/test/java/org/keycloak/models/MigrationVersionTest.java
Labels: Bug fix
