Repository keycloak/keycloak, pull requests merged in 2020-03, with the labels that each got.

#6781 KEYCLOAK-12695 Upgrade to openshift-restclient-java 8.0.0.Final
  distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/com.openshift,openshift-restclient-java,8.0.0.Final,Eclipse Public License 1.0.txt
  distribution/feature-packs/server-feature-pack/src/main/resources/licenses/keycloak/licenses.xml
  distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/com.openshift,openshift-restclient-java,8.0.0.Final-redhat-00001,Eclipse Public License 1.0.txt
  distribution/feature-packs/server-feature-pack/src/main/resources/licenses/rh-sso/licenses.xml
  pom.xml
Labels: Prioritize

#6665 KEYCLOAK-9346 Add new KeycloakPromise to support native promises
  adapters/oidc/js/src/main/resources/keycloak.d.ts
  adapters/oidc/js/src/main/resources/keycloak.js
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/javascript/JavascriptTestExecutor.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterWithNativePromisesTest.java
Labels: Docs

#6867 KEYCLOAK-10967 Add JSON body methods for test ldap and smtp connectio…
  core/src/main/java/org/keycloak/representations/idm/TestLdapConnectionRepresentation.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/RealmResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/SMTPConnectionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserFederationLdapConnectionTest.java
  themes/src/main/resources/theme/base/admin/resources/js/controllers/realm.js
  themes/src/main/resources/theme/base/admin/resources/js/controllers/users.js
  themes/src/main/resources/theme/base/admin/resources/js/services.js
Labels: Bug fix, Docs

#6849 KEYCLOAK-13163 Fixed searching for user with fine-grained permissions
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
  server-spi/src/main/java/org/keycloak/models/UserModel.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/UserMapStorage.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/UserPropertyFileStorage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/FineGrainAdminUnitTest.java
Labels: Bug fix

#6805 KEYCLOAK-10029 Offline token migration fix. Always test offline-token…
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/HOW-TO-RUN.md
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/migration/MigrationContext.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport198MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/migration-test/migration-realm-1.9.8.Final.json
  testsuite/integration-arquillian/tests/base/src/test/resources/migration-test/migration-realm-2.5.5.Final.json
  testsuite/integration-arquillian/tests/base/src/test/resources/migration-test/migration-realm-3.4.3.Final.json
  testsuite/integration-arquillian/tests/base/src/test/resources/migration-test/migration-realm-4.8.3.Final.json
Labels: Bug fix, Prioritize

#6896 KEYCLOAK-11412 Display more nice error message when creating top leve…
  services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java
Labels: Bug fix

#6898 [KEYCLOAK-11282] - Properly resolve config resolver
  adapters/oidc/spring-boot-adapter-core/src/main/java/org/keycloak/adapters/springboot/KeycloakBaseSpringBootConfiguration.java
  adapters/oidc/spring-boot-adapter-core/src/main/java/org/keycloak/adapters/springboot/KeycloakSpringBootConfigResolverWrapper.java
  adapters/oidc/spring-boot/src/main/java/org/keycloak/adapters/springboot/KeycloakAutoConfiguration.java
  adapters/oidc/spring-security/src/main/java/org/keycloak/adapters/springsecurity/config/KeycloakSpringConfigResolverWrapper.java
Labels: Bug fix

#6903 KEYCLOAK-5162 Add index to even table
  model/jpa/src/main/resources/META-INF/jpa-changelog-9.0.1.xml
  services/src/main/java/org/keycloak/services/resources/account/AccountFormService.java
Labels: Bug fix

#6842 KEYCLOAK-12768: Prevent reserved characters in URLs
  services/src/main/java/org/keycloak/services/managers/RealmManager.java
  services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientResource.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RoleContainerResource.java
  services/src/main/java/org/keycloak/utils/ReservedCharValidator.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/page/PatternFlyClosableAlert.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/AuthenticatorConfigTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/FlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/ClientRolesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java
  testsuite/integration-arquillian/tests/other/console/src/test/java/org/keycloak/testsuite/console/AbstractConsoleTest.java
  testsuite/integration-arquillian/tests/other/console/src/test/java/org/keycloak/testsuite/console/roles/RealmRolesTest.java
  themes/src/main/resources/theme/base/admin/messages/admin-messages_en.properties
  themes/src/main/resources/theme/base/admin/resources/js/app.js
  themes/src/main/resources/theme/base/admin/resources/partials/authenticator-config.html
  themes/src/main/resources/theme/base/admin/resources/partials/client-clustering-node.html
  themes/src/main/resources/theme/base/admin/resources/partials/client-role-detail.html
  themes/src/main/resources/theme/base/admin/resources/partials/create-flow.html
  themes/src/main/resources/theme/base/admin/resources/partials/realm-create.html
  themes/src/main/resources/theme/base/admin/resources/partials/realm-detail.html
  themes/src/main/resources/theme/base/admin/resources/partials/realm-identity-provider-oidc.html
  themes/src/main/resources/theme/base/admin/resources/partials/realm-identity-provider-saml.html
  themes/src/main/resources/theme/base/admin/resources/partials/role-detail.html
  themes/src/main/resources/theme/base/admin/resources/templates/kc-provider-config.html
Labels: Bug fix

#6902 KEYCLOAK-13249 jpa-changelog-8.0.0.xml contains whitespace character
  model/jpa/src/main/resources/META-INF/jpa-changelog-8.0.0.xml
Labels: Bug fix

#6313 KEYCLOAK-4923: Client Service Account Roles are not exported
  services/src/main/java/org/keycloak/exportimport/util/ExportOptions.java
  services/src/main/java/org/keycloak/exportimport/util/ExportUtils.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/partialexport/PartialExportTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/export/partialexport-testrealm.json
Labels: Bug fix, Prioritize

#6889 [KEYCLOAK-13273] - Remove group policy when group is removed
  server-spi-private/src/main/java/org/keycloak/authorization/store/AuthorizationStoreFactory.java
  server-spi-private/src/main/java/org/keycloak/authorization/store/syncronization/GroupSynchronizer.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/authorization/GroupPolicyManagementTest.java
Labels: Bug fix

#6912 KEYCLOAK-13369 Not possible to move groups in admin console
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/events/GroupAddedEvent.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cluster/GroupInvalidationClusterTest.java
Labels: Bug fix

#6915 [KEYCLOAK-13385] - Better message when saving a provider with invalid URLs
  common/src/main/java/org/keycloak/common/util/UriUtils.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProviderResource.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
Labels: Bug fix

#6921 KEYCLOAK-13384 exclude IdentityProviderTest.failCreateInvalidUrl from…
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
Labels: Bug fix

#6935 KEYCLOAK-13397 Creating role-ldap-mapper for realm-management client …
  themes/src/main/resources/theme/base/admin/resources/js/app.js
  themes/src/main/resources/theme/base/admin/resources/templates/kc-component-config.html
  themes/src/main/resources/theme/base/admin/resources/templates/kc-provider-config.html
Labels: Bug fix

#6919 KEYCLOAK-13383 WebAuthnRegisterAndLoginTest fails with -Dproduct with…
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnFeatureTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnRegisterAndLoginTest.java
Labels: Bug fix

#6937 KEYCLOAK-13442 Backwards compatibility in users searching. searchForU…
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/UserEntity.java
  services/src/main/java/org/keycloak/storage/UserStorageManager.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/BackwardsCompatibilityUserStorage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/BackwardsCompatibilityUserStorageTest.java
Labels: Bug fix

#6938 KEYCLOAK-13339 NPE when removing credentials and user cache is disabled
  services/src/main/java/org/keycloak/credential/UserCredentialStoreManager.java
Labels: Bug fix
