Repository keycloak/keycloak, pull requests merged in 2021-08, with the labels that each got.

#8155 [KEYCLOAK-18419] Support SAML 2.0 Encrypted IDs in Assertion
  saml-core/src/main/java/org/keycloak/saml/processing/core/saml/v2/util/AssertionUtil.java
  saml-core/src/test/java/org/keycloak/saml/processing/core/parsers/saml/SAMLParserTest.java
  saml-core/src/test/java/org/keycloak/saml/processing/core/saml/v2/util/AssertionUtilTest.java
  saml-core/src/test/resources/org/keycloak/saml/processing/core/parsers/saml/saml20-encrypted-id-response.xml
  services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlEncryptedIdTest.java
Labels: area/saml, kind/enhancement, status/ready

#8181 [KEYCLOAK-18498] French i18n contains wrong param
  themes/src/main/resources-community/theme/base/email/messages/messages_fr.properties
Labels: component/translations, status/ready

#8337 KEYCLOAK-18949
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/DirectGrantFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/FlowUtil.java
  testsuite/utils/src/main/resources/log4j.properties
Labels: area/authentication, kind/bug, status/in-review

#8338 KEYCLOAK-18509 Fix permission error when deleting client
  server-spi-private/src/main/java/org/keycloak/authorization/store/syncronization/ClientApplicationSynchronizer.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UserManagedPermissionServiceTest.java
Labels: missing/tests, area/authorization, kind/bug

#7892 KEYCLOAK-16633 Prevent deletion of internal clients.
  services/src/main/java/org/keycloak/services/managers/ClientManager.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ClientTest.java
Labels: kind/bug, status/in-review

#8316 KEYCLOAK-18974 BitbucketIdentityProvider IdentityBrokerException message
  services/src/main/java/org/keycloak/social/bitbucket/BitbucketIdentityProvider.java
Labels: missing/tests, area/oidc, kind/bug

#8363 KEYCLOAK-19036 Avoid infinite loop during LDAP sync with OpenLDAP and olcSizeLimit
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPOperationManager.java
Labels: area/user-federation
