Repository keycloak/keycloak, pull requests merged in 2022-11, with the labels that each got.

#15215 Allow a partial import to overwrite the default role
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
  services/src/main/java/org/keycloak/partialimport/RolesPartialImport.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/partialimport/PartialImportTest.java
Labels: status/ready, area/storage, team/storage-sig

#15115 Remove unnecessary lookup of an entity via the session
  model/map/src/main/java/org/keycloak/models/map/client/MapClientProvider.java
Labels: status/ready, area/storage

#15185 Limit CI timeout for base and model testsuites
  .github/workflows/ci.yml
Labels: kind/enhancement, area/ci

#14926 Run map-jpa model tests profile in GHA
  testsuite/model/README.md
  testsuite/model/pom.xml
  testsuite/model/src/test/java/org/keycloak/testsuite/model/authz/ConcurrentAuthzTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/JpaMapStorage.java
  testsuite/model/test-all-profiles.sh
Labels: area/storage, team/storage-sig

#15316 Allow a partial import to overwrite the default role
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
  services/src/main/java/org/keycloak/partialimport/RolesPartialImport.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/partialimport/PartialImportTest.java
Labels: area/storage, team/storage-sig

#15350 Fix Infinispan adapter not checking updated value in getAttribute met…
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/GroupAdapter.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/group/GroupModelTest.java
Labels: area/storage, team/storage-sig

#15367 Ignore test until the intermittent failure from #14917 is resolved
  testsuite/model/src/test/java/org/keycloak/testsuite/model/authz/ConcurrentAuthzTest.java
Labels: area/storage, team/storage-sig

#12600 Returns an empty groups stream without querying the database if a user doesn't belong to any groups
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java
Labels: area/storage, team/storage-sig

#15147 Use JSONB '->>' function to avoid unnecessary JSON conversion in crit…
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/client/JpaClientModelCriteriaBuilder.java
Labels: area/storage, team/storage-sig

#15131 Fix ConcurrentLoginTest.concurrentCodeReuseShouldFail on CockroachDB
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
Labels: area/storage, team/storage-sig

#15401 Use DELETE statement instead of deleting one by one for HotRod store
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/HotRodMapStorage.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/ClientModelTest.java
Labels: area/storage, team/storage-sig

#15455 Add missing JDBC driver configuration for MS SQL Server
  docs/guides/src/main/server/db.adoc
Labels: status/ready, area/storage, team/storage-sig

#15495 Backport fixes from profile refactor
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolFactory.java
  services/src/main/java/org/keycloak/services/migration/DefaultMigrationProvider.java
Labels: kind/bug, area/core

#15463 Fix performance issues with many offline sessions
  model/jpa/src/main/java/org/keycloak/models/jpa/session/JpaUserSessionPersisterProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/session/PersistentClientSessionEntity.java
Labels: kind/bug, area/storage

#15466 Upgrade Liquibase to version 4.16.1
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/log/KeycloakLogger.java
  pom.xml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/liquibase/KeycloakLogger.java
Labels: area/storage, team/storage-sig

#14925 Update Infinispan version to 14.0.2.Final
  model/infinispan/src/main/resources/default-configs/default-keycloak-jgroups-udp.xml
  model/infinispan/src/test/java/org/keycloak/models/sessions/infinispan/initializer/DistributedCacheConcurrentWritesTest.java
  model/infinispan/src/test/java/org/keycloak/models/sessions/infinispan/initializer/DistributedCacheWriteSkewTest.java
  model/map-hot-rod/pom.xml
  pom.xml
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java
  quarkus/tests/integration/src/test/resources/cache-ispn-asym-enc.xml
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/resource/TestCacheResource.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/client/resources/TestingCacheResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cluster/ConcurrentLoginClusterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
  testsuite/model/src/main/resources/hotrod/hotrod1.xml
  testsuite/model/src/main/resources/hotrod/hotrod2.xml
Labels: area/storage, team/storage-sig

#15559 Fix UserSessionProviderTest.testOnClientRemoved on CRDB
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserSessionProviderTest.java
Labels: area/storage, team/storage-sig

#15591 Disabling unstable test until further analysis is complete
  testsuite/model/src/test/java/org/keycloak/testsuite/model/DBLockTest.java
Labels: area/storage, team/storage-sig

#15047 10090 remove paginate query workaround
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/common/HotRodUtils.java
Labels: area/storage, team/storage-sig

#15023 Stop reindexing indexes on new version
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/connections/DefaultHotRodConnectionProviderFactory.java
  quarkus/config-api/src/main/java/org/keycloak/config/StorageOptions.java
Labels: area/storage, team/storage-sig

#15619 Replace operation set wrong lifespan in remote infinispan database an…
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java
Labels: area/storage, area/infinispan, team/storage-sig

#15609 Enable all test methods in ConcurrentLoginTest for JPA Map Storage
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
  services/src/main/java/org/keycloak/common/util/ResponseSessionTask.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/concurrency/ConcurrentLoginTest.java
Labels: area/storage, team/storage-sig

#15650 Fix query to work on OracleDB CLOB
  model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventStoreProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/RealmAttributeEntity.java
Labels: status/ready

#15651 Make tests run on Oracle DB on the internal pipeline
  testsuite/integration-arquillian/pom.xml
Labels: status/ready

#15733 Create map-file module with empty implementations
  dependencies/server-all/pom.xml
  model/map-file/pom.xml
  model/map-file/src/main/java/org/keycloak/models/map/storage/file/FileKeycloakTransaction.java
  model/map-file/src/main/java/org/keycloak/models/map/storage/file/FileMapStorage.java
  model/map-file/src/main/java/org/keycloak/models/map/storage/file/FileMapStorageProvider.java
  model/map-file/src/main/java/org/keycloak/models/map/storage/file/FileMapStorageProviderFactory.java
  model/map-file/src/main/resources/META-INF/services/org.keycloak.models.map.storage.MapStorageProviderFactory
  model/pom.xml
  pom.xml
  quarkus/runtime/pom.xml
Labels: area/storage, team/storage-sig
