Repository keycloak/keycloak, pull requests merged in 2022-08, with the labels that each got.

#13419 Stabilize testCreateUserSessionsParallel model test
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderModelTest.java
Labels: area/storage, team/storage-sig

#10650 KEYCLOAK-19866 Fix user-defined-/anyType parsing and introduce XPathAttributeMapper
  saml-core/src/main/java/org/keycloak/saml/processing/core/parsers/saml/assertion/SAMLAttributeValueParser.java
  saml-core/src/test/java/org/keycloak/saml/processing/core/parsers/saml/SAMLAttributeValueParserTest.java
  saml-core/src/test/java/org/keycloak/saml/processing/core/parsers/saml/SAMLParserTest.java
  saml-core/src/test/resources/org/keycloak/saml/processing/core/parsers/saml/saml20-assertion-example.xml
  services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java
  services/src/main/resources/META-INF/services/org.keycloak.broker.provider.IdentityProviderMapper
  services/src/test/java/org/keycloak/test/broker/saml/XPathAttributeMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlXPathAttributeMapperTest.java
Labels: area/saml

#13155 Fix minor typos in examples
  examples/README.md
  examples/admin-client/README.md
  examples/broker/facebook-authentication/README.md
  examples/broker/google-authentication/README.md
  examples/broker/saml-broker-authentication/README.md
  examples/broker/twitter-authentication/README.md
  examples/cordova-native/README.md
  examples/cordova/README.md
  examples/cors/README.md
  examples/js-console/README.md
  examples/kerberos/README.md
  examples/ldap/README.md
  examples/providers/authenticator/README.md
  examples/providers/domain-extension/README.md
  examples/providers/domain-extension/invoke-authenticated.sh
  examples/saml/servlet-filter/README.md
Labels: kind/enhancement, area/docs

#13488 Remove possibility to start embedded HotRod server in hotrod-map module
  model/map-hot-rod/pom.xml
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/common/HotRodUtils.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/connections/DefaultHotRodConnectionProviderFactory.java
  pom.xml
  quarkus/runtime/pom.xml
  testsuite/integration-arquillian/pom.xml
  testsuite/model/README.md
  testsuite/model/pom.xml
  testsuite/model/src/main/java/org/keycloak/testsuite/model/HotRodServerRule.java
  testsuite/model/src/main/java/org/keycloak/testsuite/model/KeycloakModelParameters.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/AfterSuiteListener.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/HotRodMapStorage.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionConcurrencyTest.java
Labels: area/storage, team/storage-sig

#10054 Suggests changes for database configuration topic
  docs/guides/src/main/server/db.adoc
Labels: kind/enhancement, area/docs

#13679 Update Node.js to latest LTS version
  pom.xml
Labels: area/dependencies, kind/task

#13617 Add limit for authSessions per rootAuthSession in map storage
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanAuthenticationSessionProviderFactory.java
  model/map/src/main/java/org/keycloak/models/map/authSession/MapRootAuthenticationSessionAdapter.java
  model/map/src/main/java/org/keycloak/models/map/authSession/MapRootAuthenticationSessionProvider.java
  model/map/src/main/java/org/keycloak/models/map/authSession/MapRootAuthenticationSessionProviderFactory.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/AuthenticationSessionTest.java
Labels: area/storage, team/storage-sig

#13546 Improve docs for importing a realm in a container
  docs/guides/src/main/server/containers.adoc
  docs/guides/src/main/server/importExport.adoc
Labels: area/docs

#13687 Run Infinispan using Testcontainers in base testsuite
  .github/workflows/ci.yml
  testsuite/integration-arquillian/HOW-TO-RUN.md
  testsuite/integration-arquillian/servers/cache-server/infinispan/pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/AuthServerTestEnricher.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/HotRodStoreTestEnricher.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/SuiteContext.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/InfinispanContainer.java
  testsuite/integration-arquillian/tests/base/src/test/resources/META-INF/keycloak-server.json
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
  testsuite/integration-arquillian/tests/pom.xml
  testsuite/model/README.md
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/HotRodMapStorage.java
Labels: area/storage, team/storage-sig

#13471 suppress confirmation screen for logout in oidc with new flag
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCProviderConfig.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LegacyLogoutTest.java
Labels: missing/docs, area/oidc

#13724 Fix KeycloakQuarkusServerDeployableContainer to correctly configure m…
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/PermissionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ServerInfoTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/domainextension/CustomExtensionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/script/DeployedScriptAuthenticatorTest.java
Labels: area/testsuite, area/storage, team/storage-sig

#13785 Disable Dependabot for Account Console
  .github/dependabot.yml
Labels: area/account/ui, area/dependencies, kind/task

#13268 Do not run snyk github workflow on forks of the repo
  .github/workflows/snyk.yml
Labels: area/ci

#13710 Updating RestEasy changes for Jetty App Server
  testsuite/integration-arquillian/servers/app-server/jetty/common/src/main/java/org/keycloak/testsuite/arquillian/jetty/JettyAppServer.java
Labels: area/testsuite

#13643 Fix DB tests for Quarkus
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusConfiguration.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/model/StoreProvider.java
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
  testsuite/integration-arquillian/tests/pom.xml
Labels: area/testsuite, area/storage

#13831 Fix running clusteraware scheduled tasks in Wildfly after legacy migration
  model/legacy-private/src/main/java/org/keycloak/services/scheduled/ClusterAwareScheduledTaskRunner.java
Labels: area/storage, team/storage-sig

#13827 Remove warning from StoragePropertyMappers about the deployment state version seed
  model/map/src/main/java/org/keycloak/models/map/deploymentState/MapDeploymentStateProviderFactory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/StoragePropertyMappers.java
Labels: area/storage, team/storage-sig

#13890 Fix ConcurrentTransactionsTest failure with CockroachDB
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/ConcurrentTransactionsTest.java
Labels: area/storage, team/storage-sig

#13891 Fix UserSessionProviderTest failures with CockroachDB
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserSessionProviderTest.java
Labels: area/storage, team/storage-sig

#13889 Fix user session deadlock by enlisting broker logout request after ma…
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
Labels: area/storage, team/storage-sig

#13161 Correct isValidScope method of TokenManager for Dynamic scopes
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/FlowOverrideTest.java
Labels: missing/tests

#13361 integration.admin-client: Add exact search for all dedicated user attributes
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/UsersResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
Labels: missing/tests

#8025 KEYCLOAK-18289: use utf-8 encoding for simplehttp
  server-spi-private/src/main/java/org/keycloak/broker/provider/util/SimpleHttp.java
  server-spi-private/src/test/java/org/keycloak/broker/provider/util/SimpleHttpTest.java
Labels: missing/issue, kind/bug

#12966 Update messages_ca.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ca.properties
Labels: area/translations

#13154 Fix minor typos in documentations
  docs/guides/src/main/operator/installation.adoc
  docs/guides/src/main/server/reverseproxy.adoc
Labels: kind/enhancement, area/docs

#14007 Make GHA HotRod base testsuite running with Quarkus
  .github/workflows/ci.yml
Labels: area/storage, team/storage-sig

#13151 Check IdP display name length before capitalizing
  services/src/main/java/org/keycloak/email/freemarker/FreeMarkerEmailTemplateProvider.java
Labels: area/authentication, kind/bug

#11060 Implement AutoCloseable in SimpleHTTP util
  server-spi-private/src/main/java/org/keycloak/broker/provider/util/SimpleHttp.java
Labels: impact/low, area/core

#7748 KEYCLOAK-17013 Brute force protection: Successfully logged in user should not have to wait up to 5 seconds for event processing
  services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java
Labels: missing/tests, kind/enhancement, impact/medium
