Repository keycloak/keycloak, pull requests merged in 2022-10, with the labels that each got.

#14658 offline token issuance can cause violation of PRIMARY KEY constraint …
  model/jpa/src/main/java/org/keycloak/models/jpa/session/JpaUserSessionPersisterProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java
Labels: area/oidc, priority/important, area/storage, team/rh-iam

#14515 Update user-list.html
  themes/src/main/resources/theme/base/admin/resources/partials/user-list.html
Labels: kind/bug, area/admin/ui

#14560 KEYCLOAK_SESSION not working for some user federation setups when use…
  common/src/main/java/org/keycloak/common/util/Encode.java
  common/src/test/java/org/keycloak/common/util/URLEncodingTest.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/storage-test/user-password.properties
Labels: priority/important

#14379 Revisit parent-child relationship in jpa map store
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaRootEntity.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/authSession/entity/JpaAuthenticationSessionEntity.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/hibernate/listeners/JpaEntityVersionListener.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/hibernate/listeners/JpaOptimisticLockingListener.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/entity/JpaComponentEntity.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserConsentEntity.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserFederatedIdentityEntity.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/userSession/entity/JpaClientSessionEntity.java
Labels: area/storage, team/storage-sig

#14732 Ensure map storage providers are closed upon session close
  model/map/src/main/java/org/keycloak/models/map/common/AbstractMapProviderFactory.java
  services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java
Labels: kind/bug, area/core, area/storage, team/storage-sig

#14744 Cleanup MapUserSessionAdapter.getAuthenticatedClientSessions()
  model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionAdapter.java
  services/src/main/java/org/keycloak/authorization/common/KeycloakIdentity.java
  services/src/main/java/org/keycloak/protocol/saml/SamlService.java
Labels: kind/enhancement, area/storage, team/storage-sig

#13394 Avoid login failures in case of non-existing group or role references and update references in case of renaming or moving
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  model/map/src/main/java/org/keycloak/models/map/group/MapGroupProvider.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/AbstractIdentityProviderMapper.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/AbstractConfigPropertySynchronizer.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/ConfigSyncEventListener.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/ConfigSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/GroupConfigPropertyByPathSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/RoleConfigPropertyByClientIdSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/RoleConfigPropertyByRoleNameSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  server-spi-private/src/test/java/org/keycloak/models/KeycloakModelUtilsTest.java
  server-spi/src/main/java/org/keycloak/models/ClientModel.java
  server-spi/src/main/java/org/keycloak/models/GroupModel.java
  server-spi/src/main/java/org/keycloak/models/RoleModel.java
  services/src/main/java/org/keycloak/broker/oidc/mappers/AbstractClaimToGroupMapper.java
  services/src/main/java/org/keycloak/broker/oidc/mappers/AbstractClaimToRoleMapper.java
  services/src/main/java/org/keycloak/broker/oidc/mappers/AdvancedClaimToGroupMapper.java
  services/src/main/java/org/keycloak/broker/provider/HardcodedRoleMapper.java
  services/src/main/java/org/keycloak/broker/saml/mappers/AbstractAttributeToRoleMapper.java
  services/src/main/java/org/keycloak/services/clientregistration/AbstractClientRegistrationProvider.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientResource.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RoleByIdResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RoleContainerResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RoleResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractAdvancedGroupMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractAdvancedRoleMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractGroupMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractRoleMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AttributeToRoleMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/BrokerTestTools.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/ExternalKeycloakRoleToRoleMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/HardcodedRoleMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlAdvancedAttributeToRoleMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlMultipleAttributeToRoleMappersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/OidcAdvancedClaimToGroupMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/OidcAdvancedClaimToRoleMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/OidcClaimToRoleMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/OidcMultipleClaimToRoleMappersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/OidcUserInfoClaimToRoleMapperTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/RealmModelTest.java
Labels: priority/important

#14748 MapUserProvider in KC20 needs to store username compatible with KC19 …
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/hibernate/jsonb/migration/JpaUserMigration.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/JpaUserMapKeycloakTransaction.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/JpaUserModelCriteriaBuilder.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserMetadata.java
  model/map-jpa/src/main/resources/META-INF/users/jpa-users-changelog-2.xml
  model/map/src/main/java/org/keycloak/models/map/user/MapUserAdapter.java
  model/map/src/main/java/org/keycloak/models/map/user/MapUserProvider.java
  model/map/src/main/java/org/keycloak/models/map/user/MapUserProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  services/src/main/java/org/keycloak/userprofile/validator/DuplicateUsernameValidator.java
  services/src/main/java/org/keycloak/userprofile/validator/UsernameMutationValidator.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/UserMapStorage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AssertEvents.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/FineGrainAdminUnitTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UsersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterWithUserProfileTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/UserModelTest.java
Labels: area/storage, team/storage-sig

#14819 Update H2 database to 2.x
  model/jpa/pom.xml
  model/jpa/src/main/java/org/keycloak/connections/jpa/DefaultJpaConnectionProviderFactory.java
  model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventStoreProvider.java
  pom.xml
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  testsuite/integration-arquillian/pom.xml
  testsuite/model/pom.xml
Labels: area/storage, team/storage-sig

#14856 Revisit unique constraints in jpa user store
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/entity/JpaUserEntity.java
  model/map-jpa/src/main/resources/META-INF/users/jpa-users-changelog-2.xml
Labels: area/storage, team/storage-sig

#14087 Fix ComponentsTest failures with CockroachDB
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  server-spi-private/src/main/java/org/keycloak/utils/LockObjectsForModification.java
  server-spi/src/main/java/org/keycloak/models/KeycloakSessionTaskWithResult.java
  services/src/main/java/org/keycloak/keys/JavaKeystoreKeyProviderFactory.java
  services/src/main/java/org/keycloak/services/resources/admin/ComponentResource.java
Labels: area/storage, team/storage-sig

#15039 Reduce number of calls to the storage for clients and realms
  server-spi-private/src/main/java/org/keycloak/authorization/identity/Identity.java
  services/src/main/java/org/keycloak/authorization/common/ClientModelIdentity.java
  services/src/main/java/org/keycloak/authorization/common/UserModelIdentity.java
  services/src/main/java/org/keycloak/services/managers/RealmManager.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmsAdminResource.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java
Labels: status/ready, kind/enhancement, area/storage, team/storage-sig

#14891 Add possibility to limit field length in legacy event store
  model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventStoreProvider.java
  model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventStoreProviderFactory.java
Labels: area/storage, team/storage-sig

#15034 Upgrade to Quarkus 2.13.3
  pom.xml
  quarkus/pom.xml
Labels: area/dependencies

#15117 Restore labels for supported applications under 'OTP Policy' tab
  themes/src/main/resources/theme/base/admin/messages/admin-messages_en.properties
  themes/src/main/resources/theme/base/admin/resources/partials/otp-policy.html
Labels: area/authentication, kind/bug, priority/critical, impact/low, area/admin/ui, team/ui

#14950 fix(sec): upgrade org.apache.tomcat:tomcat-catalina to 8.5.76
  pom.xml
  testsuite/integration-arquillian/servers/pom.xml
Labels: area/dependencies, kind/cve

#12611 Fix slow deletion on `deleteClientSessionsByRealm` and `deleteClientSessionsByUser` when using mysql and mariadb by converting sub-query to join
  model/jpa/src/main/java/org/keycloak/models/jpa/session/PersistentClientSessionEntity.java
  model/jpa/src/main/resources/META-INF/queries-default.properties
  model/jpa/src/main/resources/META-INF/queries-mariadb.properties
  model/jpa/src/main/resources/META-INF/queries-mysql.properties
Labels: area/storage, kind/performance
