Repository keycloak/keycloak, pull requests merged in 2022-07, with the labels that each got.

#12760 Instead of returning instances with different semantics, throw an exception.
  server-spi/src/main/java/org/keycloak/models/KeycloakSession.java
  services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java
Labels: status/ready, area/storage, team/storage-sig

#12791 Store composite roles within its own table for JPA Map storage.
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapKeycloakTransaction.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaModelCriteriaBuilder.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaSubqueryProvider.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/authSession/JpaRootAuthenticationSessionModelCriteriaBuilder.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/authorization/permission/JpaPermissionModelCriteriaBuilder.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/authorization/policy/JpaPolicyModelCriteriaBuilder.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/authorization/resource/JpaResourceModelCriteriaBuilder.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/authorization/resourceServer/JpaResourceServerModelCriteriaBuilder.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/authorization/scope/JpaScopeModelCriteriaBuilder.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/client/JpaClientModelCriteriaBuilder.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/clientscope/JpaClientScopeModelCriteriaBuilder.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/event/admin/JpaAdminEventModelCriteriaBuilder.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/event/auth/JpaAuthEventModelCriteriaBuilder.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/group/JpaGroupModelCriteriaBuilder.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/loginFailure/JpaUserLoginFailureModelCriteriaBuilder.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/JpaRealmModelCriteriaBuilder.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/role/JpaPredicateFunction.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/role/JpaRoleMapKeycloakTransaction.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/role/JpaRoleModelCriteriaBuilder.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/role/delegate/JpaMapRoleEntityDelegate.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/role/entity/JpaRoleCompositeEntity.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/role/entity/JpaRoleCompositeEntityKey.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/role/entity/JpaRoleEntity.java
  model/map-jpa/src/main/resources/META-INF/persistence.xml
  model/map-jpa/src/main/resources/META-INF/roles/jpa-roles-changelog-1.xml
Labels: status/ready, area/storage, team/storage-sig

#12899 Fixing broken build after merging conflicting PRs.
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/singleUseObject/JpaSingleUseObjectModelCriteriaBuilder.java
Labels: area/storage, team/storage-sig

#12928 Enable JPA store for ActionTokenStoreSpi in model tests
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/JpaMapStorage.java
Labels: area/storage, team/storage-sig

#12960 Store enums as Integers in HotRod store
  model/build-processor/src/main/java/org/keycloak/models/map/processor/GenerateHotRodEntityImplementationsProcessor.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/IckleQueryWhereClauses.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/authSession/HotRodAuthenticationSessionEntity.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/authSession/HotRodExecutionStatus.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/authSession/HotRodRootAuthenticationSessionEntity.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/authorization/HotRodDecisionStrategy.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/authorization/HotRodLogic.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/authorization/HotRodPolicyEnforcementMode.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/authorization/HotRodPolicyEntity.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/authorization/HotRodResourceServerEntity.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/common/HotRodTypesUtils.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/events/HotRodAdminEventEntity.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/events/HotRodAuthEventEntity.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/events/HotRodEventType.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/events/HotRodOperationType.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/realm/HotRodRealmEntity.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/realm/entity/HotRodAuthenticationExecutionEntity.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/realm/entity/HotRodRequirement.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodSessionState.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodUserSessionEntity.java
Labels: area/storage, team/storage-sig

#12670 Fixing ClientPoliciesTest failure
  testsuite/integration-arquillian/tests/other/console/src/test/java/org/keycloak/testsuite/console/realm/ClientPoliciesTest.java
Labels: area/testsuite

#12901 Make user->client sessions relationship consistent
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/HotRodMapStorageProviderFactory.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/IckleQueryMapModelCriteriaBuilder.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodAuthenticatedClientSessionEntity.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodUserSessionEntity.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodUserSessionMapStorage.java
  model/map-hot-rod/src/main/resources/config/cacheConfig.xml
  model/map-hot-rod/src/main/resources/config/infinispan.xml
  model/map/src/main/java/org/keycloak/models/map/storage/chm/ConcurrentHashMapStorageProviderFactory.java
  model/map/src/main/java/org/keycloak/models/map/storage/chm/MapFieldPredicates.java
  model/map/src/main/java/org/keycloak/models/map/storage/chm/UserSessionCascadeRemovalTransaction.java
  model/map/src/main/java/org/keycloak/models/map/storage/chm/UserSessionConcurrentHashMapStorage.java
  model/map/src/main/java/org/keycloak/models/map/userSession/AbstractAuthenticatedClientSessionModel.java
  model/map/src/main/java/org/keycloak/models/map/userSession/MapAuthenticatedClientSessionAdapter.java
  model/map/src/main/java/org/keycloak/models/map/userSession/MapAuthenticatedClientSessionEntity.java
  model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionAdapter.java
  model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionEntity.java
  model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionProvider.java
  model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/models/UserSessionProviderFactory.java
  server-spi/src/main/java/org/keycloak/models/AuthenticatedClientSessionModel.java
  testsuite/integration-arquillian/tests/base/src/test/resources/META-INF/keycloak-server.json
  testsuite/model/src/main/resources/hotrod/infinispan.xml
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/HotRodMapStorage.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/JpaMapStorage.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/LdapMapStorage.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderModelTest.java
Labels: area/storage, team/storage-sig

#12926 Correct NPM update instructions with correct path
  themes/UPDATING-NODE-MODULES.md
Labels: area/docs, area/admin/ui

#12994 Disable WARN logging for Hot Rod RemoteQuery class
  testsuite/integration-arquillian/tests/base/src/test/resources/log4j.properties
  testsuite/model/src/test/resources/log4j.properties
  testsuite/utils/src/main/resources/log4j.properties
Labels: status/ready, area/storage, team/storage-sig

#12925 Enable dependabot on NPM dependencies
  .github/dependabot.yml
Labels: area/ci

#13054 Prevent Dependabot from upgrading major versions of Bootstrap
  .github/dependabot.yml
Labels: kind/enhancement, area/admin/ui, area/dependencies

#13057 Use correct path for 'text-security' CSS
  examples/themes/src/main/resources/theme/logo-example/admin/theme.properties
Labels: kind/enhancement

#13048 Convert ClientSessionIdleTimeout from seconds to milliseconds before …
  model/map/src/main/java/org/keycloak/models/map/userSession/SessionExpiration.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionExpirationTest.java
Labels: area/storage, team/storage-sig

#13077 Avoid using old legacy-store API in the test suite
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/DeviceActivityTest.java
Labels: status/ready, area/storage, team/storage-sig

#12482 Add translation to portuguese
  themes/src/main/resources-community/theme/base/admin/messages/admin-messages_pt_BR.properties
Labels: area/translations

#12991 Choose alternatives for CockroachDB for referenced computed columns
  model/map-jpa/src/main/resources/META-INF/authz/permission/jpa-authz-permission-changelog-1.xml
  model/map-jpa/src/main/resources/META-INF/authz/policy/jpa-authz-policy-changelog-1.xml
  model/map-jpa/src/main/resources/META-INF/authz/resource/jpa-authz-resource-changelog-1.xml
  model/map-jpa/src/main/resources/META-INF/authz/scope/jpa-authz-scope-changelog-1.xml
Labels: kind/bug, area/storage

#13079 Update configuration to re-enable starting KeycloakServer for map storage
  testsuite/utils/src/main/resources/META-INF/keycloak-server.json
Labels: area/storage, team/storage-sig

#13134 Move non-map-storage related classes to new package
  server-spi-private/src/main/java/org/keycloak/sessions/DisabledStickySessionEncoderProvider.java
  server-spi-private/src/main/resources/META-INF/services/org.keycloak.sessions.StickySessionEncoderProviderFactory
Labels: area/storage, team/storage-sig

#13156 Ensure Dependabot PRs are created on Saturdays
  .github/dependabot.yml
Labels: kind/enhancement, area/ci

#13182 Fix ESLint configuration for Account Console
  themes/src/main/resources/theme/keycloak.v2/account/src/.eslintrc.js
  themes/src/main/resources/theme/keycloak.v2/account/src/package-lock.json
  themes/src/main/resources/theme/keycloak.v2/account/src/package.json
Labels: area/account/ui, area/dependencies

#12822 Use lf as line-ending for sh files
  .gitattributes
Labels: status/ready

#13180 Enable JPA map user session store
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/StoragePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaMapStorageProviderFactory.java
Labels: status/ready, area/storage, team/storage-sig

#13133 Remove offline sessions when deleting a realm
  model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionProvider.java
  model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionProviderFactory.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java
Labels: status/ready, kind/bug, area/storage, team/storage-sig

#13140 Enable action token JPA provider in map-storage-jpa profile
  model/map-jpa/src/main/resources/default-map-jpa-persistence.xml
  testsuite/integration-arquillian/tests/base/pom.xml
Labels: area/storage, team/storage-sig

#13075 Add model tests for Hot Rod starting multiple nodes
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderModelTest.java
Labels: area/storage, team/storage-sig

#13228 Migrate classes around the ClusterProvider
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanStickySessionEncoderProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProviderFactory.java
  model/legacy-private/src/main/java/org/keycloak/cluster/ClusterProviderFactory.java
  model/legacy-private/src/main/java/org/keycloak/cluster/ClusterSpi.java
  model/legacy-private/src/main/java/org/keycloak/services/scheduled/ClusterAwareScheduledTaskRunner.java
  model/legacy-private/src/main/resources/META-INF/services/org.keycloak.provider.Spi
  model/map/src/main/java/org/keycloak/models/map/authSession/MapRootAuthenticationSessionProvider.java
  model/map/src/main/java/org/keycloak/models/map/authorization/MapAuthorizationStore.java
  model/map/src/main/java/org/keycloak/models/map/authorization/MapAuthorizationStoreFactory.java
  model/map/src/main/java/org/keycloak/models/map/common/AbstractMapProviderFactory.java
  model/map/src/main/java/org/keycloak/models/map/events/MapEventStoreProviderFactory.java
  model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionProvider.java
  quarkus/config-api/src/main/java/org/keycloak/config/StorageOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/StoragePropertyMappers.java
  server-spi-private/src/main/java/org/keycloak/cluster/ClusterProvider.java
  server-spi-private/src/main/resources/META-INF/services/org.keycloak.provider.Spi
  server-spi/src/main/java/org/keycloak/models/UserSessionProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/model/infinispan/InfinispanTestUtil.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ResourceOwnerPasswordCredentialsGrantTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/session/LastSessionRefreshUnitTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderModelTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderOfflineModelTest.java
Labels: area/storage, team/storage-sig

#13318 Liquibase should differentiate between CockroachDB and PostgreSQL despite them same driver
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
Labels: area/storage, team/storage-sig

#13138 Optimize user-client session relationship for HotRod storage
  model/build-processor/src/main/java/org/keycloak/models/map/processor/GenerateHotRodEntityImplementationsProcessor.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/HotRodMapStorage.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/HotRodMapStorageProviderFactory.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/SingleUseObjectHotRodMapStorage.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/common/HotRodTypesUtils.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/AuthenticatedClientSessionReferenceOnlyFieldDelegate.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodAuthenticatedClientSessionEntity.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodAuthenticatedClientSessionEntityDelegateProvider.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodAuthenticatedClientSessionEntityReference.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodUserSessionEntity.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/userSession/HotRodUserSessionTransaction.java
  model/map-hot-rod/src/main/resources/config/cacheConfig.xml
  model/map-hot-rod/src/main/resources/config/infinispan.xml
  model/map/src/main/java/org/keycloak/models/map/storage/ModelEntityUtil.java
  model/map/src/main/java/org/keycloak/models/map/storage/chm/MapFieldPredicates.java
  model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionAdapter.java
  testsuite/model/src/main/resources/hotrod/infinispan.xml
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/HotRodUserSessionClientSessionRelationshipTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionConcurrencyTest.java
Labels: area/storage, team/storage-sig

#13313 Allow Quarkus configuration to mix different storage providers
  .github/workflows/ci.yml
  quarkus/config-api/src/main/java/org/keycloak/config/StorageOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/StoragePropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/map/MixedStoreDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/approvals/cli/help/HelpCommandTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/approvals/cli/help/HelpCommandTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/approvals/cli/help/HelpCommandTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/approvals/cli/help/HelpCommandTest.testStartHelpAll.windows.approved.txt
Labels: status/ready

#13356 Add prefix to the area Map storage options for Quarkus
  quarkus/config-api/src/main/java/org/keycloak/config/StorageOptions.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/map/MixedStoreDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/approvals/cli/help/HelpCommandTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/approvals/cli/help/HelpCommandTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/approvals/cli/help/HelpCommandTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/approvals/cli/help/HelpCommandTest.testStartHelpAll.windows.approved.txt
Labels: area/storage, team/storage-sig

#13333 Enable near-caching for HotRod store
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/connections/DefaultHotRodConnectionProviderFactory.java
Labels: area/storage, team/storage-sig

#13365 Add 'prepublishOnly' script for Keycloak JS
  adapters/oidc/js/package.json
Labels: kind/enhancement, area/adapter/javascript

#13306 Set deployment state resources version to avoid warning in the console
  model/map/src/main/java/org/keycloak/models/map/deploymentState/MapDeploymentStateProviderFactory.java
  quarkus/config-api/src/main/java/org/keycloak/config/StorageOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/StoragePropertyMappers.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/approvals/cli/help/HelpCommandTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/approvals/cli/help/HelpCommandTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/approvals/cli/help/HelpCommandTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/approvals/cli/help/HelpCommandTest.testStartHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/approvals/cli/help/HelpCommandTest.testStartOptimizedHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/approvals/cli/help/HelpCommandTest.testStartOptimizedHelpAll.windows.approved.txt
Labels: area/storage, team/storage-sig
