Repository keycloak/keycloak, pull requests merged in 2023-05, with the labels that each got.

#20011 Update to Quarkus 3.0.1.Final
  operator/pom.xml
  pom.xml
  quarkus/container/README.md
Labels: team/cloud-native, team/store, team/core, flaky-test

#19991 don't add access when fine grained access is off
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/GroupsResource.java
Labels: team/ui

#19984 added missing fields when dynamic scope is enabled
  js/apps/admin-ui/public/resources/en/client-scopes-help.json
  js/apps/admin-ui/public/resources/en/client-scopes.json
  js/apps/admin-ui/src/client-scopes/details/ScopeForm.tsx
  js/apps/admin-ui/src/components/SwitchControl.tsx
  js/apps/admin-ui/src/utils/useIsFeatureEnabled.ts
  js/libs/ui-shared/src/controls/SwitchControl.tsx
Labels: team/ui

#19804 better default avatar if none is set
  js/apps/account-ui/public/avatar.svg
  js/libs/keycloak-masthead/src/DefaultAvatar.tsx
  js/libs/keycloak-masthead/src/Masthead.tsx
  js/libs/keycloak-masthead/src/svg.d.ts
  js/package-lock.json
Labels: team/ui

#19799 added referrer link
  js/apps/account-ui/public/locales/en/translation.json
  js/apps/account-ui/src/root/Root.tsx
  js/libs/keycloak-masthead/src/Masthead.tsx
Labels: team/ui

#20004 Remove workaround for fix available in Hibernate 6.2.1
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
Labels: team/store

#20030 Add OpenShift support to KeycloakIngressTest
  operator/src/main/java/org/keycloak/operator/Utils.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java
Labels: team/cloud-native, flaky-test

#20040 Clean RealmProvider from methods from other areas
  model/map/src/main/java/org/keycloak/models/map/realm/MapRealmProvider.java
  server-spi/src/main/java/org/keycloak/models/RealmProvider.java
Labels: team/store, flaky-test

#20062 Fix custom userFed that doesn't implement CredentialInputUpdater
  js/apps/admin-ui/src/user/UserCredentials.tsx
  js/apps/admin-ui/src/user/user-credentials/FederatedCredentials.tsx
Labels: team/ui

#19956 New messages are added in Spanish
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
Labels: team/ui

#20102 fixed paging
  js/apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
Labels: team/ui

#20133 Adding support for rsa-oaep for SAML encryption
  saml-core/src/main/java/org/keycloak/saml/BaseSAML2BindingBuilder.java
  saml-core/src/main/java/org/keycloak/saml/SPMetadataDescriptor.java
  saml-core/src/main/java/org/keycloak/saml/processing/core/util/XMLEncryptionUtil.java
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java
  services/src/main/java/org/keycloak/protocol/saml/SAMLEncryptionAlgorithms.java
  services/src/test/java/org/keycloak/protocol/saml/SamlEncryptionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractKcSamlEncryptedElementsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlEncryptedAssertionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlEncryptedIdTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlSpDescriptorTest.java
Labels: team/cloud-native, team/store, team/core

#20149 Replace guide with a placeholder for downstream docs
  docs/guides/getting-started/getting-started-kube.adoc
  docs/guides/getting-started/getting-started-openshift.adoc
  docs/guides/operator/advanced-configuration.adoc
  docs/guides/operator/basic-deployment.adoc
  docs/guides/operator/installation.adoc
  docs/guides/server/configuration-production.adoc
  docs/guides/server/configuration-provider.adoc
  docs/guides/server/configuration.adoc
  docs/guides/server/importExport.adoc
  docs/guides/server/logging.adoc
  docs/guides/server/outgoinghttp.adoc
Labels: team/cloud-native

#20154 Update to Quarkus 3.0.2.Final
  pom.xml
Labels: team/cloud-native, flaky-test

#20141 Support for non-XA databases
  .github/workflows/ci.yml
  quarkus/config-api/src/main/java/org/keycloak/config/TransactionOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TransactionPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/AbstractJpaConnectionProviderFactory.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/MSSQLTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/CustomTransactionDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/TransactionConfigurationDistTest.java
  quarkus/tests/integration/src/test/resources/container-license-acceptance.txt
  quarkus/tests/junit5/pom.xml
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/DatabaseContainer.java
Labels: team/cloud-native, flaky-test

#20112 JpaUserProvider count methods are inconsistent with searchForUser's p…
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UsersTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20142 on the roles page we have paging on others not
  js/apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
Labels: team/ui

#20109 use event id instead of name
  js/apps/admin-ui/src/events/EventsSection.tsx
  js/apps/admin-ui/src/realm-settings/event-config/EventsTypeTable.tsx
Labels: team/ui

#20113 Artifact SLF4J LOG4J-12 has been relocated
  docs/documentation/tests/pom.xml
  model/jpa/pom.xml
  pom.xml
  quarkus/runtime/pom.xml
  testsuite/integration-arquillian/tests/pom.xml
  testsuite/model/pom.xml
  testsuite/utils/pom.xml
  util/embedded-ldap/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#20132 Remove OkHttp Client from the Operator
  operator/pom.xml
  operator/src/main/java/org/keycloak/kubernetes/client/HttpClientFactory.java
  operator/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.http.HttpClient$Factory
Labels: team/cloud-native, flaky-test

#14702 Use Chrome as the default JavaScript browser
  testsuite/integration-arquillian/tests/pom.xml
Labels: area/testsuite, kind/enhancement

#20136 Fix custom userFed that doesn't implement CredentialInputUpdater
  js/apps/admin-ui/src/user/UserCredentials.tsx
  js/apps/admin-ui/src/user/user-credentials/FederatedCredentials.tsx
Labels: team/ui

#20181 use event id instead of name (#20109)
  js/apps/admin-ui/src/events/EventsSection.tsx
  js/apps/admin-ui/src/realm-settings/event-config/EventsTypeTable.tsx
Labels: team/ui

#20187 Stops the recreation of managed Keycloak Statefulset Pods when Keycloak Operator restarts occasionally.
  operator/src/main/java/org/keycloak/operator/Constants.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
Labels: team/cloud-native

#20251 Force user to authenticate before bootstrapping Admin Console
  js/apps/admin-ui/src/keycloak.ts
  js/apps/admin-ui/src/main.tsx
Labels: team/ui

#20091 Migration guide for Keycloak admin client
  docs/documentation/release_notes/topics/22_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc
Labels: priority/important, area/docs

#20277 Improve coding guidelines for PNPM workspaces
  js/CODING_GUIDELINES.md
Labels: area/docs, team/ui

#20301 SSSD testing with GH actions
  .github/actions/conditional/action.yml
  .github/actions/conditional/conditions
  .github/scripts/run-ipa-tests.sh
  .github/scripts/run-ipa.sh
  .github/workflows/ci.yml
Labels: flaky-test

#20242 fixed to use parameter
  js/libs/keycloak-admin-client/src/resources/realms.ts
Labels: team/ui

#20240 add 'seconds' unit if value not valid
  js/apps/admin-ui/src/components/time-selector/TimeSelector.tsx
Labels: team/ui

#20234 added min length > 0 check to required
  js/apps/admin-ui/src/user/UserProfileFields.tsx
Labels: team/ui

#20104 empty array instead of null
  js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx
Labels: team/ui, flaky-test

#20183 Rework merging of message bundles for localization of Admin Console
  docs/documentation/release_notes/topics/22_0_0.adoc
  js/apps/admin-ui/src/context/whoami/WhoAmI.tsx
  js/apps/admin-ui/src/context/whoami/__tests__/WhoAmI.test.ts
  js/apps/admin-ui/src/context/whoami/__tests__/mock-whoami.json
  js/apps/admin-ui/src/i18n.ts
  js/apps/admin-ui/src/i18n/OverridesBackend.ts
  js/apps/admin-ui/src/i18n/i18n.ts
  js/apps/admin-ui/src/main.tsx
  js/apps/admin-ui/src/realm-settings/LocalizationTab.tsx
Labels: status/hold, team/ui

#20355 Update dependencies to latest version
  js/apps/account-ui/package.json
  js/apps/admin-ui/package.json
  js/apps/keycloak-server/package.json
  js/libs/keycloak-admin-client/package.json
  js/libs/keycloak-js/package.json
  js/libs/keycloak-masthead/package.json
  js/libs/ui-shared/package.json
  js/package.json
  js/pnpm-lock.yaml
  pom.xml
Labels: area/dependencies, kind/task, team/ui, flaky-test

#19848 19847 - Split UsersSection into components for better maintainability
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
  js/apps/admin-ui/src/components/users/UserDataTableToolbarItems.tsx
  js/apps/admin-ui/src/user/UsersSection.tsx
Labels: team/ui, flaky-test

#20131 Jakarta EE, Quarkus 3 and Hibernate ORM upgrade documentation
  docs/documentation/release_notes/topics/22_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc
Labels: priority/important

#19976 add disabled and required to User Profile fields
  js/apps/account-ui/src/personal-info/FormField.tsx
Labels: team/ui

#20274 Upgrade tested DB versions
  pom.xml
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#20072 Update the docs on passthrough proxy
  docs/documentation/release_notes/topics/22_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc
  docs/guides/server/reverseproxy.adoc
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ProxyPropertyMappers.java
  testsuite/integration-arquillian/servers/auth-server/quarkus/src/main/content/conf/keycloak.conf
Labels: team/cloud-native, team/store, team/core

#20323 Upgrade JNA library
  pom.xml
Labels: flaky-test

#20373 Disable proxy argument passing for executions of pnpm pack
  js/libs/keycloak-admin-client/pom.xml
  js/libs/keycloak-js/pom.xml
Labels: team/ui

#20318 Remove duplicated properties from the main POM file
  pom.xml
Labels: flaky-test

#20266 Replace guide with a placeholder for downstream docs
  docs/documentation/pom.xml
  docs/documentation/release_notes/topics/18_0_0.adoc
  docs/documentation/release_notes/topics/19_0_0.adoc
  docs/documentation/release_notes/topics/20_0_0.adoc
  docs/documentation/release_notes/topics/21_0_0.adoc
  docs/documentation/securing_apps/topics/docker/docker-overview.adoc
  docs/documentation/securing_apps/topics/oidc/fapi-support.adoc
  docs/documentation/securing_apps/topics/token-exchange/token-exchange.adoc
  docs/documentation/server_admin/topics/authentication/webauthn.adoc
  docs/documentation/server_admin/topics/realms/keys.adoc
  docs/documentation/server_admin/topics/sso-protocols/con-sso-docker.adoc
  docs/documentation/server_admin/topics/sso-protocols/docker.adoc
  docs/documentation/server_admin/topics/user-federation/ldap.adoc
  docs/documentation/server_development/topics/providers.adoc
  docs/documentation/topics/templates/deprecated.adoc
  docs/documentation/topics/templates/document-attributes.adoc
Labels: flaky-test

#19898 Update documentation on user storage provider in Quarkus
  docs/documentation/server_development/images/readonly-user-storage-provider-with-config.png
  docs/documentation/server_development/images/storage-provider-with-config.png
  docs/documentation/server_development/topics/user-storage/augmenting.adoc
  docs/documentation/server_development/topics/user-storage/configuration.adoc
  docs/documentation/server_development/topics/user-storage/registration-query.adoc
  docs/documentation/server_development/topics/user-storage/simple-example.adoc
  docs/documentation/server_development/topics/user-storage/stream-interfaces.adoc
Labels: area/docs, area/storage, team/store

#8574 KEYCLOAK-19539 FAPI 2.0 Baseline : Reject Implicit Grant
  docs/documentation/server_admin/topics/clients/client-policies.adoc
  services/src/main/java/org/keycloak/services/clientpolicy/executor/RejectImplicitGrantExecutor.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/RejectImplicitGrantExecutorFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.services.clientpolicy.executor.ClientPolicyExecutorProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ClientPoliciesUtil.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#19889 Updates Datastore provider to contain full data model
  model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyDatastoreProvider.java
  model/map/src/main/java/org/keycloak/models/map/datastore/ImportKeycloakSession.java
  model/map/src/main/java/org/keycloak/models/map/datastore/MapDatastoreProvider.java
  server-spi-private/src/main/java/org/keycloak/storage/DatastoreProvider.java
  server-spi/src/main/java/org/keycloak/models/KeycloakSession.java
  server-spi/src/main/java/org/keycloak/models/SingleUseObjectProvider.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientSecretAuthenticator.java
  services/src/main/java/org/keycloak/credential/OTPCredentialProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenRevocationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/endpoints/BackchannelAuthenticationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/device/DeviceGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/device/endpoints/DeviceEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/par/endpoints/ParEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/par/endpoints/request/AuthzEndpointParParser.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/OAuth2CodeParser.java
  services/src/main/java/org/keycloak/protocol/saml/SamlProtocol.java
  services/src/main/java/org/keycloak/protocol/saml/SamlService.java
  services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsServiceChecks.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/saml/HandleArtifactStepBuilder.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/singleUseObject/SingleUseObjectModelTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20116 Removing duplicated serverPrincipal at LDAPStorageProviderFactory.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProviderFactory.java
Labels: flaky-test

#20243 Adhere to HTML standard when using ul-element
  themes/src/main/resources/theme/base/login/login.ftl
  themes/src/main/resources/theme/keycloak/login/resources/css/login.css
Labels: flaky-test

#20235 added default value back when not new
  js/apps/admin-ui/cypress/e2e/realm_settings_events_test.spec.ts
  js/apps/admin-ui/src/client-scopes/details/MappingDetails.tsx
  js/apps/admin-ui/src/components/dynamic/BooleanComponent.tsx
  js/apps/admin-ui/src/components/dynamic/DynamicComponents.tsx
  js/apps/admin-ui/src/components/dynamic/components.ts
Labels: team/ui, flaky-test

#20403 Use non-blocking random generator on Linux, and native Microsoft CryptoAPI on Windows
  quarkus/dist/src/main/content/bin/kc.bat
  quarkus/dist/src/main/content/bin/kc.sh
Labels: team/cloud-native, flaky-test

#20295 Fix otp on credentials page.
  js/apps/admin-ui/src/user/UserCredentials.tsx
Labels: team/ui

#20201 Allow changing admin console logo and favicon from theme.properties
  js/apps/admin-ui/pom.xml
  js/apps/admin-ui/src/PageHeader.tsx
  js/apps/admin-ui/src/dashboard/Dashboard.tsx
  js/apps/admin-ui/src/environment.ts
Labels: team/ui, flaky-test

#20014 NPE when updating a subflow in an authentication flow
  services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java
Labels: team/core

#20359 Reorder chapters in server guide
  docs/guides/assembly.xml
  docs/guides/server/pinned-guides
Labels: team/cloud-native

#20420 use addError so we see the message
  js/apps/admin-ui/src/identity-providers/add/AddSamlConnect.tsx
Labels: team/ui

#17577 Avoid NPE while fetching offline sessions
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/UserSessionAdapter.java
  model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionAdapter.java
  model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionProvider.java
  server-spi/src/main/java/org/keycloak/models/UserSessionProvider.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
Labels: team/store, flaky-test

#19062 Added User-Session Note Idp mapper.
  services/src/main/java/org/keycloak/broker/oidc/mappers/AbstractClaimMapper.java
  services/src/main/java/org/keycloak/broker/oidc/mappers/ClaimToUserSessionNoteMapper.java
  services/src/main/resources/META-INF/services/org.keycloak.broker.provider.IdentityProviderMapper
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/OidcClaimToUserSessionNoteMapperTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20264 Separate version properties for hibernate-enhance and quarkus-maven
  model/map-jpa/pom.xml
  operator/pom.xml
  pom.xml
  quarkus/deployment/pom.xml
  quarkus/runtime/pom.xml
  quarkus/server/pom.xml
  quarkus/set-quarkus-version.sh
Labels: team/cloud-native, team/store, flaky-test

#20302 Upgrade to Quarkus 3.0.3.Final
  pom.xml
Labels: team/store, flaky-test

#19050 Make LDAP `searchForUsersStream` consistent with other storages
  docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc
  federation/ldap/pom.xml
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/query/internal/LDAPQuery.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPContextManager.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPIdentityStore.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPOperationManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/AbstractLDAPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPSearchForUsersPaginationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/noimport/LDAPSearchForUsersPaginationNoImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/migration-test/migration-realm-1.9.8.Final.json
  testsuite/integration-arquillian/tests/base/src/test/resources/model/testrealm.json
Labels: team/cloud-native, team/store, team/core, flaky-test

#20429 Reduce the amount of duplicated security alerts for the Quarkus distribution
  .github/workflows/snyk-analysis.yml
Labels: team/cloud-native

#20422 Remove log4j dependency from model/jpa which is EOL
  model/jpa/pom.xml
  model/jpa/src/test/resources/log4j.properties
  model/jpa/src/test/resources/logging.properties
  pom.xml
Labels: team/store, flaky-test

#20462 Fix processing of env variable references
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PropertyMappingInterceptor.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/OptionsDistTest.java
  quarkus/tests/integration/src/test/resources/OptionsDistTest/keycloak.conf
Labels: team/cloud-native, flaky-test

#20080 Removes AccountFederatedIdentityPage from testsuite
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/AccountFederatedIdentityPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractAdvancedBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AccountLinkTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerWithConsentTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/AccountHelper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/TestAppHelper.java
Labels: priority/critical, team/cloud-native, team/store, team/core, flaky-test

#20473 Avoid optimistic locking queries on CockroachDB to avoid rolling back transactions
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/EventListenerIntegrator.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/authSession/JpaRootAuthenticationSessionMapStorage.java
  model/map-jpa/src/main/resources/META-INF/jpa-map/queries-default.properties
Labels: team/store, flaky-test

#20474 Avoid querying with secondary columns which might fetch and lock additional rows
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorage.java
  model/map/src/main/java/org/keycloak/models/map/singleUseObject/MapSingleUseObjectProvider.java
  model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionProvider.java
Labels: team/store, flaky-test

#20396 User search with LDAP federation not consistent
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPProvidersIntegrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPSearchForUsersPaginationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/noimport/LDAPSearchForUsersPaginationNoImportTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20493 Fix processing of env variable references
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PropertyMappingInterceptor.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/OptionsDistTest.java
  quarkus/tests/integration/src/test/resources/OptionsDistTest/keycloak.conf
Labels: team/cloud-native

#20360 jakarta package
  adapters/oidc/jakarta-servlet-filter/pom.xml
Labels: flaky-test

#20511 Memory leak with PathCache.cache growing due the map was not synchron…
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/PathCache.java
Labels: flaky-test

#20535 Replace `ChromeJavascriptBrowser` annotation with `JavascriptBrowser`
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/ChromeJavascriptBrowser.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/example/cors/CorsExampleAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
Labels: area/testsuite, kind/task, team/continuous-testing

#20512 Update of the Server Development doc about how 'User Storage Providers' must adhere to Quarkus.
  docs/documentation/server_development/topics/user-storage/javaee.adoc
Labels: area/docs, area/dist/quarkus, team/cloud-native

#20538 Raise required version of Node.js to 18
  js/libs/keycloak-admin-client/package.json
Labels: team/ui

#20539 19847 / 20498 - Fix Split UsersSection into components for better maintainability
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
Labels: team/ui

#20545 Update dependencies to latest version
  js/apps/account-ui/package.json
  js/apps/admin-ui/package.json
  js/apps/keycloak-server/package.json
  js/libs/keycloak-admin-client/package.json
  js/libs/keycloak-js/package.json
  js/libs/keycloak-masthead/package.json
  js/libs/ui-shared/package.json
  js/package.json
  js/pnpm-lock.yaml
Labels: area/dependencies, kind/task, team/ui

#17289 Update example custom cache configuration for v>21
  docs/guides/server/caching.adoc
Labels: area/docs, team/cloud-native, team/store

#20246 added missing fields when dynamic scope is enabled
  js/apps/admin-ui/public/resources/en/client-scopes-help.json
  js/apps/admin-ui/public/resources/en/client-scopes.json
  js/apps/admin-ui/src/client-scopes/details/ScopeForm.tsx
  js/apps/admin-ui/src/components/SwitchControl.tsx
  js/apps/admin-ui/src/utils/useIsFeatureEnabled.ts
  js/libs/ui-shared/src/controls/SwitchControl.tsx
Labels: team/ui

#20247 added check for undefined
  js/apps/admin-ui/src/clients/add/LogoutPanel.tsx
Labels: team/ui

#20312 added min length > 0 check to required
  js/apps/admin-ui/src/user/UserProfileFields.tsx
Labels: team/ui

#20313 empty array instead of null
  js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx
Labels: team/ui

#20408 add disabled and required to User Profile fields
  js/apps/account-ui/src/personal-info/FormField.tsx
Labels: team/ui

#20546 Enable Firefox for WebAuthn and Account Console tests
  .github/workflows/ci.yml
Labels: flaky-test

#20542 Fix KcCustomOidcBrokerTest
  model/map/src/main/java/org/keycloak/models/map/realm/MapRealmAdapter.java
  model/map/src/main/java/org/keycloak/models/map/realm/entity/MapIdentityProviderEntity.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcCustomOidcBrokerTest.java
Labels: team/cloud-native, team/store, team/core

#20406 Don't remove an element from the cache that was queued to be created during the current request
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanKeycloakTransaction.java
Labels: team/store, flaky-test

#20271 remove fields when standard flow disabled
  js/apps/admin-ui/src/clients/add/LoginSettings.tsx
Labels: team/ui

#20544 Use `sandbox` attibute for iframes created by Keycloak JS
  js/libs/keycloak-js/src/keycloak.js
Labels: area/adapter/javascript, team/ui, kind/security-hardening

#20524 Changing the email address has no impact at username regardless "Email as username" toggle
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20557 Ensure client secret is encoded properly in `Authorization` header
  js/libs/keycloak-admin-client/src/utils/auth.ts
Labels: team/ui

#20410 be sure to only select one if type is not multi
  js/apps/admin-ui/src/clients/authorization/ResourcesPolicySelect.tsx
Labels: team/ui

#20561 Update Quarkus to 3.0.4.Final
  pom.xml
Labels: team/cloud-native, flaky-test

#20375 SmallRye Keystore
  docs/guides/server/configuration.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/ConfigKeystoreOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionCategory.java
  quarkus/runtime/pom.xml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ConfigKeystorePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/runtime/src/test/resources/META-INF/keycloak.conf
  quarkus/runtime/src/test/resources/keystore
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java
  quarkus/tests/integration/src/test/resources/keystore
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.unix.approved.txt
Labels: team/cloud-native, flaky-test

#20208 added PostBrokerLoginFlow to idp used by query
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AuthenticationManagementResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/AuthenticationMapper.java
Labels: team/ui

#20516 Improve third-party storage access detection and cookie fallback
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step1.html
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step2.html
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/login-status-iframe.html
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LoginStatusIframeEndpointTest.java
Labels: team/cloud-native, team/store, team/core, team/ui

#20593 Add correct Node.js version range for Admin Client
  js/libs/keycloak-admin-client/package.json
Labels: team/ui

#20236 added error on password confirm on password change
  js/apps/admin-ui/src/user/user-credentials/ResetPasswordDialog.tsx
Labels: team/ui

#20594 Raise required version of Node.js to 18
  js/libs/keycloak-admin-client/package.json
Labels: team/ui

#20597 Add href to brand of Masthead
  js/apps/account-ui/src/root/Root.tsx
  js/libs/keycloak-masthead/src/Masthead.tsx
Labels: team/ui

#20286 moved filter to it's own component
  js/apps/admin-ui/src/sessions/SessionsSection.tsx
Labels: team/ui

#20600 Introduced additional dependencies in the testsuite
  testsuite/integration-arquillian/servers/app-server/jboss/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#20598 Due to a bug in chromedriver version < 113.0.5672.92, temporarily ignoring some tests.
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/InternationalizationTest.java
  testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/account/WebAuthnSigningInTest.java
Labels: team/cloud-native, team/store, team/core, team/ui

#13086 [ISSUE-13084] - Fix msDS-UserPasswordExpired user password expiration
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/msadlds/MSADLDSUserAccountControlStorageMapper.java
Labels: flaky-test

#20585 Show warning message when overriding build options during starts
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/Configuration.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PersistedConfigSource.java
  quarkus/runtime/src/main/resources/META-INF/keycloak.conf
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesAutoBuildDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ShowConfigCommandDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
Labels: team/cloud-native, flaky-test

#20237 allow specifying format of "permission" parameter in the UMA grant token endpoint (#15947)
  authz/client/src/main/java/org/keycloak/authorization/client/util/HttpMethodAuthenticator.java
  core/src/main/java/org/keycloak/representations/idm/authorization/AuthorizationRequest.java
  docs/documentation/authorization_services/topics/service-authorization-obtaining-permission.adoc
  services/src/main/java/org/keycloak/authorization/authorization/AuthorizationTokenService.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/AbstractResourceServerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UmaGrantTypeTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20612 Tests for user property mapper
  core/src/main/java/org/keycloak/representations/idm/ClientScopeRepresentation.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OIDCProtocolMappersTest.java
Labels: team/cloud-native, team/store, team/core

#20573 Backport 20459 to 21.1
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20566 Use cached policy store in Infinispan PolicyAdapter
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/authorization/PolicyAdapter.java
Labels: team/store, flaky-test

#20581 Fix User Event Types not visible when 'Save events disabled`
  js/apps/admin-ui/src/realm-settings/event-config/EventsTab.tsx
Labels: team/ui

#20552 removed need to query all groups
  js/apps/admin-ui/src/user/UserGroups.tsx
Labels: team/ui

#20399 Fix LDAP user synchronization documentation
  docs/documentation/server_admin/topics/user-federation/ldap.adoc
  docs/documentation/server_admin/topics/users/proc-searching-user.adoc
Labels: area/docs, area/storage, team/store

#20553 use display header when set
  js/apps/admin-ui/src/user/UserProfileFields.tsx
Labels: team/ui

#20589 use the first value from options as default
  js/apps/admin-ui/src/components/dynamic/ListComponent.tsx
Labels: team/ui

#20647 added should dirty
  js/apps/admin-ui/src/realm-settings/event-config/EventConfigForm.tsx
Labels: team/ui

#20591 navigate back to list when deleted
  js/apps/admin-ui/src/client-scopes/EditClientScope.tsx
Labels: team/ui

#20607 Removing OpenShift integration and moving to separate extension
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
  dependencies/server-all/pom.xml
  docs/documentation/release_notes/topics/22_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc
  federation/sssd/pom.xml
  misc/keycloak-test-helper/src/main/java/org/keycloak/test/builders/UserBuilder.java
  model/legacy-services/pom.xml
  model/legacy-services/src/main/java/org/keycloak/storage/openshift/OpenshiftClientStorageProvider.java
  model/legacy-services/src/main/java/org/keycloak/storage/openshift/OpenshiftClientStorageProviderFactory.java
  model/legacy-services/src/main/java/org/keycloak/storage/openshift/OpenshiftSAClientAdapter.java
  model/legacy-services/src/main/resources/META-INF/services/org.keycloak.storage.client.ClientStorageProviderFactory
  model/legacy/pom.xml
  pom.xml
  quarkus/runtime/pom.xml
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FeaturesDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
  services/src/main/java/org/keycloak/protocol/openshift/OpenShiftTokenReviewEndpoint.java
  services/src/main/java/org/keycloak/protocol/openshift/OpenShiftTokenReviewEndpointFactory.java
  services/src/main/java/org/keycloak/protocol/openshift/OpenShiftTokenReviewRequestRepresentation.java
  services/src/main/java/org/keycloak/protocol/openshift/OpenShiftTokenReviewResponseRepresentation.java
  services/src/main/resources/META-INF/services/org.keycloak.protocol.oidc.ext.OIDCExtProviderFactory
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/HardcodedGroupStorageProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/openshift/OpenShiftTokenReviewEndpointTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/openshift/OpenshiftClientStorageTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/openshift/client-storage/api-v1.json
  testsuite/integration-arquillian/tests/base/src/test/resources/openshift/client-storage/api.json
  testsuite/integration-arquillian/tests/base/src/test/resources/openshift/client-storage/apis-response.json
  testsuite/integration-arquillian/tests/base/src/test/resources/openshift/client-storage/apis-route-v1.json
  testsuite/integration-arquillian/tests/base/src/test/resources/openshift/client-storage/namespace-default.json
  testsuite/integration-arquillian/tests/base/src/test/resources/openshift/client-storage/oapi-response.json
  testsuite/integration-arquillian/tests/base/src/test/resources/openshift/client-storage/oapi-v1.json
  testsuite/integration-arquillian/tests/base/src/test/resources/openshift/client-storage/openshift-version.json
  testsuite/integration-arquillian/tests/base/src/test/resources/openshift/client-storage/route-response.json
  testsuite/integration-arquillian/tests/base/src/test/resources/openshift/client-storage/sa-oauth-redirect-reference.json
  testsuite/integration-arquillian/tests/base/src/test/resources/openshift/client-storage/sa-oauth-redirect-uri.json
  testsuite/integration-arquillian/tests/base/src/test/resources/openshift/client-storage/sa-system.json
  testsuite/integration-arquillian/tests/base/testsuites/base-suite
Labels: team/cloud-native, team/store, team/core, flaky-test

#20638 FAPI 2.0 security profile - Reject Implicit Grant executor does not return an appropriate error
  services/src/main/java/org/keycloak/services/clientpolicy/executor/RejectImplicitGrantExecutor.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20213 Improve a11y by providing the current language in theme HTML
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/LoginPageTest.java
  themes/src/main/resources/theme/base/account/template.ftl
  themes/src/main/resources/theme/base/login/template.ftl
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#20665 Upgrade Operator to QOSDK 4.0.9
  operator/pom.xml
Labels: team/cloud-native

#20644 Made tree view paging based on count query (#19758)
  js/apps/admin-ui/src/groups/components/GroupTree.tsx
Labels: team/ui

#20595 Improve third-party storage access detection and cookie fallback
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step1.html
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step2.html
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/login-status-iframe.html
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LoginStatusIframeEndpointTest.java
Labels: team/cloud-native, team/store, team/core

#20447 `LDAPStorageProvider` count queries
  docs/documentation/server_development/topics/user-storage/provider-capability-interfaces.adoc
  docs/documentation/server_development/topics/user-storage/registration-query.adoc
  docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java
  model/legacy/src/main/java/org/keycloak/storage/UserStorageProvider.java
  server-spi/src/main/java/org/keycloak/storage/user/UserCountMethodsProvider.java
  server-spi/src/main/java/org/keycloak/storage/user/UserQueryMethodsProvider.java
  server-spi/src/main/java/org/keycloak/storage/user/UserQueryProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/UserPropertyFileStorage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPCountQueryTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20678 FAPI 2.0 security profile - not allow an authorization request whose parameters were not included in PAR request
  docs/documentation/server_admin/topics/clients/client-policies.adoc
  services/src/main/java/org/keycloak/services/clientpolicy/executor/SecureParContentsExecutor.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/SecureParContentsExecutorFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.services.clientpolicy.executor.ClientPolicyExecutorProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesTest.java
Labels: team/cloud-native, team/store, team/core

#20518 Add escaping for fields with wildcard search
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/query/EscapeStrategy.java
  federation/ldap/src/test/java/org/keycloak/storage/ldap/idm/model/EscapeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPProvidersIntegrationTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20660 Fix for certificate revalidation
  services/src/main/java/org/keycloak/authentication/authenticators/x509/CertificateValidator.java
  services/src/main/java/org/keycloak/truststore/FileTruststoreProviderFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/client/resources/TestingResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509BrowserLoginTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20659 Migration guide for JAX-RS changes
  docs/documentation/release_notes/topics/22_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc
  services/src/main/java/org/keycloak/authorization/admin/PolicyService.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
Labels: flaky-test

#20417 added fine-grained auth on EffectiveRoleMappingResource
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/EffectiveRoleMappingResource.java
Labels: team/ui, flaky-test

#20413 use the "remember me" max time if set for expires
  services/src/main/java/org/keycloak/services/resources/account/SessionResource.java
Labels: team/ui
