Repository keycloak/keycloak, pull requests merged in 2023-12, with the labels that each got.

#25195 skipping the revocation tests
  js/apps/admin-ui/cypress/e2e/sessions_test.spec.ts
Labels: team/ui

#25196 skipping the revocation tests (#25195)
  js/apps/admin-ui/cypress/e2e/sessions_test.spec.ts
Labels: team/ui

#25157 Attempt to request storage access for cookies (#25055)
  js/libs/keycloak-js/src/keycloak.js
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step1.html
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/login-status-iframe.html
Labels: team/ui, flaky-test

#25197 If application has no URL, render text only (#25138)
  js/apps/account-ui/src/applications/Applications.tsx
Labels: team/ui

#25198 If application has no URL, render text only (#25138)
  js/apps/account-ui/src/applications/Applications.tsx
Labels: team/ui

#25180 Make sure username is lowercase when normalizing attributes
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25203 Unify utils for interpolated labels under `ui-shared`
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
  js/apps/account-ui/src/personal-info/utils.ts
  js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx
  js/apps/admin-ui/src/user/CreateUser.tsx
  js/apps/admin-ui/src/user/EditUser.tsx
  js/apps/admin-ui/src/user/UserForm.tsx
  js/apps/admin-ui/src/user/utils.ts
  js/libs/ui-shared/package.json
  js/libs/ui-shared/src/main.ts
  js/libs/ui-shared/src/user-profile/MultiInputComponent.tsx
  js/libs/ui-shared/src/user-profile/UserProfileFields.tsx
  js/libs/ui-shared/src/user-profile/UserProfileGroup.tsx
  js/libs/ui-shared/src/user-profile/utils.ts
  js/pnpm-lock.yaml
Labels: team/ui

#25207 Add UP decorator to SSSD provider
  federation/sssd/src/main/java/org/keycloak/federation/sssd/SSSDFederationProvider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginUpdateProfilePage.java
  testsuite/integration-arquillian/tests/other/sssd/pom.xml
  testsuite/integration-arquillian/tests/other/sssd/src/test/java/org/keycloak/testsuite/sssd/AbstractBaseSSSDTest.java
  testsuite/integration-arquillian/tests/other/sssd/src/test/java/org/keycloak/testsuite/sssd/SSSDTest.java
  testsuite/integration-arquillian/tests/other/sssd/src/test/java/org/keycloak/testsuite/sssd/SSSDUserProfileTest.java
Labels: team/cloud-native, team/store, team/core

#25206 Remove GlobalLockProviderSpi
  model/legacy-private/src/main/java/org/keycloak/models/dblock/DBLockGlobalLockProvider.java
  model/legacy-private/src/main/java/org/keycloak/models/dblock/DBLockGlobalLockProviderFactory.java
  model/legacy-private/src/main/resources/META-INF/services/org.keycloak.models.locking.GlobalLockProviderFactory
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/database/LegacyJpaConnectionProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/models/locking/GlobalLockProvider.java
  server-spi-private/src/main/java/org/keycloak/models/locking/GlobalLockProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/models/locking/GlobalLockProviderSpi.java
  server-spi-private/src/main/java/org/keycloak/models/locking/LockAcquiringTimeoutException.java
  server-spi-private/src/main/resources/META-INF/services/org.keycloak.provider.Spi
  services/pom.xml
  services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java
  testsuite/integration-arquillian/tests/base/src/test/resources/META-INF/keycloak-server.json
  testsuite/model/src/test/java/org/keycloak/testsuite/model/KeycloakModelTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/globalLock/GlobalLocksTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/LegacyJpa.java
  testsuite/utils/src/main/resources/META-INF/keycloak-server.json
Labels: team/cloud-native, team/store, team/core, flaky-test

#25012 Ignore JDBC Drivers artifacts
  quarkus/config-api/src/main/java/org/keycloak/config/ClassLoaderOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Build.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/IgnoredArtifacts.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ClassLoaderPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/IgnoredArtifactsTest.java
Labels: team/cloud-native, flaky-test

#25222 Add PatternFly 5 to the 'common' Keycloak theme
  themes/src/main/resources/theme/keycloak/common/resources/package.json
  themes/src/main/resources/theme/keycloak/common/resources/pnpm-lock.yaml
Labels: kind/task, team/ui, flaky-test

#25174 Add tests for lb-check endpoint
  .github/workflows/ci.yml
  docs/guides/high-availability/concepts-active-passive-sync.adoc
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HealthDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/ExternalInfinispanTest.java
  quarkus/tests/integration/src/test/resources/ExternalInfinispan/kcb-infinispan-cache-remote-store-config.xml
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/CLITestExtension.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/DatabaseContainer.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/InfinispanContainer.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/WithExternalInfinispan.java
Labels: team/cloud-native, flaky-test

#25081 Update springboot version
  pom.xml
  testsuite/integration-arquillian/HOW-TO-RUN.md
  testsuite/integration-arquillian/test-apps/spring-boot-adapter-app/pom.xml
  testsuite/integration-arquillian/tests/other/springboot-tests/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#25229 Add active RSA key to decryption if deprecated mode (#25205)
  services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java
Labels: flaky-test

#25239 Add missing Arabic messages
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_ar.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ar.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_ar.properties
Labels: team/ui, flaky-test

#25257 Add tests for lb-check endpoint
  .github/workflows/ci.yml
  docs/guides/high-availability/concepts-active-passive-sync.adoc
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HealthDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/ExternalInfinispanTest.java
  quarkus/tests/integration/src/test/resources/ExternalInfinispan/kcb-infinispan-cache-remote-store-config.xml
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/CLITestExtension.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/DatabaseContainer.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/InfinispanContainer.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/WithExternalInfinispan.java
Labels: team/cloud-native, flaky-test

#25155 Remove 'Product' information from dashboard
  js/apps/admin-ui/src/dashboard/Dashboard.tsx
Labels: team/ui

#25256 Add tests for lb-check endpoint
  .github/workflows/ci.yml
  docs/guides/high-availability/concepts-active-passive-sync.adoc
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HealthDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/ExternalInfinispanTest.java
  quarkus/tests/integration/src/test/resources/ExternalInfinispan/kcb-infinispan-cache-remote-store-config.xml
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/CLITestExtension.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/InfinispanContainer.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/WithExternalInfinispan.java
Labels: team/cloud-native, flaky-test

#25044 Update polish translation of theme/base/account properties
  themes/src/main/resources-community/theme/base/account/messages/messages_pl.properties
Labels: area/translations, flaky-test

#25164 Fix 'Cancel' button in the user form (#25161)
  js/apps/admin-ui/src/user/UserForm.tsx
Labels: team/ui

#25106 Pass MAVEN_ARGS manually to mvnw as they are only supported in Maven 3.9
  .github/workflows/ci.yml
Labels: flaky-test

#25117 Align maven parameters across GitHub actions
  .github/actions/build-keycloak/action.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/documentation.yml
  .github/workflows/guides.yml
  .github/workflows/js-ci.yml
  .github/workflows/operator-ci.yml
  .github/workflows/snyk-analysis.yml
Labels: flaky-test

#25286 Fix 'Cancel' button in the user form (#25161)
  js/apps/admin-ui/src/user/UserForm.tsx
Labels: team/ui

#24642 Fix osx missing error post-alignment
  pom.xml
Labels: flaky-test, backport/22.0

#25125 Remove lowercase for the hostname as recommended/advised by OAuth spec
  docs/documentation/upgrading/topics/keycloak/changes-23_0_2.adoc
  docs/documentation/upgrading/topics/keycloak/changes.adoc
  services/src/main/java/org/keycloak/protocol/oidc/utils/RedirectUtils.java
  services/src/test/java/org/keycloak/protocol/oidc/utils/RedirectUtilsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthRedirectUriTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25289 Upgrade Infinispan to 14.0.21.Final
  pom.xml
Labels: flaky-test

#25104 enable dot in attribute when user profile enabled
  js/apps/admin-ui/src/user/form-state.ts
  js/apps/admin-ui/src/util.ts
  js/libs/ui-shared/src/user-profile/utils.ts
Labels: team/ui

#25298 Upgrade Infinispan to 14.0.21.Final
  pom.xml
Labels: flaky-test

#25217 Prevent client cache stampede after invalidation of a client or on startup
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
Labels: team/store, flaky-test

#25267 [backport/release:23] Make sure username is lowercase when normalizing attributes
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/store, team/core

#25313 Make sure realm is available from session when migrating to 23
  model/legacy-private/src/main/java/org/keycloak/migration/migrators/MigrateTo23_0_0.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusConfiguration.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
  testsuite/integration-arquillian/tests/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#25325 Make sure realm is available from session when migrating to 23
  model/legacy-private/src/main/java/org/keycloak/migration/migrators/MigrateTo23_0_0.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusConfiguration.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
  testsuite/integration-arquillian/tests/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#25280 Allow authorization changes with fine-grained client access and manag…
  js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx
  js/apps/admin-ui/src/clients/routes/PermissionDetails.tsx
  js/apps/admin-ui/src/clients/routes/PolicyDetails.tsx
  js/apps/admin-ui/src/clients/routes/Resource.tsx
Labels: team/ui

#25296 Workaround to allow percent chars in getGroupByPath via PathSegment
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java
Labels: status/hold, team/cloud-native, team/store, team/core, flaky-test

#25327 Removing unnecessary property from auth-server-migration maven profile
  testsuite/integration-arquillian/tests/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#25346 Revert changes to OIDCIdentityProvider that enlisted the client logou…
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
Labels: area/storage, team/store

#25347 Remove ResponseSessionTask
  services/src/main/java/org/keycloak/common/util/ResponseSessionTask.java
Labels: area/storage, team/store

#25371 Ignore `target` directory when running ESLint
  js/.eslintrc.cjs
Labels: kind/task, team/ui

#25329 Added tests for client scopes/evaluate tab
  js/apps/admin-ui/cypress/e2e/client_registration_policies.spec.ts
  js/apps/admin-ui/cypress/e2e/clients_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/ClientRegistrationPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/ClientDetailsPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/tabs/ClientScopesTab.ts
  js/apps/admin-ui/src/clients/ClientDetails.tsx
  js/apps/admin-ui/src/clients/registration/ClientRegistrationList.tsx
  js/apps/admin-ui/src/clients/scopes/EvaluateScopes.tsx
Labels: team/ui

#25323 Map Store Removal: Remove `LockObjectsForModification`
  server-spi-private/src/main/java/org/keycloak/utils/LockObjectsForModification.java
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
  services/src/main/java/org/keycloak/authentication/authenticators/sessionlimits/UserSessionLimitsAuthenticator.java
  services/src/main/java/org/keycloak/authorization/authorization/AuthorizationTokenService.java
  services/src/main/java/org/keycloak/authorization/common/KeycloakIdentity.java
  services/src/main/java/org/keycloak/broker/oidc/KeycloakOIDCIdentityProvider.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/device/DeviceGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/OAuth2CodeParser.java
  services/src/main/java/org/keycloak/protocol/saml/SamlService.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationSessionManager.java
  services/src/main/java/org/keycloak/services/managers/UserSessionCrossDCManager.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsServiceChecks.java
  services/src/main/java/org/keycloak/services/resources/SessionCodeChecks.java
  services/src/main/java/org/keycloak/services/resources/account/SessionResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionConcurrencyTest.java
Labels: team/store, flaky-test

#25376 Realm roles tests (admin-ui)
  js/apps/admin-ui/cypress/e2e/realm_roles_test.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_user_registration.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/ClientRolesTab.ts
  js/apps/admin-ui/src/realm-roles/UsersInRoleTab.tsx
  js/apps/admin-ui/src/realm-settings/UserRegistration.tsx
Labels: team/ui

#25378 25208 MSSQL startup message - fix
  testsuite/integration-arquillian/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#25292 Re-enable Federated Access Token in user sessions
  services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java
Labels: flaky-test

#25389 Fix broken assertion in Cypress tests
  js/apps/admin-ui/cypress/e2e/user_fed_ldap_test.spec.ts
Labels: team/ui

#25390 Allow concurrent remote cache operations
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanNotificationsManager.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/util/InfinispanKeyGenerator.java
Labels: team/store

#25324 Avoid logged warning when remote cache is enabled
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProvider.java
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanNotificationsManager.java
Labels: team/store, flaky-test

#25260 Make sure authz endpoints are documented in openapi spec
  services/src/main/java/org/keycloak/authorization/admin/AuthorizationService.java
  services/src/main/java/org/keycloak/authorization/admin/PermissionService.java
  services/src/main/java/org/keycloak/authorization/admin/PolicyService.java
  services/src/main/java/org/keycloak/authorization/admin/ResourceServerService.java
  services/src/main/java/org/keycloak/authorization/admin/ResourceSetService.java
  services/src/main/java/org/keycloak/authorization/admin/ScopeService.java
Labels: flaky-test

#25411 [enhancement] pr-backport.sh - make it more understandable when using gh and git
  .github/scripts/pr-backport.sh
Labels: flaky-test

#24416 Improved credential select form accessibility
  themes/src/main/resources/theme/base/login/select-authenticator.ftl
  themes/src/main/resources/theme/keycloak/login/resources/css/login.css
Labels: flaky-test

#24216 Fixes for LDAP group membership and search in chunks
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPConfig.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPIdentityStore.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/MembershipType.java
  server-spi-private/src/main/java/org/keycloak/models/LDAPConstants.java
  server-spi-private/src/main/java/org/keycloak/utils/StreamsUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25414 Do not allow removing username and email from user profile configuration
  core/src/main/java/org/keycloak/representations/userprofile/config/UPAttribute.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPAttributePermissions.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPAttributeRequired.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPAttributeSelector.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPConfig.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPGroup.java
  js/apps/admin-ui/cypress/e2e/realm_settings_user_profile_enabled.spec.ts
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesTab.tsx
  services/src/main/java/org/keycloak/userprofile/config/UPConfigUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTestWithUserProfile.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/userprofile/UserProfileAdminTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPAdminRestApiWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/VerifyProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/AbstractUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/config/UPConfigParserTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#25405 Allow incremental build for the themes
  .mvn/extensions.xml
  adapters/oidc/js/pom.xml
  js/pom.xml
  themes/pom.xml
Labels: team/ui, flaky-test

#25450 Cleanup translations for DE/EN for a first test run of Weblate
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
Labels: team/ui, flaky-test

#24933 Idp pager UI
  js/apps/admin-ui/src/identity-providers/IdentityProvidersSection.tsx
  js/apps/admin-ui/src/identity-providers/ManageOrderDialog.tsx
  js/libs/keycloak-admin-client/src/resources/identityProviders.ts
Labels: team/ui

#25348 Add support for logout via POST in Keycloak JS
  js/libs/keycloak-js/dist/keycloak.d.ts
  js/libs/keycloak-js/src/keycloak.js
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/javascript/JavascriptTestExecutor.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#25488 Extra realm settings tests
  js/apps/admin-ui/cypress/e2e/client_registration_policies.spec.ts
  js/apps/admin-ui/cypress/e2e/partial_export_test.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_settings_client_profiles_test.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_settings_events_test.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_settings_general_tab_test.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_settings_tabs_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/ClientRegistrationPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
  js/apps/admin-ui/src/clients/registration/ClientRegistrationList.tsx
  js/apps/admin-ui/src/realm-settings/security-defences/SecurityDefenses.tsx
Labels: team/ui

#24736 Switch locale
  js/apps/account-ui/pom.xml
  js/apps/account-ui/src/environment.ts
  js/apps/account-ui/src/i18n.ts
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
Labels: team/ui, flaky-test

#25435 Iss25307 backport
  docs/documentation/upgrading/topics/keycloak/changes-23_0_2.adoc
  operator/src/main/java/org/keycloak/operator/Utils.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakAdminSecretDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDiscoveryServiceDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakServiceDependentResource.java
Labels: team/cloud-native, flaky-test

#25473 Revert changes related to map store in test classes in base testsuite
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/ModelTestExecutor.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/annotation/ModelTest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakContainerEventsController.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/model/StoreProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/PermissionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ServerInfoTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UsersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupSearchTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AccountLinkTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/AdminEventStoreProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/EventStoreProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPMultipleAttributesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPProvidersIntegrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPRoleMappingsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/noimport/LDAPMultipleAttributesNoImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/noimport/LDAPProvidersIntegrationNoImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/noimport/LDAPRoleMappingsNoImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/ClientStorageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/FederatedStorageExportImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageFailureTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageOTPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/sync/SyncFederationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/BadRealmTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/CacheTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/ConcurrentTransactionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserConsentWithUserStorageModelTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509DirectGrantTest.java
Labels: team/cloud-native, team/store, team/core

#25482 Refactoring user profile interfaces and consolidating user representation for both admin and account contexts
  core/src/main/java/org/keycloak/representations/account/UserRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/AbstractUserRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/UserRepresentation.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPConfig.java
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UserResource.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultUserProfile.java
  server-spi-private/src/main/java/org/keycloak/userprofile/UserProfile.java
  server-spi-private/src/main/java/org/keycloak/userprofile/UserProfileUtil.java
  server-spi/src/main/java/org/keycloak/userprofile/Attributes.java
  server-spi/src/main/java/org/keycloak/userprofile/UserProfileContext.java
  services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpReviewProfileAuthenticator.java
  services/src/main/java/org/keycloak/authentication/forms/RegistrationUserCreation.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateEmail.java
  services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
  services/src/main/java/org/keycloak/services/resources/admin/UserProfileResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/validator/ImmutableAttributeValidator.java
  services/src/main/java/org/keycloak/userprofile/validator/UsernameMutationValidator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceReadOnlyAttributesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/DeclarativeUserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPAdminRestApiWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#25428 Show the original exception when shutdown of Keycloak failed
  .github/scripts/run-fips-it.sh
  .github/workflows/ci.yml
  misc/log/trimmer.sh
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
Labels: team/cloud-native, flaky-test

#25517 Deleting an atribute from the UI is reseting the unmanaged attribute policy
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesTab.tsx
Labels: team/ui

#25178 Add new `--proxy-headers` option
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  docs/guides/server/hostname.adoc
  docs/guides/server/reverseproxy.adoc
  docs/guides/templates/options.adoc
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Options.java
  quarkus/config-api/src/main/java/org/keycloak/config/DeprecatedMetadata.java
  quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/MultiOption.java
  quarkus/config-api/src/main/java/org/keycloak/config/Option.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionBuilder.java
  quarkus/config-api/src/main/java/org/keycloak/config/ProxyOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/OptionRenderer.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ProxyPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HostnameDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ProxyDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.windows.approved.txt
  services/src/main/java/org/keycloak/truststore/FileTruststoreProviderFactory.java
Labels: team/cloud-native, flaky-test

#25492 Avoid shutdown of Infinispan when using cache
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionsLoader.java
Labels: team/store, flaky-test

#25462 fix moving of sub flows
  js/apps/admin-ui/src/authentication/FlowDetails.tsx
Labels: team/ui

#25466 use login realm
  js/apps/admin-ui/src/i18n/i18n.ts
Labels: team/ui

#25507 account.v3 allow adding scripts like in v2
  js/apps/account-ui/pom.xml
Labels: team/ui, flaky-test

#25395 NullPointerException when key is not available in the database
  common/src/main/java/org/keycloak/common/util/KeystoreUtil.java
  services/src/main/java/org/keycloak/keys/ImportedRsaKeyProvider.java
Labels: missing/tests, flaky-test

#25531 Update web elements of the Instagram login page
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social/InstagramLoginPage.java
Labels: team/cloud-native, team/store, team/core

#25550 Update UserProfileProvider.setConfiguration. Tuning of UserProfilePro…
  core/src/main/java/org/keycloak/representations/userprofile/config/UPAttribute.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPAttributePermissions.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPAttributeRequired.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPAttributeSelector.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPConfig.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPGroup.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UIRealmResource.java
  server-spi-private/src/main/java/org/keycloak/userprofile/UserProfileProvider.java
  services/src/main/java/org/keycloak/services/resources/admin/UserProfileResource.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/AbstractUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/CustomUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#25215 enhance: adds truststores to the keycloak cr
  adapters/saml/core/src/main/resources/schema/keycloak_saml_adapter_1_10.xsd
  adapters/saml/core/src/main/resources/schema/keycloak_saml_adapter_1_11.xsd
  adapters/saml/core/src/main/resources/schema/keycloak_saml_adapter_1_12.xsd
  adapters/saml/core/src/main/resources/schema/keycloak_saml_adapter_1_13.xsd
  adapters/saml/core/src/main/resources/schema/keycloak_saml_adapter_1_7.xsd
  adapters/saml/core/src/main/resources/schema/keycloak_saml_adapter_1_8.xsd
  adapters/saml/core/src/main/resources/schema/keycloak_saml_adapter_1_9.xsd
  adapters/saml/wildfly/wildfly-subsystem/src/main/resources/schema/wildfly-keycloak-saml_1_3.xsd
  adapters/saml/wildfly/wildfly-subsystem/src/main/resources/schema/wildfly-keycloak-saml_1_4.xsd
  docs/documentation/release_notes/topics/24_0_0.adoc
  operator/src/main/java/org/keycloak/operator/Constants.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakSpec.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/Truststore.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/TruststoreSource.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakTruststoresTests.java
  operator/src/test/resources/example-truststore-secret.yaml
  services/src/main/java/org/keycloak/truststore/FileTruststoreProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/client/resources/TestingResource.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/AdminClientUtil.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/MutualTLSUtils.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25264 Change arg of getSubGroups to briefRepresentation
  docs/documentation/upgrading/topics/keycloak/changes-23_0_3.adoc
  docs/documentation/upgrading/topics/keycloak/changes.adoc
  services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java
Labels: missing/tests, team/cloud-native, team/store, team/core, flaky-test

#25429 Avoid logged warning about objects not present in the cache for tasks
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProvider.java
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanNotificationsManager.java
Labels: team/store, flaky-test

#25407 Allow concurrent remote cache operations
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanNotificationsManager.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/util/InfinispanKeyGenerator.java
Labels: team/store, flaky-test

#25494 Keep workaround permanently for concurrent shutdowns of embedded Infinispan
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanNotificationsManager.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java
Labels: team/store

#25409 25208 MSSQL startup message - fix (#25378)
  testsuite/integration-arquillian/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#25410 25208 MSSQL startup message - fix (#25378)
  testsuite/integration-arquillian/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#25426 Introduce ProtocolMapper.getEffectiveModel to make sure values displa…
  server-spi-private/src/main/java/org/keycloak/protocol/ProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractOIDCProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AllowedWebOriginsProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AudienceResolveProtocolMapper.java
  services/src/main/java/org/keycloak/services/resources/admin/ProtocolMappersResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/ClientProtocolMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/ClientScopeProtocolMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportUtil.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25432 Fix broken assertion in Cypress tests (#25389)
  js/apps/admin-ui/cypress/e2e/user_fed_ldap_test.spec.ts
Labels: team/ui

#25526 Fix resource path for account console
  themes/src/main/resources/theme/keycloak.v2/account/src/.babelrc
Labels: team/ui, flaky-test

#25577 Do not show sign-out action for offline sessions
  js/apps/admin-ui/cypress/e2e/sessions_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/components/TablePage.ts
  js/apps/admin-ui/cypress/support/util/AdminClient.ts
  js/apps/admin-ui/src/sessions/SessionsTable.tsx
Labels: team/ui

#25472 don't add empty key values
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/AddMapperPage.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/components/dynamic/MapComponent.tsx
  js/apps/admin-ui/src/components/key-value-form/KeyValueInput.tsx
Labels: team/ui

#25476 Do not allow remove a credential in account endpoint if provider marks it as not removable
  services/src/main/java/org/keycloak/services/resources/account/AccountCredentialResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25474 Do not allow remove a credential in account endpoint if provider marks it as not removable
  services/src/main/java/org/keycloak/services/resources/account/AccountCredentialResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
Labels: team/cloud-native, team/store, team/core

#25610 PubKeySignRegisterTest failures in WebAuthn tests
  testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/registration/PubKeySignRegisterTest.java
Labels: team/cloud-native, team/store, team/core

#25625 PubKeySignRegisterTest failures in WebAuthn tests
  testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/registration/PubKeySignRegisterTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25624 PubKeySignRegisterTest failures in WebAuthn tests
  testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/registration/PubKeySignRegisterTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25605 Add response annotations to resourceserver
  services/src/main/java/org/keycloak/authorization/admin/PolicyEvaluationService.java
  services/src/main/java/org/keycloak/authorization/admin/PolicyService.java
  services/src/main/java/org/keycloak/authorization/admin/ResourceServerService.java
  services/src/main/java/org/keycloak/authorization/admin/ResourceSetService.java
  services/src/main/java/org/keycloak/authorization/admin/ScopeService.java
Labels: flaky-test

#25570 Fix for test SSSDUserProfileTest.test05MixedInternalDBUserProfile
  testsuite/integration-arquillian/tests/other/sssd/src/test/java/org/keycloak/testsuite/sssd/SSSDUserProfileTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25655 remove oauth2DeviceAuthorizationGrantEnabled from ClientRepresentation
  core/src/main/java/org/keycloak/representations/idm/ClientRepresentation.java
Labels: flaky-test

#25554 For post logout redirect URI - Make '+' represent existing redirect URIs and merge with existing post logout redirect URIs
  services/src/main/java/org/keycloak/protocol/oidc/OIDCAdvancedConfigWrapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RPInitiatedLogoutTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25657 Fix OpenAPI spec POST /admin/realms/{realm}/clients-initial-access
  services/src/main/java/org/keycloak/services/resources/admin/ClientInitialAccessResource.java
Labels: flaky-test

#25602 Fix OpenAPI spec POST /admin/realms/{realm}/clients #25601
  services/src/main/java/org/keycloak/services/resources/admin/ClientsResource.java
Labels: flaky-test

#25615 Avoid shutdown of Infinispan when using cache
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionsLoader.java
Labels: team/store, flaky-test

#25442 Client policies : executor for enforcing DPoP
  docs/documentation/server_admin/topics/clients/client-policies.adoc
  services/src/main/java/org/keycloak/services/clientpolicy/executor/DPoPBindEnforcerExecutor.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/DPoPBindEnforcerExecutorFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.services.clientpolicy.executor.ClientPolicyExecutorProviderFactory
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/DPoPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ClientPoliciesUtil.java
Labels: missing/docs, missing/tests, team/cloud-native, team/store, team/core, flaky-test

#25499 User Profile: If required roles ('user') and reqired scopes are set, …
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/AbstractUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25627 fix: improve group matching
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/operations/GroupOperations.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/util/HttpUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25587 Change arg of getSubGroups to briefRepresentation
  docs/documentation/upgrading/topics/keycloak/changes-23_0_4.adoc
  docs/documentation/upgrading/topics/keycloak/changes.adoc
  services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25614 Avoid shutdown of Infinispan when using cache
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionsLoader.java
Labels: team/store, flaky-test

#25616 Showing the original exception plus any swallowed exceptions
  .github/scripts/run-fips-it.sh
  .github/workflows/ci.yml
  misc/log/trimmer.sh
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
Labels: team/cloud-native

#25643 Fixes KeycloakDistConfiguratorTest missingHostname test case.
  operator/src/test/java/org/keycloak/operator/testsuite/unit/KeycloakDistConfiguratorTest.java
Labels: team/cloud-native

#25434 fix: adding filtering to ignore anything runtime during a build
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PropertyMappingInterceptor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.windows.approved.txt
Labels: team/cloud-native, flaky-test

#25586 fix: adding the kube ca cert to the truststores
  docs/documentation/release_notes/topics/24_0_0.adoc
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
Labels: team/cloud-native, flaky-test

#25665 User Profile: If required roles ('user') and reqired scopes are set, …
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/AbstractUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25600 Updating theme templates to render user attributes based on the user profile configuration
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  server-spi-private/src/main/java/org/keycloak/forms/login/LoginFormsPages.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpReviewProfileAuthenticator.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/forms/login/freemarker/Templates.java
  services/src/main/java/org/keycloak/userprofile/LegacyAttributes.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginUpdateProfilePage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/RegisterPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerUiLocalesWithIdpHintTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/theme/CustomRegistrationTemplateTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/theme/CustomRegistrationTemplateUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/theme/CustomUpdateProfileTemplateTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/theme/CustomUpdateProfileTemplateUserProfileTest.java
  testsuite/integration-arquillian/tests/other/sssd/src/test/java/org/keycloak/testsuite/sssd/SSSDUserProfileTest.java
  themes/src/main/resources/theme/base/login/login-update-profile.ftl
  themes/src/main/resources/theme/base/login/register-user-profile.ftl
  themes/src/main/resources/theme/base/login/register.ftl
  themes/src/main/resources/theme/base/login/update-user-profile.ftl
Labels: team/cloud-native, team/store, team/core, flaky-test

#21638 Scope parameter in Oauth 2.0 token exchange
  docs/documentation/securing_apps/topics/token-exchange/token-exchange.adoc
  services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientTokenExchangeTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25606 Escape action in the form_post response mode
  saml-core/src/main/java/org/keycloak/saml/BaseSAML2BindingBuilder.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/OIDCRedirectUriBuilder.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/SamlClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AuthorizationCodeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/saml/BasicSamlTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25588 Ensure 'iss' is returned when 'prompt=none' and user is not authenticated, per RFC9207
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCAdvancedRequestParamsTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25607 Strip off user-info from redirect URI when validating using wildcard
  services/src/main/java/org/keycloak/protocol/oidc/utils/RedirectUtils.java
  services/src/test/java/org/keycloak/protocol/oidc/utils/RedirectUtilsTest.java
Labels: flaky-test

#25620 Migration steps for enabling user profile by default
  model/legacy-private/src/main/java/org/keycloak/migration/migrators/MigrateTo24_0_0.java
  model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyMigrationManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport1903MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport198MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport255MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport343MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport483MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport903MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/MigrationTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25692 More info on UserProfileContext
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  federation/sssd/src/main/java/org/keycloak/federation/sssd/SSSDFederationProvider.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultUserProfile.java
  server-spi-private/src/main/java/org/keycloak/userprofile/UserProfileUtil.java
  server-spi/src/main/java/org/keycloak/userprofile/UserProfileConstants.java
  server-spi/src/main/java/org/keycloak/userprofile/UserProfileContext.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/config/UPConfigUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/config/UPConfigUtilsTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25471 Workaround to allow percent chars in getGroupByPath via PathSegment
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25590 fix: adds --verbose to all commands
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Main.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartDevCommandDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.windows.approved.txt
Labels: team/cloud-native, flaky-test

#25693 Bugfix for: Removing all group attributes no longer works with keycloak-admin-client (java)
  core/src/main/java/org/keycloak/representations/idm/GroupRepresentation.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25573 Make Locale updater generate an event and use the user profile
  services/src/main/java/org/keycloak/locale/DefaultLocaleUpdaterProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/LoginPageTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25732 Update the UPDATE_EMAIL feature to rely on the user profile configuration when rendering templates and validating the email
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  server-spi/src/main/java/org/keycloak/userprofile/UserProfileContext.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/forms/login/freemarker/model/EmailBean.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AbstractAppInitiatedActionUpdateEmailTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AbstractRequiredActionUpdateEmailTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionUpdateEmailUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
  themes/src/main/resources/theme/base/login/update-email.ftl
Labels: team/cloud-native, team/store, team/core, flaky-test

#25739 Tooltips improvements when configuring user profile attribute
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
Labels: team/ui

#22940 Add raw OpenApi documentation files to rest-api documentation
  services/pom.xml
  services/src/docs/openapi-generator-templates/keycloak-admin-api/index.mustache
Labels: flaky-test

#25634 Adding parsing of "fixes"/"fixed" Keyword and the colon
  .github/scripts/pr-find-issues-test.sh
  .github/scripts/pr-find-issues.sh
Labels: flaky-test

#25756 Adding parsing of "fixes"/"fixed" Keyword and the colon
  .github/scripts/pr-find-issues-test.sh
  .github/scripts/pr-find-issues.sh
Labels: flaky-test

#25755 Adding parsing of "fixes"/"fixed" Keyword and the colon
  .github/scripts/pr-find-issues-test.sh
  .github/scripts/pr-find-issues.sh
Labels: flaky-test

#25785 Add 'scope' field to KeycloakAdminClient
  js/libs/keycloak-admin-client/src/client.ts
  js/libs/keycloak-admin-client/src/utils/auth.ts
Labels: team/ui
