Repository keycloak/keycloak, pull requests merged in 2023-11, with the labels that each got.

#24432 Downgrade transient users to experimental
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FeaturesDistTest.java
Labels: team/cloud-native

#24460 Improve error handling for Fetch calls
  js/apps/admin-ui/src/authentication/AuthenticationSection.tsx
  js/apps/admin-ui/src/clients/import/ImportForm.tsx
  js/apps/admin-ui/src/components/download-dialog/DownloadDialog.tsx
  js/apps/admin-ui/src/context/auth/admin-ui-endpoint.ts
  js/apps/admin-ui/src/identity-providers/add/SamlConnectSettings.tsx
  js/libs/keycloak-admin-client/src/index.ts
Labels: team/ui

#24338 Correct the value of option --cache-stack
  docs/guides/server/caching.adoc
Labels: team/cloud-native

#24441 Make sure optional default attributes are removed when decorating the user-define user profile configuration
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24463 Add 'Email Verified' checkbox if user profile is enabled
  js/apps/admin-ui/src/user/UserForm.tsx
Labels: team/ui

#24174 clean util *
  adapters/saml/wildfly-elytron/src/main/java/org/keycloak/adapters/saml/elytron/infinispan/InfinispanSessionCacheIdMapperUpdater.java
  adapters/saml/wildfly-elytron/src/main/java/org/keycloak/adapters/saml/elytron/infinispan/SsoSessionCacheListener.java
  core/src/main/java/org/keycloak/TokenVerifier.java
  docs/documentation/tests/src/test/java/org/keycloak/documentation/test/utils/LinkUtils.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  server-spi-private/src/main/java/org/keycloak/models/utils/DefaultAuthenticationFlows.java
  services/src/main/java/org/keycloak/protocol/saml/mappers/ScriptBasedMapper.java
Labels: team/store, flaky-test

#23778 Escape $ sign when replacing clientId in the role mappers
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractUserRoleMappingMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/UserInfoTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24471 Remove UTF-8 encoding header from property files
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme-preview/account/messages/messages_en.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme-preview/account/messages/messages_test.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme/account/messages/messages_en.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme/account/messages/messages_test.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme/email/messages/messages_en.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme/email/messages/messages_test.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme/login/messages/messages_en.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme/login/messages/messages_test.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_th.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_th.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_th.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_ca.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_de.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_el.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_fa.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_hu.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_th.properties
  themes/src/main/resources/theme/keycloak.v2/account/messages/messages_en.properties
Labels: team/ui, flaky-test

#24478 fix: exceptions should be ignored in until the condition is met
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
Labels: team/cloud-native, flaky-test

#24475 [release/22] Make sure optional default attributes are removed when decorating the user-define user profile configuration
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24249 Map Store Removal: Delete map profiles and scopes from model tests
  testsuite/model/README.md
  testsuite/model/pom.xml
  testsuite/model/src/test/java/org/keycloak/testsuite/model/ConcurrentHashMapStorageTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/client/ClientModelTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/events/EventQueryTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/ConcurrentHashMapStorage.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/FileMapStorage.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/HotRodMapStorage.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/JpaMapStorage.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/JpaMapStorageCockroachdb.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/LdapMapStorage.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/Map.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/HotRodUserSessionClientSessionRelationshipTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionConcurrencyTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionExpirationTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionInitializerTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionPersisterProviderTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderModelTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderOfflineModelTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/singleUseObject/SingleUseObjectModelTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/storage/tree/sample/Dict.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/storage/tree/sample/DictStorage.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/storage/tree/sample/DictTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/transaction/StorageTransactionTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/user/UserModelTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/util/KeycloakAssertions.java
  testsuite/model/src/test/resources/log4j.properties
Labels: team/store, flaky-test

#22568 Preserve user id on partial import
  services/src/main/java/org/keycloak/partialimport/UsersPartialImport.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/partialimport/PartialImportTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24423 Fix IllegalState InjectionManagerFactory not found on springboot tests
  testsuite/integration-arquillian/test-apps/spring-boot-adapter-app/pom.xml
  testsuite/integration-arquillian/tests/other/springboot-tests/pom.xml
  testsuite/integration-arquillian/tests/other/springboot-tests/src/test/java/org/keycloak/testsuite/springboot/AccountLinkSpringBootTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24502 Fix Cypress tests for User Profile
  js/apps/admin-ui/cypress/e2e/realm_settings_user_profile_enabled.spec.ts
Labels: team/ui

#24486 Remove leftover namespaces from translation keys
  js/apps/admin-ui/cypress/e2e/i18n_test.spec.ts
  js/apps/admin-ui/src/authentication/EmptyExecutionState.tsx
  js/apps/admin-ui/src/authentication/policies/PolicyRow.tsx
  js/apps/admin-ui/src/clients/add/SamlConfig.tsx
  js/apps/admin-ui/src/clients/advanced/TokenLifespan.tsx
  js/apps/admin-ui/src/clients/authorization/PermissionDetails.tsx
  js/apps/admin-ui/src/clients/authorization/policy/Time.tsx
  js/apps/admin-ui/src/clients/credentials/Credentials.tsx
  js/apps/admin-ui/src/clients/keys/Certificate.tsx
  js/apps/admin-ui/src/clients/keys/SamlKeys.tsx
  js/apps/admin-ui/src/clients/scopes/ClientScopes.tsx
  js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx
  js/apps/admin-ui/src/components/users/UserSelect.tsx
  js/apps/admin-ui/src/events/EventsSection.tsx
  js/apps/admin-ui/src/realm-settings/DefaultGroupsTab.tsx
  js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
  js/apps/admin-ui/src/realm-settings/NewClientPolicyCondition.tsx
  js/apps/admin-ui/src/realm-settings/event-config/EventConfigForm.tsx
  js/apps/admin-ui/src/realm-settings/event-config/EventsTab.tsx
  js/apps/admin-ui/src/realm-settings/security-defences/Time.tsx
  js/apps/admin-ui/src/realm/routes/AddRealm.tsx
Labels: kind/bug, team/ui

#24483 Properly handle array query arguments in Admin Client
  js/libs/keycloak-admin-client/src/utils/stringifyQueryParams.ts
  js/libs/keycloak-admin-client/test/auth.spec.ts
  js/libs/keycloak-admin-client/test/authenticationManagement.spec.ts
  js/libs/keycloak-admin-client/test/stringifyQueryParams.spec.ts
Labels: team/ui

#24488 Enable `html` reporter for Playwright on CI
  js/apps/account-ui/playwright.config.ts
Labels: team/ui

#24489 Remove hidden inputs from update password form
  themes/src/main/resources/theme/base/login/login-update-password.ftl
Labels: team/ui, flaky-test

#24296 Data too long for column 'DETAILS_JSON'
  docs/documentation/server_admin/topics/events/login.adoc
  docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
  model/jpa/src/main/java/org/keycloak/events/jpa/AdminEventEntity.java
  model/jpa/src/main/java/org/keycloak/events/jpa/EventEntity.java
  model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventStoreProvider.java
  model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventStoreProviderFactory.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-23.0.0.xml
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/event/AdminEventTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/events/AdminEventQueryTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/events/EventQueryTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24515 Minor fixes for FIPS and Operator Guide
  docs/guides/operator/customizing-keycloak.adoc
  docs/guides/server/fips.adoc
Labels: team/cloud-native

#24530 Fixed a11y violations in the user attribute search form
  js/apps/admin-ui/public/locales/en/translation.json
  js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx
  js/apps/admin-ui/src/components/users/UserDataTableToolbarItems.tsx
Labels: team/ui

#24548 Feature flag DPoP metadata in OIDC Well Known endpoint
  services/src/main/java/org/keycloak/protocol/oidc/OIDCWellKnownProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCWellKnownProviderTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24576 Improvement for user profile tests
  js/apps/admin-ui/cypress/e2e/realm_settings_user_profile_disabled.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_settings_user_profile_enabled.spec.ts
Labels: team/ui

#24580 Backport FIPS and Operator corrections
  docs/guides/operator/customizing-keycloak.adoc
  docs/guides/server/fips.adoc
Labels: team/cloud-native

#24579 Update webauth4j to 0.21.5.RELEASE
  pom.xml
Labels: flaky-test

#24582 Modify quarkus-container-image-docker dependency in operator
  operator/pom.xml
Labels: team/cloud-native, flaky-test

#24583 Modify quarkus-container-image-docker dependency in operator
  operator/pom.xml
Labels: team/cloud-native, flaky-test

#24518 Add possibility to override fileName and base directory of Keycloak Quarkus distribution ZIP archive
  operator/pom.xml
  pom.xml
  quarkus/dist/assembly.xml
  quarkus/dist/pom.xml
  testsuite/integration-arquillian/servers/auth-server/quarkus/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#24284 Add possibility to override fileName and base directory of Keycloak Quarkus distribution ZIP archive
  operator/pom.xml
  pom.xml
  quarkus/dist/assembly.xml
  quarkus/dist/pom.xml
  testsuite/integration-arquillian/servers/auth-server/quarkus/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#24536 Moving UPConfig and related classes from keycloak-services
  core/src/main/java/org/keycloak/representations/userprofile/config/UPAttribute.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPAttributePermissions.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPAttributeRequired.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPAttributeSelector.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPConfig.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPGroup.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/UserProfileResource.java
  server-spi-private/src/main/java/org/keycloak/userprofile/UserProfileProvider.java
  services/src/main/java/org/keycloak/services/resources/admin/UserProfileResource.java
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/config/DeclarativeUserProfileModel.java
  services/src/main/java/org/keycloak/userprofile/config/UPAttributeSelector.java
  services/src/main/java/org/keycloak/userprofile/config/UPConfigUtils.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/user/profile/CustomUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTestWithUserProfile.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/userprofile/UserProfileAdminTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPAdminRestApiWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/VerifyProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/ImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/AbstractUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/config/UPConfigParserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/JsonTestUtils.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24445 Translate user profile attribute group label
  js/apps/admin-ui/src/user/UserProfileFields.tsx
  js/apps/admin-ui/src/user/components/MultiInputComponent.tsx
  js/apps/admin-ui/src/user/components/UserProfileGroup.tsx
  js/apps/admin-ui/src/user/utils.ts
Labels: team/ui

#24608 Allow overriding Quarkus Netty version in keycloak-parent
  pom.xml
Labels: flaky-test

#24540 Delete map dependencies from dependency management
  dependencies/server-all/pom.xml
  model/map-file/pom.xml
  model/map-hot-rod/pom.xml
  model/map-jpa/pom.xml
  model/map-ldap/pom.xml
  pom.xml
  quarkus/config-api/pom.xml
  quarkus/runtime/pom.xml
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#24519 Add attributes.adoc for guides to share common attributes
  docs/documentation/securing_apps/topics/oidc/java/adapter-deprecation-notice.adoc
  docs/documentation/securing_apps/topics/oidc/java/jboss-adapter.adoc
  docs/documentation/securing_apps/topics/oidc/java/jetty9-adapter.adoc
  docs/documentation/securing_apps/topics/oidc/mod-auth-openidc.adoc
  docs/documentation/securing_apps/topics/oidc/nodejs-adapter.adoc
  docs/guides/attributes.adoc
  docs/guides/getting-started/getting-started-docker.adoc
  docs/guides/getting-started/getting-started-kube.adoc
  docs/guides/getting-started/getting-started-openshift.adoc
  docs/guides/getting-started/getting-started-podman.adoc
  docs/guides/getting-started/getting-started-zip.adoc
  docs/guides/getting-started/index.adoc
  docs/guides/getting-started/templates/create-admin-localhost.adoc
  docs/guides/getting-started/templates/first-app.adoc
  docs/guides/getting-started/templates/login-to-account.adoc
  docs/guides/getting-started/templates/next.adoc
  docs/guides/getting-started/templates/realm-config.adoc
  docs/guides/getting-started/templates/start-keycloak-container.adoc
  docs/guides/getting-started/templates/start-keycloak-localhost.adoc
  docs/guides/getting-started/templates/test-app.adoc
  docs/guides/migration/index.adoc
  docs/guides/operator/advanced-configuration.adoc
  docs/guides/operator/basic-deployment.adoc
  docs/guides/operator/customizing-keycloak.adoc
  docs/guides/operator/index.adoc
  docs/guides/operator/installation.adoc
  docs/guides/operator/realm-import.adoc
  docs/guides/pom.xml
  docs/guides/server/all-config.adoc
  docs/guides/server/caching.adoc
  docs/guides/server/configuration-metrics.adoc
  docs/guides/server/configuration-production.adoc
  docs/guides/server/configuration.adoc
  docs/guides/server/containers.adoc
  docs/guides/server/db.adoc
  docs/guides/server/enabletls.adoc
  docs/guides/server/features.adoc
  docs/guides/server/fips.adoc
  docs/guides/server/health.adoc
  docs/guides/server/hostname.adoc
  docs/guides/server/importExport.adoc
  docs/guides/server/index.adoc
  docs/guides/server/keycloak-truststore.adoc
  docs/guides/server/logging.adoc
  docs/guides/server/outgoinghttp.adoc
  docs/guides/server/reverseproxy.adoc
  docs/guides/server/vault.adoc
  docs/guides/templates/guide.adoc
Labels: team/cloud-native, flaky-test

#24590 Add attributes.adoc for guides to share common attributes
  docs/documentation/securing_apps/topics/oidc/java/adapter-deprecation-notice.adoc
  docs/documentation/securing_apps/topics/oidc/java/jboss-adapter.adoc
  docs/documentation/securing_apps/topics/oidc/java/jetty9-adapter.adoc
  docs/documentation/securing_apps/topics/oidc/mod-auth-openidc.adoc
  docs/documentation/securing_apps/topics/oidc/nodejs-adapter.adoc
  docs/guides/attributes.adoc
  docs/guides/getting-started/getting-started-docker.adoc
  docs/guides/getting-started/getting-started-kube.adoc
  docs/guides/getting-started/getting-started-openshift.adoc
  docs/guides/getting-started/getting-started-podman.adoc
  docs/guides/getting-started/getting-started-zip.adoc
  docs/guides/getting-started/index.adoc
  docs/guides/getting-started/templates/create-admin-localhost.adoc
  docs/guides/getting-started/templates/first-app.adoc
  docs/guides/getting-started/templates/login-to-account.adoc
  docs/guides/getting-started/templates/next.adoc
  docs/guides/getting-started/templates/realm-config.adoc
  docs/guides/getting-started/templates/start-keycloak-container.adoc
  docs/guides/getting-started/templates/start-keycloak-localhost.adoc
  docs/guides/getting-started/templates/test-app.adoc
  docs/guides/migration/index.adoc
  docs/guides/operator/advanced-configuration.adoc
  docs/guides/operator/basic-deployment.adoc
  docs/guides/operator/customizing-keycloak.adoc
  docs/guides/operator/index.adoc
  docs/guides/operator/installation.adoc
  docs/guides/operator/realm-import.adoc
  docs/guides/pom.xml
  docs/guides/server/all-config.adoc
  docs/guides/server/caching.adoc
  docs/guides/server/configuration-metrics.adoc
  docs/guides/server/configuration-production.adoc
  docs/guides/server/configuration.adoc
  docs/guides/server/containers.adoc
  docs/guides/server/db.adoc
  docs/guides/server/enabletls.adoc
  docs/guides/server/features.adoc
  docs/guides/server/fips.adoc
  docs/guides/server/health.adoc
  docs/guides/server/hostname.adoc
  docs/guides/server/importExport.adoc
  docs/guides/server/index.adoc
  docs/guides/server/keycloak-truststore.adoc
  docs/guides/server/logging.adoc
  docs/guides/server/outgoinghttp.adoc
  docs/guides/server/reverseproxy.adoc
  docs/guides/server/vault.adoc
  docs/guides/templates/guide.adoc
Labels: team/cloud-native, flaky-test

#24086 Ensure safe initialization of the embedded caches
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/LegacyInfinispanConnectionFactory.java
  testsuite/model/pom.xml
  testsuite/model/src/main/java/org/keycloak/testsuite/model/Config.java
Labels: team/cloud-native, team/store, flaky-test

#24657 Failing test X509OCSPResponderTest due expired certificate
  testsuite/integration-arquillian/servers/auth-server/common/keystore/test-user-cert-intermediary-ca.jks
  testsuite/integration-arquillian/servers/auth-server/common/pki/root/ca/intermediate/index.txt
  testsuite/integration-arquillian/servers/auth-server/common/pki/root/ca/intermediate/index.txt.old
  testsuite/integration-arquillian/servers/auth-server/common/pki/root/ca/intermediate/newcerts/200B.pem
  testsuite/integration-arquillian/servers/auth-server/common/pki/root/ca/intermediate/serial
  testsuite/integration-arquillian/servers/auth-server/common/pki/root/ca/intermediate/serial.old
Labels: team/cloud-native, team/store, team/core

#24145 Keep same name on update for LDAP attributes
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/model/LDAPObject.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPProvidersIntegrationTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24496 Transient users: Consents
  server-spi-private/src/main/java/org/keycloak/models/light/LightweightConsentEntity.java
  server-spi-private/src/main/java/org/keycloak/models/light/LightweightUserAdapter.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenRevocationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/CibaGrantType.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/managers/UserConsentManager.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTransientSessionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserConsentModelTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserConsentWithUserStorageModelTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24333 Transient sessions: Documentation
  docs/transient-users.md
Labels: team/cloud-native, flaky-test

#24666 Failing test X509OCSPResponderTest due expired certificate
  testsuite/integration-arquillian/servers/auth-server/common/keystore/test-user-cert-intermediary-ca.jks
  testsuite/integration-arquillian/servers/auth-server/common/pki/root/ca/intermediate/index.txt
  testsuite/integration-arquillian/servers/auth-server/common/pki/root/ca/intermediate/index.txt.old
  testsuite/integration-arquillian/servers/auth-server/common/pki/root/ca/intermediate/newcerts/200B.pem
  testsuite/integration-arquillian/servers/auth-server/common/pki/root/ca/intermediate/serial
  testsuite/integration-arquillian/servers/auth-server/common/pki/root/ca/intermediate/serial.old
Labels: team/cloud-native, team/store, team/core

#20378 fix cli output token without return token
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractRequestCmd.java
Labels: flaky-test

#24689 Delete removed `spi-events-store-jpa-max-detail-length` property
  testsuite/integration-arquillian/servers/auth-server/quarkus/src/main/content/conf/keycloak.conf
Labels: team/cloud-native, team/store, team/core, flaky-test

#24316 changed to use resource bundles
  js/apps/admin-ui/maven-resources/theme-resources/messages/messages_ca.properties
  js/apps/admin-ui/maven-resources/theme-resources/messages/messages_de.properties
  js/apps/admin-ui/maven-resources/theme-resources/messages/messages_en.properties
  js/apps/admin-ui/maven-resources/theme-resources/messages/messages_es.properties
  js/apps/admin-ui/maven-resources/theme-resources/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources/theme-resources/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources/theme-resources/messages/messages_lt.properties
  js/apps/admin-ui/maven-resources/theme-resources/messages/messages_no.properties
  js/apps/admin-ui/maven-resources/theme-resources/messages/messages_pt_BR.properties
  js/apps/admin-ui/maven-resources/theme-resources/messages/messages_ru.properties
  js/apps/admin-ui/maven-resources/theme-resources/messages/messages_zh_CN.properties
  js/apps/admin-ui/public/locales/ca/translation.json
  js/apps/admin-ui/public/locales/de/translation.json
  js/apps/admin-ui/public/locales/en/translation.json
  js/apps/admin-ui/public/locales/es/translation.json
  js/apps/admin-ui/public/locales/fr/translation.json
  js/apps/admin-ui/public/locales/it/translation.json
  js/apps/admin-ui/public/locales/ja/translation.json
  js/apps/admin-ui/public/locales/lt/translation.json
  js/apps/admin-ui/public/locales/lv/translation.json
  js/apps/admin-ui/public/locales/nl/translation.json
  js/apps/admin-ui/public/locales/no/translation.json
  js/apps/admin-ui/public/locales/pl/translation.json
  js/apps/admin-ui/public/locales/pt-BR/translation.json
  js/apps/admin-ui/public/locales/ru/translation.json
  js/apps/admin-ui/public/locales/zh-CN/translation.json
  js/apps/admin-ui/src/i18n/OverridesBackend.ts
  js/apps/admin-ui/src/i18n/i18n.ts
  services/src/main/java/org/keycloak/services/resources/ThemeResource.java
Labels: team/ui, flaky-test

#24709 Fix broken link to node.js and internal anchor
  docs/documentation/server_admin/topics/threat.adoc
  docs/documentation/tests/src/test/resources/ignored-link-redirects
Labels: flaky-test

#24717 24476 backport
  docs/documentation/authorization_services/topics/getting-started-overview.adoc
  docs/documentation/authorization_services/topics/policy-js-policy.adoc
  docs/documentation/server_admin/topics/threat/read-only-attributes.adoc
  docs/documentation/server_admin/topics/users/proc-configuring-user-attributes.adoc
  docs/documentation/server_development/topics/auth-spi.adoc
  docs/documentation/server_development/topics/user-storage.adoc
  docs/documentation/upgrading/topics/keycloak/changes.adoc
  docs/documentation/upgrading/topics/rhsso/changes-75.adoc
Labels: area/docs

#24682 Added missing dependencies to themes/pom.xml
  themes/pom.xml
Labels: flaky-test

#24712 Make user profile validation success if the attribute was already wrong and read-only in the context
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24708 Fix redirect uri for cordova adapter
  js/libs/keycloak-js/src/keycloak.js
Labels: team/ui

#24740 Upgrade PatternFly dependencies to latest 4.x version
  js/apps/account-ui/package.json
  js/apps/admin-ui/package.json
  js/libs/keycloak-masthead/package.json
  js/libs/ui-shared/package.json
  js/pnpm-lock.yaml
  themes/src/main/resources/theme/keycloak.v2/account/src/package.json
  themes/src/main/resources/theme/keycloak.v2/account/src/pnpm-lock.yaml
Labels: team/ui

#24753 Upgrade TypeScript to latest version for Account Console v2
  themes/src/main/resources/theme/keycloak.v2/account/src/package.json
  themes/src/main/resources/theme/keycloak.v2/account/src/pnpm-lock.yaml
  themes/src/main/resources/theme/keycloak.v2/account/src/tsconfig.json
Labels: team/ui, flaky-test

#24756 fix: all mappings should use getValidProxyModeValue
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ProxyPropertyMappers.java
Labels: team/cloud-native, flaky-test

#24777 Use common TSConfig base for Account Console v2
  themes/src/main/resources/theme/keycloak.v2/account/src/app/content/account-page/AccountPage.tsx
  themes/src/main/resources/theme/keycloak.v2/account/src/app/content/device-activity-page/DeviceActivityPage.tsx
  themes/src/main/resources/theme/keycloak.v2/account/src/app/content/my-resources-page/MyResourcesPage.tsx
  themes/src/main/resources/theme/keycloak.v2/account/src/app/content/my-resources-page/PermissionRequest.tsx
  themes/src/main/resources/theme/keycloak.v2/account/src/app/content/my-resources-page/PermissionSelect.tsx
  themes/src/main/resources/theme/keycloak.v2/account/src/app/content/my-resources-page/ResourcesTable.tsx
  themes/src/main/resources/theme/keycloak.v2/account/src/app/content/signingin-page/SigningInPage.tsx
  themes/src/main/resources/theme/keycloak.v2/account/src/package.json
  themes/src/main/resources/theme/keycloak.v2/account/src/tsconfig.json
Labels: team/ui, flaky-test

#24780 Add missing localization for Event Type "User Disabled By Permament Lockout Error"
  js/apps/admin-ui/maven-resources/theme-resources/messages/messages_en.properties
Labels: team/ui

#24788 convert the account ui to properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_ar.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_fa.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_fr.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_nl.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_ru.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_tr.properties
  js/apps/account-ui/public/locales/ar/translation.json
  js/apps/account-ui/public/locales/fa/translation.json
  js/apps/account-ui/public/locales/fr/translation.json
  js/apps/account-ui/public/locales/nl/translation.json
  js/apps/account-ui/public/locales/ru/translation.json
  js/apps/account-ui/public/locales/tr/translation.json
  js/apps/account-ui/src/i18n.ts
Labels: team/ui

#24597 Avoid NPE if RelayState is null and return a proper error
  services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlBrokerTest.java
Labels: team/cloud-native, team/store, team/core

#24723 Removal of retry blocks introduced for CRDB
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  services/src/main/java/org/keycloak/services/resources/admin/ComponentResource.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/KeycloakModelTest.java
Labels: team/store, flaky-test

#24796 fix: removing the hard expectation of setting the restart condition
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
Labels: team/cloud-native, flaky-test

#24542 Use session ID rather than broker session ID
  server-spi-private/src/main/java/org/keycloak/models/light/LightweightUserAdapter.java
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
  services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpCreateUserIfUniqueAuthenticator.java
  services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
Labels: team/core, flaky-test

#24686 Removal EPL-licensed org.eclipse.sisu.inject dependency for CNCF compliance
  quarkus/deployment/pom.xml
Labels: team/cloud-native, flaky-test

#24603 Update Social Identity Providers documentation
  docs/documentation/server_admin/images/bitbucket-add-identity-provider.png
  docs/documentation/server_admin/images/facebook-add-identity-provider.png
  docs/documentation/server_admin/images/github-add-identity-provider.png
  docs/documentation/server_admin/images/gitlab-add-identity-provider.png
  docs/documentation/server_admin/images/google-add-identity-provider.png
  docs/documentation/server_admin/images/instagram-add-identity-provider.png
  docs/documentation/server_admin/images/instagram-add-new-app.png
  docs/documentation/server_admin/images/instagram-add-platform.png
  docs/documentation/server_admin/images/instagram-add-product.png
  docs/documentation/server_admin/images/instagram-app-settings.png
  docs/documentation/server_admin/images/instagram-create-app-id.png
  docs/documentation/server_admin/images/instagram-create-instagram-app-id.png
  docs/documentation/server_admin/images/linked-in-add-identity-provider.png
  docs/documentation/server_admin/images/meta-add-product.png
  docs/documentation/server_admin/images/meta-add-use-case.png
  docs/documentation/server_admin/images/meta-create-app.png
  docs/documentation/server_admin/images/meta-select-app-type.png
  docs/documentation/server_admin/images/microsoft-add-identity-provider.png
  docs/documentation/server_admin/images/openshift-4-add-identity-provider.png
  docs/documentation/server_admin/images/openshift-add-identity-provider.png
  docs/documentation/server_admin/images/paypal-add-identity-provider.png
  docs/documentation/server_admin/images/stack-overflow-add-identity-provider.png
  docs/documentation/server_admin/images/twitter-add-identity-provider.png
  docs/documentation/server_admin/topics.adoc
  docs/documentation/server_admin/topics/identity-broker/social/bitbucket.adoc
  docs/documentation/server_admin/topics/identity-broker/social/facebook.adoc
  docs/documentation/server_admin/topics/identity-broker/social/github.adoc
  docs/documentation/server_admin/topics/identity-broker/social/gitlab.adoc
  docs/documentation/server_admin/topics/identity-broker/social/google.adoc
  docs/documentation/server_admin/topics/identity-broker/social/instagram.adoc
  docs/documentation/server_admin/topics/identity-broker/social/linked-in.adoc
  docs/documentation/server_admin/topics/identity-broker/social/microsoft.adoc
  docs/documentation/server_admin/topics/identity-broker/social/openshift.adoc
  docs/documentation/server_admin/topics/identity-broker/social/paypal.adoc
  docs/documentation/server_admin/topics/identity-broker/social/stack-overflow.adoc
  docs/documentation/server_admin/topics/identity-broker/social/twitter.adoc
Labels: area/docs, team/core

#24779 KeycloakErrorHandler NullPointerException String.toLowerCase() because message is null
  model/jpa/src/main/java/org/keycloak/connections/jpa/PersistenceExceptionConverter.java
Labels: team/store, flaky-test

#24776 Use LinkedIn instead of LinkedIn OpenID Connect for better UI experience
  docs/documentation/server_admin/topics/identity-broker/social/linked-in.adoc
  js/apps/admin-ui/cypress/e2e/identity_providers_test.spec.ts
  services/src/main/java/org/keycloak/social/linkedin/LinkedInOIDCIdentityProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#24801 Delete `SearchableModelField` and its usages
  server-spi-private/src/main/java/org/keycloak/authorization/model/PermissionTicket.java
  server-spi-private/src/main/java/org/keycloak/authorization/model/Policy.java
  server-spi-private/src/main/java/org/keycloak/authorization/model/Resource.java
  server-spi-private/src/main/java/org/keycloak/authorization/model/ResourceServer.java
  server-spi-private/src/main/java/org/keycloak/authorization/model/Scope.java
  server-spi-private/src/main/java/org/keycloak/events/Event.java
  server-spi-private/src/main/java/org/keycloak/events/admin/AdminEvent.java
  server-spi/src/main/java/org/keycloak/models/ClientModel.java
  server-spi/src/main/java/org/keycloak/models/ClientScopeModel.java
  server-spi/src/main/java/org/keycloak/models/GroupModel.java
  server-spi/src/main/java/org/keycloak/models/RealmModel.java
  server-spi/src/main/java/org/keycloak/models/RoleModel.java
  server-spi/src/main/java/org/keycloak/models/SingleUseObjectValueModel.java
  server-spi/src/main/java/org/keycloak/models/UserLoginFailureModel.java
  server-spi/src/main/java/org/keycloak/models/UserModel.java
  server-spi/src/main/java/org/keycloak/models/UserSessionModel.java
  server-spi/src/main/java/org/keycloak/sessions/RootAuthenticationSessionModel.java
  server-spi/src/main/java/org/keycloak/storage/SearchableModelField.java
Labels: flaky-test

#24787 added theme name as parameter
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_ca.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_lt.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_no.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_pt_BR.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_ru.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_zh_CN.properties
  services/src/main/java/org/keycloak/services/resources/ThemeResource.java
Labels: team/ui

#24819 Fix lowerCaseHostname to lower-case scheme and host properly
  services/src/main/java/org/keycloak/protocol/oidc/utils/RedirectUtils.java
  services/src/test/java/org/keycloak/protocol/oidc/utils/RedirectUtilsTest.java
Labels: flaky-test

#24826 fix: adds a better error message if an spi argument lacks a value
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ExecutionExceptionHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/PropertyException.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
Labels: team/cloud-native, flaky-test

#24818 Fix DocsBuildDebugUtil signatures, and ensure it can be called from an IDE
  docs/guides/pom.xml
  docs/guides/src/test/java/org/keycloak/guides/DocsBuildDebugUtil.java
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/GuideBuilder.java
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/GuideMojo.java
Labels: flaky-test

#24837 24672 remove linebreaks from basicauth base64 encoding to comply to s…
  core/src/main/java/org/keycloak/util/BasicAuthHelper.java
  core/src/test/java/org/keycloak/util/BasicAuthHelperTest.java
Labels: flaky-test

#24300 Introduce MaxAuthAge Password policy (#12943)
  docs/documentation/server_admin/topics/authentication/password-policies.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  server-spi-private/src/main/java/org/keycloak/policy/MaxAuthAgePasswordPolicyProviderFactory.java
  server-spi-private/src/main/resources/META-INF/services/org.keycloak.policy.PasswordPolicyProviderFactory
  server-spi/src/main/java/org/keycloak/models/PasswordPolicy.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdatePassword.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionResetPasswordTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#24847 Start of MS-SQL fails in CI
  testsuite/integration-arquillian/pom.xml
Labels: team/cloud-native, team/store, team/core

#24843 Include `react` and `react-dom` as external dependencies
  .github/workflows/js-ci.yml
  js/apps/account-ui/pom.xml
  js/apps/account-ui/vite.config.ts
  js/apps/admin-ui/pom.xml
  js/apps/admin-ui/vite.config.ts
  themes/.gitignore
  themes/pom.xml
  themes/src/main/resources/theme/keycloak/common/resources/package.json
  themes/src/main/resources/theme/keycloak/common/resources/pnpm-lock.yaml
  themes/src/main/resources/theme/keycloak/common/resources/rollup.config.js
Labels: area/account/ui, area/admin/ui, kind/task, team/ui

#24774 Disable cache store only if a remote store is used
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/CacheDecorators.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserLoginFailureProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/InfinispanChangelogBasedTransaction.java
Labels: team/store, flaky-test

#24845 Endpoint for getting localization/effective message bundles
  js/libs/keycloak-admin-client/src/defs/effectiveMessageBundleRepresentation.ts
  js/libs/keycloak-admin-client/src/resources/serverInfo.ts
  js/libs/keycloak-admin-client/test/serverInfo.spec.ts
Labels: team/ui

#24602 Transient users: UX improvements
  .github/workflows/js-ci.yml
  js/apps/admin-ui/cypress/e2e/identity_providers_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/sessions/SessionsTable.tsx
  js/apps/admin-ui/src/user/EditUser.tsx
  js/apps/admin-ui/src/user/utils.ts
  js/apps/keycloak-server/scripts/start-server.js
Labels: team/ui

#24869 fix: correcting the realmrepresentation link
  docs/guides/operator/realm-import.adoc
Labels: team/cloud-native

#24870 Avoid deprecated API usage in testsuite/integration-arquillian/util
  testsuite/integration-arquillian/util/src/main/java/org/keycloak/testsuite/utils/fuse/FuseUtils.java
  testsuite/integration-arquillian/util/src/main/java/org/keycloak/testsuite/utils/undertow/UndertowDeployerHelper.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24812 Do not run value transformation if a option is being requested by its name and there is no dependency on other options
  quarkus/config-api/src/main/java/org/keycloak/config/ProxyOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/Configuration.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ProxyPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
Labels: team/cloud-native, flaky-test

#24684 Implement load shedding
  docs/documentation/release_notes/topics/23_0_0.adoc
  docs/guides/server/configuration-production.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java
  quarkus/tests/integration/src/test-providers/java/org/keycloak/it/resource/realm/TestRealmResource.java
  quarkus/tests/integration/src/test-providers/java/org/keycloak/it/resource/realm/TestRealmResourceFactory.java
  quarkus/tests/integration/src/test-providers/java/org/keycloak/it/resource/realm/TestRealmResourceTestProvider.java
  quarkus/tests/integration/src/test-providers/resources/org/keycloak/it/resource/realm/org.keycloak.services.resource.RealmResourceProviderFactory
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HttpDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.windows.approved.txt
Labels: team/cloud-native, flaky-test

#24858 fix: skip rebuild if using the tools command
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Tools.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ToolsCommandDistTest.java
Labels: team/cloud-native, flaky-test

#24715 Removal of LGPL-2.1 licensed org.jboss.metadata.jboss-metadata-web dependency for CNCF compliance
  quarkus/deployment/pom.xml
Labels: team/cloud-native, flaky-test

#24438 Add Galleon layer metadata to the SAML Galleon feature-pack
  distribution/galleon-feature-packs/pom.xml
  distribution/galleon-feature-packs/saml-adapter-galleon-pack-layer-metadata-tests/pom.xml
  distribution/galleon-feature-packs/saml-adapter-galleon-pack-layer-metadata-tests/src/test/java/org/keycloak/test/saml/adapter/galleon/pack/layer/metadata/EjbLiteAnnotationUsage.java
  distribution/galleon-feature-packs/saml-adapter-galleon-pack-layer-metadata-tests/src/test/java/org/keycloak/test/saml/adapter/galleon/pack/layer/metadata/KeycloakSamlAdapterLayerMetaDataTestCase.java
  distribution/galleon-feature-packs/saml-adapter-galleon-pack-layer-metadata-tests/src/test/resources/glow/latest/provisioning-bare-metal.xml
  distribution/galleon-feature-packs/saml-adapter-galleon-pack-layer-metadata-tests/src/test/resources/glow/versions.yaml
  distribution/galleon-feature-packs/saml-adapter-galleon-pack/src/main/resources/layers/standalone/keycloak-client-saml-ejb/layer-spec.xml
  distribution/galleon-feature-packs/saml-adapter-galleon-pack/src/main/resources/layers/standalone/keycloak-client-saml/layer-spec.xml
  distribution/galleon-feature-packs/saml-adapter-galleon-pack/src/main/resources/layers/standalone/keycloak-saml/layer-spec.xml
  pom.xml
Labels: flaky-test

#24012 23404 improve client role listing
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  model/legacy-private/src/main/java/org/keycloak/storage/RoleStorageManager.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AuthenticationManagementResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AvailableRoleMappingResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/EffectiveRoleMappingResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/RoleMappingResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/RoleMapper.java
  server-spi/src/main/java/org/keycloak/storage/role/RoleLookupProvider.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/ClientPermissionEvaluator.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/ClientPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissionEvaluator.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissions.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/HardcodedRoleStorageProvider.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#22443 Ignore JDBC Drivers artifacts
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/IgnoredArtifacts.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/IgnoredArtifactsTest.java
Labels: team/cloud-native, team/store, flaky-test

#24929 Stop copying resources from Account v2 theme into 'common'
  docs/documentation/server_development/topics/themes.adoc
  themes/pom.xml
  themes/src/main/resources/theme/keycloak.v2/account/index.ftl
  themes/src/main/resources/theme/keycloak.v2/account/resources/.gitignore
  themes/src/main/resources/theme/keycloak.v2/account/src/.babelrc
  themes/src/main/resources/theme/keycloak.v2/account/src/package.json
  themes/src/main/resources/theme/keycloak.v2/account/src/pnpm-lock.yaml
  themes/src/main/resources/theme/keycloak.v2/account/src/snowpack.config.js
  themes/src/main/resources/theme/keycloak/common/resources/package.json
  themes/src/main/resources/theme/keycloak/common/resources/pnpm-lock.yaml
  themes/src/main/resources/theme/keycloak/login/theme.properties
Labels: team/ui

#24938 Revert "Ignore JDBC Drivers artifacts"
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/IgnoredArtifacts.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/IgnoredArtifactsTest.java
Labels: team/cloud-native

#24913 Adding a Keycloak High Availability section to Keycloak's docs
  docs/documentation/release_notes/topics/23_0_0.adoc
  docs/guides/assembly.xml
  docs/guides/attributes.adoc
  docs/guides/high-availability/bblocks-active-passive-sync.adoc
  docs/guides/high-availability/concepts-active-passive-sync.adoc
  docs/guides/high-availability/concepts-database-connections.adoc
  docs/guides/high-availability/concepts-memory-and-cpu-sizing.adoc
  docs/guides/high-availability/concepts-threads.adoc
  docs/guides/high-availability/connect-keycloak-to-external-infinispan.adoc
  docs/guides/high-availability/deploy-aurora-multi-az.adoc
  docs/guides/high-availability/deploy-aws-route53-loadbalancer.adoc
  docs/guides/high-availability/deploy-infinispan-kubernetes-crossdc.adoc
  docs/guides/high-availability/deploy-keycloak-kubernetes.adoc
  docs/guides/high-availability/examples/generated/ispn-single.yaml
  docs/guides/high-availability/examples/generated/ispn-site-a.yaml
  docs/guides/high-availability/examples/generated/ispn-site-b.yaml
  docs/guides/high-availability/examples/generated/keycloak-ispn.yaml
  docs/guides/high-availability/examples/generated/keycloak.yaml
  docs/guides/high-availability/examples/src/kcb-infinispan-cache-remote-store-config.xml
  docs/guides/high-availability/index.adoc
  docs/guides/high-availability/introduction.adoc
  docs/guides/high-availability/operate-failover.adoc
  docs/guides/high-availability/operate-network-partition-recovery.adoc
  docs/guides/high-availability/operate-switch-back.adoc
  docs/guides/high-availability/operate-switch-over.adoc
  docs/guides/high-availability/partials/aurora/aurora-create-peering-connections.adoc
  docs/guides/high-availability/partials/aurora/aurora-failover.adoc
  docs/guides/high-availability/partials/aurora/aurora-multiaz-create-procedure.adoc
  docs/guides/high-availability/partials/aurora/aurora-verify-peering-connections.adoc
  docs/guides/high-availability/partials/blueprint-disclaimer.adoc
  docs/guides/high-availability/partials/database-connections/configure-db-connection-pool-best-practices.adoc
  docs/guides/high-availability/partials/infinispan/infinispan-attributes.adoc
  docs/guides/high-availability/partials/infinispan/infinispan-cli-clear-caches.adoc
  docs/guides/high-availability/partials/infinispan/infinispan-cli-connect.adoc
  docs/guides/high-availability/partials/infinispan/infinispan-cli-state-transfer.adoc
  docs/guides/high-availability/partials/infinispan/infinispan-credentials.adoc
  docs/guides/high-availability/partials/infinispan/infinispan-install-operator.adoc
  docs/guides/high-availability/partials/infinispan/infinispan-prerequisites.adoc
  docs/guides/high-availability/partials/threads/executor-jgroups-thread-calculation.adoc
  docs/guides/high-availability/pinned-guides
  docs/guides/images/high-availability/active-passive-sync.dio.svg
  docs/guides/images/high-availability/aurora-multi-az.dio.svg
  docs/guides/images/high-availability/infinispan-crossdc-az.dio.svg
  docs/guides/images/high-availability/route53-multi-az-failover.svg
  docs/guides/pom.xml
  docs/guides/templates/guide.adoc
  docs/guides/templates/links.adoc
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Context.java
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/GuideMojo.java
Labels: flaky-test

#24971 Mark `jwt-decode` as an external dependency of Keycloak JS
  js/libs/keycloak-js/rollup.config.ts
Labels: team/ui

#24963 Fix compilation error with ServerInfoAdminResource
  services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java
Labels: flaky-test

#24953 Fix logic error in AbstractOAuth2IdentityProvider
  services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
Labels: flaky-test

#24954 Wrong value for VALIDATED_ID_TOKEN stored in the brokered identity co…
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
Labels: flaky-test

#24974 Use `exports` field for Keycloak JS
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  js/libs/keycloak-js/package.json
  js/pnpm-lock.yaml
Labels: team/ui

#24982 Improve detection of User Profile related errors
  js/libs/ui-shared/src/user-profile/utils.ts
Labels: team/ui

#24915 fixed possible undefined enabled flag
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
Labels: team/ui

#24911 should be disabled when mode = UNSYNCED
  js/apps/admin-ui/src/user-federation/shared/ExtendedHeader.tsx
Labels: team/ui

#25009 Fix search in group picker dialog
  js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx
Labels: team/ui

#25017 Make password visibility css classes configurable for themes
  themes/src/main/resources/theme/base/login/login-password.ftl
  themes/src/main/resources/theme/base/login/login-update-password.ftl
  themes/src/main/resources/theme/base/login/login.ftl
  themes/src/main/resources/theme/base/login/register-user-profile.ftl
  themes/src/main/resources/theme/base/login/register.ftl
  themes/src/main/resources/theme/base/login/resources/js/passwordVisibility.js
  themes/src/main/resources/theme/keycloak/login/theme.properties
Labels: flaky-test

#25021 Replace static text with reference to translation in Applications page #24527
  themes/src/main/resources/theme/keycloak.v2/account/messages/messages_en.properties
  themes/src/main/resources/theme/keycloak.v2/account/src/app/content/applications-page/ApplicationsPage.tsx
Labels: team/ui

#25023 NPE in checkAndBindMtlsHoKToken on Token Refresh when using SuppressRefreshTokenRotationExecutor and Certificate Bound Token
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25020 Fix search in group picker dialog (#25009)
  js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx
Labels: team/ui

#25036 Escape ldap id when using normal attribute syntax (#25)
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPOperationManager.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/AbstractUsernameFormAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPSpecialCharsTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24956 only flatten array when it's length is one
  js/apps/admin-ui/src/util.ts
Labels: team/ui

#25043 Fix missing CRD metadata in Operator CSV
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/Keycloak.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/realmimport/KeycloakRealmImport.java
Labels: team/cloud-native

#25042 Escape ldap id when using normal attribute syntax (#25)
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPOperationManager.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/AbstractUsernameFormAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPSpecialCharsTest.java
Labels: team/cloud-native, team/store, team/core

#25011 should be disabled when mode = UNSYNCED (#24911)
  js/apps/admin-ui/src/user-federation/shared/ExtendedHeader.tsx
Labels: team/ui

#25003 fixed possible undefined enabled flag (#24915)
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
Labels: team/ui

#24998 Improve detection of User Profile related errors (#24982)
  js/libs/ui-shared/src/user-profile/utils.ts
Labels: team/ui

#25045 Downgrade Oracle driver
  pom.xml
Labels: team/store, flaky-test

#24848 Start of MS-SQL fails in CI
  testsuite/integration-arquillian/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#24965 Added Polish Translations
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_pl.properties
Labels: area/translations, team/ui

#24888 fix: skip rebuild if using the tools command
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Tools.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ToolsCommandDistTest.java
Labels: team/cloud-native, flaky-test

#24809 fix: removing the hard expectation of setting the restart condition
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
Labels: team/cloud-native, flaky-test

#24534 check operand StatefulSet is ready for realm import Job to run
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJob.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/RealmImportTest.java
Labels: team/cloud-native, flaky-test

#24978 Allow duplicated keys in the HardcodedKeyLocator
  saml-core/src/main/java/org/keycloak/rotation/HardcodedKeyLocator.java
  saml-core/src/test/java/org/keycloak/rotation/HardcodedKeyLocatorTest.java
Labels: flaky-test

#25084 Use `module` type for all packages
  js/.eslintrc.cjs
  js/apps/admin-ui/cypress.config.js
  js/apps/admin-ui/package.json
  js/package.json
Labels: kind/task, team/ui

#24852 Add configuration option for LDAP referral
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPConfig.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProviderFactory.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPContextManager.java
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsSearching.tsx
  server-spi-private/src/main/java/org/keycloak/models/LDAPConstants.java
Labels: team/ui, flaky-test

#24879 Support OR condition for forms + authz
  js/apps/admin-ui/cypress/e2e/client_authorization_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/ListingPage.ts
  js/apps/admin-ui/cypress/support/util/AdminClient.ts
  js/apps/admin-ui/src/ForbiddenSection.tsx
  js/apps/admin-ui/src/clients/ClientDetails.tsx
  js/apps/admin-ui/src/clients/authorization/DecisionStrategySelect.tsx
  js/apps/admin-ui/src/clients/authorization/PermissionDetails.tsx
  js/apps/admin-ui/src/clients/authorization/Permissions.tsx
  js/apps/admin-ui/src/clients/authorization/Policies.tsx
  js/apps/admin-ui/src/clients/authorization/ResourceDetails.tsx
  js/apps/admin-ui/src/clients/authorization/Resources.tsx
  js/apps/admin-ui/src/clients/authorization/ScopeDetails.tsx
  js/apps/admin-ui/src/clients/authorization/Scopes.tsx
  js/apps/admin-ui/src/clients/authorization/Settings.tsx
  js/apps/admin-ui/src/clients/routes/AuthenticationTab.tsx
  js/apps/admin-ui/src/clients/routes/NewPermission.tsx
  js/apps/admin-ui/src/clients/routes/NewPolicy.tsx
  js/apps/admin-ui/src/clients/routes/NewResource.tsx
  js/apps/admin-ui/src/clients/routes/NewScope.tsx
  js/apps/admin-ui/src/clients/routes/PermissionDetails.tsx
  js/apps/admin-ui/src/clients/routes/PolicyDetails.tsx
  js/apps/admin-ui/src/clients/routes/Resource.tsx
  js/apps/admin-ui/src/clients/routes/Scope.tsx
  js/apps/admin-ui/src/components/form/FormAccess.tsx
  js/apps/admin-ui/src/components/key-value-form/KeyValueInput.tsx
  js/apps/admin-ui/src/components/list-empty-state/ListEmptyState.tsx
  js/apps/admin-ui/src/context/access/Access.tsx
  js/libs/keycloak-admin-client/src/defs/whoAmIRepresentation.ts
Labels: team/ui

#24015 Add script to help with backporting PRs to release branches
  .github/scripts/pr-backport.sh
Labels: flaky-test

#25050 Fix missing CRD metadata in Operator CSV (#25043)
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/Keycloak.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/realmimport/KeycloakRealmImport.java
Labels: team/cloud-native, flaky-test

#25063 Attempt to request storage access for cookies (#25055)
  js/libs/keycloak-js/src/keycloak.js
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step1.html
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/login-status-iframe.html
Labels: team/ui, flaky-test

#25069 Allow duplicated keys in the HardcodedKeyLocator
  saml-core/src/main/java/org/keycloak/rotation/HardcodedKeyLocator.java
  saml-core/src/test/java/org/keycloak/rotation/HardcodedKeyLocatorTest.java
Labels: flaky-test

#25102 External to Internal Token exchange fails with Null pointer Exception…
  services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java
Labels: flaky-test

#25034 Fix typo in the balloon help of SAML Username Template Importer
  services/src/main/java/org/keycloak/broker/saml/mappers/UsernameTemplateMapper.java
Labels: flaky-test

#25115 Remove lowercase for the hostname as recommended/advised by OAuth spec
  docs/documentation/upgrading/topics/keycloak/changes-23_0_2.adoc
  docs/documentation/upgrading/topics/keycloak/changes.adoc
  services/src/main/java/org/keycloak/protocol/oidc/utils/RedirectUtils.java
  services/src/test/java/org/keycloak/protocol/oidc/utils/RedirectUtilsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthRedirectUriTest.java
Labels: team/cloud-native, team/store, team/core

#24881 Allow automatic download of SAML certificates in the identity provider
  core/src/main/java/org/keycloak/crypto/PublicKeysWrapper.java
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/server_admin/topics/identity-broker/saml.adoc
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/IdentityProviderResource.java
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx
  js/apps/admin-ui/src/identity-providers/add/DetailSettings.tsx
  js/libs/keycloak-admin-client/src/resources/identityProviders.ts
  model/infinispan/src/main/java/org/keycloak/keys/infinispan/InfinispanPublicKeyStorageProvider.java
  model/infinispan/src/main/java/org/keycloak/keys/infinispan/InfinispanPublicKeyStorageProviderFactory.java
  model/infinispan/src/test/java/org/keycloak/keys/infinispan/InfinispanKeyStorageProviderTest.java
  saml-core/src/main/java/org/keycloak/saml/processing/core/saml/v2/util/SAMLMetadataUtil.java
  saml-core/src/main/java/org/keycloak/saml/processing/core/util/XMLSignatureUtil.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/IdentityProvider.java
  server-spi-private/src/main/java/org/keycloak/keys/PublicKeyStorageProvider.java
  server-spi/src/main/java/org/keycloak/models/IdentityProviderModel.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProviderConfig.java
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProviderFactory.java
  services/src/main/java/org/keycloak/protocol/saml/SamlAbstractMetadataPublicKeyLoader.java
  services/src/main/java/org/keycloak/protocol/saml/SamlMetadataKeyLocator.java
  services/src/main/java/org/keycloak/protocol/saml/SamlMetadataPublicKeyLoader.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProviderResource.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java
  services/src/test/java/org/keycloak/protocol/saml/SamlMetadataKeyLocatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlMetadataSignedBrokerTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#25119 Update Kerberos provider for user-profile
  federation/kerberos/src/main/java/org/keycloak/federation/kerberos/KerberosFederationProvider.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  server-spi-private/src/main/java/org/keycloak/userprofile/UserProfileUtil.java
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/Assert.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosStandaloneTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPUserProfileTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25101 Register event not triggered on external to internal token exchange
  services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/BrokerLinkAndTokenExchangeTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25088 fix: corrects the db property handling and null mapped values
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
Labels: team/cloud-native, flaky-test, backport/23.0

#25071 Add release labels to issues on merge
  .github/scripts/pr-find-issues.sh
  .github/workflows/label.yml
Labels: flaky-test

#25126 Fix cross-links in guides and remove unprocessed content in include
  docs/guides/high-availability/introduction.adoc
  docs/guides/high-availability/partials/aurora/aurora-create-peering-connections.adoc
  docs/guides/operator/index.adoc
Labels: team/cloud-native

#25127 Fix cross-links in guides and remove unprocessed content in include
  docs/guides/high-availability/introduction.adoc
  docs/guides/high-availability/partials/aurora/aurora-create-peering-connections.adoc
  docs/guides/operator/index.adoc
Labels: team/cloud-native

#24937 Add options to change behavior on how unmanaged attributes are managed
  core/src/main/java/org/keycloak/representations/userprofile/config/UPConfig.java
  js/apps/account-ui/test/admin-client.ts
  js/apps/account-ui/test/personal-info/personal-info.spec.ts
  js/apps/admin-ui/cypress/support/util/AdminClient.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/components/key-value-form/AttributeForm.tsx
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
  js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx
  js/apps/admin-ui/src/components/users/UserDataTableToolbarItems.tsx
  js/apps/admin-ui/src/components/users/resource.ts
  js/apps/admin-ui/src/context/RealmsContext.tsx
  js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
  js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
  js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
  js/apps/admin-ui/src/realm-settings/routes/UserProfile.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/UserProfileContext.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
  js/apps/admin-ui/src/user/EditUser.tsx
  js/apps/admin-ui/src/user/UserAttributes.tsx
  js/apps/admin-ui/src/user/form-state.ts
  js/libs/keycloak-admin-client/src/defs/userProfileMetadata.ts
  js/libs/keycloak-admin-client/src/resources/realms.ts
  js/libs/keycloak-admin-client/src/resources/users.ts
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AdminExtResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UIRealmResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UIRealmsResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UserResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UsersResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/UIRealmRepresentation.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultUserProfile.java
  server-spi/src/main/java/org/keycloak/userprofile/AttributeMetadata.java
  server-spi/src/main/java/org/keycloak/userprofile/Attributes.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/forms/login/freemarker/model/AbstractUserProfileBean.java
  services/src/main/java/org/keycloak/services/resources/admin/UserProfileResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: status/hold, team/cloud-native, team/store, team/core, team/ui, flaky-test

#25161 Fix 'Cancel' button in the user form
  js/apps/admin-ui/src/user/UserForm.tsx
Labels: team/ui

#25162 Map Store Removal: Delete map profiles from testsuite
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/pom.xml
  testsuite/utils/pom.xml
Labels: team/cloud-native, team/store, team/core

#25048 Localize Spanish language
  themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
Labels: flaky-test

#25159 fix: corrects the db property handling and null mapped values (#25088)
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
Labels: team/cloud-native

#24080 NoSuchFileException with ${kc.home.dir} on Windows
  quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java
Labels: team/cloud-native, flaky-test

#25138 If application has no URL, render text only
  js/apps/account-ui/src/applications/Applications.tsx
Labels: team/ui
