Repository keycloak/keycloak, pull requests merged in 2023-06, with the labels that each got.

#20692 Removing unnecessary message from main command help text
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Main.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testDefaultToHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testHelpShort.unix.approved.txt
Labels: team/cloud-native

#20543 Documentation for User Storage Spi is incorrect
  docs/documentation/server_development/topics/auth-spi.adoc
  docs/documentation/server_development/topics/user-storage.adoc
  docs/documentation/server_development/topics/user-storage/cache.adoc
  docs/documentation/server_development/topics/user-storage/import.adoc
Labels: team/store

#20712 moved filter to it's own component
  js/apps/admin-ui/src/sessions/SessionsSection.tsx
Labels: team/ui

#20653 navigate back to list when deleted
  js/apps/admin-ui/src/client-scopes/EditClientScope.tsx
Labels: team/ui

#20652 use the first value from options as default
  js/apps/admin-ui/src/components/dynamic/ListComponent.tsx
Labels: team/ui

#20693 Fix for certificate revalidation
  services/src/main/java/org/keycloak/authentication/authenticators/x509/CertificateValidator.java
  services/src/main/java/org/keycloak/truststore/FileTruststoreProviderFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/client/resources/TestingResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509BrowserLoginTest.java
Labels: team/cloud-native, team/store, team/core

#20707 Add `eslint-plugin-react-hooks` to enforce the Rules of Hooks
  js/.eslintrc.js
  js/apps/admin-ui/src/clients/authorization/AuthorizationEvaluate.tsx
  js/package.json
  js/pnpm-lock.yaml
Labels: kind/task, team/ui

#20661 Add support to the Operator for setting default labels on Keycloak pods
  operator/pom.xml
  operator/src/main/java/org/keycloak/operator/Config.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/main/kubernetes/kustomization.yml
  operator/src/main/resources/application-rhbk.properties
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
  operator/src/test/resources/application.properties
  pom.xml
Labels: team/cloud-native

#20698 Update Keycloak to Quarkus 3.1.0.Final
  pom.xml
Labels: team/cloud-native, team/store

#20709 Execution config not duplicated when duplicating flows
  services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/AbstractAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/FlowTest.java
Labels: team/cloud-native, team/store, team/core

#20714 Group list isn't filtered based on permission like user lists
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/GroupsResource.java
Labels: team/ui, flaky-test

#20727 Update contributing.adoc
  docs/documentation/internal_resources/contributing.adoc
Labels: area/docs, kind/task

#20752 Add simplified Chinese localization for the Admin Console
  js/apps/admin-ui/public/locales/zh-CN/authentication-help.json
  js/apps/admin-ui/public/locales/zh-CN/authentication.json
  js/apps/admin-ui/public/locales/zh-CN/client-scopes-help.json
  js/apps/admin-ui/public/locales/zh-CN/client-scopes.json
  js/apps/admin-ui/public/locales/zh-CN/clientScopes.json
  js/apps/admin-ui/public/locales/zh-CN/clients-help.json
  js/apps/admin-ui/public/locales/zh-CN/clients.json
  js/apps/admin-ui/public/locales/zh-CN/common-help.json
  js/apps/admin-ui/public/locales/zh-CN/common.json
  js/apps/admin-ui/public/locales/zh-CN/dashboard.json
  js/apps/admin-ui/public/locales/zh-CN/dynamic.json
  js/apps/admin-ui/public/locales/zh-CN/events.json
  js/apps/admin-ui/public/locales/zh-CN/groups.json
  js/apps/admin-ui/public/locales/zh-CN/identity-providers-help.json
  js/apps/admin-ui/public/locales/zh-CN/identity-providers.json
  js/apps/admin-ui/public/locales/zh-CN/realm-settings-help.json
  js/apps/admin-ui/public/locales/zh-CN/realm-settings.json
  js/apps/admin-ui/public/locales/zh-CN/realm.json
  js/apps/admin-ui/public/locales/zh-CN/roles.json
  js/apps/admin-ui/public/locales/zh-CN/sessions.json
  js/apps/admin-ui/public/locales/zh-CN/user-federation-help.json
  js/apps/admin-ui/public/locales/zh-CN/user-federation.json
  js/apps/admin-ui/public/locales/zh-CN/users-help.json
  js/apps/admin-ui/public/locales/zh-CN/users.json
Labels: team/ui

#20735 Fix required getting toggled on when creating new UP attribute.
  js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
Labels: team/ui

#20395 Filter first, then sort, and avoid atomics
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  services/src/main/java/org/keycloak/protocol/ProtocolMapperUtils.java
  services/src/main/java/org/keycloak/protocol/docker/DockerAuthV2Protocol.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/UserInfoEndpoint.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientScopeEvaluateResource.java
Labels: team/core, flaky-test

#20748 #20742 - Fixed Slovak translations for plurals - seconds, minutes, hours, days
  themes/src/main/resources-community/theme/base/email/messages/messages_sk.properties
Labels: area/translations, flaky-test, team/other

#20754 Remove workaround for legacy consoles from `waitForPageToLoad`
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/WaitUtils.java
Labels: area/testsuite, area/account/ui, area/admin/ui, kind/task, team/ui, flaky-test, team/continuous-testing

#20450 theme.properties customizations for account v3
  js/apps/account-ui/pom.xml
  js/apps/account-ui/src/environment.ts
  js/apps/account-ui/src/root/Root.tsx
Labels: team/ui, flaky-test

#20759 Manage elytron configuration if configured for JDK-17
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/AppServerTestEnricher.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20606 Setting ParallelGC as the default garbage collector
  quarkus/dist/src/main/content/bin/kc.bat
  quarkus/dist/src/main/content/bin/kc.sh
Labels: team/cloud-native

#20784 Fix test for brute force detection of recovery codes
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RecoveryAuthnCodesAuthenticatorTest.java
Labels: team/ui, team/continuous-testing

#20590 join title and expand section together
  js/apps/admin-ui/src/dashboard/ProviderInfo.tsx
Labels: team/ui

#20572 Improved Reset OTP authenticator
  server-spi-private/src/main/java/org/keycloak/forms/login/LoginFormsPages.java
  server-spi-private/src/main/java/org/keycloak/forms/login/LoginFormsProvider.java
  services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetOTP.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/forms/login/freemarker/Templates.java
  services/src/main/java/org/keycloak/services/messages/Messages.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/ResetOtpPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/InitialFlowsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/ProvidersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetOtpTest.java
  themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_de.properties
  themes/src/main/resources/theme/base/login/login-reset-otp.ftl
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/cloud-native, team/store, team/core, flaky-test

#20728 Remove Fabric8 override from the Operator
  operator/pom.xml
Labels: team/cloud-native, flaky-test

#20788 Update dependencies to latest version
  js/apps/account-ui/package.json
  js/apps/admin-ui/package.json
  js/libs/keycloak-admin-client/package.json
  js/libs/keycloak-js/package.json
  js/libs/keycloak-masthead/package.json
  js/libs/ui-shared/package.json
  js/package.json
  js/pnpm-lock.yaml
  pom.xml
Labels: area/dependencies, kind/task, team/ui

#20733 Check if formData is empty before putting login hint
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
Labels: team/ui, flaky-test

#20819 Use new method for obtaining DB dialect
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/hibernate/contributor/JpaMapFunctionContributor.java
Labels: team/store

#20832 Pass webauthn signature algorithm IDs as integers instead of strings
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnRegister.java
  themes/src/main/resources/theme/base/login/webauthn-register.ftl
Labels: flaky-test

#20786 Stop waiting page load when calling `assertCurrent()`
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/AbstractPage.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20793 EventBuilder fixes to copy the store and session context
  server-spi-private/src/main/java/org/keycloak/events/EventBuilder.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/events/TestEventsListenerContextDetailsProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/events/TestEventsListenerContextDetailsProviderFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/resources/META-INF/services/org.keycloak.events.EventListenerProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/EventStoreProviderTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#16540 Fix erroneous return of parent group when querying for groups via attribute keycloak/keycloak#16535
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/GroupsResource.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupSearchTest.java
Labels: area/admin/api, team/cloud-native, team/store, team/core, flaky-test

#20657 Update the docs
  docs/documentation/release_notes/topics/22_0_0.adoc
  docs/guides/server/fips.adoc
Labels: team/cloud-native

#20825 mostly updating the logic to newer fabric8 apis
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngress.java
  operator/src/main/java/org/keycloak/operator/controllers/OperatorManagedResource.java
  operator/src/main/java/org/keycloak/operator/controllers/WatchedSecretsStore.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakSpec.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/ValueOrSecret.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/DatabaseSpec.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/FeatureSpec.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/HostnameSpec.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/HttpSpec.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/IngressSpec.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/TransactionsSpec.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/UnsupportedSpec.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/ClusteringTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakServicesTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/PodTemplateTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/RealmImportTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/K8sUtils.java
Labels: team/cloud-native, flaky-test

#19110 these will fix issue (#14860) and (#15136) for UPDATE_EMAIL feature
  services/src/main/java/org/keycloak/authentication/actiontoken/updateemail/UpdateEmailActionToken.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateEmail.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionUpdateEmailWithVerificationTest.java
Labels: area/core, team/cloud-native, team/store, team/core, flaky-test

#20828 enabling keycloak to be a scalable resource
  operator/src/main/java/org/keycloak/operator/Constants.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDiscoveryService.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDistConfigurator.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngress.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakService.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakSpec.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakStatus.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakStatusAggregator.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/ClusteringTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/KeycloakDistConfiguratorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/KeycloakStatusTest.java
Labels: team/cloud-native, flaky-test

#20811 Fix pagination issue with H6
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/OfflinePersistentUserSessionLoader.java
  model/jpa/src/main/java/org/keycloak/models/jpa/PaginationUtils.java
  model/jpa/src/main/java/org/keycloak/models/jpa/session/JpaUserSessionPersisterProvider.java
  model/legacy-private/src/main/java/org/keycloak/models/session/PersistentAuthenticatedClientSessionAdapter.java
  model/legacy-private/src/main/java/org/keycloak/models/session/PersistentUserSessionAdapter.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java
Labels: team/store, flaky-test

#20804 Upgrade to Infinispan 14.0.10.Final
  pom.xml
Labels: flaky-test

#20731 Removing 'http challenge' authentication flow and related authenticators
  docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc
  model/legacy-private/src/main/java/org/keycloak/migration/migrators/MigrateTo22_0_0.java
  model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyMigrationManager.java
  server-spi-private/src/main/java/org/keycloak/models/utils/DefaultAuthenticationFlows.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  services/src/main/java/org/keycloak/authentication/authenticators/challenge/BasicAuthAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/challenge/BasicAuthAuthenticatorFactory.java
  services/src/main/java/org/keycloak/authentication/authenticators/challenge/BasicAuthOTPAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/challenge/BasicAuthOTPAuthenticatorFactory.java
  services/src/main/java/org/keycloak/authentication/authenticators/challenge/NoCookieFlowRedirectAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/challenge/NoCookieFlowRedirectAuthenticatorFactory.java
  services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java
  services/src/main/resources/META-INF/services/org.keycloak.authentication.AuthenticatorFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/ExecutionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/InitialFlowsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/ProvidersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosLdapTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/FlowOverrideTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport198MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport255MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport343MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport483MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport903MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/kerberos/kerberosrealm.json
Labels: team/cloud-native, team/store, team/core, flaky-test

#20480 Use OIDCAttributeMapperHelper.mapClaim in the GroupMembershipMapper
  services/src/main/java/org/keycloak/protocol/oidc/mappers/GroupMembershipMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupMappersTest.java
Labels: team/cloud-native, team/store, team/core

#20856 expands the status handling to account for the prior status
  operator/src/main/java/org/keycloak/operator/Utils.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakStatus.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakStatusAggregator.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakStatusCondition.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/KeycloakDistConfiguratorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/KeycloakStatusTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/CRAssert.java
Labels: team/cloud-native, flaky-test

#19394 Strip rotated client secret from export json
  server-spi-private/src/main/java/org/keycloak/models/utils/StripSecretsUtils.java
  server-spi-private/src/test/java/org/keycloak/models/StripSecretsUtilsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/partialexport/PartialExportTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/export/partialexport-testrealm.json
Labels: team/cloud-native, team/store, team/core, flaky-test

#20824 Clean-up of deprecated methods and interfaces
  docs/documentation/server_development/topics/user-storage/augmenting.adoc
  docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  model/jpa/src/main/java/org/keycloak/storage/jpa/JpaUserFederatedStorageProvider.java
  model/legacy-private/src/main/java/org/keycloak/models/session/UserSessionPersisterProvider.java
  model/legacy-private/src/main/java/org/keycloak/storage/adapter/InMemoryUserAdapter.java
  model/legacy-services/src/main/java/org/keycloak/services/legacysessionsupport/LegacySessionSupportProviderFactory.java
  model/legacy-services/src/main/java/org/keycloak/services/legacysessionsupport/LegacySessionSupportProviderImpl.java
  model/legacy-services/src/main/java/org/keycloak/services/legacysessionsupport/LegacySessionSupportSpi.java
  model/legacy-services/src/main/resources/META-INF/services/org.keycloak.provider.Spi
  model/legacy/src/main/java/org/keycloak/models/LegacySessionSupportProvider.java
  model/legacy/src/main/java/org/keycloak/models/UserCredentialManager.java
  model/legacy/src/main/java/org/keycloak/models/UserModelDefaultMethods.java
  model/legacy/src/main/java/org/keycloak/models/cache/CachedUserModel.java
  model/legacy/src/main/java/org/keycloak/models/cache/UserCache.java
  model/legacy/src/main/java/org/keycloak/storage/adapter/AbstractUserAdapterFederatedStorage.java
  model/legacy/src/main/java/org/keycloak/storage/federated/UserAttributeFederatedStorage.java
  model/legacy/src/main/java/org/keycloak/storage/federated/UserBrokerLinkFederatedStorage.java
  model/legacy/src/main/java/org/keycloak/storage/federated/UserConsentFederatedStorage.java
  model/legacy/src/main/java/org/keycloak/storage/federated/UserFederatedStorageProvider.java
  model/legacy/src/main/java/org/keycloak/storage/federated/UserFederatedUserCredentialStore.java
  model/legacy/src/main/java/org/keycloak/storage/federated/UserGroupMembershipFederatedStorage.java
  model/legacy/src/main/java/org/keycloak/storage/federated/UserRequiredActionsFederatedStorage.java
  model/legacy/src/main/java/org/keycloak/storage/federated/UserRoleMappingsFederatedStorage.java
  model/map/src/main/java/org/keycloak/models/map/datastore/ImportKeycloakSession.java
  model/map/src/main/java/org/keycloak/models/map/realm/MapRealmAdapter.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi-private/src/test/java/org/keycloak/broker/provider/util/IdentityBrokerStateTestHelpers.java
  server-spi/src/main/java/org/keycloak/credential/CredentialInputUpdater.java
  server-spi/src/main/java/org/keycloak/credential/UserCredentialStore.java
  server-spi/src/main/java/org/keycloak/models/GroupModel.java
  server-spi/src/main/java/org/keycloak/models/KeycloakSession.java
  server-spi/src/main/java/org/keycloak/models/RealmModel.java
  server-spi/src/main/java/org/keycloak/models/RoleMapperModel.java
  server-spi/src/main/java/org/keycloak/models/UserModel.java
  server-spi/src/main/java/org/keycloak/models/UserProvider.java
  server-spi/src/main/java/org/keycloak/storage/user/UserLookupProvider.java
  server-spi/src/main/java/org/keycloak/storage/user/UserQueryProvider.java
  services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java
  services/src/main/java/org/keycloak/services/util/ScopeMappedUtil.java
  services/src/main/resources/META-INF/services/org.keycloak.provider.Spi
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UserManagedPermissionServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPSyncTest.java
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/utils/WebAuthnDataWrapper.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20713 added missing "allow ecp flow" field
  js/apps/admin-ui/public/locales/en/clients-help.json
  js/apps/admin-ui/public/locales/en/clients.json
  js/apps/admin-ui/src/clients/add/SamlConfig.tsx
Labels: team/ui

#20717 use id instead of name
  js/apps/admin-ui/src/client-scopes/add/MapperDialog.tsx
Labels: team/ui

#20772 use ui ext groups endpoint
  js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx
Labels: team/ui

#20774 use admin client instead of fetch
  js/apps/admin-ui/src/identity-providers/add/OpenIdConnectSettings.tsx
  js/libs/keycloak-admin-client/src/resources/agent.ts
  js/libs/keycloak-admin-client/src/resources/identityProviders.ts
Labels: team/ui

#20813 added fix for url encoded paths
  js/apps/admin-ui/src/components/routable-tabs/RoutableTabs.tsx
Labels: team/ui

#20816 increased policy row with
  js/apps/admin-ui/src/authentication/policies/policy-row.css
Labels: team/ui

#20880 added test saml advanced tab
  js/apps/admin-ui/cypress/e2e/clients_saml_advanced.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/tabs/AdvancedSamlTab.ts
  js/apps/admin-ui/src/clients/advanced/ApplicationUrls.tsx
  js/apps/admin-ui/src/clients/advanced/FineGrainSamlEndpointConfig.tsx
  js/libs/ui-shared/src/controls/TextControl.tsx
Labels: team/ui

#20881 little wrapper around the time selector
  js/apps/admin-ui/src/clients/advanced/ClusteringPanel.tsx
  js/apps/admin-ui/src/components/time-selector/TimeSelector.tsx
  js/apps/admin-ui/src/components/time-selector/TimeSelectorForm.tsx
Labels: team/ui

#20890 Session cross-reference / transaction mismatch
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  services/src/main/java/org/keycloak/common/util/ResponseSessionTask.java
Labels: flaky-test

#20893 Remove override of mime4j version in parent pom
  pom.xml
Labels: flaky-test

#20897 Handle HTTP response codes when retrieving data from remote endpoints
  server-spi-private/src/main/java/org/keycloak/connections/httpclient/HttpClientProvider.java
  services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java
Labels: flaky-test

#20887 Make "Personal Info" the default index route
  js/apps/account-ui/public/locales/en/translation.json
  js/apps/account-ui/src/root/PageNav.tsx
  js/apps/account-ui/src/root/RootIndex.tsx
  js/apps/account-ui/src/routes.tsx
Labels: team/ui

#19574 17728 - Added User Attribute Search
  js/apps/admin-ui/public/locales/de/common.json
  js/apps/admin-ui/public/locales/de/users.json
  js/apps/admin-ui/public/locales/en/common.json
  js/apps/admin-ui/public/locales/en/users.json
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
  js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx
  js/apps/admin-ui/src/components/users/UserDataTableToolbarItems.tsx
  js/apps/admin-ui/src/user/UserProfileFields.tsx
  js/apps/admin-ui/src/user/details/SearchFilter.tsx
  js/apps/admin-ui/src/user/user-section.css
  js/apps/admin-ui/src/user/utils.ts
Labels: team/ui

#16614 Impossible to update a federated user credential label
  model/jpa/src/main/java/org/keycloak/storage/jpa/JpaUserFederatedStorageProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
Labels: team/cloud-native, team/store, flaky-test

#20440 Update UserQueryProvider interface
  docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java
  server-spi/pom.xml
  server-spi/src/main/java/org/keycloak/storage/user/UserCountMethodsProvider.java
  server-spi/src/main/java/org/keycloak/storage/user/UserQueryMethodsProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/BackwardsCompatibilityUserStorage.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/FailableHardcodedStorageProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/UserMapStorage.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/UserPropertyFileStorage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPProvidersIntegrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/noimport/LDAPProvidersIntegrationNoImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageFailureTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/MultipleRealmsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserModelTest.java
  testsuite/model/pom.xml
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/user/UserPaginationTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20891 Removes the check for full readiness of 3 replicas
  operator/src/test/java/org/keycloak/operator/testsuite/integration/ClusteringTest.java
Labels: team/cloud-native, flaky-test

#20814 Avoid iterating indefinetly when checking CRLs
  services/src/main/java/org/keycloak/utils/CRLUtils.java
  testsuite/integration-arquillian/servers/auth-server/common/fips/keycloak-fips.keystore.bcfks
  testsuite/integration-arquillian/servers/auth-server/common/fips/keycloak-fips.truststore.bcfks
  testsuite/integration-arquillian/servers/auth-server/common/fips/keycloak-fips.truststore.pkcs12
  testsuite/integration-arquillian/servers/auth-server/common/keystore/invalid.crl
  testsuite/integration-arquillian/servers/auth-server/common/keystore/keycloak.truststore
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/AbstractX509AuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/CRLRule.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509BrowserCRLTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20632 High severity - Use of a Broken or Risky Cryptographic Algorithm vulnerability in org.bitbucket.b_c:jose4j
  pom.xml
Labels: flaky-test

#20950 Simplify TokenManager expiration calculations using SessionExpirationUtils
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
Labels: team/cloud-native, team/store, team/core

#20866 using multiple SchemaSwap annotations instead of the schell script
  operator/patch-sources.sh
  operator/pom.xml
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/realmimport/KeycloakRealmImport.java
Labels: team/cloud-native, flaky-test

#20912 Restore feature flags and hidden menu items.
  js/apps/account-ui/pom.xml
  js/apps/account-ui/src/environment.ts
  js/apps/account-ui/src/root/PageNav.tsx
Labels: team/ui, flaky-test

#20961 Pass client id for Account and Admin consoles through environment
  js/apps/account-ui/pom.xml
  js/apps/account-ui/src/environment.ts
  js/apps/account-ui/src/keycloak.ts
  js/apps/admin-ui/pom.xml
  js/apps/admin-ui/src/environment.ts
  js/apps/admin-ui/src/keycloak.ts
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
  services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java
Labels: area/account/ui, area/admin/ui, kind/task, team/ui, flaky-test

#20430 Trigger the invalidation of the realm when a client scope changes
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedRealm.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/clientscope/ClientScopeModelTest.java
Labels: team/store, flaky-test

#20975 Enable Dependabot for PNPM
  .github/dependabot.yml
  js/package.json
  pom.xml
Labels: kind/task, team/ui, flaky-test

#20923 remove attributes form when use profile enabled
  js/apps/admin-ui/src/user/EditUser.tsx
  js/apps/admin-ui/src/user/UserAttributes.tsx
  js/apps/admin-ui/src/user/UserForm.tsx
Labels: team/ui

#20865 fixed pagination on the sessions tab
  js/apps/admin-ui/src/sessions/SessionsSection.tsx
  js/apps/admin-ui/src/sessions/SessionsTable.tsx
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/SessionsResource.java
Labels: team/ui, flaky-test

#20979 Prevent NPE on close() if postInit() hasn't been called
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProviderFactory.java
  model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyDatastoreProviderFactory.java
Labels: team/store, flaky-test

#20952 move jumplinks to the top if there no room
  js/apps/admin-ui/src/components/scroll-form/ScrollForm.tsx
Labels: team/ui

#20958 Upgrade to Quarkus 3.1.1.Final
  operator/pom.xml
  pom.xml
Labels: team/cloud-native, flaky-test

#21002 Update dependencies to latest version
  js/apps/account-ui/package.json
  js/apps/admin-ui/package.json
  js/libs/keycloak-admin-client/package.json
  js/libs/keycloak-js/package.json
  js/libs/keycloak-masthead/package.json
  js/libs/ui-shared/package.json
  js/package.json
  js/pnpm-lock.yaml
Labels: area/dependencies, kind/task, team/ui

#20969 Promote Account Console v3 to preview
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
  docs/documentation/release_notes/topics/22_0_0.adoc
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FeaturesDistTest.java
Labels: team/cloud-native, team/ui, flaky-test

#19747 Adding a list of translated texts, to check the right path
  js/apps/account-ui/public/locales/fa/translation.json
  themes/src/main/resources-community/theme/base/account/messages/messages_ar.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_da.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_fa.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_fi.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_hu.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_lt.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_lv.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_nl.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_no.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_pl.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ru.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_sk.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_sv.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_zh_CN.properties
  themes/src/main/resources-community/theme/base/account/theme.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_fa.properties
  themes/src/main/resources-community/theme/base/admin/theme.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_fa.properties
  themes/src/main/resources-community/theme/base/email/theme.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fa.properties
  themes/src/main/resources-community/theme/base/login/theme.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_fa.properties
  themes/src/main/resources/theme/base/account/messages/messages_en.properties
Labels: area/translations, team/ui, flaky-test

#21034 Save ~2s for Keycloak startup in the testsuite
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
Labels: team/cloud-native, team/store, team/core

#21036 Ensure `RegisterTest` runs in Chrome and Firefox
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/RegisterPage.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21006 added missing delete account feature
  js/apps/account-ui/public/locales/en/translation.json
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
Labels: team/ui

#21025 remove icon label from text input
  js/libs/ui-shared/src/controls/TextControl.tsx
Labels: team/ui

#21030 added `isLinkedAccountEnabled`
  js/apps/account-ui/src/root/PageNav.tsx
Labels: team/ui

#20964 use array instead of first
  js/apps/admin-ui/src/user-federation/shared/Header.tsx
Labels: team/ui

#20949 added default values for user profile annotations
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/UserProfile.ts
  js/apps/admin-ui/public/locales/en/common.json
  js/apps/admin-ui/public/locales/en/realm-settings.json
  js/apps/admin-ui/src/components/key-value-form/KeySelect.tsx
  js/apps/admin-ui/src/components/key-value-form/KeyValueInput.tsx
  js/apps/admin-ui/src/components/key-value-form/ValueSelect.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeAnnotations.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeValidations.tsx
Labels: team/ui

#20189 Extends the conditional user attribute authenticator to check the att…
  docs/documentation/server_admin/topics/authentication/conditions.adoc
  services/src/main/java/org/keycloak/authentication/authenticators/conditional/ConditionalUserAttributeValue.java
  services/src/main/java/org/keycloak/authentication/authenticators/conditional/ConditionalUserAttributeValueFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ConditionalUserAttributeAuthenticatorTest.java
Labels: missing/tests, team/cloud-native, team/store, team/core

#21077 Upgrade TypeScript to latest version
  js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
  js/package.json
  js/pnpm-lock.yaml
Labels: area/dependencies, team/ui

#21052 Update to Quarkus 3.1.2.Final
  pom.xml
Labels: team/cloud-native, flaky-test

#20963 Documentation on LDAP secure connection
  docs/guides/server/keycloak-truststore.adoc
Labels: team/cloud-native

#20990 Remove account package from testsuite
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/account/Account.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/account/AccountManagement.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/account/Applications.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/account/Autheticator.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/account/ChangePassword.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/account/Sessions.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/account/fragment/AccountManagementPatternFlyAlert.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractAuthTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/custom/AbstractAccountManagementTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/example/cors/CorsExampleAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SessionServletAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/undertow/servlet/UndertowRelaviteUriAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ConsentsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/AbstractClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/event/AbstractEventTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/event/EmailEventListenerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerLoginHintTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/SSOTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LegacyLogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RPInitiatedLogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCAdvancedRequestParamsTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/LDAPAccountTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/LinkedAccountsTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/login/AbstractLoginTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/login/LoginPageTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/login/RequiredActionsTest.java
  testsuite/integration-arquillian/tests/other/springboot-tests/src/test/java/org/keycloak/testsuite/springboot/AccountLinkSpringBootTest.java
  testsuite/integration-arquillian/tests/other/springboot-tests/src/test/java/org/keycloak/testsuite/springboot/SessionSpringBootTest.java
Labels: priority/critical, team/cloud-native, team/store, team/core, team/ui

#20967 Update docs and tooltips for lifespan and idle timeout changes
  docs/documentation/server_admin/images/client-advanced-settings-oidc.png
  docs/documentation/server_admin/topics/clients/oidc/con-advanced-settings.adoc
  docs/documentation/server_admin/topics/sessions/offline.adoc
  docs/documentation/server_admin/topics/sessions/timeouts.adoc
  js/apps/admin-ui/public/locales/en/clients-help.json
  js/apps/admin-ui/public/locales/en/clients.json
  js/apps/admin-ui/public/locales/en/realm-settings-help.json
Labels: team/ui

#20809 added initial playwright test
  js/apps/account-ui/.gitignore
  js/apps/account-ui/package.json
  js/apps/account-ui/playwright.config.ts
  js/apps/account-ui/src/personal-info/FormField.tsx
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
  js/apps/account-ui/src/root/PageNav.tsx
  js/apps/account-ui/test/auth.setup.ts
  js/apps/account-ui/test/personal-info.spec.ts
  js/libs/ui-shared/src/alerts/Alerts.tsx
  js/pnpm-lock.yaml
Labels: team/ui

#21105 Use installed driver for Firefox on GitHub runners
  .github/workflows/ci.yml
Labels: flaky-test

#20672 Use quarkus-operator-sdk-bundle-generator for OLM YAMLs
  operator/olm-assembly.xml
  operator/olm-base/bundle.Dockerfile
  operator/olm-base/manifests/clusterserviceversion.yaml
  operator/olm-base/metadata/annotations.yaml
  operator/pom.xml
  operator/scripts/create-olm-bundle.sh
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakSharedCsvMetadata.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/Keycloak.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/realmimport/KeycloakRealmImport.java
  operator/src/main/kubernetes/KeycloakController.icon.png
  operator/src/main/resources/application.properties
Labels: team/cloud-native, flaky-test

#21098 Removed old account console
  model/legacy-private/src/main/java/org/keycloak/migration/migrators/MigrateTo22_0_0.java
  server-spi-private/src/main/java/org/keycloak/forms/account/AccountPages.java
  server-spi-private/src/main/java/org/keycloak/forms/account/AccountProvider.java
  server-spi-private/src/main/java/org/keycloak/forms/account/AccountProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/forms/account/AccountSpi.java
  server-spi-private/src/main/resources/META-INF/services/org.keycloak.provider.Spi
  services/src/main/java/org/keycloak/forms/account/freemarker/FreeMarkerAccountProvider.java
  services/src/main/java/org/keycloak/forms/account/freemarker/FreeMarkerAccountProviderFactory.java
  services/src/main/java/org/keycloak/forms/account/freemarker/Templates.java
  services/src/main/java/org/keycloak/forms/account/freemarker/model/AccountBean.java
  services/src/main/java/org/keycloak/forms/account/freemarker/model/AccountFederatedIdentityBean.java
  services/src/main/java/org/keycloak/forms/account/freemarker/model/ApplicationsBean.java
  services/src/main/java/org/keycloak/forms/account/freemarker/model/AuthorizationBean.java
  services/src/main/java/org/keycloak/forms/account/freemarker/model/FeaturesBean.java
  services/src/main/java/org/keycloak/forms/account/freemarker/model/LogBean.java
  services/src/main/java/org/keycloak/forms/account/freemarker/model/PasswordBean.java
  services/src/main/java/org/keycloak/forms/account/freemarker/model/RealmBean.java
  services/src/main/java/org/keycloak/forms/account/freemarker/model/ReferrerBean.java
  services/src/main/java/org/keycloak/forms/account/freemarker/model/SessionsBean.java
  services/src/main/java/org/keycloak/forms/account/freemarker/model/TotpBean.java
  services/src/main/java/org/keycloak/forms/account/freemarker/model/UrlBean.java
  services/src/main/java/org/keycloak/services/Urls.java
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  services/src/main/java/org/keycloak/services/resources/PublicRealmResource.java
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
  services/src/main/java/org/keycloak/services/resources/account/AccountFormService.java
  services/src/main/java/org/keycloak/services/resources/account/AccountLoader.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  services/src/main/resources/META-INF/services/org.keycloak.forms.account.AccountProviderFactory
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/examples/providersoverride/CustomDefaultEmailSenderProvider1.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/examples/providersoverride/CustomDefaultEmailSenderProvider2.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/examples/providersoverride/CustomDefaultEmailSenderProviderFactory1.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/examples/providersoverride/CustomDefaultEmailSenderProviderFactory2.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/resources/META-INF/services/org.keycloak.email.EmailSenderProviderFactory
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/AbstractAccountPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ConsentsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UmaRepresentationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/providers/ProvidersOverrideTest.java
  themes/UPDATING-NODE-MODULES.md
  themes/src/main/resources/META-INF/keycloak-themes.json
  themes/src/main/resources/theme/base/account/account.ftl
  themes/src/main/resources/theme/base/account/applications.ftl
  themes/src/main/resources/theme/base/account/federatedIdentity.ftl
  themes/src/main/resources/theme/base/account/log.ftl
  themes/src/main/resources/theme/base/account/password.ftl
  themes/src/main/resources/theme/base/account/resource-detail.ftl
  themes/src/main/resources/theme/base/account/resources.ftl
  themes/src/main/resources/theme/base/account/sessions.ftl
  themes/src/main/resources/theme/base/account/template.ftl
  themes/src/main/resources/theme/base/account/totp.ftl
  themes/src/main/resources/theme/keycloak/account/resources/css/account.css
  themes/src/main/resources/theme/keycloak/account/resources/img/icon-sidebar-active.png
  themes/src/main/resources/theme/keycloak/account/resources/img/keycloak-logo.png
  themes/src/main/resources/theme/keycloak/account/resources/img/logo.png
  themes/src/main/resources/theme/keycloak/account/theme.properties
Labels: team/cloud-native, team/store, team/core, flaky-test

#21039 Remove unused feature flags.
  docs/documentation/release_notes/topics/22_0_0.adoc
  js/apps/account-ui/pom.xml
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
  themes/src/main/resources/theme/keycloak.v2/account/index.ftl
Labels: team/ui, flaky-test

#21101 Incorrect Signature algorithms presented by Client Authenticator
  core/src/main/java/org/keycloak/representations/info/CryptoInfoRepresentation.java
  js/apps/admin-ui/public/locales/en/clients-help.json
  js/apps/admin-ui/src/clients/credentials/Credentials.tsx
  js/apps/admin-ui/src/clients/credentials/SignedJWT.tsx
  js/libs/keycloak-admin-client/src/defs/serverInfoRepesentation.ts
  server-spi-private/src/main/java/org/keycloak/crypto/ClientSignatureVerifierProvider.java
  services/src/main/java/org/keycloak/crypto/AsymmetricClientSignatureVerifierProvider.java
  services/src/main/java/org/keycloak/crypto/ECDSAClientSignatureVerifierProvider.java
  services/src/main/java/org/keycloak/crypto/MacSecretClientSignatureVerifierProvider.java
  services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ServerInfoTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#14893 Admin API - Count users by custom user attribute
  docs/documentation/release_notes/topics/22_0_0.adoc
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/UsersResource.java
  model/map/src/main/java/org/keycloak/models/map/user/MapUserProvider.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
Labels: flaky-test

#21005 Extend admin-client GroupsResource: Enhanced query functionality
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/GroupsResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupSearchTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21126 Fixing auth-server-quarkus-embedded
  quarkus/tests/junit5/pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
Labels: team/cloud-native, team/store, team/core

#21009 removing the usage of MultivaluedStringStringHashMap
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/realmimport/KeycloakRealmImport.java
  operator/src/main/java/org/keycloak/representations/overrides/ComponentExportRepresentationMap.java
  operator/src/main/java/org/keycloak/representations/overrides/MultivaluedStringStringHashMap.java
  operator/src/main/java/org/keycloak/representations/overrides/NoSubcomponentsComponentExportRepresentation.java
Labels: team/cloud-native, flaky-test

#21129 Account Console II doesn't remove TOTP from UserStorage
  services/src/main/java/org/keycloak/services/resources/account/AccountCredentialResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/BackwardsCompatibilityUserStorageTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21048 Incorrect Url on Keycloak Health - Liveness and Readiness, no Startup Probes
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
Labels: team/cloud-native, flaky-test

#21117 Support reading base32 encoded OTP secret
  server-spi-private/src/main/java/org/keycloak/models/utils/CredentialValidation.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  server-spi-private/src/main/java/org/keycloak/models/utils/TimeBasedOTP.java
  server-spi-private/src/test/java/org/keycloak/models/TotpTest.java
  server-spi/src/main/java/org/keycloak/models/credential/OTPCredentialModel.java
  server-spi/src/main/java/org/keycloak/models/credential/dto/OTPCredentialData.java
  server-spi/src/main/java/org/keycloak/models/utils/HmacOTP.java
  services/src/main/java/org/keycloak/credential/OTPCredentialProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTotpTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21110 Avoid calls to Control Plane when the secondary resource is in cache
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
Labels: team/cloud-native, flaky-test

#20655 Check whether CREATE_REALM role exists (Closes #20332)
  services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java
Labels: flaky-test

#20965 running mappers during account linking
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/ClientInitiatedAccountLinkTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21159 processGrantRequest in TokenEndPoint uses new TokenManager instead of this.tokenMananager
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
Labels: flaky-test

#21004 ResourceType lost during cloning
  services/src/main/java/org/keycloak/services/resources/admin/AdminEventBuilder.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/partialimport/PartialImportTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21142 Allow view client roles tab without view-realm access
  js/apps/admin-ui/src/clients/routes/ClientRole.tsx
  js/apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
  js/apps/admin-ui/src/components/roles-list/RolesList.tsx
  js/apps/admin-ui/src/realm-roles/RealmRoleTabs.tsx
Labels: team/ui

#21084 Guava vulnerable to insecure use of temporary directory
  pom.xml
Labels: team/cloud-native, team/core, flaky-test

#20933 finishes the conversion away from createOrReplace
  docs/documentation/release_notes/topics/22_0_0.adoc
  operator/src/main/java/org/keycloak/operator/Utils.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakAdminSecret.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDiscoveryService.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDistConfigurator.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngress.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJob.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakService.java
  operator/src/main/java/org/keycloak/operator/controllers/MetadataAwareOnUpdateFilter.java
  operator/src/main/java/org/keycloak/operator/controllers/OperatorManagedResource.java
  operator/src/main/java/org/keycloak/operator/controllers/WatchedSecretsStore.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/ClusteringTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakServicesTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/PodTemplateTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/RealmImportTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/KeycloakDistConfiguratorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/K8sUtils.java
Labels: team/cloud-native, flaky-test

#20741 FAPI 2.0 security profile - not allow an authorization request whose parameters were not included in Request Object pushed to PAR request
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/SecureParContentsExecutor.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExecutorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20190 Support for Greek translation and localized messages in Keycloak
  themes/src/main/resources-community/theme/base/account/messages/messages_el.properties
  themes/src/main/resources-community/theme/base/account/theme.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_el.properties
  themes/src/main/resources-community/theme/base/admin/theme.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_el.properties
  themes/src/main/resources-community/theme/base/email/theme.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_el.properties
  themes/src/main/resources-community/theme/base/login/theme.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_el.properties
Labels: area/translations, area/account/ui, area/admin/ui, team/ui

#11760 Add support to indicate desired locale on init func with onLoad: 'log…
  docs/documentation/securing_apps/topics/oidc/javascript-adapter.adoc
  js/libs/keycloak-js/dist/keycloak.d.ts
  js/libs/keycloak-js/src/keycloak.js
Labels: team/ui

#21240 Make awaitInitialTransfer for ISPN configurable
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/Infinispan.java
Labels: area/storage, team/store, flaky-test

#21164 Support for the locale user attribute
  server-spi-private/src/main/java/org/keycloak/userprofile/Attributes.java
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/LegacyAttributes.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/DeclarativeUserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/LoginPageWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20873 Custom theme - url.resourcesCommonPath references wrong theme
  docs/documentation/server_development/topics/themes.adoc
  services/src/main/java/org/keycloak/forms/login/freemarker/model/UrlBean.java
Labels: flaky-test

#21241 Don't allow impersonate disabled users or service accounts
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ImpersonationTest.java
Labels: team/cloud-native, team/store, team/core

#21274 Do not return an error when moving a group to the current parent
  services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java
Labels: team/cloud-native, team/store, team/core

#20896 Ensure basic auth header is encoded properly
  js/libs/keycloak-admin-client/src/utils/auth.ts
Labels: team/ui

#21174 Improve French translation
  themes/src/main/resources-community/theme/base/account/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fr.properties
Labels: area/translations, flaky-test

#21282 Added missing translation for login-config-totp template in spanish
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
Labels: kind/enhancement, area/translations

#21271 Verify holder of the device code (#21)
  server-spi-private/src/main/java/org/keycloak/models/OAuth2DeviceCodeModel.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/CibaGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/device/DeviceGrantType.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/CIBATest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuth2DeviceAuthorizationGrantTest.java
Labels: priority/important, team/cloud-native, team/store, team/core, flaky-test

#17451 Update getting-started-zip.adoc
  docs/guides/getting-started/getting-started-zip.adoc
Labels: status/hold, team/core

#20906 adds an instance label to support multiple instances
  docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc
  operator/src/main/java/org/keycloak/operator/Constants.java
  operator/src/main/java/org/keycloak/operator/Utils.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDiscoveryService.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakService.java
  operator/src/main/java/org/keycloak/operator/controllers/OperatorManagedResource.java
  operator/src/main/java/org/keycloak/operator/controllers/WatchedSecretsStore.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/ClusteringTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/K8sUtils.java
Labels: team/cloud-native, flaky-test

#21280 Add iat to JWT passed to CIBA HttpAuthenticationChannel
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/channel/HttpAuthenticationChannelProvider.java
Labels: flaky-test

#21281 widens status to be any type.
  docs/documentation/release_notes/topics/22_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/StatusCondition.java
Labels: team/cloud-native, flaky-test

#21312 fix identity test
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/AttributesTab.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseGeneralSettingsPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/social/ProviderFacebookGeneralSettings.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/social/ProviderGithubGeneralSettings.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/social/ProviderGoogleGeneralSettings.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/social/ProviderOpenshiftGeneralSettings.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/social/ProviderPaypalGeneralSettings.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/social/ProviderStackoverflowGeneralSettings.ts
Labels: team/ui

#21255 Fixed moderate a11y issues for clients list
  js/apps/admin-ui/src/clients/authorization/Policies.tsx
  js/apps/admin-ui/src/clients/scopes/ClientScopes.tsx
Labels: team/ui

#21286 Fixed a11y issue for groups
  js/apps/admin-ui/src/user/user-section.css
Labels: team/ui

#21267 Fixed moderate and critical a11y issues for realm settings
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
  js/apps/admin-ui/src/realm-settings/ClientProfileForm.tsx
  js/apps/admin-ui/src/realm-settings/EmailTab.tsx
  js/apps/admin-ui/src/realm-settings/NewClientPolicyForm.tsx
  js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
  js/apps/admin-ui/src/realm-settings/realm-settings-section.css
Labels: team/ui

#21302 adding just crd tests of the specs
  operator/pom.xml
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/CRDTest.java
  operator/src/test/resources/test-serialization-realmimport-cr.yml
Labels: team/cloud-native, flaky-test

#20669 Refactor Admin REST API Documentation to use OpenAPI annotations.
  pom.xml
  rest/admin-ui-ext/pom.xml
  services/pom.xml
  services/src/docs/asciidoc/index.adoc
  services/src/docs/asciidoc/overview.adoc
  services/src/docs/openapi-generator-templates/keycloak-admin-api/index.mustache
  services/src/docs/openapi-generator-templates/keycloak-admin-api/model.mustache
  services/src/docs/openapi-generator-templates/keycloak-admin-api/param.mustache
  services/src/docs/openapi-generator-templates/keycloak-admin-api/params.mustache
  services/src/docs/openapi-generator-templates/keycloak-admin-api/stubs/empty.adoc
  services/src/docs/swagger/apiinfo.json
  services/src/main/java/org/keycloak/services/resources/KeycloakOpenAPI.java
  services/src/main/java/org/keycloak/services/resources/admin/AdminRoot.java
  services/src/main/java/org/keycloak/services/resources/admin/AttackDetectionResource.java
  services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientAttributeCertificateResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientInitialAccessResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientPoliciesResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientProfilesResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientRegistrationPolicyResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientRoleMappingsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientScopeEvaluateResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientScopeEvaluateScopeMappingsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientScopeResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientScopesResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ComponentResource.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProviderResource.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java
  services/src/main/java/org/keycloak/services/resources/admin/KeyResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ProtocolMappersResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmLocalizationResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmsAdminResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmsAdminResourcePreflight.java
  services/src/main/java/org/keycloak/services/resources/admin/RoleByIdResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RoleContainerResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RoleMapperResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ScopeMappedClientResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ScopeMappedResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UserProfileResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
  services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java
Labels: team/ui, flaky-test

#20188 Conditional login through identity provider
  docs/documentation/release_notes/topics/22_0_0.adoc
  docs/documentation/server_admin/topics/identity-broker/configuration.adoc
  js/apps/admin-ui/cypress/e2e/identity_providers_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts
  js/apps/admin-ui/public/locales/en/identity-providers-help.json
  js/apps/admin-ui/public/locales/en/identity-providers.json
  js/apps/admin-ui/src/identity-providers/add/AdvancedSettings.tsx
  server-spi/src/main/java/org/keycloak/models/IdentityProviderModel.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractInitializedBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#21325 Handle exceptions thrown when requesting `storage-access` permission
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step1.html
Labels: priority/critical, team/ui, flaky-test

#21257 scrapes pod container statuses when waiting for more to become available
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
Labels: team/cloud-native, flaky-test

#21278 Fix EAP adapter tests when running on Windows and JDK 17.
  testsuite/integration-arquillian/servers/app-server/jboss/pom.xml
Labels: team/cloud-native, team/store, team/core

#21333 Upgrade tested version of Postgresql to 15
  docs/guides/server/db.adoc
  pom.xml
Labels: team/cloud-native, team/store, flaky-test

#21353 Fixed minor accessibility violations for Users
  js/apps/account-ui/src/resources/ResourcesTab.tsx
  js/apps/admin-ui/src/authentication/components/DraggableTable.tsx
  js/apps/admin-ui/src/clients/authorization/AuthorizationEvaluateResource.tsx
  js/apps/admin-ui/src/clients/authorization/Policies.tsx
  js/apps/admin-ui/src/clients/authorization/evaluate/Results.tsx
  js/apps/admin-ui/src/clients/authorization/policy/ClientScope.tsx
  js/apps/admin-ui/src/clients/authorization/policy/Group.tsx
  js/apps/admin-ui/src/clients/authorization/policy/Role.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeValidations.tsx
  js/apps/admin-ui/src/user/UserConsents.tsx
  js/apps/admin-ui/src/user/UserCredentials.tsx
  js/apps/admin-ui/src/user/user-section.css
Labels: team/ui
