Repository keycloak/keycloak, pull requests merged in 2023-03, with the labels that each got.

#17205 Applying documentation style to the Operator Guide
  docs/guides/src/main/operator/advanced-configuration.adoc
  docs/guides/src/main/operator/basic-deployment.adoc
  docs/guides/src/main/operator/customizing-keycloak.adoc
  docs/guides/src/main/operator/installation.adoc
  docs/guides/src/main/operator/realm-import.adoc
Labels: area/docs, flaky-test

#16298 16188 added quotes to logging documentation to also work under Windows
  docs/guides/src/main/server/logging.adoc
Labels: area/docs

#17189 don't include service accounts in search results
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/BruteForceUsersResource.java
Labels: flaky-test

#17375 Remove now unused release script
  release.sh
Labels: area/ci, kind/task

#17340 Entity version is not updated when the entity is root entity
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/hibernate/listeners/JpaEntityVersionListener.java
Labels: status/ready, area/storage, team/store

#17419 Write AsciiDoc output as UTF-8 independent of system file encoding.
  docs/guides/src/main/server/reverseproxy.adoc
  docs/maven-plugin/pom.xml
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/FreeMarker.java
Labels: flaky-test

#16619 Add support for pessimistic locking to HotRod
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/HotRodMapStorage.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/HotRodMapStorageProviderFactory.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/SingleUseObjectHotRodMapStorage.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/connections/DefaultHotRodConnectionProviderFactory.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/locking/HotRodGlobalLockProvider.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/locking/HotRodLocksUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ComponentsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/concurrency/ConcurrentLoginTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/HotRodMapStorage.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionConcurrencyTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/transaction/StorageTransactionTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/util/TransactionController.java
Labels: area/storage, flaky-test

#16876 Update UA Parser to latest version
  pom.xml
  services/src/main/java/org/keycloak/device/DeviceRepresentationProviderFactoryImpl.java
Labels: flaky-test

#17533 Add job for Admin UI to JS workflow
  .github/workflows/js-ci.yml
Labels: area/ci, area/admin/ui, kind/task, team/ui

#17534 Add job for Account UI to JS workflow
  .github/workflows/js-ci.yml
Labels: area/ci, area/account/ui, kind/task, team/ui

#17535 Add job for Keycloak JS to JS workflow
  .github/workflows/js-ci.yml
Labels: area/ci, area/adapter/javascript, kind/task, team/ui

#17537 Add job for Keycloak Masthead to JS workflow
  .github/workflows/js-ci.yml
Labels: area/ci, kind/task, team/ui

#17512 changed id of dropdown
  js/apps/admin-ui/src/components/table-toolbar/KeycloakDataTable.tsx
  js/apps/admin-ui/src/components/table-toolbar/PaginatingTableToolbar.tsx
  js/apps/admin-ui/src/realm-settings/event-config/AddEventTypesDialog.tsx
  js/apps/admin-ui/src/realm-settings/event-config/EventsTypeTable.tsx
Labels: team/ui

#17538 Add job for UI Shared to JS workflow
  .github/workflows/js-ci.yml
Labels: area/ci, kind/task, team/ui

#17536 Fixed moderate issues for Home page
  js/apps/admin-ui/src/dashboard/Dashboard.tsx
Labels: team/ui

#17545 Applied darker grey colour to fix the insuffient colour contrast a11y…
  js/apps/admin-ui/src/user/user-section.css
Labels: team/ui

#17550 Fixed a11y serious issues for clients list
  js/apps/admin-ui/src/client-scopes/ChangeTypeDropdown.tsx
  js/apps/admin-ui/src/clients/ClientDetails.tsx
  js/apps/admin-ui/src/clients/authorization/AuthorizationEvaluate.tsx
  js/apps/admin-ui/src/clients/scopes/GeneratedCodeTab.tsx
Labels: team/ui

#17540 Fixed a11y accessibility header issue for clients/initial token
  js/apps/admin-ui/src/clients/initial-access/AccessTokenDialog.tsx
Labels: team/ui

#17564 changed to use on select
  js/apps/admin-ui/src/groups/GroupsSection.tsx
  js/apps/admin-ui/src/groups/components/GroupTree.tsx
  js/apps/admin-ui/src/groups/components/group-tree.css
Labels: team/ui

#17560 move empty state out of list
  js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx
Labels: team/ui

#17542 add unique title to pagination controls
  js/apps/admin-ui/src/components/table-toolbar/PaginatingTableToolbar.tsx
Labels: team/ui

#17213 Fix client (scope) model test placement
  testsuite/model/src/test/java/org/keycloak/testsuite/model/client/ClientModelTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/clientscope/ClientScopeModelTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/clientscope/ClientScopeStorageTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/user/UserModelTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/user/UserPaginationTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/user/UserSyncTest.java
Labels: flaky-test

#17552 Add Maven build for the Admin UI
  dependencies/admin-ui/pom.xml
  dependencies/pom.xml
  docs/maven-plugin/pom.xml
  js/apps/admin-ui/maven-resources/META-INF/keycloak-themes.json
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/theme.properties
  js/apps/admin-ui/pom.xml
  js/pom.xml
  pom.xml
  quarkus/runtime/pom.xml
  testsuite/integration-arquillian/pom.xml
  testsuite/utils/pom.xml
Labels: area/admin/ui, kind/task, team/ui

#17619 reverted not user realm roles are not paginated
  js/apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
Labels: team/ui

#16549 Remove `JsonbPostgreSQL95Dialect` from quarkus.
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java
Labels: status/hold, area/storage, team/store, flaky-test

#17490 Unexpected invalid_grant error on offline session refresh when client…
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/UserSessionAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/session/JpaUserSessionPersisterProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/session/PersistentClientSessionEntity.java
  model/legacy-private/src/main/java/org/keycloak/models/session/DisabledUserSessionPersisterProvider.java
  model/legacy-private/src/main/java/org/keycloak/models/session/UserSessionPersisterProvider.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderOfflineModelTest.java
Labels: area/storage, flaky-test

#17685 fixed reset of section fields
  js/apps/admin-ui/src/clients/AdvancedTab.tsx
Labels: team/ui

#19058 Exclude experimental configuration options for the guides
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Options.java
Labels: flaky-test

#19102 updated code example
  js/libs/keycloak-admin-client/README.md
Labels: team/ui

#19163 Run E2E tests for the Admin UI in parallel
  .github/workflows/js-ci.yml
Labels: area/ci, area/admin/ui, kind/task, team/ui

#17689 fixed size of dropdown
  js/apps/admin-ui/src/components/realm-selector/realm-selector.css
Labels: team/ui

#17511 made title clickable instead of card
  js/apps/admin-ui/src/components/keycloak-card/ClickableCard.tsx
  js/apps/admin-ui/src/components/keycloak-card/KeycloakCard.tsx
Labels: area/admin/ui, team/ui

#15929 Fix attribute deleted from LDAP is not immediately reflected even if it is "Always Read Value From LDAP"
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/UserAttributeLDAPStorageMapper.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/user/UserSyncTest.java
Labels: flaky-test

#19075 fixed pagination bug due to fixed entry
  js/apps/admin-ui/src/clients/scopes/ClientScopes.tsx
Labels: team/ui

#17244 made list pop out of dialog and added scrollbar
  themes/src/main/resources/theme/keycloak.v2/account/src/app/content/my-resources-page/PermissionSelect.tsx
Labels: area/account/ui, team/ui

#17687 removed use of inline components
  js/apps/admin-ui/src/clients/ClientsSection.tsx
  js/apps/admin-ui/src/clients/authorization/Permissions.tsx
  js/apps/admin-ui/src/clients/registration/ClientRegistrationList.tsx
  js/apps/admin-ui/src/components/role-mapping/RoleMapping.tsx
  js/apps/admin-ui/src/components/roles-list/RolesList.tsx
  js/apps/admin-ui/src/events/EventsSection.tsx
  js/apps/admin-ui/src/groups/GroupTable.tsx
  js/apps/admin-ui/src/groups/Members.tsx
  js/apps/admin-ui/src/identity-providers/add/DetailSettings.tsx
  js/apps/admin-ui/src/realm-settings/AddClientProfileModal.tsx
  js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperList.tsx
Labels: team/ui

#17510 also add error to details panel
  js/apps/admin-ui/src/events/EventsSection.tsx
Labels: area/admin/ui, team/ui

#19063 filter out disabled user storage providers
  js/apps/admin-ui/src/user/UsersSection.tsx
Labels: team/ui

#19195 added missing fields when jwks is off
  js/apps/admin-ui/public/resources/en/identity-providers-help.json
  js/apps/admin-ui/public/resources/en/identity-providers.json
  js/apps/admin-ui/src/identity-providers/add/DiscoverySettings.tsx
Labels: team/ui

#19061 added label for "Has access to"
  js/apps/account-ui/public/locales/en/translation.json
  js/apps/account-ui/src/applications/Applications.tsx
Labels: team/ui

#19215 Added missing aria-label
  js/apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
Labels: team/ui

#19210 added display name to resources and scope
  js/apps/admin-ui/src/clients/authorization/Resources.tsx
  js/apps/admin-ui/src/clients/authorization/Scopes.tsx
Labels: team/ui

#19086 Added cypress-axe and test checking for critical and serious a11y violations on page load
  js/apps/admin-ui/cypress/e2e/authentication_policies.spec.ts
  js/apps/admin-ui/cypress/e2e/authentication_policies_ciba.spec.ts
  js/apps/admin-ui/cypress/e2e/authentication_test.spec.ts
  js/apps/admin-ui/cypress/e2e/client_authorization_test.spec.ts
  js/apps/admin-ui/cypress/e2e/client_registration_policies.spec.ts
  js/apps/admin-ui/cypress/e2e/client_scopes_test.spec.ts
  js/apps/admin-ui/cypress/e2e/clients_saml_test.spec.ts
  js/apps/admin-ui/cypress/e2e/clients_test.spec.ts
  js/apps/admin-ui/cypress/e2e/events_test.spec.ts
  js/apps/admin-ui/cypress/e2e/group_test.spec.ts
  js/apps/admin-ui/cypress/e2e/identity_providers_test.spec.ts
  js/apps/admin-ui/cypress/e2e/masthead_test.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_roles_test.spec.ts
  js/apps/admin-ui/cypress/e2e/users_test.spec.ts
  js/apps/admin-ui/cypress/support/commands.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/ClientRolesTab.ts
  js/apps/admin-ui/cypress/tsconfig.json
  js/apps/admin-ui/package.json
  js/apps/admin-ui/src/user/UserForm.tsx
  js/package-lock.json
Labels: team/ui

#14283 iterate any attribute in multi-valued RDN to find the correct one
  core/src/test/java/org/keycloak/authentication/x509/CertificateIdentityExtractorTest.java
  core/src/test/resources/certs/ANS-cert.pem
  crypto/default/src/main/java/org/keycloak/crypto/def/BCUserIdentityExtractorProvider.java
  crypto/fips1402/src/main/java/org/keycloak/crypto/fips/BCFIPSUserIdentityExtractorProvider.java
Labels: flaky-test

#19245 Fixed serious a11y violation for client scopes list
  js/apps/admin-ui/src/client-scopes/client-scope.css
Labels: team/ui

#19274 Run Cypress tests only on the main repo
  .github/workflows/js-ci.yml
Labels: kind/bug, area/ci, area/admin/ui, team/ui

#19201 moved credentials reset button to always show
  js/apps/admin-ui/src/user/UserCredentials.tsx
Labels: team/ui

#19198 use signature providers instead of hardcoded index
  js/apps/admin-ui/src/realm-settings/TokensTab.tsx
Labels: team/ui

#19270 Return a user friendly message when a group name already exists on the same level
  services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java
Labels: flaky-test

#17669 count endpoint with search field has different behavior than users query endpoint
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UsersTest.java
Labels: status/ready, area/storage, team/store

#19361 Use new React Router API for the Admin UI
  js/apps/admin-ui/src/App.tsx
  js/apps/admin-ui/src/main.tsx
  js/apps/admin-ui/src/root/AuthWall.tsx
  js/apps/admin-ui/src/routes.tsx
Labels: area/admin/ui, kind/task, team/ui

#19199 Fix NoActionHotRodTransactionWrapper using default exists implementation
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/transaction/NoActionHotRodTransactionWrapper.java
Labels: area/storage, team/store

#17722 SOAP backchannel logout for SAML protocol - AdminUI field for logout URL
  js/apps/admin-ui/public/resources/en/clients-help.json
  js/apps/admin-ui/public/resources/en/clients.json
  js/apps/admin-ui/src/clients/advanced/FineGrainSamlEndpointConfig.tsx
Labels: team/ui

#19048 Admin UI: Credentials Reset dialog should only show activated required actions
  js/apps/admin-ui/public/resources/en/users.json
  js/apps/admin-ui/src/user/UserForm.tsx
  js/apps/admin-ui/src/user/user-credentials/RequiredActionMultiSelect.tsx
  js/apps/admin-ui/src/user/user-credentials/ResetCredentialDialog.tsx
Labels: team/ui

#19395 Fixed a11y violation for link style
  js/apps/admin-ui/src/realm-settings/DefaultGroupsTab.tsx
Labels: team/ui

#19098 Fix missing migration when reading TERMS_AND_CONDITIONS required acti…
  docs/documentation/upgrading/topics/keycloak/changes-21_0_2.adoc
  docs/documentation/upgrading/topics/keycloak/changes.adoc
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/CredentialsPage.ts
  js/apps/admin-ui/public/resources/en/users.json
  js/apps/admin-ui/src/clients/add/__tests__/mock-serverinfo.json
  js/apps/admin-ui/src/context/server-info/__tests__/mock.json
  js/libs/keycloak-admin-client/src/defs/requiredActionProviderRepresentation.ts
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate21_0_2_TermsAndConditionsRequiredAction.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-21.0.2.xml
  model/jpa/src/main/resources/META-INF/jpa-changelog-master.xml
  model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyExportImportManager.java
  services/src/main/java/org/keycloak/authentication/requiredactions/TermsAndConditions.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport198MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport255MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport343MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport483MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport903MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/MigrationTest.java
  themes/src/main/resources-community/theme/base/email/messages/messages_ar.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_da.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_fi.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_hu.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_pl.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_sk.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_tr.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ar.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_da.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fi.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_hu.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_lv.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_nl.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_pl.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_sk.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_tr.properties
  themes/src/main/resources/theme/base/email/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/ui, flaky-test

#19389 Remove legacy Promise APIs from Keycloak JS
  docs/documentation/release_notes/index.adoc
  docs/documentation/release_notes/topics/22_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc
  js/libs/keycloak-js/dist/keycloak.d.ts
  js/libs/keycloak-js/src/keycloak.js
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java
Labels: missing/docs, area/adapter/javascript, kind/eol, team/ui

#19429 Consistent handling of enums in the database schema
  model/jpa/src/main/resources/META-INF/jpa-changelog-22.0.0.xml
  model/jpa/src/main/resources/META-INF/jpa-changelog-master.xml
Labels: team/store, flaky-test

#19434 Fixed color contrast serious a11y violation
  js/apps/admin-ui/src/user/user-section.css
Labels: team/ui

#19432 Regressions in redirect URL verification when redirect_uri has encode…
  common/src/main/java/org/keycloak/common/util/KeycloakUriBuilder.java
  common/src/test/java/org/keycloak/common/util/KeycloakUriBuilderTest.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/RedirectUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthRedirectUriTest.java
Labels: team/cloud-native, team/store, team/core

#19446 Fixed moderate a11y violation for client scopes/scope tab
  js/apps/admin-ui/src/client-scopes/EditClientScope.tsx
Labels: team/ui

#19448 Fixed moderate a11y violations for Authentication
  js/apps/admin-ui/src/authentication/EmptyExecutionState.tsx
Labels: team/ui

#19441 Remove Cypress component tests
  .github/workflows/js-ci.yml
  js/apps/admin-ui/cypress.config.mjs
  js/apps/admin-ui/cypress/component/ConfirmDialogModal.cy.tsx
  js/apps/admin-ui/cypress/component/KeyValueInput.cy.tsx
  js/apps/admin-ui/cypress/component/MultiLineInput.cy.tsx
  js/apps/admin-ui/cypress/fixtures/example.json
  js/apps/admin-ui/cypress/support/component-index.html
  js/apps/admin-ui/cypress/support/component.ts
  js/apps/admin-ui/package.json
Labels: area/ci, area/admin/ui, kind/task, team/ui

#19459 Do not verify identity cookie when processing required actions
  services/src/main/java/org/keycloak/protocol/AuthorizationEndpointBase.java
  services/src/main/java/org/keycloak/services/resources/SessionCodeChecks.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#19471 Removing custom classloader and allow loading drivers at runtime
  docs/guides/server/db.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/DatabaseOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakClassLoader.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/OptionValidationTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.unix.approved.txt
Labels: team/cloud-native

#19449 Fixes access for credentials tab.
  js/apps/admin-ui/src/clients/ClientDetails.tsx
  js/apps/admin-ui/src/clients/credentials/ClientSecret.tsx
  js/apps/admin-ui/src/clients/credentials/Credentials.tsx
Labels: team/ui

#19423 Add access object to full group tree. Fix access for members tab.
  js/apps/admin-ui/public/resources/en/groups.json
  js/apps/admin-ui/src/groups/GroupTable.tsx
  js/apps/admin-ui/src/groups/GroupsSection.tsx
  js/apps/admin-ui/src/groups/components/GroupTree.tsx
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/GroupsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/GroupPermissionEvaluator.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/GroupPermissions.java
Labels: team/ui
