Repository keycloak/keycloak, pull requests merged in 2023-07, with the labels that each got.

#21013 TestLdapConnectionResource: give usefull feedback in UI on what faile…
  federation/ldap/src/main/java/org/keycloak/services/managers/LDAPServerCapabilitiesManager.java
  federation/ldap/src/main/java/org/keycloak/services/resources/admin/TestLdapConnectionResource.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPContextManager.java
  js/apps/admin-ui/cypress/e2e/user_fed_ldap_test.spec.ts
  js/apps/admin-ui/public/locales/en/user-federation.json
  model/legacy-services/src/main/java/org/keycloak/services/resources/admin/UserStorageProviderResource.java
Labels: team/store, team/ui, flaky-test

#21291 adds port names to the pod / service
  operator/src/main/java/org/keycloak/operator/Constants.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngress.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakService.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakServicesTest.java
Labels: team/cloud-native, flaky-test

#21331 Allow Client->ClientScopes tab w/ view-clients
  js/apps/admin-ui/src/clients/ClientDetails.tsx
  js/apps/admin-ui/src/clients/scopes/ClientScopes.tsx
  js/apps/admin-ui/src/clients/scopes/EvaluateScopes.tsx
Labels: team/ui

#21361 unregister fields on mapper type switch
  js/apps/admin-ui/src/identity-providers/add/AddMapper.tsx
Labels: team/ui

#20722 Throw an exeption when `init()` is called more than once
  js/libs/keycloak-js/src/keycloak.js
Labels: team/ui

#21372 Add missing Arabic messages
  js/apps/account-ui/public/locales/ar/translation.json
  themes/src/main/resources-community/theme/base/account/messages/messages_ar.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ar.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_ar.properties
Labels: team/ui, flaky-test

#21340 Enable IPv6 dualstack support by default
  docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc
  docs/guides/server/configuration-production.adoc
  quarkus/dist/src/main/content/bin/kc.bat
  quarkus/dist/src/main/content/bin/kc.sh
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/IpStackDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JavaOptsScriptTest.java
Labels: team/cloud-native, flaky-test

#21408 Properly handle execeptions thrown by Promises in the `usePromise()` hook
  js/apps/account-ui/src/utils/usePromise.ts
Labels: kind/bug, area/account/ui, team/ui

#21323 Remove support for OpenJDK 11 on the server side
  .github/workflows/ci.yml
  crypto/fips1402/pom.xml
  distribution/api-docs-dist/pom.xml
  docs/documentation/release_notes/topics/22_0_0.adoc
  docs/maven-plugin/pom.xml
  federation/ldap/pom.xml
  federation/sssd/pom.xml
  pom.xml
  quarkus/pom.xml
  server-spi/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#21413 JavascriptAdapterTest is broken due to the multiple initialization of JS adapter
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21266 Fix updating locale on info/error page after authenticationSession wa…
  server-spi-private/src/main/java/org/keycloak/forms/login/LoginFormsProvider.java
  server-spi-private/src/main/java/org/keycloak/forms/login/MessageType.java
  services/src/main/java/org/keycloak/forms/login/freemarker/DetachedInfoStateChecker.java
  services/src/main/java/org/keycloak/forms/login/freemarker/DetachedInfoStateCookie.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/forms/login/freemarker/model/UrlBean.java
  services/src/main/java/org/keycloak/locale/DefaultLocaleSelectorProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/LogoutUtil.java
  services/src/main/java/org/keycloak/services/Urls.java
  services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationSessionManager.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  services/src/main/java/org/keycloak/services/resources/SessionCodeChecks.java
  services/src/main/java/org/keycloak/services/util/LocaleUtil.java
  services/src/main/java/org/keycloak/theme/beans/MessageBean.java
  services/src/main/java/org/keycloak/theme/beans/MessageType.java
  services/src/main/java/org/keycloak/theme/beans/MessagesPerFieldBean.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/ErrorPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/EmailTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/LoginPageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RPInitiatedLogoutTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20028 Fix connection-pool-size 0 being ignored and being unable to disable the connection pool
  adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/HttpClientBuilder.java
  adapters/saml/core/src/main/java/org/keycloak/adapters/cloned/HttpClientBuilder.java
Labels: flaky-test

#21065 Allow any JGroups stack with --cache-stack
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
Labels: team/cloud-native, team/store, flaky-test

#21355 Support for JWE IDToken and UserInfo tokens in OIDC brokers
  docs/documentation/release_notes/topics/22_0_0.adoc
  docs/documentation/server_admin/topics/identity-broker/oidc.adoc
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerJWETest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerJWEUserInfoJustEncryptedTest.java
  testsuite/integration-arquillian/tests/base/testsuites/fips-suite
Labels: team/cloud-native, team/store, team/core, flaky-test

#21316 Align naming of OTP policy window setting with actual semantics (#20469)
  docs/documentation/server_admin/topics/authentication/otp-policies.adoc
  js/apps/admin-ui/public/locales/en/authentication-help.json
  js/apps/admin-ui/public/locales/en/authentication.json
  js/apps/admin-ui/public/locales/ja/authentication.json
  js/apps/admin-ui/public/locales/lt/authentication.json
  js/apps/admin-ui/public/locales/no/authentication.json
  js/apps/admin-ui/public/locales/pt-BR/authentication.json
  js/apps/admin-ui/public/locales/ru/authentication.json
  js/apps/admin-ui/public/locales/zh-CN/authentication-help.json
  js/apps/admin-ui/public/locales/zh-CN/authentication.json
  js/apps/admin-ui/src/authentication/policies/OtpPolicy.tsx
  server-spi-private/src/main/java/org/keycloak/models/utils/TimeBasedOTP.java
  server-spi/src/main/java/org/keycloak/models/utils/HmacOTP.java
Labels: team/ui, flaky-test

#21416 Fix flaky OfflineServletsAdapterTest test
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/OfflineServletsAdapterTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21387 Added missing translation in polish for login title
  themes/src/main/resources-community/theme/base/login/messages/messages_pl.properties
Labels: kind/enhancement, area/translations, area/login/ui

#21178 NPE in getDefaultRequiredActionCaseInsensitively
  server-spi-private/src/main/java/org/keycloak/models/utils/DefaultRequiredActions.java
Labels: flaky-test

#21330 NullPointerException on reading auth.attemptedUsername in terms template
  services/src/main/java/org/keycloak/forms/login/freemarker/model/AuthenticationContextBean.java
Labels: flaky-test

#20976 Support ignoring artigacts when running re-augmentation
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/EventListenerIntegrator.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorageProviderFactory.java
  quarkus/config-api/src/main/java/org/keycloak/config/ClassLoaderOptions.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Build.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ClassLoaderPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaMapStorageProviderFactory.java
Labels: status/hold, team/cloud-native, team/store, flaky-test

#21454 Use same Java version when starting Keycloak for Cypress tests
  .github/workflows/js-ci.yml
Labels: priority/critical, team/ui

#21466 Fix deleteSession
  js/apps/account-ui/src/api/methods.ts
Labels: team/ui

#21296 UserSessionProviderModelTest#testRemoteCachesParallel sessions are no…
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderModelTest.java
Labels: team/store

#21492 Wrong message for sync actions on LDAP role mapper
  js/apps/admin-ui/public/locales/en/user-federation.json
  js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx
Labels: team/ui

#21457 Fix property name changed in Quarkus 3.2
  quarkus/runtime/src/main/resources/application.properties
Labels: team/cloud-native

#16462 make cli usable on OpenBSD
  integration/client-cli/admin-cli/src/main/bin/kcadm.sh
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/util/OsUtil.java
  integration/client-cli/client-registration-cli/src/main/bin/kcreg.sh
  integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/util/OsUtil.java
  quarkus/dist/src/main/content/bin/kc.sh
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/cli/OsUtils.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21388 Fix for Email settings erased after any change on realm settings
  js/apps/admin-ui/src/realm-settings/EmailTab.tsx
  js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
Labels: team/ui

#21501 Update Arabic translation.json
  js/apps/account-ui/public/locales/ar/translation.json
Labels: kind/enhancement, area/translations, team/ui

#21357 Updating performance information on export/import
  1.txt
  2.txt
  docs/documentation/server_admin/topics/export-import.adoc
  docs/guides/server/importExport.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/ExportOptions.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
Labels: team/cloud-native, flaky-test

#16866 Bump Freemarker to Version 2.3.32.
  pom.xml
Labels: team/ui, flaky-test

#21334 initial test for resources tab
  js/apps/account-ui/package.json
  js/apps/account-ui/playwright.config.ts
  js/apps/account-ui/src/environment.ts
  js/apps/account-ui/src/resources/ResourcesTab.tsx
  js/apps/account-ui/test/admin-client.ts
  js/apps/account-ui/test/auth.setup.ts
  js/apps/account-ui/test/import.setup.ts
  js/apps/account-ui/test/import.teardown.ts
  js/apps/account-ui/test/login.ts
  js/apps/account-ui/test/my-resources.spec.ts
  js/apps/account-ui/test/personal-info.spec.ts
  js/apps/account-ui/test/test-realm.json
  js/libs/keycloak-masthead/src/KeycloakDropdown.tsx
  js/libs/keycloak-masthead/src/Masthead.tsx
  js/pnpm-lock.yaml
Labels: team/ui

#21517 Using "Account is disabled" message (and also added new test case)
  services/src/main/java/org/keycloak/services/resources/LoginActionsServiceChecks.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21455 CVE-2023-21971 - Update Connector/J to 8.0.33
  pom.xml
Labels: team/store, flaky-test

#21478 convert form will flatten the value
  js/apps/admin-ui/src/user-federation/shared/Header.tsx
Labels: team/ui

#21289 fix: closes #21095
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/GroupsResource.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
  services/src/main/java/org/keycloak/utils/GroupUtils.java
Labels: team/ui, flaky-test

#21160 Find an appropriate key based on the given KID and JWA
  core/src/main/java/org/keycloak/crypto/KeyWrapper.java
  core/src/main/java/org/keycloak/crypto/PublicKeysWrapper.java
  js/apps/admin-ui/public/locales/en/clients.json
  model/infinispan/src/main/java/org/keycloak/keys/infinispan/InfinispanPublicKeyStorageProvider.java
  services/src/main/java/org/keycloak/keys/loader/ClientPublicKeyLoader.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
Labels: missing/tests, team/cloud-native, team/store, team/core, team/ui, flaky-test

#21551 Remove unnecessary tests
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UmaRepresentationTest.java
Labels: team/cloud-native, team/store, team/core

#21544 Align guava dependency with the Quarkus Platform BOM
  pom.xml
  services/src/main/java/org/keycloak/vault/FilesKeystoreVaultProvider.java
  services/src/main/java/org/keycloak/vault/FilesPlainTextVaultProvider.java
Labels: flaky-test

#21546 Remove unused resources from 'common' theme
  .github/dependabot.yml
  examples/themes/src/main/resources/theme/logo-example/admin/theme.properties
  themes/src/main/resources/theme/keycloak/common/resources/lib/angular/errors.json
  themes/src/main/resources/theme/keycloak/common/resources/lib/angular/treeview/LICENSE
  themes/src/main/resources/theme/keycloak/common/resources/lib/angular/treeview/README.md
  themes/src/main/resources/theme/keycloak/common/resources/lib/angular/treeview/angular.treeview.js
  themes/src/main/resources/theme/keycloak/common/resources/lib/angular/treeview/angular.treeview.min.js
  themes/src/main/resources/theme/keycloak/common/resources/lib/angular/treeview/css/angular.treeview.css
  themes/src/main/resources/theme/keycloak/common/resources/lib/angular/treeview/img/file.png
  themes/src/main/resources/theme/keycloak/common/resources/lib/angular/treeview/img/folder-closed.png
  themes/src/main/resources/theme/keycloak/common/resources/lib/angular/treeview/img/folder.png
  themes/src/main/resources/theme/keycloak/common/resources/lib/angular/ui-bootstrap-tpls-0.11.0.js
  themes/src/main/resources/theme/keycloak/common/resources/lib/angular/version.json
  themes/src/main/resources/theme/keycloak/common/resources/lib/filesaver/FileSaver.js
  themes/src/main/resources/theme/keycloak/common/resources/lib/fileupload/FileAPI.min.js
  themes/src/main/resources/theme/keycloak/common/resources/lib/fileupload/angular-file-upload-html5-shim.js
  themes/src/main/resources/theme/keycloak/common/resources/lib/fileupload/angular-file-upload-html5-shim.min.js
  themes/src/main/resources/theme/keycloak/common/resources/lib/fileupload/angular-file-upload-shim.js
  themes/src/main/resources/theme/keycloak/common/resources/lib/fileupload/angular-file-upload-shim.min.js
  themes/src/main/resources/theme/keycloak/common/resources/lib/fileupload/angular-file-upload.js
  themes/src/main/resources/theme/keycloak/common/resources/lib/fileupload/angular-file-upload.min.js
  themes/src/main/resources/theme/keycloak/common/resources/lib/pficon/pficon.css
  themes/src/main/resources/theme/keycloak/common/resources/lib/pficon/pficon.woff
Labels: team/ui, flaky-test

#21512 Align database versions in Quarkus integration tests with the root pom
  quarkus/tests/integration/pom.xml
  quarkus/tests/integration/src/test/resources/container-license-acceptance.txt
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/DatabaseContainer.java
Labels: team/cloud-native, flaky-test

#21511 Enable publishNotReadyAddresses for discovery service
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDiscoveryService.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakServicesTest.java
Labels: team/cloud-native

#21118 Improve error management in the github provider
  services/src/main/java/org/keycloak/social/github/GitHubIdentityProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21568 CVE-2022-45868 H2 Cleartext Storage of Sensitive Information
  pom.xml
Labels: team/store, flaky-test

#21561 Remove user credentials from admin event representation
  services/src/main/java/org/keycloak/services/resources/admin/AdminEventBuilder.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/event/AdminEventTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21577 Update javadoc for user search in UserResource
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
Labels: flaky-test

#21518 Additional test for logout when using multiple tabs
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultipleTabsLoginTest.java
Labels: team/cloud-native, team/store, team/core

#21587 Only run the pre-commit hooks when Husky is installed
  js/.husky/pre-commit
Labels: team/ui

#21475 use group instead of name
  js/apps/admin-ui/src/groups/GroupTable.tsx
  js/apps/admin-ui/src/groups/GroupsModal.tsx
  js/apps/admin-ui/src/groups/GroupsSection.tsx
  js/apps/admin-ui/src/groups/components/GroupTree.tsx
Labels: team/ui

#21292 UserSessionConcurrencyTest#testConcurrentNotesChange fails intermitte…
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionConcurrencyTest.java
Labels: team/store, flaky-test

#21177 Updating securing apps and authorization documentation based on the adapter deprecation/removal plan
  docs/documentation/authorization_services/topics.adoc
  docs/documentation/authorization_services/topics/authorization-quickstarts.adoc
  docs/documentation/authorization_services/topics/enforcer-authorization-context.adoc
  docs/documentation/authorization_services/topics/enforcer-claim-information-point.adoc
  docs/documentation/authorization_services/topics/enforcer-configuration.adoc
  docs/documentation/authorization_services/topics/enforcer-https.adoc
  docs/documentation/authorization_services/topics/enforcer-js-adapter.adoc
  docs/documentation/authorization_services/topics/enforcer-overview.adoc
  docs/documentation/authorization_services/topics/getting-started-overview.adoc
  docs/documentation/authorization_services/topics/hello-world-before-start.adoc
  docs/documentation/authorization_services/topics/hello-world-create-realm.adoc
  docs/documentation/authorization_services/topics/hello-world-create-resource-server.adoc
  docs/documentation/authorization_services/topics/hello-world-deploy.adoc
  docs/documentation/authorization_services/topics/hello-world-overview.adoc
  docs/documentation/securing_apps/topics.adoc
  docs/documentation/securing_apps/topics/oidc/available-endpoints.adoc
  docs/documentation/securing_apps/topics/oidc/java/adapter-deprecation-notice.adoc
  docs/documentation/securing_apps/topics/oidc/java/jaas.adoc
  docs/documentation/securing_apps/topics/oidc/java/java-adapter-config.adoc
  docs/documentation/securing_apps/topics/oidc/java/java-adapters.adoc
  docs/documentation/securing_apps/topics/oidc/java/jboss-adapter-rpms.adoc
  docs/documentation/securing_apps/topics/oidc/java/jboss-adapter.adoc
  docs/documentation/securing_apps/topics/oidc/java/jetty9-adapter.adoc
  docs/documentation/securing_apps/topics/oidc/java/servlet-filter-adapter.adoc
  docs/documentation/securing_apps/topics/oidc/java/spring-boot-adapter.adoc
  docs/documentation/securing_apps/topics/oidc/java/spring-security-adapter.adoc
  docs/documentation/securing_apps/topics/oidc/java/tomcat-adapter.adoc
  docs/documentation/securing_apps/topics/oidc/javascript-adapter.adoc
  docs/documentation/securing_apps/topics/oidc/nodejs-adapter.adoc
  docs/documentation/securing_apps/topics/oidc/oidc-generic.adoc
  docs/documentation/securing_apps/topics/oidc/oidc-overview.adoc
  docs/documentation/securing_apps/topics/oidc/recommendations.adoc
  docs/documentation/securing_apps/topics/oidc/supported-grant-types.adoc
  docs/documentation/securing_apps/topics/overview/basic-steps.adoc
  docs/documentation/securing_apps/topics/overview/getting-started.adoc
  docs/documentation/securing_apps/topics/overview/overview.adoc
  docs/documentation/securing_apps/topics/overview/supported-platforms.adoc
  docs/documentation/securing_apps/topics/overview/supported-protocols.adoc
  docs/documentation/securing_apps/topics/overview/what-are-client-adapters.adoc
  docs/documentation/securing_apps/topics/saml/java/java-adapters.adoc
  docs/documentation/securing_apps/topics/saml/java/multi-tenancy.adoc
  docs/documentation/server_development/topics/user-storage/javaee.adoc
  docs/documentation/topics/templates/document-attributes.adoc
Labels: flaky-test

#21310 Fixed a11y violations for clients
  js/apps/admin-ui/src/clients/authorization/PermissionDetails.tsx
  js/apps/admin-ui/src/clients/authorization/Permissions.tsx
  js/apps/admin-ui/src/clients/authorization/Resources.tsx
  js/apps/admin-ui/src/clients/authorization/Scopes.tsx
Labels: team/ui

#21590 Allow setting context-path for KeycloakServer
  testsuite/utils/src/main/java/org/keycloak/testsuite/KeycloakServer.java
Labels: team/cloud-native, team/store, team/core

#21602 Upgrade TypeScript ESLint dependencies to latest version
  js/package.json
  js/pnpm-lock.yaml
Labels: dependencies, team/ui

#21288 Upgrade React Router dependencies to latest version
  js/apps/account-ui/package.json
  js/apps/admin-ui/package.json
  js/apps/admin-ui/src/root/AuthWall.tsx
  js/apps/admin-ui/src/routes.tsx
  js/pnpm-lock.yaml
Labels: area/account/ui, area/admin/ui, area/dependencies, team/ui

#21608 `keycloakCRName` and `realm` are no longer marked as required in KeycloakRealmImport CRD
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/realmimport/KeycloakRealmImportSpec.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/CRDTest.java
Labels: team/cloud-native

#21676 Various fixes for localization of the Account Console
  js/apps/account-ui/public/locales/ar/translation.json
  js/apps/account-ui/public/locales/en/translation.json
  js/apps/account-ui/public/locales/fa/translation.json
  js/apps/account-ui/src/account-security/AccountRow.tsx
  js/apps/account-ui/src/account-security/DeviceActivity.tsx
  js/apps/account-ui/src/account-security/LinkedAccounts.tsx
  js/apps/account-ui/src/applications/Applications.tsx
  js/apps/account-ui/src/groups/Groups.tsx
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
  js/apps/account-ui/src/resources/PermissionRequest.tsx
Labels: kind/task, team/ui

#21354 Update password-policies.adoc
  docs/documentation/server_admin/topics/authentication/password-policies.adoc
  js/apps/admin-ui/public/locales/en/authentication-help.json
Labels: area/docs, team/core, team/ui

#21702 Check whether realm has store enabled for immediately sent events
  server-spi-private/src/main/java/org/keycloak/events/EventBuilder.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/event/LoginEventsTest.java
Labels: team/cloud-native, team/store, team/core

#21522 Prevent cache stampede on realms
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheManager.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
Labels: team/store, flaky-test

#21711 Switches the merging logic to using the override as the basis
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDistConfigurator.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/RealmImportTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
Labels: team/cloud-native, flaky-test

#21162 Removes the watched secret store by directly using the statefulsets
  operator/src/main/java/org/keycloak/operator/Constants.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/main/java/org/keycloak/operator/controllers/OperatorManagedResource.java
  operator/src/main/java/org/keycloak/operator/controllers/WatchedSecrets.java
  operator/src/main/java/org/keycloak/operator/controllers/WatchedSecretsController.java
  operator/src/main/java/org/keycloak/operator/controllers/WatchedSecretsStore.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/ClusteringTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/WatchedSecretsControllerTest.java
Labels: status/hold, team/cloud-native, flaky-test

#21634 `keycloakCRName` and `realm` are no longer marked as required in KeycloakRealmImport CRD
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/realmimport/KeycloakRealmImportSpec.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/CRDTest.java
Labels: team/cloud-native, flaky-test

#21712 Update messages_ar.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ar.properties
Labels: flaky-test

#21646 Revert emailVerified to false if email modified on force-sync non-trusted broker
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21653 Revert emailVerified to false if email modified on force-sync non-trusted broker
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21411 Improvements for policy creation at permissions screen
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/tabs/authorization_subtabs/PermissionsTab.ts
  js/apps/admin-ui/public/locales/en/clients.json
  js/apps/admin-ui/src/clients/authorization/ResourcesPolicySelect.tsx
Labels: team/ui

#21735 Various fixes for localization of the Account Console
  js/apps/account-ui/public/locales/ar/translation.json
  js/apps/account-ui/public/locales/en/translation.json
  js/apps/account-ui/public/locales/fa/translation.json
  js/apps/account-ui/src/account-security/AccountRow.tsx
  js/apps/account-ui/src/account-security/DeviceActivity.tsx
  js/apps/account-ui/src/account-security/LinkedAccounts.tsx
  js/apps/account-ui/src/applications/Applications.tsx
  js/apps/account-ui/src/groups/Groups.tsx
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
  js/apps/account-ui/src/resources/PermissionRequest.tsx
Labels: team/ui

#21736 Fixed a11y violations for clients
  js/apps/admin-ui/src/clients/authorization/PermissionDetails.tsx
  js/apps/admin-ui/src/clients/authorization/Permissions.tsx
  js/apps/admin-ui/src/clients/authorization/Resources.tsx
  js/apps/admin-ui/src/clients/authorization/Scopes.tsx
Labels: team/ui

#21662 Re-augmentation failing on windows
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Build.java
  quarkus/runtime/src/main/resources/application.properties
Labels: team/cloud-native, flaky-test

#21742 Fix JSON syntax of translation files (#21734)
  js/apps/admin-ui/public/locales/zh-CN/authentication.json
  js/apps/admin-ui/public/locales/zh-CN/identity-providers.json
  js/apps/admin-ui/public/locales/zh-CN/user-federation-help.json
Labels: team/ui

#21740 Check whether realm has store enabled for immediately sent events
  server-spi-private/src/main/java/org/keycloak/events/EventBuilder.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/event/LoginEventsTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21738 Fall back to `IdentityProvider` component type if present
  js/apps/admin-ui/src/identity-providers/add/AddIdentityProvider.tsx
Labels: team/ui

#21750 Keycloak forgets ui_locales parameter when using reset password
  services/src/main/java/org/keycloak/locale/DefaultLocaleSelectorProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/EmailTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21576 only use the names of the realms
  js/apps/admin-ui/cypress/e2e/realm_test.spec.ts
  js/apps/admin-ui/src/components/realm-selector/RealmSelector.tsx
  js/apps/admin-ui/src/context/RealmsContext.tsx
  js/apps/admin-ui/src/context/RecentRealms.tsx
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AdminExtResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/RealmResource.java
Labels: team/ui, flaky-test

#21588 made added groups browsable
  js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx
  js/apps/admin-ui/src/user/user-section.css
Labels: team/ui

#21579 fix for validators that don't have config
  js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
Labels: team/ui

#21684 SessionTimeoutsTest flaky test fix
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionListener.java
Labels: team/store, flaky-test

#21682 Add Dutch locale to the Account Console
  js/apps/account-ui/public/locales/nl/translation.json
Labels: status/hold, team/ui

#21675 Add Java Distribution IT for Windows
  .github/actions/integration-test-setup/action.yml
  .github/workflows/ci.yml
  testsuite/integration-arquillian/servers/auth-server/quarkus/assembly.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#21180 render components based on the annotations
  js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
  js/apps/admin-ui/src/user/UserProfileFields.tsx
  js/apps/admin-ui/src/user/components/OptionsComponent.tsx
  js/apps/admin-ui/src/user/components/SelectComponent.tsx
  js/apps/admin-ui/src/user/components/TextAreaComponent.tsx
  js/apps/admin-ui/src/user/components/TextComponent.tsx
  js/apps/admin-ui/src/user/components/UserProfileGroup.tsx
  js/apps/admin-ui/src/user/utils.ts
  js/libs/keycloak-admin-client/src/defs/userProfileConfig.ts
Labels: team/ui

#21788 switches the workaround to JsonNode, which produces a cleaner crd
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/StatusCondition.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/CRDTest.java
Labels: team/cloud-native, flaky-test

#21789 Ensure that the flow tested to be deleted is a built in flow
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/FlowTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21703 Simplify date formatting for the Account Console (v3)
  js/apps/account-ui/src/account-security/DeviceActivity.tsx
  js/apps/account-ui/src/account-security/SigningIn.tsx
  js/apps/account-ui/src/applications/Applications.tsx
  js/apps/account-ui/src/components/format/format-date.ts
  js/apps/account-ui/src/components/formatter/format-date.ts
  js/apps/account-ui/src/utils/formatDate.ts
Labels: team/ui

#21807 Add missing labels for Account Console (v3)
  js/apps/account-ui/public/locales/ar/translation.json
  js/apps/account-ui/public/locales/en/translation.json
  js/apps/account-ui/public/locales/fa/translation.json
  js/apps/account-ui/public/locales/nl/translation.json
  js/apps/account-ui/src/account-security/DeviceActivity.tsx
  js/apps/account-ui/src/account-security/SigningIn.tsx
  js/apps/account-ui/src/applications/Applications.tsx
  js/apps/account-ui/src/resources/ResourcesTab.tsx
  js/libs/ui-shared/src/continue-cancel/ContinueCancelModal.tsx
Labels: team/ui

#21806 [20455] Arquillian reflection bug -> using different setter to avoid overloading.
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#21808 use multi select if value is an array
  js/apps/admin-ui/src/user/UserProfileFields.tsx
  js/apps/admin-ui/src/user/components/SelectComponent.tsx
Labels: team/ui

#21813 Update account-ui/ar/translation.json
  js/apps/account-ui/public/locales/ar/translation.json
Labels: team/ui

#21828 Disable ZeroDowntimeTest
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/zerodowntime/ZeroDowntimeTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21831 Add "created at" column to user credentials table in admin ui
  js/apps/admin-ui/src/user/UserCredentials.tsx
  js/apps/admin-ui/src/user/user-credentials/CredentialRow.tsx
Labels: status/hold, team/ui

#21829 switches the workaround to JsonNode, which produces a cleaner crd
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/StatusCondition.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/CRDTest.java
Labels: team/cloud-native

#21832 Adds a pod list rbac
  operator/src/main/kubernetes/kubernetes.yml
Labels: team/cloud-native, flaky-test

#21543 Update bcpkix and bcprov dependencies
  adapters/oidc/adapter-core/pom.xml
  adapters/oidc/installed/pom.xml
  adapters/oidc/jakarta-servlet-filter/pom.xml
  adapters/oidc/jetty/jetty-core/pom.xml
  adapters/oidc/jetty/jetty9.4/pom.xml
  adapters/oidc/servlet-filter/pom.xml
  adapters/oidc/spring-security/pom.xml
  adapters/oidc/tomcat/tomcat-core/pom.xml
  adapters/oidc/tomcat/tomcat/pom.xml
  adapters/oidc/undertow/pom.xml
  adapters/oidc/wildfly-elytron/pom.xml
  adapters/saml/jakarta-servlet-filter/pom.xml
  adapters/saml/jetty/jetty-core/pom.xml
  adapters/saml/jetty/jetty9.4/pom.xml
  adapters/saml/servlet-filter/pom.xml
  adapters/saml/tomcat/tomcat-core/pom.xml
  adapters/saml/tomcat/tomcat/pom.xml
  adapters/spi/adapter-spi/pom.xml
  adapters/spi/jboss-adapter-core/pom.xml
  crypto/default/pom.xml
  dependencies/server-min/pom.xml
  distribution/feature-packs/adapter-feature-pack/pom.xml
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/util/ClassLoaderUtil.java
  integration/client-cli/client-cli-dist/assembly.xml
  integration/client-cli/client-cli-dist/pom.xml
  integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/util/ClassLoaderUtil.java
  operator/pom.xml
  pom.xml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ClassLoaderPropertyMappers.java
  quarkus/tests/junit5/src/main/java/org/keycloak/Keycloak.java
  testsuite/integration-arquillian/servers/adapter-spi/undertow-adapter-jakarta/pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/integration-arquillian/tests/pom.xml
  testsuite/utils/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#21844 Automatically import dev client when starting Keycloak server
  js/apps/keycloak-server/README.md
  js/apps/keycloak-server/package.json
  js/apps/keycloak-server/scripts/import-client.mjs
  js/apps/keycloak-server/scripts/start-server.js
  js/apps/keycloak-server/scripts/start-server.mjs
Labels: team/ui

#21841 Introduce re-try mechanism when deserializing during import for map store
  model/map/src/main/java/org/keycloak/models/map/datastore/MapExportImportManager.java
Labels: team/store, flaky-test

#21850 Adds a pod list rbac
  operator/src/main/kubernetes/kubernetes.yml
Labels: team/cloud-native

#21565 Upgrade Infinispan to 14.0.13.Final
  pom.xml
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/DatabaseContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/InfinispanContainer.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21776 fixes the details page
  js/apps/admin-ui/src/identity-providers/add/DetailSettings.tsx
Labels: team/ui

#21347 KEYCLOAK-20343 Add message bundle to export/import
  core/src/main/java/org/keycloak/representations/idm/RealmRepresentation.java
  model/legacy-private/src/main/java/org/keycloak/exportimport/util/ExportUtils.java
  model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyExportImportManager.java
  model/map/src/main/java/org/keycloak/models/map/datastore/MapExportImportManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportUtil.java
  testsuite/integration-arquillian/tests/base/src/test/resources/model/testrealm.json
Labels: team/cloud-native, team/store, team/core, flaky-test

#21752 Fix String comparison
  adapters/oidc/tomcat/tomcat-core/src/main/java/org/keycloak/adapters/tomcat/AbstractKeycloakAuthenticatorValve.java
  core/src/main/java/org/keycloak/representations/docker/DockerError.java
  model/jpa/src/main/java/org/keycloak/storage/jpa/entity/FederatedUserRequiredActionEntity.java
  services/src/main/java/org/keycloak/authentication/authenticators/x509/CertificateValidator.java
Labels: team/store, flaky-test

#21790 removes the filtering of erroneous enum values
  operator/pom.xml
Labels: team/cloud-native, flaky-test

#21774 Check RDN attribute for DN membership
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/MembershipType.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperSyncTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21847 Remove scheduled from individual workflows
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/documentation.yml
  .github/workflows/guides.yml
  .github/workflows/js-ci.yml
  .github/workflows/operator-ci.yml
  .github/workflows/schedule-nightly.yml
  .github/workflows/schedule.yml
  .github/workflows/trivy-analysis.yml
Labels: flaky-test

#21849 Improve 'oauthGrantTitle' French translation
  themes/src/main/resources-community/theme/base/login/messages/messages_fr.properties
Labels: flaky-test

#21869 Warnings about TLS properties on startup
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java
Labels: team/cloud-native

#21870 Warnings about TLS properties on startup
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java
Labels: team/cloud-native, flaky-test

#21883 Check RDN attribute for DN membership
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/MembershipType.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperSyncTest.java
Labels: team/cloud-native, team/store, team/core

#21872 Removing workaround for state transfer never completes
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/Infinispan.java
Labels: area/storage, area/infinispan, team/store, flaky-test

#21865 Use `--verbose` by default in Operator deployments
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJob.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
Labels: team/cloud-native, flaky-test

#21879 updating the location of the Dockerfile
  operator/README.md
Labels: team/cloud-native

#20621 FAPI 2.0 security profile - supporting RFC 9207 OAuth 2.0 Authorization Server Issuer Identification
  adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/OAuthRequestAuthenticator.java
  adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/ServerRequest.java
  core/src/main/java/org/keycloak/OAuth2Constants.java
  core/src/main/java/org/keycloak/protocol/oidc/representations/OIDCConfigurationRepresentation.java
  docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes.adoc
  js/apps/admin-ui/public/locales/en/clients-help.json
  js/apps/admin-ui/public/locales/en/clients.json
  js/apps/admin-ui/src/clients/advanced/OpenIdConnectCompatibilityModes.tsx
  js/libs/keycloak-js/src/keycloak.js
  server-spi-private/src/main/java/org/keycloak/protocol/oidc/OIDCConfigAttributes.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCAdvancedConfigWrapper.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCWellKnownProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  testsuite/integration-arquillian/test-apps/hello-world-authz-service/hello-world-authz-realm.json
  testsuite/integration-arquillian/test-apps/servlet-authz/servlet-authz-realm.json
  testsuite/integration-arquillian/test-apps/servlet-policy-enforcer/servlet-policy-enforcer-authz-realm.json
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/BrokerLinkAndTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/ClientInitiatedAccountLinkTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AuthorizationCodeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthRedirectUriTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCBackwardsCompatibilityTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/demorealm.json
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/offline-client/offlinerealm.json
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/tenant1-realm.json
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/tenant2-realm.json
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#21862 Remove Infinispan workarounds introduced to prevent deadlocks
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanNotificationsManager.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java
Labels: team/store, flaky-test

#21861 Upgrade Infinispan to 14.0.13.Final
  pom.xml
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/DatabaseContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/InfinispanContainer.java
Labels: team/cloud-native, team/store, team/core

#20883 Adding Maven Build Cache Extension as opt-in feature
  .github/workflows/js-ci.yml
  .github/workflows/operator-ci.yml
  .github/workflows/snyk-analysis.yml
  .mvn/extensions.xml
  .mvn/maven-build-cache-config.xml
  .mvn/wrapper/maven-wrapper.properties
  adapters/oidc/js/pom.xml
  docs/building.md
  js/pom.xml
  quarkus/README.md
  themes/pom.xml
Labels: team/cloud-native, team/ui, flaky-test

#21904 Removing workaround for state transfer never completes
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/Infinispan.java
Labels: team/store

#21202 DPoP support 1st phase
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
  core/src/main/java/org/keycloak/OAuthErrorException.java
  core/src/main/java/org/keycloak/jose/jws/JWSHeader.java
  core/src/main/java/org/keycloak/jose/jws/crypto/HashUtils.java
  core/src/main/java/org/keycloak/protocol/oidc/representations/OIDCConfigurationRepresentation.java
  core/src/main/java/org/keycloak/representations/AccessToken.java
  core/src/main/java/org/keycloak/representations/dpop/DPoP.java
  core/src/main/java/org/keycloak/util/JWKSUtils.java
  core/src/test/java/org/keycloak/AtHashTest.java
  js/apps/admin-ui/public/locales/en/clients-help.json
  js/apps/admin-ui/public/locales/en/clients.json
  js/apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
  js/apps/admin-ui/src/utils/useIsFeatureEnabled.ts
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FeaturesDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
  server-spi-private/src/main/java/org/keycloak/events/Errors.java
  server-spi-private/src/main/java/org/keycloak/protocol/oidc/OIDCConfigAttributes.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCAdvancedConfigWrapper.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCWellKnownProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/HolderOfKeyEnforcerExecutor.java
  services/src/main/java/org/keycloak/services/resources/Cors.java
  services/src/main/java/org/keycloak/services/util/DPoPUtil.java
  services/src/main/java/org/keycloak/services/util/MtlsHoKTokenUtil.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/CIBATest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPI1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPICIBATest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/DPoPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/hok/HoKTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCWellKnownProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/flows/AbstractOIDCResponseTypeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/flows/OIDCHybridResponseTypeCodeIDTokenAsDetachedSigTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/flows/OIDCHybridResponseTypeCodeIDTokenAsDetachedSigTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/flows/OIDCHybridResponseTypeCodeIDTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/flows/OIDCHybridResponseTypeCodeIDTokenTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/LogoutTokenUtil.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#21924 Fix intermittent failures of the users tests
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/UserGroupsPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/user_details/UserDetailsPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/user_details/tabs/IdentityProviderLinksTab.ts
  js/apps/admin-ui/src/components/scroll-form/FormPanel.tsx
  js/apps/admin-ui/src/components/table-toolbar/KeycloakDataTable.tsx
Labels: area/testsuite, area/admin/ui, team/ui

#21867 Prevent EntityNotFoundException when ID doesn't exist in the DB
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorage.java
Labels: team/store, flaky-test

#21942 Fix script tests on windows
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/script/DeployedSAMLScriptMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/script/DeployedScriptAuthenticatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/script/DeployedScriptMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/script/DeployedScriptPolicyTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21102 Use new Root API to render Admin UI
  js/apps/admin-ui/cypress/e2e/realm_settings_general_tab_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/CredentialsPage.ts
  js/apps/admin-ui/src/main.tsx
Labels: area/admin/ui, kind/task, team/ui

#21845 Update bcpkix and bcprov dependencies (#21543)
  adapters/oidc/adapter-core/pom.xml
  adapters/oidc/installed/pom.xml
  adapters/oidc/jakarta-servlet-filter/pom.xml
  adapters/oidc/jetty/jetty-core/pom.xml
  adapters/oidc/jetty/jetty9.4/pom.xml
  adapters/oidc/servlet-filter/pom.xml
  adapters/oidc/spring-security/pom.xml
  adapters/oidc/tomcat/tomcat-core/pom.xml
  adapters/oidc/tomcat/tomcat/pom.xml
  adapters/oidc/undertow/pom.xml
  adapters/oidc/wildfly-elytron/pom.xml
  adapters/saml/jakarta-servlet-filter/pom.xml
  adapters/saml/jetty/jetty-core/pom.xml
  adapters/saml/jetty/jetty9.4/pom.xml
  adapters/saml/servlet-filter/pom.xml
  adapters/saml/tomcat/tomcat-core/pom.xml
  adapters/saml/tomcat/tomcat/pom.xml
  adapters/spi/adapter-spi/pom.xml
  adapters/spi/jboss-adapter-core/pom.xml
  crypto/default/pom.xml
  dependencies/server-min/pom.xml
  distribution/feature-packs/adapter-feature-pack/pom.xml
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/util/ClassLoaderUtil.java
  integration/client-cli/client-cli-dist/assembly.xml
  integration/client-cli/client-cli-dist/pom.xml
  integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/util/ClassLoaderUtil.java
  operator/pom.xml
  pom.xml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ClassLoaderPropertyMappers.java
  quarkus/tests/junit5/src/main/java/org/keycloak/Keycloak.java
  testsuite/integration-arquillian/servers/adapter-spi/undertow-adapter-jakarta/pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/integration-arquillian/tests/pom.xml
  testsuite/utils/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#21612 LGPL license header in files incompatible with Apache v2.0
  examples/saml/servlet-filter/src/main/webapp/error.jsp
  examples/saml/servlet-filter/src/main/webapp/logout.jsp
  themes/src/main/resources/theme/keycloak/welcome/index.ftl
Labels: team/core, flaky-test

#21884 Removes the initial delay seconds and drops the period to 1 second
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
Labels: team/cloud-native, flaky-test

#21897 Add logout other sessions checkbox to TOTP, webauthn and recovery authn codes setup pages
  services/src/main/java/org/keycloak/authentication/AuthenticatorUtil.java
  services/src/main/java/org/keycloak/authentication/actiontoken/updateemail/UpdateEmailActionToken.java
  services/src/main/java/org/keycloak/authentication/actiontoken/updateemail/UpdateEmailActionTokenHandler.java
  services/src/main/java/org/keycloak/authentication/requiredactions/RecoveryAuthnCodesAction.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateEmail.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdatePassword.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateTotp.java
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnRegister.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/login/UpdateEmailPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginConfigTotpPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPasswordUpdatePage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LogoutSessionsPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/SetupRecoveryAuthnCodesPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AbstractRequiredActionUpdateEmailTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionTotpSetupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateEmailTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateEmailTestWithVerificationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/BackwardsCompatibilityUserStorageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RecoveryAuthnCodesAuthenticatorTest.java
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/WebAuthnRegisterPage.java
  testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/AppInitiatedActionWebAuthnTest.java
  themes/src/main/resources/theme/base/login/login-config-totp.ftl
  themes/src/main/resources/theme/base/login/login-recovery-authn-code-config.ftl
  themes/src/main/resources/theme/base/login/login-update-password.ftl
  themes/src/main/resources/theme/base/login/password-commons.ftl
  themes/src/main/resources/theme/base/login/update-email.ftl
  themes/src/main/resources/theme/base/login/webauthn-register.ftl
Labels: team/cloud-native, team/store, team/core

#17541 Place Java setup in re-usable workflow file
  .github/actions/build-keycloak/action.yml
  .github/actions/integration-test-setup/action.yml
  .github/actions/java-setup/action.yml
  .github/actions/unit-test-setup/action.yml
  .github/workflows/ci.yml
  .github/workflows/documentation.yml
  .github/workflows/guides.yml
  .github/workflows/operator-ci.yml
Labels: area/ci, kind/task

#21983 Keycloak forgets ui_locales parameter when using reset password
  services/src/main/java/org/keycloak/locale/DefaultLocaleSelectorProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/EmailTest.java
Labels: team/cloud-native, team/store, team/core

#21912 Upgrade to Quarkus 3.2.2.Final
  pom.xml
  quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ConfigKeystorePropertyMappers.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.windows.approved.txt
Labels: team/cloud-native, flaky-test

#21963 Provide an HTTP 503 response when the thread pool rejected the request
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java
Labels: team/cloud-native, flaky-test

#21980 Fix german grammar issue in verification email
  themes/src/main/resources-community/theme/base/email/messages/messages_de.properties
Labels: flaky-test

#21998 Upgrade to Quarkus 3.2.2.Final (#21912)
  pom.xml
  quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ConfigKeystorePropertyMappers.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.windows.approved.txt
Labels: team/cloud-native

#21988 Fix script tests on windows (#21942)
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/script/DeployedSAMLScriptMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/script/DeployedScriptAuthenticatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/script/DeployedScriptMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/script/DeployedScriptPolicyTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#20472 Replace Windows separator with Unix separator
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
Labels: team/cloud-native, flaky-test

#21888 Convert LinkExpirationFormatterMethod to Java's ChoiceFormat pattern
  services/src/main/java/org/keycloak/theme/beans/LinkExpirationFormatterMethod.java
  services/src/test/java/org/keycloak/theme/beans/LinkExpirationFormatterMethodTest.java
  themes/src/main/resources-community/theme/base/email/messages/messages_ar.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_da.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_el.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_fa.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_fi.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_hu.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_nl.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_pl.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_sk.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_tr.properties
  themes/src/main/resources/theme/base/email/messages/messages_en.properties
Labels: flaky-test

#22017 Adjustements to the behaviour of dpop_bound_access_tokens switch
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
  services/src/main/java/org/keycloak/services/util/DPoPUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/DPoPTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21658 changes to speed up test times
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/ClusteringTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakServicesTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/RealmImportTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/K8sUtils.java
Labels: team/cloud-native, flaky-test

#22003 Initial pagination in the admin REST API for identity providers
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/IdentityProvidersResource.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21671 Inconsistent Wildcard handling for JPA
  docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/user/JpaUserModelCriteriaBuilder.java
  model/map/src/main/java/org/keycloak/models/map/user/MapUserProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UsersTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#21990 The escape() function is deprecated.
  js/libs/keycloak-js/package.json
  js/libs/keycloak-js/src/keycloak.js
  js/pnpm-lock.yaml
Labels: team/ui

#22037 Profile activation for WF app server doesn't properly work for Windows
  testsuite/integration-arquillian/servers/app-server/jboss/pom.xml
Labels: team/cloud-native, team/store, team/core

#22007 Allow view creds tab if user has `view` fine-grained permission
  js/apps/admin-ui/src/clients/ClientDetails.tsx
Labels: team/ui

#21997 Add logout other sessions checkbox to TOTP, webauthn and recovery authn codes setup pages
  services/src/main/java/org/keycloak/authentication/AuthenticatorUtil.java
  services/src/main/java/org/keycloak/authentication/actiontoken/updateemail/UpdateEmailActionToken.java
  services/src/main/java/org/keycloak/authentication/actiontoken/updateemail/UpdateEmailActionTokenHandler.java
  services/src/main/java/org/keycloak/authentication/requiredactions/RecoveryAuthnCodesAction.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateEmail.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdatePassword.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateTotp.java
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnRegister.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/login/UpdateEmailPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginConfigTotpPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPasswordUpdatePage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LogoutSessionsPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/SetupRecoveryAuthnCodesPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AbstractRequiredActionUpdateEmailTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionTotpSetupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateEmailTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateEmailTestWithVerificationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/BackwardsCompatibilityUserStorageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RecoveryAuthnCodesAuthenticatorTest.java
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/WebAuthnRegisterPage.java
  testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/AppInitiatedActionWebAuthnTest.java
  themes/src/main/resources/theme/base/login/login-config-totp.ftl
  themes/src/main/resources/theme/base/login/login-recovery-authn-code-config.ftl
  themes/src/main/resources/theme/base/login/login-update-password.ftl
  themes/src/main/resources/theme/base/login/password-commons.ftl
  themes/src/main/resources/theme/base/login/update-email.ftl
  themes/src/main/resources/theme/base/login/webauthn-register.ftl
Labels: team/cloud-native, team/store, team/core

#22025 Ensure mounted state in `useSetTimeout()` remains consistent
  js/apps/admin-ui/src/utils/useSetTimeout.ts
Labels: kind/bug, area/admin/ui, team/ui

#22053 Refactor conditional for sssd testing
  .github/actions/conditional/conditions
  .github/workflows/ci.yml
Labels: flaky-test

#22065 Execute CI when some changes were made in scripts dir
  .github/actions/conditional/conditions
Labels: flaky-test

#22071 Temporarily disable WebAuthn Firefox testing
  .github/workflows/ci.yml
Labels: flaky-test

#21846 Hostname guide improvements
  docs/guides/server/hostname.adoc
Labels: team/cloud-native

#22070 Run store testing conditionally for PRs
  .github/actions/conditional/conditions
  .github/workflows/ci.yml
Labels: team/store

#22058 Re-adding Infinispan workarounds to prevent deadlocks
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanNotificationsManager.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java
Labels: team/store

#21339 added shared resources to account ui
  js/apps/account-ui/src/api.ts
  js/apps/account-ui/src/api/representations.ts
  js/apps/account-ui/src/resources/PermissionRequest.tsx
  js/apps/account-ui/src/resources/Resources.tsx
  js/apps/account-ui/src/resources/ResourcesTab.tsx
Labels: team/ui, flaky-test

#22117 Hostname guide improvements
  docs/guides/server/hostname.adoc
Labels: team/cloud-native

#22093 refinements to improve how pod logs are saved
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/main/resources/META-INF/services/io.quarkus.test.junit.callback.QuarkusTestAfterEachCallback
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
Labels: team/cloud-native
