Repository keycloak/keycloak, pull requests merged in 2023-10, with the labels that each got.

#23557 Ignore query parameters while testing the LinkedIn profile picture URL
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23298 OAuthClient - fix nonce/scope typo
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
Labels: team/store, flaky-test

#23608 Update Help text for Exclude Issuer From Authentication Response
  js/apps/admin-ui/public/locales/en/translation.json
Labels: team/ui

#23639 Add setup erase command to example for adding more RPMs to the server container
  docs/guides/server/containers.adoc
Labels: team/cloud-native

#23102 Fix various bugs and issues in crypto/elytron
  crypto/elytron/src/main/java/org/keycloak/crypto/elytron/ElytronCertificateUtils.java
  crypto/elytron/src/main/java/org/keycloak/crypto/elytron/ElytronECDSACryptoProvider.java
  crypto/elytron/src/main/java/org/keycloak/crypto/elytron/ElytronOCSPProvider.java
  crypto/elytron/src/main/java/org/keycloak/crypto/elytron/ElytronUserIdentityExtractorProvider.java
  crypto/elytron/src/test/java/org/keycloak/crypto/elytron/test/CRLDistributionPointTest.java
  crypto/elytron/src/test/java/org/keycloak/crypto/elytron/test/ElytronHmacTest.java
  crypto/elytron/src/test/java/org/keycloak/crypto/elytron/test/ElytronKeyStoreTypesTest.java
  crypto/elytron/src/test/java/org/keycloak/crypto/elytron/test/ElytronPemUtilsTest.java
  crypto/elytron/src/test/java/org/keycloak/crypto/elytron/test/ElytronSignatureAlgTest.java
Labels: flaky-test

#23641 switching the operator role to clusterrole for ingresses config
  operator/overlays/default-namespace/kustomization.yaml
  operator/src/main/kubernetes/kubernetes.yml
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/K8sUtils.java
Labels: team/cloud-native

#23550 try and make, identity_providers_test.spec.ts > should revert and save options less flaky
  js/apps/admin-ui/cypress/e2e/identity_providers_test.spec.ts
Labels: team/ui

#23638 Fix set-version.sh's handling of NPM versions
  js/libs/keycloak-js/pom.xml
  pom.xml
  set-version.sh
Labels: team/ui, flaky-test

#23680 Fix set-version.sh's handling of NPM versions (#23638)
  js/libs/keycloak-js/pom.xml
  pom.xml
  set-version.sh
Labels: team/ui, flaky-test

#23535 Improve test coverage for Admin hostname properties
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HostnameDistTest.java
Labels: team/cloud-native, flaky-test

#23459 allows csv output to handle missing requested fields
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractRequestCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/util/Headers.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/util/HeadersBody.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/util/OutputUtil.java
  integration/client-cli/admin-cli/src/test/java/org/keycloak/client/admin/cli/util/OuputUtilTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#23712 Remove recommendation to file a GitHub issue
  docs/guides/operator/advanced-configuration.adoc
Labels: team/cloud-native

#22662 Update the Instagram login process
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social/InstagramLoginPage.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23726 Remove recommendation to file a GitHub issue (#23712)
  docs/guides/operator/advanced-configuration.adoc
Labels: team/cloud-native

#23714 Weak hashing algorithm usage in SSSD User federation
  federation/sssd/src/main/java/org/freedesktop/dbus/bin/DBusDaemon.java
  federation/sssd/src/main/java/org/freedesktop/dbus/bin/EmbeddedDBusDaemon.java
  federation/sssd/src/main/java/org/freedesktop/dbus/connections/impl/DirectConnection.java
  federation/sssd/src/main/java/org/freedesktop/dbus/connections/impl/DirectConnectionBuilder.java
Labels: team/core, flaky-test

#23722 Fix client assertion with invalid ES256, ES384, ES512 signatures
  services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
Labels: flaky-test

#23560 Upgrade liquibase version to avoid a bug where a changeset is execute…
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java
  pom.xml
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/zerodowntime/ZeroDowntimeTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#22317 added AccountResource SPI, Provider and ProviderFactory.
  server-spi-private/src/main/java/org/keycloak/services/resource/AccountResourceProvider.java
  server-spi-private/src/main/java/org/keycloak/services/resource/AccountResourceProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/services/resource/AccountResourceSpi.java
  server-spi-private/src/main/resources/META-INF/services/org.keycloak.provider.Spi
  server-spi/src/main/java/org/keycloak/theme/Theme.java
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
  services/src/main/java/org/keycloak/services/resources/account/AccountConsoleFactory.java
  services/src/main/java/org/keycloak/services/resources/account/AccountLoader.java
  services/src/main/resources/META-INF/services/org.keycloak.services.resource.AccountResourceProviderFactory
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/theme/CustomAccountResourceProviderFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/resources/META-INF/services/org.keycloak.services.resource.AccountResourceProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ServerInfoTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/theme/CustomAccountResourceProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/META-INF/keycloak-themes.json
  testsuite/integration-arquillian/tests/base/src/test/resources/theme/custom-account-provider/account/theme.properties
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#23744 fix: remove common-compress
  operator/pom.xml
Labels: team/cloud-native

#23708 Remove transaction in InfinispanSingleUseObjectProvider#remove
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanSingleUseObjectProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/concurrency/ConcurrentLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/SingleUseProviderTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23741 Tolerate secrets being missing (22.0)
  operator/src/main/java/org/keycloak/operator/controllers/WatchedSecretsStore.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
Labels: team/cloud-native, flaky-test

#23781 Fix broken URL in CODING_GUIDELINES.md
  js/CODING_GUIDELINES.md
Labels: kind/bug, area/docs, team/ui

#23776 Remove backward compatibility for ECDSA tokens
  core/src/main/java/org/keycloak/crypto/ECDSAAlgorithm.java
  core/src/main/java/org/keycloak/crypto/ECDSASignatureSignerContext.java
  core/src/main/java/org/keycloak/protocol/oidc/client/authentication/JWTClientCredentialsProvider.java
  services/src/main/java/org/keycloak/crypto/ClientECDSASignatureVerifierContext.java
  services/src/main/java/org/keycloak/crypto/ECDSASignatureProvider.java
  services/src/main/java/org/keycloak/crypto/ServerECDSASignatureSignerContext.java
  services/src/main/java/org/keycloak/crypto/ServerECDSASignatureVerifierContext.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/DPoPTest.java
Labels: kind/eol, team/cloud-native, team/store, team/core, flaky-test

#23750 UserProfileContext.ACCOUNT_OLD seems to be obsolete and not needed
  server-spi-private/src/main/java/org/keycloak/userprofile/UserProfileContext.java
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/config/UPConfigUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/config/UPConfigUtilsTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#22128 Fix multi-valued LDAP attribute support
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPProvidersFullNameMapperTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23702 Improve logging in case of OIDC Identity provider errors:
  server-spi-private/src/main/java/org/keycloak/broker/provider/util/SimpleHttp.java
  services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
  services/src/main/java/org/keycloak/services/messages/Messages.java
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: flaky-test

#22591 Converts keycloakdeployment to a dependent resource
  operator/pom.xml
  operator/src/main/java/org/keycloak/operator/Constants.java
  operator/src/main/java/org/keycloak/operator/Utils.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakAdminSecretDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDiscoveryServiceDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDistConfigurator.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngressDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportSecretDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakServiceDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/MetadataAwareOnUpdateFilter.java
  operator/src/main/java/org/keycloak/operator/controllers/OperatorManagedResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/KeycloakDistConfiguratorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
Labels: team/cloud-native, flaky-test

#23675 Update GroupAttributes to refresh fields on group change
  js/apps/admin-ui/src/groups/GroupAttributes.tsx
Labels: team/ui

#23686 Mark required config properties for LDAP Mappers
  core/src/main/java/org/keycloak/representations/idm/ConfigPropertyRepresentation.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/AbstractLDAPStorageMapperFactory.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/HardcodedAttributeMapperFactory.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/HardcodedLDAPAttributeMapperFactory.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/HardcodedLDAPGroupStorageMapperFactory.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/HardcodedLDAPRoleStorageMapperFactory.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/UserAttributeLDAPStorageMapperFactory.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapperFactory.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/role/RoleLDAPStorageMapperFactory.java
  js/apps/admin-ui/src/components/client/ClientSelect.tsx
  js/apps/admin-ui/src/components/dynamic/GroupComponent.tsx
  js/apps/admin-ui/src/components/dynamic/ListComponent.tsx
  js/apps/admin-ui/src/components/dynamic/MapComponent.tsx
  js/apps/admin-ui/src/components/dynamic/MultivaluedListComponent.tsx
  js/apps/admin-ui/src/components/dynamic/MultivaluedStringComponent.tsx
  js/apps/admin-ui/src/components/dynamic/PasswordComponent.tsx
  js/apps/admin-ui/src/components/dynamic/RoleComponent.tsx
  js/apps/admin-ui/src/components/dynamic/ScriptComponent.tsx
  js/apps/admin-ui/src/components/dynamic/StringComponent.tsx
  js/apps/admin-ui/src/components/dynamic/TextComponent.tsx
  js/libs/keycloak-admin-client/src/defs/authenticatorConfigInfoRepresentation.ts
  js/libs/keycloak-admin-client/src/defs/configPropertyRepresentation.ts
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi/src/main/java/org/keycloak/provider/ProviderConfigProperty.java
  server-spi/src/main/java/org/keycloak/provider/ProviderConfigurationBuilder.java
Labels: team/ui, flaky-test

#23831 Upgrade liquibase version to avoid a bug where a changeset is execute…
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/CustomCreateIndexChange.java
  pom.xml
Labels: team/store, flaky-test

#23819 Update `GroupAttributes` to refresh fields on group change
  js/apps/admin-ui/src/groups/GroupAttributes.tsx
Labels: team/ui

#23751 Optimize Vite configuration files
  js/apps/account-ui/package.json
  js/apps/account-ui/vite.config.ts
  js/apps/admin-ui/package.json
  js/apps/admin-ui/vite.config.ts
  js/libs/keycloak-masthead/vite.config.ts
  js/libs/ui-shared/vite.config.ts
  js/pnpm-lock.yaml
Labels: team/ui

#23839 Do not store empty attributes when updating user profile
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultUserProfile.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateProfileWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#22112 Making the readiness and liveness probe non-blocking
  quarkus/config-api/src/main/java/org/keycloak/config/HealthOptions.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HealthPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/health/ReactiveHealthHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/health/ReactiveLivenessHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/health/ReactiveReadinessHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/health/KeycloakReadyAsyncHealthCheck.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HealthDistTest.java
Labels: status/hold, team/cloud-native, flaky-test

#23785 Fix generated OpenAPI spec
  core/pom.xml
  core/src/main/java/org/keycloak/representations/idm/RealmRepresentation.java
  pom.xml
Labels: flaky-test

#23664 added id when the object is still new
  js/apps/admin-ui/src/identity-providers/add/AddMapper.tsx
Labels: team/ui

#23801 Add disclaimer about Kubernetes
  docs/guides/server/configuration.adoc
  docs/guides/server/containers.adoc
Labels: team/cloud-native

#23876 Fixing missing import for guide
  docs/guides/server/containers.adoc
Labels: team/cloud-native

#23517 12406 you are already logged in
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
  services/src/main/java/org/keycloak/forms/login/freemarker/AuthenticationStateCookie.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/forms/login/freemarker/model/AuthenticationSessionBean.java
  services/src/main/java/org/keycloak/forms/login/freemarker/model/UrlBean.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/saml/SamlProtocol.java
  services/src/main/java/org/keycloak/services/Urls.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationSessionManager.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/AppPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultipleTabsLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
  themes/src/main/resources/theme/base/login/resources/js/authChecker.js
  themes/src/main/resources/theme/base/login/template.ftl
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#20699 Add support for single-tenant mode to Microsoft Identity Provider
  js/apps/admin-ui/cypress/e2e/identity_providers_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/social/ProviderMicrosoftGeneralSettings.ts
  services/src/main/java/org/keycloak/social/microsoft/MicrosoftIdentityProvider.java
  services/src/main/java/org/keycloak/social/microsoft/MicrosoftIdentityProviderConfig.java
  services/src/main/java/org/keycloak/social/microsoft/MicrosoftIdentityProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#23874 Simplify the docs referencing the container registry
  docs/guides/server/containers.adoc
  docs/guides/server/importExport.adoc
Labels: team/cloud-native

#22035 Ignore UnknownHostException for Quarkus IT on local
  quarkus/tests/integration/src/test/resources/application.properties
Labels: impact/low, team/cloud-native, team/core, flaky-test

#23934 Update Operator product documentation
  docs/guides/operator/advanced-configuration.adoc
  docs/guides/operator/basic-deployment.adoc
Labels: team/cloud-native

#23793 Correct the SyntaxError on old navigators
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step1.html
Labels: flaky-test

#23796 Update TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
Labels: flaky-test

#22585 modification of kc.sh to remove param eval
  docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
  quarkus/container/Dockerfile
  quarkus/dist/src/main/content/bin/kc.bat
  quarkus/dist/src/main/content/bin/kc.sh
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/CustomLegacyUserProviderDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/model/StoreProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/ClientSearchTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupSearchTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23826 Do not return empty scope field in token introspection response
  services/src/main/java/org/keycloak/protocol/oidc/AccessTokenIntrospectionProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenIntrospectionTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23964 Fix incorrect description of offline session
  docs/guides/server/caching.adoc
Labels: area/storage, team/store

#23792 Resolve several usability issues around User Profile
  core/src/main/java/org/keycloak/representations/idm/UserProfileAttributeGroupMetadata.java
  core/src/main/java/org/keycloak/representations/idm/UserProfileAttributeMetadata.java
  core/src/main/java/org/keycloak/representations/idm/UserProfileMetadata.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/UserProfileResource.java
  js/apps/admin-ui/cypress/e2e/i18n_test.spec.ts
  js/apps/admin-ui/cypress/support/util/AdminClient.ts
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
  js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx
  js/apps/admin-ui/src/components/users/UserDataTableToolbarItems.tsx
  js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesTab.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/UserProfileContext.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
  js/apps/admin-ui/src/user/CreateUser.tsx
  js/apps/admin-ui/src/user/EditUser.tsx
  js/apps/admin-ui/src/user/UserAttributes.tsx
  js/apps/admin-ui/src/user/UserForm.tsx
  js/apps/admin-ui/src/user/UserProfileFields.tsx
  js/apps/admin-ui/src/user/components/OptionsComponent.tsx
  js/apps/admin-ui/src/user/components/SelectComponent.tsx
  js/apps/admin-ui/src/user/components/TextAreaComponent.tsx
  js/apps/admin-ui/src/user/components/TextComponent.tsx
  js/apps/admin-ui/src/user/components/UserProfileGroup.tsx
  js/apps/admin-ui/src/user/form-state.ts
  js/apps/admin-ui/src/user/user-credentials/RequiredActionMultiSelect.tsx
  js/apps/admin-ui/src/user/user-credentials/ResetCredentialDialog.tsx
  js/apps/admin-ui/src/user/utils.ts
  js/apps/admin-ui/src/user/utils/user-profile.ts
  js/libs/keycloak-admin-client/src/defs/userProfileConfig.ts
  js/libs/keycloak-admin-client/src/defs/userProfileMetadata.ts
  js/libs/keycloak-admin-client/src/defs/userRepresentation.ts
  js/libs/keycloak-admin-client/src/resources/users.ts
  server-spi-private/src/main/java/org/keycloak/userprofile/AttributeContext.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  server-spi-private/src/main/java/org/keycloak/userprofile/UserProfileProvider.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
  services/src/main/java/org/keycloak/services/resources/admin/UserProfileResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/validator/ImmutableAttributeValidator.java
  services/src/main/java/org/keycloak/userprofile/validator/UsernameMutationValidator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTestWithUserProfile.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/userprofile/UserProfileAdminTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#23156 Support custom FIDO2 origin validation
  core/src/main/java/org/keycloak/representations/idm/RealmRepresentation.java
  js/apps/admin-ui/public/locales/en/translation.json
  js/apps/admin-ui/public/locales/ja/translation.json
  js/apps/admin-ui/public/locales/zh-CN/translation.json
  js/apps/admin-ui/src/authentication/policies/WebauthnPolicy.tsx
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/RealmAttributes.java
  model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyExportImportManager.java
  model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/realm/entity/HotRodWebAuthnPolicyEntity.java
  model/map/src/main/java/org/keycloak/models/map/datastore/MapExportImportManager.java
  model/map/src/main/java/org/keycloak/models/map/realm/entity/MapWebAuthnPolicyEntity.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi/src/main/java/org/keycloak/models/WebAuthnPolicy.java
  services/src/main/java/org/keycloak/credential/WebAuthnCredentialProvider.java
  services/src/main/java/org/keycloak/credential/WebAuthnCredentialProviderFactory.java
  services/src/main/java/org/keycloak/credential/WebAuthnPasswordlessCredentialProvider.java
Labels: area/core, team/store, team/core, team/ui, flaky-test

#23398 Fix unexpected expiration when import offline client session
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderOfflineModelTest.java
Labels: team/store, flaky-test

#23916 Removing the default cache metadata
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/user/profile/CustomUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTestWithUserProfile.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/store, team/core

#23969 23951 backport
  docs/documentation/server_admin/topics/admin-cli.adoc
Labels: team/cloud-native, team/store, team/core, team/ui

#23974 Fix unexpected expiration when import offline client session
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderOfflineModelTest.java
Labels: team/store

#23979 Separating CLI arguments into separate strings to avoid concatenation
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HealthDistTest.java
Labels: team/cloud-native, flaky-test

#24005 Disable Account Console IT in Firefox.
  .github/workflows/ci.yml
Labels: flaky-test

#23963 Update login flow in OCP3 and OCP4 social login
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social/OpenShiftLoginPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23855 Backport non-blocking liveness probes
  quarkus/config-api/src/main/java/org/keycloak/config/HealthOptions.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HealthPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/health/ReactiveHealthHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/health/ReactiveLivenessHandler.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HealthDistTest.java
Labels: team/cloud-native, flaky-test

#23944 Remove realm model storage from OAuth2DeviceConfig class
  model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyExportImportManager.java
  model/map/src/main/java/org/keycloak/models/map/datastore/MapExportImportManager.java
  server-spi/src/main/java/org/keycloak/models/OAuth2DeviceConfig.java
Labels: team/cloud-native, team/store, flaky-test

#24027 Remove mentions of Crunchy Operator from docs
  docs/guides/operator/basic-deployment.adoc
Labels: team/cloud-native

#24009 Clean up created test user to avoid conflict with other tests
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/runonserver/SerializationUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPProvidersFullNameMapperTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23657 always allow browsing as we don't know the subgroups
  js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx
  js/apps/admin-ui/src/components/group/group-picker-dialog.css
  js/apps/admin-ui/src/groups/components/MoveDialog.tsx
Labels: team/ui

#23544 Update Account UI French translation as of September 26th.
  js/apps/account-ui/public/locales/fr/translation.json
Labels: area/translations, team/ui

#23894 Simplify the docs referencing the container registry
  docs/guides/server/containers.adoc
  docs/guides/server/importExport.adoc
Labels: team/cloud-native

#23706 added test for resources
  js/apps/account-ui/playwright.config.ts
  js/apps/account-ui/src/resources/Resources.tsx
  js/apps/account-ui/src/resources/ResourcesTab.tsx
  js/apps/account-ui/src/resources/ShareTheResource.tsx
  js/apps/account-ui/src/resources/SharedWith.tsx
  js/apps/account-ui/test/my-resources.spec.ts
Labels: team/ui

#23859 Unify CLI handling across guides
  docs/documentation/server_admin/topics/vault.adoc
Labels: flaky-test

#24048 Wait for request when testing session revocation
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/sessions/SessionsPage.ts
Labels: team/ui

#22148 Enhancing Light Weight Token
  core/src/main/java/org/keycloak/representations/JsonWebToken.java
  js/apps/admin-ui/public/locales/en/translation.json
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/UserSessionAdapter.java
  model/legacy-private/src/main/java/org/keycloak/models/session/PersistentUserSessionAdapter.java
  model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionAdapter.java
  server-spi/src/main/java/org/keycloak/models/UserSessionModel.java
  services/src/main/java/org/keycloak/protocol/oidc/AccessTokenIntrospectionProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/UserInfoEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractOIDCProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractPairwiseSubMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractUserRoleMappingMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AcrProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AddressMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AllowedWebOriginsProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AudienceProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AudienceResolveProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/ClaimsParameterTokenMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/ClaimsParameterWithValueIdTokenMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/FullNameMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/GroupMembershipMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/HardcodedClaim.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/HardcodedRole.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/OIDCAttributeMapperHelper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/RoleNameMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/ScriptBasedOIDCProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/TokenIntrospectionTokenMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/UserAttributeMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/UserClientRoleMappingMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/UserPropertyMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/UserRealmRoleMappingMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/UserSessionNoteMapper.java
  services/src/main/java/org/keycloak/services/managers/ClientManager.java
  services/src/main/java/org/keycloak/services/util/UserSessionUtil.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerSubMatchIntrospectionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/AbstractKerberosSingleRealmTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPMultipleAttributesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthGrantTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OIDCProtocolMappersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AudienceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/script/DeployedScriptMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/script/UndeployedScriptMapperNotAvailableTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ProtocolMapperUtil.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#24001 removed invalid RealmName check
  js/apps/admin-ui/src/realm/add/NewRealmForm.tsx
Labels: team/ui

#24002 Fix issue with overlapping WebElements in SocialLoginTest#PaypalLogin
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social/PayPalLoginPage.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24018 Optionally accept RELATED_IMAGE_KEYCLOAK as the operand coordinate
  operator/src/main/resources/application.properties
Labels: team/cloud-native, flaky-test

#23983 Allow full use of Authorization tab for anyone with manage-authorization
  js/apps/admin-ui/src/clients/ClientDetails.tsx
  js/apps/admin-ui/src/clients/authorization/AuthorizationExport.tsx
  js/apps/admin-ui/src/clients/routes/AuthenticationTab.tsx
Labels: team/ui

#24065 Backport: removed invalid RealmName check (#24001)
  js/apps/admin-ui/src/realm/add/NewRealmForm.tsx
Labels: team/ui

#23982 The username in account is required and don't change when email as username is enabled
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/LegacyAttributes.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24062 Optionally accept RELATED_IMAGE_KEYCLOAK as the operand coordinate
  operator/src/main/resources/application.properties
Labels: team/cloud-native, flaky-test

#23942 test: eliminates some possible timing issues with watched secrets tests
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
Labels: team/cloud-native

#23975 test: eliminates some possible timing issues with watched secrets tests
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
Labels: team/cloud-native, flaky-test

#23922 Do not show empty annotation when creating attribute group
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesGroupForm.tsx
Labels: team/ui

#24078 Allow full use of Authorization tab for anyone with manage-authorization (#23983)
  js/apps/admin-ui/src/clients/ClientDetails.tsx
  js/apps/admin-ui/src/clients/authorization/AuthorizationExport.tsx
  js/apps/admin-ui/src/clients/routes/AuthenticationTab.tsx
Labels: team/ui

#24083 Enhance user profile attribute form UX
  js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
Labels: team/ui

#24050 multiple values are valid
  js/apps/admin-ui/src/util.ts
Labels: team/ui

#23636 Use JDK LdapName and Rdn instead of our classes
  federation/ldap/pom.xml
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPUtils.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/model/LDAPDn.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/query/internal/LDAPQuery.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/IdentityStore.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPIdentityStore.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPOperationManager.java
  federation/ldap/src/test/java/org/keycloak/storage/ldap/idm/model/LDAPDnTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPNoMSADTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/user/UserSyncTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24053 Import migration step for kc22
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate22_0_0_RemoveRhssoThemes.java
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate22_0_5_UpdateAccountTheme.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-22.0.0.xml
  model/legacy-private/src/main/java/org/keycloak/migration/migrators/MigrateTo22_0_0.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport1903MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/migration-test/migration-realm-19.0.3.json
Labels: team/cloud-native, team/store, team/core, flaky-test

#24137 Make dropdown groups unique
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesTab.tsx
Labels: team/ui

#23777 operator: Replace dead documentation link
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakSharedCsvMetadata.java
Labels: team/cloud-native, flaky-test

#23669 removed some remnant namespaces usage
  js/apps/admin-ui/src/clients/authorization/AuthorizationEvaluate.tsx
  js/apps/admin-ui/src/components/client/ClientSelect.tsx
  js/apps/admin-ui/src/components/dynamic/ClientSelectComponent.tsx
  js/apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
Labels: team/ui

#23932 After tab1 finish authentication, make sure that rootAuthenticationSe…
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanKeycloakTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/RootAuthenticationSessionAdapter.java
  services/src/main/java/org/keycloak/forms/login/freemarker/AuthenticationStateCookie.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationSessionManager.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/client/resources/TestingResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24135 Import migration step for kc22
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate22_0_0_RemoveRhssoThemes.java
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate22_0_5_UpdateAccountTheme.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-22.0.0.xml
  model/legacy-private/src/main/java/org/keycloak/migration/migrators/MigrateTo22_0_0.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport1903MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/migration-test/migration-realm-19.0.3.json
Labels: team/cloud-native, team/store, team/core, flaky-test

#24115 CVE-2023-44487 Denial of Service (DoS) vulnerability in io.netty
  pom.xml
Labels: team/cloud-native, kind/cve, flaky-test

#24114 CVE-2023-44487 Denial of Service (DoS) vulnerability in io.netty
  pom.xml
Labels: team/cloud-native, kind/cve, flaky-test

#24057 fix: moves jgroups.dns.query to a system property
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
Labels: team/cloud-native, flaky-test

#24056 Update fips.adoc
  docs/guides/server/fips.adoc
Labels: team/cloud-native

#24161 fix: allows --version to work
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/VersionDistTest.java
Labels: team/cloud-native

#24154 Fix for issue #24035
  js/apps/admin-ui/src/groups/components/GroupTree.tsx
Labels: team/ui

#23378 Realm localization texts are now sorted by key.
  js/apps/admin-ui/src/realm-settings/LocalizationTab.tsx
Labels: team/store, team/ui, flaky-test

#24152 small refactor on the scroll form
  js/apps/admin-ui/src/components/scroll-form/FormPanel.tsx
  js/apps/admin-ui/src/components/scroll-form/FormTitle.tsx
  js/apps/admin-ui/src/components/scroll-form/ScrollForm.tsx
  js/apps/admin-ui/src/components/scroll-form/ScrollPanel.tsx
  js/apps/admin-ui/src/components/scroll-form/form-panel.css
  js/apps/admin-ui/src/components/scroll-form/form-title.module.css
  js/apps/admin-ui/src/components/scroll-form/scroll-form.css
  js/apps/admin-ui/src/components/scroll-form/scroll-form.module.css
Labels: team/ui

#24025 User profile tweaks in registration forms
  server-spi-private/src/main/java/org/keycloak/models/utils/DefaultAuthenticationFlows.java
  server-spi-private/src/main/java/org/keycloak/userprofile/UserProfileContext.java
  services/src/main/java/org/keycloak/authentication/forms/RegistrationProfile.java
  services/src/main/java/org/keycloak/authentication/forms/RegistrationUserCreation.java
  services/src/main/java/org/keycloak/forms/login/freemarker/model/RegisterBean.java
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/InitialFlowsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/ProvidersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/RegistrationFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/config/UPConfigUtilsTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23630 kcadm.bat, kcreg.bat do not respect environment variables JAVA, JAVA_…
  integration/client-cli/admin-cli/src/main/bin/kcadm.bat
  integration/client-cli/client-registration-cli/src/main/bin/kcreg.bat
  quarkus/dist/src/main/content/bin/kc.bat
Labels: team/cloud-native, flaky-test

#23918 Allow running of UI development server against local build quarkus distribution of keycloak
  js/apps/keycloak-server/README.md
  js/apps/keycloak-server/package.json
  js/apps/keycloak-server/scripts/start-server.js
Labels: team/ui

#24181 fix: allows --version to work
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/VersionDistTest.java
Labels: team/cloud-native

#24162 Ignore custom attributes when processing attributes in verify profile action
  services/src/main/java/org/keycloak/forms/login/freemarker/model/AbstractUserProfileBean.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/VerifyProfileTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23394 Making sure public clients can RPT tokens
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/EntitlementAPITest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24134 Avoid breaking change in UserSessionModel
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java
  model/legacy-private/src/main/java/org/keycloak/models/session/PersistentUserSessionAdapter.java
  server-spi/src/main/java/org/keycloak/models/UserSessionModel.java
Labels: team/store, flaky-test

#20212 Improve quoting and variable parsing for batch start script.
  quarkus/dist/src/main/content/bin/kc.bat
Labels: team/cloud-native, flaky-test

#24172 added default field type
  js/apps/admin-ui/src/user/UserProfileFields.tsx
  js/apps/admin-ui/src/user/components/MultiInputComponent.tsx
Labels: team/ui

#23797 fix: ensures that cli and env messages are the same
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ExecutionExceptionHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/NonCliPropertyException.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/PropertyMapperParameterConsumer.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ShortErrorMessageHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractStartCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Build.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Export.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Import.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Start.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/StartDev.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/BuildCommandDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
  quarkus/tests/integration/src/test/resources/BuildCommandDistTest/keycloak.conf
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/DockerKeycloakDistribution.java
  testsuite/integration-arquillian/servers/auth-server/quarkus/src/main/content/conf/keycloak.conf
Labels: team/cloud-native, team/store, team/core, flaky-test

#24189 fix #24188 Update Czech and Slovak localization
  themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_sk.properties
Labels: kind/enhancement, area/translations

#22989 Prevent stampede after realm cache invalidation
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheManager.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
Labels: team/store, flaky-test

#24147 Declarative User Profile export
  model/jpa/src/main/resources/META-INF/jpa-changelog-23.0.0.xml
  model/jpa/src/main/resources/META-INF/jpa-changelog-master.xml
  model/legacy-private/src/main/java/org/keycloak/migration/migrators/MigrateTo23_0_0.java
  model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyMigrationManager.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/config/UPConfigUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ComponentsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport1903MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport198MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport255MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport343MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport483MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport903MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/CustomUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/config/UPConfigUtilsTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/migration-test/migration-realm-19.0.3.json
  testsuite/integration-arquillian/tests/base/src/test/resources/model/import-userprofile.json
Labels: team/cloud-native, team/store, team/core, flaky-test

#24175 operator: Replace dead documentation link (#23777)
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakSharedCsvMetadata.java
Labels: team/cloud-native, flaky-test

#24221 added default field type (#24172)
  js/apps/admin-ui/src/user/UserProfileFields.tsx
  js/apps/admin-ui/src/user/components/MultiInputComponent.tsx
Labels: team/ui

#24149 typo fixed
  js/apps/admin-ui/public/locales/de/translation.json
Labels: team/ui

#24036 fix exception when user does not have view-realm role
  js/apps/admin-ui/src/user/FederatedUserLink.tsx
Labels: team/ui

#20151 Fixes a NullPointerException after import validation
  model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/user/UserSyncTest.java
Labels: missing/tests, team/store, flaky-test

#24231 fix exception when user does not have view-realm role (#24036)
  js/apps/admin-ui/src/user/FederatedUserLink.tsx
Labels: team/ui

#23892 Add dedicated feature flag for oauth device grant flow (#23891)
  common/src/main/java/org/keycloak/common/Profile.java
  js/apps/admin-ui/src/clients/add/CapabilityConfig.tsx
  js/apps/admin-ui/src/realm-settings/TokensTab.tsx
  js/apps/admin-ui/src/utils/useIsFeatureEnabled.ts
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
  services/src/main/java/org/keycloak/protocol/oidc/OIDCWellKnownProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/device/endpoints/DeviceEndpointFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/client/KeycloakTestingClient.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/client/resources/TestingResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuth2DeviceAuthorizationGrantTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#24209 Do not reset the user profile configuration on disable
  model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyExportImportManager.java
  model/map/src/main/java/org/keycloak/models/map/datastore/MapExportImportManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/VerifyProfileTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24244 Fix for Admin UI group view shows attributes of previously viewed group
  js/apps/admin-ui/src/groups/components/GroupTree.tsx
Labels: team/ui

#24034 fixed count for pagination
  js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx
  js/apps/admin-ui/src/groups/components/GroupTree.tsx
Labels: team/ui

#24177 Adapter tests failing with Jakarta error
  pom.xml
  testsuite/integration-arquillian/test-apps/spring-boot-adapter-app/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test, team/continuous-testing

#23318 Users in role Rest API returns empty when User federation used
  model/jpa/src/main/java/org/keycloak/storage/jpa/JpaUserFederatedStorageProvider.java
  model/jpa/src/main/java/org/keycloak/storage/jpa/entity/FederatedUserRoleMappingEntity.java
  model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java
  model/legacy/src/main/java/org/keycloak/storage/federated/UserRoleMappingsFederatedStorage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24215 Remove RegistrationProfile class and handle migration
  docs/documentation/server_development/topics/auth-spi.adoc
  docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
  model/legacy-private/src/main/java/org/keycloak/migration/migrators/MigrateTo23_0_0.java
  services/src/main/java/org/keycloak/authentication/forms/RegistrationProfile.java
  services/src/main/resources/META-INF/services/org.keycloak.authentication.FormActionFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/ProvidersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/other/webauthn/src/test/resources/webauthn/testrealm-webauthn.json
Labels: team/cloud-native, team/store, team/core, flaky-test

#24212 Verification of iss at refresh token request
  core/src/main/java/org/keycloak/TokenVerifier.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24259 Add support for passing acr_values in auth requests in keycloak.js (#9383)
  docs/documentation/securing_apps/topics/oidc/javascript-adapter.adoc
  js/libs/keycloak-js/dist/keycloak.d.ts
  js/libs/keycloak-js/src/keycloak.js
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/javascript/JSObjectBuilder.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#24272 Add openapi annotations to the UserProfileResource
  services/src/main/java/org/keycloak/services/resources/admin/UserProfileResource.java
Labels: flaky-test

#24290 Enable `github` reporter for Playwright
  js/apps/account-ui/playwright.config.ts
Labels: team/ui

#23663 Account user roles tests
  js/apps/account-ui/src/components/page/Page.tsx
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
  js/apps/account-ui/test/account-security.spec.ts
  js/apps/account-ui/test/personal-info/personal-info.spec.ts
  js/apps/account-ui/test/realms/user-profile-realm.json
Labels: team/ui

#24315 Fix KcOidcBrokerTransientSessionsTest
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
Labels: flaky-test

#24243 Additional tests for User Profile, Attributes & Realm-Settings/Login configs
  js/apps/admin-ui/cypress/e2e/realm_settings_user_profile_disabled.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_settings_user_profile_enabled.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_settings_user_profile_tab.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/UserProfile.ts
  js/apps/admin-ui/src/components/view-header/ViewHeader.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesGroupForm.tsx
Labels: team/ui

#22700 Group scalability upgrades
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/group/GroupPolicyProviderFactory.java
  core/src/main/java/org/keycloak/representations/idm/GroupRepresentation.java
  docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapper.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/GroupResource.java
  js/apps/admin-ui/cypress/e2e/sessions_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/components/PageObject.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/groups/GroupPage.ts
  js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx
  js/apps/admin-ui/src/groups/GroupTable.tsx
  js/apps/admin-ui/src/groups/GroupsSection.tsx
  js/apps/admin-ui/src/groups/Members.tsx
  js/apps/admin-ui/src/groups/components/GroupTree.tsx
  js/libs/keycloak-admin-client/README.md
  js/libs/keycloak-admin-client/src/defs/groupRepresentation.ts
  js/libs/keycloak-admin-client/src/resources/groups.ts
  js/libs/keycloak-admin-client/test/groups.spec.ts
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/GroupAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
  model/jpa/src/main/java/org/keycloak/models/jpa/GroupAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/GroupEntity.java
  model/legacy-private/src/main/java/org/keycloak/exportimport/util/ExportUtils.java
  model/legacy-private/src/main/java/org/keycloak/storage/GroupStorageManager.java
  model/map/src/main/java/org/keycloak/models/map/group/MapGroupProvider.java
  model/map/src/main/java/org/keycloak/models/map/group/MapGroupProviderFactory.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AdminExtResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/GroupsResource.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi/src/main/java/org/keycloak/models/GroupModel.java
  server-spi/src/main/java/org/keycloak/models/GroupProvider.java
  server-spi/src/main/java/org/keycloak/models/RealmModel.java
  services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  services/src/main/java/org/keycloak/utils/GroupUtils.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/admin/ApiUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/concurrency/ConcurrencyTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupSearchTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/GroupNamePolicyTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/GroupPathPolicyTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cluster/GroupInvalidationClusterTest.java
Labels: team/store, team/core, team/ui, flaky-test

#24347 add missing translations
  js/apps/admin-ui/public/locales/en/translation.json
  js/apps/admin-ui/src/authentication/policies/WebauthnPolicy.tsx
  js/apps/admin-ui/src/identity-providers/add/AddMapperForm.tsx
  js/apps/admin-ui/src/realm/add/NewRealmForm.tsx
Labels: team/ui

#24285 Add a property to the User Profile Email Validator for max length of the local part
  docs/documentation/server_admin/topics/users/user-profile.adoc
  server-spi-private/src/main/java/org/keycloak/utils/EmailValidationUtil.java
  server-spi-private/src/main/java/org/keycloak/validate/validators/EmailValidator.java
  server-spi-private/src/test/java/org/keycloak/validate/BuiltinValidatorsTest.java
  server-spi-private/src/test/java/org/keycloak/validate/ValidatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/VerifyProfileTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24322 Use default namespace for i18next
  js/apps/account-ui/src/i18n.ts
  js/apps/admin-ui/src/i18n/i18n.ts
Labels: team/ui

#24281 Map Store Removal: Remove Map Store tests from GHA
  .github/workflows/ci.yml
Labels: flaky-test

#23735 Cache PNPM store in CI
  .github/actions/build-keycloak/action.yml
  .github/actions/frontend-plugin-cache/action.yml
  .github/actions/integration-test-setup/action.yml
  .github/actions/pnpm-setup/action.yml
  .github/actions/unit-test-setup/action.yml
  .gitignore
  adapters/oidc/js/pom.xml
  docs/documentation/.gitignore
  docs/documentation/release-details
  js/.gitignore
  js/apps/account-ui/pom.xml
  js/apps/admin-ui/pom.xml
  js/libs/keycloak-admin-client/pom.xml
  js/libs/keycloak-js/pom.xml
  js/package.json
  js/pom.xml
  pom.xml
  prod-arguments.json
  themes/.gitignore
  themes/UPDATING-NODE-MODULES.md
  themes/pom.xml
  themes/src/main/resources/theme/keycloak.v2/account/src/app/account-service/account.service.ts
  themes/src/main/resources/theme/keycloak.v2/account/src/package-lock.json
  themes/src/main/resources/theme/keycloak.v2/account/src/package.json
  themes/src/main/resources/theme/keycloak.v2/account/src/pnpm-lock.yaml
  themes/src/main/resources/theme/keycloak/common/resources/package-lock.json
  themes/src/main/resources/theme/keycloak/common/resources/package.json
  themes/src/main/resources/theme/keycloak/common/resources/pnpm-lock.yaml
Labels: team/ui

#24327 fix to preload offline sessions faster
  model/jpa/src/main/java/org/keycloak/models/jpa/session/JpaUserSessionPersisterProvider.java
Labels: team/store, flaky-test

#24142 Add some type-safety enhancements to `AttributesTab`
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesTab.tsx
Labels: kind/enhancement, team/ui

#24354 Add userProfileEnabled attribute to realm response if admin can view users
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/PermissionsTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24329 CVE-2023-4586 - Hot Rod client does not enable hostname validation wh…
  pom.xml
Labels: team/store, flaky-test

#24173 Added Turkish support to Account ui
  js/apps/account-ui/public/locales/tr/translation.json
Labels: area/translations, team/ui

#24254 Fix IllegalState InjectionManagerFactory not found on springboot tests
  testsuite/integration-arquillian/test-apps/spring-boot-adapter-app/pom.xml
  testsuite/integration-arquillian/tests/other/springboot-tests/pom.xml
  testsuite/integration-arquillian/tests/other/springboot-tests/src/test/java/org/keycloak/testsuite/springboot/AccountLinkSpringBootTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24340 Group count and PartialExport permission fixes
  docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
  js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/PermissionsTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#24225 CVE-2023-44483 - Insertion of Sensitive Information into Log File vulnerability in org.apache.santuario:xmlsec
  pom.xml
Labels: team/store, team/core, flaky-test

#24359 Admin UI: User Profile always render multi valued inputs for multi valued input types.
  js/apps/admin-ui/src/user/UserProfileFields.tsx
Labels: team/ui

#24330 CVE-2023-4586 - Hot Rod client does not enable hostname validation when using TLS that lead to a MITM attack
  pom.xml
Labels: team/store, flaky-test

#24180 Adapter tests failing with Jakarta error
  pom.xml
  testsuite/integration-arquillian/test-apps/spring-boot-adapter-app/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#24418 Remove Quarkus branding from the Operator log
  operator/src/main/resources/application.properties
Labels: team/cloud-native, flaky-test

#24226 [Backport] CVE-2023-44483 - Insertion of Sensitive Information into Log File vulnerability in org.apache.santuario:xmlsec
  pom.xml
Labels: team/store, team/core

#23273 Allow customization of aud claim with JWT Authentication
  docs/documentation/server_admin/topics/identity-broker/oidc.adoc
  js/apps/admin-ui/cypress/e2e/identity_providers_oidc_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts
  js/apps/admin-ui/public/locales/en/translation.json
  js/apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx
  services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
  services/src/main/java/org/keycloak/broker/oidc/OAuth2IdentityProviderConfig.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerPrivateKeyJwtCustomAudienceTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#24419 Remove Quarkus branding from the Operator log
  operator/src/main/resources/application.properties
Labels: team/cloud-native, flaky-test
