Repository keycloak/keycloak, pull requests merged in 2023-08, with the labels that each got.

#22129 Fix authenticatorConfig for javascript providers
  model/legacy-private/src/main/java/org/keycloak/exportimport/util/ExportUtils.java
  model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyExportImportManager.java
  model/map/src/main/java/org/keycloak/models/map/datastore/MapExportImportManager.java
  server-spi-private/src/main/java/org/keycloak/deployment/DeployedConfigurationsManager.java
  server-spi-private/src/main/java/org/keycloak/deployment/DeployedConfigurationsProvider.java
  server-spi-private/src/main/java/org/keycloak/deployment/DeployedConfigurationsProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/deployment/DeployedConfigurationsSpi.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  server-spi-private/src/main/resources/META-INF/services/org.keycloak.provider.Spi
  services/src/main/java/org/keycloak/authentication/authenticators/browser/DeployedScriptAuthenticatorFactory.java
  services/src/main/java/org/keycloak/deployment/DefaultDeployedConfigurationsProvider.java
  services/src/main/java/org/keycloak/deployment/DefaultDeployedConfigurationsProviderFactory.java
  services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java
  services/src/main/resources/META-INF/services/org.keycloak.deployment.DeployedConfigurationsProviderFactory
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/script/DeployedScriptAuthenticatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/FlowUtil.java
Labels: team/cloud-native, team/store, team/core

#22120 Change postgres image for Operator tests
  operator/src/main/resources/example-db-secret.yaml
  operator/src/main/resources/example-postgres.yaml
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
Labels: team/cloud-native, flaky-test

#22149 Fix Operator tests on OpenShift
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/PodTemplateTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
Labels: team/cloud-native

#22165 Fix deprecated API usage in quarkus module (#22163)
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/LiquibaseProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakConfigSourceProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/VertxClientCertificateLookup.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/DatabaseContainer.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/DockerKeycloakDistribution.java
Labels: team/cloud-native

#22152 makes spec.replicas optional
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakSpec.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/CRDTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/ClusteringTest.java
Labels: team/cloud-native

#22038 Execute only FIPS Unit tests, not UT of dependent modules
  .github/scripts/run-fips-ut.sh
Labels: impact/low, team/core

#22081 simplifying status updates to a single method for each controller
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDiscoveryService.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngress.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakService.java
  operator/src/main/java/org/keycloak/operator/controllers/StatusUpdater.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/CRDUtils.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakStatus.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
Labels: team/cloud-native, flaky-test

#22178 Missing client_id validation match when authenticating client with JW…
  services/src/main/java/org/keycloak/authentication/authenticators/client/AbstractClientAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientSecretAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
Labels: team/cloud-native, team/store, team/core

#22108 Remove option Nerver Expires for tokens in Advanced OIDC client configuration
  docs/documentation/upgrading/topics/keycloak/changes-22_0_2.adoc
  docs/documentation/upgrading/topics/keycloak/changes.adoc
  js/apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
  js/apps/admin-ui/src/clients/advanced/TokenLifespan.tsx
  server-spi-private/src/main/java/org/keycloak/models/utils/SessionExpirationUtils.java
  server-spi-private/src/test/java/org/keycloak/models/utils/SessionExpirationUtilsTest.java
Labels: team/ui, flaky-test

#22044 switches the admin secret to a dependent resource
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakAdminSecret.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakAdminSecretDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/controllers/OperatorManagedResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
Labels: team/cloud-native, flaky-test

#22224 Remove option Nerver Expires for tokens in Advanced OIDC client configuration
  docs/documentation/upgrading/topics/keycloak/changes-22_0_2.adoc
  docs/documentation/upgrading/topics/keycloak/changes.adoc
  js/apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
  js/apps/admin-ui/src/clients/advanced/TokenLifespan.tsx
  server-spi-private/src/main/java/org/keycloak/models/utils/SessionExpirationUtils.java
  server-spi-private/src/test/java/org/keycloak/models/utils/SessionExpirationUtilsTest.java
Labels: team/ui

#22029 Use new "Chrome for Testing" browser and driver.
  .github/actions/install-chrome/action.yml
  .github/workflows/ci.yml
Labels: flaky-test

#22097 Allow assign realm roles with query-users access.
  js/apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
Labels: team/ui

#22222 Upgrade to Quarkus 3.2.3
  pom.xml
Labels: flaky-test

#22176 Test fixes for Operator on OpenShift
  operator/src/main/resources/example-db-secret.yaml
  operator/src/main/resources/example-postgres.yaml
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/PodTemplateTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
Labels: team/cloud-native

#22259 Add -DdeployTestsuite profile to testsuite
  testsuite/pom.xml
Labels: team/cloud-native, team/store, team/core

#21520 lazy populate the treeview for groups
  js/apps/admin-ui/src/groups/GroupTable.tsx
  js/apps/admin-ui/src/groups/GroupsSection.tsx
  js/apps/admin-ui/src/groups/Members.tsx
  js/apps/admin-ui/src/groups/components/GroupTree.tsx
  js/apps/admin-ui/src/groups/routes/Groups.tsx
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/GroupsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
  services/src/main/java/org/keycloak/utils/GroupUtils.java
Labels: team/ui, flaky-test

#22254 Changes to the time offset should be visible in all threads instantly
  common/src/main/java/org/keycloak/common/util/Time.java
Labels: flaky-test

#22244 Using DPoP token type in the access-token and as token_type in introspection response
  core/src/main/java/org/keycloak/TokenVerifier.java
  core/src/main/java/org/keycloak/util/TokenUtil.java
  services/src/main/java/org/keycloak/protocol/oidc/AccessTokenIntrospectionProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenRevocationEndpoint.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/DPoPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenIntrospectionTest.java
Labels: team/cloud-native, team/store, team/core

#22199 Prevent concurrent session cleanup on different instances in the cluster
  model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyDatastoreProviderFactory.java
Labels: team/store, flaky-test

#22298 Prevent concurrent session cleanup on different instances in the cluster
  model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyDatastoreProviderFactory.java
Labels: team/store

#22295 Add subgroups sorting
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/GroupAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/GroupEntity.java
  model/map/src/main/java/org/keycloak/models/map/group/MapGroupProvider.java
  server-spi/src/main/java/org/keycloak/models/GroupModel.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/group/GroupModelTest.java
Labels: team/store

#22265 Don't render fed link w/o view-realm access.
  js/apps/admin-ui/src/user/UserForm.tsx
Labels: team/ui

#21809 now uses save from edit user
  js/apps/admin-ui/src/user/EditUser.tsx
  js/apps/admin-ui/src/user/UserAttributes.tsx
Labels: team/ui

#21783 no longer use subgroup cache
  js/apps/admin-ui/src/groups/GroupAttributes.tsx
Labels: team/ui

#22219 added alias to view
  js/apps/admin-ui/src/authentication/components/FlowRow.tsx
  js/apps/admin-ui/src/authentication/components/FlowTitle.tsx
Labels: team/ui

#22247 keep config if it exists
  js/apps/admin-ui/src/authentication/FlowDetails.tsx
Labels: team/ui

#22269 added create option to multi select user profile
  js/apps/admin-ui/src/user/UserProfileFields.tsx
  js/apps/admin-ui/src/user/components/SelectComponent.tsx
Labels: team/ui

#22287 fix pagination
  js/apps/admin-ui/src/groups/components/GroupTree.tsx
Labels: team/ui

#22283 Fix facebook social login tests
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social/FacebookLoginPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java
Labels: team/cloud-native, team/store, team/core

#21554 only add realm access to the current realm
  js/apps/admin-ui/src/App.tsx
  js/apps/admin-ui/src/context/whoami/WhoAmI.tsx
  js/libs/keycloak-admin-client/src/resources/whoAmI.ts
  services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminConsolePermissionsCalculatedTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminSignatureAlgorithmTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#22203 removes the termination grace period override
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/K8sUtils.java
Labels: team/cloud-native

#22257 converts the keycloak services to dependent resources
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDiscoveryService.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDiscoveryServiceDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngress.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakServiceDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/ClusteringTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakServicesTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/RealmImportTest.java
Labels: team/cloud-native, flaky-test

#22155 adds the http service port if enabled
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngress.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakServiceDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
Labels: team/cloud-native

#22373 KEYCLOAK-21868
  model/jpa/src/main/java/org/keycloak/models/jpa/GroupAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/GroupEntity.java
Labels: team/store

#22361 added update email button
  js/apps/account-ui/public/locales/en/translation.json
  js/apps/account-ui/src/personal-info/FormField.tsx
Labels: team/ui

#22301 Update outdated message codes in Admin Console translations
  js/apps/admin-ui/public/locales/ca/dynamic.json
  js/apps/admin-ui/public/locales/ca/realm-settings.json
  js/apps/admin-ui/public/locales/de/realm-settings.json
  js/apps/admin-ui/public/locales/es/dynamic.json
  js/apps/admin-ui/public/locales/es/realm-settings.json
  js/apps/admin-ui/public/locales/fr/realm-settings.json
  js/apps/admin-ui/public/locales/ja/authentication.json
  js/apps/admin-ui/public/locales/ja/dynamic.json
  js/apps/admin-ui/public/locales/ja/realm-settings.json
  js/apps/admin-ui/public/locales/lt/authentication.json
  js/apps/admin-ui/public/locales/lt/dynamic.json
  js/apps/admin-ui/public/locales/lt/realm-settings.json
  js/apps/admin-ui/public/locales/no/authentication.json
  js/apps/admin-ui/public/locales/no/realm-settings.json
  js/apps/admin-ui/public/locales/pt-BR/authentication.json
  js/apps/admin-ui/public/locales/pt-BR/dynamic.json
  js/apps/admin-ui/public/locales/pt-BR/realm-settings.json
  js/apps/admin-ui/public/locales/ru/authentication.json
  js/apps/admin-ui/public/locales/ru/dynamic.json
  js/apps/admin-ui/public/locales/ru/realm-settings.json
  js/apps/admin-ui/public/locales/zh-CN/authentication.json
Labels: team/ui

#22326 Fixing how e-mail attribute permissions are set for both USER_API and ACCOUNT contexts
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/LegacyAttributes.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
Labels: team/cloud-native, team/store, team/core

#22393 Fixing how e-mail attribute permissions are set for both USER_API and ACCOUNT contexts
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/LegacyAttributes.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
Labels: team/core

#22314 Switch Trusted Host policy redirect verification to URI
  services/src/main/java/org/keycloak/services/ServicesLogger.java
  services/src/main/java/org/keycloak/services/clientregistration/policy/impl/TrustedHostClientRegistrationPolicy.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientRegistrationPoliciesTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#22376 Fix possible NullPointerException in core/JWKParser
  core/src/main/java/org/keycloak/jose/jwk/JWKParser.java
  core/src/test/java/org/keycloak/jose/jwk/JWKTest.java
Labels: team/core

#21496 Add Account Console E2E tests (Playwright) to CI
  .github/workflows/js-ci.yml
  js/apps/account-ui/package.json
  js/apps/account-ui/playwright.config.ts
  js/apps/account-ui/src/resources/ResourcesTab.tsx
  js/apps/account-ui/test/admin-client.ts
  js/apps/account-ui/test/auth.setup.ts
  js/apps/account-ui/test/login.ts
  js/apps/account-ui/test/my-resources.spec.ts
  js/apps/account-ui/test/personal-info.spec.ts
  js/apps/account-ui/test/test-realm.json
Labels: area/account/ui, kind/task, team/ui

#22406 Fix layout of tables in the new guides
  docs/guides/server/caching.adoc
  docs/guides/server/configuration-metrics.adoc
  docs/guides/server/configuration.adoc
  docs/guides/server/db.adoc
  docs/guides/server/health.adoc
  docs/guides/server/logging.adoc
  docs/guides/server/reverseproxy.adoc
Labels: team/cloud-native

#22310 also vertical align the spinner
  js/apps/admin-ui/src/components/keycloak-spinner/KeycloakSpinner.tsx
Labels: team/ui

#22341 lastname fistname swapped
  js/apps/admin-ui/public/locales/zh-CN/users.json
Labels: team/ui

#22333 added link for resource
  js/apps/admin-ui/src/clients/authorization/ResourcesPolicySelect.tsx
Labels: team/ui

#22456 Remove Vert.x Dev UI dependency
  quarkus/deployment/pom.xml
Labels: team/cloud-native

#22457 Remove JUnit dependencies from the distribution
  quarkus/deployment/pom.xml
Labels: team/cloud-native

#22458 Remove JUnit dependencies from the distribution
  quarkus/deployment/pom.xml
Labels: priority/important, team/cloud-native

#22297 added better rendering to account
  js/apps/account-ui/src/api/representations.ts
  js/apps/account-ui/src/personal-info/FormField.tsx
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
  js/apps/account-ui/src/personal-info/UserProfileFields.tsx
  js/apps/account-ui/src/personal-info/components/OptionsComponent.tsx
  js/apps/account-ui/src/personal-info/components/SelectComponent.tsx
  js/apps/account-ui/src/personal-info/components/TextAreaComponent.tsx
  js/apps/account-ui/src/personal-info/components/TextComponent.tsx
  js/apps/account-ui/src/personal-info/components/UserProfileGroup.tsx
  js/apps/account-ui/src/personal-info/utils.ts
  js/apps/account-ui/test/personal-info.spec.ts
  js/apps/admin-ui/src/user/UserProfileFields.tsx
  js/libs/ui-shared/src/main.ts
Labels: team/ui

#22440 removes logging full resources to omit secret data
  operator/src/main/java/org/keycloak/operator/controllers/OperatorManagedResource.java
Labels: team/cloud-native

#22466 Remove Vert.x Dev UI dependency
  quarkus/deployment/pom.xml
Labels: team/cloud-native

#22467 removes logging full resources to omit secret data
  operator/src/main/java/org/keycloak/operator/controllers/OperatorManagedResource.java
Labels: team/cloud-native

#22386 Upgrade to Infinispan 14.0.14
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/RemoteCacheProvider.java
  pom.xml
Labels: team/store

#22465 Update webauth4j to 0.21.5.RELEASE
  pom.xml
Labels: dependencies

#22485 Upgrade to Infinispan 14.0.14
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/RemoteCacheProvider.java
  pom.xml
Labels: team/store

#22346 Use Freemarker links between different guide pages
  docs/guides/server/configuration-provider.adoc
  docs/guides/server/fips.adoc
Labels: team/cloud-native

#22470 removing vertx-uri-template as a dependency
  operator/pom.xml
  quarkus/runtime/pom.xml
Labels: team/cloud-native

#22484 Remove Brotli dependencies from the distribution and operator
  operator/pom.xml
  quarkus/runtime/pom.xml
Labels: team/cloud-native, flaky-test

#22502 removing vertx-uri-template as a dependency
  operator/pom.xml
  quarkus/runtime/pom.xml
Labels: team/cloud-native

#22510 Remove Brotli dependencies from the distribution and operator
  operator/pom.xml
  quarkus/runtime/pom.xml
Labels: team/cloud-native

#22494 Fix IDELauncher after removing Vert.x Dev UI dependency
  quarkus/server/pom.xml
Labels: team/cloud-native, flaky-test

#22522 Fix IDELauncher after removing Vert.x Dev UI dependency
  quarkus/server/pom.xml
Labels: team/cloud-native

#22519 Fix mis-alignment of table and enforce checks on AsciiDoc during build
  docs/guides/pom.xml
  docs/guides/server/logging.adoc
Labels: team/cloud-native, flaky-test

#22559 Add label `updateEmail` to Arabic translation
  js/apps/account-ui/public/locales/ar/translation.json
Labels: team/ui

#22501 removing build time dependencies from the runtime
  operator/pom.xml
Labels: team/cloud-native, flaky-test

#22574 removing build time dependencies from the runtime
  operator/pom.xml
Labels: team/cloud-native

#22575 removing the quarkus-minikube dependency
  operator/README.md
  operator/pom.xml
  operator/src/main/kubernetes/kustomization.yml
  operator/src/main/kubernetes/minikube.yml
Labels: team/cloud-native

#22577 Remove Oracle Database JDBC driver from the Keycloak distribution
  docs/documentation/release_notes/topics/23_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
  docs/guides/server/db.adoc
  quarkus/runtime/pom.xml
  quarkus/runtime/src/main/resources/application.properties
  testsuite/integration-arquillian/servers/auth-server/quarkus/pom.xml
Labels: team/cloud-native, team/store, team/core

#22299 Converts realm import to dependent resources
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJob.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportSecret.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportSecretDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/OperatorManagedResource.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/realmimport/KeycloakRealmImport.java
Labels: team/cloud-native

#22396 Allow assign realm roles with query-users access.
  js/apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
Labels: team/ui

#22394 Allow view creds tab if view fine-grained permission
  js/apps/admin-ui/src/clients/ClientDetails.tsx
Labels: team/ui

#22221 converts the ingress logic to a conditional dependent resource
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngressDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/IngressLogicTest.java
Labels: team/cloud-native, flaky-test

#21708 Add Russian locale to the Account Console
  js/apps/account-ui/public/locales/ru/translation.json
Labels: team/ui

#22579 added null check for empty policies
  js/apps/admin-ui/src/clients/authorization/ResourcesPolicySelect.tsx
Labels: team/ui

#22073 Add Quarkus Unit tests to GHA CI
  .github/workflows/ci.yml
Labels: flaky-test

#22622 Ensures the CRDs are ready for use after installed
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
Labels: team/cloud-native

#22490 Use Freemarker links between different guide pages
  docs/guides/server/configuration-provider.adoc
  docs/guides/server/fips.adoc
Labels: team/cloud-native

#22639 Fix not-reported flaky tests
  .github/actions/upload-flaky-tests/action.yml
Labels: flaky-test

#22648 now uses save from edit user
  js/apps/admin-ui/src/user/EditUser.tsx
  js/apps/admin-ui/src/user/UserAttributes.tsx
Labels: team/ui

#22650 keep config if it exists
  js/apps/admin-ui/src/authentication/FlowDetails.tsx
Labels: team/ui

#22651 fixes the details page
  js/apps/admin-ui/src/identity-providers/add/DetailSettings.tsx
Labels: team/ui

#22655 no longer use subgroup cache
  js/apps/admin-ui/src/groups/GroupAttributes.tsx
Labels: team/ui

#22653 fix for validators that don't have config
  js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
Labels: team/ui

#22652 render components based on the annotations
  js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
  js/apps/admin-ui/src/user/UserProfileFields.tsx
  js/apps/admin-ui/src/user/components/OptionsComponent.tsx
  js/apps/admin-ui/src/user/components/SelectComponent.tsx
  js/apps/admin-ui/src/user/components/TextAreaComponent.tsx
  js/apps/admin-ui/src/user/components/TextComponent.tsx
  js/apps/admin-ui/src/user/components/UserProfileGroup.tsx
  js/apps/admin-ui/src/user/utils.ts
  js/libs/keycloak-admin-client/src/defs/userProfileConfig.ts
Labels: team/ui

#22656 lazy populate the treeview for groups
  js/apps/admin-ui/src/groups/GroupTable.tsx
  js/apps/admin-ui/src/groups/GroupsSection.tsx
  js/apps/admin-ui/src/groups/Members.tsx
  js/apps/admin-ui/src/groups/components/GroupTree.tsx
  js/apps/admin-ui/src/groups/routes/Groups.tsx
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/GroupsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
  services/src/main/java/org/keycloak/utils/GroupUtils.java
Labels: team/ui

#22664 Upgrade Prettier to the latest version
  js/apps/admin-ui/src/authentication/components/ExecutionConfigModal.tsx
  js/apps/admin-ui/src/authentication/form/CreateFlow.tsx
  js/apps/admin-ui/src/identity-providers/add/OpenIdConnectSettings.tsx
  js/package.json
  js/pnpm-lock.yaml
Labels: team/ui

#22672 Make base theme hidden for admin and account UIs.
  js/apps/admin-ui/cypress/e2e/realm_settings_tabs_test.spec.ts
  js/apps/admin-ui/src/realm-settings/ThemesTab.tsx
Labels: team/ui

#22693 Fixed removing attributes from a user
  js/apps/admin-ui/src/user/EditUser.tsx
Labels: team/ui

#22598 Remove Oracle Database JDBC driver from the Keycloak distribution
  docs/guides/server/db.adoc
  docs/guides/templates/profile.adoc
  quarkus/runtime/pom.xml
  quarkus/runtime/src/main/resources/application.properties
  testsuite/integration-arquillian/servers/auth-server/quarkus/pom.xml
Labels: priority/important, team/cloud-native, team/store, team/core, flaky-test

#22324 Update health.adoc to clarify the difference between the health endpoints
  docs/guides/server/health.adoc
Labels: team/cloud-native

#22616 Do not initialize barrier build items for deployment
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/ConfigBuildItem.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakSessionFactoryPreInitBuildItem.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/ProfileBuildItem.java
Labels: team/cloud-native

#22708 Fix cache option defaults in help
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
Labels: team/cloud-native, flaky-test

#22728 Make base theme hidden for admin and account UIs.
  js/apps/admin-ui/cypress/e2e/realm_settings_tabs_test.spec.ts
  js/apps/admin-ui/src/realm-settings/ThemesTab.tsx
Labels: team/ui

#22749 Fix cache option defaults in help (#22708)
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
Labels: team/cloud-native

#22761 Add missing translation for theme select placeholder text
  js/apps/admin-ui/public/locales/ca/realm-settings-help.json
  js/apps/admin-ui/public/locales/en/realm-settings-help.json
  js/apps/admin-ui/public/locales/en/realm-settings.json
  js/apps/admin-ui/public/locales/es/realm-settings-help.json
  js/apps/admin-ui/public/locales/fr/realm-settings-help.json
  js/apps/admin-ui/public/locales/ja/realm-settings-help.json
  js/apps/admin-ui/public/locales/lt/realm-settings-help.json
  js/apps/admin-ui/public/locales/no/realm-settings-help.json
  js/apps/admin-ui/public/locales/pt-BR/realm-settings-help.json
  js/apps/admin-ui/public/locales/ru/realm-settings-help.json
  js/apps/admin-ui/public/locales/zh-CN/realm-settings-help.json
  js/apps/admin-ui/src/realm-settings/ThemesTab.tsx
Labels: team/ui

#22673 Fixed remaining a11y violations for account console
  js/apps/account-ui/public/locales/en/translation.json
  js/apps/account-ui/public/locales/nl/translation.json
  js/apps/account-ui/src/account-security/SigningIn.tsx
  js/apps/account-ui/src/applications/Applications.tsx
Labels: team/ui

#22665 A11y fixes for Account UI
  js/apps/account-ui/public/locales/en/translation.json
  js/apps/account-ui/src/account-security/DeviceActivity.tsx
  js/apps/account-ui/src/groups/Groups.tsx
  js/apps/account-ui/src/resources/PermissionRequest.tsx
  js/apps/account-ui/src/resources/ResourcesTab.tsx
Labels: team/ui

#22624 Parsing response from user info rather than the access token
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerJWETest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#22782 Add missing translation for theme select placeholder text
  js/apps/admin-ui/public/locales/ca/realm-settings-help.json
  js/apps/admin-ui/public/locales/en/realm-settings-help.json
  js/apps/admin-ui/public/locales/en/realm-settings.json
  js/apps/admin-ui/public/locales/es/realm-settings-help.json
  js/apps/admin-ui/public/locales/fr/realm-settings-help.json
  js/apps/admin-ui/public/locales/ja/realm-settings-help.json
  js/apps/admin-ui/public/locales/lt/realm-settings-help.json
  js/apps/admin-ui/public/locales/no/realm-settings-help.json
  js/apps/admin-ui/public/locales/pt-BR/realm-settings-help.json
  js/apps/admin-ui/public/locales/ru/realm-settings-help.json
  js/apps/admin-ui/public/locales/zh-CN/realm-settings-help.json
  js/apps/admin-ui/src/realm-settings/ThemesTab.tsx
Labels: team/ui

#22531 22352 kerberos fallback
  common/src/main/java/org/keycloak/common/constants/KerberosConstants.java
  docs/documentation/release_notes/index.adoc
  docs/documentation/release_notes/topics/22_0_2.adoc
  federation/kerberos/src/main/java/org/keycloak/federation/kerberos/KerberosFederationProvider.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java
  server-spi/src/main/java/org/keycloak/models/CredentialValidationOutput.java
  server-spi/src/main/java/org/keycloak/models/UserCredentialModel.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/AbstractKerberosTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosLdapMultipleLDAPProvidersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosStandaloneMultipleProvidersTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#22089 French localization for account UI strings
  js/apps/account-ui/public/locales/fr/translation.json
Labels: area/translations, team/ui

#22781 added permission check around clipboard access
  js/apps/admin-ui/public/locales/en/clients.json
  js/apps/admin-ui/src/clients/scopes/CopyToClipboardButton.tsx
  js/apps/admin-ui/src/utils/useQueryPermission.ts
  js/apps/admin-ui/src/utils/useSetTimeout.ts
Labels: team/ui

#22766 Backports #22670
  js/apps/account-ui/public/locales/en/translation.json
  js/apps/account-ui/src/account-security/SigningIn.tsx
  js/apps/account-ui/src/applications/Applications.tsx
Labels: team/ui

#22788 Fallback to next LDAP/Kerberos provider when not able to find authent…
  common/src/main/java/org/keycloak/common/constants/KerberosConstants.java
  docs/documentation/release_notes/index.adoc
  docs/documentation/release_notes/topics/22_0_2.adoc
  federation/kerberos/src/main/java/org/keycloak/federation/kerberos/KerberosFederationProvider.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java
  server-spi/src/main/java/org/keycloak/models/CredentialValidationOutput.java
  server-spi/src/main/java/org/keycloak/models/UserCredentialModel.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/AbstractKerberosTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosLdapMultipleLDAPProvidersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosStandaloneMultipleProvidersTest.java
Labels: team/cloud-native, team/store, team/core

#22797 Add a Maven profile to remove GELF support
  docs/guides/server/logging.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/LoggingOptions.java
  quarkus/deployment/pom.xml
  quarkus/runtime/pom.xml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/tests/integration/pom.xml
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/GelfRemovedTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HelpCommandDistTest.java
  testsuite/integration-arquillian/servers/auth-server/quarkus/pom.xml
Labels: team/cloud-native, team/store, team/core

#22796 Bump Node.js and PNPM versions
  js/package.json
  js/pnpm-lock.yaml
  js/pnpm-workspace.yaml
  pom.xml
Labels: team/ui, flaky-test

#22451 use inputOptionsLabels when they exist
  js/apps/admin-ui/src/user/components/SelectComponent.tsx
Labels: team/ui

#22746 Upgrade to Quarkus 3.2.5.Final
  .github/workflows/operator-ci.yml
  pom.xml
Labels: flaky-test

#22813 Clean up Cypress configuration
  js/.gitignore
  js/apps/admin-ui/cypress.config.mjs
Labels: team/ui

#22816 Update logging properties for showing SQL statements and JDBC parameters
  testsuite/integration-arquillian/tests/base/src/test/resources/log4j.properties
  testsuite/model/src/test/resources/log4j.properties
  testsuite/utils/src/main/resources/log4j.properties
Labels: team/cloud-native, team/store, team/core

#22516 Use an original domain name of Kerberos Principal in UserModel attrib…
  common/src/main/java/org/keycloak/common/constants/KerberosConstants.java
  docs/documentation/release_notes/topics/22_0_2.adoc
  docs/documentation/server_admin/topics/authentication/kerberos.adoc
  federation/kerberos/src/main/java/org/keycloak/federation/kerberos/KerberosFederationProvider.java
  federation/kerberos/src/main/java/org/keycloak/federation/kerberos/KerberosPrincipal.java
  federation/kerberos/src/main/java/org/keycloak/federation/kerberos/impl/KerberosUsernamePasswordAuthenticator.java
  federation/kerberos/src/main/java/org/keycloak/federation/kerberos/impl/SPNEGOAuthenticator.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProviderFactory.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPUtils.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/kerberos/LDAPProviderKerberosConfig.java
  js/apps/admin-ui/public/locales/en/user-federation-help.json
  js/apps/admin-ui/public/locales/en/user-federation.json
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsGeneral.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/LDAPTestConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/AbstractKerberosTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosLdapCrossRealmTrustTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosLdapMultipleLDAPProvidersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosLdapTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosStandaloneCrossRealmTrustTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosStandaloneMultipleProvidersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosStandaloneTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KeycloakSPNegoSchemeFactory.java
  testsuite/integration-arquillian/tests/base/src/test/resources/kerberos/users-kerberos-kc2.ldif
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#22819 Use an original domain name of Kerberos Principal in UserModel attrib…
  common/src/main/java/org/keycloak/common/constants/KerberosConstants.java
  docs/documentation/release_notes/topics/22_0_2.adoc
  docs/documentation/server_admin/topics/authentication/kerberos.adoc
  federation/kerberos/src/main/java/org/keycloak/federation/kerberos/KerberosFederationProvider.java
  federation/kerberos/src/main/java/org/keycloak/federation/kerberos/KerberosPrincipal.java
  federation/kerberos/src/main/java/org/keycloak/federation/kerberos/impl/KerberosUsernamePasswordAuthenticator.java
  federation/kerberos/src/main/java/org/keycloak/federation/kerberos/impl/SPNEGOAuthenticator.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProviderFactory.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPUtils.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/kerberos/LDAPProviderKerberosConfig.java
  js/apps/admin-ui/public/locales/en/user-federation-help.json
  js/apps/admin-ui/public/locales/en/user-federation.json
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsGeneral.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/LDAPTestConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/AbstractKerberosTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosLdapCrossRealmTrustTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosLdapMultipleLDAPProvidersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosLdapTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosStandaloneCrossRealmTrustTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosStandaloneMultipleProvidersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosStandaloneTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KeycloakSPNegoSchemeFactory.java
  testsuite/integration-arquillian/tests/base/src/test/resources/kerberos/users-kerberos-kc2.ldif
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#22794 Remove log-level property for ClassTransformingBuildStep in Quarkus
  quarkus/runtime/src/main/resources/application.properties
Labels: team/cloud-native, flaky-test

#22828 removes direct operator installation for the product
  docs/guides/operator/installation.adoc
Labels: team/cloud-native

#22832 removes direct operator installation for the product
  docs/guides/operator/installation.adoc
Labels: team/cloud-native

#22834 removes quarkus-openshift since it's not being utilized
  operator/pom.xml
  operator/src/main/resources/application.properties
Labels: team/cloud-native, flaky-test

#22826 removed check as condition has pagination but it's disabled
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/authentication/FlowDetail.ts
Labels: team/ui

#22817 Added missing eventType mapping
  js/apps/admin-ui/public/locales/en/realm-settings.json
Labels: team/ui

#22576 user profile test
  .github/workflows/js-ci.yml
  js/apps/account-ui/playwright.config.ts
  js/apps/account-ui/test/admin-client.ts
  js/apps/account-ui/test/groups.spec.ts
  js/apps/account-ui/test/personal-info.spec.ts
  js/apps/account-ui/test/personal-info/personal-info.spec.ts
  js/apps/account-ui/test/personal-info/user-profile.json
  js/apps/account-ui/test/realm.setup.ts
  js/apps/account-ui/test/realm.teardown.ts
  js/apps/account-ui/test/realms/groups-realm.json
  js/apps/account-ui/test/realms/resources-realm.json
  js/apps/account-ui/test/realms/user-profile-realm.json
  js/apps/account-ui/test/test-realm.setup.ts
  js/apps/account-ui/test/test-realm.teardown.ts
  js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
  js/apps/admin-ui/src/user/components/UserProfileGroup.tsx
  js/libs/keycloak-admin-client/src/defs/userProfileConfig.ts
Labels: team/ui

#22820 Removes the bundle generator from the runtime
  operator/pom.xml
Labels: team/cloud-native, flaky-test

#22850 Backports #22709
  js/apps/admin-ui/public/locales/en/realm-settings.json
Labels: team/ui

#21915 GH Actions -> archive surefire reports (#21913).
  .github/actions/archive-surefire-reports/action.yml
  .github/workflows/ci.yml
Labels: area/testsuite, flaky-test, team/continuous-testing

#22858 GH Actions -> archive surefire reports (#21913). (#21915)
  .github/actions/archive-surefire-reports/action.yml
  .github/workflows/ci.yml
Labels: area/ci, team/continuous-testing

#22860 Removes the bundle generator from the runtime
  operator/pom.xml
Labels: team/cloud-native

#22861 Role mappers must return a single value when they are not multivalued
  docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractUserRoleMappingMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OIDCProtocolMappersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ProtocolMapperUtil.java
Labels: team/cloud-native, team/store, team/core, flaky-test
