Repository keycloak/keycloak, pull requests merged in 2023-09, with the labels that each got.

#22873 Use screenshot showing fast
  docs/guides/images/configure-operator.jpeg
  docs/guides/images/configure-operator.png
  docs/guides/operator/installation.adoc
Labels: team/cloud-native

#22404 allows normal reconciliation to continue even if secrets are not present
  operator/src/main/java/org/keycloak/operator/Constants.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/controllers/WatchedSecretsController.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
Labels: team/cloud-native, flaky-test

#22883 Use screenshot showing fast
  docs/guides/images/configure-operator.jpeg
  docs/guides/images/configure-operator.png
  docs/guides/operator/installation.adoc
Labels: team/cloud-native

#22743 Avoid direct access to executor to record worker pool metrics
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakRecorder.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java
Labels: team/cloud-native, flaky-test

#22869 Clarification on the tooltip of option 'Validate Password Policy' of …
  js/apps/admin-ui/public/locales/en/user-federation-help.json
Labels: team/ui

#22822 Remove log-level property for ClassTransformingBuildStep in Quarkus
  quarkus/runtime/src/main/resources/application.properties
Labels: team/cloud-native, flaky-test

#22887 Upgrade to Infinispan 14.0.15.Final
  pom.xml
Labels: flaky-test

#22771 Update Redirect URI when Alias changed
  js/apps/admin-ui/src/identity-providers/add/AddOpenIdConnect.tsx
  js/apps/admin-ui/src/identity-providers/add/AddSamlConnect.tsx
  js/apps/admin-ui/src/identity-providers/add/DetailSettings.tsx
  js/apps/admin-ui/src/identity-providers/add/OIDCGeneralSettings.tsx
  js/apps/admin-ui/src/identity-providers/add/SamlGeneralSettings.tsx
Labels: team/ui

#22851 Centralize user form to user representation conversion
  js/apps/admin-ui/src/user/CreateUser.tsx
  js/apps/admin-ui/src/user/EditUser.tsx
  js/apps/admin-ui/src/user/UserAttributes.tsx
  js/apps/admin-ui/src/user/UserForm.tsx
  js/apps/admin-ui/src/user/form-state.ts
Labels: area/admin/ui, team/ui

#22925 Centralize user form to user representation conversion
  js/apps/admin-ui/src/user/CreateUser.tsx
  js/apps/admin-ui/src/user/EditUser.tsx
  js/apps/admin-ui/src/user/UserAttributes.tsx
  js/apps/admin-ui/src/user/UserForm.tsx
  js/apps/admin-ui/src/user/form-state.ts
Labels: team/ui

#22929 Add correct translation key for temporary password reset help text
  js/apps/admin-ui/src/user/user-credentials/ResetPasswordDialog.tsx
Labels: team/ui

#22933 Add correct translation key for temporary password reset help text
  js/apps/admin-ui/src/user/user-credentials/ResetPasswordDialog.tsx
Labels: team/ui

#22934 Error message when JDBC driver is missing is not helpful
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/CheckJdbcBuildStep.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/BuildCommandDistTest.java
Labels: team/cloud-native, flaky-test

#22889 Allow archive surefire reports for release branches also when a test suite fails.
  .github/workflows/ci.yml
Labels: flaky-test

#22946 Update configuration for Maven resolver
  .github/workflows/ci.yml
Labels: flaky-test

#22948 Status check should fail if "conditional" step fails
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/documentation.yml
  .github/workflows/guides.yml
  .github/workflows/js-ci.yml
  .github/workflows/operator-ci.yml
Labels: flaky-test

#22975 Upgrade to Infinispan 14.0.16
  pom.xml
Labels: flaky-test

#22699 add `stringify` for custom idp
  js/apps/admin-ui/src/components/multi-line-input/MultiLineInput.tsx
  js/apps/admin-ui/src/identity-providers/add/AddIdentityProvider.tsx
  js/apps/admin-ui/src/identity-providers/add/DetailSettings.tsx
Labels: team/ui

#22879 Update Catalan translation
  themes/src/main/resources-community/theme/base/account/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ca.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_ca.properties
Labels: flaky-test

#22990 Adds failing remote operator logs to the main test log
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
Labels: team/cloud-native, flaky-test

#22972 Status check should fail if "conditional" step fails (#22948)
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/documentation.yml
  .github/workflows/guides.yml
  .github/workflows/js-ci.yml
  .github/workflows/operator-ci.yml
Labels: flaky-test

#23007 Disable ZeroDowntimeTest
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/zerodowntime/ZeroDowntimeTest.java
Labels: team/cloud-native, team/store, team/core

#22980 Add a new identity provider for LinkedIn based on OIDC
  core/src/main/java/org/keycloak/util/JWKSUtils.java
  docs/documentation/server_admin/images/linked-in-add-identity-provider.png
  docs/documentation/server_admin/topics/identity-broker/social/linked-in.adoc
  docs/documentation/upgrading/topics/keycloak/changes-22_0_2.adoc
  js/apps/admin-ui/public/locales/en/identity-providers-help.json
  js/apps/admin-ui/public/locales/en/identity-providers.json
  js/apps/admin-ui/src/identity-providers/add/ExtendedNonDiscoverySettings.tsx
  js/libs/ui-shared/src/icons/IconMapper.tsx
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProviderConfig.java
  services/src/main/java/org/keycloak/broker/oidc/mappers/UsernameTemplateMapper.java
  services/src/main/java/org/keycloak/social/linkedin/LinkedInIdentityProvider.java
  services/src/main/java/org/keycloak/social/linkedin/LinkedInIdentityProviderFactory.java
  services/src/main/java/org/keycloak/social/linkedin/LinkedInOIDCIdentityProvider.java
  services/src/main/java/org/keycloak/social/linkedin/LinkedInOIDCIdentityProviderFactory.java
  services/src/main/java/org/keycloak/social/linkedin/LinkedInPublicKeyLoader.java
  services/src/main/java/org/keycloak/social/linkedin/LinkedInUserAttributeMapper.java
  services/src/main/resources/META-INF/services/org.keycloak.broker.social.SocialIdentityProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerNonceParameterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#23006 Return Oracle JDBC driver to the upstream
  docs/documentation/release_notes/topics/23_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
  docs/guides/server/db.adoc
  quarkus/runtime/pom.xml
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/BuildCommandDistTest.java
  testsuite/integration-arquillian/servers/auth-server/quarkus/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#23021 Clean LDAP between test method executions
  testsuite/model/src/test/java/org/keycloak/testsuite/model/user/UserSyncTest.java
Labels: team/store

#23016 Remove org.jetbrains:annotations:jar from server distribution. (#23015)
  pom.xml
Labels: flaky-test

#23010 Remove use of Guava in services
  common/src/main/java/org/keycloak/common/util/SecretGenerator.java
  federation/sssd/src/main/java/org/keycloak/federation/sssd/SSSDFederationProviderFactory.java
  server-spi/src/main/java/org/keycloak/utils/StringUtil.java
  services/src/main/java/org/keycloak/authentication/AuthenticatorUtil.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCWellKnownProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/CibaClientValidation.java
  services/src/main/java/org/keycloak/protocol/saml/DefaultSamlArtifactResolver.java
  services/src/main/java/org/keycloak/services/clientregistration/oidc/DescriptionConverter.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProviderResource.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java
Labels: flaky-test

#22790 Decoupling legacy and dynamic user profiles and exposing metadata from admin api
  core/src/main/java/org/keycloak/representations/account/UserRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/UserProfileAttributeMetadata.java
  core/src/main/java/org/keycloak/representations/idm/UserProfileMetadata.java
  core/src/main/java/org/keycloak/representations/idm/UserRepresentation.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/UserResource.java
  js/apps/admin-ui/src/authentication/policies/OtpPolicy.tsx
  js/apps/admin-ui/src/realm-settings/EmailTab.tsx
  js/apps/admin-ui/src/user/EditUser.tsx
  js/apps/admin-ui/src/user/UserForm.tsx
  js/apps/admin-ui/src/user/UserProfileFields.tsx
  js/apps/admin-ui/src/user/components/OptionsComponent.tsx
  js/apps/admin-ui/src/user/components/SelectComponent.tsx
  js/apps/admin-ui/src/user/components/TextAreaComponent.tsx
  js/apps/admin-ui/src/user/components/TextComponent.tsx
  js/apps/admin-ui/src/user/utils.ts
  js/libs/keycloak-admin-client/src/defs/userProfileConfig.ts
  js/libs/keycloak-admin-client/src/defs/userRepresentation.ts
  js/libs/keycloak-admin-client/src/resources/users.ts
  server-spi-private/src/main/java/org/keycloak/userprofile/Attributes.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultUserProfile.java
  services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpReviewProfileAuthenticator.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateEmail.java
  services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/LegacyAttributes.java
  services/src/main/java/org/keycloak/userprofile/validator/ImmutableAttributeValidator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AbstractRequiredActionUpdateEmailTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/DeclarativeUserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTestWithUserProfile.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#23020 Update dependencies to enable Maven also-make working for Quarkus
  docs/maven-plugin/pom.xml
  quarkus/dist/pom.xml
Labels: team/cloud-native, flaky-test

#22986 Remove MS SQL JDBC driver from the Keycloak product
  docs/guides/server/db.adoc
  pom.xml
  quarkus/runtime/pom.xml
  quarkus/tests/integration/pom.xml
  quarkus/tests/junit5/pom.xml
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
  testsuite/integration-arquillian/servers/auth-server/quarkus/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#23040 Add a new identity provider for LinkedIn based on OIDC
  core/src/main/java/org/keycloak/util/JWKSUtils.java
  docs/documentation/server_admin/images/linked-in-add-identity-provider.png
  docs/documentation/server_admin/topics/identity-broker/social/linked-in.adoc
  docs/documentation/upgrading/topics/keycloak/changes-22_0_2.adoc
  js/apps/admin-ui/public/locales/en/identity-providers-help.json
  js/apps/admin-ui/public/locales/en/identity-providers.json
  js/apps/admin-ui/src/identity-providers/add/ExtendedNonDiscoverySettings.tsx
  js/libs/ui-shared/src/icons/IconMapper.tsx
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProviderConfig.java
  services/src/main/java/org/keycloak/broker/oidc/mappers/UsernameTemplateMapper.java
  services/src/main/java/org/keycloak/social/linkedin/LinkedInIdentityProvider.java
  services/src/main/java/org/keycloak/social/linkedin/LinkedInIdentityProviderFactory.java
  services/src/main/java/org/keycloak/social/linkedin/LinkedInOIDCIdentityProvider.java
  services/src/main/java/org/keycloak/social/linkedin/LinkedInOIDCIdentityProviderFactory.java
  services/src/main/java/org/keycloak/social/linkedin/LinkedInPublicKeyLoader.java
  services/src/main/java/org/keycloak/social/linkedin/LinkedInUserAttributeMapper.java
  services/src/main/resources/META-INF/services/org.keycloak.broker.social.SocialIdentityProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerNonceParameterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#23035 Broker claim mapper not recognizing claims from user info endpoint
  services/src/main/java/org/keycloak/broker/oidc/mappers/AbstractClaimMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/BrokerLinkAndTokenExchangeTest.java
Labels: team/cloud-native, team/store, team/core

#23064 Registration flow fixed
  server-spi-private/src/main/java/org/keycloak/authentication/FormContext.java
  server-spi-private/src/main/java/org/keycloak/events/Errors.java
  services/src/main/java/org/keycloak/authentication/forms/RegistrationUserCreation.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
Labels: team/cloud-native, team/store, team/core

#23060 Remove MS SQL JDBC driver from the Keycloak product
  docs/guides/server/db.adoc
  pom.xml
  quarkus/runtime/pom.xml
  quarkus/tests/integration/pom.xml
  quarkus/tests/junit5/pom.xml
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
  testsuite/integration-arquillian/servers/auth-server/quarkus/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#23081 Add old LinkedIn provider to the deprecated profile
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
  docs/documentation/upgrading/topics/keycloak/changes-22_0_2.adoc
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
  services/src/main/java/org/keycloak/social/linkedin/LinkedInIdentityProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/partialimport/PartialImportTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23079 Registration flow fixed (#23064)
  server-spi-private/src/main/java/org/keycloak/authentication/FormContext.java
  server-spi-private/src/main/java/org/keycloak/events/Errors.java
  services/src/main/java/org/keycloak/authentication/forms/RegistrationUserCreation.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23093 Fix for Not-working link during adding a SAML Identity provider #22892
  js/apps/admin-ui/src/identity-providers/add/SamlGeneralSettings.tsx
Labels: team/ui

#22968 Attributes without a value set are not rendered in the account console
  themes/src/main/resources/theme/keycloak.v2/account/src/app/content/account-page/AccountPage.tsx
Labels: team/ui, flaky-test

#23097 Upgrade to Infinispan 14.0.17
  pom.xml
Labels: flaky-test

#23084 Quarkus IT that use Oracle DB don't work with -Dproduct
  quarkus/tests/integration/pom.xml
  quarkus/tests/junit5/pom.xml
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
Labels: team/cloud-native, flaky-test

#23088 Quarkus IT that use Oracle DB don't work with -Dproduct
  quarkus/tests/integration/pom.xml
  quarkus/tests/junit5/pom.xml
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
Labels: team/cloud-native, flaky-test

#23103 Attributes without a value set are not rendered in the account console
  themes/src/main/resources/theme/keycloak.v2/account/src/app/content/account-page/AccountPage.tsx
Labels: team/ui, flaky-test

#23091 Broker claim mapper not recognizing claims from user info endpoint
  services/src/main/java/org/keycloak/broker/oidc/mappers/AbstractClaimMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/BrokerLinkAndTokenExchangeTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23109 Fix for Keycloak 22.0.1 unable to create user with long email address
  docs/documentation/upgrading/topics/keycloak/changes-22_0_2.adoc
  server-spi-private/src/main/java/org/keycloak/utils/EmailValidationUtil.java
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  services/src/test/java/org/keycloak/test/ValidationTest.java
  testsuite/integration-arquillian/servers/auth-server/quarkus/src/main/content/conf/keycloak.conf
Labels: team/cloud-native, team/store, team/core, flaky-test

#23126 Fix lint errorin identity_providers_test.spec.ts
  js/apps/admin-ui/cypress/e2e/identity_providers_test.spec.ts
Labels: team/ui

#23133 Refactor tests to use new LinkedIn provider
  .github/workflows/js-ci.yml
  js/apps/admin-ui/cypress/e2e/identity_providers_test.spec.ts
Labels: area/admin/ui, team/ui

#22970 Do not store empty attributes when updating user profile
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultUserProfile.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateProfileWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: status/hold, team/cloud-native, team/store, team/core, flaky-test

#22971 fixed ip address filter
  js/apps/admin-ui/src/events/EventsSection.tsx
Labels: team/ui

#23136 Typo corrected
  js/apps/admin-ui/public/locales/de/translation.json
Labels: area/translations, area/admin/ui, team/ui

#22480 Print 'key' in ReadOnlyAttributeUnchangedValidator failure log message
  services/src/main/java/org/keycloak/userprofile/validator/ReadOnlyAttributeUnchangedValidator.java
Labels: flaky-test

#23105 Marking wildfly-common with compile scope
  pom.xml
Labels: flaky-test

#23143 Enable ZeroDowntimeTest
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/zerodowntime/ZeroDowntimeTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23148 Remove bearer-only occurences in the documentation when possible. Mak…
  docs/documentation/server_admin/topics/clients/client-policies.adoc
  docs/documentation/server_admin/topics/clients/oidc/con-audience.adoc
  js/apps/admin-ui/public/locales/en/translation.json
  services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientAccessTypeConditionFactory.java
Labels: team/ui, flaky-test

#23072 Corrects log truncation and adds the database to logging
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
Labels: team/cloud-native

#23086 add stringify to MultiLineInput
  js/apps/admin-ui/src/components/dynamic/MultivaluedListComponent.tsx
Labels: team/ui

#23005 added more profile tests
  js/apps/account-ui/playwright.config.ts
  js/apps/account-ui/src/personal-info/components/UserProfileGroup.tsx
  js/apps/account-ui/test/admin-client.ts
  js/apps/account-ui/test/personal-info/personal-info.spec.ts
  js/apps/account-ui/test/realms/user-profile-realm.json
Labels: team/ui

#23025 Show expiration for certificates in Keys List in admin-ui (#17743)
  core/src/main/java/org/keycloak/representations/idm/KeysMetadataRepresentation.java
  js/apps/admin-ui/public/locales/en/translation.json
  js/apps/admin-ui/src/realm-settings/keys/KeysListTab.tsx
  js/libs/keycloak-admin-client/src/defs/keyMetadataRepresentation.ts
  services/src/main/java/org/keycloak/services/resources/admin/KeyResource.java
Labels: team/ui, flaky-test

#23059 Fix typo in en/identity-providers.json
  js/apps/admin-ui/public/locales/en/translation.json
Labels: team/ui

#21440 Handle ignored artifacts separately
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/IgnoredArtifacts.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ClassLoaderPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/IgnoredArtifactsTest.java
Labels: team/cloud-native, team/store, flaky-test

#22641 better features overview
  common/src/main/java/org/keycloak/common/Profile.java
  core/src/main/java/org/keycloak/representations/info/FeatureRepresentation.java
  core/src/main/java/org/keycloak/representations/info/ServerInfoRepresentation.java
  js/apps/admin-ui/src/dashboard/Dashboard.tsx
  js/apps/admin-ui/src/utils/useIsFeatureEnabled.ts
  js/libs/keycloak-admin-client/src/defs/featureRepresentation.ts
  js/libs/keycloak-admin-client/src/defs/serverInfoRepesentation.ts
  services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java
Labels: team/ui, flaky-test

#23140 Introduce a workaround for liquibase bug to allow use database schema…
  model/jpa/src/main/java/org/keycloak/connections/jpa/DefaultJpaConnectionProviderFactory.java
  model/jpa/src/main/java/org/keycloak/connections/jpa/util/JpaUtils.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapStorageProviderFactory.java
  model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapUtils.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/AbstractJpaConnectionProviderFactory.java
Labels: team/cloud-native, team/store, flaky-test

#23142 Fix syntax error and make minifying the theme possible
  themes/src/main/resources/theme/base/login/login-recovery-authn-code-config.ftl
Labels: flaky-test

#23117 FullNameLDAPStoreMapper removes values for other attributes
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/FullNameLDAPStorageMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPProvidersFullNameMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPTestAsserts.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23164 Remove bearer-only occurences in the documentation when possible. Mak…
  docs/documentation/server_admin/topics/clients/client-policies.adoc
  docs/documentation/server_admin/topics/clients/oidc/con-audience.adoc
  services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientAccessTypeConditionFactory.java
Labels: flaky-test

#23169 Add regex support in 'Condition - User attribute' execution
  services/src/main/java/org/keycloak/authentication/authenticators/conditional/ConditionalUserAttributeValue.java
  services/src/main/java/org/keycloak/authentication/authenticators/conditional/ConditionalUserAttributeValueFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/AllowDenyAuthenticatorTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23163 Add caret to regex expressions in federation-sssd-setup.sh to avoid comments
  .github/scripts/run-ipa-tests.sh
  quarkus/dist/src/main/content/bin/federation-sssd-setup.sh
Labels: team/cloud-native, flaky-test

#22504 Added missing hungarian translations, fix typos
  themes/src/main/resources-community/theme/base/account/messages/messages_hu.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_hu.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_hu.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_hu.properties
Labels: flaky-test

#23132 Fix for Keycloak 22.0.1 unable to create user with long email address
  docs/documentation/upgrading/topics/keycloak/changes-22_0_2.adoc
  docs/documentation/upgrading/topics/keycloak/changes-22_0_4.adoc
  docs/documentation/upgrading/topics/keycloak/changes.adoc
  server-spi-private/src/main/java/org/keycloak/utils/EmailValidationUtil.java
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  services/src/test/java/org/keycloak/test/ValidationTest.java
  testsuite/integration-arquillian/servers/auth-server/quarkus/src/main/content/conf/keycloak.conf
Labels: team/cloud-native, team/store, team/core, flaky-test

#20894 Fix valid redirect URIs for built-in account-console client on realm rename
  model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyExportImportManager.java
  model/map/src/main/java/org/keycloak/models/map/datastore/MapExportImportManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#22011 Fix infinite recursive loop causing application freeze
  adapters/spi/jakarta-servlet-adapter-spi/src/main/java/org/keycloak/adapters/servlet/FilterSessionStore.java
Labels: flaky-test

#22848 Support to define compatible mappers for (new) Identity Providers
  server-spi-private/src/main/java/org/keycloak/broker/provider/AbstractIdentityProvider.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/IdentityProvider.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProviderResource.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/broker/oidc/OverwrittenMappersTestIdentityProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/broker/oidc/OverwrittenMappersTestIdentityProviderFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/resources/META-INF/services/org.keycloak.broker.provider.IdentityProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23039 fix user profile form saving
  js/apps/admin-ui/src/user/EditUser.tsx
Labels: team/ui

#23215 Fix ldap:// with STARTTLS
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPContextManager.java
Labels: flaky-test

#23184 Ignore attributes when they are not prefixed with user.attributes prefix
  docs/documentation/release_notes/topics/22_0_3.adoc
  services/src/main/java/org/keycloak/userprofile/LegacyAttributes.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23181 Fix for Not-working link during adding a SAML Identity provider
  js/apps/admin-ui/src/identity-providers/add/SamlGeneralSettings.tsx
Labels: team/ui

#21523 Send Client ID in token request with JWT Authentication
  services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/broker/oidc/ClientIdRequiredJWTClientAuthenticator.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/resources/META-INF/services/org.keycloak.authentication.ClientAuthenticatorFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/ProvidersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerPrivateKeyJwtClientIdRequiredTest.java
Labels: team/cloud-native, team/store, status/triage, team/core, team/ui, flaky-test

#23050 Make Keycloak.updateToken minValidity parameter optional
  js/libs/keycloak-js/dist/keycloak.d.ts
Labels: team/ui

#23212 Registration page not showing username when edit username is not enabled
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
Labels: team/cloud-native, team/store, team/core

#23234 Fix ldap:// with STARTTLS
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPContextManager.java
Labels: flaky-test

#23165 i18n: Add Thai language
  themes/src/main/resources-community/theme/base/account/messages/messages_th.properties
  themes/src/main/resources-community/theme/base/account/theme.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_th.properties
  themes/src/main/resources-community/theme/base/email/theme.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_th.properties
  themes/src/main/resources-community/theme/base/login/theme.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_th.properties
  themes/src/main/resources/theme/base/account/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: area/translations, flaky-test

#22068 [Login UI] Toggle visibility of password input fields in login-ftl-based pages
  docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterWithUserProfileTest.java
  themes/src/main/resources/theme/base/login/login-password.ftl
  themes/src/main/resources/theme/base/login/login-update-password.ftl
  themes/src/main/resources/theme/base/login/login.ftl
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/register-user-profile.ftl
  themes/src/main/resources/theme/base/login/register.ftl
  themes/src/main/resources/theme/base/login/resources/js/passwordVisibility.js
  themes/src/main/resources/theme/keycloak/login/resources/css/login.css
  themes/src/main/resources/theme/keycloak/login/theme.properties
Labels: team/cloud-native, team/store, team/core, flaky-test

#23244 Registration page not showing username when edit username is not enabled
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
Labels: team/cloud-native, team/store, team/core

#23008 Add new version of Welcome theme based on PatternFly 5
  .github/dependabot.yml
  .github/workflows/js-ci.yml
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HostnameDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ProxyDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testDefaultToHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testHelpShort.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.windows.approved.txt
  server-spi/src/main/java/org/keycloak/theme/ThemeSelectorProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ServerInfoTest.java
  themes/pom.xml
  themes/src/main/resources/META-INF/keycloak-themes.json
  themes/src/main/resources/theme/keycloak.v2/welcome/.gitignore
  themes/src/main/resources/theme/keycloak.v2/welcome/index.ftl
  themes/src/main/resources/theme/keycloak.v2/welcome/package-lock.json
  themes/src/main/resources/theme/keycloak.v2/welcome/package.json
  themes/src/main/resources/theme/keycloak.v2/welcome/theme.properties
Labels: team/core, team/ui, area/welcome/ui

#23260 Race condition inside Keycloak build chain execution
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/CryptoProviderInitBuildItem.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
Labels: team/cloud-native

#23254 CLI args not recognized when running Quarkus dev mode
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/ConfigArgsConfigSource.java
Labels: team/cloud-native

#23247 Improve documentation about manual database migration
  docs/documentation/upgrading/topics/migrate_db.adoc
Labels: team/store

#23279 Race condition inside Keycloak build chain execution
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/CryptoProviderInitBuildItem.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
Labels: team/cloud-native

#23282 Upgrade to Quarkus 3.2.6
  pom.xml
Labels: flaky-test

#23281 Upgrade to Quarkus 3.2.6
  pom.xml
Labels: flaky-test

#8679 KEYCLOAK-15985 Add Brute Force Detection Lockout Event
  server-spi-private/src/main/java/org/keycloak/events/EventType.java
  services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AssertEvents.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#23264 Remove legacy code which isn't used anymore and was deprecated for some time
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java
  model/legacy-services/src/main/java/org/keycloak/credential/UserCredentialStoreManager.java
  model/legacy-services/src/main/java/org/keycloak/services/legacysessionsupport/LegacySessionSupportProviderFactory.java
  model/legacy-services/src/main/java/org/keycloak/services/legacysessionsupport/LegacySessionSupportProviderFactoryImpl.java
  model/legacy-services/src/main/java/org/keycloak/services/legacysessionsupport/LegacySessionSupportProviderImpl.java
  model/legacy-services/src/main/java/org/keycloak/services/legacysessionsupport/LegacySessionSupportSpi.java
  model/legacy-services/src/main/resources/META-INF/services/org.keycloak.provider.Spi
  model/legacy-services/src/main/resources/META-INF/services/org.keycloak.services.legacysessionsupport.LegacySessionSupportProviderFactory
  model/legacy/src/main/java/org/keycloak/models/LegacySessionSupportProvider.java
  model/legacy/src/main/java/org/keycloak/models/UserCredentialManager.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/Infinispan.java
Labels: team/store, flaky-test

#23313 Prevent NPE in AuthenticationManager.backchannelLogout (#23306)
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
Labels: flaky-test

#22979 Fixes login flow in Microsoft social login test
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social/MicrosoftLoginPage.java
Labels: area/testsuite, team/cloud-native, team/store, team/core, flaky-test, team/continuous-testing

#23284 Keystore location does not work for Windows
  .github/workflows/ci.yml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ConfigKeystorePropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
Labels: team/cloud-native, flaky-test

#23232 Allow duplicated keys in advanced claim mappers
  server-spi/src/main/java/org/keycloak/models/IdentityProviderMapperModel.java
  services/src/main/java/org/keycloak/broker/oidc/mappers/AdvancedClaimToGroupMapper.java
  services/src/main/java/org/keycloak/broker/oidc/mappers/AdvancedClaimToRoleMapper.java
  services/src/main/java/org/keycloak/broker/oidc/mappers/ClaimToUserSessionNoteMapper.java
  services/src/main/java/org/keycloak/broker/saml/mappers/AdvancedAttributeToGroupMapper.java
  services/src/main/java/org/keycloak/broker/saml/mappers/AdvancedAttributeToRoleMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractAdvancedRoleMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractGroupBrokerMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlAdvancedAttributeToGroupMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlAdvancedAttributeToRoleMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/OidcClaimToUserSessionNoteMapperTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23350 Remove `P3P` header from authentication flow
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/IframeUtil.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/util/P3PHelper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LoginStatusIframeEndpointTest.java
Labels: team/core, flaky-test

#22488 moved keycloak to context so it can be updated
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
  js/apps/account-ui/src/root/Root.tsx
  js/libs/keycloak-masthead/src/KeycloakContext.tsx
  js/libs/keycloak-masthead/src/Masthead.tsx
  js/libs/keycloak-masthead/src/main.ts
  js/libs/keycloak-masthead/src/util.ts
Labels: team/ui

#23353 Account-UI login test failing
  js/apps/account-ui/test/login.ts
Labels: team/ui

#23359 Remove old RESTEasy Classic configuration property
  quarkus/runtime/src/main/resources/application.properties
Labels: team/cloud-native, flaky-test

#22821 ensures support for cluster-wide monitoring
  .github/workflows/operator-ci.yml
  operator/scripts/check-examples-installed.sh
  operator/scripts/create-olm-test-resources.sh
  operator/scripts/install-keycloak-operator.sh
  operator/scripts/olm-testing.sh
  operator/scripts/prepare-olm-test.sh
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportController.java
  operator/src/main/java/org/keycloak/operator/controllers/WatchedSecretsController.java
  operator/src/main/resources/application.properties
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/resources/example-db-secret.yaml
  operator/src/test/resources/example-keycloak.yaml
  operator/src/test/resources/example-postgres.yaml
  operator/src/test/resources/example-realm.yaml
  operator/src/test/resources/example-tls-secret.yaml
Labels: team/cloud-native

#23371 Fixes help texts for HelpItem in Admin-UI
  js/apps/admin-ui/public/locales/en/translation.json
  js/apps/admin-ui/src/authentication/components/modals/AddSubFlowModal.tsx
  js/apps/admin-ui/src/authentication/policies/PolicyRow.tsx
  js/apps/admin-ui/src/authentication/policies/WebauthnPolicy.tsx
  js/apps/admin-ui/src/client-scopes/details/MappingDetails.tsx
  js/apps/admin-ui/src/clients/add/SamlConfig.tsx
  js/apps/admin-ui/src/clients/advanced/TokenLifespan.tsx
  js/apps/admin-ui/src/clients/authorization/PermissionDetails.tsx
  js/apps/admin-ui/src/clients/authorization/ResourceDetails.tsx
  js/apps/admin-ui/src/clients/authorization/ScopeDetails.tsx
  js/apps/admin-ui/src/clients/authorization/policy/Client.tsx
  js/apps/admin-ui/src/clients/authorization/policy/JavaScript.tsx
  js/apps/admin-ui/src/clients/authorization/policy/NameDescription.tsx
  js/apps/admin-ui/src/clients/authorization/policy/Time.tsx
  js/apps/admin-ui/src/clients/credentials/Credentials.tsx
  js/apps/admin-ui/src/clients/credentials/SignedJWT.tsx
  js/apps/admin-ui/src/clients/keys/SamlKeys.tsx
  js/apps/admin-ui/src/clients/registration/DetailProvider.tsx
  js/apps/admin-ui/src/realm-settings/ClientProfileForm.tsx
  js/apps/admin-ui/src/realm-settings/LoginTab.tsx
  js/apps/admin-ui/src/realm-settings/NewClientPolicyCondition.tsx
  js/apps/admin-ui/src/realm-settings/SessionsTab.tsx
  js/apps/admin-ui/src/realm-settings/TokensTab.tsx
  js/apps/admin-ui/src/realm-settings/event-config/EventConfigForm.tsx
  js/apps/admin-ui/src/realm-settings/event-config/EventListenersForm.tsx
  js/apps/admin-ui/src/realm-settings/security-defences/BruteForceDetection.tsx
  js/apps/admin-ui/src/realm-settings/security-defences/HelpLinkTextInput.tsx
  js/apps/admin-ui/src/realm-settings/security-defences/Time.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesGroupForm.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributePermission.tsx
  js/apps/admin-ui/src/user-federation/custom/CustomProviderSettings.tsx
  js/apps/admin-ui/src/user-federation/custom/SyncSettings.tsx
  js/apps/admin-ui/src/user-federation/kerberos/KerberosSettingsRequired.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsAdvanced.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsConnection.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsGeneral.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsSearching.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsSynchronization.tsx
  js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx
  js/apps/admin-ui/src/user-federation/shared/SettingsCache.tsx
  js/apps/admin-ui/src/user/UserCredentials.tsx
  js/apps/admin-ui/src/user/UserForm.tsx
Labels: team/ui

#23203 Ensure that the EncryptedKey is passed to the DecryptionKeyLocator for SAML
  js/apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx
  saml-core/src/main/java/org/keycloak/saml/processing/core/util/XMLEncryptionUtil.java
  services/src/main/java/org/keycloak/protocol/saml/SAMLDecryptionKeysLocator.java
  services/src/test/java/org/keycloak/protocol/saml/SamlEncryptionTest.java
Labels: team/core, team/ui, flaky-test

#8430 KEYCLOAK-19230 Calling getTopLevelGroups is slow inside GroupLDAPStorageMapper#getLDAPGroupMappingsConverted
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapper.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapperFactory.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheManager.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/GroupNameQuery.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/events/GroupMovedEvent.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/events/GroupRemovedEvent.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/events/GroupUpdatedEvent.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/stream/InGroupPredicate.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/wildfly/InGroupPredicateWFExternalizer.java
  model/infinispan/src/main/resources/META-INF/services/org.wildfly.clustering.marshalling.Externalizer
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/GroupEntity.java
  model/legacy-private/src/main/java/org/keycloak/storage/GroupStorageManager.java
  model/map/src/main/java/org/keycloak/models/map/group/MapGroupProvider.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  server-spi/src/main/java/org/keycloak/storage/group/GroupLookupProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/HardcodedGroupStorageProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/group/GroupModelTest.java
Labels: impact/medium, area/ldap, team/cloud-native, team/store, team/core, flaky-test

#23387 Set headers before calling sendError() method
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/PolicyEnforcer.java
Labels: flaky-test

#23391 Disable CockroachDB model tests since they are flaky
  testsuite/model/pom.xml
Labels: team/store, flaky-test

#23375 Call correct SAML key download API
  js/apps/admin-ui/src/clients/keys/ExportSamlKeyDialog.tsx
  js/apps/admin-ui/src/clients/keys/SamlKeys.tsx
Labels: team/ui

#23339 Update FIPS 140-2 documentation to clarify default keystore format
  docs/guides/server/fips.adoc
Labels: team/cloud-native

#23354 verifyRedirectUri should return null when the passed redirectUri is invalid
  services/src/main/java/org/keycloak/protocol/oidc/utils/RedirectUtils.java
  services/src/test/java/org/keycloak/protocol/oidc/utils/RedirectUtilsTest.java
Labels: flaky-test

#23395 Align wildfly-core and wildfly version for tests
  pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#23422 Call correct SAML key download API
  js/apps/admin-ui/src/clients/keys/ExportSamlKeyDialog.tsx
  js/apps/admin-ui/src/clients/keys/SamlKeys.tsx
Labels: team/ui

#23347 Ignoring link for stackapps registration
  docs/documentation/tests/src/test/resources/ignored-links
Labels: flaky-test

#23423 moved keycloak to context so it can be updated
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
  js/apps/account-ui/src/root/Root.tsx
  js/libs/keycloak-masthead/src/KeycloakContext.tsx
  js/libs/keycloak-masthead/src/Masthead.tsx
  js/libs/keycloak-masthead/src/main.ts
  js/libs/keycloak-masthead/src/util.ts
Labels: team/ui

#23426 add `stringify` for custom idp
  js/apps/admin-ui/src/components/multi-line-input/MultiLineInput.tsx
  js/apps/admin-ui/src/identity-providers/add/AddIdentityProvider.tsx
  js/apps/admin-ui/src/identity-providers/add/DetailSettings.tsx
Labels: team/ui

#23430 fixed ip address filter
  js/apps/admin-ui/src/events/EventsSection.tsx
Labels: team/ui

#23403 Outdated kcadm.sh help examples can be misleading to our users
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractAuthOptionsCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AddRolesCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/ConfigCredentialsCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/CreateCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/DeleteCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/GetCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/GetRolesCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/KcAdmCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/RemoveRolesCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/SetPasswordCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/UpdateCmd.java
  integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/commands/AbstractAuthOptionsCmd.java
  integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/commands/ConfigCredentialsCmd.java
  integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/commands/ConfigInitialTokenCmd.java
  integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/commands/ConfigRegistrationTokenCmd.java
  integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/commands/KcRegCmd.java
Labels: team/cloud-native, team/core, flaky-test

#23324 adds a default domain on openshift if one is not specified
  docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
  docs/guides/operator/basic-deployment.adoc
  operator/pom.xml
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/controllers/WatchedSecretsController.java
  operator/src/main/kubernetes/kubernetes.yml
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/KeycloakControllerTest.java
Labels: team/cloud-native, flaky-test

#23429 better features overview
  common/src/main/java/org/keycloak/common/Profile.java
  core/src/main/java/org/keycloak/representations/info/FeatureRepresentation.java
  core/src/main/java/org/keycloak/representations/info/ServerInfoRepresentation.java
  js/apps/admin-ui/src/dashboard/Dashboard.tsx
  js/apps/admin-ui/src/utils/useIsFeatureEnabled.ts
  js/libs/keycloak-admin-client/src/defs/featureRepresentation.ts
  js/libs/keycloak-admin-client/src/defs/serverInfoRepesentation.ts
  services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java
Labels: team/ui

#23432 Remove `@types/flat` from dependencies
  js/apps/admin-ui/package.json
  js/pnpm-lock.yaml
Labels: team/ui

#23436 [Backport] Outdated kcadm.sh help examples can be misleading to our users
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractAuthOptionsCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AddRolesCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/ConfigCredentialsCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/CreateCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/DeleteCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/GetCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/GetRolesCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/KcAdmCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/RemoveRolesCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/SetPasswordCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/UpdateCmd.java
  integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/commands/AbstractAuthOptionsCmd.java
  integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/commands/ConfigCredentialsCmd.java
  integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/commands/ConfigInitialTokenCmd.java
  integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/commands/ConfigRegistrationTokenCmd.java
  integration/client-cli/client-registration-cli/src/main/java/org/keycloak/client/registration/cli/commands/KcRegCmd.java
Labels: team/cloud-native

#23419 Align wildfly-core and wildfly version for tests
  pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#23416 Disable CockroachDB model tests since they are flaky
  testsuite/model/pom.xml
Labels: team/store

#23446 Revert the new welcome screen experience
  .github/dependabot.yml
  .github/workflows/js-ci.yml
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HostnameDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ProxyDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testDefaultToHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testHelpShort.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.windows.approved.txt
  server-spi/src/main/java/org/keycloak/theme/ThemeSelectorProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ServerInfoTest.java
  themes/pom.xml
  themes/src/main/resources/META-INF/keycloak-themes.json
  themes/src/main/resources/theme/keycloak.v2/welcome/.gitignore
  themes/src/main/resources/theme/keycloak.v2/welcome/index.ftl
  themes/src/main/resources/theme/keycloak.v2/welcome/package-lock.json
  themes/src/main/resources/theme/keycloak.v2/welcome/package.json
  themes/src/main/resources/theme/keycloak.v2/welcome/theme.properties
Labels: team/cloud-native, team/store, team/core

#23451 Update FIPS 140-2 documentation to clarify default keystore format
  docs/guides/server/fips.adoc
Labels: team/cloud-native

#22429 Reuse already fixed code to fetch offline user
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java
Labels: team/store, flaky-test

#23461 Fix minor typo in "Configuring Keycloak" docs page
  docs/guides/server/configuration.adoc
Labels: team/cloud-native

#23467 Add 'consent' prompt option to KeycloakLoginOptions
  js/libs/keycloak-js/dist/keycloak.d.ts
Labels: team/ui

#23406 Set search as case-insensitive for authentication steps
  js/apps/admin-ui/src/authentication/components/modals/AddStepModal.tsx
Labels: team/ui

#23472 Apply type migration for i18next on Account Console
  js/apps/account-ui/public/locales/en/translation.json
  js/apps/account-ui/public/locales/fr/translation.json
  js/apps/account-ui/public/locales/nl/translation.json
  js/apps/account-ui/public/locales/ru/translation.json
  js/apps/account-ui/src/account-security/DeviceActivity.tsx
  js/apps/account-ui/src/account-security/SigningIn.tsx
  js/apps/account-ui/src/applications/Applications.tsx
  js/apps/account-ui/src/i18n.ts
  js/apps/account-ui/src/resources/EditTheResource.tsx
  js/apps/account-ui/src/resources/PermissionRequest.tsx
  js/apps/account-ui/src/resources/ShareTheResource.tsx
Labels: team/ui

#23452 Fix issue with groups search not sending the search input in the request
  js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx
Labels: team/ui

#22439 narrows condition status to a string
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/StatusCondition.java
Labels: team/cloud-native

#23484 Fixed creating user
  js/apps/admin-ui/src/user/CreateUser.tsx
  js/apps/admin-ui/src/user/UserForm.tsx
Labels: team/ui

#23250 changed to validators
  js/apps/admin-ui/src/user/components/OptionsComponent.tsx
  js/apps/admin-ui/src/user/components/SelectComponent.tsx
  js/apps/admin-ui/src/user/components/UserProfileGroup.tsx
  js/libs/keycloak-admin-client/src/defs/userProfileConfig.ts
Labels: team/ui

#23478 fix userform lastname input can not get focus
  js/apps/admin-ui/src/user/UserForm.tsx
Labels: team/ui

#23418 Use new findGroupByPath implementation and remove the old one
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/HardcodedLDAPGroupStorageMapper.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/HardcodedLDAPGroupStorageMapperFactory.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapper.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapperFactory.java
  federation/sssd/src/main/java/org/keycloak/federation/sssd/SSSDFederationProvider.java
  model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyExportImportManager.java
  model/map/src/main/java/org/keycloak/models/map/datastore/MapExportImportManager.java
  server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/DefaultEvaluation.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  services/src/main/java/org/keycloak/broker/oidc/mappers/AbstractClaimToGroupMapper.java
  services/src/main/java/org/keycloak/broker/saml/mappers/AbstractAttributeToGroupMapper.java
  services/src/main/java/org/keycloak/partialimport/GroupsPartialImport.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/resource/TestLDAPResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/FineGrainAdminUnitTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapper2WaySyncTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperSyncTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperSyncWithGroupsPathTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPSpecialCharsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPSyncTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/group/GroupModelTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23504 Backport (#23484)
  js/apps/admin-ui/src/user/CreateUser.tsx
  js/apps/admin-ui/src/user/UserForm.tsx
Labels: team/ui

#23505 fix userform lastname input can not get focus
  js/apps/admin-ui/src/user/UserForm.tsx
Labels: team/ui

#23448 fix userform lastname can not get focus and zh-CN CONSENSUS trans
  js/apps/admin-ui/public/locales/zh-CN/translation.json
Labels: area/translations, team/ui

#23466 Fix minor typo in "Configuring Keycloak" docs page
  docs/guides/server/configuration.adoc
Labels: team/cloud-native

#23492 Allow updating email when email as username is set and edit username disabed
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/LegacyAttributes.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTestWithUserProfile.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23369 fix: Adding client to logout event. Should fix #21236
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AssertEvents.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/DemoServletsAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientRedirectTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LegacyLogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthGrantTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RPInitiatedLogoutTest.java
  testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnIdlessTest.java
  testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnRegisterAndLoginTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23488 Add missing additions/modifications to Arabic labels
  js/apps/account-ui/public/locales/ar/translation.json
  themes/src/main/resources-community/theme/base/login/messages/messages_ar.properties
Labels: team/ui, flaky-test

#23384 Set JVM FlightRecorderOptions to capture full stacks depth
  quarkus/dist/src/main/content/bin/kc.bat
  quarkus/dist/src/main/content/bin/kc.sh
Labels: team/cloud-native

#23483 Change email checkserveridentity prop as angus mail sets it to true by default
  services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java
  services/src/main/java/org/keycloak/truststore/FileTruststoreProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/client/resources/TestingResource.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/updaters/RealmAttributeUpdater.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/ssl/TrustStoreEmailTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23468 Ensure that the EncryptedKey is passed to the DecryptionKeyLocator for SAML
  js/apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx
  saml-core/src/main/java/org/keycloak/saml/processing/core/util/XMLEncryptionUtil.java
  services/src/main/java/org/keycloak/protocol/saml/SAMLDecryptionKeysLocator.java
  services/src/test/java/org/keycloak/protocol/saml/SamlEncryptionTest.java
Labels: team/ui, flaky-test

#23514 Allow updating email when email as username is set and edit username disabled
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  services/src/main/java/org/keycloak/userprofile/AbstractUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/LegacyAttributes.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTestWithUserProfile.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23512 Attach js-adapter to maven uploads and rewrite version to semver compatible if needed
  js/libs/keycloak-js/pom.xml
  set-version.sh
Labels: team/ui, flaky-test

#23553 Client roles should be mapped to any claim name
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractUserRoleMappingMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OIDCProtocolMappersTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23293 Add createTimestamp to REST service
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#23393 Always check storage access before placing test cookie
  js/libs/keycloak-js/src/keycloak.js
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step1.html
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step2.html
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/login-status-iframe.html
Labels: team/ui

#23555 Attach js-adapter to maven uploads and rewrite version to semver compatible if needed (#23512)
  js/libs/keycloak-js/pom.xml
  set-version.sh
Labels: team/ui, flaky-test
