Repository keycloak/keycloak, pull requests merged in 2024-04, with the labels that each got.

#28278 Align isEnabled in MSAD mappers to how other properties are processed…
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProviderFactory.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/msad/MSADUserAccountControlStorageMapper.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/msad/MSADUserAccountControlStorageMapperFactory.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/msadlds/MSADLDSUserAccountControlStorageMapper.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/msadlds/MSADLDSUserAccountControlStorageMapperFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPMSADMapperTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28281 fix: providing a direct reference to close
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/CreateSessionHandler.java
Labels: team/cloud-native, flaky-test

#28243 New default client scope for 'basic' claims with 'auth_time' protocol mapper
  docs/documentation/server_admin/topics/clients/con-protocol-mappers.adoc
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo25_0_0.java
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultMigrationManager.java
  server-spi-private/src/main/java/org/keycloak/migration/MigrationProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/AccessTokenIntrospectionProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/OIDCAttributeMapperHelper.java
  services/src/main/java/org/keycloak/services/migration/DefaultMigrationProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport1903MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport198MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport255MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport343MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport483MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport903MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCWellKnownProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/migration-test/migration-realm-19.0.3.json
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27876 SAMLIdentityProvider not honoring SamlAuthenticationPreprocessor (keycloak/keycloak#27875)
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java
Labels: missing/tests

#28342 fixed change calculation
  js/apps/admin-ui/src/authentication/execution-model.ts
Labels: team/ui

#24537 Move all JavaScript projects into single PNPM workspace
  .github/CODEOWNERS
  .github/actions/pnpm-setup/action.yml
  .github/dependabot.yml
  .github/workflows/js-ci.yml
  .gitignore
  adapters/oidc/js/pom.xml
  js/.gitignore
  js/apps/account-ui/pom.xml
  js/apps/admin-ui/README.md
  js/apps/admin-ui/pom.xml
  js/apps/keycloak-server/.gitignore
  js/apps/keycloak-server/README.md
  js/libs/keycloak-admin-client/README.md
  js/libs/keycloak-admin-client/package.json
  js/libs/keycloak-admin-client/pom.xml
  js/libs/keycloak-js/package.json
  js/libs/keycloak-js/pom.xml
  js/pnpm-workspace.yaml
  js/pom.xml
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  pom.xml
  themes/UPDATING-NODE-MODULES.md
  themes/pom.xml
  themes/src/main/resources/theme/keycloak/common/resources/package.json
  themes/src/main/resources/theme/keycloak/common/resources/pnpm-lock.yaml
Labels: status/hold, team/ui

#28225 fix: moving / removing validations out of property mapper transformations
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/InitializationException.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Messages.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ExecutionExceptionHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractStartCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/QuarkusPlatform.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/IgnoredArtifactsTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/BuildCommandDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/OptionsDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
Labels: team/cloud-native, flaky-test

#28257 Fix help key for firstBrokerLoginFlowAliasOverrideHelp
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_lt.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_no.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_pl.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_pt_BR.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ru.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_CN.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#28373 fix: correcting test assertions
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
Labels: team/cloud-native

#28375 Fix source highlighting for log output
  docs/guides/server/logging.adoc
Labels: team/cloud-native

#28344 filter out parent group if it doesn't match
  js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx
Labels: team/ui

#28266 Remove deleted roles from policy on evaluation & update (#26915)
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/admin/RolePolicyManagementTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28223 Changes the contract to make it simpler and rely on the realm available from the current session
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProviderFactory.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/OrganizationAdapter.java
  server-spi-private/src/main/java/org/keycloak/organization/OrganizationProvider.java
  server-spi/src/main/java/org/keycloak/models/OrganizationModel.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationMemberResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/OrganizationMembershipMapper.java
Labels: flaky-test

#28205 Present effective sync mode value
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmCreateTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28399 Make the UI team owner of the `themes` directory
  .github/CODEOWNERS
Labels: kind/task

#28414 Fix broken Cypress tests
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts
  js/apps/admin-ui/src/identity-providers/add/AdvancedSettings.tsx
Labels: kind/task, team/ui

#22118 Update method for sending identity broker link confirmation
  services/src/main/java/org/keycloak/email/freemarker/FreeMarkerEmailTemplateProvider.java
Labels: flaky-test

#28407 :bug: Fix unclosed span bracket in register.ftl
  themes/src/main/resources/theme/keycloak.v2/login/register.ftl
Labels: team/ui

#28349 Fix navigation with realms with special chars
  js/apps/admin-ui/cypress/e2e/realm_test.spec.ts
  js/apps/admin-ui/src/PageNav.tsx
  js/apps/admin-ui/src/context/realm-context/RealmContext.tsx
Labels: team/ui

#27793 Handle 'You are already logged in' for expired authentication sessions
  js/libs/keycloak-js/src/keycloak.js
  saml-core/src/main/java/org/keycloak/saml/SAML2ErrorResponseBuilder.java
  saml-core/src/main/java/org/keycloak/saml/processing/core/saml/v2/writers/SAMLResponseWriter.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/IdentityProvider.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/util/IdentityBrokerState.java
  server-spi-private/src/main/java/org/keycloak/events/Details.java
  server-spi-private/src/main/java/org/keycloak/events/Errors.java
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  server-spi-private/src/main/java/org/keycloak/protocol/ClientData.java
  server-spi-private/src/main/java/org/keycloak/protocol/LoginProtocol.java
  server-spi-private/src/test/java/org/keycloak/broker/provider/util/IdentityBrokerStateTest.java
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
  services/src/main/java/org/keycloak/authentication/FormAuthenticationFlow.java
  services/src/main/java/org/keycloak/authentication/RequiredActionContextResult.java
  services/src/main/java/org/keycloak/authentication/actiontoken/ActionTokenContext.java
  services/src/main/java/org/keycloak/authentication/actiontoken/execactions/ExecuteActionsActionTokenHandler.java
  services/src/main/java/org/keycloak/authentication/actiontoken/idpverifyemail/IdpVerifyAccountLinkActionTokenHandler.java
  services/src/main/java/org/keycloak/authentication/actiontoken/verifyemail/VerifyEmailActionTokenHandler.java
  services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpEmailVerificationAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/IdentityProviderAuthenticator.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateEmail.java
  services/src/main/java/org/keycloak/authentication/requiredactions/VerifyEmail.java
  services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
  services/src/main/java/org/keycloak/broker/oidc/KeycloakOIDCIdentityProvider.java
  services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/forms/login/freemarker/model/UrlBean.java
  services/src/main/java/org/keycloak/protocol/docker/DockerAuthV2Protocol.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthorizationEndpointRequest.java
  services/src/main/java/org/keycloak/protocol/saml/SamlProtocol.java
  services/src/main/java/org/keycloak/services/Urls.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  services/src/main/java/org/keycloak/services/resources/LogoutSessionCodeChecks.java
  services/src/main/java/org/keycloak/services/resources/SessionCodeChecks.java
  services/src/main/java/org/keycloak/services/util/AuthenticationFlowURLHelper.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/updaters/RealmAttributeUpdater.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractFirstBrokerLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcMultipleTabsBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlBrokerConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlBrokerDestinationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlBrokerFrontendUrlTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlMultipleTabsBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultipleTabsLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RestartCookieTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#28294 Allow empty key use in JWKS for client authentication
  services/src/main/java/org/keycloak/keys/loader/ClientPublicKeyLoader.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/broker/oidc/MissingUseJwksRealmResourceProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/broker/oidc/MissingUseJwksRealmResourceProviderFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/broker/oidc/MissingUseJwksRestResource.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/resources/META-INF/services/org.keycloak.services.resource.RealmResourceProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerPrivateKeyJwtMissingUseTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28378 Fix lists to be rendered as expected
  docs/guides/server/importExport.adoc
Labels: team/cloud-native

#28293 Use realm default signature algorithm for id_token_signed_response_alg
  services/src/main/java/org/keycloak/services/clientregistration/oidc/DescriptionConverter.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OIDCClientRegistrationDefaultSignatureTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OIDCClientRegistrationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28433 Filter dedicated client scopes when searching
  js/apps/admin-ui/cypress/e2e/clients_test.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_roles_test.spec.ts
  js/apps/admin-ui/cypress/e2e/user_fed_ldap_mapper_test.spec.ts
  js/apps/admin-ui/cypress/e2e/users_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/ListingPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/components/TablePage.ts
  js/apps/admin-ui/src/clients/scopes/ClientScopes.tsx
Labels: team/ui

#28310 fix: removes default values from cache stack option
  quarkus/README.md
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HelpCommandDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#28437 JAVA_OPTS are not set under Windows
  quarkus/dist/src/main/content/bin/kc.bat
Labels: team/cloud-native

#28317 Fix the client's authorization setting import error
  docs/documentation/release_notes/topics/25_0_0.adoc
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/admin/ResourceServerManagementTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/client-with-authz-settings.json
Labels: team/cloud-native, team/core-clients, team/core-iam

#28464 Convert realms settings general tab to new form controls
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
  js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
Labels: kind/task, team/ui

#28406 Truncate the clientId
  js/apps/admin-ui/cypress/support/pages/admin-ui/ListingPage.ts
  js/apps/admin-ui/src/clients/ClientsSection.tsx
Labels: team/ui

#28442 Fix NotContainsUsernamePasswordPolicyProvider: reversed check
  server-spi-private/src/main/java/org/keycloak/policy/NotContainsUsernamePasswordPolicyProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28353 Support for searching users based on search filter, enabled attribute, first, max
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/UsersResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28354 Remove 'session_state' from tokens
  core/src/main/java/org/keycloak/representations/IDToken.java
  core/src/main/java/org/keycloak/representations/RefreshToken.java
  docs/documentation/server_admin/topics/clients/con-protocol-mappers.adoc
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  js/apps/admin-ui/cypress/e2e/clients_test.spec.ts
  js/libs/keycloak-js/src/keycloak.js
  services/src/main/java/org/keycloak/authorization/authorization/AuthorizationTokenService.java
  services/src/main/java/org/keycloak/protocol/oidc/AccessTokenIntrospectionProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ClientCredentialsGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/SessionStateMapper.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/resources/META-INF/services/org.keycloak.protocol.ProtocolMapper
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenIntrospectionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#24577 Better management of the CSP header
  server-spi-private/src/main/java/org/keycloak/models/ContentSecurityPolicyBuilder.java
  server-spi-private/src/test/java/org/keycloak/models/BrowserSecurityHeadersTest.java
  services/src/main/java/org/keycloak/headers/DefaultSecurityHeadersProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/FrontChannelLogoutHandler.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/updaters/ClientAttributeUpdater.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/updaters/RealmAttributeUpdater.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RPInitiatedFrontChannelLogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RPInitiatedLogoutTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, team/core-shared

#28494 Skip unsupported keys in JWKS
  core/src/main/java/org/keycloak/util/JWKSUtils.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/broker/oidc/UnsupportedKeyJwksRealmResourceProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/broker/oidc/UnsupportedKeyJwksRealmResourceProviderFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/broker/oidc/UnsupportedKeyJwksRestResource.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/resources/META-INF/services/org.keycloak.services.resource.RealmResourceProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerPrivateKeyJwtUnsupportedKeyTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28455 Make sure attribute metadata from user storage providers are added only for the provider associated with a federated user
  docs/documentation/upgrading/topics/changes/changes-24_0_3.adoc
  docs/documentation/upgrading/topics/changes/changes.adoc
  federation/kerberos/src/main/java/org/keycloak/federation/kerberos/KerberosFederationProvider.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  federation/sssd/src/main/java/org/keycloak/federation/sssd/SSSDFederationProvider.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java
  model/storage-private/src/main/java/org/keycloak/storage/UserStorageManager.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  server-spi-private/src/main/java/org/keycloak/userprofile/UserProfileUtil.java
  server-spi/src/main/java/org/keycloak/userprofile/UserProfileDecorator.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/util/LDAPTestUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPAccountRestApiTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPTestContext.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/ldap/users.ldif
  testsuite/integration-arquillian/tests/other/sssd/src/test/java/org/keycloak/testsuite/sssd/SSSDUserProfileTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28504 added unique message for key provider name
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/keys/key-providers/KeyProviderForm.tsx
Labels: team/ui

#28173 use subGroupCount to render subGroups
  js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx
Labels: team/ui

#28462 Enable Syslog log handler
  docs/documentation/release_notes/topics/25_0_0.adoc
  docs/guides/server/logging.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/LoggingOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ManagementConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#27009 Added ClientType implementation from Marek's prototype
  core/src/main/java/org/keycloak/representations/idm/ClientRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/ClientTypeRepresentation.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/ClientTypesResource.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/RealmResource.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  server-spi-private/src/main/java/org/keycloak/client/clienttype/ClientTypeSpi.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  server-spi/src/main/java/org/keycloak/models/ClientModel.java
  services/src/main/java/org/keycloak/services/clienttype/DefaultClientTypeManager.java
  services/src/main/java/org/keycloak/services/clienttype/client/TypeAwareClientModelDelegate.java
  services/src/main/java/org/keycloak/services/clienttype/impl/DefaultClientType.java
  services/src/main/java/org/keycloak/services/managers/ClientManager.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientTypesResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  services/src/main/resources/keycloak-default-client-types.json
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientTypesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ClientBuilder.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28347 Allow `false` to be set for `pkceMethod` option
  js/libs/keycloak-js/src/keycloak.js
Labels: team/ui

#26345 Hostname SPI v2
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/main/java/org/keycloak/common/profile/PropertiesProfileConfigResolver.java
  docs/guides/server/hostname.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/HostnameV1Options.java
  quarkus/config-api/src/main/java/org/keycloak/config/HostnameV2Options.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionBuilder.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionCategory.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Help.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/OptionRenderer.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ShortErrorMessageHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractExportImportCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KcUnmatchedArgumentException.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnamePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV1PropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/ConstantsDebugHostname.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java
  quarkus/runtime/src/main/resources/theme-resources/templates/debug-hostname-settings.ftl
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HostnameV1DistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HostnameV2DistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ProxyHostnameV1DistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ProxyHostnameV2DistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  server-spi/src/main/java/org/keycloak/utils/StringUtil.java
  services/src/main/java/org/keycloak/url/DefaultHostnameProvider.java
  services/src/main/java/org/keycloak/url/DefaultHostnameProviderFactory.java
  services/src/main/java/org/keycloak/url/FixedHostnameProvider.java
  services/src/main/java/org/keycloak/url/FixedHostnameProviderFactory.java
  services/src/main/java/org/keycloak/url/HostnameV2Provider.java
  services/src/main/java/org/keycloak/url/HostnameV2ProviderFactory.java
  services/src/main/java/org/keycloak/url/RequestHostnameProvider.java
  services/src/main/java/org/keycloak/url/RequestHostnameProviderFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.urls.HostnameProviderFactory
  testsuite/integration-arquillian/servers/auth-server/quarkus/src/main/content/conf/keycloak.conf
  testsuite/integration-arquillian/servers/auth-server/undertow/src/main/java/org/keycloak/testsuite/arquillian/undertow/KeycloakOnUndertow.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakContainerFeaturesController.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusEmbeddedDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/RemoteContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/WelcomePage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UmaDiscoveryDocumentTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/url/AbstractHostnameTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/url/DefaultHostnameTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/url/FixedHostnameTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/url/HostnameV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/resources/META-INF/keycloak-server.json
  testsuite/utils/src/main/resources/META-INF/keycloak-server.json
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28537 fix: changing max threads default
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native

#28467 Set SameSite for all cookies
  docs/documentation/release_notes/topics/25_0_0.adoc
  server-spi-private/src/main/java/org/keycloak/cookie/CookieScope.java
  server-spi-private/src/main/java/org/keycloak/cookie/CookieType.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cookies/DefaultCookieProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28544 Remove messages for Account Console v2
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_ar.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_ca.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_cs.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_da.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_de.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_el.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_es.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_fa.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_fr.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_hu.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_it.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_ja.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_lt.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_nl.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_no.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_pl.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_pt.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_ru.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_sk.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_sv.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_th.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_tr.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_zh_CN.properties
Labels: kind/task, team/ui

#28179 Provide histograms for http server metrics
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  docs/guides/server/configuration-metrics.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/metrics/HistogramMeterFilter.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/MetricsDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native

#28532 Migrate ESLint to 'flat' configuration
  js/.eslintrc.cjs
  js/CODING_GUIDELINES.md
  js/README.md
  js/apps/account-ui/package.json
  js/apps/admin-ui/package.json
  js/eslint.config.js
  js/libs/keycloak-admin-client/.eslintignore
  js/libs/keycloak-admin-client/package.json
  js/libs/keycloak-masthead/package.json
  js/libs/ui-shared/package.json
  js/tsconfig.eslint.json
  package.json
  pnpm-lock.yaml
Labels: kind/task, team/ui

#28213 docs: Support management port for health and metrics
  docs/documentation/release_notes/topics/25_0_0.adoc
  docs/documentation/tests/src/test/resources/ignored-links
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  docs/guides/operator/advanced-configuration.adoc
  docs/guides/server/configuration-metrics.adoc
  docs/guides/server/health.adoc
  docs/guides/server/management-interface.adoc
  docs/guides/server/pinned-guides
Labels: team/cloud-native, flaky-test

#28481 Update flow diagram to support branching edges for conditionals
  js/apps/admin-ui/src/authentication/components/FlowDiagram.tsx
  js/apps/admin-ui/src/authentication/components/diagram/ButtonEdge.tsx
  js/apps/admin-ui/src/authentication/components/diagram/auto-layout.ts
Labels: team/ui

#28556 Fixed searchClientRegistration message text
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/registration/ClientRegistrationList.tsx
Labels: team/ui

#28560 Added helpText for importFileHelp
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#28411 task: use simple display names for config sources
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/PropertyMapperParameterConsumer.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KcEnvConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakConfigSourceProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakPropertiesConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/BuildCommandDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/PostgreSQLDistTest.java
Labels: team/cloud-native, flaky-test

#28530 Redirect error to client right-away when browser tab detects that ano…
  server-spi-private/src/main/java/org/keycloak/cookie/CookieType.java
  services/src/main/java/org/keycloak/forms/login/freemarker/AuthenticationStateCookie.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationSessionManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AssertEvents.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cookies/DefaultCookieProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultipleTabsLoginTest.java
  themes/src/main/resources/theme/base/login/resources/js/authChecker.js
  themes/src/main/resources/theme/base/login/template.ftl
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#28588 Add VS Code configuration for ESlint
  .vscode/settings.json
Labels: kind/task

#28557 Exclude `groovy` artifact from testsuite to avoid version collision
  testsuite/integration-arquillian/tests/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28224 Remove legacy Account Console tests
  .github/CODEOWNERS
  testsuite/integration-arquillian/HOW-TO-RUN.md
  testsuite/integration-arquillian/README.md
  testsuite/integration-arquillian/tests/other/base-ui/pom.xml
  testsuite/integration-arquillian/tests/other/base-ui/src/main/java/org/keycloak/testsuite/ui/account3/page/ApplicationsPage.java
  testsuite/integration-arquillian/tests/other/base-ui/src/main/java/org/keycloak/testsuite/ui/account3/page/DeviceActivityPage.java
  testsuite/integration-arquillian/tests/other/base-ui/src/main/java/org/keycloak/testsuite/ui/account3/page/LinkedAccountsPage.java
  testsuite/integration-arquillian/tests/other/base-ui/src/main/java/org/keycloak/testsuite/ui/account3/page/MyResourcesPage.java
  testsuite/integration-arquillian/tests/other/base-ui/src/main/java/org/keycloak/testsuite/ui/account3/page/PageNotFound.java
  testsuite/integration-arquillian/tests/other/base-ui/src/main/java/org/keycloak/testsuite/ui/account3/page/PersonalInfoPage.java
  testsuite/integration-arquillian/tests/other/base-ui/src/main/java/org/keycloak/testsuite/ui/account3/page/WelcomeScreen.java
  testsuite/integration-arquillian/tests/other/base-ui/src/main/java/org/keycloak/testsuite/ui/account3/page/fragment/AbstractFragmentWithMobileLayout.java
  testsuite/integration-arquillian/tests/other/base-ui/src/main/java/org/keycloak/testsuite/ui/account3/page/fragment/WelcomeScreenHeader.java
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme-preview/account/messages/messages_en.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme-preview/account/messages/messages_test.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme-preview/account/theme.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme/account/messages/messages_en.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme/account/messages/messages_test.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme/account/theme.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme/email/messages/messages_en.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme/email/messages/messages_test.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme/email/theme.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme/login/messages/messages_en.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme/login/messages/messages_test.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/main/resources/themes/localized-theme/login/theme.properties
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/AbstractUiTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/AbstractAccountTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/ApplicationsTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/BaseAccountPageTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/DeleteAccountTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/DeviceActivityTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/InternationalizationTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/LDAPAccountTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/LinkedAccountsTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/MyResourcesTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/PermissionsTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/PersonalInfoTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/ReferrerTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/SessionTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/SigningInTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/SmokeTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/UpdateEmailTest.java
  testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account3/WelcomeScreenTest.java
  testsuite/integration-arquillian/tests/other/pom.xml
  testsuite/integration-arquillian/tests/other/webauthn/pom.xml
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/AbstractAccountPage.java
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/AbstractLoggedInPage.java
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/SigningInPage.java
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/fragments/AbstractFragmentWithMobileLayout.java
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/fragments/AbstractHeader.java
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/fragments/ContentAlert.java
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/fragments/ContinueCancelModal.java
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/fragments/LoggedInPageHeader.java
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/fragments/Sidebar.java
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/utils/SigningInPageUtils.java
  testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/account/AbstractWebAuthnAccountTest.java
  testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/account/WebAuthnSigningInTest.java
Labels: team/cloud-native, kind/task, team/ui, team/core-clients, team/core-iam

#28590 Made roleName disabled instead of readOnly
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_roles/CreateRealmRolePage.ts
  js/apps/admin-ui/src/components/role-form/RoleForm.tsx
Labels: team/ui

#28598 Fixed redirect on cancelling role edit
  js/apps/admin-ui/src/client-scopes/details/MappingDetails.tsx
Labels: team/ui, backport/22.0, backport/24.0

#28589 Add ability to set one or more internet domain to an organization.
  core/src/main/java/org/keycloak/representations/idm/OrganizationDomainRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/OrganizationRepresentation.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationsResource.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/OrganizationDomainEntity.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/OrganizationEntity.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/OrganizationAdapter.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-25.0.0.xml
  model/jpa/src/main/resources/default-persistence.xml
  server-spi-private/src/main/java/org/keycloak/organization/OrganizationProvider.java
  server-spi/src/main/java/org/keycloak/models/OrganizationDomainModel.java
  server-spi/src/main/java/org/keycloak/models/OrganizationModel.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28599 Hostname v2 for Operator
  docs/guides/operator/advanced-configuration.adoc
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDistConfigurator.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/HostnameSpec.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/KeycloakDistConfiguratorTest.java
  operator/src/test/resources/test-serialization-keycloak-cr.yml
Labels: team/cloud-native, flaky-test

#28582 Changed userId value for refresh token events
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  server-spi-private/src/main/java/org/keycloak/events/Details.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ConsentsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTransientSessionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ResourceOwnerPasswordCredentialsGrantTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ServiceAccountTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCScopeTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28565 Bug/storage sync int overflow
  model/storage-private/src/main/java/org/keycloak/storage/managers/UserStorageSyncManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/sync/SyncFederationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28607 OrganizationTest.testAttributes fails in GHA CI
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28520 task: remove MultiVersionClusterTest
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/cluster/MultiVersionClusterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/cluster/SerializableTestClass.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28627 Fixed css styling for SearchDropdown
  js/apps/admin-ui/src/clients/authorization/search-dropdown.css
Labels: team/ui

#28636 Fix Husky setup
  js/.husky/pre-commit
  js/lint-staged.config.js
  package.json
Labels: kind/task, team/ui

#28629 Fix string comparison for action
  model/storage-services/src/main/java/org/keycloak/services/resources/admin/UserStorageProviderResource.java
Labels: flaky-test

#28637 Fix test IdentityProviderTest#testSamlImportWithAnyEncryptionMethod
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28610 Add null checks after retrieving user from LDAP for validation to pre…
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPUserLoginTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28622 Release notes for lightweight access tokens and group together relate…
  docs/documentation/release_notes/topics/25_0_0.adoc
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  services/src/main/java/org/keycloak/protocol/oidc/mappers/SHA256PairwiseSubMapper.java
Labels: flaky-test

#28625 Incorrect user info in the head when using lightweight access token f…
  js/libs/keycloak-masthead/src/Masthead.tsx
Labels: team/ui

#28368 DefaultBruteForceProtector leverages a single thread to write success /failed events
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/LoginFailureEntity.java
  services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java
  services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtectorFactory.java
Labels: flaky-test

#28639 Move ESLint configuration to project root
  .vscode/settings.json
  eslint.config.js
  js/.husky/pre-commit
  js/.prettierrc.json
  js/apps/account-ui/tsconfig.json
  js/apps/admin-ui/cypress/support/util/AdminClient.ts
  js/apps/admin-ui/tsconfig.json
  js/libs/keycloak-admin-client/tsconfig.json
  js/libs/keycloak-masthead/tsconfig.json
  js/libs/ui-shared/tsconfig.json
  js/lint-staged.config.js
  package.json
  tsconfig.eslint.json
  tsconfig.json
Labels: team/ui

#28542 Make general cache options runtime
  docs/documentation/release_notes/topics/25_0_0.adoc
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/CacheBuildSteps.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakRecorder.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/BuildCommandDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/ServerOptions.java
  testsuite/integration-arquillian/servers/auth-server/quarkus/ant/configure.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28578 Correct translation of groups for Russian language
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ru.properties
Labels: team/ui

#28319 Persistent sessions code also for offline sessions
  .github/workflows/ci.yml
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/ClientSessionPersistentChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/InfinispanChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/JpaChangesPerformer.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/PersistentSessionsChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/UserSessionPersistentChangelogBasedTransaction.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-25.0.0.xml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
  server-spi/src/main/java/org/keycloak/models/UserSessionProvider.java
  testsuite/integration-arquillian/tests/base/testsuites/persistent-sessions-suite
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderOfflineModelTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28645 Prevent members with an email other than the domain set to an organization
  core/src/main/java/org/keycloak/representations/idm/OrganizationDomainRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/OrganizationRepresentation.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/OrganizationAdapter.java
  server-spi-private/src/main/java/org/keycloak/organization/OrganizationProvider.java
  server-spi/src/main/java/org/keycloak/models/OrganizationDomainModel.java
  server-spi/src/main/java/org/keycloak/models/OrganizationModel.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java
  services/src/main/java/org/keycloak/organization/validator/OrganizationMemberValidator.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProviderFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.validate.ValidatorFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationMemberTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28652 fix: adds a test and permissions for cache configmap
  operator/src/main/kubernetes/kubernetes.yml
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/CacheTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/K8sUtils.java
Labels: team/cloud-native, flaky-test

#28663 Adjust priority of SubMapper
  docs/documentation/server_admin/topics/clients/con-protocol-mappers.adoc
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  services/src/main/java/org/keycloak/protocol/ProtocolMapperUtils.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/SHA256PairwiseSubMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/SubMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OIDCPairwiseClientRegistrationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28665 Retry the login in the SAML adapter if response is authentication_expired
  adapters/saml/core/src/main/java/org/keycloak/adapters/saml/AbstractInitiateLogin.java
  adapters/saml/core/src/main/java/org/keycloak/adapters/saml/AdapterConstants.java
  adapters/saml/core/src/main/java/org/keycloak/adapters/saml/profile/AbstractSamlAuthenticationHandler.java
  adapters/saml/core/src/main/java/org/keycloak/adapters/saml/profile/ecp/EcpAuthenticationHandler.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28559 Remove last violatations of `no-unstable-nested-components`
  eslint.config.js
  js/apps/admin-ui/src/realm-settings/PoliciesTab.tsx
Labels: team/ui

#28673 Leave a tombstone after the deletion of a cache entry
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanKeycloakTransaction.java
Labels: flaky-test

#28682 fix: adjusting the test to use a fully valid config
  operator/src/test/java/org/keycloak/operator/testsuite/integration/CacheTest.java
  operator/src/test/resources/cache-ispn.xml
Labels: team/cloud-native

#28642 Simplified checks in IntrospectionEndpoint
  services/src/main/java/org/keycloak/authorization/protection/introspect/RPTIntrospectionProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/AccessTokenIntrospectionProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/managers/UserSessionCrossDCManager.java
  services/src/main/java/org/keycloak/services/resources/account/AccountLoader.java
  services/src/main/java/org/keycloak/services/util/UserSessionUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/CIBATest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28703 Encode realm name in URL when fetching from `ui-ext`
  js/apps/admin-ui/src/context/auth/admin-ui-endpoint.ts
Labels: team/ui

#28450 Denylist improvements
  docs/documentation/server_admin/topics/authentication/password-policies.adoc
  server-spi-private/src/main/java/org/keycloak/policy/BlacklistPasswordPolicyProviderFactory.java
  server-spi-private/src/test/java/org/keycloak/policy/BlacklistPasswordPolicyProviderTest.java
  server-spi-private/src/test/java/org/keycloak/policy/short_blacklist.txt
Labels: flaky-test

#28674 Ensure correct treatment of auth and transient users
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AdminExtResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UsersResource.java
Labels: team/ui

#28635 Add validation for the organization's internet domains.
  model/jpa/src/main/java/org/keycloak/organization/jpa/OrganizationAdapter.java
  server-spi/src/main/java/org/keycloak/models/OrganizationDomainModel.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28726 Explicitly specify React version for ESLint
  eslint.config.js
Labels: team/ui

#28478 Limit the concurrency of password hashing to the number of CPU cores available
  crypto/default/src/main/java/org/keycloak/crypto/hash/Argon2PasswordHashProvider.java
  crypto/default/src/main/java/org/keycloak/crypto/hash/Argon2PasswordHashProviderFactory.java
  docs/documentation/release_notes/topics/25_0_0.adoc
  docs/documentation/server_admin/topics/authentication/password-policies.adoc
Labels: flaky-test

#28651 Add german translations for admin ui (#28650)
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
Labels: team/ui

#28483 Upgrade artifact actions to latest version
  .github/actions/archive-surefire-reports/action.yml
  .github/actions/build-keycloak/action.yml
  .github/actions/integration-test-setup/action.yml
  .github/actions/upload-flaky-tests/action.yml
  .github/actions/upload-heapdumps/action.yml
  .github/workflows/ci.yml
  .github/workflows/documentation.yml
  .github/workflows/js-ci.yml
  .github/workflows/operator-ci.yml
Labels: kind/task

#27027 Workflow failure: Fuse adapter tests
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/servers/app-server/karaf/fuse7x/src/main/resources/product-portal-keycloak.json
  testsuite/integration-arquillian/servers/app-server/karaf/pom.xml
  testsuite/integration-arquillian/test-apps/fuse/camel-fuse7-undertow/pom.xml
  testsuite/integration-arquillian/test-apps/fuse/customer-app-fuse/pom.xml
  testsuite/integration-arquillian/test-apps/fuse/cxf-jaxrs-fuse7-undertow/pom.xml
  testsuite/integration-arquillian/test-apps/fuse/cxf-jaxrs-fuse7-undertow/src/main/java/org/keycloak/example/rs/CxfCustomerService.java
  testsuite/integration-arquillian/test-apps/fuse/demorealm.json
  testsuite/integration-arquillian/test-apps/fuse/external-config/pom.xml
  testsuite/integration-arquillian/test-apps/fuse/features/src/main/resources/features.xml
  testsuite/integration-arquillian/test-apps/fuse/pom.xml
  testsuite/integration-arquillian/test-apps/fuse/product-app-fuse7-undertow/src/main/java/org/keycloak/example/ProductPortalServlet.java
  testsuite/integration-arquillian/test-apps/fuse/product-app-fuse7-undertow/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  testsuite/integration-arquillian/test-apps/fuse/product-app-fuse7-undertow/src/main/resources/keycloak.json
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/example/fuse/FuseAdapterTest.java
  testsuite/integration-arquillian/util/src/main/java/org/keycloak/testsuite/utils/fuse/FuseUtils.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28727 Apply localization to placeholder and before text
  js/apps/account-ui/test/personal-info/personal-info.spec.ts
  js/apps/account-ui/test/personal-info/user-profile.json
  js/libs/ui-shared/src/user-profile/TextComponent.tsx
  js/libs/ui-shared/src/user-profile/UserProfileGroup.tsx
  themes/src/main/resources/theme/base/login/user-profile-commons.ftl
  themes/src/main/resources/theme/keycloak.v2/login/user-profile-commons.ftl
Labels: team/ui

#28757 Remove usages of EnvironmentDependentProviderFactory.isSupported
  services/src/main/java/org/keycloak/services/DefaultKeycloakSessionFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/util/FeatureDeployerUtil.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28758 Refactor and remove deprecated Infinispan methods from DefaultInfinis…
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java
  testsuite/model/src/main/java/org/keycloak/testsuite/model/HotRodServerRule.java
  testsuite/model/src/main/resources/hotrod/hotrod1.xml
  testsuite/model/src/main/resources/hotrod/hotrod2.xml
Labels: team/cloud-native, team/core-clients, team/core-iam

#28721 Add Traditional Chinese support
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_zh_TW.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_zh_TW.properties
  themes/src/main/resources-community/theme/base/account/theme.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_zh_TW.properties
  themes/src/main/resources-community/theme/base/admin/theme.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_zh_TW.properties
  themes/src/main/resources-community/theme/base/email/theme.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_zh_TW.properties
  themes/src/main/resources-community/theme/base/login/theme.properties
  themes/src/main/resources/theme/base/account/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/ui, flaky-test

#28793 added show inherited roles to empty state
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/components/role-mapping/RoleMapping.tsx
Labels: team/ui

#28773 reload when id changes
  js/apps/admin-ui/src/identity-providers/add/AddMapper.tsx
Labels: team/ui

#28618 use input instead of TextInput to make them truly hidden
  js/apps/admin-ui/src/user-federation/kerberos/KerberosSettingsRequired.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsGeneral.tsx
  js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx
Labels: team/ui

#28521 fixed style of clickable card
  js/apps/admin-ui/src/components/keycloak-card/ClickableCard.tsx
Labels: team/ui

#28743 Only allow a known refferer URI for the Account Console
  js/apps/account-ui/pom.xml
  js/apps/account-ui/src/constants.ts
  js/apps/account-ui/src/environment.ts
  js/apps/account-ui/src/root/Header.tsx
  js/apps/account-ui/test/referrer.spec.ts
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
Labels: team/ui, flaky-test

#28811 Upgrade PNPM to version 9
  package.json
  pnpm-lock.yaml
  pom.xml
Labels: kind/task, team/ui

#28206 Workflow failure: Fuse adapter tests (#27021)
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/servers/app-server/karaf/fuse7x/src/main/resources/product-portal-keycloak.json
  testsuite/integration-arquillian/servers/app-server/karaf/pom.xml
  testsuite/integration-arquillian/test-apps/fuse/camel-fuse7-undertow/pom.xml
  testsuite/integration-arquillian/test-apps/fuse/customer-app-fuse/pom.xml
  testsuite/integration-arquillian/test-apps/fuse/cxf-jaxrs-fuse7-undertow/pom.xml
  testsuite/integration-arquillian/test-apps/fuse/cxf-jaxrs-fuse7-undertow/src/main/java/org/keycloak/example/rs/CxfCustomerService.java
  testsuite/integration-arquillian/test-apps/fuse/demorealm.json
  testsuite/integration-arquillian/test-apps/fuse/external-config/pom.xml
  testsuite/integration-arquillian/test-apps/fuse/features/src/main/resources/features.xml
  testsuite/integration-arquillian/test-apps/fuse/pom.xml
  testsuite/integration-arquillian/test-apps/fuse/product-app-fuse7-undertow/src/main/java/org/keycloak/example/ProductPortalServlet.java
  testsuite/integration-arquillian/test-apps/fuse/product-app-fuse7-undertow/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  testsuite/integration-arquillian/test-apps/fuse/product-app-fuse7-undertow/src/main/resources/keycloak.json
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/example/fuse/FuseAdapterTest.java
  testsuite/integration-arquillian/util/src/main/java/org/keycloak/testsuite/utils/fuse/FuseUtils.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28435 Fix lists to be rendered as expected
  docs/guides/server/importExport.adoc
Labels: team/cloud-native

#28632 Revert "Update disabled feature status code in social login tests"
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java
Labels: team/cloud-native, flaky-test

#28775 added missing translations
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
Labels: team/ui

#28770 use filtered times instead of all
  js/apps/admin-ui/src/components/time-selector/TimeSelector.tsx
Labels: team/ui

#28123 Hostname:v2 docs
  docs/guides/server/hostname-deprecated.adoc
  docs/guides/server/hostname.adoc
Labels: team/cloud-native

#28761 Organization member onboarding using the organization identity provider
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProviderFactory.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/OrganizationAdapter.java
  server-spi-private/src/main/java/org/keycloak/forms/login/LoginFormsProvider.java
  server-spi-private/src/main/java/org/keycloak/organization/OrganizationProvider.java
  server-spi/src/main/java/org/keycloak/models/OrganizationModel.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/IdentityProviderAuthenticator.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationIdentityProviderResource.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/broker/IdpOrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/broker/IdpOrganizationAuthenticatorFactory.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticatorFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.authentication.AuthenticatorFactory
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationBrokerSelfRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationIdentityProviderTest.java
  themes/src/main/resources/theme/base/login/login-username.ftl
  themes/src/main/resources/theme/base/login/login.ftl
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#28280 Encode role name parameter in the location header uri
  services/src/main/java/org/keycloak/services/resources/admin/RoleContainerResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/ClientRolesTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28718 Ensure correct treatment of auth and transient users
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AdminExtResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UsersResource.java
Labels: team/ui

#28558 Backport for fixing searchClientRegistration message
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/registration/ClientRegistrationList.tsx
Labels: team/ui

#28849 Automatically fill username when authenticating to through a broker
  services/src/main/java/org/keycloak/authentication/authenticators/browser/IdentityProviderAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/services/Urls.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationBrokerSelfRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationIdentityProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28410 Add realm to session context when exporting to prevent NPE when vault…
  model/storage-services/src/main/java/org/keycloak/exportimport/singlefile/SingleFileExportProvider.java
  model/storage-services/src/main/java/org/keycloak/exportimport/util/MultipleStepsExportProvider.java
Labels: flaky-test

#28506 Fix navigation with realms with special chars (#28349)
  js/apps/admin-ui/cypress/e2e/realm_test.spec.ts
  js/apps/admin-ui/src/PageNav.tsx
  js/apps/admin-ui/src/context/realm-context/RealmContext.tsx
Labels: team/ui

#28768 Fix OCSP nonce handling
  crypto/default/src/main/java/org/keycloak/crypto/def/BCOCSPProvider.java
  crypto/fips1402/src/main/java/org/keycloak/crypto/fips/BCFIPSOCSPProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/OcspHandler.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28668 Added new SessionStateMapper
  js/libs/keycloak-js/src/keycloak.js
  services/src/main/java/org/keycloak/protocol/oidc/mappers/SessionStateMapper.java
  services/src/main/resources/META-INF/services/org.keycloak.protocol.ProtocolMapper
Labels: team/ui

#28871 Moved masthead to ui-shared
  js/README.md
  js/apps/account-ui/package.json
  js/apps/account-ui/src/root/Header.tsx
  js/libs/keycloak-masthead/package.json
  js/libs/keycloak-masthead/src/KeycloakContext.tsx
  js/libs/keycloak-masthead/src/main.ts
  js/libs/keycloak-masthead/src/svg.d.ts
  js/libs/keycloak-masthead/src/translation/TranslationsContext.tsx
  js/libs/keycloak-masthead/src/translation/translations.ts
  js/libs/keycloak-masthead/src/translation/useTranslation.ts
  js/libs/keycloak-masthead/src/util.ts
  js/libs/keycloak-masthead/tsconfig.json
  js/libs/keycloak-masthead/vite.config.ts
  js/libs/ui-shared/package.json
  js/libs/ui-shared/src/main.ts
  js/libs/ui-shared/src/masthead/DefaultAvatar.tsx
  js/libs/ui-shared/src/masthead/KeycloakDropdown.tsx
  js/libs/ui-shared/src/masthead/Masthead.tsx
  pnpm-lock.yaml
Labels: team/ui

#28601 Backport for fixing redirect on cancelling role edit
  js/apps/admin-ui/src/client-scopes/details/MappingDetails.tsx
Labels: team/ui

#28800 remove use of deprecated components
  js/apps/admin-ui/cypress/support/pages/admin-ui/Masthead.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/PageHeader.tsx
Labels: team/ui

#28883 Prevent updating IdP via organization API not linked with the organiz…
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationIdentityProviderResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationIdentityProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28878 Better management of the CSP header
  server-spi-private/src/main/java/org/keycloak/models/ContentSecurityPolicyBuilder.java
  server-spi-private/src/test/java/org/keycloak/models/BrowserSecurityHeadersTest.java
  services/src/main/java/org/keycloak/headers/DefaultSecurityHeadersProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/FrontChannelLogoutHandler.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/updaters/ClientAttributeUpdater.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/updaters/RealmAttributeUpdater.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RPInitiatedFrontChannelLogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RPInitiatedLogoutTest.java
Labels: team/cloud-native

#28808 Emphasize the need for setting container limit
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/upgrading/topics/changes/changes-24_0_0.adoc
  docs/guides/server/containers.adoc
Labels: team/cloud-native

#28827 Flaky test: org.keycloak.testsuite.forms.ResetPasswordTest#resetPasswordLink
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28872 Perform exact string match if redirect URI contains userinfo, encoded slashes or parent access
  common/src/main/java/org/keycloak/common/util/Encode.java
  common/src/main/java/org/keycloak/common/util/KeycloakUriBuilder.java
  common/src/test/java/org/keycloak/common/util/KeycloakUriBuilderTest.java
  docs/documentation/server_admin/topics/clients/oidc/con-basic-settings.adoc
  docs/documentation/upgrading/topics/changes/changes-24_0_3.adoc
  services/src/main/java/org/keycloak/protocol/oidc/utils/RedirectUtils.java
  services/src/test/java/org/keycloak/protocol/oidc/utils/RedirectUtilsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthRedirectUriTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28873 Validate Saml URLs inside DefaultClientValidationProvider
  services/src/main/java/org/keycloak/validation/DefaultClientValidationProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/InstallationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientRegistrationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28812 Emphasize the need for setting container limit
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/upgrading/topics/changes/changes-24_0_0.adoc
  docs/guides/server/containers.adoc
Labels: team/cloud-native

#28503 Fix refresh token scope in refresh token flow with scope request para…
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28512 Use a typeahead select control where there are 10 or more options
  js/apps/account-ui/test/personal-info/personal-info.spec.ts
  js/apps/account-ui/test/personal-info/user-profile.json
  js/apps/account-ui/test/realms/user-profile-realm.json
  js/libs/ui-shared/src/controls/SelectControl.tsx
  js/libs/ui-shared/src/user-profile/LocaleSelector.tsx
  js/libs/ui-shared/src/user-profile/SelectComponent.tsx
Labels: team/ui

#28901 task: use informer rather than 0 interval polling
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
Labels: team/cloud-native

#28857 quarkus-next: java.util.NoSuchElementException: No value present caus…
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
Labels: team/cloud-native

#28845 External Infinispan as cache - Part 2
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/remote/RemoteInfinispanClusterProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProvider.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/InfinispanConnectionProvider.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/InfinispanMultiSiteLoadBalancerCheckProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/RemoteCacheProvider.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/remote/RemoteInfinispanConnectionProvider.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/remote/RemoteLoadBalancerCheckProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/infinispan/util/InfinispanUtils.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanAuthenticationSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanSingleUseObjectProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanStickySessionEncoderProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserLoginFailureProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/events/AbstractAuthSessionClusterListener.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteInfinispanAuthenticationSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteInfinispanKeycloakTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteInfinispanSingleUseObjectProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteInfinispanSingleUseObjectProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteStickySessionEncoderProviderFactory.java
  model/infinispan/src/main/resources/META-INF/services/org.keycloak.health.LoadBalancerCheckProviderFactory
  model/infinispan/src/main/resources/META-INF/services/org.keycloak.models.SingleUseObjectProviderFactory
  model/infinispan/src/main/resources/META-INF/services/org.keycloak.sessions.StickySessionEncoderProviderFactory
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/ExternalInfinispanTest.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/InfinispanContainer.java
  server-spi-private/src/main/java/org/keycloak/health/LoadBalancerCheckProvider.java
  server-spi-private/src/main/java/org/keycloak/models/SingleUseObjectProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/sessions/StickySessionEncoderProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cluster/AuthenticationSessionClusterTest.java
  testsuite/model/pom.xml
  testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/FeatureEnabledTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/CrossDCInfinispan.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/Infinispan.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/RemoteInfinispan.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28882 Show indicator for transient user in user sessions list in admin ui
  core/src/main/java/org/keycloak/representations/idm/UserSessionRepresentation.java
  js/apps/admin-ui/src/sessions/SessionsTable.tsx
  js/libs/keycloak-admin-client/src/defs/userSessionRepresentation.ts
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/SessionsResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/SessionRepresentation.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
Labels: team/ui

#28884 Upgrade to Quarkus 3.8.4
  pom.xml
Labels: team/cloud-native

#28912 Relax checking of messages
  js/apps/admin-ui/cypress/support/pages/admin-ui/Masthead.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/tabs/SettingsTab.ts
Labels: team/ui

#28892 Validation of providerId during required action registration
  services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/RequiredActionsTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28897 Avoid the same userSessionId after re-authentication
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationSessionManager.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ReAuthenticationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28925 Relax checking of messages
  js/apps/admin-ui/cypress/support/pages/admin-ui/Masthead.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/tabs/SettingsTab.ts
Labels: team/ui

#28806 Remove deprecated EnvironmentDependentProviderFactory.isSupported method
  crypto/default/src/main/java/org/keycloak/crypto/hash/Argon2PasswordHashProviderFactory.java
  docs/documentation/release_notes/topics/25_0_0.adoc
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  federation/kerberos/src/main/java/org/keycloak/federation/kerberos/KerberosFederationProviderFactory.java
  federation/sssd/src/main/java/org/keycloak/federation/sssd/SSSDFederationProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/InfinispanMultiSiteLoadBalancerCheckProviderFactory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/vault/FilesKeystoreVaultProviderFactory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/vault/FilesPlainTextVaultProviderFactory.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AdminExtProvider.java
  server-spi-private/src/main/java/org/keycloak/policy/RecoveryCodesWarningThresholdPasswordPolicyProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/services/clientpolicy/condition/ClientPolicyConditionProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/services/clientpolicy/executor/ClientPolicyExecutorProviderFactory.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/DeployedScriptAuthenticatorFactory.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/RecoveryAuthnCodesFormAuthenticatorFactory.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/ScriptBasedAuthenticatorFactory.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/WebAuthnAuthenticatorFactory.java
  services/src/main/java/org/keycloak/authentication/authenticators/conditional/ConditionalLoaAuthenticatorFactory.java
  services/src/main/java/org/keycloak/authentication/requiredactions/RecoveryAuthnCodesAction.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateEmail.java
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnRegisterFactory.java
  services/src/main/java/org/keycloak/credential/RecoveryAuthnCodesCredentialProviderFactory.java
  services/src/main/java/org/keycloak/credential/WebAuthnCredentialProviderFactory.java
  services/src/main/java/org/keycloak/credential/WebAuthnPasswordlessCredentialProviderFactory.java
  services/src/main/java/org/keycloak/protocol/docker/DockerAuthV2ProtocolFactory.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/VCSigningServiceProviderFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/TokenExchangeGrantTypeFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/CibaGrantTypeFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/channel/AuthenticationChannelProviderFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/endpoints/CibaRootEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/resolvers/CIBALoginUserResolverFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/device/DeviceGrantTypeFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/device/endpoints/DeviceEndpointFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AcrProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AmrProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/DeployedScriptOIDCProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/ScriptBasedOIDCProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/par/endpoints/ParRootEndpoint.java
  services/src/main/java/org/keycloak/protocol/saml/mappers/ScriptBasedMapper.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/ClientSecretRotationExecutorFactory.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/RegistrationAccessTokenRotationDisabledExecutorFactory.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/SuppressRefreshTokenRotationExecutorFactory.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/UseLightweightAccessTokenExecutorFactory.java
  services/src/main/java/org/keycloak/services/clienttype/DefaultClientTypeManagerFactory.java
  services/src/main/java/org/keycloak/services/clienttype/impl/DefaultClientTypeProviderFactory.java
  services/src/main/java/org/keycloak/url/HostnameV2ProviderFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/authentication/TestHttpAuthenticationChannelProviderFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/services/clientpolicy/condition/TestRaiseExceptionConditionFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/services/clientpolicy/executor/TestRaiseExceptionExecutorFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/theme/TestThemeResourceProvider.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#28562 Added helpText for importFileHelp
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#28929 Relax checking of messages
  js/apps/admin-ui/cypress/support/pages/admin-ui/Masthead.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/tabs/SettingsTab.ts
Labels: team/ui

#28602 Backport for fixing redirect on cancelling role edit
  js/apps/admin-ui/src/client-scopes/details/MappingDetails.tsx
Labels: team/ui

#28899 Fixed loading translation values for User Profile attributes
  js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AddTranslationsDialog.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
Labels: team/ui

#28685 return proper error message for admin /users endpoint
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28807 passwordPoliciesHelp.notContainsUsername missing in admin console
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#28933 Added helpText for importFile
  js/apps/admin-ui/public/locales/en/clients-help.json
Labels: team/ui

#28924 remove deprecated component use
  js/apps/account-ui/src/account-security/SigningIn.tsx
Labels: team/ui

#28928 removed use of deprecated dropdown
  js/apps/account-ui/src/resources/ResourcesTab.tsx
Labels: team/ui

#26393 Add IdpConfirmOverrideLinkAuthenticator to handle duplicate federated identity
  docs/documentation/server_admin/topics/identity-broker/first-login-flow.adoc
  server-spi-private/src/main/java/org/keycloak/events/EventType.java
  server-spi-private/src/main/java/org/keycloak/forms/login/LoginFormsPages.java
  server-spi-private/src/main/java/org/keycloak/forms/login/LoginFormsProvider.java
  services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpConfirmOverrideLinkAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpConfirmOverrideLinkAuthenticatorFactory.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/forms/login/freemarker/Templates.java
  services/src/main/java/org/keycloak/services/messages/Messages.java
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  services/src/main/resources/META-INF/services/org.keycloak.authentication.AuthenticatorFactory
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/IdpConfirmOverrideLinkPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AssertEvents.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/ProvidersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractFirstBrokerLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/BrokerRunOnServerUtil.java
  themes/src/main/resources/theme/base/login/login-idp-link-confirm-override.ftl
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#28822 Failure reset time is applied to Permanent Lockout
  services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
Labels: missing/tests, team/cloud-native, team/core-clients, team/core-iam
