Repository keycloak/keycloak, pull requests merged in 2024-08, with the labels that each got.

#31794 Caches the id-to-user mapping for the evaluation in the current session
  server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/DefaultEvaluation.java
Labels: flaky-test

#31790 Adding an index for the revoked tokens table to speed up the cleanup
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanSingleUseObjectProviderFactory.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-26.0.0.xml
Labels: flaky-test

#31162 Enable ProtoStream encoding for External Infinispan feature
  model/infinispan/pom.xml
  model/infinispan/src/main/java/org/keycloak/marshalling/KeycloakIndexSchemaUtil.java
  model/infinispan/src/main/java/org/keycloak/marshalling/KeycloakModelSchema.java
  model/infinispan/src/main/java/org/keycloak/marshalling/Marshalling.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/remote/remover/query/ByRealmIdQueryConditionalRemover.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/remote/remover/query/QueryBasedConditionalRemover.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/LoginFailureEntity.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/RootAuthenticationSessionEntity.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/SessionEntity.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteInfinispanAuthenticationSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserLoginFailureProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/transaction/AuthenticationSessionTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/transaction/LoginFailureChangeLogTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/transaction/RemoteCacheAndExecutor.java
  model/infinispan/src/test/java/org/keycloak/marshalling/IndexSchemaChangeTest.java
  model/infinispan/src/test/java/org/keycloak/marshalling/TestModelV1.java
  model/infinispan/src/test/java/org/keycloak/marshalling/TestModelV2.java
  quarkus/runtime/pom.xml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
  testsuite/model/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#31799 Convert chapter planning for securing applications and services to guides
  docs/documentation/aggregation/pom.xml
  docs/documentation/aggregation/src/index.html
  docs/documentation/build-auto.sh
  docs/documentation/pom.xml
  docs/documentation/release_notes/topics/23_0_0.adoc
  docs/documentation/securing_apps/.asciidoctorconfig
  docs/documentation/securing_apps/docinfo-footer.html
  docs/documentation/securing_apps/docinfo.html
  docs/documentation/securing_apps/images/keycloak_logo.png
  docs/documentation/securing_apps/index.adoc
  docs/documentation/securing_apps/pom.xml
  docs/documentation/securing_apps/topics.adoc
  docs/documentation/securing_apps/topics/oidc/oidc-overview.adoc
  docs/documentation/securing_apps/topics/saml/saml-overview.adoc
  docs/documentation/securing_apps/topics/templates
  docs/documentation/server_admin/topics/authentication/authentication-sessions.adoc
  docs/documentation/server_admin/topics/clients/client-policies.adoc
  docs/documentation/server_admin/topics/clients/oidc/con-basic-settings.adoc
  docs/documentation/server_development/topics/admin-rest-api.adoc
  docs/documentation/server_development/topics/auth-spi.adoc
  docs/documentation/server_development/topics/saml-role-mappings-spi.adoc
  docs/documentation/tests/pom.xml
  docs/documentation/tests/src/test/java/org/keycloak/documentation/test/Guides.java
  docs/documentation/tests/src/test/resources/guide-url-fragments
  docs/documentation/topics/templates/document-attributes.adoc
  docs/documentation/topics/templates/release-header.adoc
  docs/documentation/upgrading/topics/changes/changes.adoc
  docs/guides/attributes.adoc
  docs/guides/securing-apps/client-registration-cli.adoc
  docs/guides/securing-apps/client-registration.adoc
  docs/guides/securing-apps/docker-registry.adoc
  docs/guides/securing-apps/javascript-adapter.adoc
  docs/guides/securing-apps/mod-auth-mellon.adoc
  docs/guides/securing-apps/mod-auth-openidc.adoc
  docs/guides/securing-apps/oidc-layers.adoc
  docs/guides/securing-apps/overview.adoc
  docs/guides/securing-apps/partials/overview/basic-steps.adoc
  docs/guides/securing-apps/partials/overview/getting-started.adoc
  docs/guides/securing-apps/partials/overview/terminology.adoc
  docs/guides/securing-apps/partials/saml/saml-errors.adoc
  docs/guides/securing-apps/saml-galleon-layers-detailed-config.adoc
  docs/guides/securing-apps/saml-galleon-layers.adoc
  docs/guides/securing-apps/token-exchange.adoc
Labels: flaky-test

#31805 Parse saml urls correctly if the bindings are different
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/admin-test/saml-idp-metadata-different-bindings.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#31854 Allow empty key use in JWKS from identity provider
  services/src/main/java/org/keycloak/keys/loader/OIDCIdentityProviderPublicKeyLoader.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/broker/oidc/MissingUseJwksRestResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerIdpPublicKeyMissingUseTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#31817 Support certificate creation for EC keys
  core/src/test/java/org/keycloak/jose/jwk/JWKTest.java
  crypto/default/src/main/java/org/keycloak/crypto/def/BCCertificateUtilsProvider.java
  crypto/elytron/src/main/java/org/keycloak/crypto/elytron/ElytronCertificateUtilsProvider.java
  crypto/fips1402/src/main/java/org/keycloak/crypto/fips/BCFIPSCertificateUtilsProvider.java
Labels: flaky-test

#31587 Add a media type to error responses on OID4VC endpoints
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCJWTIssuerEndpointTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtIssuingEndpointTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#31763 Fix access token issue OID4VC
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialsOffer.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/PreAuthorizedCode.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/PreAuthorizedGrant.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/OAuth2CodeParser.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCJWTIssuerEndpointTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#31665 Don't fail on null config map in AdvancedClaimToGroupMapper/AdvancedClaimToRoleMapper/AdvancedAttributeToGroupMapper/AdvancedAttributeToGroupMapper
  server-spi/src/main/java/org/keycloak/models/IdentityProviderMapperModel.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractAdvancedRoleMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractGroupBrokerMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlAdvancedAttributeToGroupMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlAdvancedAttributeToRoleMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/OidcAdvancedClaimToGroupMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/OidcAdvancedClaimToRoleMapperTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#31717 use stringify on use meta data descriptor
  js/apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx
Labels: team/ui

#31898 Change {0} to {{name}} to comply with other languages and display correct variable
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_es.properties
Labels: team/ui

#30751 Allow requests from local IPv6 addresses
  common/src/main/java/org/keycloak/common/enums/SslRequired.java
  docs/documentation/server_admin/topics/realms/ssl.adoc
Labels: team/cloud-native, flaky-test

#31877 Non clustered Keycloak with External Infinispan feature
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
Labels: team/cloud-native, flaky-test

#31902 Fix for Network error attempting to view default realm roles without permissions
  js/apps/admin-ui/src/components/roles-list/RolesList.tsx
Labels: team/ui

#31922 Fix for In realm role ellipsis value is null
  js/apps/admin-ui/src/components/roles-list/RolesList.tsx
Labels: team/ui

#31919 messages_ko.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ko.properties
  themes/src/main/resources-community/theme/base/login/theme.properties
Labels: team/ui, flaky-test

#31907 reverted accidental change to logout url
  js/apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx
Labels: team/ui

#31834 Remove InfinispanMultiSiteLoadBalancerCheckProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/InfinispanMultiSiteLoadBalancerCheckProvider.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/InfinispanMultiSiteLoadBalancerCheckProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/remote/RemoteLoadBalancerCheckProviderFactory.java
  model/infinispan/src/main/resources/META-INF/services/org.keycloak.health.LoadBalancerCheckProviderFactory
Labels: flaky-test

#31933 Backport to revert accidental change to logout url
  js/apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx
Labels: team/ui

#31911 backport: removed strange searching pagination logic (#31430)
  js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx
Labels: team/ui

#31765 backport: disable save when all fields are readonly (#31535)
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
Labels: team/ui, flaky-test

#31743 backport: Use TextControl in StringComponent (#31442)
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/client_scopes/client_scope_details/tabs/mappers/MapperDetailsPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
  js/apps/admin-ui/src/components/dynamic/StringComponent.tsx
  js/libs/ui-shared/src/controls/TextControl.tsx
Labels: team/ui, flaky-test

#31831 Update ESLint dependencies to latest version
  eslint.config.js
  js/apps/account-ui/src/api.ts
  js/apps/account-ui/src/api/parse-links.ts
  js/apps/account-ui/src/api/request.ts
  js/apps/admin-ui/cypress.config.ts
  js/apps/admin-ui/cypress/e2e/events_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/tabs/realmsettings_events_subtabs/AdminEventsSettingsTab.ts
  js/apps/admin-ui/src/admin-client.ts
  js/apps/admin-ui/src/client-scopes/add/MapperDialog.tsx
  js/apps/admin-ui/src/client-scopes/details/MappingDetails.tsx
  js/apps/admin-ui/src/clients/authorization/policy/Time.tsx
  js/apps/admin-ui/src/clients/initial-access/InitialAccessTokenList.tsx
  js/apps/admin-ui/src/clients/scopes/CopyToClipboardButton.tsx
  js/apps/admin-ui/src/clients/scopes/EvaluateScopes.tsx
  js/apps/admin-ui/src/components/client-scope/ClientScopeTypes.tsx
  js/apps/admin-ui/src/components/dynamic/components.ts
  js/apps/admin-ui/src/components/json-file-upload/JsonFileUpload.tsx
  js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx
  js/apps/admin-ui/src/components/users/UserSelect.tsx
  js/apps/admin-ui/src/organizations/IdentityProviderSelect.tsx
  js/apps/admin-ui/src/page/PageHandler.tsx
  js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
  js/apps/admin-ui/src/realm-settings/PoliciesTab.tsx
  js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
  js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx
  js/apps/admin-ui/src/realm-settings/localization/RealmOverrides.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesGroupTab.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesTab.tsx
  js/apps/admin-ui/src/user/UserForm.tsx
  js/apps/admin-ui/src/util.ts
  js/apps/admin-ui/src/utils/types.ts
  js/libs/keycloak-admin-client/src/resources/agent.ts
  js/libs/keycloak-admin-client/src/utils/fetchWithError.ts
  js/libs/keycloak-admin-client/test/authenticationManagement.spec.ts
  js/libs/keycloak-admin-client/test/clientScopes.spec.ts
  js/libs/keycloak-admin-client/test/clients.spec.ts
  js/libs/keycloak-admin-client/test/users.spec.ts
  js/libs/ui-shared/src/context/environment.ts
  js/libs/ui-shared/src/user-profile/LocaleSelector.tsx
  js/libs/ui-shared/src/user-profile/UserProfileFields.tsx
  package.json
  pnpm-lock.yaml
Labels: team/ui

#31052 Turkish translations added for login
  themes/src/main/resources-community/theme/base/login/messages/messages_tr.properties
Labels: team/ui

#31927 Disable SessionTimeoutsTest for old cross-site code
  testsuite/model/src/test/java/org/keycloak/testsuite/model/KeycloakModelTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/SessionTimeoutsTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#31802 OIDC dynamic client registration with response_type=none
  services/src/main/java/org/keycloak/services/clientregistration/oidc/DescriptionConverter.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OIDCClientRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/flows/OIDCBasicResponseTypeNoneTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#31964 Upgrade to Infinispan 15.0.7.Final
  docs/guides/high-availability/examples/generated/ispn-single.yaml
  docs/guides/high-availability/examples/generated/ispn-site-a.yaml
  docs/guides/high-availability/examples/generated/ispn-site-b.yaml
  pom.xml
Labels: flaky-test

#31971 Flaky test: org.keycloak.testsuite.model.DBLockTest#testTwoLocksCurre…
  testsuite/model/src/test/java/org/keycloak/testsuite/model/DBLockTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#30961 Issuer id must be a URL according to specification
  services/src/main/java/org/keycloak/protocol/oid4vc/model/VerifiableCredential.java
  services/src/test/java/org/keycloak/protocol/oid4vc/model/VerifiableCredentialTest.java
Labels: flaky-test

#31939 Do not return identity providers when querying the realm representation
  docs/documentation/release_notes/topics/26_0_0.adoc
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  js/apps/admin-ui/src/user/UserIdentityProviderLinks.tsx
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportUtil.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#31973 Upgrade to Infinispan 15.0.7.Final
  docs/guides/high-availability/examples/generated/ispn-single.yaml
  docs/guides/high-availability/examples/generated/ispn-site-a.yaml
  docs/guides/high-availability/examples/generated/ispn-site-b.yaml
  pom.xml
Labels: flaky-test

#31920 Fix for Network error attempting to view events without permissions
  js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
Labels: team/ui

#31583 fix: adds a check for duplicate users/clients to simplify cmd errors
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java
  services/src/main/java/org/keycloak/services/ServicesLogger.java
  services/src/main/java/org/keycloak/services/managers/ApplianceBootstrap.java
Labels: team/cloud-native, flaky-test

#31729 task: removing 10 second poll for optional secrets / configmaps
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
Labels: team/cloud-native

#31737 fix: adding weak validation of spi options
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/ConfigArgsConfigSource.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
Labels: team/cloud-native

#28597 Support OpenTelemetry tracing
  quarkus/config-api/pom.xml
  quarkus/config-api/src/main/java/org/keycloak/config/LoggingOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionCategory.java
  quarkus/config-api/src/main/java/org/keycloak/config/TracingOptions.java
  quarkus/deployment/pom.xml
  quarkus/runtime/pom.xml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/IgnoredArtifacts.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TracingPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/TracingConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/TracingDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#32014 Add SHAKE256 hash provider for Ed448
  core/src/main/java/org/keycloak/crypto/JavaAlgorithm.java
  core/src/main/java/org/keycloak/jose/jws/crypto/HashUtils.java
  services/src/main/java/org/keycloak/crypto/SHAKE256HashProviderFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.crypto.HashProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AccessTokenTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#31996 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ka.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ka.properties
Labels: team/ui, flaky-test

#32019 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
Labels: team/ui

#31773 Added gh-dependabot-failure-stats script
  js/util/gh-dependabot-failure-stats.sh
Labels: team/ui

#31988 Fix for Network error attempting to view events without permissions (#31920)
  js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
Labels: team/ui

#31830 Deleted authentication sessions should not be re-surrected with an update
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanKeycloakTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/transaction/RemoteInfinispanKeycloakTransaction.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionResetPasswordTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#31977 Stabilize Infinispan container startup and client connecting to server
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/ExternalInfinispanTest.java
  quarkus/tests/integration/src/test/resources/ExternalInfinispan/kcb-infinispan-cache-remote-store-config.xml
  quarkus/tests/junit5/pom.xml
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/InfinispanContainer.java
Labels: team/cloud-native, flaky-test

#31935 Conditionally redirect existing users to a broker based on their cred…
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/AbstractBrokerSelfRegistrationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32026 Add ECDH-ES encyption algorithms to the java keystore key provider
  docs/documentation/release_notes/topics/26_0_0.adoc
  services/src/main/java/org/keycloak/keys/JavaKeystoreKeyProvider.java
  services/src/main/java/org/keycloak/keys/JavaKeystoreKeyProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/keys/JavaKeystoreKeyProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#31995 Fix for ID is used as tab name instead of localized string
  js/apps/admin-ui/src/components/routable-tabs/RoutableTabs.tsx
Labels: team/ui

#32038 fix: add a warning log if a deprecated admin env variable is used
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java
  services/src/main/java/org/keycloak/services/ServicesLogger.java
Labels: team/cloud-native, flaky-test

#32050 Fix for My password string in Signing in page not getting translated in keycloak.v3 account theme
  js/apps/account-ui/src/account-security/SigningIn.tsx
Labels: team/ui, flaky-test

#31871 fix: always replacing placeholders
  common/src/main/java/org/keycloak/common/util/StringPropertyReplacer.java
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  docs/guides/server/importExport.adoc
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Import.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ImportDistTest.java
Labels: team/cloud-native, flaky-test

#31909 Add docs for the OpenTelemetry tracing
  docs/documentation/release_notes/topics/26_0_0.adoc
  docs/documentation/tests/src/test/resources/ignored-links
  docs/documentation/topics/templates/document-attributes.adoc
  docs/guides/images/jaeger-tracing.png
  docs/guides/server/pinned-guides
  docs/guides/server/tracing.adoc
Labels: team/cloud-native

#32053 Cache node binary for Windows to avoid download failures
  .github/actions/integration-test-setup/action.yml
  .github/actions/maven-cache/action.yml
Labels: flaky-test

#31846 Aligning the JS build and caching with the main build
  .github/actions/pnpm-setup/action.yml
  .github/workflows/js-ci.yml
Labels: flaky-test

#31943 Cache guide does not properly print cache-stack values
  docs/guides/templates/options.adoc
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Options.java
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/Option.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionBuilder.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#32052 added `bin` to package.json to make it executable
  js/apps/create-keycloak-theme/README.md
  js/apps/create-keycloak-theme/create.js
  js/apps/create-keycloak-theme/package.json
Labels: team/ui

#32006 IDP storage provider Infinispan implementation
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/CachedCount.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/CachedIdentityProvider.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/InfinispanIDPProvider.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/InfinispanIDPProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/InfinispanOrganizationProvider.java
  model/infinispan/src/main/resources/META-INF/services/org.keycloak.models.IDPProviderFactory
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaIDPProvider.java
Labels: flaky-test

#32031 Retry remote cache operations with back off
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProvider.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/InfinispanConnectionProvider.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/remote/RemoteInfinispanConnectionProvider.java
  model/infinispan/src/main/java/org/keycloak/infinispan/util/InfinispanUtils.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/remote/remover/iteration/ByRealmIdConditionalRemover.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/remote/remover/iteration/IterationBasedConditionalRemover.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/remote/updater/client/AuthenticatedClientSessionUpdater.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/remote/updater/user/UserSessionUpdater.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserLoginFailureProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/transaction/ClientSessionChangeLogTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/transaction/LoginFailureChangeLogTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/transaction/RemoteChangeLogTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/transaction/UserSessionChangeLogTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/transaction/UserSessionTransaction.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/RetryAndBackOffTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/TimeOutInterceptor.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#31912 Allow removing users federated from a kerberos provider
  federation/kerberos/src/main/java/org/keycloak/federation/kerberos/KerberosFederationProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosStandaloneTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#32021 Hide User Reg tab if you don't have permissions
  js/apps/admin-ui/src/realm-settings/DefaultGroupsTab.tsx
  js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
Labels: team/ui

#31767 Client Policy - Condition : Client - Client Attribute
  docs/documentation/server_admin/topics/clients/client-policies.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientAttributesCondition.java
  services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientAttributesConditionFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.services.clientpolicy.condition.ClientPolicyConditionProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesConditionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ClientPoliciesUtil.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#32118 Update RolePolicyRepresentation fields from 'boolean' to 'Boolean'
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProviderFactory.java
  core/src/main/java/org/keycloak/representations/idm/authorization/RolePolicyRepresentation.java
Labels: flaky-test

#32142 Add additional checks for pre-commit hook
  js/.husky/pre-commit
Labels: team/ui

#32126 Export users throws Disabled option: '--users'
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/Configuration.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ExportPropertyMappers.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ExportDistTest.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/CLIResult.java
Labels: team/cloud-native, flaky-test

#32130 Remove legacy cookies
  docs/documentation/release_notes/topics/26_0_0.adoc
  server-spi-private/src/main/java/org/keycloak/cookie/CookieType.java
  services/src/main/java/org/keycloak/cookie/CookieSecureResolver.java
  services/src/main/java/org/keycloak/cookie/DefaultCookieProvider.java
  services/src/main/java/org/keycloak/cookie/DefaultCookieProviderFactory.java
  services/src/main/java/org/keycloak/cookie/SecureContextResolver.java
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/login-status-iframe.html
  services/src/test/java/org/keycloak/cookie/SecureContextResolverTest.java
  testsuite/integration-arquillian/servers/auth-server/undertow/src/main/java/org/keycloak/testsuite/arquillian/undertow/lb/SimpleUndertowLoadBalancer.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerLogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cluster/AuthenticationSessionFailoverClusterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cookies/DefaultCookieProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32104 Support for resolving organization based on the organization scope
  server-spi/src/main/java/org/keycloak/models/ClientScopeDecorator.java
  server-spi/src/main/java/org/keycloak/organization/OrganizationProvider.java
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
  services/src/main/java/org/keycloak/authorization/admin/PolicyEvaluationService.java
  services/src/main/java/org/keycloak/authorization/authorization/AuthorizationTokenService.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationMembershipMapper.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  services/src/main/java/org/keycloak/protocol/AuthorizationEndpointBase.java
  services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/AuthorizationCodeGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ClientCredentialsGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/OAuth2GrantTypeBase.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ResourceOwnerPasswordCredentialsGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/CibaGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/endpoints/BackchannelAuthenticationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/device/DeviceGrantType.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientScopeEvaluateResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientScopeEvaluateScopeMappingsResource.java
  services/src/main/java/org/keycloak/services/util/DefaultClientSessionContext.java
  services/src/main/java/org/keycloak/services/util/UserSessionUtil.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationBruteForceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/member/OrganizationMemberAuthenticationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#31875 Replace calls to deprecated RealmModel IDP methods
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/InfinispanIDPProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaIDPProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/OrganizationAdapter.java
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo1_7_0.java
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo2_2_0.java
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AuthenticationManagementResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/AuthenticationMapper.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  server-spi/src/main/java/org/keycloak/models/IDPProvider.java
  server-spi/src/main/java/org/keycloak/models/IdentityProviderModel.java
  services/src/main/java/org/keycloak/authentication/authenticators/broker/util/SerializedBrokeredIdentityContext.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/IdentityProviderAuthenticator.java
  services/src/main/java/org/keycloak/forms/login/freemarker/LoginFormsUtil.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationIdentityProvidersResource.java
  services/src/main/java/org/keycloak/organization/forms/login/freemarker/model/OrganizationAwareIdentityProviderBean.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  services/src/main/java/org/keycloak/partialimport/IdentityProvidersPartialImport.java
  services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  services/src/main/java/org/keycloak/services/resources/account/LinkedAccountsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProviderResource.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/BrokerRunOnServerUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/OrganizationIdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/sessionlimits/AbstractUserSessionLimitsBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/FlowUtil.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/FederatedIdentityModelTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#32151 Handle non-existing client gracefully
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/SessionsResource.java
  services/src/main/java/org/keycloak/services/resources/account/SessionResource.java
Labels: team/ui

#32149 added extra install step to suggested steps
  js/apps/create-keycloak-theme/create.js
Labels: team/ui

#32137 fix for issue #31595
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32138 Caches the id-to-user mapping for the evaluation in the current session
  server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/DefaultEvaluation.java
Labels: flaky-test

#32167 Handle non-existing client gracefully
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/SessionsResource.java
  services/src/main/java/org/keycloak/services/resources/account/SessionResource.java
Labels: team/ui, flaky-test

#32139 Caches the id-to-user mapping for the evaluation in the current session
  server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/DefaultEvaluation.java
Labels: flaky-test

#31678 Upgrade to Quarkus 3.13.2
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  operator/pom.xml
  pom.xml
  quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/PropertyException.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Build.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/ConfigArgsConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakPropertiesConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PersistedConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/QuarkusPropertiesConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java
  quarkus/runtime/src/main/resources/application.properties
  quarkus/server/src/main/resources/application.properties
  quarkus/tests/integration/pom.xml
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FipsDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32168 Add acr scope to all clients for those migrating from older than Keyc…
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo18_0_0.java
  server-spi-private/src/main/java/org/keycloak/migration/MigrationProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolFactory.java
  services/src/main/java/org/keycloak/services/migration/DefaultMigrationProvider.java
  services/src/main/java/org/keycloak/services/resources/account/AccountCredentialResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/migration-test/migration-realm-19.0.3.json
  testsuite/integration-arquillian/tests/base/src/test/resources/migration-test/migration-realm-24.0.4.json
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32190 Specify version column name in a case-sensitive manner
  model/jpa/src/main/java/org/keycloak/models/jpa/session/PersistentClientSessionEntity.java
  model/jpa/src/main/java/org/keycloak/models/jpa/session/PersistentUserSessionEntity.java
Labels: flaky-test

#32128 Hide User Reg tab if you don't have permissions (#32021)
  js/apps/admin-ui/src/realm-settings/DefaultGroupsTab.tsx
  js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
Labels: team/ui

#32062 better unset check
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/initial-access/CreateInitialAccessToken.tsx
  js/libs/ui-shared/src/controls/NumberControl.tsx
  js/libs/ui-shared/src/utils/getRuleValue.ts
Labels: team/ui

#31747 added translation formatter to role description
  js/apps/admin-ui/src/clients/ClientsSection.tsx
  js/apps/admin-ui/src/clients/scopes/ClientScopes.tsx
  js/apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
  js/apps/admin-ui/src/components/role-mapping/RoleMapping.tsx
  js/apps/admin-ui/src/components/roles-list/RolesList.tsx
  js/apps/admin-ui/src/realm-settings/AddClientProfileModal.tsx
  js/apps/admin-ui/src/realm-settings/PoliciesTab.tsx
  js/apps/admin-ui/src/realm-settings/event-config/EventsTypeTable.tsx
  js/apps/admin-ui/src/utils/translationFormatter.ts
Labels: team/ui

#32189 IDE Launcher should set JVM options like kc.sh
  quarkus/server/src/main/java/org/keycloak/quarkus/_private/IDELauncher.java
Labels: team/cloud-native, flaky-test

#32185 Load client sessions in chunks from the database
  model/jpa/src/main/java/org/keycloak/models/jpa/session/JpaUserSessionPersisterProvider.java
Labels: flaky-test

#32186 Fix duplicate options in `show-config`
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KcEnvConfigSource.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/ShowConfigCommandTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ShowConfigCommandDistTest.java
  quarkus/tests/integration/src/test/resources/ShowConfigCommandTest/keycloak-keystore.conf
Labels: team/cloud-native, flaky-test

#32206 better unset check (#32062) (24)
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/user_details/tabs/IdentityProviderLinksTab.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/libs/ui-shared/src/controls/NumberControl.tsx
  js/libs/ui-shared/src/utils/getRuleValue.ts
Labels: team/ui

#32171 Support for ALL and ANY organization scope values
  common/src/main/java/org/keycloak/common/util/TriFunction.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationMembershipMapper.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationScope.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/AuthorizationCodeGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/OAuth2GrantTypeBase.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/CibaGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/endpoints/BackchannelAuthenticationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/device/DeviceGrantType.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientScopeEvaluateResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientScopeEvaluateScopeMappingsResource.java
  services/src/main/java/org/keycloak/services/util/DefaultClientSessionContext.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationOIDCProtocolMapperTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#31938 Management Interface is turned on even though nothing is exposed on it
  docs/guides/server/management-interface.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/ManagementOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ManagementPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ManagementConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HealthDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ManagementOffDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/MetricsDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  testsuite/integration-arquillian/servers/auth-server/quarkus/src/main/content/conf/keycloak.conf
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32235 SAML IdMapperUpdaterSessionListener should be added always and must implement HttpSessionIdListener interface (24)
  adapters/saml/wildfly-elytron/pom.xml
  adapters/saml/wildfly-elytron/src/main/java/org/keycloak/adapters/saml/elytron/IdMapperUpdaterSessionListener.java
  adapters/saml/wildfly-elytron/src/main/java/org/keycloak/adapters/saml/elytron/KeycloakConfigurationServletListener.java
  pom.xml
  testsuite/integration-arquillian/test-apps/servlets/pom.xml
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/SendUsernameServlet.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLFilterServletAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#32234 SAML IdMapperUpdaterSessionListener should be added always and must implement HttpSessionIdListener interface (25)
  adapters/saml/wildfly-elytron/pom.xml
  adapters/saml/wildfly-elytron/src/main/java/org/keycloak/adapters/saml/elytron/IdMapperUpdaterSessionListener.java
  adapters/saml/wildfly-elytron/src/main/java/org/keycloak/adapters/saml/elytron/KeycloakConfigurationServletListener.java
  pom.xml
  testsuite/integration-arquillian/test-apps/servlets/pom.xml
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/SendUsernameServlet.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32239 SAML IdMapperUpdaterSessionListener should be added always and must implement HttpSessionIdListener interface (22)
  adapters/saml/wildfly-elytron/pom.xml
  adapters/saml/wildfly-elytron/src/main/java/org/keycloak/adapters/saml/elytron/IdMapperUpdaterSessionListener.java
  adapters/saml/wildfly-elytron/src/main/java/org/keycloak/adapters/saml/elytron/KeycloakConfigurationServletListener.java
  pom.xml
  testsuite/integration-arquillian/test-apps/servlets/pom.xml
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/SendUsernameServlet.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLFilterServletAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java
Labels: team/cloud-native, flaky-test

#31672 Make sure federationLink always map to the storage provider associated with federated users
  core/src/main/java/org/keycloak/representations/idm/UserRepresentation.java
  docs/documentation/release_notes/topics/26_0_0.adoc
  js/apps/admin-ui/src/user/FederatedUserLink.tsx
  js/apps/admin-ui/src/user/UserCredentials.tsx
  js/apps/admin-ui/src/user/UserForm.tsx
  js/libs/keycloak-admin-client/src/defs/userRepresentation.ts
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java
  model/storage/src/main/java/org/keycloak/credential/UserCredentialManager.java
  model/storage/src/main/java/org/keycloak/storage/adapter/AbstractUserAdapter.java
  model/storage/src/main/java/org/keycloak/storage/adapter/AbstractUserAdapterFederatedStorage.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi-private/src/main/java/org/keycloak/storage/adapter/AbstractInMemoryUserAdapter.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  server-spi/src/main/java/org/keycloak/models/UserModel.java
  services/src/main/java/org/keycloak/userprofile/validator/ImmutableAttributeValidator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/noimport/LDAPProvidersIntegrationNoImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#32249 Let create/edit client role w/ fine-grained auth.
  js/apps/admin-ui/src/clients/routes/NewRole.tsx
  js/apps/admin-ui/src/components/role-form/RoleForm.tsx
  js/apps/admin-ui/src/realm-roles/RealmRoleTabs.tsx
Labels: team/ui

#32245 Resolve disabled options even at fast startup
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java
Labels: team/cloud-native

#31879 Deprecate UserSessionCrossDCManager
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  server-spi/src/main/java/org/keycloak/models/UserSessionProvider.java
  services/src/main/java/org/keycloak/protocol/AuthorizationEndpointBase.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenRevocationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/device/DeviceGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/OAuth2CodeParser.java
  services/src/main/java/org/keycloak/protocol/saml/SamlSessionUtils.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationSessionManager.java
  services/src/main/java/org/keycloak/services/managers/UserSessionCrossDCManager.java
  services/src/main/java/org/keycloak/services/util/UserSessionUtil.java
Labels: flaky-test

#31387 Warnings for temporary admin user and service account
  .github/workflows/js-ci.yml
  js/apps/admin-ui/cypress/e2e/clients_test.spec.ts
  js/apps/admin-ui/cypress/e2e/users_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/components/TablePage.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/App.tsx
  js/apps/admin-ui/src/Banners.tsx
  js/apps/admin-ui/src/clients/ClientsSection.tsx
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
  js/apps/admin-ui/src/context/whoami/WhoAmI.tsx
  js/apps/keycloak-server/scripts/start-server.js
  js/libs/keycloak-admin-client/src/defs/whoAmIRepresentation.ts
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  services/src/main/java/org/keycloak/events/log/JBossLoggingEventListenerProvider.java
  services/src/main/java/org/keycloak/services/managers/ApplianceBootstrap.java
  services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#32202 added isDisabled to menu toggle
  js/libs/ui-shared/src/select/SingleSelect.tsx
  js/libs/ui-shared/src/select/TypeaheadSelect.tsx
Labels: team/ui

#32224 use stringify for client scope mappers
  js/apps/admin-ui/src/client-scopes/details/MappingDetails.tsx
Labels: team/ui

#32225 added * when field is required
  js/apps/admin-ui/src/components/dynamic/FileComponent.tsx
Labels: team/ui

#32201 added populateHierarchy to types
  js/libs/keycloak-admin-client/src/resources/groups.ts
Labels: team/ui

#32276 Ensure identity providers returned to the org IDP selection are IDPs …
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/IdentityProvidersResource.java
  js/apps/admin-ui/src/organizations/IdentityProviderSelect.tsx
  js/libs/keycloak-admin-client/src/resources/identityProviders.ts
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/InfinispanIDPProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaIDPProvider.java
  server-spi/src/main/java/org/keycloak/models/IDPProvider.java
  server-spi/src/main/java/org/keycloak/models/IdentityProviderModel.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java
Labels: team/ui

#32284 Support for selecting an organization when requesting the organization scope
  docs/documentation/server_admin/topics/organizations/mapping-organization-claims.adoc
  services/src/main/java/org/keycloak/email/freemarker/beans/ProfileBean.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationMembershipMapper.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationScope.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/services/util/DefaultClientSessionContext.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/SelectOrganizationPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationOIDCProtocolMapperTest.java
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/select-organization.ftl
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#32218 Fix: admin GUI not working with 1000s of realms
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/RealmEntity.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UIRealmsResource.java
  server-spi/src/main/java/org/keycloak/models/RealmProvider.java
Labels: team/ui

#32241 fix: expose bootstrap-admin-* options
  quarkus/config-api/src/main/java/org/keycloak/config/BootstrapAdminOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/BootstrapAdminService.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/BootstrapAdminUser.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/BootstrapAdminPropertyMappers.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  services/pom.xml
  services/src/main/java/org/keycloak/services/managers/ApplianceBootstrap.java
Labels: team/cloud-native, flaky-test

#32101 fix: adding docs around client redirect uris and hostname-strict
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  docs/guides/server/hostname.adoc
Labels: team/cloud-native

#32140 OTEL: Dynamic service name for tracing in K8s environment
  docs/guides/server/tracing.adoc
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/ClusteringTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
Labels: team/cloud-native

#32268 Enable persistent sessions by default
  .github/workflows/ci.yml
  common/src/main/java/org/keycloak/common/Profile.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
  testsuite/integration-arquillian/tests/base/testsuites/volatile-sessions-suite
  testsuite/integration-arquillian/tests/pom.xml
  testsuite/model/pom.xml
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/VolatileUserSessions.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32313 Relocate Quarkus resteasy-reactive dependencies to REST
  quarkus/deployment/pom.xml
  quarkus/runtime/pom.xml
Labels: team/cloud-native, flaky-test

#32070 Add Oracle database provider.
  test-poc/examples/pom.xml
  test-poc/framework/pom.xml
  test-poc/framework/src/main/java/org/keycloak/test/framework/database/DatabaseConfig.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/database/OracleDatabaseSupplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/database/TestDatabase.java
  test-poc/framework/src/main/resources/META-INF/services/org.keycloak.test.framework.injection.Supplier
Labels: flaky-test

#31752 Migrate UserTest to the new base testsuite
  test-poc/framework/src/main/java/org/keycloak/test/framework/oauth/OAuthClient.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/realm/ClientSupplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/realm/UserSupplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/util/ApiUtil.java
  test-poc/showcase/src/test/java/org/keycloak/test/showcase/DUMMY.txt
  test-poc/showcase/src/test/java/org/keycloak/test/showcase/UserTest.java
Labels: flaky-test

#32304 Testsuite PoC - Add ability to obtain events in tests using Syslog
  test-poc/examples/src/test/java/org/keycloak/test/examples/EventsTest.java
  test-poc/examples/src/test/resources/logging.properties
  test-poc/framework/src/main/java/org/keycloak/test/framework/KeycloakIntegrationTestExtension.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/annotations/InjectEvents.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/annotations/InjectSysLogServer.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/events/EventParser.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/events/Events.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/events/EventsSupplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/events/SysLog.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/events/SysLogListener.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/events/SysLogServer.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/events/SysLogServerSupplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/injection/Registry.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/injection/Supplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/server/AbstractKeycloakTestServerSupplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/server/KeycloakTestServerConfig.java
  test-poc/framework/src/main/resources/META-INF/services/org.keycloak.test.framework.injection.Supplier
  test-poc/framework/src/test/java/org/keycloak/test/framework/events/EventParserTest.java
  test-poc/framework/src/test/java/org/keycloak/test/framework/events/SysLogTest.java
  test-poc/framework/src/test/resources/logging.properties
Labels: flaky-test

#32317 fix: adding consistent language for the non-server commands
  docs/guides/server/bootstrap-admin-recovery.adoc
  docs/guides/server/importExport.adoc
Labels: team/cloud-native

#32285 Move unrelated files out of `common` resources
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  pnpm-lock.yaml
  pnpm-workspace.yaml
  themes/.gitignore
  themes/package.json
  themes/pom.xml
  themes/rollup.config.js
  themes/src/main/resources/theme/base/login/template.ftl
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
  themes/src/main/resources/theme/keycloak.v2/login/theme.properties
  themes/src/main/resources/theme/keycloak/login/theme.properties
  themes/src/main/resources/theme/keycloak/welcome/theme.properties
Labels: team/ui, flaky-test

#32325 fix: generalizing when enabled like behavior as a validator
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/BootstrapAdminPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#32301 Ensure organization aware IdentityProviderModel is used in the infini…
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/InfinispanIDPProvider.java
Labels: flaky-test

#32335 Import React from import map
  themes/package.json
  themes/rollup.config.js
  themes/scripts/rewrite-imports.js
Labels: team/ui

#32341 fix: ensure the legacy admin username env can still be used
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/BuildAndStartDistTest.java
Labels: team/cloud-native

#32338 Testsuite PoC - Add support for html unit
  test-poc/framework/pom.xml
  test-poc/framework/src/main/java/org/keycloak/test/framework/config/Config.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/webdriver/AbstractWebDriverSupplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/webdriver/ChromeHeadlessWebDriverSupplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/webdriver/ChromeWebDriverSupplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/webdriver/FirefoxHeadlessWebDriverSupplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/webdriver/FirefoxWebDriverSupplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/webdriver/HtmlUnitWebDriverSupplier.java
  test-poc/framework/src/main/resources/META-INF/services/org.keycloak.test.framework.injection.Supplier
Labels: flaky-test

#32251 Decouple Identity provider mappers from RealmModel
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedRealm.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/CachedIdentityProviderMapper.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/InfinispanIDPProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaIDPProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/IdentityProviderMapperEntity.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/RealmEntity.java
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/AbstractConfigPropertySynchronizer.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/ConfigSyncEventListener.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/ConfigSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/GroupConfigPropertyByPathSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/RoleConfigPropertyByClientIdSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/RoleConfigPropertyByRoleNameSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi/src/main/java/org/keycloak/models/IDPProvider.java
  server-spi/src/main/java/org/keycloak/models/RealmModel.java
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java
  services/src/main/java/org/keycloak/partialimport/IdentityProviderMappersPartialImport.java
  services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProviderResource.java
Labels: flaky-test

#32311 added organizations table to account
  core/src/main/java/org/keycloak/representations/account/OrganizationRepresentation.java
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/index.ftl
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
  js/apps/account-ui/public/content.json
  js/apps/account-ui/src/api/methods.ts
  js/apps/account-ui/src/environment.ts
  js/apps/account-ui/src/organizations/Organizations.tsx
  js/apps/account-ui/src/routes.tsx
  js/apps/admin-ui/src/organizations/OrganizationsSection.tsx
  js/apps/admin-ui/src/user/Organizations.tsx
  js/libs/ui-shared/src/controls/OrganizationTable.tsx
  js/libs/ui-shared/src/main.ts
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
  services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
  services/src/main/java/org/keycloak/services/resources/account/OrganizationsResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/account/OrganizationAccountTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#32370 Removes startup probe from KeycloakRealmImport job container
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java
Labels: team/cloud-native

#32320 Rename IDPSpi to IdentityProviderStorageSpi
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/InfinispanIdentityProviderStorageProvider.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/InfinispanIdentityProviderStorageProviderFactory.java
  model/infinispan/src/main/resources/META-INF/services/org.keycloak.models.IdentityProviderStorageProviderFactory
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaIdentityProviderStorageProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaIdentityProviderStorageProviderFactory.java
  model/jpa/src/main/resources/META-INF/services/org.keycloak.models.IdentityProviderStorageProviderFactory
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultDatastoreProvider.java
  server-spi-private/src/main/java/org/keycloak/models/IdentityProviderStorageProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/models/IdentityProviderStorageSpi.java
  server-spi-private/src/main/java/org/keycloak/storage/DatastoreProvider.java
  server-spi-private/src/main/resources/META-INF/services/org.keycloak.provider.Spi
  server-spi/src/main/java/org/keycloak/models/IdentityProviderStorageProvider.java
  server-spi/src/main/java/org/keycloak/models/KeycloakSession.java
  server-spi/src/main/java/org/keycloak/models/RealmModel.java
  services/src/main/java/org/keycloak/forms/login/freemarker/model/IdentityProviderBean.java
  services/src/main/java/org/keycloak/organization/forms/login/freemarker/model/OrganizationAwareIdentityProviderBean.java
  services/src/main/java/org/keycloak/services/DefaultKeycloakSession.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/Jpa.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32394 fix for the header to make it work better on small page
  themes/src/main/resources/theme/keycloak.v2/login/resources/css/styles.css
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
Labels: team/ui

#32422 Upgrade `typescript-eslint` to the latest version
  js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx
  js/apps/admin-ui/src/components/json-file-upload/patternfly/FileUpload.tsx
  js/apps/admin-ui/src/groups/groupIdUtils.ts
  js/apps/admin-ui/src/realm-settings/security-defences/HelpLinkTextInput.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesTab.tsx
  js/libs/ui-shared/src/controls/table/KeycloakDataTable.tsx
  js/libs/ui-shared/src/user-profile/UserProfileFields.tsx
  package.json
  pnpm-lock.yaml
Labels: team/ui, flaky-test

#32350 More options to organization scope mapper including adding organization attributes to tokens
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationMembershipMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/OIDCAttributeMapperHelper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationOIDCProtocolMapperTest.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#32421 Skip creating sessions cache when Persistent Sessions is enabled
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/InfinispanConnectionProvider.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/remote/RemoteInfinispanConnectionProvider.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/remote/RemoteLoadBalancerCheckProviderFactory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
Labels: team/cloud-native, flaky-test

#32192 Removing policy-enforcer from Keycloak repository
  authz/policy-enforcer/pom.xml
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/PathCache.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/PathConfigMatcher.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/PolicyEnforcer.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/TokenPrincipal.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/cip/ClaimsInformationPointProvider.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/cip/ClaimsInformationPointProviderFactory.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/cip/HttpClaimInformationPointProvider.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/cip/HttpClaimInformationPointProviderFactory.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/cip/spi/ClaimInformationPointProvider.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/cip/spi/ClaimInformationPointProviderFactory.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/integration/elytron/ElytronPolicyEnforcerFilter.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/integration/elytron/PolicyEnforcerServletContextListener.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/integration/elytron/ServletHttpRequest.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/integration/elytron/ServletHttpResponse.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/integration/jakarta/ServletPolicyEnforcerFilter.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/spi/ConfigurationResolver.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/spi/HttpRequest.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/spi/HttpResponse.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/util/JsonUtils.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/util/KeycloakSecurityContextPlaceHolderResolver.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/util/PlaceHolderResolver.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/util/PlaceHolders.java
  authz/policy-enforcer/src/main/java/org/keycloak/adapters/authorization/util/RequestPlaceHolderResolver.java
  authz/policy-enforcer/src/main/resources/META-INF/services/org.keycloak.adapters.authorization.cip.spi.ClaimInformationPointProviderFactory
  authz/pom.xml
  pom.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/AuthzTestUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/AuthzClientCredentialsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/admin/ClaimInformationPointProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/admin/EnforcerConfigTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/admin/MyCustomCIPFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/admin/PolicyEnforcerClaimsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/admin/PolicyEnforcerTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/META-INF/services/org.keycloak.adapters.authorization.cip.spi.ClaimInformationPointProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-bearer-only-with-cip.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-bearer-only.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-config-claims-provider.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-config-path-cip.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-config-paths-same-name.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-disabled-enforce-mode-path.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-disabled-enforce-mode.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-disabled-path-nocache.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-entitlement-claims-test.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-lazyload-with-paths.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-lazyload.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-match-http-verbs-scopes.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-no-lazyload.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-on-deny-redirect.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-paths-use-method-config.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-paths.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/enforcer-uma-claims-test.json
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/test-authz-realm.json
  testsuite/integration-arquillian/util/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32352 task: remove hostname v1
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
  docs/documentation/release_notes/topics/26_0_0.adoc
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  docs/guides/server/hostname-deprecated.adoc
  docs/guides/server/reverseproxy.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/HostnameV1Options.java
  quarkus/config-api/src/main/java/org/keycloak/config/ProxyOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV1PropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ProxyPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java
  quarkus/runtime/src/main/resources/META-INF/services/org.keycloak.urls.HostnameProviderFactory
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HostnameV1DistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ProxyHostnameV1DistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ProxyHostnameV2DistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#32444 removed duplicate keys
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#32461 When Organization feature is enabled UserAdapter.getGroupsCount() ret…
  model/jpa/src/main/java/org/keycloak/models/jpa/UserAdapter.java
Labels: flaky-test

#32230 Remove GELF
  docs/documentation/release_notes/topics/26_0_0.adoc
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  docs/guides/server/logging.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/LoggingOptions.java
  quarkus/deployment/pom.xml
  quarkus/runtime/pom.xml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/runtime/src/test/resources/META-INF/keycloak.conf
  quarkus/tests/integration/pom.xml
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/GelfRemovedTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HelpCommandDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/OptionsDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
  quarkus/tests/integration/src/test/resources/OptionsDistTest/keycloak.conf
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native

#32445 Validate organization alias for forbidden chars
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationsResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32434 Add missing translation for webauthn-register action
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/ui

#32403 Additional datasources now require XA
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/CheckMultipleDatasourcesBuildStep.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/tests/integration/src/test-providers/resources/com/acme/provider/legacy/jpa/entity/quarkus.properties
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesAutoBuildDistTest.java
Labels: team/cloud-native, flaky-test

#32423 Some regular maintenance to JavaScript tooling
  js/libs/ui-shared/src/user-profile/UserProfileGroup.tsx
  package.json
  pnpm-lock.yaml
  pom.xml
Labels: team/ui

#32346 fix: adding a first-class option for trusted proxies
  docs/documentation/release_notes/topics/26_0_0.adoc
  docs/guides/server/reverseproxy.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/ProxyOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/Configuration.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/BootstrapAdminPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ProxyPropertyMappers.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ProxyHostnameV2DistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: status/hold, team/cloud-native, flaky-test

#32466 Set the correct realm when setting up client exchange permissions
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32484 added dark mode to account
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/index.ftl
  js/apps/account-ui/src/main.tsx
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/index.ftl
  js/apps/admin-ui/src/components/dropdown-panel/DropdownPanel.tsx
  js/apps/admin-ui/src/components/dropdown-panel/dropdown-panel.css
  js/apps/admin-ui/src/main.tsx
  js/apps/admin-ui/src/util.ts
  js/libs/ui-shared/src/main.ts
  js/libs/ui-shared/src/utils/darkMode.ts
Labels: team/ui, flaky-test

#32432 Brute force protection: Lockout permanently uses parameters configured under lockout temporarily
  services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#32499 Flaky test BruteForceTest.testPermanentLockout()
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32431 Document persistent sessions are enabled by default
  docs/documentation/release_notes/topics/26_0_0.adoc
  docs/documentation/server_admin/topics/sessions.adoc
  docs/documentation/server_admin/topics/sessions/administering.adoc
  docs/documentation/server_admin/topics/sessions/offline.adoc
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  docs/documentation/upgrading/topics/prep_migration.adoc
  docs/guides/getting-started/getting-started-scaling-and-tuning.adoc
  docs/guides/server/caching.adoc
  docs/guides/server/reverseproxy.adoc
  docs/transient-users.md
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
  quarkus/runtime/src/main/resources/cache-ispn.xml
Labels: team/cloud-native, flaky-test

#32309 OTEL: Profile Feature
  common/src/main/java/org/keycloak/common/Profile.java
  docs/guides/server/tracing.adoc
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TracingPropertyMappers.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/TracingDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#32418 Rename Dockerfile to Containerfile in the docs
  docs/guides/server/containers.adoc
  docs/guides/server/db.adoc
  docs/guides/server/fips.adoc
  docs/guides/server/health.adoc
Labels: team/cloud-native

#32518 Identity Provider secret visible in Organization tab (API request)
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationIdentityProvidersResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/OrganizationOIDCBrokerSelfRegistrationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32339 Remove `redirect_uri` support from OIDC logout endpoint
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolService.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCProviderConfig.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/RedirectUtils.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlSignedBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LegacyLogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RPInitiatedLogoutTest.java
  testsuite/utils/src/main/resources/META-INF/keycloak-server.json
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam
