Repository keycloak/keycloak, pull requests merged in 2024-03, with the labels that each got.

#27410 Apply remote store workaround also for configuration via CLI options
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
Labels: team/cloud-native

#27314 Update client scopes in Client Update Request in DCR
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  services/src/main/java/org/keycloak/services/clientregistration/AbstractClientRegistrationProvider.java
  services/src/main/java/org/keycloak/services/clientregistration/policy/impl/ClientScopesClientRegistrationPolicy.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientRegistrationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27413 OAuth 2.1 default profile lacks oauth-2-1-compliant setting for SecureRedirectUrisEnforcerExecutor
  services/src/main/resources/keycloak-default-client-profiles.json
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1ConfidentialClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1PublicClientTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#26950 Roles admin REST API: Don't expand composite roles
  services/src/main/java/org/keycloak/services/resources/admin/RoleContainerResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/RoleByIdResourceTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27408 Check email and username for duplicated if isLoginWithEmailAllowed
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProviderFactory.java
  services/src/main/java/org/keycloak/userprofile/validator/DuplicateEmailValidator.java
  services/src/main/java/org/keycloak/userprofile/validator/DuplicateUsernameValidator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosStandaloneTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#27425 Omit built-in props overwritten on form controls
  js/libs/ui-shared/src/controls/NumberControl.tsx
  js/libs/ui-shared/src/controls/SwitchControl.tsx
  js/libs/ui-shared/src/controls/TextControl.tsx
Labels: kind/task, team/ui

#27427 Fix flaky Cypress test for user profile
  js/apps/admin-ui/cypress/e2e/realm_settings_user_profile_enabled.spec.ts
Labels: team/ui

#27441 task: adding more diagnostics for remote failed runs
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
Labels: team/cloud-native

#27447 Map Store Removal: Remove obsolete `isUsernameCaseSensitive` ...
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  services/src/main/java/org/keycloak/userprofile/validator/DuplicateUsernameValidator.java
  services/src/main/java/org/keycloak/userprofile/validator/UsernameMutationValidator.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/UserMapStorage.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#27473 Map Store Removal: Remove obsolete KeycloakModelUtils.isRealmProvider…
  model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventStoreProvider.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
Labels: flaky-test

#27313 Adding translations when a new attribute is created
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/AddTranslationModal.tsx
  js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
  js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
  js/apps/admin-ui/src/realm-settings/localization/LocalizationTab.tsx
  js/apps/admin-ui/src/realm-settings/localization/RealmOverrides.tsx
  js/apps/admin-ui/src/realm-settings/realm-settings-section.css
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesTab.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/UserProfileTab.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AddTranslationsDialog.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
Labels: team/ui

#22192 Use browser router for Account Console
  js/apps/account-ui/playwright.config.ts
  js/apps/account-ui/src/constants.ts
  js/apps/account-ui/src/environment.ts
  js/apps/account-ui/src/main.tsx
  js/apps/account-ui/src/utils/getRootPath.ts
  js/apps/account-ui/test/account-security/linked-accounts.spec.ts
  js/apps/account-ui/test/admin-client.ts
  js/apps/account-ui/test/applications.spec.ts
  js/apps/account-ui/test/login.ts
  js/apps/account-ui/test/personal-info/personal-info.spec.ts
  js/apps/account-ui/test/utils.ts
  js/apps/account-ui/vite.config.ts
  js/apps/admin-ui/cypress/e2e/masthead_test.spec.ts
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
Labels: kind/enhancement, area/account/ui, team/ui

#27448 Map Store Removal: Remove unnecessary check in Jpa Connection Provider
  model/jpa/src/main/java/org/keycloak/connections/jpa/DefaultJpaConnectionProviderFactory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/database/QuarkusJpaConnectionProviderFactory.java
Labels: team/cloud-native, flaky-test

#27496 Import Alpine through module instead of script tag
  themes/src/main/resources/theme/keycloak.v2/login/resources/script/cdn.min.js
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
  themes/src/main/resources/theme/keycloak.v2/login/theme.properties
  themes/src/main/resources/theme/keycloak/common/resources/package.json
  themes/src/main/resources/theme/keycloak/common/resources/pnpm-lock.yaml
Labels: kind/task

#27479 Upgrade aws-advanced-jdbc-wrapper to v2.3.4
  pom.xml
Labels: flaky-test

#27493 Show expiration only when explicitly requested
  js/apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
  js/apps/admin-ui/src/clients/advanced/TokenLifespan.tsx
Labels: team/ui

#27495 Use JDK17 features to simplify code with multiline strings
  operator/pom.xml
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakSharedCsvMetadata.java
Labels: team/cloud-native, flaky-test

#27502 LDAPSyncTest - additional removal of users at the end of the test
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPSyncTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27498 Update disabled feature status code in social login tests
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java
Labels: team/cloud-native, flaky-test, backport/22.0, team/core-clients, team/core-iam, backport/24.0

#27507 Upgrade to Aurora Postgres 15.5
  docs/guides/high-availability/partials/aurora/aurora-multiaz-create-procedure.adoc
  pom.xml
Labels: flaky-test

#27351 Change supported criteria for Google Authenticator
  services/src/main/java/org/keycloak/authentication/otp/GoogleAuthenticatorProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionTotpSetupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionTotpSetupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27516 keycloak-model-legacy is deprecated, not removed
  pom.xml
  quarkus/runtime/pom.xml
Labels: team/cloud-native, flaky-test

#27533 Update disabled feature status code in social login tests
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java
Labels: team/cloud-native, flaky-test

#27430 Allow fetching roles when evaluating role licies
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProviderFactory.java
  core/src/main/java/org/keycloak/representations/idm/authorization/RolePolicyRepresentation.java
  docs/documentation/authorization_services/images/policy/create-role.png
  docs/documentation/authorization_services/topics/policy-role-policy.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/authorization/policy/Role.tsx
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/RolePolicyTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/admin/RolePolicyManagementTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#27547 Show an error message when file does not exist for the config-file parameter
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Main.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
Labels: team/cloud-native, flaky-test

#27566 Fix broken tests for authenticators in Admin Console
  js/apps/admin-ui/cypress/e2e/authentication_policies.spec.ts
Labels: team/ui

#27414 Port client login settings to new form controls
  js/apps/admin-ui/cypress/e2e/clients_saml_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/CreateClientPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/tabs/SettingsTab.ts
  js/apps/admin-ui/src/clients/add/AccessSettings.tsx
  js/apps/admin-ui/src/clients/add/LoginSettings.tsx
Labels: kind/task, team/ui

#27419 Port logout panel to new form controls
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/CreateClientPage.ts
  js/apps/admin-ui/src/clients/add/LogoutPanel.tsx
Labels: kind/task, team/ui

#27568 Port import form to new form controls
  js/apps/admin-ui/src/clients/import/ImportForm.tsx
Labels: kind/task, team/ui

#27570 Port group client authorization policy to new form controls
  js/apps/admin-ui/src/clients/authorization/policy/Group.tsx
Labels: kind/task, team/ui

#27424 migrated some of the controls to ui-shared
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/providers/ProviderPage.ts
  js/apps/admin-ui/src/user-federation/custom/SyncSettings.tsx
  js/apps/admin-ui/src/user-federation/kerberos/KerberosSettingsRequired.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsConnection.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsGeneral.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsSearching.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsSynchronization.tsx
  js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx
Labels: kind/task, team/ui

#27571 Port common authorization policy fields to new form controls
  js/apps/admin-ui/src/clients/authorization/policy/NameDescription.tsx
  js/apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx
Labels: area/admin/ui, kind/task, team/ui

#27569 Port regex client authorization policy to new form controls
  js/apps/admin-ui/cypress/e2e/client_authorization_test.spec.ts
  js/apps/admin-ui/src/clients/authorization/policy/Regex.tsx
Labels: kind/task, team/ui

#27591 Fixed messages and replaced KeyckloakTextInput with TextControl
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/events/AdminEvents.tsx
  js/apps/admin-ui/src/events/EventsSection.tsx
Labels: team/ui

#27546 Simplify handling of profile handling in test cases
  common/src/test/java/org/keycloak/common/ProfileTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HelpCommandDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
Labels: team/cloud-native

#27551 keycloak-model-legacy is deprecated, not removed
  pom.xml
  quarkus/runtime/pom.xml
Labels: team/cloud-native, flaky-test

#27596 Changed KeyckloakTextInput to TextControl in NewRealmForm
  js/apps/admin-ui/cypress/support/pages/admin-ui/CreateRealmPage.ts
  js/apps/admin-ui/src/components/SwitchControl.tsx
  js/apps/admin-ui/src/realm/add/NewRealmForm.tsx
  js/libs/ui-shared/src/controls/SwitchControl.tsx
  js/libs/ui-shared/src/main.ts
Labels: team/ui

#26775 Initial client policies integration for SAML
  server-spi/src/main/java/org/keycloak/services/clientpolicy/ClientPolicyEvent.java
  services/src/main/java/org/keycloak/protocol/saml/SamlService.java
  services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientProtocolCondition.java
  services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientProtocolConditionFactory.java
  services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientRolesCondition.java
  services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientUpdaterContextCondition.java
  services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientUpdaterSourceGroupsCondition.java
  services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientUpdaterSourceHostsCondition.java
  services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientUpdaterSourceRolesCondition.java
  services/src/main/java/org/keycloak/services/clientpolicy/context/AbstractSamlRequestContext.java
  services/src/main/java/org/keycloak/services/clientpolicy/context/SamlAuthnRequestContext.java
  services/src/main/java/org/keycloak/services/clientpolicy/context/SamlLogoutRequestContext.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/SamlAvoidRedirectBindingExecutor.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/SamlAvoidRedirectBindingExecutorFactory.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/SamlSecureClientUrisExecutor.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/SamlSecureClientUrisExecutorFactory.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/SamlSignatureEnforcerExecutor.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/SamlSignatureEnforcerExecutorFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.services.clientpolicy.condition.ClientPolicyConditionProviderFactory
  services/src/main/resources/META-INF/services/org.keycloak.services.clientpolicy.executor.ClientPolicyExecutorProviderFactory
  services/src/main/resources/keycloak-default-client-profiles.json
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/SamlClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesLoadUpdateTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/SamlClientPoliciesExecutorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ClientPoliciesUtil.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27542 Encode role name parameter in the location header uri
  services/src/main/java/org/keycloak/services/resources/admin/RoleContainerResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/ClientRolesTest.java
Labels: missing/tests, team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27593 migrated user forms to ui-shared
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/CredentialsPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/user_details/tabs/IdentityProviderLinksTab.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/user/UserForm.tsx
  js/apps/admin-ui/src/user/UserIdPModal.tsx
  js/apps/admin-ui/src/user/user-credentials/LifespanField.tsx
  js/apps/admin-ui/src/user/user-credentials/RequiredActionMultiSelect.tsx
  js/apps/admin-ui/src/user/user-credentials/ResetCredentialDialog.tsx
  js/apps/admin-ui/src/user/user-credentials/ResetPasswordDialog.tsx
  js/libs/ui-shared/src/controls/TextControl.tsx
Labels: team/ui

#27435 Clarify format of keys in `additionalOptions` field in the Keycloak CR
  docs/guides/operator/advanced-configuration.adoc
Labels: team/cloud-native

#21817 trigger REMOVE_TOTP event on user credential removal
  server-spi-private/src/main/java/org/keycloak/events/Details.java
  services/src/main/java/org/keycloak/services/resources/account/AccountCredentialResource.java
  services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam, team/core-shared

#27618 Clarify format of keys in `additionalOptions` field in the Keycloak CR (#27435)
  docs/guides/operator/advanced-configuration.adoc
Labels: team/cloud-native

#27615 Remove additional handlers for health and metrics endpoints
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/NotFoundHandler.java
Labels: team/cloud-native

#27613 enhance: add a note about checking the migration guide
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
Labels: team/cloud-native, flaky-test

#27631 trigger REMOVE_TOTP event on removal of an OTP credential
  server-spi-private/src/main/java/org/keycloak/events/Details.java
  services/src/main/java/org/keycloak/services/resources/account/AccountCredentialResource.java
  services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#27576 Support for script providers when running in embedded mode
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  testsuite/integration-arquillian/HOW-TO-RUN.md
Labels: team/cloud-native, team/core-clients, team/core-iam

#27588 Only add the nonce claim to the ID Token (mapper for backwards compatibility)
  docs/documentation/upgrading/topics/keycloak/changes-25_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes.adoc
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/NonceBackwardsCompatibleMapper.java
  services/src/main/resources/META-INF/services/org.keycloak.protocol.ProtocolMapper
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/updaters/ClientAttributeUpdater.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/concurrency/ConcurrentLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AuthorizationTokenResponseModeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/NonceBackwardsCompatibleMapperTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#27428 changed to use ui-shared
  js/apps/admin-ui/src/user-federation/custom/CustomProviderSettings.tsx
Labels: team/ui

#27550 fixed the search attributes when federation is enabled
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
  js/apps/admin-ui/src/components/users/UserDataTableToolbarItems.tsx
Labels: team/ui

#27594 added better default value
  js/apps/admin-ui/src/authentication/form/CreateFlow.tsx
Labels: team/ui

#27650 added better default value (#27594)
  js/apps/admin-ui/src/authentication/form/CreateFlow.tsx
Labels: team/ui

#27651 fixed the search attributes when federation is enabled (#27550)
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
  js/apps/admin-ui/src/components/users/UserDataTableToolbarItems.tsx
Labels: team/ui

#27531 Updated CS and SK login messages
  themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_sk.properties
Labels: flaky-test

#27487 Instead of an InputStream that doesn't know about its encoding, use a String
  saml-core/src/main/java/org/keycloak/saml/common/util/StaxParserUtil.java
  saml-core/src/main/java/org/keycloak/saml/processing/core/saml/v2/util/SAMLMetadataUtil.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/AbstractIdentityProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/IdentityProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/connections/httpclient/HttpClientProvider.java
  services/src/main/java/org/keycloak/broker/oidc/KeycloakOIDCIdentityProviderFactory.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProviderFactory.java
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProviderFactory.java
  services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthorizationEndpointRequestParserProcessor.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/endpoints/request/BackchannelAuthenticationEndpointRequestParserProcessor.java
  services/src/main/java/org/keycloak/protocol/oidc/par/endpoints/request/ParEndpointRequestParserProcessor.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/JWKSHttpUtils.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/PairwiseSubMapperValidator.java
  services/src/main/java/org/keycloak/protocol/saml/SamlAbstractMetadataPublicKeyLoader.java
  services/src/main/java/org/keycloak/protocol/saml/SamlMetadataPublicKeyLoader.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java
  services/src/test/java/org/keycloak/protocol/saml/SamlMetadataKeyLocatorTest.java
Labels: flaky-test

#27411 changed repository url to make finding the source easier
  js/libs/keycloak-admin-client/package.json
Labels: team/ui

#27600 Fix account console tests for dev
  js/apps/account-ui/src/main.tsx
  js/apps/account-ui/src/root/PageNav.tsx
  js/apps/account-ui/src/routes.tsx
  js/apps/account-ui/test/account-security/linked-accounts.spec.ts
  js/apps/account-ui/test/admin-client.ts
  js/apps/account-ui/test/utils.ts
Labels: team/ui

#27625 Revoked token cache expiration fix
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenRevocationEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenRevocationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#27658 Replaced KeycloakTextInput with TextControl in clients/registration/detailProvider
  js/apps/admin-ui/src/clients/registration/DetailProvider.tsx
Labels: team/ui

#27649 Remove recursively when deleting an authentication executor
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo22_0_0.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/FlowTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#27626 Port role form to new form controls
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/providers/ProviderPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_roles/CreateRealmRolePage.ts
  js/apps/admin-ui/src/clients/roles/CreateClientRole.tsx
  js/apps/admin-ui/src/components/role-form/RoleForm.tsx
  js/apps/admin-ui/src/realm-roles/CreateRealmRole.tsx
  js/apps/admin-ui/src/realm-roles/RealmRoleTabs.tsx
Labels: area/admin/ui, kind/task, team/ui

#27577 Make sure refresh token expiration is based on the current time when the token is issued
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/EntitlementAPITest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#25333 Conditionally enable and disable CLI options
  common/src/main/java/org/keycloak/common/Profile.java
  docs/guides/templates/guide.adoc
  docs/guides/templates/options.adoc
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Options.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionCategory.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Environment.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Help.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ShortErrorMessageHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Build.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Export.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/HelpAllMixin.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Import.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/Configuration.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/DisabledMappersInterceptor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KcUnmatchedArgumentException.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PersistedConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PropertyMappingInterceptor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ExportPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ImportPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/main/resources/META-INF/services/io.smallrye.config.ConfigSourceInterceptor
  quarkus/runtime/src/test/resources/META-INF/keycloak.conf
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/OptionValidationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ExportDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ImportDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/OptionsDistTest.java
  quarkus/tests/integration/src/test/resources/OptionsDistTest/keycloak.conf
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.unix.approved.txt
  server-spi/src/main/java/org/keycloak/utils/StringUtil.java
Labels: team/cloud-native, flaky-test

#27336 no result to parse on success
  js/apps/account-ui/src/account-security/AccountRow.tsx
  js/apps/account-ui/src/api/methods.ts
  services/src/main/java/org/keycloak/services/resources/account/LinkedAccountsResource.java
Labels: team/ui, flaky-test

#27704 Changed key provider form to use ui shared
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/keys/key-providers/KeyProviderForm.tsx
Labels: team/ui

#27439 Change oidcScopeMissing from WARN to DEBUG
  services/src/main/java/org/keycloak/services/ServicesLogger.java
Labels: flaky-test

#27711 Replaced KeycloakTextInput with TextControl in GroupsModal
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/groups/GroupModal.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/groups/group_details/GroupDetailPage.ts
  js/apps/admin-ui/src/groups/GroupsModal.tsx
Labels: team/ui

#27630 fix: accounting for the possibility of null flows from existing realms
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/AuthenticationMapper.java
  server-spi-private/src/main/java/org/keycloak/models/utils/DefaultAuthenticationFlows.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/import/partial-authentication-flows-import.json
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#27713 Use correct path to account console
  js/apps/account-ui/pom.xml
  js/apps/account-ui/src/environment.ts
  js/apps/account-ui/src/root/PageNav.tsx
  js/apps/account-ui/src/routes.tsx
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
Labels: team/ui, flaky-test

#27721 Handle errors from Keycloak JS in the Account Console
  js/apps/account-ui/src/root/ErrorPage.tsx
  js/apps/account-ui/src/root/KeycloakContext.tsx
Labels: team/ui

#27717 fix: accounting for the possibility of null flows from existing realms
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/AuthenticationMapper.java
  server-spi-private/src/main/java/org/keycloak/models/utils/DefaultAuthenticationFlows.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/import/partial-authentication-flows-import.json
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#27601 Map Storage Removal: Remove deprecated model/legacy module
  docs/documentation/upgrading/topics/keycloak/changes-25_0_0.adoc
  model/legacy/pom.xml
  model/legacy/src/main/java/org/keycloak/credential/LegacyUserCredentialManager.java
  model/legacy/src/main/java/org/keycloak/models/LegacyRealmModel.java
  model/legacy/src/main/java/org/keycloak/storage/LegacyStoreManagers.java
  model/pom.xml
  pom.xml
  quarkus/runtime/pom.xml
Labels: team/cloud-native

#27735 Handle errors from Keycloak JS in the Account Console (#27721)
  js/apps/account-ui/src/root/ErrorPage.tsx
  js/apps/account-ui/src/root/KeycloakContext.tsx
Labels: team/ui

#27207 Issue Verifiable Credentials in the SD-JWT-VC format #25942
  core/src/main/java/org/keycloak/sdjwt/IssuerSignedJWT.java
  core/src/main/java/org/keycloak/sdjwt/SdJwt.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/JwtSigningService.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/SdJwtSigningService.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/SdJwtSigningServiceProviderFactory.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/SigningProperties.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/JwtSigningServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/SdJwtSigningServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/SigningServiceTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27612 task: refine DistributionTest.keepAlive
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/CLITestExtension.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/DistributionTest.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/KeepServerAlive.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/DockerKeycloakDistribution.java
Labels: team/cloud-native, flaky-test

#27742 Make sure empty configuration resolves to the system default configuration
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo23_0_0.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27764 Migrated to ui-shared clients/advanced
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/tabs/AdvancedTab.ts
  js/apps/admin-ui/src/clients/advanced/AddHostDialog.tsx
  js/apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
  js/libs/ui-shared/src/controls/SwitchControl.tsx
Labels: team/ui

#27763 [backport] - Make sure empty configuration resolves to the system default configuration
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo23_0_0.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#27670 Fix search by attribute tests
  js/libs/keycloak-admin-client/test/users.spec.ts
Labels: team/ui

#27668 [backport] - Authz-client: fix ClassCast Exception when getting resource permissions
  authz/client/src/main/java/org/keycloak/authorization/client/resource/AuthorizationResource.java
Labels: flaky-test

#27776 changed to use ui-shared
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/tabs/KeysTab.ts
  js/apps/admin-ui/src/clients/keys/GenerateKeyDialog.tsx
  js/apps/admin-ui/src/clients/keys/ImportKeyDialog.tsx
  js/apps/admin-ui/src/clients/keys/Keys.tsx
  js/apps/admin-ui/src/clients/keys/SamlKeys.tsx
  js/apps/admin-ui/src/clients/keys/StoreSettings.tsx
Labels: team/ui

#27803 Do not challenge inside spnego authenticator is FORKED_FLOW
  services/src/main/java/org/keycloak/authentication/authenticators/browser/SpnegoAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosStandaloneTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/kerberos/kerberosrealm.json
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27682 task: ensuring that keycloaksessions are closed
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/CreateSessionHandler.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FipsDistTest.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
Labels: team/cloud-native

#27804 fixed merge conflict
  themes/src/main/resources/theme/keycloak.v2/login/register.ftl
Labels: flaky-test

#27762 migrated discovery field
  js/apps/admin-ui/package.json
  js/apps/admin-ui/src/identity-providers/add/AddOpenIdConnect.tsx
  js/apps/admin-ui/src/identity-providers/add/AddSamlConnect.tsx
  js/apps/admin-ui/src/identity-providers/component/DiscoveryEndpointField.tsx
  js/pnpm-lock.yaml
Labels: team/ui

#27727 Adds Portuguese translations
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_pt.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_pt.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/account/theme.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_pt.properties
  themes/src/main/resources-community/theme/base/admin/theme.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_pt.properties
  themes/src/main/resources-community/theme/base/email/theme.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_pt.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/login/theme.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_pt.properties
  themes/src/main/resources/theme/base/account/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/ui

#27822 Do not challenge inside spnego authenticator is FORKED_FLOW
  services/src/main/java/org/keycloak/authentication/authenticators/browser/SpnegoAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosStandaloneTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/kerberos/kerberosrealm.json
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27821 MTLS Cache options should be runtime options, not build time options
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.unix.approved.txt
Labels: team/cloud-native

#27845 moved credentials to ui-shared
  js/apps/admin-ui/src/clients/credentials/Credentials.tsx
  js/apps/admin-ui/src/clients/credentials/SignedJWT.tsx
  js/apps/admin-ui/src/clients/credentials/X509.tsx
Labels: team/ui

#27647 migrated to ui-shared
  js/apps/admin-ui/cypress/e2e/realm_settings_tabs_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/AddTranslationModal.tsx
  js/apps/admin-ui/src/realm-settings/ClientProfileForm.tsx
  js/apps/admin-ui/src/realm-settings/EmailTab.tsx
  js/libs/ui-shared/src/controls/TextAreaControl.tsx
Labels: team/ui

#27806 Fix JS build on Windows
  js/pom.xml
Labels: team/ui

#27389 Continue LDAP search if a duplicated user (ModelDuplicateException) is found
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPSearchForUsersPaginationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/noimport/LDAPSearchForUsersPaginationNoImportTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27783 Load server info before rendering rest of application
  js/apps/admin-ui/src/context/server-info/ServerInfoProvider.tsx
Labels: team/ui

#27578 "Allowed Protocol Mapper Types" prevents clients from self-updating via client registration api
  services/src/main/java/org/keycloak/services/clientregistration/policy/impl/ProtocolMappersClientRegistrationPolicy.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientRegistrationPoliciesTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27857 Load server info before rendering rest of application (#27783)
  js/apps/admin-ui/src/context/server-info/ServerInfoProvider.tsx
Labels: team/ui

#27858 Load server info before rendering rest of application (#27783)
  js/apps/admin-ui/src/context/server-info/ServerInfoProvider.tsx
Labels: team/ui

#27830 Organizations SPI
  common/src/main/java/org/keycloak/common/Profile.java
  server-spi-private/src/main/java/org/keycloak/organization/OrganizationSpi.java
  server-spi-private/src/main/resources/META-INF/services/org.keycloak.provider.Spi
  server-spi/src/main/java/org/keycloak/models/OrganizationModel.java
  server-spi/src/main/java/org/keycloak/organization/OrganizationProvider.java
  server-spi/src/main/java/org/keycloak/organization/OrganizationProviderFactory.java
Labels: flaky-test

#27831 Only remove attributes with empty values when updating user profile
  model/jpa/src/main/java/org/keycloak/models/jpa/UserAdapter.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultUserProfile.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#27656 Limit the received content when handling the content as a String.
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  server-spi-private/src/main/java/org/keycloak/broker/provider/util/SimpleHttp.java
  server-spi-private/src/main/java/org/keycloak/connections/httpclient/HttpClientProvider.java
  server-spi-private/src/main/java/org/keycloak/connections/httpclient/SafeInputStream.java
  server-spi-private/src/test/java/org/keycloak/broker/provider/util/SimpleHttpTest.java
  services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java
  services/src/main/java/org/keycloak/connections/httpclient/SafeBasicResponseHandler.java
  services/src/main/java/org/keycloak/connections/httpclient/SafeHttpEntity.java
  services/src/test/java/org/keycloak/connections/httpclient/SafeBasicResponseHandlerTest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/broker/util/SimpleHttpDefault.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AbstractRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceReadOnlyAttributesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/LinkedAccountsRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/ResourcesRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/SessionRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminConsoleLandingPageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminConsolePermissionsCalculatedTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminConsoleWhoAmILocaleTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTransientSessionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/error/UncaughtErrorPageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPAccountRestApiTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/BackwardsCompatibilityUserStorageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthRedirectUriTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenRevocationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCAdvancedRequestParamsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCWellKnownProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/url/DefaultHostnameTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27872 Upgrade to Infinispan 14.0.26.Final
  docs/guides/high-availability/connect-keycloak-to-external-infinispan.adoc
  docs/guides/high-availability/examples/generated/keycloak-ispn.yaml
  docs/guides/high-availability/examples/src/kcb-infinispan-cache-remote-store-config.xml
  pom.xml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
Labels: team/cloud-native

#27725 Enable Infinispan metrics automatically if overall metrics are enabled
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  docs/guides/server/caching.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/CachingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/MetricsPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
  quarkus/runtime/src/main/resources/cache-ispn.xml
  quarkus/runtime/src/main/resources/cache-local.xml
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/MetricsDistTest.java
  quarkus/tests/integration/src/test/resources/cache-local.xml
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.unix.approved.txt
Labels: team/cloud-native, flaky-test

#27817 Add a section on the admin console partial import/export capability
  docs/guides/server/importExport.adoc
Labels: team/cloud-native, team/core-iam

#27865 [backport] - Only remove attributes with empty values when updating user profile
  model/jpa/src/main/java/org/keycloak/models/jpa/UserAdapter.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultUserProfile.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27883 Update version of bctls-fips in the docs
  docs/guides/server/fips.adoc
Labels: team/cloud-native

#27891 Update version of bctls-fips in the docs closes #27882
  docs/guides/server/fips.adoc
Labels: team/cloud-native

#27896 Upgrade to Infinispan 14.0.26.Final
  docs/guides/high-availability/connect-keycloak-to-external-infinispan.adoc
  docs/guides/high-availability/examples/generated/keycloak-ispn.yaml
  docs/guides/high-availability/examples/src/kcb-infinispan-cache-remote-store-config.xml
  pom.xml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
Labels: team/cloud-native

#27799 converted client select to ui-shared
  js/apps/admin-ui/src/components/client/ClientSelect.tsx
  js/libs/ui-shared/src/controls/SelectControl.tsx
Labels: team/ui

#27642 fix: allow the formbodyhandler to run tasks in the calling thread
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/KeycloakHandlerChainCustomizer.java
Labels: team/cloud-native

#27283 fixed missing translations for links in french and italian emails
  themes/src/main/resources-community/theme/base/email/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_it.properties
Labels: area/translations, flaky-test

#27513 Filter subgroups before paginating
  server-spi/src/main/java/org/keycloak/models/GroupModel.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java
Labels: flaky-test

#27889 Add migration for terms and conditions required action in FED_USER_RE…
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate24_0_2_FederatedTermsAndConditionsRequiredAction.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-24.0.2.xml
  model/jpa/src/main/resources/META-INF/jpa-changelog-master.xml
Labels: flaky-test

#27922 Fix missing log argument in MigrateTo24_0_0
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo24_0_0.java
Labels: flaky-test

#27680 User locale in server info has language and country switched around
  core/src/main/java/org/keycloak/representations/info/SystemInfoRepresentation.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27929 Remove log4j from documentation tests
  docs/documentation/tests/pom.xml
  docs/documentation/tests/src/test/java/org/keycloak/documentation/test/Config.java
  docs/documentation/tests/src/test/java/org/keycloak/documentation/test/Guide.java
  docs/documentation/tests/src/test/java/org/keycloak/documentation/test/utils/LinkUtils.java
  docs/documentation/tests/src/test/resources/log4j.properties
Labels: flaky-test

#27907 Creating the bare minimum implementation for organization
  core/src/main/java/org/keycloak/representations/idm/OrganizationRepresentation.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationResource.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationsResource.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/RealmResource.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/OrganizationEntity.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProviderFactory.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/OrganizationAdapter.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-25.0.0.xml
  model/jpa/src/main/resources/META-INF/jpa-changelog-master.xml
  model/jpa/src/main/resources/META-INF/services/org.keycloak.organization.OrganizationProviderFactory
  model/jpa/src/main/resources/default-persistence.xml
  server-spi-private/src/main/java/org/keycloak/organization/OrganizationProvider.java
  server-spi-private/src/main/java/org/keycloak/organization/OrganizationProviderFactory.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResourceFactory.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResourceProvider.java
  services/src/main/resources/META-INF/services/org.keycloak.services.resources.admin.ext.AdminRealmResourceProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
  testsuite/integration-arquillian/tests/base/testsuites/base-suite
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27606 Remove offline session preloading
  common/src/main/java/org/keycloak/common/Profile.java
  docs/documentation/release_notes/topics/17_0_0.adoc
  docs/documentation/server_admin/topics.adoc
  docs/documentation/server_admin/topics/sessions/preloading.adoc
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/BaseCacheInitializer.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/DBLockBasedCacheInitializer.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/OfflinePersistentUserSessionLoader.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/SessionLoader.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionsLoader.java
  model/storage-private/src/main/java/org/keycloak/models/dblock/DBLockProvider.java
  server-spi/src/main/java/org/keycloak/models/UserSessionProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
  testsuite/model/pom.xml
  testsuite/model/src/test/java/org/keycloak/testsuite/model/DBLockTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderOfflineModelTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27926 Remove http metrics from the docs as they are not available in the current release
  docs/guides/server/configuration-metrics.adoc
Labels: team/cloud-native

#27684 Stabilize the quarkus-next build stage
  .github/scripts/prepare-quarkus-next.sh
Labels: team/cloud-native, flaky-test

#27949 Remove http metrics from the docs as they are not available in the curent release
  docs/guides/server/configuration-metrics.adoc
Labels: team/cloud-native

#27950 Remove http metrics from the docs as they are not available in the curent release
  docs/guides/server/configuration-metrics.adoc
Labels: team/cloud-native

#27978 27955 backport
  docs/documentation/server_admin/topics/authentication/flows.adoc
  docs/documentation/server_admin/topics/authentication/kerberos.adoc
  docs/documentation/server_admin/topics/identity-broker/social/openshift.adoc
  docs/documentation/server_admin/topics/login-settings/forgot-password.adoc
  docs/documentation/server_admin/topics/sso-protocols/con-oidc-auth-flows.adoc
  docs/documentation/server_admin/topics/user-federation/ldap.adoc
  docs/documentation/server_admin/topics/users/user-profile.adoc
  docs/documentation/server_admin/topics/vault.adoc
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#27982 Stabilize realm_settings_user_profile_enabled test
  js/apps/admin-ui/cypress/e2e/realm_settings_user_profile_enabled.spec.ts
Labels: team/ui

#27071 Issue Verifiable Credentials in the VCDM format #25943
  pom.xml
  quarkus/runtime/pom.xml
  services/pom.xml
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/LDSigningService.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/LDSigningServiceProviderFactory.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/SigningProperties.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/vcdm/Ed255192018Suite.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/vcdm/LDSignatureType.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/vcdm/LinkedDataCryptographicSuite.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/vcdm/LdProof.java
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/LDSigningServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/SigningServiceTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27991 Stabilize realm_settings_user_profile_enabled test (#27982)
  js/apps/admin-ui/cypress/e2e/realm_settings_user_profile_enabled.spec.ts
Labels: team/ui

#27935 Fix Signing in page
  js/apps/account-ui/src/account-security/SigningIn.tsx
  js/apps/account-ui/src/components/datalist/EmptyRow.tsx
  js/apps/account-ui/test/account-security/signing-in.spec.ts
  js/libs/ui-shared/src/continue-cancel/ContinueCancelModal.tsx
Labels: team/ui

#27985 no result to parse on success
  js/apps/account-ui/src/account-security/AccountRow.tsx
  js/apps/account-ui/src/api/methods.ts
  services/src/main/java/org/keycloak/services/resources/account/LinkedAccountsResource.java
Labels: team/ui

#27902 use includes when it's multi select
  js/libs/ui-shared/src/controls/SelectControl.tsx
Labels: team/ui

#28003 MySQL connector artifact should be ignored
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/IgnoredArtifacts.java
Labels: team/cloud-native, flaky-test

#28005 MySQL connector artifact should be ignored
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/IgnoredArtifacts.java
Labels: team/cloud-native, flaky-test

#27998 enhance: add a note about checking the migration guide
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
Labels: team/cloud-native, flaky-test

#28044 Fix javadoc generation failure introduced with new dependencies
  services/pom.xml
Labels: flaky-test

#27652 introduced password control
  js/apps/admin-ui/cypress/e2e/identity_providers_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/CreateProviderPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseGeneralSettingsPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/providers/ProviderPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
  js/apps/admin-ui/src/clients/credentials/ClientSecret.tsx
  js/apps/admin-ui/src/clients/keys/StoreSettings.tsx
  js/apps/admin-ui/src/components/dynamic/PasswordComponent.tsx
  js/apps/admin-ui/src/identity-providers/add/AddIdentityProvider.tsx
  js/apps/admin-ui/src/identity-providers/component/ClientIdSecret.tsx
  js/apps/admin-ui/src/realm-settings/EmailTab.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsConnection.tsx
  js/apps/admin-ui/src/user/user-credentials/ResetPasswordDialog.tsx
  js/libs/ui-shared/src/controls/PasswordControl.tsx
  js/libs/ui-shared/src/controls/PasswordInput.tsx
  js/libs/ui-shared/src/main.ts
Labels: team/ui

#28046 Attributes without a group should appear first
  services/src/main/java/org/keycloak/forms/login/freemarker/model/AbstractUserProfileBean.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateProfileWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcFirstBrokerLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/VerifyProfileTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28013 fix: making the truststore name field optional
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/Truststore.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakTruststoresTests.java
  operator/src/test/resources/test-serialization-keycloak-cr.yml
Labels: team/cloud-native, flaky-test

#28059 Upgrade Infinispan to 14.0.27.Final
  docs/guides/high-availability/examples/generated/ispn-single.yaml
  docs/guides/high-availability/examples/generated/ispn-site-a.yaml
  docs/guides/high-availability/examples/generated/ispn-site-b.yaml
  pom.xml
Labels: flaky-test

#14793 Correct unique constraints for UserConsent entity
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate25_0_0_ConsentConstraints.java
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate25_0_0_MySQL_ConsentConstraints.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-25.0.0.xml
Labels: flaky-test

#28056 fix test
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
Labels: team/ui

#28043 Fix realm_settings_user_profile_enabled test instability
  js/apps/admin-ui/cypress/downloads/downloads.html
  js/apps/admin-ui/cypress/e2e/realm_settings_user_profile_enabled.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/UserProfile.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/CreateUserPage.ts
Labels: team/ui

#28042 add beerify to account-ui
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
  js/libs/ui-shared/src/main.ts
  js/libs/ui-shared/src/user-profile/utils.ts
Labels: team/ui

#28075 Fix JS build on Windows (#27806)
  js/pom.xml
Labels: team/ui, flaky-test

#28074 Fix realm_settings_user_profile_enabled test instability
  js/apps/admin-ui/cypress/downloads/downloads.html
  js/apps/admin-ui/cypress/e2e/realm_settings_user_profile_enabled.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/UserProfile.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/CreateUserPage.ts
Labels: team/ui

#28076 Fix Signing in page (#27935)
  js/apps/account-ui/src/account-security/SigningIn.tsx
  js/apps/account-ui/src/components/datalist/EmptyRow.tsx
  js/apps/account-ui/test/account-security/signing-in.spec.ts
  js/libs/ui-shared/src/continue-cancel/ContinueCancelModal.tsx
Labels: team/ui

#28082 backport add beerify to account-ui
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
  js/libs/ui-shared/src/main.ts
  js/libs/ui-shared/src/user-profile/utils.ts
Labels: team/ui

#28053 User Profile attribute translation saves correct key to realm overrides
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
Labels: team/ui

#27239 Refactoring JavaScript code of WebAuthn's authenticators to follow the current Keycloak's JavaScript coding convention
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/WebAuthnLoginPage.java
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/WebAuthnRegisterPage.java
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/resources/js/base64url.js
  themes/src/main/resources/theme/base/login/resources/js/webauthnAuthenticate.js
  themes/src/main/resources/theme/base/login/resources/js/webauthnRegister.js
  themes/src/main/resources/theme/base/login/template.ftl
  themes/src/main/resources/theme/base/login/webauthn-authenticate.ftl
  themes/src/main/resources/theme/base/login/webauthn-register.ftl
  themes/src/main/resources/theme/keycloak/common/resources/package.json
  themes/src/main/resources/theme/keycloak/common/resources/pnpm-lock.yaml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28091 Attributes without a group should appear first
  services/src/main/java/org/keycloak/forms/login/freemarker/model/AbstractUserProfileBean.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateProfileWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcFirstBrokerLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/VerifyProfileTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28092 more waits to stabilize test
  js/apps/admin-ui/cypress/downloads/downloads.html
  js/apps/admin-ui/cypress/e2e/realm_settings_general_tab_test.spec.ts
Labels: team/ui

#28050 Multi datasource configuration does not work
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/IgnoredArtifacts.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/IgnoredArtifactsTest.java
  quarkus/runtime/src/test/resources/META-INF/services/quarkus.properties
Labels: team/cloud-native, flaky-test

#28051 Multi datasource configuration does not work
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/IgnoredArtifacts.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/IgnoredArtifactsTest.java
  quarkus/runtime/src/test/resources/META-INF/services/quarkus.properties
Labels: team/cloud-native, flaky-test

#28085 Upgrading to Quarkus 3.8.3
  pom.xml
  testsuite/integration-arquillian/pom.xml
Labels: team/cloud-native, team/core-clients, team/core-iam
