Repository keycloak/keycloak, pull requests merged in 2024-06, with the labels that each got.

#30045 auth-server-feature does not work for auth-server-quarkus-embedded
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
Labels: team/cloud-native, team/core-clients, team/core-iam

#30022 Improve the cleanup after a failed test to ensure retries work
  .github/actions/conditional/conditions
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/SessionTimeoutsTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30057 Backchannel logout url with curly brackets
  services/src/main/java/org/keycloak/validation/DefaultClientValidationProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/DefaultClientValidationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#30020 Fix creation of domains when creating the organization
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  server-spi-private/src/main/java/org/keycloak/organization/OrganizationProvider.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationsResource.java
Labels: flaky-test

#30041 Ignore unknown realms when migrating sessions
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java
Labels: flaky-test

#30071 Fix various linting issues for Account Console
  js/apps/account-ui/src/account-security/AccountRow.tsx
  js/apps/account-ui/src/account-security/DeviceActivity.tsx
  js/apps/account-ui/src/api.ts
  js/apps/account-ui/src/api/representations.ts
  js/apps/account-ui/src/api/request.ts
  js/apps/account-ui/src/applications/Applications.tsx
  js/apps/account-ui/src/oid4vci/Oid4Vci.tsx
  js/apps/account-ui/src/resources/ResourcesTab.tsx
  js/apps/account-ui/src/routes.tsx
  js/apps/account-ui/test/oid4vci/oid4vci.spec.ts
Labels: area/account/ui, kind/task, team/ui

#30051 Allow to configure if users are automatically redirected when the email domain matches an organization
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/organizations/LinkIdentityProviderModal.tsx
  server-spi/src/main/java/org/keycloak/models/OrganizationModel.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractBrokerSelfRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#29973 Use correct PNPM workspace names on CI
  .github/workflows/js-ci.yml
  js/apps/account-ui/playwright.config.ts
  js/apps/account-ui/src/resources/ShareTheResource.tsx
  js/apps/account-ui/test/account-security.spec.ts
  js/apps/account-ui/test/applications.spec.ts
  js/apps/account-ui/test/my-resources.spec.ts
  js/apps/account-ui/test/oid4vci/oid4vci.spec.ts
  js/apps/account-ui/test/personal-info/personal-info.spec.ts
  js/apps/account-ui/test/realm.setup.ts
  js/apps/keycloak-server/scripts/start-server.js
Labels: team/ui, flaky-test

#30069 Update RFC reference in subject: Likely typo RFC2553 -> RFC2253, Consider RFC4514
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_pl.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_CN.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/core-clients

#30055 Editing built-in client policy profiles are silently reverted
  core/src/main/java/org/keycloak/representations/idm/ClientPolicyExecutorRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/ClientProfileRepresentation.java
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/ProfilesTab.tsx
  services/src/main/java/org/keycloak/services/clientpolicy/ClientPoliciesUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesLoadUpdateTest.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#30082 Add Playwright ESLint plugin
  eslint.config.js
  package.json
  pnpm-lock.yaml
Labels: area/account/ui, kind/task, team/ui

#29956 Fixes the auth url for account and admin
  js/apps/account-ui/src/root/Root.tsx
  js/libs/ui-shared/src/context/KeycloakContext.tsx
Labels: team/ui

#30001 reset selected after action
  js/apps/admin-ui/src/components/role-mapping/RoleMapping.tsx
  js/apps/admin-ui/src/user/UserGroups.tsx
Labels: team/ui

#30096 Remove the transformed output directory before executing JakartaTransformer
  adapters/saml/core-jakarta/pom.xml
  adapters/saml/wildfly-elytron-jakarta/pom.xml
  adapters/saml/wildfly/wildfly-jakarta-subsystem/pom.xml
  integration/admin-client/pom.xml
  testsuite/integration-arquillian/test-apps/servlets-jakarta/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29842 Add support for application/jwt media-type in token introspection
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  services/src/main/java/org/keycloak/protocol/oidc/AccessTokenIntrospectionProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenIntrospectionEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenIntrospectionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#30117 Revert "Fixes the auth url for account and admin"
  js/apps/account-ui/src/root/Root.tsx
  js/libs/ui-shared/src/context/KeycloakContext.tsx
Labels: team/ui

#29906 Upgrade supported PostgreSQL to version 16
  pom.xml
Labels: flaky-test

#29904 Upgrade supported PostgreSQL to version 16
  pom.xml
Labels: flaky-test

#29938 Execute Aurora DB cleanup in a separate workflow to prevent timeout o…
  .github/actions/aurora-delete-database/action.yml
  .github/workflows/aurora-delete.yml
  .github/workflows/ci.yml
Labels: flaky-test

#29959 🐛 Fix unclosed span bracket in register.ftl
  themes/src/main/resources/theme/keycloak.v2/login/register.ftl
Labels: flaky-test

#29812 remove use of deprecated table component
  js/apps/admin-ui/cypress/e2e/clients_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/RoleMappingTab.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/tabs/InitialAccessTokenTab.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/groups/group_details/GroupDetailPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_roles/AssociatedRolesPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/UserProfile.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/UserRegistration.ts
  js/apps/admin-ui/src/components/table-toolbar/KeycloakDataTable.tsx
  js/apps/admin-ui/src/realm-settings/keys/KeysListTab.tsx
  js/apps/admin-ui/src/sessions/SessionsTable.tsx
  js/apps/admin-ui/src/user/UserGroups.tsx
  js/apps/admin-ui/src/user/UserIdentityProviderLinks.tsx
Labels: team/ui

#30131 Workaround for #30120
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
Labels: team/cloud-native

#30135 Malformed dependency version causing the build failure
  testsuite/integration-arquillian/tests/base/pom.xml
Labels: team/cloud-native, team/core-clients, team/core-iam

#30142 Introduce count method to avoid fetching all organization upon checki…
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/OrganizationEntity.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  server-spi-private/src/main/java/org/keycloak/organization/OrganizationProvider.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#30149 Ensure that Java's ForkJoinPool is initialized with Quarkus' ThreadPoolFactory
  quarkus/dist/src/main/content/bin/kc.bat
  quarkus/dist/src/main/content/bin/kc.sh
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java
  quarkus/tests/integration/pom.xml
Labels: team/cloud-native, flaky-test

#30007 Export import realm with organizations
  core/src/main/java/org/keycloak/representations/idm/OrganizationRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/RealmRepresentation.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  model/storage-private/src/main/java/org/keycloak/exportimport/util/ExportUtils.java
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  server-spi-private/src/main/java/org/keycloak/exportimport/ExportOptions.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationExportTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30114 Encrypted KC_RESTART cookie and removed sensitive notes
  docs/documentation/release_notes/index.adoc
  docs/documentation/release_notes/topics/24_0_5.adoc
  services/src/main/java/org/keycloak/jose/jws/DefaultTokenManager.java
  services/src/main/java/org/keycloak/protocol/RestartLoginCookie.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthzEndpointRequestParser.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RestartCookieTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/keys/FallbackKeyProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30116 Missing auth checks in some admin endpoints (#166)
  federation/ldap/src/main/java/org/keycloak/services/resources/admin/TestLdapConnectionResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientRegistrationPolicyResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/PermissionsTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30103 Updating client policies in JSON editor is buggy. Attempt to update g…
  core/src/main/java/org/keycloak/representations/idm/ClientPolicyConditionRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/ClientPolicyRepresentation.java
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/PoliciesTab.tsx
  services/src/main/java/org/keycloak/services/clientpolicy/ClientPoliciesUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/securityprofile/StrictSecurityProfileTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#30106 Prevent users to unlink their home identity provider when they are a managed member
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  services/src/main/java/org/keycloak/organization/validator/OrganizationMemberValidator.java
  services/src/main/java/org/keycloak/services/messages/Messages.java
  services/src/main/java/org/keycloak/services/resources/account/LinkedAccountsResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationAccountTest.java
  themes/src/main/resources/theme/base/account/messages/messages_en.properties
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#30078 fixed flaky-ness and removed deprecated select
  js/apps/admin-ui/cypress/e2e/realm_settings_user_profile_enabled.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/CreateUserPage.ts
  js/apps/admin-ui/cypress/support/util/AdminClient.ts
  js/apps/admin-ui/src/components/key-value-form/ValueSelect.tsx
  js/libs/ui-shared/src/user-profile/SelectComponent.tsx
  js/libs/ui-shared/src/user-profile/UserProfileFields.tsx
Labels: team/ui

#30121 Aggregated javadoc generation fix
  distribution/api-docs-dist/pom.xml
Labels: flaky-test

#30163 Add files in project root to JS conditional workflow
  .github/actions/conditional/conditions
Labels: kind/task, flaky-test

#30125 Align environment variables between consoles
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  js/apps/account-ui/README.md
  js/apps/account-ui/pom.xml
  js/apps/account-ui/src/api.ts
  js/apps/account-ui/src/api/methods.ts
  js/apps/account-ui/src/api/request.ts
  js/apps/account-ui/src/environment.ts
  js/apps/account-ui/src/i18n.ts
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
  js/apps/account-ui/src/root/Header.tsx
  js/apps/account-ui/src/root/PageNav.tsx
  js/apps/account-ui/src/root/Root.tsx
  js/apps/account-ui/src/routes.tsx
  js/apps/admin-ui/pom.xml
  js/apps/admin-ui/src/App.tsx
  js/apps/admin-ui/src/Root.tsx
  js/apps/admin-ui/src/admin-client.ts
  js/apps/admin-ui/src/environment.ts
  js/apps/admin-ui/src/i18n/i18n.ts
  js/apps/admin-ui/src/identity-providers/add/SamlConnectSettings.tsx
  js/apps/admin-ui/src/identity-providers/add/SamlGeneralSettings.tsx
  js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
  js/libs/ui-shared/src/context/KeycloakContext.tsx
  js/libs/ui-shared/src/context/environment.ts
  js/libs/ui-shared/src/main.ts
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
  services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java
Labels: team/ui, flaky-test

#30175 Fixing forkjoin pool factory validation when running embedded server
  quarkus/tests/junit5/src/main/java/org/keycloak/Keycloak.java
Labels: team/cloud-native, flaky-test

#30173 Upgrade to Quarkus 3.8.5
  pom.xml
Labels: flaky-test

#29990 Upgrade Groovy dependencies to latest version
  distribution/maven-plugins/pom.xml
Labels: area/dependencies, kind/task, flaky-test

#30127 fix oid4vci tests
  js/apps/account-ui/src/oid4vci/Oid4Vci.tsx
  js/apps/account-ui/test/oid4vci/oid4vci.spec.ts
Labels: team/ui, flaky-test

#30197 Use Quarkus fork join worker for Test PoC
  test-poc/base/pom.xml
Labels: flaky-test

#30207 Adding ForkJoinPool for Quarkus to the surefire initialization for emedded Quarkus
  testsuite/integration-arquillian/tests/pom.xml
Labels: team/cloud-native, team/core-clients, team/core-iam

#29752 Backports for test stability
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakStatus.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
Labels: team/cloud-native, flaky-test

#29942 Update license headers
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/cli/OsArch.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/cli/OsUtils.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29430 fix: adds handling for a KC_CLI_PASSWORD env variable
  docs/documentation/server_admin/topics/admin-cli.adoc
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/KcAdmMain.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractAuthOptionsCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AddRolesCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/CreateCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/DeleteCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/GetCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/GetRolesCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/HelpCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/RemoveRolesCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/SetPasswordCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/UpdateCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/common/BaseAuthOptionsCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/common/BaseConfigCredentialsCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/common/BaseConfigTruststoreCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/common/CommandState.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/util/IoUtil.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/registration/cli/KcRegMain.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/registration/cli/commands/CreateCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/registration/cli/commands/DeleteCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/registration/cli/commands/GetCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/registration/cli/commands/HelpCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/registration/cli/commands/UpdateCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/registration/cli/commands/UpdateTokenCmd.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/AbstractAdmCliTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmSessionTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29536 fix: minor refinements to collection utils
  common/src/main/java/org/keycloak/common/util/CollectionUtil.java
  common/src/main/java/org/keycloak/common/util/ConcurrentMultivaluedHashMap.java
  common/src/main/java/org/keycloak/common/util/MultivaluedHashMap.java
  common/src/main/java/org/keycloak/common/util/MultivaluedMap.java
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDistConfigurator.java
Labels: team/cloud-native, flaky-test, team/core-shared

#30013 Snyk report to identify branches impacted by a CVE
  .github/scripts/snyk-report.sh
Labels: flaky-test

#30014 [Backport] Snyk report to identify branches impacted by a CVE
  .github/scripts/snyk-report.sh
  .github/workflows/snyk-analysis.yml
Labels: status/hold, flaky-test

#30101 Make sure configuration is loaded with mapped/transformed properties …
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartDevCommandDistTest.java
Labels: team/cloud-native, flaky-test

#29638 Refactor remote cache feature code
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/remote/RemoteInfinispanClusterProvider.java
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/remote/RemoteInfinispanClusterProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/remote/RemoteInfinispanNotificationManager.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/remote/RemoteInfinispanConnectionProvider.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/remote/RemoteLoadBalancerCheckProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/infinispan/util/InfinispanUtils.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanAuthenticationSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanSingleUseObjectProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanStickySessionEncoderProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/SessionEntityUpdater.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteInfinispanAuthenticationSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteInfinispanAuthenticationSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteInfinispanKeycloakTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteInfinispanSingleUseObjectProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteInfinispanSingleUseObjectProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteStickySessionEncoderProviderFactory.java
  model/storage-private/src/main/java/org/keycloak/cluster/ClusterProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/models/SingleUseObjectProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/sessions/AuthenticationSessionProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/sessions/StickySessionEncoderProviderFactory.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/FeatureEnabledTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/RemoteInfinispan.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/SessionTimeoutsTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30212 Pin Ansible version for Aurora Store IT tests to 9.x.y stream
  .github/scripts/ansible/aws_ec2.sh
  .github/workflows/ci.yml
Labels: flaky-test

#29847 Generate RESTART_AUTHENTICATION event on success Closes #29385
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  services/src/main/java/org/keycloak/services/resources/SessionCodeChecks.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultiFactorAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RestartCookieTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29848 Generate RESTART_AUTHENTICATION event on success
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  services/src/main/java/org/keycloak/services/resources/SessionCodeChecks.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultiFactorAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RestartCookieTest.java
Labels: team/cloud-native, flaky-test

#29493 Default SAML client type
  services/src/main/java/org/keycloak/services/clienttype/client/TypeAwareClientModelDelegate.java
  services/src/main/java/org/keycloak/services/clienttype/client/TypedClientAttribute.java
  services/src/main/resources/keycloak-default-client-types.json
Labels: flaky-test

#29966 Improvements to refresh token rotation
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/AuthenticatedClientSessionAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/JpaChangesPerformer.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/AuthenticatedClientSessionEntity.java
  model/storage-private/src/main/java/org/keycloak/models/session/PersistentAuthenticatedClientSessionAdapter.java
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  server-spi/src/main/java/org/keycloak/models/AuthenticatedClientSessionModel.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/test/java/org/keycloak/protocol/TestAuthenticatedClientSessionModel.java
  services/src/test/java/org/keycloak/protocol/docker/mapper/TestAuthenticatedClientSessionModel.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/migration-test/migration-realm-24.0.4.json
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#30225 Improvements for openapi annotations in AuthenticationManagementResource
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java
Labels: flaky-test

#30244 Add ability to get realm attributes from RealmBean
  services/src/main/java/org/keycloak/forms/login/freemarker/model/RealmBean.java
Labels: flaky-test

#30238 Display the webauthn sig-alg in computer language in the template
  themes/src/main/resources/theme/base/login/webauthn-register.ftl
Labels: flaky-test

#30191 prevent freemarker exceptions from unavailable properties
  themes/src/main/resources/theme/base/login/login-recovery-authn-code-config.ftl
  themes/src/main/resources/theme/base/login/webauthn-register.ftl
Labels: team/ui, flaky-test

#30209 move keycloak select to ui-shared and fix typeahead
  js/apps/account-ui/test/personal-info/personal-info.spec.ts
  js/apps/admin-ui/cypress.config.js
  js/apps/admin-ui/cypress/e2e/realm_settings_user_profile_enabled.spec.ts
  js/apps/admin-ui/src/clients/authorization/KeyBasedAttributeInput.tsx
  js/apps/admin-ui/src/clients/authorization/PermissionDetails.tsx
  js/apps/admin-ui/src/clients/authorization/ResourcesPolicySelect.tsx
  js/apps/admin-ui/src/clients/authorization/ScopePicker.tsx
  js/apps/admin-ui/src/clients/authorization/ScopeSelect.tsx
  js/apps/admin-ui/src/clients/scopes/AddScopeDialog.tsx
  js/apps/admin-ui/src/clients/scopes/EvaluateScopes.tsx
  js/apps/admin-ui/src/components/dynamic/ListComponent.tsx
  js/apps/admin-ui/src/components/dynamic/MultivaluedListComponent.tsx
  js/apps/admin-ui/src/components/key-value-form/KeySelect.tsx
  js/apps/admin-ui/src/components/key-value-form/ValueSelect.tsx
  js/apps/admin-ui/src/components/time-selector/TimeSelector.tsx
  js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx
  js/apps/admin-ui/src/events/AdminEvents.tsx
  js/apps/admin-ui/src/events/EventsSection.tsx
  js/apps/admin-ui/src/identity-providers/add/AddMapperForm.tsx
  js/apps/admin-ui/src/identity-providers/add/AdvancedSettings.tsx
  js/apps/admin-ui/src/identity-providers/add/ExtendedNonDiscoverySettings.tsx
  js/apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx
  js/apps/admin-ui/src/identity-providers/add/ReqAuthnConstraintsSettings.tsx
  js/apps/admin-ui/src/realm-settings/ExecutorForm.tsx
  js/apps/admin-ui/src/realm-settings/NewClientPolicyCondition.tsx
  js/apps/admin-ui/src/realm-settings/PartialImport.tsx
  js/apps/admin-ui/src/realm-settings/ThemesTab.tsx
  js/apps/admin-ui/src/realm-settings/TokensTab.tsx
  js/apps/admin-ui/src/realm-settings/keys/KeysListTab.tsx
  js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx
  js/apps/admin-ui/src/realm-settings/localization/RealmOverrides.tsx
  js/apps/admin-ui/src/realm-settings/security-defences/BruteForceDetection.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesTab.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/ValidatorSelect.tsx
  js/apps/admin-ui/src/sessions/SessionsSection.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsConnection.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsGeneral.tsx
  js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx
  js/apps/admin-ui/src/user-federation/shared/SettingsCache.tsx
  js/apps/admin-ui/src/user/details/SearchFilter.tsx
  js/libs/ui-shared/src/controls/select-control/SingleSelectControl.tsx
  js/libs/ui-shared/src/controls/select-control/TypeaheadSelectControl.tsx
  js/libs/ui-shared/src/main.ts
  js/libs/ui-shared/src/select/KeycloakSelect.tsx
  js/libs/ui-shared/src/select/SingleSelect.tsx
  js/libs/ui-shared/src/select/TypeaheadSelect.tsx
  js/libs/ui-shared/src/user-profile/SelectComponent.tsx
Labels: team/ui, flaky-test

#30159 fixed display value
  js/apps/admin-ui/src/clients/scopes/EvaluateScopes.tsx
Labels: team/ui

#30252 changed to use the right query
  js/apps/admin-ui/src/components/role-mapping/queries.ts
Labels: team/ui

#30170 Enhance documentation regarding edge termination
  docs/guides/server/reverseproxy.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/ProxyOptions.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#30295 Fix Quarkus development mode
  quarkus/server/pom.xml
Labels: team/cloud-native

#30298 Logout from all clients after IdP logout is performed
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerLogoutTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30056 Client type configuration inheritance
  core/src/main/java/org/keycloak/representations/idm/ClientTypeRepresentation.java
  server-spi-private/src/main/java/org/keycloak/client/clienttype/ClientType.java
  server-spi-private/src/main/java/org/keycloak/client/clienttype/ClientTypeException.java
  server-spi-private/src/main/java/org/keycloak/client/clienttype/ClientTypeProvider.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  services/src/main/java/org/keycloak/services/clienttype/DefaultClientTypeManager.java
  services/src/main/java/org/keycloak/services/clienttype/client/TypeAwareClientModelDelegate.java
  services/src/main/java/org/keycloak/services/clienttype/client/TypedClientAttribute.java
  services/src/main/java/org/keycloak/services/clienttype/impl/DefaultClientType.java
  services/src/main/java/org/keycloak/services/clienttype/impl/DefaultClientTypeProvider.java
  services/src/main/resources/keycloak-default-client-types.json
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientTypesTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30269 Activate Save Button in Client Scopes on first modification
  js/apps/admin-ui/src/client-scopes/details/ScopeForm.tsx
Labels: team/ui

#30307 add missing doXXX methods with KeycloakSession usage
  server-spi-private/src/main/java/org/keycloak/broker/provider/util/SimpleHttp.java
Labels: flaky-test

#30322 Logout from all clients after IdP logout is performed
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerLogoutTest.java
Labels: team/cloud-native

#30321 Logout from all clients after IdP logout is performed Closes #25234
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerLogoutTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#30320 Logout from all clients after IdP logout is performed Closes #25234
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerLogoutTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29907 Add support of RTL UI in login pages
  services/src/main/java/org/keycloak/theme/beans/LocaleBean.java
  themes/src/main/resources/theme/base/login/login-config-totp.ftl
  themes/src/main/resources/theme/base/login/login-oauth2-device-verify-user-code.ftl
  themes/src/main/resources/theme/base/login/login-otp.ftl
  themes/src/main/resources/theme/base/login/login-passkeys-conditional-authenticate.ftl
  themes/src/main/resources/theme/base/login/login-password.ftl
  themes/src/main/resources/theme/base/login/login-recovery-authn-code-input.ftl
  themes/src/main/resources/theme/base/login/login-reset-password.ftl
  themes/src/main/resources/theme/base/login/login-update-password.ftl
  themes/src/main/resources/theme/base/login/login-username.ftl
  themes/src/main/resources/theme/base/login/login.ftl
  themes/src/main/resources/theme/base/login/register.ftl
  themes/src/main/resources/theme/base/login/template.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-config-totp.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-update-password.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login.ftl
  themes/src/main/resources/theme/keycloak.v2/login/register.ftl
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
Labels: team/ui, flaky-test

#30331 [Admin-UI] Fix Client secret rotation UI
  js/apps/admin-ui/src/clients/credentials/ClientSecret.tsx
Labels: team/ui

#30038 stabilize realm setting test
  js/apps/admin-ui/cypress/e2e/realm_settings_general_tab_test.spec.ts
Labels: team/ui

#30208 Allow multiple instances of the same social broker in a realm
  docs/documentation/release_notes/index.adoc
  docs/documentation/release_notes/topics/26_0_0.adoc
  js/apps/admin-ui/src/identity-providers/add/AddIdentityProvider.tsx
  js/apps/admin-ui/src/identity-providers/add/DetailSettings.tsx
  js/apps/admin-ui/src/identity-providers/add/GeneralSettings.tsx
  services/src/main/java/org/keycloak/forms/login/freemarker/model/IdentityProviderBean.java
Labels: team/ui, flaky-test

#30350 add missing doXXX methods with KeycloakSession usage
  server-spi-private/src/main/java/org/keycloak/broker/provider/util/SimpleHttp.java
Labels: flaky-test

#30348 Enhance masking around config-keystore
  docs/guides/server/configuration.adoc
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakConfigSourceProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ConfigKeystorePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/ShowConfigCommandTest.java
  quarkus/tests/integration/src/test/resources/ShowConfigCommandTest/keycloak-keystore.conf
Labels: team/cloud-native, flaky-test

#30345 Use only plain hostname in Ingress
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngressDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/IngressLogicTest.java
Labels: team/cloud-native, flaky-test

#30363 Enhance masking around config-keystore (#30348)
  docs/guides/server/configuration.adoc
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakConfigSourceProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ConfigKeystorePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/ShowConfigCommandTest.java
  quarkus/tests/integration/src/test/resources/ShowConfigCommandTest/keycloak-keystore.conf
Labels: team/cloud-native, flaky-test

#30370 fix label error for persistent-user-sessions feature flag in document…
  docs/documentation/release_notes/topics/25_0_0.adoc
  docs/documentation/server_admin/topics/sessions.adoc
  docs/documentation/server_admin/topics/sessions/offline.adoc
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  docs/documentation/upgrading/topics/prep_migration.adoc
  docs/guides/server/caching.adoc
Labels: team/cross-dc

#30371 fix label error for persistent-user-sessions feature flag in documentation
  docs/documentation/release_notes/topics/25_0_0.adoc
  docs/documentation/server_admin/topics/sessions.adoc
  docs/documentation/server_admin/topics/sessions/offline.adoc
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  docs/documentation/upgrading/topics/prep_migration.adoc
  docs/guides/server/caching.adoc
Labels: team/cloud-native

#30369 Remove link to management interface guide from ignored links in docs
  docs/documentation/tests/src/test/resources/ignored-links
Labels: flaky-test

#27311 Run the Vite dev server through the Keycloak server
  .github/workflows/js-ci.yml
  common/src/main/java/org/keycloak/common/util/Environment.java
  core/pom.xml
  core/src/main/java/org/keycloak/util/JsonSerialization.java
  js/apps/account-ui/index.html
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/index.ftl
  js/apps/account-ui/playwright.config.ts
  js/apps/account-ui/pom.xml
  js/apps/account-ui/src/utils/getRootPath.ts
  js/apps/account-ui/test/account-security/linked-accounts.spec.ts
  js/apps/account-ui/test/admin-client.ts
  js/apps/account-ui/test/applications.spec.ts
  js/apps/account-ui/test/constants.ts
  js/apps/account-ui/test/login.ts
  js/apps/account-ui/test/referrer.spec.ts
  js/apps/account-ui/test/utils.ts
  js/apps/account-ui/vite.config.ts
  js/apps/admin-ui/cypress/e2e/identity_providers_oidc_test.spec.ts
  js/apps/admin-ui/cypress/e2e/identity_providers_saml_test.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_settings_general_tab_test.spec.ts
  js/apps/admin-ui/cypress/support/constants.ts
  js/apps/admin-ui/cypress/support/e2e.ts
  js/apps/admin-ui/cypress/support/util/AdminClient.ts
  js/apps/admin-ui/index.html
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/index.ftl
  js/apps/admin-ui/pom.xml
  js/apps/admin-ui/src/authentication/__tests__/FlowDiagram.test.tsx
  js/apps/admin-ui/vite.config.ts
  js/apps/keycloak-server/README.md
  js/apps/keycloak-server/package.json
  js/apps/keycloak-server/scripts/security-admin-console-v2.json
  js/apps/keycloak-server/scripts/start-server.js
  js/libs/ui-shared/src/context/environment.ts
  pnpm-lock.yaml
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Environment.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Messages.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Start.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/Configuration.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakConfigSourceProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
  services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java
  services/src/main/java/org/keycloak/services/util/Chunk.java
  services/src/main/java/org/keycloak/services/util/ViteManifest.java
Labels: team/cloud-native, team/ui, flaky-test

#30287 Add translation for oid4vc protocol name
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/utils.ts
Labels: team/ui

#30365 small fix to npm package
  js/apps/account-ui/src/index.ts
  js/apps/account-ui/vite.config.ts
Labels: team/ui, flaky-test

#30372 Remove adapter app-server-undertow profile which is not used
  testsuite/integration-arquillian/servers/app-server/pom.xml
  testsuite/integration-arquillian/servers/app-server/undertow/pom.xml
  testsuite/integration-arquillian/servers/app-server/undertow/src/main/java/org/keycloak/testsuite/arquillian/undertow/UndertowAppServer.java
  testsuite/integration-arquillian/servers/app-server/undertow/src/main/java/org/keycloak/testsuite/arquillian/undertow/UndertowAppServerArquillianExtension.java
  testsuite/integration-arquillian/servers/app-server/undertow/src/main/java/org/keycloak/testsuite/arquillian/undertow/UndertowAppServerConfiguration.java
  testsuite/integration-arquillian/servers/app-server/undertow/src/main/java/org/keycloak/testsuite/arquillian/undertow/container/UndertowAppServerProvider.java
  testsuite/integration-arquillian/servers/app-server/undertow/src/main/java/org/keycloak/testsuite/arquillian/undertow/container/UndertowDeploymentArchiveProcessor.java
  testsuite/integration-arquillian/servers/app-server/undertow/src/main/java/org/keycloak/testsuite/arquillian/undertow/saml/util/RestSamlApplicationConfig.java
  testsuite/integration-arquillian/servers/app-server/undertow/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  testsuite/integration-arquillian/servers/app-server/undertow/src/main/resources/META-INF/services/org.keycloak.testsuite.arquillian.container.AppServerContainerProvider
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLClockSkewAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLLoginResponseHandlingTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLLogoutAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletSessionTimeoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SamlSignatureTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SamlXMLAttacksTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/undertow/servlet/UndertowRelaviteUriAdapterTest.java
  testsuite/integration-arquillian/util/src/main/java/org/keycloak/testsuite/utils/arquillian/ContainerConstants.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30336 Add step to Google Social Login (#30335)
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java
Labels: flaky-test, team/continuous-testing

#30382 Remove jakarta imports from admin-client-jee resources
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/ClientTypesResource.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationIdentityProviderResource.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationIdentityProvidersResource.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationMemberResource.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationMembersResource.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationResource.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationsResource.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/RealmResource.java
Labels: flaky-test

#30373 Run the Vite dev server through the Keycloak server (#27311)
  .github/workflows/js-ci.yml
  common/src/main/java/org/keycloak/common/util/Environment.java
  core/pom.xml
  core/src/main/java/org/keycloak/util/JsonSerialization.java
  js/apps/account-ui/index.html
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/index.ftl
  js/apps/account-ui/playwright.config.ts
  js/apps/account-ui/pom.xml
  js/apps/account-ui/src/utils/getRootPath.ts
  js/apps/account-ui/test/account-security/linked-accounts.spec.ts
  js/apps/account-ui/test/admin-client.ts
  js/apps/account-ui/test/applications.spec.ts
  js/apps/account-ui/test/constants.ts
  js/apps/account-ui/test/login.ts
  js/apps/account-ui/test/referrer.spec.ts
  js/apps/account-ui/test/utils.ts
  js/apps/account-ui/vite.config.ts
  js/apps/admin-ui/cypress/e2e/identity_providers_oidc_test.spec.ts
  js/apps/admin-ui/cypress/e2e/identity_providers_saml_test.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_settings_general_tab_test.spec.ts
  js/apps/admin-ui/cypress/support/constants.ts
  js/apps/admin-ui/cypress/support/e2e.ts
  js/apps/admin-ui/cypress/support/util/AdminClient.ts
  js/apps/admin-ui/index.html
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/index.ftl
  js/apps/admin-ui/pom.xml
  js/apps/admin-ui/src/authentication/__tests__/FlowDiagram.test.tsx
  js/apps/admin-ui/vite.config.ts
  js/apps/keycloak-server/README.md
  js/apps/keycloak-server/package.json
  js/apps/keycloak-server/scripts/security-admin-console-v2.json
  js/apps/keycloak-server/scripts/start-server.js
  js/libs/ui-shared/src/context/environment.ts
  pnpm-lock.yaml
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Environment.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Messages.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Start.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/Configuration.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakConfigSourceProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
  services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java
  services/src/main/java/org/keycloak/services/util/Chunk.java
  services/src/main/java/org/keycloak/services/util/ViteManifest.java
Labels: team/cloud-native, team/ui, flaky-test

#30352 Migration of sessions in KC25 should run only on migration, not on imports
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo25_0_0.java
Labels: flaky-test

#30388 Migration of sessions in KC25 should run only on migration, not on imports
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo25_0_0.java
Labels: flaky-test

#30401 quarkus-next: adjust HelpCommandDistTest templates
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#30403 Fix current page highlight in Account UI sidebar navigation
  js/apps/account-ui/public/content.json
  js/apps/account-ui/src/root/PageNav.tsx
Labels: team/ui, flaky-test

#30406 [#29412] DB Allocator removal - dependency cleanup.
  docs/tests-db.md
  testsuite/db-allocator-plugin/pom.xml
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/AllocateDBMojo.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/Constants.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/ReleaseDBMojo.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/client/BackoffRetryPolicy.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/client/DBAllocatorServiceClient.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/client/data/AllocationResult.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/client/data/EraseResult.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/client/data/ReleaseResult.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/client/exceptions/DBAllocatorException.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/client/exceptions/DBAllocatorUnavailableException.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/client/retry/IncrementalBackoffRetryPolicy.java
  testsuite/db-allocator-plugin/src/test/java/org/keycloak/testsuite/dballocator/client/DBAllocatorServiceClientTest.java
  testsuite/db-allocator-plugin/src/test/java/org/keycloak/testsuite/dballocator/client/mock/MockResponse.java
  testsuite/db-allocator-plugin/src/test/java/org/keycloak/testsuite/dballocator/client/retry/IncrementalBackoffRetryPolicyTest.java
  testsuite/db-allocator-plugin/src/test/resources/db-allocator-response.properties
  testsuite/db-allocator-plugin/src/test/resources/log4j.properties
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/pom.xml
Labels: team/cloud-native, team/core-clients, team/core-iam

#30366 use subGroupCount to render subGroups (#28173)
  js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx
Labels: team/ui

#30416 Fix compilation error
  model/infinispan/src/main/java/org/keycloak/marshalling/KeycloakModelSchema.java
  model/infinispan/src/main/java/org/keycloak/marshalling/Marshalling.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheManager.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/events/CacheKeyInvalidatedEvent.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/InfinispanOrganizationProvider.java
Labels: flaky-test

#30400 Pin Ansible version for Aurora Store IT tests to 9.x.y stream
  .github/scripts/ansible/aws_ec2.sh
  .github/workflows/ci.yml
Labels: flaky-test

#30402 Pin Ansible version for Aurora Store IT tests to 9.x.y stream
  .github/scripts/ansible/aws_ec2.sh
  .github/workflows/ci.yml
Labels: flaky-test

#30394 Add missing space
  docs/guides/server/db.adoc
Labels: team/cloud-native

#29619 feat(SAML): add Artifact Binding on brokering scenarios when Keycloak is SP
  docs/documentation/server_admin/topics/identity-broker/saml.adoc
  js/apps/admin-ui/cypress/e2e/partial_import_test.spec.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx
  saml-core/src/main/java/org/keycloak/saml/SAML2ArtifactResolveRequestBuilder.java
  saml-core/src/main/java/org/keycloak/saml/processing/api/saml/v2/request/SAML2Request.java
  saml-core/src/main/java/org/keycloak/saml/processing/api/saml/v2/response/SAML2Response.java
  services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProviderConfig.java
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProviderFactory.java
  services/src/main/java/org/keycloak/protocol/saml/SamlProtocol.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/saml/ModifySamlResponseStepBuilder.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/saml/SamlBackchannelArtifactResolveReceiver.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlBrokerArtifactBindingTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlBrokerConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmUpdateTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/saml/BrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/saml/LogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/admin-test/saml-idp-metadata-disabled.xml
  testsuite/integration-arquillian/tests/base/src/test/resources/admin-test/saml-idp-metadata-encryption-methods.xml
  testsuite/integration-arquillian/tests/base/src/test/resources/admin-test/saml-idp-metadata-two-signing-certs.xml
  testsuite/integration-arquillian/tests/base/src/test/resources/admin-test/saml-idp-metadata.xml
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#30333 removed version as it's already in the package.json
  js/apps/account-ui/README.md
Labels: team/ui, flaky-test

#30327 add first and max to group member query
  js/apps/admin-ui/src/groups/Members.tsx
  js/apps/admin-ui/src/groups/MembersModal.tsx
  js/apps/admin-ui/src/organizations/Members.tsx
Labels: team/ui

#30325 add label interpolation to description fields
  js/apps/admin-ui/src/clients/ClientsSection.tsx
  js/apps/admin-ui/src/clients/scopes/ClientScopes.tsx
  js/apps/admin-ui/src/components/roles-list/RolesList.tsx
  js/apps/admin-ui/src/realm-settings/AddClientProfileModal.tsx
  js/apps/admin-ui/src/realm-settings/PoliciesTab.tsx
  js/apps/admin-ui/src/realm-settings/event-config/EventsTypeTable.tsx
  js/apps/admin-ui/src/util.ts
Labels: team/ui

#30442 Adding managed dependencies when resolving provider artifacts
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/Maven.java
Labels: team/cloud-native, flaky-test

#30431 Protobuf schema compatibility check (maven plugin)
  model/infinispan/pom.xml
  pom.xml
Labels: flaky-test

#30447 Batch cluster events
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProvider.java
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanNotificationsManager.java
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/WrapperClusterEvent.java
  model/infinispan/src/main/java/org/keycloak/keys/infinispan/InfinispanCachePublicKeyProvider.java
  model/infinispan/src/main/java/org/keycloak/keys/infinispan/InfinispanPublicKeyStorageProvider.java
  model/infinispan/src/main/java/org/keycloak/marshalling/KeycloakModelSchema.java
  model/infinispan/src/main/java/org/keycloak/marshalling/Marshalling.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/CacheManager.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/ClearCacheEvent.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/events/SessionEventsSenderTransaction.java
  server-spi-private/src/main/java/org/keycloak/cluster/ClusterEvent.java
  server-spi-private/src/main/java/org/keycloak/cluster/ClusterProvider.java
Labels: flaky-test

#30439 Improvements for ldap test authentication
  core/src/main/java/org/keycloak/representations/idm/TestLdapConnectionRepresentation.java
  federation/ldap/src/main/java/org/keycloak/services/managers/LDAPServerCapabilitiesManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserFederationLdapConnectionTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30486 Remove `web_modules` from `.gitignore`
  themes/.gitignore
Labels: kind/task, team/ui

#30481 Fix LoginFailureEntity protostream encoding
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserLoginFailureProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/LoginFailureEntity.java
Labels: flaky-test

#29918 Remove Internet Explorer from supported web drivers
  testsuite/integration-arquillian/pom.xml
Labels: kind/eol, team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30422 removed useless cell formatter
  js/apps/admin-ui/src/events/EventsSection.tsx
Labels: team/ui

#30512 Fix AuthenticatedClientSessionEntity protostream encoding
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/AuthenticatedClientSessionEntity.java
Labels: flaky-test

#30199 Fixed refreshing translations on user detail's tab
  js/apps/admin-ui/cypress/e2e/partial_import_test.spec.ts
  js/apps/admin-ui/cypress/fixtures/partial-import-test-data/client-only.json
  js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
  js/apps/admin-ui/src/realm-settings/localization/RealmOverrides.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesGroupForm.tsx
Labels: team/ui

#30510 Fixed issue related to dark mode in DropdownPanel
  js/apps/admin-ui/src/components/dropdown-panel/DropdownPanel.tsx
  js/apps/admin-ui/src/components/dropdown-panel/dropdown-panel.css
  js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx
  js/apps/admin-ui/src/events/AdminEvents.tsx
  js/apps/admin-ui/src/realm-settings/ThemesTab.tsx
  js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx
  js/apps/admin-ui/src/util.ts
Labels: team/ui

#30374 Enable WebAuthn tests for Firefox
  .github/workflows/ci.yml
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/AppInitiatedActionWebAuthnTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/VirtualAuthenticatorsManagerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnIdlessTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnPropertyTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnRegisterAndLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnTransportsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/account/WebAuthnErrorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/account/WebAuthnSigningInTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/account/WebAuthnTransportLocaleTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/passwordless/WebAuthnPwdLessPropertyTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/AttestationConveyanceRegisterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/AuthAttachmentRegisterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/PolicyJsInjectionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/PubKeySignRegisterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/ResidentKeyRegisterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/UserVerificationRegisterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/WebAuthnOtherSettingsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/passwordless/PwdLessAttestationRegTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/passwordless/PwdLessAuthAttachmentRegTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/passwordless/PwdLessPubKeySignRegTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/passwordless/PwdLessResidentKeyRegTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/passwordless/PwdLessUserVerRegTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30119 Unify save-buttons in admin-ui
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/AttributesTab.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/KeyValueInput.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/CreateUserPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/user_details/UserDetailsPage.ts
  js/apps/admin-ui/src/components/form/FixedButtonGroup.tsx
  js/apps/admin-ui/src/components/key-value-form/AttributeForm.tsx
  js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
  js/apps/admin-ui/src/user/UserForm.tsx
Labels: team/ui

#30526 Run JS CI upon change in services
  .github/actions/conditional/conditions
Labels: flaky-test

#30304 Upgrade to Keycloak 25 - Table 'USER_CONSENT' is specified twice on MySQL/MariaDB database
  model/jpa/src/main/resources/META-INF/jpa-changelog-25.0.0.xml
Labels: flaky-test

#30480 Improvements for ldap test authentication (22.0)
  core/src/main/java/org/keycloak/representations/idm/TestLdapConnectionRepresentation.java
  federation/ldap/src/main/java/org/keycloak/services/managers/LDAPServerCapabilitiesManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserFederationLdapConnectionTest.java
Labels: team/cloud-native, flaky-test

#30478 Improvements for ldap test authentication (25.0)
  core/src/main/java/org/keycloak/representations/idm/TestLdapConnectionRepresentation.java
  federation/ldap/src/main/java/org/keycloak/services/managers/LDAPServerCapabilitiesManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserFederationLdapConnectionTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30479 Improvements for ldap test authentication (24.0)
  core/src/main/java/org/keycloak/representations/idm/TestLdapConnectionRepresentation.java
  federation/ldap/src/main/java/org/keycloak/services/managers/LDAPServerCapabilitiesManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserFederationLdapConnectionTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30395 Upgrade adapters test to use wildfly 28 (jakarta only) via maven plugin
  pom.xml
  testsuite/integration-arquillian/servers/app-server/jboss/galleon/pom.xml
  testsuite/integration-arquillian/servers/app-server/jboss/pom.xml
  testsuite/integration-arquillian/servers/app-server/jboss/wildfly/pom.xml
  testsuite/integration-arquillian/test-apps/pom.xml
  testsuite/integration-arquillian/test-apps/servlets-jakarta/.gitignore
  testsuite/integration-arquillian/test-apps/servlets-jakarta/pom.xml
  testsuite/integration-arquillian/test-apps/servlets/pom.xml
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/filter/AdapterActionsFilter.java
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/BasicAuthServlet.java
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/CallAuthenticatedServlet.java
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/ClientInitiatedAccountLinkServlet.java
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/CustomerDatabaseServlet.java
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/CustomerServlet.java
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/CustomerServletNoConf.java
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/ErrorServlet.java
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/InputServlet.java
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/KerberosCredDelegServlet.java
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/MultiTenantServlet.java
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/ProductServlet.java
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/SamlSPFacade.java
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/SendUsernameServlet.java
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/SessionServlet.java
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/example/hal/ConsoleProtectionTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/keycloak-saml/different-cookie-name/WEB-INF/web.xml
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/keycloak-saml/employee-role-mapping/WEB-INF/web.xml
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/keycloak-saml/multi-tenant-saml/WEB-INF/web.xml
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/keycloak-saml/sales-post-clock-skew/WEB-INF/web.xml
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/keycloak-saml/web-with-action-filter.xml
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/keycloak-saml/web.xml
  testsuite/integration-arquillian/tests/base/src/test/resources/wildfly-integration/wildfly-management-realm.json
  testsuite/integration-arquillian/tests/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30420 Enhance SupportedCredentialConfiguration to support optional claims object as defined in OpenID for Verifiable Credential Issuance specification
  services/src/main/java/org/keycloak/protocol/oid4vc/model/Claim.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/ClaimDisplay.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/Claims.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/DisplayObject.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/ProofTypeCWT.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/ProofTypeJWT.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/ProofTypeLdpVp.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/ProofTypesSupported.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/SupportedCredentialConfiguration.java
  services/src/test/java/org/keycloak/protocol/oid4vc/OID4VCClientRegistrationProviderTest.java
  services/src/test/java/org/keycloak/protocol/oid4vc/model/ClaimsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerWellKnownProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30508 Adjust JpaEventQuery.toDate so that events fro…
  model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventQuery.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/EventStoreProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30467 Use correct tooltip
  js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx
Labels: team/ui, backport/24.0, backport/25.0

#30464 Upgrade maven cache extension
  .mvn/extensions.xml
  js/pom.xml
  quarkus/dist/pom.xml
Labels: team/cloud-native, team/ui, flaky-test

#30528 add RS256 algorythm to webauthn default policy
  docs/documentation/server_admin/topics/authentication/webauthn.adoc
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  server-spi/src/main/java/org/keycloak/models/WebAuthnPolicy.java
Labels: flaky-test

#30502 Upgrade Maven and wrapper to latest version
  .github/actions/maven-cache/action.yml
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
Labels: flaky-test

#30524 Backport to fix issue related to dark mode in DropdownPanel
  js/apps/admin-ui/src/components/dropdown-panel/DropdownPanel.tsx
  js/apps/admin-ui/src/components/dropdown-panel/dropdown-panel.css
  js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx
  js/apps/admin-ui/src/events/AdminEvents.tsx
  js/apps/admin-ui/src/realm-settings/ThemesTab.tsx
  js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx
  js/apps/admin-ui/src/util.ts
Labels: team/ui, backport/25.0

#30536 Remove the timeout in authChecker when page is unloaded
  themes/src/main/resources/theme/base/login/resources/js/authChecker.js
Labels: team/ui, flaky-test

#30534 Internal read-only attributes have precedence over unmanaged attribute policy
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceReadOnlyAttributesTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30564 Backport fixed tooltip message in LdapMapperDetails
  js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx
Labels: team/ui, backport/24.0

#30559 Update to Infinispan 15.0.5.Final
  docs/guides/high-availability/examples/generated/ispn-single.yaml
  docs/guides/high-availability/examples/generated/ispn-site-a.yaml
  docs/guides/high-availability/examples/generated/ispn-site-b.yaml
  pom.xml
Labels: flaky-test, backport/25.0

#30530 issue keycloak/keycloak#30300
  model/jpa/src/main/resources/META-INF/jpa-changelog-25.0.0.xml
Labels: flaky-test

#30527 Importing organizations failing if there is no broker and members in …
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/exportimport/OrganizationExportTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30568 Internal read-only attributes have precedence over unmanaged attribute policy
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceReadOnlyAttributesTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30446 Refactor organization tests
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/account/OrganizationAccountTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/AbstractBrokerSelfRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/exportimport/OrganizationExportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/member/OrganizationMemberAuthenticationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30535 Use correct host URL for Admin Console requests
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  js/apps/account-ui/README.md
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/index.ftl
  js/apps/account-ui/src/api.ts
  js/apps/account-ui/src/api/methods.ts
  js/apps/account-ui/src/api/request.ts
  js/apps/account-ui/src/environment.ts
  js/apps/account-ui/src/i18n.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/index.ftl
  js/apps/admin-ui/src/admin-client.ts
  js/apps/admin-ui/src/environment.ts
  js/apps/admin-ui/src/i18n/i18n.ts
  js/apps/admin-ui/src/identity-providers/add/SamlConnectSettings.tsx
  js/apps/admin-ui/src/identity-providers/add/SamlGeneralSettings.tsx
  js/libs/ui-shared/src/context/KeycloakContext.tsx
  js/libs/ui-shared/src/context/environment.ts
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
  services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java
Labels: team/ui, flaky-test

#30569 Fix the website on https://www.keycloak.org/server/db showing some asciidoc related `ifeval` text
  docs/guides/server/db.adoc
Labels: team/cloud-native

#30577 Remove the timeout in authChecker when page is unloaded
  themes/src/main/resources/theme/base/login/resources/js/authChecker.js
Labels: team/ui

#30576 Fix partial_import_test
  js/apps/admin-ui/cypress/e2e/partial_import_test.spec.ts
Labels: team/ui

#30574 Fixed Frontend URL realm setting label
  js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
Labels: team/ui, backport/25.0

#30570 Internal read-only attributes have precedence over unmanaged attribute policy
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceReadOnlyAttributesTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30466 Reduce number of warnings and log lines created by the dependency plugin
  .github/actions/build-keycloak/action.yml
Labels: flaky-test

#30575 Backport to fix Frontend URL realm setting label
  js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
Labels: team/ui, backport/25.0

#30579 Use correct host URL for Admin Console requests (#30535)
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  js/apps/account-ui/README.md
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/index.ftl
  js/apps/account-ui/src/api.ts
  js/apps/account-ui/src/api/methods.ts
  js/apps/account-ui/src/api/request.ts
  js/apps/account-ui/src/environment.ts
  js/apps/account-ui/src/i18n.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/index.ftl
  js/apps/admin-ui/src/admin-client.ts
  js/apps/admin-ui/src/environment.ts
  js/apps/admin-ui/src/i18n/i18n.ts
  js/apps/admin-ui/src/identity-providers/add/SamlConnectSettings.tsx
  js/apps/admin-ui/src/identity-providers/add/SamlGeneralSettings.tsx
  js/libs/ui-shared/src/context/KeycloakContext.tsx
  js/libs/ui-shared/src/context/environment.ts
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
  services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java
Labels: team/ui, flaky-test

#30602 Fix partial_import_test
  js/apps/admin-ui/cypress/e2e/partial_import_test.spec.ts
Labels: team/ui

#30603 Remove the SAML undertow adapter
  adapters/saml/pom.xml
  adapters/saml/undertow/pom.xml
  adapters/saml/undertow/src/main/java/org/keycloak/adapters/saml/undertow/AbstractSamlAuthMech.java
  adapters/saml/undertow/src/main/java/org/keycloak/adapters/saml/undertow/IdMapperUpdaterSessionListener.java
  adapters/saml/undertow/src/main/java/org/keycloak/adapters/saml/undertow/SamlServletExtension.java
  adapters/saml/undertow/src/main/java/org/keycloak/adapters/saml/undertow/ServletSamlAuthMech.java
  adapters/saml/undertow/src/main/java/org/keycloak/adapters/saml/undertow/ServletSamlSessionStore.java
  adapters/saml/undertow/src/main/java/org/keycloak/adapters/saml/undertow/UndertowSamlAuthenticator.java
  adapters/saml/undertow/src/main/java/org/keycloak/adapters/saml/undertow/UndertowSamlEndpoint.java
  adapters/saml/undertow/src/main/resources/META-INF/services/io.undertow.servlet.ServletExtension
  distribution/feature-packs/adapter-feature-pack/pom.xml
  distribution/feature-packs/adapter-feature-pack/src/main/resources/modules/system/add-ons/keycloak/org/keycloak/keycloak-adapter-spi/main/module.xml
  distribution/galleon-feature-packs/saml-adapter-galleon-pack/pom.xml
  distribution/galleon-feature-packs/saml-adapter-galleon-pack/src/main/resources/license/licenses.xml
  distribution/galleon-feature-packs/saml-adapter-galleon-pack/src/main/resources/modules/system/add-ons/keycloak/org/keycloak/keycloak-adapter-spi/main/module.xml
  distribution/galleon-feature-packs/saml-adapter-galleon-pack/src/main/resources/modules/system/add-ons/keycloak/org/keycloak/keycloak-saml-undertow-adapter/main/module.xml
  distribution/galleon-feature-packs/saml-adapter-galleon-pack/src/main/resources/modules/system/add-ons/keycloak/org/keycloak/keycloak-saml-wildfly-elytron-jakarta-adapter/main/module.xml
  distribution/saml-adapters/wildfly-adapter/wildfly-jakarta-modules/build.xml
  distribution/saml-adapters/wildfly-adapter/wildfly-jakarta-modules/pom.xml
  distribution/saml-adapters/wildfly-adapter/wildfly-jakarta-modules/src/main/resources/modules/org/keycloak/keycloak-saml-undertow-adapter/main/module.xml
  distribution/saml-adapters/wildfly-adapter/wildfly-jakarta-modules/src/main/resources/modules/org/keycloak/keycloak-saml-wildfly-elytron-jakarta-adapter/main/module.xml
  distribution/saml-adapters/wildfly-adapter/wildfly-modules/build.xml
  distribution/saml-adapters/wildfly-adapter/wildfly-modules/pom.xml
  distribution/saml-adapters/wildfly-adapter/wildfly-modules/src/main/resources/modules/org/keycloak/keycloak-saml-undertow-adapter/main/module.xml
  distribution/saml-adapters/wildfly-adapter/wildfly-modules/src/main/resources/modules/org/keycloak/keycloak-saml-wildfly-elytron-adapter/main/module.xml
  pom.xml
  testsuite/integration-arquillian/servers/adapter-spi/pom.xml
  testsuite/integration-arquillian/servers/adapter-spi/undertow-adapter-saml-jakarta/.gitignore
  testsuite/integration-arquillian/servers/adapter-spi/undertow-adapter-saml-jakarta/pom.xml
  testsuite/utils/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#30593 Fix invalid parameter '{3h}' to '{3}' for spanish translation
  themes/src/main/resources-community/theme/base/email/messages/messages_es.properties
Labels: team/ui, flaky-test

#30523 use clientId instead of id to save client
  js/apps/admin-ui/src/components/client/ClientSelect.tsx
Labels: team/ui

#30578 Support unmanaged attributes for service accounts and make sure they are only managed through the admin api
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/UserResource.java
  js/apps/admin-ui/cypress/e2e/users_test.spec.ts
  js/apps/admin-ui/src/components/users/resource.ts
  js/apps/admin-ui/src/user/EditUser.tsx
  js/libs/keycloak-admin-client/src/resources/users.ts
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AdminExtResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UserResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UsersResource.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/LegacyAttributes.java
  services/src/main/java/org/keycloak/userprofile/ServiceAccountAttributes.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/PermissionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ServiceAccountUserProfileTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#30560 Remove AUTO_SERVER H2 default JDBC property
  .github/workflows/ci.yml
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  testsuite/integration-arquillian/HOW-TO-RUN.md
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam
