Repository keycloak/keycloak, pull requests merged in 2024-11, with the labels that each got.

#34550 Fix Quarkus dev mode
  quarkus/server/pom.xml
Labels: team/cloud-native

#34575 Fix Quarkus dev mode (#34550)
  quarkus/server/pom.xml
Labels: team/cloud-native

#34578 Remove Provider annotation along with default constructors from org r…
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationIdentityProvidersResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationMemberResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationsResource.java
Labels: flaky-test

#34554 Add checks to prevent GroupLDAPStorageMapper from performing operatio…
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapper.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/util/LDAPTestUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34580 Add checks to prevent GroupLDAPStorageMapper from performing operatio…
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapper.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/util/LDAPTestUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#33046 Provide missing user event metrics from aerogear/keycloak-metrics-spi with a key…
  common/src/main/java/org/keycloak/common/Profile.java
  docs/guides/server/configuration-metrics.adoc
  docs/guides/server/event-metrics.adoc
  docs/guides/server/pinned-guides
  quarkus/config-api/src/main/java/org/keycloak/config/EventOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionCategory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/EventPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/metrics/events/MicrometerUserEventMetricsEventListenerProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/metrics/events/MicrometerUserEventMetricsEventListenerProviderFactory.java
  quarkus/runtime/src/main/resources/META-INF/services/org.keycloak.events.EventListenerProviderFactory
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/MetricsDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  server-spi-private/src/main/java/org/keycloak/events/EventBuilder.java
  server-spi-private/src/main/java/org/keycloak/events/EventListenerProviderFactory.java
  services/src/main/java/org/keycloak/services/resources/admin/AdminEventBuilder.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmsAdminResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/EventMetricsProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34539 changed to use TextArea
  js/apps/admin-ui/src/identity-providers/add/DiscoverySettings.tsx
Labels: team/ui

#34612 Fix failing test AdminEventQueryTest by adding required session parameter
  testsuite/model/src/test/java/org/keycloak/testsuite/model/events/AdminEventQueryTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34584 Microsoft login - add prompt param configure
  services/src/main/java/org/keycloak/social/microsoft/MicrosoftIdentityProviderFactory.java
Labels: team/core-clients, team/core-iam

#34475 Allow custom message for brute force temporary lockout
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/AbstractUsernameFormAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/OTPFormAuthenticator.java
  services/src/main/java/org/keycloak/services/messages/Messages.java
  themes/src/main/resources-community/theme/base/login/messages/messages_ar.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_da.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_el.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fa.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fi.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_hu.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ko.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_lt.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_lv.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_nl.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_no.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_pl.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_pt.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ru.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_sk.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_sv.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_th.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_tr.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_uk.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_zh_CN.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_zh_TW.properties
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/ui, flaky-test, team/core-clients

#34525 Add ability to enable OID4VCI Verifiable Credentials per realm (#34524)
  core/src/main/java/org/keycloak/representations/idm/RealmRepresentation.java
  js/apps/account-ui/src/routes.tsx
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
  js/libs/keycloak-admin-client/src/defs/realmRepresentation.ts
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedRealm.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/RealmAttributes.java
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RealmModelDelegate.java
  server-spi-private/src/test/java/org/keycloak/broker/provider/util/IdentityBrokerStateTestHelpers.java
  server-spi/src/main/java/org/keycloak/models/RealmModel.java
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
Labels: status/ready, team/ui, flaky-test

#34461 fix: ensure that kc.config.args is omitted from show-config
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java
  quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java
Labels: team/cloud-native, flaky-test

#33904 Refresh login page when root auth session changes
  server-spi-private/src/main/java/org/keycloak/cookie/CookieType.java
  services/src/main/java/org/keycloak/forms/login/freemarker/model/AuthenticationSessionBean.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationSessionManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cookies/DefaultCookieProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultipleTabsLoginTest.java
  themes/src/main/resources/theme/base/login/resources/js/authChecker.js
  themes/src/main/resources/theme/base/login/template.ftl
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#34543 Migrate WelcomeTestPage to testsuite framework
  test-framework/examples/src/test/java/org/keycloak/test/examples/WelcomePageTest.java
  test-framework/ui/src/main/java/org/keycloak/test/framework/ui/page/WelcomePage.java
  tests/base/src/test/java/org/keycloak/test/welcomepage/WelcomePageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/welcomepage/WelcomePageTest.java
  testsuite/integration-arquillian/tests/base/testsuites/base-suite
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam, area/test-framework

#34643 fix Client Protocol Mappers with non UUID ids cannot be edited
  js/apps/admin-ui/src/client-scopes/EditClientScope.tsx
  js/apps/admin-ui/src/client-scopes/details/MappingDetails.tsx
  js/apps/admin-ui/src/client-scopes/routes/Mapper.tsx
  js/apps/admin-ui/src/clients/routes/Mapper.tsx
  js/apps/admin-ui/src/clients/scopes/DedicatedScopes.tsx
Labels: team/ui

#34653 Avoid continuous reload when KC_AUTH_SESSION_HASH expires
  themes/src/main/resources/theme/base/login/resources/js/authChecker.js
Labels: team/ui

#34589 Show forbidden section only after whoAmI is set
  js/apps/admin-ui/src/context/whoami/WhoAmI.tsx
  js/apps/admin-ui/src/root/AuthWall.tsx
Labels: team/ui

#34477 BACKPORT: added required attribute to multiline (#34336)
  js/apps/admin-ui/src/components/multi-line-input/MultiLineInput.tsx
  js/apps/admin-ui/src/organizations/NewOrganization.tsx
  js/apps/admin-ui/src/organizations/OrganizationForm.tsx
Labels: team/ui

#34311 Restore the Cache tab in Realm Settings
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/PageHeader.tsx
  js/apps/admin-ui/src/PageHeaderClearCachesModal.tsx
  js/apps/keycloak-server/README.md
  js/libs/keycloak-admin-client/src/resources/cache.ts
Labels: team/ui

#34613 fixed link to documentation
  js/apps/admin-ui/src/components/help-enabler/HelpHeader.tsx
Labels: team/ui

#34648 BACKPORT: fix bundling issues (#34387)
  js/apps/admin-ui/src/authentication/AuthenticationSection.tsx
  js/apps/admin-ui/src/authentication/BindFlowDialog.tsx
  js/apps/admin-ui/src/authentication/components/UsedBy.tsx
  js/apps/admin-ui/src/authentication/constants.ts
  js/apps/admin-ui/src/components/routable-tabs/RoutableTabs.tsx
  js/apps/admin-ui/src/page/Page.tsx
  js/apps/admin-ui/src/page/PageHandler.tsx
  js/apps/admin-ui/src/page/PageList.tsx
  js/apps/admin-ui/src/page/constants.ts
  js/apps/admin-ui/vite.config.ts
Labels: team/ui

#34522 fix: Incorrect Content-Type Expectation for organization api endpoints
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationIdentityProvidersResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationMemberResource.java
Labels: team/ui

#34642 Update `passwordResetBodyHtml` key for missing email translations to match others
  themes/src/main/resources-community/theme/base/email/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_lt.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_ru.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_sv.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_zh_CN.properties
Labels: team/ui

#34260 fix: consolidating logic dealing with persisted property handling
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Environment.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractStartCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Build.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Completion.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Start.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/Configuration.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakPropertiesConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/QuarkusPropertiesConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/AbstractConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigRegExPatternMatchingTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesAutoBuildDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartDevCommandDistTest.java
Labels: team/cloud-native, flaky-test

#34668 cache-embedded-mtls-enabled is ignored
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/CacheManagerFactory.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/OptionsDistTest.java
Labels: team/cloud-native, flaky-test

#34670 [26.0] cache-embedded-mtls-enabled is ignored
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/CacheManagerFactory.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/OptionsDistTest.java
Labels: team/cloud-native

#34588 Added missing Danish translation keys in messages_da.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_da.properties
Labels: team/ui, flaky-test

#34656 Use a weekly cache key for PNPM store
  .github/actions/build-keycloak/action.yml
  .github/actions/cypress-cache/action.yml
  .github/actions/frontend-plugin-cache/action.yml
  .github/actions/integration-test-setup/action.yml
  .github/actions/pnpm-setup/action.yml
  .github/actions/pnpm-store-cache/action.yml
  .github/actions/unit-test-setup/action.yml
Labels: flaky-test

#34346 Remove online session when offline access is requested as the first request
  docs/documentation/upgrading/topics/changes/changes-26_1_0.adoc
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/OAuth2GrantTypeBase.java
  services/src/main/java/org/keycloak/services/managers/UserSessionManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExtendedEventTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/BackchannelLogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java
Labels: status/ready, team/cloud-native, team/core-clients, team/core-iam

#34694 Use a hidden form to do `POST` based logout
  js/libs/keycloak-js/lib/keycloak.js
Labels: team/ui

#34693 Avoid using nip.io resolution in RefreshTokenTest#refreshTokenWithDifferentIssuer test
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#34696 Allow OIDCIdentityProvider implementations to override isTokenTypeSupported (#34695)
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
Labels: status/ready

#34699 fix: mark slf4j as not optional for the operator (#32652)
  operator/pom.xml
Labels: team/cloud-native, flaky-test

#34664 Add service account mappers via client scope instead of dedicated scope
  common/src/main/java/org/keycloak/common/constants/ServiceAccountConstants.java
  docs/documentation/upgrading/topics/changes/changes-26_1_0.adoc
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo26_1_0.java
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultMigrationManager.java
  server-spi-private/src/main/java/org/keycloak/migration/MigrationProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ClientCredentialsGrantType.java
  services/src/main/java/org/keycloak/services/managers/ClientManager.java
  services/src/main/java/org/keycloak/services/migration/DefaultMigrationProvider.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/AbstractClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/ServiceAccountClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmCreateTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AbstractWellKnownProviderTest.java
Labels: status/ready, team/cloud-native, team/core-clients, team/core-iam

#34685 Fix credential_type in update/remove credential email template
  services/src/main/java/org/keycloak/email/freemarker/beans/EventBean.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionDeleteCredentialTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionResetPasswordTest.java
  themes/src/main/resources/theme/base/email/html/event-remove_credential.ftl
  themes/src/main/resources/theme/base/email/html/event-update_credential.ftl
  themes/src/main/resources/theme/base/email/text/event-remove_credential.ftl
  themes/src/main/resources/theme/base/email/text/event-update_credential.ftl
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#34721 Fix(admin-ui): key status filtering issue in KeysListTab
  js/apps/admin-ui/src/realm-settings/keys/KeysListTab.tsx
Labels: team/ui

#34700 Add Lets Encrypt intermediate CAs to keycloak.truststore
  testsuite/integration-arquillian/servers/auth-server/common/keystore/keycloak.truststore
Labels: team/cloud-native, team/core-clients, team/core-iam

#34579 Remove Provider annotation along with default constructors from org r…
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationIdentityProvidersResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationMemberResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationsResource.java
Labels: flaky-test

#34689 BACKPORT: fixed link to documentation (#34613)
  js/apps/admin-ui/src/components/help-enabler/HelpHeader.tsx
Labels: team/ui

#34250 fix: addresses consistency issues with property mapping
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/DisabledMappersInterceptor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PersistedConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PropertyMappingInterceptor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/AbstractConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/IgnoredArtifactsTest.java
Labels: team/cloud-native

#34672 BACKPORT: Let create/edit client role w/ fine-grained auth.
  js/apps/admin-ui/src/clients/routes/NewRole.tsx
  js/apps/admin-ui/src/components/role-form/RoleForm.tsx
  js/apps/admin-ui/src/realm-roles/RealmRoleTabs.tsx
Labels: team/ui

#32654 Fix broken JavaScript adapter tests when running in cross-origin context
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/javascript/JavascriptAdapterTest.java
Labels: status/ready, team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34744 Add Lets Encrypt intermediate CAs to keycloak.truststore
  testsuite/integration-arquillian/servers/auth-server/common/keystore/keycloak.truststore
Labels: team/cloud-native, team/core-clients, team/core-iam

#34676 Better message when updating users when import is disabled
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java
  model/storage-private/src/main/java/org/keycloak/storage/UserStorageManager.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ReadOnlyUserModelDelegate.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/noimport/LDAPProvidersIntegrationNoImportTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34742 Fix credential_type in update/remove credential email template (26.0)
  services/src/main/java/org/keycloak/email/freemarker/beans/EventBean.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionDeleteCredentialTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionResetPasswordTest.java
  themes/src/main/resources/theme/base/email/html/event-remove_credential.ftl
  themes/src/main/resources/theme/base/email/html/event-update_credential.ftl
  themes/src/main/resources/theme/base/email/text/event-remove_credential.ftl
  themes/src/main/resources/theme/base/email/text/event-update_credential.ftl
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#34775 Add database testsuite matrix to new testsuite
  .github/workflows/ci.yml
  docs/guides/server/db.adoc
  pom.xml
  quarkus/tests/integration/pom.xml
  test-framework/README.md
  test-framework/core/pom.xml
  test-framework/core/src/main/java/org/keycloak/test/framework/annotations/InjectTestDatabase.java
  test-framework/core/src/main/java/org/keycloak/test/framework/config/Config.java
  test-framework/core/src/main/java/org/keycloak/test/framework/database/AbstractContainerTestDatabase.java
  test-framework/core/src/main/java/org/keycloak/test/framework/database/DatabaseConfig.java
  test-framework/core/src/main/java/org/keycloak/test/framework/database/DatabaseProperties.java
  test-framework/core/src/main/java/org/keycloak/test/framework/database/JBossLogConsumer.java
  test-framework/core/src/main/java/org/keycloak/test/framework/database/TestDatabase.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/AbstractKeycloakTestServerSupplier.java
  test-framework/core/src/main/resources/org/keycloak/test/framework/database/database.properties
  test-framework/db-mariadb/src/main/java/org/keycloak/test/framework/database/MariaDBDatabaseSupplier.java
  test-framework/db-mariadb/src/main/java/org/keycloak/test/framework/database/MariaDBTestDatabase.java
  test-framework/db-mssql/src/main/java/org/keycloak/test/framework/database/MSSQLServerDatabaseSupplier.java
  test-framework/db-mssql/src/main/java/org/keycloak/test/framework/database/MSSQLServerTestDatabase.java
  test-framework/db-mysql/src/main/java/org/keycloak/test/framework/database/MySQLTestDatabase.java
  test-framework/db-oracle/src/main/java/org/keycloak/test/framework/database/Oracle19DatabaseSupplier.java
  test-framework/db-oracle/src/main/java/org/keycloak/test/framework/database/Oracle19TestDatabase.java
  test-framework/db-oracle/src/main/java/org/keycloak/test/framework/database/OracleDatabaseSupplier.java
  test-framework/db-oracle/src/main/java/org/keycloak/test/framework/database/OracleTestDatabase.java
  test-framework/db-oracle/src/main/java/org/keycloak/test/framework/database/OracleTestFrameworkExtension.java
  test-framework/db-postgres/src/main/java/org/keycloak/test/framework/database/PostgresDatabaseSupplier.java
  test-framework/db-postgres/src/main/java/org/keycloak/test/framework/database/PostgresTestDatabase.java
  test-framework/examples/tests/src/test/resources/container-license-acceptance.txt
  tests/base/pom.xml
  tests/base/src/test/java/org/keycloak/test/suites/DatabaseTestSuite.java
  tests/base/src/test/java/org/keycloak/test/tmp/PlaceHolderTest.java
  tests/base/src/test/resources/container-license-acceptance.txt
  tests/base/src/test/resources/logging.properties
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34541 Make cache-remote-host enabled when needed
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/CachingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/OptionsDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#34748 Update UP via provider instead of going through the UserProfileResource
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UIRealmResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UserProfileResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UIRealmResourceTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#34786 Avoid a build warning about missing Infinispan annotations
  quarkus/runtime/pom.xml
Labels: team/cloud-native

#34754 Fix NullPointerException if no session attached when authenticating with identity cookie
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
Labels: flaky-test, team/core-iam

#34719 Document network ports for Keycloak clustering
  docs/documentation/release_notes/topics/26_1_0.adoc
  docs/documentation/upgrading/topics/changes/changes-26_1_0.adoc
  docs/guides/attributes.adoc
  docs/guides/server/caching.adoc
  docs/guides/server/configuration-production.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/CacheManagerFactory.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native

#34781 Strip Double Quotes from Request Content in Organization API
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationIdentityProvidersResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationMemberResource.java
Labels: flaky-test

#34551 Update KEYCLOAK_SESSION cookie to not have sessionId in plaintext
  core/src/main/java/org/keycloak/jose/jws/crypto/HashUtils.java
  core/src/test/java/org/keycloak/HashTest.java
  docs/documentation/upgrading/topics/changes/changes-26_1_0.adoc
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/IframeUtil.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LoginStatusIframeEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/PkceUtils.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/utils/FreemarkerUtils.java
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/login-status-iframe.ftl
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34833 Flaky test: org.keycloak.testsuite.actions.TermsAndConditionsTest#ter…
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/TermsAndConditionsTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#34838 Cookie not found in multi-step auth flows / mobile browsers
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/ui

#34791 [Backport] Better message when updating users when import is disabled
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java
  model/storage-private/src/main/java/org/keycloak/storage/UserStorageManager.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ReadOnlyUserModelDelegate.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/noimport/LDAPProvidersIntegrationNoImportTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34792 [Backport] - Added a representation that includes an organization and user model
  core/src/main/java/org/keycloak/representations/idm/AdminEventRepresentation.java
  docs/documentation/release_notes/index.adoc
  docs/documentation/release_notes/topics/26_0_6.adoc
  js/apps/admin-ui/src/events/AdminEvents.tsx
  js/libs/keycloak-admin-client/src/defs/adminEventRepresentation.ts
  model/jpa/src/main/java/org/keycloak/events/jpa/AdminEventEntity.java
  model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventStoreProvider.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-26.0.6.xml
  model/jpa/src/main/resources/META-INF/jpa-changelog-master.xml
  server-spi-private/src/main/java/org/keycloak/events/admin/AdminEvent.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi/src/main/java/org/keycloak/models/OrganizationModel.java
  services/src/main/java/org/keycloak/events/log/JBossLoggingEventListenerProvider.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationMemberResource.java
  services/src/main/java/org/keycloak/services/resources/admin/AdminEventBuilder.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/event/AdminEventTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#34688 BACKPORT: changed to use TextArea (#34539)
  js/apps/admin-ui/src/identity-providers/add/DiscoverySettings.tsx
Labels: team/ui

#34735 Remove columns and un-clearable filters
  js/apps/admin-ui/cypress/e2e/clients_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/ClientDetailsPage.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/ClientDetails.tsx
  js/apps/admin-ui/src/events/EventsSection.tsx
  js/apps/admin-ui/src/events/UserEvents.tsx
  js/apps/admin-ui/src/realm-settings/event-config/EventsTab.tsx
  js/apps/admin-ui/src/user/EditUser.tsx
  js/libs/ui-shared/src/controls/table/KeycloakDataTable.tsx
Labels: team/ui

#34476 BACKPORT: add brute force enabled so we can render switch (#34282)
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
Labels: flaky-test

#34235 Expose membership type in the Admin UI for organization members and users
  core/src/main/java/org/keycloak/representations/idm/MembershipType.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationMembersResource.java
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/components/dynamic/CheckboxFilterComponent.tsx
  js/apps/admin-ui/src/components/dynamic/SearchInputComponent.tsx
  js/apps/admin-ui/src/organizations/Members.tsx
  js/apps/admin-ui/src/user/EditUser.tsx
  js/apps/admin-ui/src/user/Organizations.tsx
  js/apps/admin-ui/src/util.ts
  js/libs/keycloak-admin-client/src/resources/organizations.ts
  js/libs/ui-shared/src/controls/OrganizationTable.tsx
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/InfinispanOrganizationProvider.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  model/storage-private/src/main/java/org/keycloak/exportimport/util/ExportUtils.java
  server-spi/src/main/java/org/keycloak/organization/OrganizationProvider.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationMemberResource.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/member/OrganizationMemberTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#34510 do not filter the realm list on recent used as it might be on the next page
  js/apps/admin-ui/src/components/error/ErrorRenderer.tsx
  js/apps/admin-ui/src/components/realm-selector/RealmSelector.tsx
  js/apps/admin-ui/src/context/RecentRealms.tsx
  js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
Labels: team/ui

#34702 no longer disable when resource is pre selected
  js/apps/admin-ui/src/clients/authorization/ResourcesPolicySelect.tsx
Labels: team/ui

#34814 added wait for group to load
  js/apps/admin-ui/cypress/e2e/group_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/groups/GroupPage.ts
  js/apps/admin-ui/src/authentication/execution-model.ts
  js/apps/admin-ui/src/groups/components/GroupTree.tsx
Labels: team/ui

#34867 Update installation locations
  docs/guides/server/directory-structure.adoc
  docs/guides/server/reverseproxy.adoc
Labels: team/cloud-native

#34874 Cookies Tests - KcSamlBrokerTest
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlBrokerTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#34885 fix: using local cache for distribution tests to avoid port conflicts
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/BuildAndStartDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
Labels: team/cloud-native

#34877 Update Leveraging Jakarta EE
  docs/documentation/server_development/topics/user-storage/javaee.adoc
Labels: backport/26.0

#34908 Surefire artifacts - updating names for Quarkus IT and UT.
  .github/workflows/ci.yml
Labels: flaky-test

#34871 Update installation locations
  docs/guides/server/directory-structure.adoc
  docs/guides/server/reverseproxy.adoc
Labels: team/cloud-native

#34878 Backport to improve translations
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesGroupForm.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AddTranslationsDialog.tsx
Labels: team/ui

#34849 Avoid creating unnecessary exception instances on profile validation
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultUserProfile.java
  server-spi-private/src/main/java/org/keycloak/userprofile/ValidationException.java
Labels: flaky-test

#34866 Send exact param in user attr search only when it is enabled
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
Labels: team/ui

#34820 Allow a request object by considering a clock skew for smooth interoperability
  services/src/main/java/org/keycloak/services/clientpolicy/executor/SecureRequestObjectExecutor.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/SecureRequestObjectExecutorFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExecutorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ClientPoliciesUtil.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34914 Avoid DB error when sessionId is passed in the incorrect format
  server-spi-private/src/main/java/org/keycloak/events/Event.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/events/EventStoreProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#34841 Allow a JWT client assertion by considering a clock skew for smooth interoperability
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#34845 Keycloak needs to return invalid_request from Token Endpoint if a token or refresh request lacks DPOP proof
  services/src/main/java/org/keycloak/services/util/DPoPUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/DPoPTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#34889 Fix to check correctly that the service account scope is assigned
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ClientCredentialsGrantType.java
  services/src/main/java/org/keycloak/services/managers/ClientManager.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientsResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/ServiceAccountClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#33732 make the tests capable of running against login v1 and v2
  .github/workflows/ci.yml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/login/DeleteAccountActionConfirmPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/login/FeedbackMessage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/InstalledAppRedirectPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LanguageComboboxAwarePage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPasswordResetPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPasswordUpdatePage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginTotpPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginUpdateProfilePage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/OAuthGrantPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/RegisterPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/UpdateAccountInformationPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/VerifyProfilePage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateProfileWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractDefaultIdpTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcFirstBrokerLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/VerifyProfileTest.java
  testsuite/integration-arquillian/tests/base/testsuites/login-suite
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34836 fix: liquibase update summary to log only
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/conn/KeycloakLiquibase.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java
Labels: team/cloud-native

#34601 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fr.properties
Labels: team/ui, flaky-test

#34743 [FGAP] First draft of Authorization Schema
  core/src/main/java/org/keycloak/representations/idm/authorization/AuthorizationSchema.java
  core/src/main/java/org/keycloak/representations/idm/authorization/FineGrainedAdminPermissionsAuthorizationSchema.java
  core/src/main/java/org/keycloak/representations/idm/authorization/ResourceServerRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/authorization/ResourceType.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/admin/FineGrainedAdminPermissionsTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34948 Cookies Tests - KcOidcBrokerPrivateKeyJwtCustomAudienceTest
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerPrivateKeyJwtCustomAudienceTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32483 db.adoc: Refined the 'Configuring a database' paragraph
  docs/guides/server/db.adoc
Labels: team/cloud-native

#34939 Make sure unmanaged attributes are populated before updating username when in update email context
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#34969 Check "Always use lightweight access token" is enabled on the client for Admin REST APIs
  services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#34961 Allow updating the username when registration as email is enabled during LDAP updates
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/UserAttributeLDAPStorageMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPUserProfileTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34863 Pre-download and cache Node.js and PNPM on CI
  .github/actions/node-cache/action.yml
  .github/scripts/download-node-tooling.sh
Labels: flaky-test

#34932 Upgrade to ISPN 15.0.11.Final
  pom.xml
  quarkus/runtime/pom.xml
Labels: team/cloud-native

#33830 Authentication session with changelog transaction
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/AuthenticationSessionAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanAuthenticationSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanAuthenticationSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/RootAuthenticationSessionAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/InfinispanChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/MergedUpdate.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/RootAuthenticationSessionUpdateTask.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/SessionUpdateTask.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/remote/updater/BaseUpdater.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/remote/updater/authsession/RootAuthenticationSessionUpdater.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/RootAuthenticationSessionEntity.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/SessionEntity.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteInfinispanAuthenticationSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteInfinispanAuthenticationSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/transaction/AuthenticationSessionChangeLogTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/util/SessionTimeouts.java
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo26_1_0.java
  server-spi/src/main/java/org/keycloak/sessions/AuthenticationSessionProvider.java
  testsuite/model/src/main/java/org/keycloak/testsuite/model/HotRodServerRule.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/AuthenticationSessionTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34815 Use short UUID for ldap components
  docs/documentation/server_admin/topics/authentication/webauthn.adoc
  docs/documentation/server_development/topics/user-storage/model-interfaces.adoc
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  server-spi-private/src/test/java/org/keycloak/models/utils/KeycloakModelUtilsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/AbstractLDAPTest.java
Labels: status/ready, team/cloud-native, team/core-clients, team/core-iam

#34958 Avoid MRJAR in keycloak-core
  .github/workflows/ci.yml
  core/pom.xml
  core/src/main/java/org/keycloak/jose/jwk/AbstractJWKBuilder.java
  core/src/main/java/org/keycloak/jose/jwk/AbstractJWKParser.java
  core/src/main/java/org/keycloak/jose/jwk/EdECUtils.java
  core/src/main/java/org/keycloak/jose/jwk/EdECUtilsUnsupportedImpl.java
  core/src/main/java/org/keycloak/jose/jwk/JWKBuilder.java
  core/src/main/java/org/keycloak/jose/jwk/JWKParser.java
  core/src/main/java15/org/keycloak/jose/jwk/EdECUtilsImpl.java
  core/src/main/java16/org/keycloak/jose/jwk/JWKBuilder.java
  core/src/main/java16/org/keycloak/jose/jwk/JWKParser.java
Labels: status/ready, flaky-test

#34915 Introduce SdJwtFacade layer for simplified SD-JWT handling and enhance test coverage
  core/src/main/java/org/keycloak/sdjwt/SdJwtFacade.java
  core/src/test/java/org/keycloak/sdjwt/SdJwtFacadeTest.java
  crypto/default/src/test/java/org/keycloak/crypto/def/test/sdjwt/DefaultCryptoSdJwtFacadeTest.java
  crypto/elytron/src/test/java/org/keycloak/crypto/elytron/test/sdjwt/ElytronCryptoSdJwtFacadeTest.java
Labels: status/ready, flaky-test

#34924 fix: PEM files distributed as part of SAML adapter configs for mod_au…
  common/src/main/java/org/keycloak/common/util/PemUtils.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientResource.java
  services/src/main/java/org/keycloak/protocol/saml/installation/ModAuthMellonClientInstallation.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/SamlUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/PermissionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/InstallationTest.java
Labels: status/ready, team/cloud-native, team/core-clients, team/core-iam

#34959 Cookies Tests - KcOidcBrokerLdapTest
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerLdapTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#34956 Add simple logging support to the test framework
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/OutputConsumer.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
  test-framework/LOGGING.md
  test-framework/core/src/main/java/org/keycloak/test/framework/KeycloakIntegrationTestExtension.java
  test-framework/core/src/main/java/org/keycloak/test/framework/LogFilter.java
  test-framework/core/src/main/java/org/keycloak/test/framework/LogHandler.java
  test-framework/core/src/main/java/org/keycloak/test/framework/config/Config.java
  test-framework/core/src/main/java/org/keycloak/test/framework/config/LogConfigInterceptor.java
  test-framework/core/src/main/java/org/keycloak/test/framework/database/AbstractContainerTestDatabase.java
  test-framework/core/src/main/java/org/keycloak/test/framework/database/JBossLogConsumer.java
  test-framework/core/src/main/java/org/keycloak/test/framework/injection/Registry.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/AbstractKeycloakTestServerSupplier.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/CommandBuilder.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/DistributionKeycloakTestServer.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/DistributionKeycloakTestServerSupplier.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/EmbeddedKeycloakTestServer.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/EmbeddedKeycloakTestServerSupplier.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/KeycloakTestServer.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/RemoteKeycloakTestServer.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/RemoteKeycloakTestServerSupplier.java
  test-framework/core/src/main/resources/application.properties
  test-framework/core/src/test/resources/logging.properties
  test-framework/examples/tests/src/test/resources/keycloak-test.properties
  test-framework/examples/tests/src/test/resources/logging.properties
  tests/base/src/test/resources/keycloak-test.properties
  tests/base/src/test/resources/logging.properties
Labels: team/cloud-native

#35030 Add startup instructions for remote test server
  test-framework/core/src/main/java/org/keycloak/test/framework/server/RemoteKeycloakTestServer.java
Labels: area/test-framework

#35033 Pass builders to realm, client, and user configs
  test-framework/core/src/main/java/org/keycloak/test/framework/oauth/DefaultOAuthClientConfiguration.java
  test-framework/core/src/main/java/org/keycloak/test/framework/oauth/OAuthClient.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/ClientConfig.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/ClientConfigBuilder.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/ClientSupplier.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/DefaultClientConfig.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/DefaultRealmConfig.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/DefaultUserConfig.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/RealmConfig.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/RealmConfigBuilder.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/RealmSupplier.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/UserConfig.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/UserConfigBuilder.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/UserSupplier.java
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/FancyRealmTest.java
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/MultipleInstancesTest.java
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/OAuthClientTest.java
Labels: area/test-framework

#35037 Add support for marking a managed realm as dirty, making updates with rollback, and running cleanup tasks for a realm
  test-framework/core/src/main/java/org/keycloak/test/framework/injection/ManagedTestResource.java
  test-framework/core/src/main/java/org/keycloak/test/framework/injection/Registry.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/ManagedRealm.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/ManagedRealmCleanup.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/RealmConfigBuilder.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/RepresentationUtils.java
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/CleanupTest.java
Labels: flaky-test, area/test-framework

#35036 Check the authentication config exists before returning its reference
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/AuthenticatorConfigTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34980 Fix and enable firefox-strict-cookies profile adapter tests
  .github/workflows/ci.yml
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/AppServerTestEnricher.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/samesite/undertow-handlers.conf
Labels: team/cloud-native, team/continuous-testing, team/core-clients, team/core-iam

#34960 Migrated UserProfileAdminTest to the new framework
  tests/base/pom.xml
  tests/base/src/test/java/org/keycloak/test/admin/userprofile/UserProfileAdminTest.java
  tests/pom.xml
  tests/utils/pom.xml
  tests/utils/src/main/java/org/keycloak/test/utils/Assert.java
  tests/utils/src/main/java/org/keycloak/test/utils/JsonTestUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/userprofile/UserProfileAdminTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, area/test-framework

#35049 Migrate AdminSignatureAlgorithmTest
  test-framework/core/src/main/java/org/keycloak/test/framework/annotations/InjectRealm.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/RealmConfigBuilder.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/RealmSupplier.java
  tests/base/src/test/java/org/keycloak/test/admin/AdminSignatureAlgorithmTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminSignatureAlgorithmTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam, area/test-framework

#35056 Add admin package to DatabaseTestSuite.java
  tests/base/src/test/java/org/keycloak/test/suites/DatabaseTestSuite.java
  tests/base/src/test/java/org/keycloak/test/tmp/PlaceHolderTest.java
Labels: area/test-framework

#34865 Fix for Log handler specific log levels support only lower-case levels
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/LoggingOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/Option.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionBuilder.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ShortErrorMessageHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/test/java/or/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/LoggingConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#35074 Use cleanup tasks in migrated UserProfileAdminTest
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/RealmConfigBuilder.java
  tests/base/src/test/java/org/keycloak/test/admin/userprofile/UserProfileAdminTest.java
Labels: area/test-framework

#35057 [Test framework MVP] ImpersonationDisabledTest
  test-framework/core/src/main/java/org/keycloak/test/framework/server/AbstractKeycloakTestServerSupplier.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/CommandBuilder.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/KeycloakTestServerConfig.java
  tests/base/src/test/java/org/keycloak/test/admin/ImpersonationDisabledTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/FineGrainAdminUnitTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ImpersonationDisabledTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, area/test-framework

#35086 Add ManagedRealm#getId
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/ManagedRealm.java
  test-framework/core/src/main/java/org/keycloak/test/framework/realm/RealmSupplier.java
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/ManagedResourcesTest.java
Labels: area/test-framework

#34993 trying to make general test switch less flaky
  js/apps/admin-ui/cypress/e2e/realm_settings_general_tab_test.spec.ts
Labels: team/ui

#35043 Add a realm-level setting to enable FGAP to a realm
  core/src/main/java/org/keycloak/representations/idm/RealmRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/authorization/AdminPermissionsAuthorizationSchema.java
  core/src/main/java/org/keycloak/representations/idm/authorization/AuthorizationSchema.java
  core/src/main/java/org/keycloak/representations/idm/authorization/ResourceServerRepresentation.java
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
  js/apps/admin-ui/src/utils/useIsFeatureEnabled.ts
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedRealm.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/RealmAttributes.java
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RealmModelDelegate.java
  server-spi-private/src/test/java/org/keycloak/broker/provider/util/IdentityBrokerStateTestHelpers.java
  server-spi/src/main/java/org/keycloak/models/RealmModel.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/updaters/RealmAttributeUpdater.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/admin/AdminPermissionsTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#34897 documented how to skip the build of the frontend
  js/README.md
Labels: team/ui

#35034 Use clickLink to click back to Application in Info Page
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/InfoPage.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#34991 [Test framework MVP] PartialExportTest
  tests/base/src/test/java/org/keycloak/test/admin/partialexport/PartialExportTest.java
  tests/base/src/test/resources/export/partialexport-testrealm.json
Labels: team/cloud-native, team/core-clients, team/core-iam, area/test-framework

#35058 Drop old table USERNAME_LOGIN_FAILURE used before by UserSessionProvider
  model/jpa/src/main/resources/META-INF/jpa-changelog-26.1.0.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/helpers/DropAllServlet.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/annotation/RestartContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakContainerEventsController.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#35109 [Test framework MVP] ManagementPermissionsTest
  tests/base/src/test/java/org/keycloak/test/admin/ManagementPermissionsTest.java
  tests/utils/pom.xml
  tests/utils/src/main/java/org/keycloak/test/utils/admin/ApiUtil.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam, area/test-framework

#35031 remove double scrollbar fix
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/index.ftl
  js/apps/admin-ui/src/index.css
Labels: team/ui

#35072 sort event types
  js/apps/admin-ui/src/events/UserEvents.tsx
Labels: team/ui

#33819 Add test for KcAdm status change
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#35005 splitting the zip test suite
  .github/workflows/ci.yml
  quarkus/tests/integration/pom.xml
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/BuildAndStartDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/CustomJpaEntityProviderDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ExportDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FeaturesDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FipsDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HealthDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ImportAtStartupDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ImportDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JavaOptsScriptTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JaxRsDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ManagementDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/MetricsDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartDevCommandDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/TruststoreDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/BasicDatabaseTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/ExternalInfinispanTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/DatabaseOptionsDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MariaDBDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MySQLDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/PostgreSQLDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/TransactionConfigurationDistTest.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/CLITest.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/DistributionTest.java
Labels: team/cloud-native, flaky-test

#34999 fix: providing stable ordering for deprecation metadata
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/DeprecatedMetadata.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionBuilder.java
  quarkus/config-api/src/main/java/org/keycloak/config/TruststoreOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/test/java/org/keycloak/config/OptionBuilderTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
Labels: team/cloud-native

#35144 Create a new guide category Observability and move some guides from s…
  docs/guides/assembly.xml
  docs/guides/observability/configuration-metrics.adoc
  docs/guides/observability/event-metrics.adoc
  docs/guides/observability/health.adoc
  docs/guides/observability/index.adoc
  docs/guides/observability/pinned-guides
  docs/guides/observability/tracing.adoc
  docs/guides/pom.xml
  docs/guides/server/pinned-guides
Labels: team/cloud-native

#35191 getAll() organization and organization members only returns the first…
  docs/documentation/release_notes/topics/26_1_0.adoc
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationMembersResource.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationsResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/event/AdminEventTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationGroupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authz/OrganizationAdminPermissionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/AbstractBrokerSelfRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/cache/OrganizationCacheTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/exportimport/OrganizationExportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationOIDCProtocolMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/member/OrganizationMemberTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#35222 Update docs with security warning around client certificate lookup
  docs/documentation/release_notes/topics/26_0_6.adoc
  docs/documentation/topics/templates/document-attributes.adoc
  docs/guides/server/reverseproxy.adoc
Labels: team/cloud-native

#35223 fix: prevent inclusion of characters that could lead to FileVault pat…
  docs/documentation/server_admin/topics/vault.adoc
  docs/documentation/upgrading/topics/changes/changes-26_0_6.adoc
  docs/guides/server/vault.adoc
  services/src/main/java/org/keycloak/vault/AbstractVaultProvider.java
  services/src/main/java/org/keycloak/vault/AbstractVaultProviderFactory.java
  services/src/main/java/org/keycloak/vault/FilesPlainTextVaultProvider.java
  services/src/test/java/org/keycloak/vault/PlainTextVaultProviderTest.java
  services/src/test/resources/org/keycloak/vault/keyonly__escaped
  services/src/test/resources/org/keycloak/vault/keyonly_legacy
Labels: team/cloud-native

#35198 Do not show internal details in KcUnrecognizedPropertyExceptionHandler
  services/src/main/java/org/keycloak/services/error/KcUnrecognizedPropertyExceptionHandler.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#35210 Fix typo `www.recatcha.net` -> `www.recaptcha.net` in docs
  docs/documentation/server_admin/topics/users/proc-enabling-recaptcha.adoc
Labels: status/ready

#34940 [Backport] Allow returning attributes when querying organizations
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationsResource.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationsResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34923 Send exact param in user attr search only when it is enabled
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
Labels: team/ui

#34979 Ignore Accept-Language header for email themes
  server-spi/src/main/java/org/keycloak/locale/LocaleSelectorProvider.java
  server-spi/src/main/java/org/keycloak/models/KeycloakContext.java
  services/src/main/java/org/keycloak/email/freemarker/FreeMarkerEmailTemplateProvider.java
  services/src/main/java/org/keycloak/locale/DefaultLocaleSelectorProvider.java
  services/src/main/java/org/keycloak/services/DefaultKeycloakContext.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/EmailTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34997 Use short UUID for ldap components (#34815)
  docs/documentation/server_admin/topics/authentication/webauthn.adoc
  docs/documentation/server_development/topics/user-storage/model-interfaces.adoc
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  server-spi-private/src/test/java/org/keycloak/models/utils/KeycloakModelUtilsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/AbstractLDAPTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#35070 Check the authentication config exists before returning its reference (26.0)
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/AuthenticatorConfigTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#35107 Backport to fix the wrapping issue
  js/apps/admin-ui/src/clients/authorization/NewPolicyDialog.tsx
Labels: team/ui

#35126 Backport to fix a11y issue in FormattedLink
  js/apps/admin-ui/src/components/external-link/FormattedLink.tsx
Labels: team/ui

#35140 Backport to remove obsolete a11y tests
  js/apps/admin-ui/cypress/e2e/users_test.spec.ts
Labels: team/ui

#35197 [Backport] Allow updating the username when registration as email is enabled during LDAP updates
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/UserAttributeLDAPStorageMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPUserProfileTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#35201 [Backport] Make sure unmanaged attributes are populated before updating username when in update email context
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#35123 Resolve scopes from authenticated client sessions when selecting attributes
  server-spi/src/main/java/org/keycloak/models/KeycloakContext.java
  server-spi/src/main/java/org/keycloak/userprofile/UserProfileContext.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/services/DefaultKeycloakContext.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/AbstractUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/config/UPConfigUtilsTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34953 Use a hidden form to do `POST` based logout (#34694)
  js/libs/keycloak-js/src/keycloak.js
Labels: team/ui

#35241 Fix observability links
  docs/guides/observability/configuration-metrics.adoc
  docs/guides/server/caching.adoc
  docs/guides/templates/links.adoc
Labels: team/cloud-native

#35224 Requested grant_types inconsistent with created grant_types for OpenI…
  services/src/main/java/org/keycloak/services/clientregistration/AbstractClientRegistrationProvider.java
  services/src/main/java/org/keycloak/services/clientregistration/oidc/DescriptionConverter.java
  services/src/main/java/org/keycloak/services/clientregistration/oidc/OIDCClientRegistrationProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OIDCClientRegistrationResponseTypesAndGrantsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OIDCClientRegistrationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#35246 fix: ensures that properties are runtime properties are filtered
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
Labels: team/cloud-native

#35247 fix: returning addresses instead of hosts on the ClientConnection
  common/src/main/java/org/keycloak/common/ClientConnection.java
  common/src/main/java/org/keycloak/common/enums/SslRequired.java
  common/src/test/java/org/keycloak/common/enums/SslRequiredTest.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/QuarkusClientConnection.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ProxyHostnameV2DistTest.java
  services/src/main/java/org/keycloak/services/resources/WelcomeResource.java
  services/src/main/java/org/keycloak/utils/SecureContextResolver.java
  services/src/test/java/org/keycloak/utils/SecureContextResolverTest.java
Labels: team/cloud-native

#35250 fix: using stable ordering for deprecated metadata (#34999)
  quarkus/config-api/src/main/java/org/keycloak/config/DeprecatedMetadata.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionBuilder.java
  quarkus/config-api/src/main/java/org/keycloak/config/TruststoreOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/test/java/org/keycloak/config/OptionBuilderTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
Labels: team/cloud-native, flaky-test

#35185 Passivate imported keys if the associate certificate is expired
  common/src/main/java/org/keycloak/common/crypto/CertificateUtilsProvider.java
  common/src/main/java/org/keycloak/common/util/CertificateUtils.java
  crypto/default/src/main/java/org/keycloak/crypto/def/BCCertificateUtilsProvider.java
  crypto/elytron/src/main/java/org/keycloak/crypto/elytron/ElytronCertificateUtilsProvider.java
  crypto/fips1402/src/main/java/org/keycloak/crypto/fips/BCFIPSCertificateUtilsProvider.java
  docs/documentation/upgrading/topics/changes/changes-26_1_0.adoc
  js/apps/account-ui/test/realms/verifiable-credentials-realm.json
  services/src/main/java/org/keycloak/keys/AbstractImportedRsaKeyProviderFactory.java
  services/src/main/java/org/keycloak/keys/AbstractRsaKeyProvider.java
  services/src/main/java/org/keycloak/keys/GeneratedRsaKeyProviderFactory.java
  services/src/main/java/org/keycloak/keys/ImportedRsaKeyProvider.java
  services/src/main/java/org/keycloak/keys/JavaKeystoreKeyProvider.java
  services/src/main/java/org/keycloak/keys/JavaKeystoreKeyProviderFactory.java
  services/src/main/java/org/keycloak/keys/KeyNoteUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/keys/ImportedRsaKeyProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/keys/JavaKeystoreKeyProviderTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#35237 getAll() organization and organization members only returns the first…
  docs/documentation/upgrading/topics/changes/changes-26_0_7.adoc
  docs/documentation/upgrading/topics/changes/changes.adoc
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationMembersResource.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationsResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationGroupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authz/OrganizationAdminPermissionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/AbstractBrokerSelfRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/cache/OrganizationCacheTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/exportimport/OrganizationExportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationOIDCProtocolMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/member/OrganizationMemberTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#34992 Authorization Code Binding to a DPoP Key and DPoP with Pushed Authorization Requests
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthorizationEndpointRequest.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthzEndpointRequestParser.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/AuthorizationCodeGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/PreAuthorizedCodeGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/par/endpoints/ParEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/par/endpoints/request/AuthzEndpointParParser.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/OAuth2Code.java
  services/src/main/java/org/keycloak/services/util/DPoPUtil.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/resource/TestingOIDCEndpointsApplicationResource.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/DPoPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/par/ParWithDPoPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#35007 Fix unordered list in caching guide
  docs/guides/server/caching.adoc
Labels: team/cloud-native

#35155 Flaky test: AuthenticationSessionTest
  testsuite/model/src/main/java/org/keycloak/testsuite/model/HotRodServerRule.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#35284 Remove new test PoC from workflow
  .github/workflows/ci.yml
Labels: flaky-test

#35291 Upgrade to ISPN 15.0.11.Final
  pom.xml
Labels: flaky-test
