Repository keycloak/keycloak, pull requests merged in 2024-02, with the labels that each got.

#26610 Migrating Realm JSON with declarative user profile fails when scope s…
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo23_0_0.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport1903MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/migration-test/migration-realm-19.0.3-user-profile.json
Labels: team/cloud-native, team/store, team/core, flaky-test

#26663 Renamed messages in localization/realm overrides
  js/apps/admin-ui/cypress/e2e/realm_settings_tabs_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/AddTranslationModal.tsx
  js/apps/admin-ui/src/realm-settings/localization/RealmOverrides.tsx
Labels: team/ui

#26322 Allow formating numbers when rendering attributes
  docs/documentation/server_admin/topics/users/user-profile.adoc
  docs/documentation/tests/src/test/resources/ignored-variables
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeAnnotations.tsx
  services/src/main/java/org/keycloak/forms/login/freemarker/model/AbstractUserProfileBean.java
  themes/src/main/resources/theme/base/login/resources/js/common.js
  themes/src/main/resources/theme/base/login/resources/js/kcNumberFormat.js
  themes/src/main/resources/theme/base/login/resources/js/kcNumberUnFormat.js
  themes/src/main/resources/theme/base/login/user-profile-commons.ftl
Labels: status/needs-discussion, status/hold, team/ui, flaky-test

#26666 Fix Keycloak operator setting for cache-config-file
  operator/src/main/java/org/keycloak/operator/Constants.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDistConfigurator.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/KeycloakDistConfiguratorTest.java
Labels: team/cloud-native, flaky-test

#26690 Update Maven dependency versions for docs
  .mvn/wrapper/maven-wrapper.properties
  docs/documentation/header-maven-plugin/pom.xml
  docs/documentation/pom.xml
  docs/maven-plugin/pom.xml
  pom.xml
Labels: flaky-test

#26563 Add authentication test to cypress (#26337)
  js/apps/admin-ui/cypress/e2e/authentication_test.spec.ts
Labels: team/ui

#26693 Fixed disabling role unassign on cancel
  js/apps/admin-ui/src/components/role-mapping/RoleMapping.tsx
Labels: team/ui

#26373 account library
  js/apps/account-ui/package.json
  js/apps/account-ui/src/account-security/AccountRow.tsx
  js/apps/account-ui/src/account-security/DeviceActivity.tsx
  js/apps/account-ui/src/account-security/LinkedAccounts.tsx
  js/apps/account-ui/src/account-security/SigningIn.tsx
  js/apps/account-ui/src/api.ts
  js/apps/account-ui/src/api/methods.ts
  js/apps/account-ui/src/api/request.ts
  js/apps/account-ui/src/applications/Applications.tsx
  js/apps/account-ui/src/content/ContentComponent.tsx
  js/apps/account-ui/src/content/fetchContent.ts
  js/apps/account-ui/src/groups/Groups.tsx
  js/apps/account-ui/src/index.ts
  js/apps/account-ui/src/keycloak.ts
  js/apps/account-ui/src/main.tsx
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
  js/apps/account-ui/src/resources/EditTheResource.tsx
  js/apps/account-ui/src/resources/PermissionRequest.tsx
  js/apps/account-ui/src/resources/Resources.tsx
  js/apps/account-ui/src/resources/ResourcesTab.tsx
  js/apps/account-ui/src/resources/ShareTheResource.tsx
  js/apps/account-ui/src/root/Header.tsx
  js/apps/account-ui/src/root/KeycloakContext.tsx
  js/apps/account-ui/src/root/PageNav.tsx
  js/apps/account-ui/src/root/Root.tsx
  js/apps/account-ui/src/root/header.module.css
  js/apps/account-ui/test/account-security.spec.ts
  js/apps/account-ui/vite.config.ts
Labels: team/ui

#26711 Upgrade Husky to latest version
  js/.husky/.gitignore
  js/.husky/pre-commit
  js/package.json
  js/pnpm-lock.yaml
Labels: kind/task, team/ui

#26709 Remove un-maintained domain-extension example
  examples/providers/domain-extension/README.md
  examples/providers/domain-extension/invoke-authenticated.sh
  examples/providers/domain-extension/pom.xml
  examples/providers/domain-extension/src/main/java/org/keycloak/examples/domainextension/CompanyRepresentation.java
  examples/providers/domain-extension/src/main/java/org/keycloak/examples/domainextension/jpa/Company.java
  examples/providers/domain-extension/src/main/java/org/keycloak/examples/domainextension/jpa/ExampleJpaEntityProvider.java
  examples/providers/domain-extension/src/main/java/org/keycloak/examples/domainextension/jpa/ExampleJpaEntityProviderFactory.java
  examples/providers/domain-extension/src/main/java/org/keycloak/examples/domainextension/rest/CompanyResource.java
  examples/providers/domain-extension/src/main/java/org/keycloak/examples/domainextension/rest/ExampleRealmResourceProvider.java
  examples/providers/domain-extension/src/main/java/org/keycloak/examples/domainextension/rest/ExampleRealmResourceProviderFactory.java
  examples/providers/domain-extension/src/main/java/org/keycloak/examples/domainextension/rest/ExampleRestResource.java
  examples/providers/domain-extension/src/main/java/org/keycloak/examples/domainextension/spi/ExampleService.java
  examples/providers/domain-extension/src/main/java/org/keycloak/examples/domainextension/spi/ExampleServiceProviderFactory.java
  examples/providers/domain-extension/src/main/java/org/keycloak/examples/domainextension/spi/ExampleSpi.java
  examples/providers/domain-extension/src/main/java/org/keycloak/examples/domainextension/spi/impl/ExampleServiceImpl.java
  examples/providers/domain-extension/src/main/java/org/keycloak/examples/domainextension/spi/impl/ExampleServiceProviderFactoryImpl.java
  examples/providers/domain-extension/src/main/resources/META-INF/example-changelog.xml
  examples/providers/domain-extension/src/main/resources/META-INF/services/org.keycloak.connections.jpa.entityprovider.JpaEntityProviderFactory
  examples/providers/domain-extension/src/main/resources/META-INF/services/org.keycloak.examples.domainextension.spi.ExampleServiceProviderFactory
  examples/providers/domain-extension/src/main/resources/META-INF/services/org.keycloak.provider.Spi
  examples/providers/domain-extension/src/main/resources/META-INF/services/org.keycloak.services.resource.RealmResourceProviderFactory
  examples/providers/pom.xml
Labels: flaky-test

#26542 removing duplicate open id scope
  services/src/main/java/org/keycloak/protocol/oidc/OIDCWellKnownProvider.java
Labels: flaky-test

#26729 fix empty attributes parsing
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedRealm.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  server-spi/src/main/java/org/keycloak/models/RealmModel.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#26708 Remove RealmModel from authorization services interfaces
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/client/ClientPolicyProviderFactory.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/clientscope/ClientScopePolicyProviderFactory.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/permission/UMAPolicyProviderFactory.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/authorization/InfinispanCacheStoreFactoryProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/authorization/PermissionTicketAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/authorization/PolicyAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/authorization/ResourceAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/authorization/ResourceServerAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/authorization/ScopeAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/authorization/StoreFactoryCacheSession.java
  model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAAuthorizationStoreFactory.java
  model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAPermissionTicketStore.java
  model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAPolicyStore.java
  model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAResourceServerStore.java
  model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAResourceStore.java
  model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAScopeStore.java
  model/jpa/src/main/java/org/keycloak/authorization/jpa/store/PermissionTicketAdapter.java
  model/jpa/src/main/java/org/keycloak/authorization/jpa/store/PolicyAdapter.java
  model/jpa/src/main/java/org/keycloak/authorization/jpa/store/ResourceAdapter.java
  model/jpa/src/main/java/org/keycloak/authorization/jpa/store/ResourceServerAdapter.java
  model/jpa/src/main/java/org/keycloak/authorization/jpa/store/ScopeAdapter.java
  server-spi-private/src/main/java/org/keycloak/authorization/AuthorizationProvider.java
  server-spi-private/src/main/java/org/keycloak/authorization/UserManagedPermissionUtil.java
  server-spi-private/src/main/java/org/keycloak/authorization/model/ResourceServer.java
  server-spi-private/src/main/java/org/keycloak/authorization/permission/Permissions.java
  server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/PermissionTicketAwareDecisionResultCollector.java
  server-spi-private/src/main/java/org/keycloak/authorization/store/PermissionTicketStore.java
  server-spi-private/src/main/java/org/keycloak/authorization/store/PolicyStore.java
  server-spi-private/src/main/java/org/keycloak/authorization/store/ResourceServerStore.java
  server-spi-private/src/main/java/org/keycloak/authorization/store/ResourceStore.java
  server-spi-private/src/main/java/org/keycloak/authorization/store/ScopeStore.java
  server-spi-private/src/main/java/org/keycloak/authorization/store/syncronization/ClientApplicationSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/authorization/store/syncronization/GroupSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/authorization/store/syncronization/UserSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  services/src/main/java/org/keycloak/authorization/admin/PolicyEvaluationService.java
  services/src/main/java/org/keycloak/authorization/admin/PolicyResourceService.java
  services/src/main/java/org/keycloak/authorization/admin/PolicyService.java
  services/src/main/java/org/keycloak/authorization/admin/ResourceSetService.java
  services/src/main/java/org/keycloak/authorization/admin/ScopeService.java
  services/src/main/java/org/keycloak/authorization/admin/representation/PolicyEvaluationResponseBuilder.java
  services/src/main/java/org/keycloak/authorization/authorization/AuthorizationTokenService.java
  services/src/main/java/org/keycloak/authorization/protection/permission/AbstractPermissionService.java
  services/src/main/java/org/keycloak/authorization/protection/permission/PermissionTicketService.java
  services/src/main/java/org/keycloak/authorization/protection/policy/UserManagedPermissionService.java
  services/src/main/java/org/keycloak/services/resources/account/resources/ResourceService.java
  services/src/main/java/org/keycloak/services/resources/account/resources/ResourcesService.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/ClientPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/GroupPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/IdentityProviderPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissions.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UserManagedPermissionServiceTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/authz/ConcurrentAuthzTest.java
Labels: team/cloud-native, team/store, team/core-clients, team/core-iam

#26736 Upgrade to Quarkus 3.7.1
  pom.xml
  quarkus/config-api/src/main/java/org/keycloak/config/HealthOptions.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HealthPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/health/ReactiveHealthHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/health/ReactiveLivenessHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/health/ReactiveReadinessHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/health/KeycloakReadyAsyncHealthCheck.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/health/KeycloakReadyHealthCheck.java
  quarkus/runtime/src/main/resources/application.properties
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HealthDistTest.java
  testsuite/utils/pom.xml
Labels: team/cloud-native, team/store, team/core-clients, team/core-iam

#26659 Supported option to specify maximum threads used to handle HTTP requests
  quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HttpDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.unix.approved.txt
Labels: team/cloud-native

#26748 Tooltip for attribute name in user-profile configuration is incorrect
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
Labels: team/ui

#26743 Keep time units upon time entry
  js/apps/admin-ui/src/components/time-selector/TimeSelector.tsx
Labels: team/ui

#26539 Add comment about MySQL invisible Primary key generation
  docs/guides/server/db.adoc
Labels: team/store

#26786 Fix Operator tests on ARM-based machines
  operator/src/test/resources/example-postgres.yaml
Labels: team/cloud-native

#26778 Add actions for flaky Admin UI tests
  js/apps/admin-ui/cypress/e2e/authentication_test.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/ListingPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/authentication/RequiredActions.ts
Labels: team/ui

#26789 fix: using iteration to allow recursive structures
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/realmimport/KeycloakRealmImport.java
  operator/src/main/java/org/keycloak/representations/overrides/NoSubGroupsGroupRepresentation.java
  operator/src/main/java/org/keycloak/representations/overrides/NoSubGroupsGroupRepresentationList.java
  operator/src/main/java/org/keycloak/representations/overrides/NoSubcomponentsComponentExportRepresentation.java
  operator/src/main/java/org/keycloak/representations/overrides/NoSubcomponentsComponentExportRepresentationMap.java
  operator/src/test/resources/test-serialization-realmimport-cr.yml
Labels: team/cloud-native, flaky-test

#26797 Upgrade arquilliam bom to match org.apache.maven dependency versions from Quarkus
  quarkus/CONTRIBUTING.md
  testsuite/integration-arquillian/pom.xml
Labels: team/cloud-native, team/store, team/core-clients, team/core-iam

#26760 Fixed/improved issues with effective message bundles tab
  js/apps/admin-ui/src/components/dropdown-panel/DropdownPanel.tsx
  js/apps/admin-ui/src/components/dropdown-panel/dropdown-panel.css
  js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx
  js/apps/admin-ui/src/realm-settings/localization/LocalizationTab.tsx
Labels: team/ui

#26670 Add Ukrainian localization
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_uk.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_uk.properties
  themes/src/main/resources-community/theme/base/account/theme.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_uk.properties
  themes/src/main/resources-community/theme/base/admin/theme.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_uk.properties
  themes/src/main/resources-community/theme/base/email/theme.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_uk.properties
  themes/src/main/resources-community/theme/base/login/theme.properties
  themes/src/main/resources/theme/base/account/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/ui, flaky-test

#26796 Update Keycloak operator example with correct hostname syntax
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakSharedCsvMetadata.java
Labels: team/cloud-native

#26808 PKCE should return error if code_verifier sent but no code_challenge in the authorization request
  services/src/main/java/org/keycloak/protocol/oidc/utils/PkceUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/AbstractFAPITest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthProofKeyForCodeExchangeTest.java
Labels: team/cloud-native, team/store, flaky-test, team/core-clients, team/core-iam

#26779 Update messages_pt_BR.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_pt_BR.properties
Labels: team/ui

#26596 Introduce index.ftl into base account theme
  docs/documentation/server_development/topics/themes.adoc
  themes/src/main/resources/theme/base/account/index.ftl
  themes/src/main/resources/theme/base/account/messages/messages_en.properties
Labels: area/account/ui, team/ui, flaky-test

#26599 added refresh button
  js/apps/admin-ui/src/components/table-toolbar/KeycloakDataTable.tsx
Labels: team/ui

#26558 Use code from RestEasy to create and set cookies
  common/src/main/java/org/keycloak/common/util/ServerCookie.java
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  pom.xml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/QuarkusHttpResponse.java
  server-spi-private/src/main/java/org/keycloak/cookie/CookieScope.java
  server-spi/src/main/java/org/keycloak/http/HttpCookie.java
  server-spi/src/main/java/org/keycloak/http/HttpResponse.java
  services/src/main/java/org/keycloak/cookie/CookiePathResolver.java
  services/src/main/java/org/keycloak/cookie/CookieSecureResolver.java
  services/src/main/java/org/keycloak/cookie/DefaultCookieProvider.java
  services/src/main/java/org/keycloak/cookie/DefaultCookieProviderFactory.java
  services/src/main/java/org/keycloak/forms/login/freemarker/AuthenticationStateCookie.java
  services/src/main/java/org/keycloak/services/HttpResponseImpl.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationSessionManager.java
  services/src/main/resources/org/keycloak/protocol/oidc/endpoints/login-status-iframe.html
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cookies/DefaultCookieProviderTest.java
  themes/src/main/resources/theme/base/login/resources/js/authChecker.js
Labels: team/cloud-native, team/store, team/core, flaky-test, team/core-clients, team/core-iam

#26827 Fixed tabbing issues in dropdown forms
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/events/tabs/AdminEventsTab.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/events/tabs/UserEventsTab.ts
  js/apps/admin-ui/src/components/dropdown-panel/DropdownPanel.tsx
  js/apps/admin-ui/src/components/dropdown-panel/dropdown-panel.css
  js/apps/admin-ui/src/components/users/UserDataTableToolbarItems.tsx
  js/apps/admin-ui/src/events/AdminEvents.tsx
  js/apps/admin-ui/src/events/EventsSection.tsx
  js/apps/admin-ui/src/events/events.css
  js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx
Labels: team/ui

#26737 Ignore empty attribute values when retriveing boolean/int/long (#26729)
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedRealm.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  server-spi/src/main/java/org/keycloak/models/RealmModel.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java
Labels: team/cloud-native, team/store, flaky-test, team/core-clients, team/core-iam

#26831 Fixed token expiration help text
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/initial-access/CreateInitialAccessToken.tsx
Labels: team/ui

#26820 Use version specific tag for Keycloak images in the docs
  docs/guides/attributes.adoc
  docs/guides/server/containers.adoc
  docs/guides/server/db.adoc
  docs/guides/server/fips.adoc
Labels: team/cloud-native

#26751 Empty error message when validation issue due the PersonNameProhibite…
  server-spi-private/src/main/java/org/keycloak/validate/validators/PatternValidator.java
  server-spi/src/main/java/org/keycloak/validate/ValidatorConfig.java
  services/src/main/java/org/keycloak/userprofile/validator/PersonNameProhibitedCharactersValidator.java
  services/src/main/java/org/keycloak/userprofile/validator/UsernameIDNHomographValidator.java
  services/src/main/java/org/keycloak/userprofile/validator/UsernameProhibitedCharactersValidator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/store, flaky-test, team/core-clients, team/core-iam

#26702 Improvements for test connection and authentication in the LDAP provider
  federation/ldap/src/main/java/org/keycloak/services/managers/LDAPServerCapabilitiesManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserFederationLdapConnectionTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test, team/core-clients, team/core-iam

#26738 Ignore empty attribute values when retriveing boolean/int/long (#26729)
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedRealm.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  server-spi/src/main/java/org/keycloak/models/RealmModel.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#22717 Support customize common path in welcome theme
  services/src/main/java/org/keycloak/services/resources/WelcomeResource.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#26839 Fixed search results after removing chips from effective message bundles
  js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx
Labels: team/ui

#26840 chore: clarify default creds in readme, add .vscode to gitignore
  .gitignore
  js/apps/admin-ui/README.md
Labels: kind/task, team/ui

#26857 Removed duplicate refresh buttons
  js/apps/admin-ui/src/components/dropdown-panel/DropdownPanel.tsx
  js/apps/admin-ui/src/events/AdminEvents.tsx
  js/apps/admin-ui/src/events/EventsSection.tsx
  js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx
Labels: team/ui

#26848 Add cookie type builder
  server-spi-private/src/main/java/org/keycloak/cookie/CookieType.java
Labels: flaky-test

#26630 Added event for temporary lockout for brute force protector
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/server_admin/topics/events/login.adoc
  docs/documentation/topics/templates/document-attributes.adoc
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  server-spi-private/src/main/java/org/keycloak/events/Details.java
  server-spi-private/src/main/java/org/keycloak/events/EventType.java
  services/src/main/java/org/keycloak/services/ServicesLogger.java
  services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test, team/core-clients, team/core-iam

#26864 task: adds event diagnostics for failed tests
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
Labels: team/cloud-native

#26788 Removing version overrides and further aligning with quarkus versions
  authz/policy-enforcer/pom.xml
  operator/pom.xml
  pom.xml
  quarkus/set-quarkus-version.sh
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/integration-arquillian/tests/pom.xml
  testsuite/utils/pom.xml
Labels: team/cloud-native, team/store, flaky-test, team/core-clients, team/core-iam

#26718 Brute Force Detection is disabled when updating frontenUrl via admin client
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#26525 Fix confusing SAML NameId mapper format tooltip
  docs/documentation/release_notes/topics/24_0_0.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  services/src/main/java/org/keycloak/protocol/saml/mappers/NameIdMapperHelper.java
Labels: team/core, team/ui, flaky-test

#26838 #26826 fix for Freemarker erroneously escapes/sanitizes URL in template.ftl (&amp;)
  themes/src/main/resources/theme/base/login/template.ftl
Labels: flaky-test

#26891 [Fixes #26651] Do not verify nonce in access and refresh tokens (only…
  js/libs/keycloak-js/src/keycloak.js
Labels: team/ui

#26414 fix: change from operator. to kc-operator. properties
  .github/workflows/operator-ci.yml
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  operator/README.md
  operator/scripts/olm-testing.sh
  operator/src/main/java/org/keycloak/operator/Config.java
  operator/src/main/resources/application-rhbk.properties
  operator/src/main/resources/application.properties
  operator/src/test/resources/application.properties
Labels: flaky-test

#26909 UPDATE_EMAIL action token handling should allow the user to resume its navigation to the redirect uri
  services/src/main/java/org/keycloak/authentication/actiontoken/updateemail/UpdateEmailActionToken.java
  services/src/main/java/org/keycloak/authentication/actiontoken/updateemail/UpdateEmailActionTokenHandler.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateEmail.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateEmailTestWithVerificationTest.java
Labels: team/cloud-native, team/store, team/core-clients, team/core-iam

#26850 Upgrade Infinispan to the latest version
  pom.xml
Labels: flaky-test

#26892 modifying start-server.js to work on windows
  js/apps/keycloak-server/package.json
  js/apps/keycloak-server/scripts/start-server.js
Labels: team/ui

#26912 fix: adds service-ca.crt to the trust stores
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
Labels: team/cloud-native

#26926 use login realm (#25466)
  js/apps/admin-ui/src/i18n/i18n.ts
Labels: team/ui

#26899 add user-profile admin-ui test to realm_settings_user_profile_enabled.spec.ts: "Checks that attribute with select-annotation is displayed and editable when user is created/edited"
  js/apps/admin-ui/cypress/e2e/realm_settings_user_profile_enabled.spec.ts
  js/apps/admin-ui/cypress/e2e/users_test.spec.ts
  js/apps/admin-ui/cypress/support/forms/FormValidation.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/UserProfile.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/ValidatorConfigDialogue.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/CreateUserPage.ts
  js/apps/admin-ui/cypress/support/util/AdminClient.ts
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesGroupTab.tsx
Labels: team/ui

#26930 Fix MembershipType so that NPE is not thrown when an empty member is …
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/MembershipType.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
Labels: team/cloud-native, team/store, team/core-clients, team/core-iam

#26811 Shorter lifespan for offline session cache entries in memory
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/server_admin/topics/sessions/offline.adoc
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProviderFactory.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/CrossDCInfinispan.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/Infinispan.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderOfflineModelTest.java
Labels: team/store, flaky-test

#26685 fix flow status
  js/apps/admin-ui/src/authentication/BindFlowDialog.tsx
  js/apps/admin-ui/src/authentication/FlowDetails.tsx
Labels: team/ui

#26938 Upgrade to Quarkus 3.7.2
  pom.xml
Labels: flaky-test

#26739 added new q param
  js/libs/keycloak-admin-client/src/resources/groups.ts
Labels: team/ui

#26740 bigger column
  js/apps/admin-ui/src/events/events.css
Labels: team/ui

#26911 Allow setting a default user profile configuration
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProviderFactory.java
  services/src/main/java/org/keycloak/userprofile/config/UPConfigUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/userprofile/UserProfileAdminTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/AbstractUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/CustomUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: priority/important, team/cloud-native, team/store, flaky-test, team/core-clients, team/core-iam

#26928 Fipsdist test changes backport
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FipsDistTest.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/KeycloakDistributionDecorator.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/DockerKeycloakDistribution.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/KeycloakDistribution.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
Labels: team/cloud-native, flaky-test

#26680 debeerify in account as user profile can have dots
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
  js/libs/ui-shared/src/main.ts
  js/libs/ui-shared/src/user-profile/utils.ts
Labels: team/ui

#26975 fix: switching to clusterip service
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/resources/example-postgres.yaml
Labels: team/cloud-native, flaky-test

#26924 Add account console group test
  js/apps/account-ui/src/groups/Groups.tsx
  js/apps/account-ui/test/groups.spec.ts
  js/apps/account-ui/test/realms/groups-realm.json
Labels: team/ui

#26962 Run adapters in a separate job on GitHub Actions
  .github/actions/build-keycloak/action.yml
  .github/actions/upload-heapdumps/action.yml
  .github/workflows/ci.yml
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/servers/app-server/pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/AppServerTestEnricher.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/authz/example/AbstractBaseServletAuthzAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/authz/example/AbstractServletAuthzAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/authz/example/AbstractServletPolicyEnforcerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/authz/example/DefaultAuthzConfigAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/authz/example/PermissiveModeAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/authz/example/ServletAuthzCIPAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/authz/example/ServletAuthzCacheDisabledAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/authz/example/ServletAuthzCacheLifespanAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/authz/example/ServletAuthzLazyLoadPathsAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/authz/example/ServletAuthzNoLazyLoadPathsAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/authz/example/ServletPolicyEnforcerLifespanTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/authz/example/ServletPolicyEnforcerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SamlXMLAttacksTest.java
  testsuite/integration-arquillian/tests/base/testsuites/base-suite
  testsuite/integration-arquillian/tests/other/adapters/karaf/fuse61/pom.xml
  testsuite/integration-arquillian/tests/other/adapters/karaf/fuse62/pom.xml
  testsuite/integration-arquillian/tests/other/adapters/karaf/karaf3/pom.xml
  testsuite/integration-arquillian/tests/other/adapters/karaf/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#26964 Use the appropriate database dialect to add quotes to the schema name
  model/jpa/src/main/java/org/keycloak/connections/jpa/util/JpaUtils.java
Labels: flaky-test, team/core-iam, team/cross-dc

#26580 added patternfly 5 update password
  themes/src/main/resources/theme/keycloak.v2/login/login-update-password.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login.ftl
  themes/src/main/resources/theme/keycloak.v2/login/theme.properties
Labels: team/ui

#26734 pf5 refactor client scope
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/client_scopes/CreateClientScopePage.ts
  js/apps/admin-ui/src/client-scopes/details/MappingDetails.tsx
  js/apps/admin-ui/src/client-scopes/details/ScopeForm.tsx
  js/libs/ui-shared/src/controls/FormLabel.tsx
  js/libs/ui-shared/src/controls/SwitchControl.tsx
Labels: team/ui

#26876 fix: adds pfx as a recognized extension
  common/src/main/java/org/keycloak/common/util/KeystoreUtil.java
  common/src/test/java/org/keycloak/common/util/KeystoreUtilTest.java
  services/src/main/java/org/keycloak/truststore/FileTruststoreProviderFactory.java
  services/src/main/java/org/keycloak/truststore/TruststoreBuilder.java
  services/src/test/java/org/keycloak/truststore/TruststoreBuilderTest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/KeystoreUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/registration/KcRegTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#26877 task: addressing build warnings
  services/pom.xml
  testsuite/integration-arquillian/util/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#26994 Do not require non-builtin attributes for service accounts
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ServiceAccountUserProfileTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#26472 Added SPIs for ClientType and ClientTypeManager
  core/src/main/java/org/keycloak/representations/idm/ClientTypeRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/ClientTypesRepresentation.java
  server-spi-private/src/main/java/org/keycloak/client/clienttype/ClientType.java
  server-spi-private/src/main/java/org/keycloak/client/clienttype/ClientTypeException.java
  server-spi-private/src/main/java/org/keycloak/client/clienttype/ClientTypeManager.java
  server-spi-private/src/main/java/org/keycloak/client/clienttype/ClientTypeManagerFactory.java
  server-spi-private/src/main/java/org/keycloak/client/clienttype/ClientTypeManagerSpi.java
  server-spi-private/src/main/java/org/keycloak/client/clienttype/ClientTypeProvider.java
  server-spi-private/src/main/java/org/keycloak/client/clienttype/ClientTypeProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/client/clienttype/ClientTypeSpi.java
  server-spi-private/src/main/resources/META-INF/services/org.keycloak.provider.Spi
  services/src/main/java/org/keycloak/services/clienttype/DefaultClientTypeManager.java
  services/src/main/java/org/keycloak/services/clienttype/DefaultClientTypeManagerFactory.java
  services/src/main/java/org/keycloak/services/clienttype/impl/DefaultClientType.java
  services/src/main/java/org/keycloak/services/clienttype/impl/DefaultClientTypeProvider.java
  services/src/main/java/org/keycloak/services/clienttype/impl/DefaultClientTypeProviderFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.client.clienttype.ClientTypeManagerFactory
  services/src/main/resources/META-INF/services/org.keycloak.client.clienttype.ClientTypeProviderFactory
  services/src/main/resources/keycloak-default-client-types.json
Labels: flaky-test

#27028 refresh the when we need to refresh
  js/apps/admin-ui/src/components/table-toolbar/KeycloakDataTable.tsx
Labels: team/ui

#26986 Add signing-in tests
  js/apps/account-ui/src/account-security/SigningIn.tsx
  js/apps/account-ui/test/account-security/signing-in.spec.ts
  js/apps/account-ui/test/admin-client.ts
  js/apps/account-ui/test/groups.spec.ts
  js/apps/account-ui/test/realms/groups-realm.json
Labels: team/ui

#26970 Add Multi-AZ Aurora DB to CI store-integration-tests
  .github/actions/aurora-create-database/action.yml
  .github/actions/aurora-delete-database/action.yml
  .github/scripts/ansible/.gitignore
  .github/scripts/ansible/ansible.cfg
  .github/scripts/ansible/aws_ec2.sh
  .github/scripts/ansible/aws_ec2.yml
  .github/scripts/ansible/keycloak.yml
  .github/scripts/ansible/keycloak_ec2_installer.sh
  .github/scripts/ansible/mvn.yml
  .github/scripts/ansible/mvn_ec2_runner.sh
  .github/scripts/ansible/requirements.yml
  .github/scripts/ansible/roles/aws_ec2/README.md
  .github/scripts/ansible/roles/aws_ec2/defaults/main.yml
  .github/scripts/ansible/roles/aws_ec2/tasks/create-resources.yml
  .github/scripts/ansible/roles/aws_ec2/tasks/delete-resources.yml
  .github/scripts/ansible/roles/aws_ec2/tasks/main.yml
  .github/scripts/ansible/roles/aws_ec2/tasks/manage-instances.yml
  .github/scripts/ansible/roles/aws_ec2/templates/inventory.yml.j2
  .github/scripts/ansible/roles/keycloak_ec2_installer/README.md
  .github/scripts/ansible/roles/keycloak_ec2_installer/defaults/main.yml
  .github/scripts/ansible/roles/keycloak_ec2_installer/tasks/install.yml
  .github/scripts/ansible/roles/keycloak_ec2_installer/tasks/main.yml
  .github/scripts/ansible/roles/mvn_ec2_runner/README.md
  .github/scripts/ansible/roles/mvn_ec2_runner/defaults/main.yml
  .github/scripts/ansible/roles/mvn_ec2_runner/tasks/main.yml
  .github/scripts/ansible/roles/mvn_ec2_runner/tasks/run.yml
  .github/scripts/aws/rds/aurora_common.sh
  .github/scripts/aws/rds/aurora_create.sh
  .github/scripts/aws/rds/aurora_delete.sh
  .github/workflows/ci.yml
  testsuite/integration-arquillian/HOW-TO-RUN.md
  testsuite/integration-arquillian/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam, team/cross-dc

#27015 Cors modifications for UserInfo endpoint
  server-spi-private/src/main/java/org/keycloak/services/cors/Cors.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/UserInfoEndpoint.java
  services/src/main/java/org/keycloak/services/cors/DefaultCors.java
  services/src/main/java/org/keycloak/services/util/UserSessionUtil.java
  services/src/main/java/org/keycloak/utils/OAuth2Error.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/UserInfoEndpointCorsTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#26872 Do not print executed commands in loop when checking deployments
  .github/actions/conditional/conditions
  operator/scripts/check-crds-installed.sh
  operator/scripts/check-examples-installed.sh
  operator/scripts/install-keycloak-operator.sh
Labels: team/cloud-native, flaky-test

#26939 fix: add an info message, and converts info to debug on non-pem files
  services/src/main/java/org/keycloak/truststore/TruststoreBuilder.java
Labels: flaky-test

#26957 Increase internal algorithm security using HS512 and 128 byte hmac keys
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo24_0_0.java
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  server-spi-private/src/main/java/org/keycloak/models/utils/DefaultKeyProviders.java
  services/src/main/java/org/keycloak/jose/jws/DefaultTokenManager.java
  services/src/main/java/org/keycloak/keys/Attributes.java
  services/src/main/java/org/keycloak/keys/GeneratedHmacKeyProviderFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/channel/CIBAAuthenticationRequest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/InitialAccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RestartCookieTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/keys/FallbackKeyProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/keys/GeneratedHmacKeyProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/keys/KeyRotationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthProofKeyForCodeExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ResourceOwnerPasswordCredentialsGrantTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ServiceAccountTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/hok/HoKTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#26974 Fixing UriValidator
  js/apps/admin-ui/src/components/dynamic/MultivaluedStringComponent.tsx
  server-spi-private/src/main/java/org/keycloak/validate/validators/UriValidator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/validation/BuiltinValidatorsTest.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#26661 Supported option to specify resource management for pods in Keycloak CR
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  docs/guides/operator/advanced-configuration.adoc
  docs/guides/server/containers.adoc
  operator/src/main/java/org/keycloak/operator/Config.java
  operator/src/main/java/org/keycloak/operator/Utils.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakSpec.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/realmimport/KeycloakRealmImportSpec.java
  operator/src/main/resources/application.properties
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/RealmImportTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/CRSerializationTest.java
  operator/src/test/resources/test-serialization-keycloak-cr-with-empty-list.yml
  operator/src/test/resources/test-serialization-keycloak-cr.yml
  operator/src/test/resources/test-serialization-realmimport-cr.yml
  quarkus/container/Dockerfile
  quarkus/dist/src/main/content/bin/kc.bat
  quarkus/dist/src/main/content/bin/kc.sh
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JavaOptsScriptTest.java
Labels: team/cloud-native, flaky-test

#27035 fix: increasing the default max-form-attribute-size
  quarkus/runtime/src/main/resources/application.properties
Labels: team/cloud-native, flaky-test

#27037 Upgrade to Quarkus 3.7.3
  pom.xml
Labels: flaky-test

#27058 During password reset, the baseURL is not shown on the info page afte…
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27046 Fix realm_test in cypress (#26400)
  js/apps/admin-ui/cypress/e2e/realm_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/CreateRealmPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/ListingPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/SidebarPage.ts
Labels: team/ui

#27061 Aurora Postgres IT: Upload flaky and surefire test reports
  .github/scripts/ansible/roles/mvn_ec2_runner/tasks/run.yml
  .github/workflows/ci.yml
Labels: flaky-test

#27082 Check if kerberos auth is enabled before creating the kerberos princi…
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
Labels: flaky-test

#27087 Fix MembershipType so that NPE is not thrown when an empty member is …
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/MembershipType.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
Labels: team/cloud-native

#26992 Use the appropriate database dialect to add quotes to the schema name
  model/jpa/src/main/java/org/keycloak/connections/jpa/util/JpaUtils.java
Labels: flaky-test

#27049 Add Amazon Aurora PostgreSQL to the list of tested databases
  .github/actions/conditional/conditions
  .github/scripts/aws/rds/aurora_common.sh
  docs/guides/high-availability/partials/aurora/aurora-multiaz-create-procedure.adoc
  docs/guides/server/db.adoc
  pom.xml
Labels: team/cloud-native, flaky-test

#27050 Disable Groovy Closures when bootstrapping Picocli
  quarkus/dist/src/main/content/bin/kc.bat
  quarkus/dist/src/main/content/bin/kc.sh
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/DefaultFactory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JavaOptsScriptTest.java
Labels: team/cloud-native, flaky-test

#27074 Add device activity tests
  js/apps/account-ui/src/account-security/DeviceActivity.tsx
  js/apps/account-ui/test/account-security/device-activity.spec.ts
Labels: team/ui

#27024 permissions can be empty
  js/apps/account-ui/src/resources/PermissionRequest.tsx
Labels: team/ui

#27108 Add EdDSA/Ed25519 to WebAuthn Signature algorithms
  js/apps/admin-ui/src/authentication/policies/WebauthnPolicy.tsx
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnRegister.java
Labels: area/authentication/webauthn, team/ui

#27104 Rename Resident key to Discoverable Credential
  docs/documentation/server_admin/topics/authentication/webauthn.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: area/authentication/webauthn, team/ui

#22840 Invalid redirect uri when identity provider alias has spaces
  server-spi-private/src/main/java/org/keycloak/utils/ReservedCharValidator.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
Labels: missing/tests, team/cloud-native, flaky-test, team/core-clients, team/core-iam, team/core-shared

#27129 Fix docs around `--config-file` option
  docs/guides/server/configuration.adoc
Labels: team/cloud-native

#27131 Fix Microsoft social login test case
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social/MicrosoftLoginPage.java
Labels: team/cloud-native, flaky-test, backport/22.0, backport/23.0, team/core-clients, team/core-iam

#27094 Change Open ID Connect to OpenID Connect in UI and docs
  docs/documentation/server_admin/topics/clients/oidc/con-advanced-settings.adoc
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/tabs/AdvancedTab.ts
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_pl.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#27141 chore: don't render locale selector when there are no options
  js/libs/ui-shared/src/user-profile/LocaleSelector.tsx
Labels: team/ui

#27100 Distinguish user registration action label from the security key registration action's one
  themes/src/main/resources-community/theme/base/login/messages/messages_ar.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_da.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_el.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fa.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fi.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_hu.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_lt.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_lv.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_nl.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_no.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_pl.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ru.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_sk.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_sv.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_th.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_tr.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_uk.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_zh_CN.properties
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/webauthn-register.ftl
Labels: flaky-test

#25647 Client policies: executor for validate and match a redirect URI
  docs/documentation/server_admin/topics/clients/client-policies.adoc
  docs/documentation/server_admin/topics/threat/open-redirect.adoc
  docs/documentation/server_admin/topics/threat/redirect.adoc
  services/src/main/java/org/keycloak/services/clientpolicy/executor/SecureRedirectUrisEnforcerExecutor.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/SecureRedirectUrisEnforcerExecutorFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.services.clientpolicy.executor.ClientPolicyExecutorProviderFactory
  services/src/test/java/org/keycloak/services/clientpolicy/executor/SecureRedirectUrisEnforcerExecutorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/SecureRedirectUrisEnforcerExecutorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ClientPoliciesUtil.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27145 Fixed setting requiredActions to "UPDATE_PASSWORD" when user credential created
  js/apps/admin-ui/src/user/UserForm.tsx
  js/apps/admin-ui/src/user/user-credentials/ResetPasswordDialog.tsx
Labels: team/ui

#27155 Fix Microsoft social login test case
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social/MicrosoftLoginPage.java
Labels: team/cloud-native

#27156 Fix Microsoft social login test case
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social/MicrosoftLoginPage.java
Labels: team/cloud-native

#27034 fixed labels
  js/apps/admin-ui/src/clients/authorization/AuthorizationEvaluate.tsx
  js/apps/admin-ui/src/clients/authorization/KeyBasedAttributeInput.tsx
Labels: team/ui

#26745 Create a seamless transition.
  js/apps/admin-ui/src/authentication/components/FlowDiagram.tsx
Labels: team/ui

#27167 Remove Cordova examples
  examples/README.md
  examples/cordova-native/.gitignore
  examples/cordova-native/README.md
  examples/cordova-native/config.xml
  examples/cordova-native/example-realm.json
  examples/cordova-native/package-lock.json
  examples/cordova-native/package.json
  examples/cordova-native/www/index.html
  examples/cordova/.gitignore
  examples/cordova/README.md
  examples/cordova/example-realm.json
  examples/cordova/www/config.xml
  examples/cordova/www/index.html
Labels: area/docs, kind/eol

#27033 added some build options to account-ui
  js/apps/account-ui/package.json
  js/apps/account-ui/src/index.ts
  js/apps/account-ui/vite.config.ts
  js/pnpm-lock.yaml
Labels: team/ui

#27149 Allow overriding the default validators added to attributes
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
Labels: flaky-test

#27172 fix: address test failure by using the previous log
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
Labels: team/cloud-native

#26235 Allow LDAP provider to search using any attribute configured via mappers
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/admin/ApiUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPSearchForUsersPaginationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/noimport/LDAPSearchForUsersPaginationNoImportTest.java
Labels: team/cloud-native, flaky-test, team/core-iam

#27187 Implement overriding description from properties
  js/apps/account-ui/pom.xml
  js/apps/admin-ui/pom.xml
Labels: team/ui, flaky-test

#27200 Run Cypress tests in parallel using `cypress-split` (#20685)
  .github/workflows/js-ci.yml
  js/apps/admin-ui/cypress.config.mjs
  js/apps/admin-ui/package.json
  js/pnpm-lock.yaml
Labels: team/ui

#27199 Run Cypress tests in parallel using `cypress-split` (#20685)
  .github/workflows/js-ci.yml
  js/apps/admin-ui/cypress.config.mjs
  js/apps/admin-ui/package.json
  js/pnpm-lock.yaml
Labels: team/ui

#27208 fix: waiting more time for the log to appear
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
Labels: team/cloud-native

#27160 Expose display name and locales when user has ANY admin role
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/PermissionsTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#26318 Write announcement and documentation for Account Console v3
  common/src/main/java/org/keycloak/common/Profile.java
  docs/documentation/release_notes/images/new-account-console.png
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/securing_apps/topics/oidc/javascript-adapter.adoc
  docs/documentation/server_admin/images/account-console-applications.png
  docs/documentation/server_admin/images/account-console-device.png
  docs/documentation/server_admin/images/account-console-groups.png
  docs/documentation/server_admin/images/account-console-intro.png
  docs/documentation/server_admin/images/account-console-linked.png
  docs/documentation/server_admin/images/account-console-signing-in-webauthn-2factor.png
  docs/documentation/server_admin/images/account-console-signing-in-webauthn-passwordless.png
  docs/documentation/server_admin/images/account-console-signing-in.png
  docs/documentation/server_admin/images/groups_account_console.png
  docs/documentation/server_admin/topics/account.adoc
  docs/documentation/server_admin/topics/overview/features.adoc
  docs/documentation/server_admin/topics/realms/themes.adoc
  docs/documentation/server_admin/topics/threat/csrf.adoc
  docs/documentation/server_admin/topics/users/con-user-impersonation.adoc
  docs/documentation/server_development/topics/themes.adoc
  docs/documentation/tests/src/test/resources/ignored-links
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
Labels: team/ui, flaky-test

#27085 Remove the preview note from Keycloak's HA guide
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
  docs/guides/high-availability/bblocks-active-passive-sync.adoc
  docs/guides/high-availability/concepts-active-passive-sync.adoc
  docs/guides/high-availability/concepts-database-connections.adoc
  docs/guides/high-availability/concepts-infinispan-cli-batch.adoc
  docs/guides/high-availability/concepts-memory-and-cpu-sizing.adoc
  docs/guides/high-availability/concepts-threads.adoc
  docs/guides/high-availability/connect-keycloak-to-external-infinispan.adoc
  docs/guides/high-availability/deploy-aurora-multi-az.adoc
  docs/guides/high-availability/deploy-aws-route53-loadbalancer.adoc
  docs/guides/high-availability/deploy-infinispan-kubernetes-crossdc.adoc
  docs/guides/high-availability/deploy-keycloak-kubernetes.adoc
  docs/guides/high-availability/introduction.adoc
  docs/guides/high-availability/operate-failover.adoc
  docs/guides/high-availability/operate-network-partition-recovery.adoc
  docs/guides/high-availability/operate-switch-back.adoc
  docs/guides/high-availability/operate-switch-over.adoc
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FeaturesDistTest.java
Labels: status/hold, team/cloud-native, flaky-test

#27044 Cannot display 'Authentication Flows' screen when a realm contains mo…
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  model/legacy-private/src/main/java/org/keycloak/storage/ClientStorageManager.java
  model/map/src/main/java/org/keycloak/models/map/realm/MapRealmAdapter.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/AuthenticationMapper.java
  server-spi-private/src/test/java/org/keycloak/broker/provider/util/IdentityBrokerStateTestHelpers.java
  server-spi/src/main/java/org/keycloak/models/ClientModel.java
  server-spi/src/main/java/org/keycloak/models/RealmModel.java
  server-spi/src/main/java/org/keycloak/storage/client/ClientLookupProvider.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/HardcodedClientStorageProvider.java
Labels: team/cloud-native, team/ui, flaky-test

#26208 Permanently lock users out after X temporary lockouts during a brute …
  core/src/main/java/org/keycloak/representations/idm/RealmRepresentation.java
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/server_admin/topics/threat/brute-force.adoc
  js/apps/admin-ui/cypress/e2e/realm_settings_events_test.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_settings_tabs_test.spec.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/security-defences/BruteForceDetection.tsx
  js/libs/keycloak-admin-client/src/defs/realmRepresentation.ts
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedRealm.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/UserLoginFailureAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/LoginFailureEntity.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi-private/src/test/java/org/keycloak/broker/provider/util/IdentityBrokerStateTestHelpers.java
  server-spi/src/main/java/org/keycloak/models/RealmModel.java
  server-spi/src/main/java/org/keycloak/models/UserLoginFailureModel.java
  services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java
  services/src/main/java/org/keycloak/services/managers/RealmManager.java
  services/src/main/java/org/keycloak/services/resources/admin/AttackDetectionResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AttackDetectionResourceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#27176 Supporting OAuth 2.1 for public clients
  docs/documentation/securing_apps/topics/oidc/oauth21-support.adoc
  docs/documentation/server_admin/topics/clients/client-policies.adoc
  docs/documentation/server_admin/topics/threat/oauth21-compliance.adoc
  services/src/main/java/org/keycloak/services/clientpolicy/executor/DPoPBindEnforcerExecutor.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/DPoPBindEnforcerExecutorFactory.java
  services/src/main/resources/keycloak-default-client-profiles.json
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1PublicClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesLoadUpdateTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#26943 Allow setting an attribute as multivalued
  core/src/main/java/org/keycloak/representations/idm/UserProfileAttributeMetadata.java
  core/src/main/java/org/keycloak/representations/userprofile/config/UPAttribute.java
  docs/documentation/server_admin/topics/users/user-profile.adoc
  js/apps/account-ui/src/api/representations.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
  js/libs/keycloak-admin-client/src/defs/userProfileMetadata.ts
  js/libs/ui-shared/src/user-profile/MultiInputComponent.tsx
  js/libs/ui-shared/src/user-profile/UserProfileFields.tsx
  server-spi-private/src/main/java/org/keycloak/userprofile/UserProfileUtil.java
  server-spi/src/main/java/org/keycloak/userprofile/AttributeMetadata.java
  server-spi/src/main/java/org/keycloak/validate/ValidationResult.java
  server-spi/src/main/java/org/keycloak/validate/ValidatorConfig.java
  services/src/main/java/org/keycloak/email/freemarker/FreeMarkerEmailTemplateProvider.java
  services/src/main/java/org/keycloak/email/freemarker/beans/ProfileBean.java
  services/src/main/java/org/keycloak/forms/login/freemarker/model/AbstractUserProfileBean.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/validator/MultiValueValidator.java
  services/src/main/resources/META-INF/services/org.keycloak.validate.ValidatorFactory
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginUpdateProfilePage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateProfileWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcFirstBrokerLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/VerifyProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/validation/BuiltinValidatorsTest.java
  testsuite/integration-arquillian/tests/base/testsuites/forms-suite
  testsuite/integration-arquillian/tests/other/sssd/src/test/java/org/keycloak/testsuite/sssd/SSSDUserProfileTest.java
  themes/src/main/resources/theme/base/admin/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/resources/js/kcMultivalued.js
  themes/src/main/resources/theme/base/login/resources/js/kcNumberFormat.js
  themes/src/main/resources/theme/base/login/resources/js/kcNumberUnFormat.js
  themes/src/main/resources/theme/base/login/resources/js/userProfile.js
  themes/src/main/resources/theme/base/login/user-profile-commons.ftl
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#27235 Updating docs and account message
  docs/documentation/server_admin/images/user-profile-create-attribute.png
  docs/documentation/server_admin/topics/users/user-profile.adoc
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
Labels: team/ui

#27231 Upgrade to Quarkus 3.7.4
  pom.xml
Labels: flaky-test

#27206 Avoid regenerating the totpSecret on every reload of the OTP configuration page
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateTotp.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/forms/login/freemarker/model/TotpBean.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionTotpSetupTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27237 use the right context
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
Labels: team/ui

#27196 better default value
  js/apps/admin-ui/src/authentication/components/modals/AddSubFlowModal.tsx
Labels: team/ui

#27229 Only run Husky scripts when installed
  js/.husky/pre-commit
Labels: kind/task, team/ui

#27163 Set the selected locale to default realm locale when creating a user
  js/apps/admin-ui/src/user/CreateUser.tsx
Labels: team/ui

#27012 Add failedLoginNotBefore to AttackDetectionResource
  docs/documentation/release_notes/topics/24_0_0.adoc
  services/src/main/java/org/keycloak/services/resources/admin/AttackDetectionResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AttackDetectionResourceTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27134 Fix for Issue #26937
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_CN.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/client-scopes/ClientScopesSection.tsx
  services/src/main/java/org/keycloak/services/resources/admin/ClientScopeResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/ClientScopeTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#27236 Document using AWS JDBC Wrapper in HA guide
  docs/guides/high-availability/deploy-aurora-multi-az.adoc
  docs/guides/high-availability/deploy-keycloak-kubernetes.adoc
  docs/guides/high-availability/examples/generated/keycloak-ispn.yaml
  docs/guides/high-availability/examples/generated/keycloak.yaml
  docs/guides/server/db.adoc
Labels: team/cloud-native

#27136 Tests for applications page
  js/apps/account-ui/playwright.config.ts
  js/apps/account-ui/src/applications/Applications.tsx
  js/apps/account-ui/test/applications.spec.ts
  js/apps/account-ui/test/auth.setup.ts
  js/apps/account-ui/test/my-resources.spec.ts
Labels: team/ui

#27288 Upgrade to Infinispan 14.0.25
  pom.xml
Labels: flaky-test

#27299 Add tests for linked accounts
  js/apps/account-ui/src/account-security/AccountRow.tsx
  js/apps/account-ui/test/account-security/linked-accounts.spec.ts
  js/apps/account-ui/test/admin-client.ts
  js/apps/account-ui/test/personal-info/personal-info.spec.ts
  js/apps/account-ui/test/realms/groups-idp.json
  js/apps/account-ui/test/realms/groups-realm.json
Labels: team/ui

#27286 Perform internal introspect for the access token in the account app
  services/src/main/java/org/keycloak/protocol/oidc/AccessTokenIntrospectionProvider.java
  services/src/main/java/org/keycloak/services/resources/account/AccountLoader.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceLightweightTokenTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#26971 reset form when provider / mapperPype changes
  js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx
Labels: team/ui

#27295 Allow setting if both 'client_id' and 'id_token_hint' params should be sent in logout requests
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx
  js/apps/admin-ui/src/identity-providers/add/ExtendedNonDiscoverySettings.tsx
  js/apps/admin-ui/src/identity-providers/component/SwitchField.tsx
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProviderConfig.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerLogoutTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#27305 Downgrade aws-advanced-jdbc-wrapper to v2.3.1
  pom.xml
Labels: flaky-test

#27088 changed to use ui-shared
  js/apps/admin-ui/src/events/AdminEvents.tsx
Labels: team/ui

#27232 Record Cypress test failures in video
  .github/workflows/js-ci.yml
  js/apps/admin-ui/cypress.config.js
Labels: kind/task, team/ui

#26942 Set expiry and maxidle when loading entries from the remote store
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionsLoader.java
Labels: flaky-test

#27227 Added documentation for bug triage process
  docs/bug-triage-prioritize.svg
  docs/bug-triage-verify.svg
  docs/bug-triage.md
Labels: status/hold

#27292 Add option to clients to use lightweight access token
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractOIDCProtocolMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ClientManager.java
Labels: priority/important, team/cloud-native, team/ui, team/core-clients, team/core-iam

#27312 Re-index CLIENT_ATTRIBUTES using name and value
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-24.0.0.xml
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/migration-test/migration-realm-19.0.3.json
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#27328 Harmonize behaviour of different CertificateUtilsProvider implementations
  crypto/elytron/src/main/java/org/keycloak/crypto/elytron/ElytronCertificateUtilsProvider.java
  crypto/elytron/src/main/java/org/keycloak/crypto/elytron/WildFlyElytronProvider.java
  crypto/elytron/src/test/java/org/keycloak/crypto/elytron/test/CRLDistributionPointTest.java
Labels: flaky-test
