Repository keycloak/keycloak, pull requests merged in 2024-01, with the labels that each got.

#25683 added permission checking to ui-ext realm resource
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AdminExtResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UIRealmsResource.java
Labels: team/ui, flaky-test

#25619 Fix 'What is the function of default groups?' popover
  js/apps/admin-ui/src/realm-settings/DefaultGroupsTab.tsx
Labels: team/ui

#25848 Do not show sign-out action for offline sessions (#25577)
  js/apps/admin-ui/cypress/e2e/sessions_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/components/TablePage.ts
  js/apps/admin-ui/cypress/support/util/AdminClient.ts
  js/apps/admin-ui/src/sessions/SessionsTable.tsx
Labels: team/ui

#25850 Update SessionsTable.tsx
  js/apps/admin-ui/src/sessions/SessionsTable.tsx
Labels: team/ui

#25854 Revert "Bump actions/download-artifact from 3 to 4"
  .github/actions/archive-surefire-reports/action.yml
  .github/actions/build-keycloak/action.yml
  .github/actions/integration-test-setup/action.yml
  .github/actions/upload-flaky-tests/action.yml
  .github/actions/upload-heapdumps/action.yml
  .github/workflows/documentation.yml
  .github/workflows/js-ci.yml
  .github/workflows/operator-ci.yml
Labels: flaky-test

#25599 Update message keys for Realm Events Setting UI help text
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_lt.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_no.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_pl.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_pt_BR.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_ru.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_zh_CN.properties
Labels: team/ui

#25630 Fixed translations
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#25697 [Admin UI] Allow DynamicComponents on OIDC and SAML IDP
  js/apps/admin-ui/src/identity-providers/add/DetailSettings.tsx
Labels: team/ui

#25869 Map Store Removal: Remove protostream dependency
  distribution/api-docs-dist/pom.xml
  pom.xml
Labels: flaky-test

#24811 enhance: allow for versioned features
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/main/java/org/keycloak/common/profile/CommaSeparatedListProfileConfigResolver.java
  common/src/main/java/org/keycloak/common/profile/ProfileConfigResolver.java
  common/src/main/java/org/keycloak/common/profile/PropertiesFileProfileConfigResolver.java
  common/src/main/java/org/keycloak/common/profile/PropertiesProfileConfigResolver.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  docs/guides/server/features.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/FeatureOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/Option.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Environment.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/QuarkusProfileConfigResolver.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/PropertyMapperParameterConsumer.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractStartCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Build.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PropertyMappingInterceptor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/FeaturePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/FeaturePropertyMappersTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FeaturesDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FipsDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25420 Upgrade Welcome theme to PatternFly 5
  operator/src/test/java/org/keycloak/operator/testsuite/integration/ClusteringTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HostnameDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ProxyDistTest.java
  services/src/main/java/org/keycloak/services/resources/WelcomeResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/theme/ThemeResourceProviderTest.java
  themes/src/main/resources/theme/keycloak/welcome/index.ftl
  themes/src/main/resources/theme/keycloak/welcome/resources/admin-console.png
  themes/src/main/resources/theme/keycloak/welcome/resources/alert.png
  themes/src/main/resources/theme/keycloak/welcome/resources/background.svg
  themes/src/main/resources/theme/keycloak/welcome/resources/bg.png
  themes/src/main/resources/theme/keycloak/welcome/resources/bug.png
  themes/src/main/resources/theme/keycloak/welcome/resources/css/welcome.css
  themes/src/main/resources/theme/keycloak/welcome/resources/keycloak-project.png
  themes/src/main/resources/theme/keycloak/welcome/resources/keycloak_logo.png
  themes/src/main/resources/theme/keycloak/welcome/resources/logo.png
  themes/src/main/resources/theme/keycloak/welcome/resources/logo.svg
  themes/src/main/resources/theme/keycloak/welcome/resources/mail.png
  themes/src/main/resources/theme/keycloak/welcome/resources/user.png
  themes/src/main/resources/theme/keycloak/welcome/theme.properties
Labels: team/cloud-native, team/store, team/core, team/ui, area/welcome/ui

#25877 Fix links in Catalan HTML email templates
  themes/src/main/resources-community/theme/base/email/messages/messages_ca.properties
Labels: flaky-test

#24299 Implement Authentication Method Reference (AMR) claim from OIDC speci…
  core/src/main/java/org/keycloak/OAuth2Constants.java
  docs/documentation/server_admin/images/config-authenticator-reference.png
  docs/documentation/server_admin/topics/authentication/flows.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/authentication/components/ExecutionConfigModal.tsx
  js/apps/admin-ui/src/authentication/components/FlowRow.tsx
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  services/src/main/java/org/keycloak/authentication/DefaultAuthenticationFlow.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/CookieAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/util/AuthenticatorUtils.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AmrProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/AmrUtils.java
  services/src/main/resources/META-INF/services/org.keycloak.protocol.ProtocolMapper
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AuthenticationMethodReferenceTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#25859 In UserProfileContext.IDP_REVIEW, NPE on UserModel#getEmail because UserModelDelegate#delegate is null
  services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpReviewProfileAuthenticator.java
Labels: flaky-test

#25284 Add missing Spanish translations for keycloak.v2 admin theme
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_es.properties
Labels: team/ui

#25860 Make sure the context path from the base URI is respected when building TOTP URIs
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
Labels: flaky-test

#25613 added scroll bars to modal
  js/apps/admin-ui/src/realm-settings/keys/key-providers/KeyProviderModal.tsx
  js/apps/admin-ui/src/realm-settings/keys/key-providers/key-provider-modal.module.css
  js/apps/admin-ui/src/realm-settings/realm-settings-section.css
Labels: team/ui

#25901 Fixing the registration_client_uri to point to a valid URI after updating a client
  services/src/main/java/org/keycloak/services/Urls.java
  services/src/main/java/org/keycloak/services/clientregistration/oidc/OIDCClientRegistrationProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OIDCClientRegistrationTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25711 Do not allow verifying email from a different account
  docs/documentation/release_notes/topics/24_0_0.adoc
  server-spi-private/src/main/java/org/keycloak/events/Errors.java
  services/src/main/java/org/keycloak/authentication/actiontoken/idpverifyemail/IdpVerifyAccountLinkActionTokenHandler.java
  services/src/main/java/org/keycloak/authentication/actiontoken/verifyemail/VerifyEmailActionTokenHandler.java
  services/src/main/java/org/keycloak/services/messages/Messages.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsServiceChecks.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionEmailVerificationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractFirstBrokerLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageTest.java
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/cloud-native, team/store, team/core, flaky-test

#25876 fix: do not split on space for option errors
  docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ShortErrorMessageHandler.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/OptionValidationTest.java
Labels: team/cloud-native, flaky-test

#25836 Fix for empty realm name issue during api update
  model/legacy-private/src/main/java/org/keycloak/storage/datastore/LegacyExportImportManager.java
  services/src/main/java/org/keycloak/services/managers/RealmManager.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmsAdminResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25921 Add logging to the policy providers for general debugging purposes
  authz/policy/common/pom.xml
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/aggregated/AggregatePolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/client/ClientPolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/clientscope/ClientScopePolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/group/GroupPolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/js/JSPolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/js/JSPolicyProviderFactory.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/permission/AbstractPermissionProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/permission/ResourcePolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/permission/ScopePolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/permission/UMAPolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/regex/RegexPolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/time/TimePolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/user/UserPolicyProvider.java
  server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/DefaultEvaluation.java
  server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/Evaluation.java
Labels: flaky-test

#25952 Do not switch to admin console too early
  js/apps/admin-ui/cypress/e2e/masthead_test.spec.ts
Labels: team/ui

#25902 Using a valid URI when deleting cookies before/after running tests
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/drone/KeycloakDronePostSetup.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25905 Update web element of the LinkedIn login page
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social/LinkedInLoginPage.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25828 Revised many parts of the account console that were not correctly translated into Chinese.
  themes/src/main/resources-community/theme/base/account/messages/messages_zh_CN.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_zh_CN.properties
  themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_zh_CN.properties
Labels: flaky-test

#25895 Add release announcement and migration for new welcome theme
  docs/documentation/release_notes/images/new-welcome-screen.png
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
Labels: area/docs, team/ui, area/welcome/ui

#25532 Localization tabs
  js/apps/admin-ui/cypress/e2e/realm_settings_events_test.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_settings_tabs_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/LocalizationTab.tsx
  js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
  js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx
  js/apps/admin-ui/src/realm-settings/localization/LocalizationTab.tsx
  js/apps/admin-ui/src/realm-settings/localization/RealmOverrides.tsx
  js/apps/admin-ui/src/util.ts
  js/libs/keycloak-admin-client/src/defs/effectiveMessageBundleRepresentation.ts
  js/libs/keycloak-admin-client/src/resources/serverInfo.ts
  services/src/main/java/org/keycloak/services/resources/ThemeResource.java
Labels: team/ui, flaky-test

#24627 PermissionTicketService: Check if UMA is enabled on resource, if not reject the request.
  services/src/main/java/org/keycloak/authorization/protection/permission/PermissionTicketService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UserManagedAccessTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25957 Add German translations for account console v3
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_de.properties
Labels: area/translations, team/ui

#25806 fix: providing an error description
  services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientAttributeCertificateResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ComponentResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RoleContainerResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/error/UncaughtErrorPageTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25955 fix: do not split on space for option errors
  docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ShortErrorMessageHandler.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/OptionValidationTest.java
Labels: team/cloud-native

#25938 Making metrics with labels for embedded Infinispan the default
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  quarkus/runtime/src/main/resources/cache-ispn.xml
  quarkus/runtime/src/main/resources/cache-local.xml
Labels: team/cloud-native, flaky-test

#25611 removed use of ui-ext in library
  js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
  js/libs/keycloak-admin-client/src/resources/realms.ts
Labels: team/ui

#25995 Escape action in the form_post.jwt and only decode path in RedirectUtils
  common/src/main/java/org/keycloak/common/util/HttpPostRedirect.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/OIDCRedirectUriBuilder.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/RedirectUtils.java
  services/src/test/java/org/keycloak/protocol/oidc/utils/RedirectUtilsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AuthorizationCodeTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25963 Update cs+sk login messages - fixes #25962
  themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_sk.properties
Labels: flaky-test

#25982 Add the build step to the overall status check
  .github/workflows/ci.yml
  .github/workflows/js-ci.yml
  .github/workflows/operator-ci.yml
Labels: flaky-test

#25716 Enhancing Lightweight access token M2
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractOIDCProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AllowedWebOriginsProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AudienceResolveProtocolMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/OIDCAttributeMapperHelper.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/UseLightweightAccessTokenExecutor.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/UseLightweightAccessTokenExecutorFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.services.clientpolicy.executor.ClientPolicyExecutorProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#25845 added permission checking to ui-ext realm resource so realm names are…
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AdminExtResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/RealmResource.java
Labels: team/ui, flaky-test

#25623 fixed label on resource
  js/apps/admin-ui/src/clients/authorization/PermissionDetails.tsx
Labels: team/ui

#25608 remove userProfileMetadata from user
  js/apps/admin-ui/src/user/EditUser.tsx
Labels: team/ui

#25910 Could not format default value for log formats
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
Labels: team/cloud-native, flaky-test

#25664 change text based on the context
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
  js/apps/admin-ui/src/components/dynamic/MapComponent.tsx
  js/apps/admin-ui/src/components/key-value-form/KeyValueInput.tsx
  js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesGroupForm.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeAnnotations.tsx
Labels: team/ui

#25672 fixed message for disabling clients
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/ClientDetails.tsx
Labels: team/ui

#26030 Bugfix for: Removing all group attributes no longer works with keycloak-admin-client (java)
  core/src/main/java/org/keycloak/representations/idm/GroupRepresentation.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25422 enable dot in attribute when user profile enabled
  js/apps/admin-ui/src/user/form-state.ts
  js/apps/admin-ui/src/util.ts
  js/libs/ui-shared/src/user-profile/utils.ts
Labels: team/ui

#25662 Update web elements of the Instagram login page
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social/InstagramLoginPage.java
Labels: team/cloud-native, team/store, team/core, flaky-test, backport/22.0

#25663 Update web elements of the Instagram login page
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social/InstagramLoginPage.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#26050 Clarify note about containers
  docs/guides/server/containers.adoc
Labels: team/cloud-native

#26037 Add landmark element for loading state for consoles
  js/apps/account-ui/index.html
  js/apps/admin-ui/index.html
Labels: team/ui

#25709 Remove concurrent loading of remote sessions as at startup time only one node is up anyway
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  model/infinispan/pom.xml
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/BaseCacheInitializer.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/InfinispanCacheInitializer.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/SessionInitializerWorker.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionsLoader.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionsLoaderContext.java
  model/infinispan/src/test/java/org/keycloak/cluster/infinispan/JDGPutTest.java
  model/infinispan/src/test/java/org/keycloak/cluster/infinispan/RemoteCacheSessionsLoaderTest.java
  model/infinispan/src/test/java/org/keycloak/models/sessions/infinispan/initializer/InitializerStateTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/OfflineSessionPersistenceTest.java
Labels: team/store, flaky-test

#25992 Added welcome tab to admin-ui
  js/apps/admin-ui/cypress/e2e/masthead_test.spec.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/PageHeader.tsx
  js/apps/admin-ui/src/dashboard/Dashboard.tsx
  js/apps/admin-ui/src/dashboard/dashboard.css
  js/apps/admin-ui/src/dashboard/routes/Dashboard.tsx
  js/apps/admin-ui/src/help-urls.ts
Labels: team/ui

#25948 On invalid submission, IdpUsernamePasswordForm sends back the user to the standard UsernamePasswordForm template
  services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpUsernamePasswordForm.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractFirstBrokerLoginTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#25959 doc: adding notes about header priority
  docs/guides/migration/migrating-to-quarkus.adoc
  docs/guides/server/reverseproxy.adoc
Labels: team/cloud-native

#25744 use content json also for own menu
  js/apps/account-ui/public/content.json
  js/apps/account-ui/src/content/ContentComponent.tsx
  js/apps/account-ui/src/content/ContentRenderer.tsx
  js/apps/account-ui/src/content/content.ts
  js/apps/account-ui/src/content/fetchContent.ts
  js/apps/account-ui/src/environment.ts
  js/apps/account-ui/src/root/PageNav.tsx
Labels: team/ui

#25988 Add progressbar role
  themes/src/main/resources/theme/keycloak.v2/account/index.ftl
Labels: team/ui, flaky-test

#26018 more missing translations
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_ca.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_cs.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_da.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_el.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_es.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_fi.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_hu.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_it.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_ja.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_lt.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_lv.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_no.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_pt_BR.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_sk.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_sv.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_th.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_zh_CN.properties
Labels: team/ui

#26024 remove default so it can be empty
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx
Labels: team/ui

#25775 Avoid returning duplicated users in LDAP and unsynced
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPProvidersIntegrationTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#26070 Add federated identity ProviderEvent(s)
  model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java
  server-spi/src/main/java/org/keycloak/models/FederatedIdentityModel.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/FederatedIdentityModelTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/LegacyJpa.java
Labels: team/store, flaky-test

#26045 Fix OfflineServletAdapterTest failures, and improve logging
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/adapter/page/AbstractShowTokensPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/adapter/page/LogScreenContents.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/AbstractServletsAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/DemoServletsAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/OIDCPublicKeyRotationAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/OfflineServletsAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/offline-client/WEB-INF/web.xml
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/secure-portal/WEB-INF/web.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#25958 Add tests to Cypress in admin console UI
  js/apps/admin-ui/cypress/e2e/client_scopes_test.spec.ts
  js/apps/admin-ui/cypress/e2e/clients_test.spec.ts
  js/apps/admin-ui/cypress/e2e/masthead_test.spec.ts
  js/apps/admin-ui/cypress/e2e/users_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/AttributesTab.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/client_scopes/CreateClientScopePage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/user_details/UserDetailsPage.ts
Labels: team/ui

#24442 Add a toggle to use context attributes on the regex policy provider
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/regex/RegexPolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/regex/RegexPolicyProviderFactory.java
  core/src/main/java/org/keycloak/representations/idm/authorization/RegexPolicyRepresentation.java
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/authorization/policy/Regex.tsx
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/RegexPolicyTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#25983 Ensure OIDC prompt=login gets correctly mapped to SAML ForceAuthN during identity brokering
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlForceAuthnBrokerTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#26114 Container warning 26006 backport to 23
  docs/guides/server/containers.adoc
Labels: team/cloud-native

#26022 Fix mvn clean of js/ directory
  js/pom.xml
Labels: team/ui, flaky-test

#25996 Use proper attribute name in UI
  js/apps/admin-ui/src/realm-settings/TokensTab.tsx
Labels: team/ui

#24163 Avoid usage of primitive wrapper constructors in server-spi-private
  server-spi-private/src/main/java/org/keycloak/validate/validators/DoubleValidator.java
  server-spi-private/src/main/java/org/keycloak/validate/validators/IntegerValidator.java
  server-spi/src/main/java/org/keycloak/validate/ValidatorConfig.java
Labels: flaky-test

#26078 Remove unnecessary tooltip on device activity page
  js/apps/account-ui/src/account-security/DeviceActivity.tsx
Labels: team/ui

#26044 Fix OfflineServletAdapterTest failures, and improve logging
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/adapter/page/AbstractShowTokensPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/adapter/page/LogScreenContents.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/AbstractServletsAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/DemoServletsAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/OIDCPublicKeyRotationAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/OfflineServletsAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/offline-client/WEB-INF/web.xml
  testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/secure-portal/WEB-INF/web.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#26120 Use proper attribute name in UI
  js/apps/admin-ui/src/realm-settings/TokensTab.tsx
Labels: team/ui

#26125 Fixed a11y violations
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/authorization/policy/Client.tsx
  js/apps/admin-ui/src/components/alert/AlertPanel.tsx
  js/apps/admin-ui/src/components/key-value-form/ValueSelect.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeValidations.tsx
  js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx
Labels: team/ui

#25852 Promote Account Console v3 to default and deprecate v2
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
  js/apps/account-ui/index.html
  js/apps/account-ui/pom.xml
  js/apps/account-ui/src/root/Root.tsx
  js/apps/admin-ui/cypress/support/pages/admin-ui/Masthead.ts
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FeaturesDistTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ServerInfoTest.java
  testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/account/AbstractWebAuthnAccountTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#26133 Support OR condition for forms + authz (#24879)
  js/apps/admin-ui/cypress/e2e/client_authorization_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/ListingPage.ts
  js/apps/admin-ui/cypress/support/util/AdminClient.ts
  js/apps/admin-ui/src/ForbiddenSection.tsx
  js/apps/admin-ui/src/clients/ClientDetails.tsx
  js/apps/admin-ui/src/clients/authorization/DecisionStrategySelect.tsx
  js/apps/admin-ui/src/clients/authorization/PermissionDetails.tsx
  js/apps/admin-ui/src/clients/authorization/Permissions.tsx
  js/apps/admin-ui/src/clients/authorization/Policies.tsx
  js/apps/admin-ui/src/clients/authorization/ResourceDetails.tsx
  js/apps/admin-ui/src/clients/authorization/Resources.tsx
  js/apps/admin-ui/src/clients/authorization/ScopeDetails.tsx
  js/apps/admin-ui/src/clients/authorization/Scopes.tsx
  js/apps/admin-ui/src/clients/authorization/Settings.tsx
  js/apps/admin-ui/src/clients/routes/AuthenticationTab.tsx
  js/apps/admin-ui/src/clients/routes/NewPermission.tsx
  js/apps/admin-ui/src/clients/routes/NewPolicy.tsx
  js/apps/admin-ui/src/clients/routes/NewResource.tsx
  js/apps/admin-ui/src/clients/routes/NewScope.tsx
  js/apps/admin-ui/src/clients/routes/PermissionDetails.tsx
  js/apps/admin-ui/src/clients/routes/PolicyDetails.tsx
  js/apps/admin-ui/src/clients/routes/Resource.tsx
  js/apps/admin-ui/src/clients/routes/Scope.tsx
  js/apps/admin-ui/src/components/form/FormAccess.tsx
  js/apps/admin-ui/src/components/key-value-form/KeyValueInput.tsx
  js/apps/admin-ui/src/components/list-empty-state/ListEmptyState.tsx
  js/apps/admin-ui/src/context/access/Access.tsx
  js/libs/keycloak-admin-client/src/defs/whoAmIRepresentation.ts
Labels: team/ui

#23303 Use email verification instead of executing action for `send-verify-email` endpoint
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/UserResource.java
  services/src/main/java/org/keycloak/authentication/actiontoken/verifyemail/VerifyEmailActionToken.java
  services/src/main/java/org/keycloak/authentication/actiontoken/verifyemail/VerifyEmailActionTokenHandler.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
Labels: team/core, flaky-test

#26136 Remove `lodash` as a hard dependency from the Admin Client
  js/libs/keycloak-admin-client/package.json
  js/libs/keycloak-admin-client/src/resources/agent.ts
  js/pnpm-lock.yaml
Labels: team/ui

#25730 refactored authentication to use the ui-shared
  js/apps/account-ui/src/resources/EditTheResource.tsx
  js/apps/account-ui/src/resources/ShareTheResource.tsx
  js/apps/admin-ui/cypress/support/forms/Select.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/authentication/BindFlowModal.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/authentication/CIBAPolicyPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/authentication/DuplicateFlowModal.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/authentication/FlowDetail.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/authentication/OTPPolicies.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/authentication/WebAuthnPolicies.ts
  js/apps/admin-ui/src/authentication/BindFlowDialog.tsx
  js/apps/admin-ui/src/authentication/components/EditFlow.tsx
  js/apps/admin-ui/src/authentication/components/ExecutionConfigModal.tsx
  js/apps/admin-ui/src/authentication/components/modals/AddSubFlowModal.tsx
  js/apps/admin-ui/src/authentication/form/CreateFlow.tsx
  js/apps/admin-ui/src/authentication/form/FlowType.tsx
  js/apps/admin-ui/src/authentication/form/NameDescription.tsx
  js/apps/admin-ui/src/authentication/policies/CibaPolicy.tsx
  js/apps/admin-ui/src/authentication/policies/OtpPolicy.tsx
  js/apps/admin-ui/src/authentication/policies/WebauthnPolicy.tsx
  js/apps/admin-ui/src/components/time-selector/TimeSelectorControl.tsx
  js/libs/ui-shared/src/controls/NumberControl.tsx
  js/libs/ui-shared/src/controls/SelectControl.tsx
  js/libs/ui-shared/src/main.ts
Labels: team/ui

#26157 fixed critical a11y violation
  js/apps/admin-ui/src/clients/registration/DetailProvider.tsx
Labels: team/ui

#20366 Add X509 thumbprint to JWT when using private_key_jwt
  core/src/main/java/org/keycloak/jose/jws/JWSBuilder.java
  js/apps/admin-ui/cypress/e2e/identity_providers_oidc_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx
  services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
  services/src/main/java/org/keycloak/broker/oidc/OAuth2IdentityProviderConfig.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerPrivateKeyJwtWithX509HeadersTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#26142 account.v3 allow adding scripts like in v2
  js/apps/account-ui/pom.xml
Labels: team/ui, flaky-test

#26097 fix: thread dump for raw containers not working as expected
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FipsDistTest.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/KeycloakDistributionDecorator.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/DockerKeycloakDistribution.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/KeycloakDistribution.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
Labels: team/cloud-native, flaky-test

#26093 Do not use raw parameterized PropertyMapper
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/FeatureOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/HostnameOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/LoggingOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/MetricsOptions.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/ConfigArgsConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/Configuration.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KcEnvConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakPropertiesConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/CachingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ClassLoaderPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ConfigKeystorePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/FeaturePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HealthPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnamePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/MetricsPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ProxyPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/SecurityPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TransactionPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TruststorePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/VaultPropertyMappers.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
Labels: team/cloud-native, flaky-test

#26138 Sanitize logs in JBossLoggingEventListenerProvider
  server-spi/src/main/java/org/keycloak/utils/StringUtil.java
  server-spi/src/test/java/org/keycloak/utils/StringUtilTest.java
  services/src/main/java/org/keycloak/events/log/JBossLoggingEventListenerProvider.java
  services/src/main/java/org/keycloak/events/log/JBossLoggingEventListenerProviderFactory.java
Labels: flaky-test

#26174 Add `@Deprecated` annotation to deprecated profiles
  common/src/main/java/org/keycloak/common/Profile.java
Labels: kind/task

#26137 Changing to the Infinispan BOM to avoid mis-aligned Infinispan dependencies
  adapters/saml/wildfly-elytron-jakarta/pom.xml
  adapters/saml/wildfly-elytron/pom.xml
  model/infinispan/pom.xml
  pom.xml
  quarkus/config-api/pom.xml
  quarkus/pom.xml
  quarkus/runtime/pom.xml
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#26123 Update dependencies to enable Maven also-make working for Quarkus
  docs/maven-plugin/pom.xml
  quarkus/dist/pom.xml
Labels: team/cloud-native, flaky-test

#26126 Integrate registration with terms and conditions required action
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  services/src/main/java/org/keycloak/authentication/forms/RegistrationUserCreation.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
Labels: team/cloud-native, team/store, team/core, team/ui

#26199 Comprehensive log for the LoggingDistTest and Quarkus IT
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java
Labels: team/cloud-native

#26166 fix non-POSIX usage of expr in kc.sh
  quarkus/dist/src/main/content/bin/kc.sh
Labels: team/cloud-native, flaky-test

#25918 fix: provide better error messages for list options
  quarkus/config-api/src/main/java/org/keycloak/config/DatabaseOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/FeatureOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/LoggingOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/MultiOption.java
  quarkus/config-api/src/main/java/org/keycloak/config/Option.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionBuilder.java
  quarkus/config-api/src/main/java/org/keycloak/config/SecurityOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/TruststoreOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/PropertyMapperParameterConsumer.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/FeaturePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/FeaturePropertyMappersTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/OptionValidationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java
  quarkus/tests/junit5/src/main/java/org/keycloak/Keycloak.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/CLITestExtension.java
Labels: team/cloud-native, flaky-test

#26160 Deprecating the offline session preloading
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/server_admin/topics/sessions/preloading.adoc
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProviderFactory.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  server-spi/src/main/java/org/keycloak/models/UserSessionProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
  testsuite/model/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#26053 fixes navigation when searching for groups
  js/apps/admin-ui/src/groups/components/GroupTree.tsx
  js/apps/admin-ui/src/groups/routes/Groups.tsx
Labels: team/ui

#24346 Enhance error logs and error events during UserInfo endpoint and Toke…
  server-spi-private/src/main/java/org/keycloak/events/Errors.java
  server-spi-private/src/main/java/org/keycloak/protocol/oidc/TokenIntrospectionProvider.java
  services/src/main/java/org/keycloak/authorization/protection/introspect/RPTIntrospectionProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/AccessTokenIntrospectionProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenIntrospectionEndpoint.java
  services/src/main/java/org/keycloak/services/util/UserSessionUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ServiceAccountTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#26226 Fix broken assertion in Cypress tests (#25389)
  js/apps/admin-ui/cypress/e2e/user_fed_ldap_test.spec.ts
Labels: team/ui

#26169 Localization: Realm Overrides Fixes
  js/apps/admin-ui/cypress/e2e/realm_settings_tabs_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_pl.properties
  js/apps/admin-ui/src/realm-settings/LocalizationTab.tsx
  js/apps/admin-ui/src/realm-settings/localization/LocalizationTab.tsx
  js/apps/admin-ui/src/realm-settings/localization/RealmOverrides.tsx
Labels: team/ui

#26121 Use proper attribute name in UI
  js/apps/admin-ui/src/realm-settings/TokensTab.tsx
Labels: team/ui

#26065 added choose as an option to reset
  js/libs/ui-shared/src/user-profile/SelectComponent.tsx
Labels: team/ui

#26034 fix: permissions tab should be only shown with the correct rights
  js/apps/admin-ui/src/user/UsersSection.tsx
Labels: team/ui

#26195 Change test check to fix Firefox flaky failures
  js/apps/admin-ui/cypress/e2e/client_scopes_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/ListingPage.ts
Labels: team/ui

#26242 Do not use general debug log level for tests
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/BuildAndStartDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java
Labels: team/cloud-native

#26171 Make the option buildTime to match the quarkus configuration
  quarkus/config-api/src/main/java/org/keycloak/config/DatabaseOptions.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/OptionValidationTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.windows.approved.txt
Labels: team/cloud-native, flaky-test

#26265 Drop `base64-js` dependency from Keycloak JS
  js/libs/keycloak-js/package.json
  js/libs/keycloak-js/rollup.config.ts
  js/libs/keycloak-js/src/keycloak.js
  js/pnpm-lock.yaml
Labels: team/ui

#26221 Update norwegian translation of groups
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_no.properties
Labels: team/ui

#26003 fix: adds hostname:v1
  common/src/main/java/org/keycloak/common/Profile.java
  quarkus/config-api/src/main/java/org/keycloak/config/FeatureOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
  server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java
Labels: team/cloud-native, flaky-test

#26303 Remove deprecated mode for saml encryption
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractKcSamlEncryptedElementsTest.java
Labels: team/cloud-native, team/store, team/core

#25703 Encrypt network communication in JGroups
  docs/guides/server/caching.adoc
  docs/guides/server/configuration-production.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/CachingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
Labels: team/cloud-native, flaky-test

#26309 Make sure the component resolves to a UPConfig before cloning it
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
Labels: flaky-test

#26312 Assume test testEncryptedElementIsReadableInDep in FIPS mode
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractKcSamlEncryptedElementsTest.java
Labels: team/cloud-native, team/store, team/core

#26313 Assume test testEncryptedElementIsReadableInDep in FIPS mode
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractKcSamlEncryptedElementsTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#26272 Move community resources to separate directory
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ar.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ca.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_cs.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_da.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_de.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_el.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_es.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_fa.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_fi.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_fr.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_hu.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_it.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ja.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_lt.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_lv.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_nl.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_no.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_pl.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_pt_BR.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ru.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_sk.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_sv.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_th.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_tr.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_zh_CN.properties
  js/apps/account-ui/pom.xml
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ca.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_lt.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_no.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_pl.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_pt_BR.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ru.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_CN.properties
  js/apps/admin-ui/pom.xml
Labels: team/ui, flaky-test

#26238 remove client side validation
  js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
Labels: team/ui

#26239 better path resolve
  js/apps/account-ui/src/content/ContentComponent.tsx
Labels: team/ui

#26333 move suspense around lazy component
  js/apps/account-ui/src/content/ContentComponent.tsx
Labels: team/ui

#26302 Localization > Effective message bundles tab improvements
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/localization/EffectiveMessageBundles.tsx
  js/libs/keycloak-admin-client/src/resources/serverInfo.ts
Labels: team/ui

#26336 Fix broken flow binding dialog
  js/apps/admin-ui/src/authentication/BindFlowDialog.tsx
  js/libs/ui-shared/src/controls/SelectControl.tsx
Labels: team/ui

#26179 Invalidate authentication session on repeated OTP failures
  server-spi-private/src/main/java/org/keycloak/events/Errors.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/AbstractUsernameFormAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/OTPFormAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#24890 Parse default UserProfile configuration in the build time
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/UserProfileBuildItem.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakRecorder.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProviderFactory.java
Labels: team/cloud-native

#26326 Remove unused HttpResponse.setWriteCookiesOnTransactionComplete
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/QuarkusHttpResponse.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/QuarkusKeycloakContext.java
  server-spi/src/main/java/org/keycloak/http/HttpResponse.java
  services/src/main/java/org/keycloak/services/DefaultKeycloakContext.java
  services/src/main/java/org/keycloak/services/HttpResponseImpl.java
Labels: team/cloud-native, flaky-test

#26184 Invalidate authentication session on repeated Recovery Code failures
  services/src/main/java/org/keycloak/authentication/authenticators/browser/RecoveryAuthnCodesFormAuthenticator.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#26344 More a11y fixes
  js/apps/admin-ui/cypress/e2e/realm_settings_tabs_test.spec.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/authentication/BindFlowDialog.tsx
  js/apps/admin-ui/src/authentication/form/CreateFlow.tsx
  js/apps/admin-ui/src/clients/advanced/FineGrainOpenIdConnect.tsx
  js/apps/admin-ui/src/clients/authorization/AuthorizationEvaluate.tsx
  js/apps/admin-ui/src/clients/authorization/NewPolicyDialog.tsx
  js/apps/admin-ui/src/clients/authorization/ResourcesPolicySelect.tsx
  js/apps/admin-ui/src/clients/authorization/policy/Client.tsx
  js/apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx
  js/apps/admin-ui/src/realm-settings/EmailTab.tsx
  js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
  js/apps/admin-ui/src/realm-settings/PartialExport.tsx
  js/apps/admin-ui/src/realm-settings/PartialImport.tsx
  js/apps/admin-ui/src/realm-settings/ThemesTab.tsx
  js/apps/admin-ui/src/realm-settings/event-config/EventListenersForm.tsx
  js/apps/admin-ui/src/realm-settings/keys/KeysListTab.tsx
  js/apps/admin-ui/src/realm-settings/localization/RealmOverrides.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsSearching.tsx
  js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx
  js/apps/admin-ui/src/user-federation/shared/SettingsCache.tsx
  js/apps/admin-ui/src/user/user-credentials/InlineLabelEdit.tsx
Labels: team/ui

#26387 Fixed translation for search box in clients authorization policies tab
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/authorization/SearchDropdown.tsx
Labels: team/ui

#26384 Add missing translations for WebAuthN in Account Console
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
  js/apps/account-ui/public/locales/en/translation.json
  js/apps/account-ui/src/i18next.d.ts
  js/apps/admin-ui/src/i18next.d.ts
Labels: team/ui

#26386 25054 and 20125 make role mapping tab visible with view user permissions
  js/apps/admin-ui/src/user/EditUser.tsx
Labels: team/ui

#26391 Make role mapping tab visible with view user permissions (backport of #26386)
  js/apps/admin-ui/src/user/EditUser.tsx
Labels: team/ui

#23407 Testing Keycloak with nightly Quarkus releases
  .github/scripts/prepare-quarkus-next.sh
  .github/workflows/codeql-analysis.yml
  .github/workflows/documentation.yml
  .github/workflows/guides.yml
  .github/workflows/js-ci.yml
  .github/workflows/quarkus-next.yml
  testsuite/integration-arquillian/test-apps/spring-boot-adapter-app/pom.xml
Labels: team/cloud-native, team/store, team/core, flaky-test

#26395 Fixed a11y violations and typos in translations for messages in the dialog message for disabling clients.
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/authentication/components/DraggableTable.tsx
  js/apps/admin-ui/src/clients/keys/SamlKeysDialog.tsx
  js/apps/admin-ui/src/clients/scopes/GeneratedCodeTab.tsx
  js/apps/admin-ui/src/components/keycloak-spinner/KeycloakSpinner.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsConnection.tsx
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsGeneral.tsx
Labels: team/ui

#26015 Add the build step to the overall status check
  .github/workflows/ci.yml
  .github/workflows/js-ci.yml
  .github/workflows/operator-ci.yml
Labels: flaky-test

#26410 Ensure `key` prop of credentials list is unique
  js/apps/account-ui/src/account-security/SigningIn.tsx
Labels: team/ui

#26408 Fixed typo in disable modal
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#26412 Enable PKCE by default for Keycloak JS
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/securing_apps/topics/oidc/javascript-adapter.adoc
  js/apps/account-ui/src/main.tsx
  js/apps/admin-ui/src/keycloak.ts
  js/libs/keycloak-js/dist/keycloak.d.ts
  js/libs/keycloak-js/src/keycloak.js
  themes/src/main/resources/theme/keycloak.v2/account/index.ftl
Labels: team/ui, flaky-test

#26381 Fix issue with access tokens claims not being imported using OIDC IDPAttribute Mappers (#21627)
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts
  js/apps/admin-ui/public/locales/en/identity-providers-help.json
  js/apps/admin-ui/public/locales/en/identity-providers.json
  js/apps/admin-ui/src/identity-providers/add/AdvancedSettings.tsx
  services/src/main/java/org/keycloak/broker/oidc/KeycloakOIDCIdentityProvider.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProviderConfig.java
  services/src/main/java/org/keycloak/social/google/GoogleIdentityProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcAccessTokenOnlyClaimsUserAttributeMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/OidcAccessTokenOnlyClaimsUserAttributeMapperTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#26421 Add missing translations for WebAuthN Passwordless in Account Console
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
Labels: team/ui

#26099 fix: auto-build not needed for build
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
Labels: team/cloud-native, flaky-test

#26424 Fixed dropdown form in clients authorization policies tab
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/authorization/Permissions.tsx
  js/apps/admin-ui/src/clients/authorization/Policies.tsx
  js/apps/admin-ui/src/clients/authorization/Resources.tsx
  js/apps/admin-ui/src/clients/authorization/SearchDropdown.tsx
Labels: team/ui

#26230 fix: check actual subgroup rights when clicking a subgroup
  js/apps/admin-ui/src/groups/components/GroupTree.tsx
Labels: team/ui

#21509 CVE-2022-1471- SnakeYaml remote code execution by sending malicious YAML content
  pom.xml
Labels: team/cloud-native, flaky-test

#26261 Remove Jetty 9.4 adapters
  distribution/adapters/jetty94-adapter-zip/assembly.xml
  distribution/adapters/jetty94-adapter-zip/keycloak.mod
  distribution/adapters/jetty94-adapter-zip/pom.xml
  distribution/adapters/pom.xml
  distribution/downloads/src/main/resources/files
  distribution/saml-adapters/jetty94-adapter-zip/assembly.xml
  distribution/saml-adapters/jetty94-adapter-zip/keycloak.mod
  distribution/saml-adapters/jetty94-adapter-zip/pom.xml
  distribution/saml-adapters/pom.xml
  docs/documentation/release_notes/topics/24_0_0.adoc
  docs/documentation/securing_apps/topics/oidc/java/java-adapters.adoc
  docs/documentation/securing_apps/topics/oidc/java/jetty9-adapter.adoc
  docs/documentation/securing_apps/topics/oidc/java/spring-boot-adapter.adoc
  docs/documentation/securing_apps/topics/overview/getting-started.adoc
  docs/documentation/securing_apps/topics/saml/java/java-adapters.adoc
  docs/documentation/securing_apps/topics/saml/java/jetty-adapter.adoc
  docs/documentation/securing_apps/topics/saml/java/jetty-adapter/jetty9_installation.adoc
  docs/documentation/securing_apps/topics/saml/java/jetty-adapter/jetty9_per_war_config.adoc
  docs/documentation/server_admin/topics/overview/features.adoc
  docs/documentation/upgrading/topics/keycloak/changes.adoc
  pom.xml
Labels: flaky-test

#26445 added data-testid to expandable nav
  js/apps/account-ui/src/root/PageNav.tsx
Labels: team/ui

#26419 Add verify email required action for IdP email verification
  services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpEmailVerificationAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractFirstBrokerLoginTest.java
Labels: team/cloud-native, team/store, team/core

#26389 Added Client Type feature flag to begin client type work
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
  js/apps/admin-ui/src/context/server-info/__tests__/mock.json
  js/apps/admin-ui/src/utils/useIsFeatureEnabled.ts
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
Labels: area/core, team/cloud-native, team/core, team/ui, flaky-test

#26444 Remove code that expires old cookie paths
  services/src/main/java/org/keycloak/forms/login/freemarker/DetachedInfoStateChecker.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationSessionManager.java
  services/src/main/java/org/keycloak/services/util/CookieHelper.java
  services/src/test/java/org/keycloak/utils/CookieHelperTest.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/client/KeycloakTestingClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cookies/CookieHelperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cookies/CookiesPathTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#26453 Fixed selected row persisting on 'Cancel' during translation deletion
  js/apps/admin-ui/src/realm-settings/localization/RealmOverrides.tsx
Labels: team/ui

#25776 Fix hardcoded conditional rendering of client secret input field
  js/apps/admin-ui/src/clients/credentials/Credentials.tsx
  js/libs/keycloak-admin-client/src/defs/authenticatorConfigRepresentation.ts
  services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/ProvidersTest.java
Labels: team/cloud-native, team/store, team/core, team/ui, flaky-test

#26428 Fix `createdAt` format in Operator CSV
  operator/scripts/create-olm-bundle.sh
Labels: team/cloud-native

#26401 Stabilizing the FipsDistTest
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
Labels: team/cloud-native, flaky-test

#25949 Change password hashing defaults to match OWASP recommendations (#16629)
  docs/documentation/server_admin/topics/threat/password-db-compromised.adoc
  docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc
  server-spi-private/src/main/java/org/keycloak/credential/hash/Pbkdf2PasswordHashProvider.java
  server-spi-private/src/main/java/org/keycloak/credential/hash/Pbkdf2PasswordHashProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/credential/hash/Pbkdf2Sha256PasswordHashProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/credential/hash/Pbkdf2Sha512PasswordHashProviderFactory.java
  server-spi/src/main/java/org/keycloak/models/PasswordPolicy.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/PasswordHashingTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/policy/PasswordPolicyTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#26338 Enable verify profile required action by default for new realms
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java
  server-spi-private/src/main/java/org/keycloak/models/utils/DefaultRequiredActions.java
  services/src/main/java/org/keycloak/services/managers/ApplianceBootstrap.java
  services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java
  services/src/main/java/org/keycloak/services/resources/WelcomeResource.java
  testsuite/integration-arquillian/servers/auth-server/undertow/src/main/java/org/keycloak/testsuite/arquillian/undertow/KeycloakOnUndertow.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IllegalAdminUpgradeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ImpersonationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/PermissionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/RequiredActionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/event/AdminEventAuthDetailsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmSessionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/VerifyProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/keycloak-add-user.json
  testsuite/utils/src/main/java/org/keycloak/testsuite/KeycloakServer.java
  themes/src/main/resources/theme/keycloak/welcome/index.ftl
Labels: team/cloud-native, team/store, team/core, flaky-test

#26462 Remove support for multiple AUTH_SESSION_ID cookies
  services/src/main/java/org/keycloak/services/managers/AuthenticationSessionManager.java
  services/src/main/java/org/keycloak/services/managers/UserSessionCrossDCManager.java
  services/src/main/java/org/keycloak/services/util/CookieHelper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cookies/CookieHelperTest.java
Labels: team/cloud-native, team/store, team/core, flaky-test

#26263 Create SPI and Provider for Verifiable Credentials Signing #25937
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.windows.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.unix.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.windows.approved.txt
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/VCIssuerException.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/JwtSigningService.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/JwtSigningServiceProviderFactory.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/LDSigningService.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/LDSigningServiceProviderFactory.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/SdJwtSigningService.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/SdJwtSigningServiceProviderFactory.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/SigningProperties.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/SigningService.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/SigningServiceException.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/VCSigningServiceProviderFactory.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/VCSigningServiceSpi.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/VerifiableCredentialsSigningService.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialSubject.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/Format.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/VerifiableCredential.java
  services/src/main/resources/META-INF/services/org.keycloak.provider.Spi
Labels: team/cloud-native, team/ui, flaky-test

#26282 fix http_tlsSecret example for operator
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakSharedCsvMetadata.java
Labels: team/cloud-native, flaky-test
