Repository keycloak/keycloak, pull requests merged in 2024-05, with the labels that each got.

#28894 Upgrade to Quarkus 3.2.12
  pom.xml
  testsuite/integration-arquillian/pom.xml
  testsuite/utils/pom.xml
Labels: team/cloud-native, flaky-test

#28885 Upgrade to Quarkus 3.8.4
  pom.xml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
Labels: team/cloud-native, flaky-test

#29102 Encode realm name in console URIs
  js/apps/account-ui/src/routes.tsx
  services/src/main/java/org/keycloak/services/managers/RealmManager.java
  services/src/main/java/org/keycloak/services/resources/admin/AdminRoot.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#29037 Client type service account default type
  server-spi-private/src/main/java/org/keycloak/client/clienttype/ClientType.java
  server-spi-private/src/main/java/org/keycloak/models/delegate/ClientModelLazyDelegate.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  services/src/main/java/org/keycloak/services/clienttype/client/TypeAwareClientModelDelegate.java
  services/src/main/java/org/keycloak/services/clienttype/client/TypedClientSimpleAttribute.java
  services/src/main/java/org/keycloak/services/clienttype/impl/DefaultClientType.java
  services/src/main/java/org/keycloak/services/clienttype/impl/DefaultClientTypeProvider.java
  services/src/main/java/org/keycloak/services/clienttype/impl/DefaultClientTypeProviderFactory.java
  services/src/main/java/org/keycloak/services/managers/ClientManager.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientResource.java
  services/src/main/resources/keycloak-default-client-types.json
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientTypesTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29209 Fix oid4vc tests
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakContainerFeaturesController.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29150 Introduce filtered (and paginated) search for organization members
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationMembersResource.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationsResource.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/UserGroupMembershipEntity.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  model/storage-private/src/main/java/org/keycloak/storage/UserStorageManager.java
  server-spi-private/src/main/java/org/keycloak/organization/OrganizationProvider.java
  server-spi/src/main/java/org/keycloak/storage/user/UserQueryMethodsProvider.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationMemberResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationMemberTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29110 fix: remove runtime related warnings from rebuild
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
Labels: team/cloud-native, flaky-test

#29151 fix: updating docs around -q parameter
  docs/documentation/server_admin/topics/admin-cli.adoc
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractRequestCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/CreateCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/DeleteCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/GetCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/UpdateCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/util/HttpUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin/KcAdmSessionTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29143 Use computeIfPresent also for Persistent sessions
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/EmbeddedCachesChangesPerformer.java
Labels: flaky-test

#29217 Fix catching NameAlreadyBoundException
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPIdentityStore.java
Labels: flaky-test

#29229 Use cache.compute() method to improve the replace retry loop
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/marshalling/Marshalling.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/ReplaceFunction.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
Labels: team/cloud-native, flaky-test

#29184 Ignore g-recaptcha-response in user profile validation
  services/src/main/java/org/keycloak/authentication/forms/RegistrationPage.java
  services/src/main/java/org/keycloak/authentication/forms/RegistrationUserCreation.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#28976 Ignore include in token scope for refresh token
  server-spi/src/main/java/org/keycloak/models/ClientSessionContext.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/services/util/DefaultClientSessionContext.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29236 Execute persistent sessions tests in CI and fix deadlock
  .github/workflows/ci.yml
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/EmbeddedCachesChangesPerformer.java
Labels: flaky-test

#29095 Bugfix/29094/fix client name help grammatical error
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#29204 Rework the result for the session search to contain a single result per user sessions
  .github/actions/conditional/conditions
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/SessionsResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/ClientIdSessionType.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/SessionRepresentation.java
Labels: team/ui, flaky-test

#28890 Fix typos found by codespell in docs
  docs/dependency-license-information.md
  docs/documentation/License.html
  docs/documentation/README.md
  docs/documentation/authorization_services/images/keycloak_logo.png
  docs/documentation/release_notes/topics/23_0_0.adoc
  docs/documentation/securing_apps/images/keycloak_logo.png
  docs/documentation/server_admin/images/add-provider-dialog.png
  docs/documentation/server_admin/images/add-provider-select.png
  docs/documentation/server_admin/images/add-user.png
  docs/documentation/server_admin/images/credentials.png
  docs/documentation/server_admin/images/domain-mode.png
  docs/documentation/server_admin/images/email-simple-example.png
  docs/documentation/server_admin/images/identity_broker_flow.png
  docs/documentation/server_admin/images/keycloak_logo.png
  docs/documentation/server_admin/images/update-server-config-dialog.png
  docs/documentation/server_admin/images/update-server-config-select.png
  docs/documentation/server_admin/images/users.png
  docs/documentation/server_admin/topics/admin-cli.adoc
  docs/documentation/server_admin/topics/authentication/flows.adoc
  docs/documentation/server_admin/topics/authentication/kerberos.adoc
  docs/documentation/server_admin/topics/authentication/otp-policies.adoc
  docs/documentation/server_admin/topics/identity-broker/social/paypal.adoc
  docs/documentation/server_admin/topics/roles-groups/con-role-scope-mappings.adoc
  docs/documentation/server_admin/topics/users/user-profile.adoc
  docs/documentation/server_development/images/keycloak_logo.png
  docs/documentation/server_development/topics/action-token-handler-spi.adoc
  docs/documentation/server_development/topics/themes.adoc
  docs/documentation/upgrading/topics/changes/changes-21_1_0.adoc
  docs/documentation/upgrading/topics/changes/changes-22_0_0.adoc
  docs/documentation/upgrading/topics/changes/changes-22_0_2.adoc
  docs/documentation/upgrading/topics/changes/changes-24_0_3.adoc
  docs/documentation/upgrading/topics/changes/changes.adoc
  docs/guides/high-availability/bblocks-active-passive-sync.adoc
  docs/guides/high-availability/deploy-aws-route53-loadbalancer.adoc
  docs/guides/high-availability/deploy-infinispan-kubernetes-crossdc.adoc
  docs/guides/high-availability/examples/generated/keycloak-ispn.yaml
  docs/guides/high-availability/examples/generated/keycloak.yaml
  docs/guides/server/caching.adoc
  docs/guides/server/configuration-metrics.adoc
  docs/guides/server/configuration.adoc
  docs/guides/server/db.adoc
  docs/guides/server/fips.adoc
  docs/guides/server/reverseproxy.adoc
  docs/pom.xml
  docs/tests-oidc-conformance.md
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#29260 Set logout token type to logout+jwt
  core/src/main/java/org/keycloak/util/TokenUtil.java
  services/src/main/java/org/keycloak/jose/jws/DefaultTokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29244 Remove old-WildFly, EAP 7.4 and 6.4 SAML adapters
  testsuite/integration-arquillian/servers/app-server/README.md
  testsuite/integration-arquillian/servers/app-server/jboss/eap/pom.xml
  testsuite/integration-arquillian/servers/app-server/jboss/eap/src/main/java/org/keycloak/testsuite/arquillian/eap/EAPAppServerArquillianExtension.java
  testsuite/integration-arquillian/servers/app-server/jboss/eap/src/main/java/org/keycloak/testsuite/arquillian/eap/container/EAPAppServerProvider.java
  testsuite/integration-arquillian/servers/app-server/jboss/eap/src/main/java/org/keycloak/testsuite/arquillian/eap/container/EAPDeploymentArchiveProcessor.java
  testsuite/integration-arquillian/servers/app-server/jboss/eap/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  testsuite/integration-arquillian/servers/app-server/jboss/eap/src/main/resources/META-INF/services/org.keycloak.testsuite.arquillian.container.AppServerContainerProvider
  testsuite/integration-arquillian/servers/app-server/jboss/eap/src/saml-adapter-supported
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/pom.xml
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/java/org/keycloak/testsuite/arquillian/eap/EAP6AppServerArquillianExtension.java
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/java/org/keycloak/testsuite/arquillian/eap/container/EAP6AppServerProvider.java
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/java/org/keycloak/testsuite/arquillian/eap/container/EAP6DeploymentArchiveProcessor.java
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/resources/META-INF/services/org.keycloak.testsuite.arquillian.container.AppServerContainerProvider
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/resources/config/add-secured-deployments.bat
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/resources/config/add-secured-deployments.sh
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/resources/config/cli/add-adapter-log-level.cli
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/resources/config/cli/add-secured-deployments.cli
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/resources/config/cli/configure-cluster-config.cli
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/resources/config/fuse/add-hawtio.xsl
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/resources/config/fuse/install-fuse.sh
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/resources/config/fuse/keycloak-hawtio-client.json
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/resources/config/fuse/keycloak-hawtio.json
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/resources/config/install-adapters-online-ha.bat
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/resources/config/install-adapters-online-ha.sh
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/resources/config/install-adapters-online.bat
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/main/resources/config/install-adapters-online.sh
  testsuite/integration-arquillian/servers/app-server/jboss/eap6/src/saml-adapter-supported
  testsuite/integration-arquillian/servers/app-server/jboss/pom.xml
  testsuite/integration-arquillian/servers/pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/adapter/page/BasicAuth.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/AppServerTestEnricher.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/page/AbstractPageWithInjectedUrl.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/example/fuse/EAP6Fuse6HawtioAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/example/hal/ConsoleProtectionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/DemoServletsAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLClockSkewAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLLoginResponseHandlingTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLLogoutAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletSessionTimeoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SamlSignatureTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SamlXMLAttacksTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/cluster/SAMLAdapterClusterTest.java
  testsuite/integration-arquillian/util/src/main/java/org/keycloak/testsuite/utils/arquillian/ContainerConstants.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29064 Support for multiple identity providers
  core/src/main/java/org/keycloak/representations/idm/OrganizationDomainRepresentation.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationIdentityProvidersResource.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationResource.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/OrganizationEntity.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/OrganizationAdapter.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-25.0.0.xml
  server-spi-private/src/main/java/org/keycloak/organization/OrganizationProvider.java
  server-spi/src/main/java/org/keycloak/models/IdentityProviderModel.java
  server-spi/src/main/java/org/keycloak/models/OrganizationModel.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationIdentityProviderResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationIdentityProvidersResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/broker/IdpAddOrganizationMemberAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/broker/IdpOrganizationAuthenticatorFactory.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAwareIdentityProviderBean.java
  services/src/main/java/org/keycloak/organization/forms/login/freemarker/model/OrganizationAwareIdentityProviderBean.java
  services/src/main/java/org/keycloak/organization/validator/OrganizationMemberValidator.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationAdminPermissionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationBrokerSelfRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationIdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationMemberAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationMemberTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29291 Ignore github links when checking links
  docs/documentation/tests/src/test/resources/ignored-links
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#29167 Improve details for user error events in OIDC protocol endpoints
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/UserInfoEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthorizationEndpointRequestParserProcessor.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/AuthorizationCodeGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ClientCredentialsGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/OAuth2GrantTypeBase.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/PermissionGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/PreAuthorizedCodeGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ResourceOwnerPasswordCredentialsGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/CibaGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/device/DeviceGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/device/endpoints/DeviceEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/PkceUtils.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/PKCEEnforcerExecutor.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPI1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuth2DeviceAuthorizationGrantTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthProofKeyForCodeExchangeTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29210 Do not use LastSessionRefreshPersister with persistent user sessions …
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/UserSessionAdapter.java
  server-spi-private/src/main/java/org/keycloak/models/UserSessionProviderFactory.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderModelTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderOfflineModelTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29265 Remove PERSISTENT_USER_SESSIONS_No_CACHE feature
  .github/workflows/ci.yml
  common/src/main/java/org/keycloak/common/Profile.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/ClientSessionPersistentChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/InfinispanChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/PersistentSessionsChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/UserSessionPersistentChangelogBasedTransaction.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
  testsuite/model/pom.xml
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/PersistentUserSessionsNoCache.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionInitializerTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29221 Handle reset credentials flow with logged in user
  services/src/main/java/org/keycloak/authentication/AuthenticatorUtil.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/CookieAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialChooseUser.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29125 Generate translations for locales via built-in Java functionality
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
  js/apps/admin-ui/src/user/UserForm.tsx
  js/apps/admin-ui/src/util.ts
  js/libs/ui-shared/src/user-profile/LocaleSelector.tsx
  js/libs/ui-shared/src/user-profile/UserProfileFields.tsx
  services/src/main/java/org/keycloak/theme/DefaultThemeManager.java
  services/src/main/java/org/keycloak/theme/beans/LocaleBean.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LanguageComboboxAwarePage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/error/UncaughtErrorPageTest.java
  themes/src/main/resources-community/theme/base/account/messages/messages_ar.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_da.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_el.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_fa.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_fi.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_hu.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_lt.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_lv.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_nl.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_no.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ru.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_sk.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_sv.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_tr.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_zh_CN.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_zh_TW.properties
  themes/src/main/resources-community/theme/base/account/theme.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_da.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_el.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fa.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_hu.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_sk.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_zh_CN.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_zh_TW.properties
  themes/src/main/resources-community/theme/base/login/theme.properties
  themes/src/main/resources/theme/base/account/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#28480 Fix incorrect branching for some authentication flow diagrams. Fixes #28479
  js/apps/admin-ui/cypress/e2e/authentication_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/SidebarPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/authentication/FlowDiagram.ts
  js/apps/admin-ui/src/authentication/__tests__/FlowDiagram.test.tsx
  js/apps/admin-ui/src/authentication/components/FlowDiagram.tsx
  js/apps/admin-ui/vite.config.ts
Labels: team/ui

#29321 29183 backport
  docs/guides/high-availability/bblocks-active-passive-sync.adoc
  docs/guides/high-availability/concepts-active-passive-sync.adoc
  docs/guides/high-availability/concepts-infinispan-cli-batch.adoc
  docs/guides/high-availability/connect-keycloak-to-external-infinispan.adoc
  docs/guides/high-availability/deploy-infinispan-kubernetes-crossdc.adoc
  docs/guides/high-availability/partials/infinispan/infinispan-credentials.adoc
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#29138 Remove unused code from model/infinispan module
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/InfinispanUtil.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/CacheManager.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheManager.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheManager.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/authorization/StoreFactoryCacheSession.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/authorization/entities/ResourceServerListQuery.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedClient.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedRealm.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/GroupListQuery.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/events/ClientAddedEvent.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/Consumers.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanAuthenticationSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanAuthenticationSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanKeycloakTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanSingleUseObjectProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserLoginFailureProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/UserSessionTimestamp.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/ClientSessionPersistentChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/ClientSessionUpdateTask.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/EmbeddedCachesChangesPerformer.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/InfinispanChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/JpaChangesPerformer.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/LoginFailuresUpdateTask.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/MergedUpdate.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/PersistentSessionsChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/SessionEntityWrapper.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/SessionUpdateTask.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/Tasks.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/UserSessionPersistentChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/UserSessionUpdateTask.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/events/AbstractAuthSessionClusterListener.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/events/AbstractUserSessionClusterListener.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/events/ClientRemovedSessionEvent.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/BaseCacheInitializer.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/CacheInitializer.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/InfinispanCacheInitializer.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/OfflinePersistentLoaderContext.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/OfflinePersistentWorkerContext.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/OfflinePersistentWorkerResult.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/SessionLoader.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionListener.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionsLoader.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionsLoaderContext.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/stream/AuthenticatedClientSessionPredicate.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/stream/Comparators.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/stream/Mappers.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/util/KeycloakMarshallUtil.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/util/SessionTimeouts.java
  model/infinispan/src/test/java/org/keycloak/cluster/infinispan/RemoteCacheSessionsLoaderTest.java
Labels: flaky-test

#29279 Add enabled field to OrganizationEntity
  core/src/main/java/org/keycloak/representations/idm/OrganizationRepresentation.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/OrganizationEntity.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/OrganizationAdapter.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-25.0.0.xml
  model/storage-private/src/main/java/org/keycloak/storage/UserStorageManager.java
  server-spi/src/main/java/org/keycloak/models/OrganizationModel.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationBrokerSelfRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationMemberTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28971 Fix user-facing typos in Java code
  adapters/saml/core/src/main/java/org/keycloak/adapters/saml/PropertiesBasedRoleMapper.java
  adapters/saml/core/src/main/java/org/keycloak/adapters/saml/SamlDeployment.java
  common/src/main/java/org/keycloak/common/util/Base64.java
  common/src/main/java/org/keycloak/common/util/Encode.java
  common/src/main/java/org/keycloak/common/util/NetworkUtils.java
  common/src/main/java/org/keycloak/common/util/StringPropertyReplacer.java
  common/src/main/java/org/keycloak/common/util/reflections/Reflections.java
  core/src/main/java/org/keycloak/jose/jwk/JWKUtil.java
  core/src/main/java/org/keycloak/sdjwt/SdJwt.java
  core/src/test/java/org/keycloak/sdjwt/sdjwtvp/TestCompareSdJwt.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPUtils.java
  federation/sssd/src/main/java/org/freedesktop/dbus/connections/impl/BaseConnectionBuilder.java
  federation/sssd/src/main/java/org/freedesktop/dbus/connections/impl/DBusConnection.java
  federation/sssd/src/main/java/org/freedesktop/dbus/interfaces/DBus.java
  federation/sssd/src/main/java/org/freedesktop/dbus/messages/MethodCall.java
  federation/sssd/src/main/java/org/freedesktop/dbus/utils/XmlUtil.java
  federation/sssd/src/main/java/org/jvnet/libpam/PAM.java
  federation/sssd/src/main/java/org/jvnet/libpam/impl/PAMLibrary.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/UsersResource.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/AbstractExtendableRevisioned.java
  model/storage/src/main/java/org/keycloak/storage/adapter/AbstractUserAdapter.java
  model/storage/src/main/java/org/keycloak/storage/adapter/AbstractUserAdapterFederatedStorage.java
  saml-core/src/main/java/org/keycloak/rotation/HardcodedKeyLocator.java
  saml-core/src/main/java/org/keycloak/saml/processing/core/saml/v2/util/AssertionUtil.java
  saml-core/src/main/java/org/keycloak/saml/processing/core/saml/v2/util/XMLTimeUtil.java
  server-spi-private/src/main/java/org/keycloak/authentication/AbstractAuthenticationFlowContext.java
  server-spi-private/src/main/java/org/keycloak/authentication/AuthenticationFlowContext.java
  server-spi-private/src/main/java/org/keycloak/authentication/Authenticator.java
  server-spi-private/src/main/java/org/keycloak/authentication/ConfigurableAuthenticatorFactory.java
  server-spi-private/src/main/java/org/keycloak/authentication/FlowStatus.java
  server-spi-private/src/main/java/org/keycloak/authentication/RequiredActionContext.java
  server-spi-private/src/main/java/org/keycloak/authentication/ValidationContext.java
  server-spi-private/src/main/java/org/keycloak/authorization/attribute/Attributes.java
  server-spi-private/src/main/java/org/keycloak/provider/ServerInfoAwareProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/storage/StoreMigrateRepresentationEvent.java
  server-spi-private/src/main/java/org/keycloak/utils/ProxyClassLoader.java
  server-spi/src/main/java/org/keycloak/models/IdentityProviderModel.java
  server-spi/src/main/java/org/keycloak/services/clientpolicy/ClientPolicyManager.java
  server-spi/src/main/java/org/keycloak/sessions/CommonClientSessionModel.java
  server-spi/src/main/java/org/keycloak/storage/group/GroupLookupProvider.java
  server-spi/src/main/java/org/keycloak/validate/ValidationError.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/ScriptBasedAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/util/LoAUtil.java
  services/src/main/java/org/keycloak/forms/login/freemarker/model/AbstractUserProfileBean.java
  services/src/main/java/org/keycloak/partialimport/IdentityProviderMappersPartialImport.java
  services/src/main/java/org/keycloak/partialimport/IdentityProvidersPartialImport.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/signing/VCSigningServiceSpi.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/UserAttributeMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/UserPropertyMapper.java
  services/src/main/java/org/keycloak/protocol/saml/profile/util/Soap.java
  services/src/main/java/org/keycloak/services/resources/LoadBalancerResource.java
Labels: flaky-test

#28700 Improve alternative step display in FlowDiagram (#28699)
  js/apps/admin-ui/cypress/e2e/authentication_test.spec.ts
  js/apps/admin-ui/src/authentication/__tests__/FlowDiagram.test.tsx
  js/apps/admin-ui/src/authentication/components/FlowDiagram.tsx
Labels: team/ui

#29308 use default also when it doesn't contain a "##"
  js/apps/admin-ui/src/components/multi-line-input/MultiLineInput.tsx
Labels: team/ui

#29315 Make Core Clients team code owner of Keycloak JS
  .github/CODEOWNERS
Labels: kind/task

#29188 Add missing q query parameter to user and client queries on js admin client
  js/libs/keycloak-admin-client/src/resources/clients.ts
  js/libs/keycloak-admin-client/src/resources/users.ts
Labels: team/core-clients

#28690 #24462 Refactor element identifiers from ID to class
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/WebAuthnAuthenticatorsList.java
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/WebAuthnLoginPage.java
  themes/src/main/resources/theme/base/login/webauthn-authenticate.ftl
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#29269 Do not manage brokers through the Organization API
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationIdentityProviderResource.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationIdentityProvidersResource.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationIdentityProvidersResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/BrokerConfigurationWrapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationAdminPermissionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationBrokerSelfRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationIdentityProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29224 Fix deprecated PF5 Tables
  js/apps/admin-ui/cypress/e2e/identity_providers_oidc_test.spec.ts
  js/apps/admin-ui/cypress/e2e/identity_providers_saml_test.spec.ts
  js/apps/admin-ui/src/events/AdminEvents.tsx
  js/apps/admin-ui/src/realm-settings/localization/RealmOverrides.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AddTranslationsDialog.tsx
  js/apps/admin-ui/src/user/user-credentials/CredentialDataDialog.tsx
Labels: team/ui

#29157 Conditionally run Quarkus tests
  .github/actions/conditional/action.yml
  .github/actions/conditional/conditions
  .github/workflows/ci.yml
Labels: flaky-test

#29357 Add description field to OrganizationEntity
  core/src/main/java/org/keycloak/representations/idm/OrganizationRepresentation.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/OrganizationEntity.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/OrganizationAdapter.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-25.0.0.xml
  server-spi/src/main/java/org/keycloak/models/OrganizationModel.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29332 Adding SAML protocol mapper to map organization membership
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationMembershipMapper.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/saml/OrganizationMembershipMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolFactory.java
  services/src/main/java/org/keycloak/protocol/saml/SamlProtocolFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.protocol.ProtocolMapper
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationSAMLProtocolMapperTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29046 Do not return groups associated with organizations from the Admin Gro…
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/OrganizationEntity.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  services/src/main/java/org/keycloak/utils/OrganizationUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupSearchTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationMemberTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#28653 iso-date validator for the user-profile
  docs/documentation/server_admin/topics/users/user-profile.adoc
  server-spi-private/src/main/java/org/keycloak/validate/BuiltinValidators.java
  server-spi-private/src/main/java/org/keycloak/validate/validators/IsoDateValidator.java
  server-spi-private/src/main/resources/META-INF/services/org.keycloak.validate.ValidatorFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/validation/ValidatorTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29160 Can we remove undertow OIDC adapter?
  adapters/oidc/pom.xml
  adapters/oidc/undertow/pom.xml
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/AbstractUndertowKeycloakAuthMech.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/AbstractUndertowRequestAuthenticator.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/KeycloakChallenge.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/KeycloakServletExtension.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/KeycloakUndertowAccount.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/OIDCServletUndertowHttpFacade.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/OIDCUndertowHttpFacade.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/ServletKeycloakAuthMech.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/ServletPreAuthActionsHandler.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/ServletRequestAuthenticator.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/ServletSessionTokenStore.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/UndertowAuthenticatedActionsHandler.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/UndertowAuthenticationMechanism.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/UndertowCookieTokenStore.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/UndertowNodesRegistrationManagementWrapper.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/UndertowPreAuthActionsHandler.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/UndertowRequestAuthenticator.java
  adapters/oidc/undertow/src/main/java/org/keycloak/adapters/undertow/UndertowSessionTokenStore.java
  adapters/oidc/undertow/src/main/resources/META-INF/services/io.undertow.servlet.ServletExtension
  boms/adapter/pom.xml
  distribution/feature-packs/adapter-feature-pack/pom.xml
  distribution/feature-packs/adapter-feature-pack/src/main/resources/modules/system/add-ons/keycloak/org/keycloak/keycloak-undertow-adapter/main/module.xml
  pom.xml
  testsuite/integration-arquillian/servers/adapter-spi/README.md
  testsuite/integration-arquillian/servers/adapter-spi/pom.xml
  testsuite/integration-arquillian/servers/adapter-spi/undertow-adapter-jakarta/.gitignore
  testsuite/integration-arquillian/servers/adapter-spi/undertow-adapter-jakarta/pom.xml
  testsuite/integration-arquillian/servers/adapter-spi/undertow-adapter-saml-jakarta/pom.xml
  testsuite/integration-arquillian/servers/app-server/undertow/pom.xml
  testsuite/integration-arquillian/servers/auth-server/undertow/pom.xml
  testsuite/utils/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29361 Adding tests to cover using SAML brokers in an organization
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractBrokerSelfRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationBrokerSelfRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationSAMLBrokerSelfRegistrationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29272 Add a separator for listing required permissions
  js/apps/admin-ui/src/ForbiddenSection.tsx
Labels: team/ui

#29370 Improve tests to ensure managed users disabled upon disabling the org…
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationMemberTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29379 Upgrade JS dependencies to latest version
  js/apps/account-ui/package.json
  js/apps/admin-ui/package.json
  js/apps/keycloak-server/package.json
  js/libs/keycloak-admin-client/package.json
  js/libs/keycloak-js/package.json
  js/libs/ui-shared/package.json
  package.json
  pnpm-lock.yaml
  pom.xml
  themes/src/main/resources/theme/keycloak/common/resources/package.json
Labels: kind/task, team/ui, flaky-test

#29069 Infinispan 15.0.3.Final
  adapters/saml/wildfly-elytron-jakarta/pom.xml
  adapters/saml/wildfly-elytron/pom.xml
  adapters/saml/wildfly-elytron/src/main/java/org/keycloak/adapters/saml/elytron/infinispan/InfinispanSessionCacheIdMapperUpdater.java
  docs/guides/high-availability/examples/generated/ispn-single.yaml
  docs/guides/high-availability/examples/generated/ispn-site-a.yaml
  docs/guides/high-availability/examples/generated/ispn-site-b.yaml
  model/infinispan/pom.xml
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/InfinispanMultiSiteLoadBalancerCheckProvider.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/InfinispanUtil.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/TopologyInfo.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserLoginFailureProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/BaseCacheInitializer.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/InfinispanCacheInitializer.java
  model/infinispan/src/test/java/org/keycloak/cluster/infinispan/ConcurrencyJDGCachePutTest.java
  model/infinispan/src/test/java/org/keycloak/cluster/infinispan/ConcurrencyJDGRemoteCacheClientListenersTest.java
  model/infinispan/src/test/java/org/keycloak/keys/infinispan/InfinispanKeyStorageProviderTest.java
  operator/src/test/resources/cache-ispn.xml
  pom.xml
  quarkus/config-api/pom.xml
  quarkus/runtime/pom.xml
  quarkus/runtime/src/main/resources/cache-ispn.xml
  quarkus/runtime/src/main/resources/cache-local.xml
  quarkus/tests/integration/src/test/resources/ExternalInfinispan/kcb-infinispan-cache-remote-store-config.xml
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/pom.xml
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/model/infinispan/InfinispanTimeServiceTask.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/resource/TestCacheResource.java
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/integration-arquillian/tests/pom.xml
  testsuite/model/pom.xml
  testsuite/utils/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29369 switch the default JVM GC from ParallelGC to G1GC
  quarkus/dist/src/main/content/bin/kc.bat
  quarkus/dist/src/main/content/bin/kc.sh
Labels: team/cloud-native, flaky-test

#29393 Avoid conflicts when writing to session stores by checking for concurrent requests within the JVM
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/ClientSessionPersistentChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/EmbeddedCachesChangesPerformer.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/PersistentSessionsChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/UserSessionPersistentChangelogBasedTransaction.java
Labels: flaky-test

#29400 Vault configuration category available to the export command
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractExportImportCommand.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#29371 Improvements to the organization authentication flow
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/forms/login/freemarker/model/OrganizationAwareAuthenticationContextBean.java
  services/src/main/java/org/keycloak/organization/forms/login/freemarker/model/OrganizationAwareIdentityProviderBean.java
  services/src/main/java/org/keycloak/organization/forms/login/freemarker/model/OrganizationAwareRealmBean.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractBrokerSelfRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationOIDCBrokerSelfRegistrationTest.java
  themes/src/main/resources/theme/base/login/login-username.ftl
  themes/src/main/resources/theme/base/login/login.ftl
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#29441 Workaround fixes for clients_test to pass
  js/apps/admin-ui/cypress/e2e/clients_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/components/TablePage.ts
Labels: team/ui

#29452 Add ability to search organizations by attribute
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationsResource.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  server-spi-private/src/main/java/org/keycloak/organization/OrganizationProvider.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java
  services/src/main/java/org/keycloak/services/resources/KeycloakOpenAPI.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29456 Guard against NPE when fetching users associated with user policies.
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/user/UserPolicyProviderFactory.java
Labels: flaky-test

#29455 Ensure master realm can't be removed
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29450 Fix realm removal when orgs are enabled
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
Labels: flaky-test

#29424 Make sure organization groups can not be managed but when managing an organization
  model/jpa/src/main/java/org/keycloak/models/jpa/GroupAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/UserAdapter.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProviderFactory.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/OrganizationAdapter.java
  server-spi/src/main/java/org/keycloak/models/GroupModel.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java
  services/src/main/java/org/keycloak/organization/forms/login/freemarker/model/OrganizationAwareRealmBean.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  services/src/main/java/org/keycloak/utils/OrganizationUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationGroupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29448 Fix test failures after methods annotated with @DisableFeature
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakContainerFeaturesController.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29439 quarkus-next: Replace deprecated QUARKUS_PROFILE_PROP constant
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Environment.java
Labels: team/cloud-native, flaky-test

#29405 Change the default role mapping filter to clients
  js/apps/admin-ui/cypress/e2e/client_scopes_test.spec.ts
  js/apps/admin-ui/cypress/e2e/clients_test.spec.ts
  js/apps/admin-ui/cypress/e2e/group_test.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_user_registration.spec.ts
  js/apps/admin-ui/cypress/e2e/users_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/RoleMappingTab.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/groups/group_details/GroupDetailPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_roles/AssociatedRolesPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/UserRegistration.ts
  js/apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
Labels: team/ui

#29467 Allow empty CSP header in headers provider
  services/src/main/java/org/keycloak/headers/DefaultSecurityHeadersProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LoginStatusIframeEndpointTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29347 Create documentation for persistent user sessions
  common/src/main/java/org/keycloak/common/Profile.java
  docs/documentation/release_notes/topics/25_0_0.adoc
  docs/documentation/server_admin/topics/sessions/offline.adoc
  docs/documentation/upgrading/topics/prep_migration.adoc
  docs/guides/high-availability/concepts-memory-and-cpu-sizing.adoc
  docs/guides/high-availability/deploy-infinispan-kubernetes-crossdc.adoc
  docs/guides/server/caching.adoc
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
Labels: team/cloud-native, flaky-test

#29463 Ensure master realm can't be removed
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
Labels: flaky-test

#29353 Added a check in ClientInitialAccessResource
  services/src/main/java/org/keycloak/services/resources/admin/ClientInitialAccessResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/InitialAccessTokenResourceTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29374 Added localization for User Profile attribute groups
  js/apps/admin-ui/cypress/e2e/clients_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/ListingPage.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
  js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesGroupForm.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesGroupTab.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesTab.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/UserProfileTab.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AddTranslationsDialog.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
  js/apps/admin-ui/src/utils/useLocale.ts
Labels: team/ui

#29320 Avoid sorting items returned from the database which are already stable
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java
Labels: flaky-test

#29304 Adding dummyHash to DirectGrant request in case user does not exists.…
  crypto/default/src/test/java/org/keycloak/crypto/def/test/CryptoPerfTest.java
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  server-spi/src/main/java/org/keycloak/credential/hash/PasswordHashProvider.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/AbstractUsernameFormAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/directgrant/ValidateUsername.java
  services/src/main/java/org/keycloak/authentication/authenticators/util/AuthenticatorUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/PasswordHashingTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ResourceOwnerPasswordCredentialsGrantTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam, team/cross-dc

#29487 Allow empty CSP header in headers provider
  services/src/main/java/org/keycloak/headers/DefaultSecurityHeadersProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LoginStatusIframeEndpointTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29461 Email validation for managed members should only fail if it does not match the domain set to a broker
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  services/src/main/java/org/keycloak/organization/validator/OrganizationMemberValidator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractBrokerSelfRegistrationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29354 Align RestEasy version with Quarkus
  pom.xml
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/error/UncaughtErrorPageTest.java
Labels: area/dependencies, team/cloud-native, dependencies, flaky-test, backport/22.0

#27743 Add new ProviderConfigProperty type to expose URLs in admin-v2
  js/apps/admin-ui/src/components/dynamic/UrlComponent.tsx
  js/apps/admin-ui/src/components/dynamic/components.ts
  js/apps/admin-ui/src/components/dynamic/url-component.css
  server-spi/src/main/java/org/keycloak/provider/ProviderConfigProperty.java
Labels: team/ui

#29131 Defer initialization of JGroups after logging is set up by Quarkus
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/CacheBuildSteps.java
Labels: team/cloud-native, flaky-test

#29297 don't do multi select when type isn't multi
  js/libs/ui-shared/src/controls/SelectControl.tsx
  js/libs/ui-shared/src/controls/SwitchControl.tsx
Labels: team/ui

#29498 Minor improvements to invitation email templates
  server-spi-private/src/main/java/org/keycloak/email/EmailTemplateProvider.java
  services/src/main/java/org/keycloak/email/freemarker/FreeMarkerEmailTemplateProvider.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationInvitationResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationMemberResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java
  themes/src/main/resources/theme/base/email/html/org-invite.ftl
  themes/src/main/resources/theme/base/email/messages/messages_en.properties
  themes/src/main/resources/theme/base/email/text/org-invite.ftl
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#29485 Only store videos of failed Cypress tests
  js/apps/admin-ui/cypress.config.js
Labels: team/ui

#29496 Fixing realm removal when removing groups and brokers associated with an organization
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29428 Fix access for IDP links tab.
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/user_details/tabs/IdentityProviderLinksTab.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/user/EditUser.tsx
  js/apps/admin-ui/src/user/UserIdentityProviderLinks.tsx
Labels: team/ui

#29514 Make sure operations on a organization are based on realm they belong to
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationIdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationMemberTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28701 Add FormSubmitButton that listens on FormState
  js/apps/admin-ui/src/authentication/form/CreateFlow.tsx
  js/apps/admin-ui/src/client-scopes/details/ScopeForm.tsx
  js/apps/admin-ui/src/clients/import/ImportForm.tsx
  js/apps/admin-ui/src/clients/roles/CreateClientRole.tsx
  js/apps/admin-ui/src/components/role-form/RoleForm.tsx
  js/apps/admin-ui/src/groups/GroupsModal.tsx
  js/apps/admin-ui/src/realm-roles/CreateRealmRole.tsx
  js/apps/admin-ui/src/realm-roles/RealmRoleTabs.tsx
  js/apps/admin-ui/src/realm/add/NewRealmForm.tsx
  js/apps/admin-ui/src/user/UserForm.tsx
  js/libs/ui-shared/src/buttons/FormSubmitButton.tsx
  js/libs/ui-shared/src/main.ts
Labels: team/ui

#29524 Defer initialization of JGroups after logging is set up by Quarkus
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/CacheBuildSteps.java
Labels: team/cloud-native

#29540 Add CRUD for orgainizations to admin client.
  js/libs/keycloak-admin-client/src/client.ts
  js/libs/keycloak-admin-client/src/defs/organizationDomainRepresentation.ts
  js/libs/keycloak-admin-client/src/defs/organizationRepresentation.ts
  js/libs/keycloak-admin-client/src/resources/organizations.ts
  js/libs/keycloak-admin-client/test/organizations.spec.ts
Labels: team/ui

#29526 Clean generated files for the admin Java client
  integration/admin-client/pom.xml
Labels: flaky-test

#28809 Fix docker image building + readme
  quarkus/container/README.md
  quarkus/container/ubi-null.sh
Labels: team/cloud-native

#29490 Update instruction on how to enable persistent sessions
  docs/documentation/release_notes/topics/25_0_0.adoc
  docs/documentation/server_admin/topics/sessions.adoc
  docs/guides/high-availability/deploy-infinispan-kubernetes-crossdc.adoc
  docs/guides/server/caching.adoc
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
Labels: team/cloud-native, flaky-test

#22807 Entering a single space in a regex password policy makes admin interface unusable.
  server-spi-private/src/main/java/org/keycloak/policy/RegexPatternsPasswordPolicyProvider.java
Labels: flaky-test, team/core-shared

#29553 Clean generated files for the admin Java client
  integration/admin-client/pom.xml
Labels: flaky-test

#29555 Upgrade Infinispan to 14.0.27.Final
  model/infinispan/pom.xml
  model/map-hot-rod/pom.xml
  pom.xml
Labels: flaky-test

#29560 Remove the video file only if it exists
  js/apps/admin-ui/cypress.config.js
Labels: team/ui

#29564 Remove the video file only if it exists
  js/apps/admin-ui/cypress.config.js
Labels: team/ui

#29565 Keep correct format of config fields
  js/apps/admin-ui/src/identity-providers/add/DetailSettings.tsx
Labels: team/ui

#29569 Keep correct format of config fields
  js/apps/admin-ui/src/identity-providers/add/DetailSettings.tsx
Labels: team/ui

#29559 Add empty Georgian translation for Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ka.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ka.properties
Labels: team/ui, flaky-test

#28930 Restrict access to whoami endpoint for the admin console and users with realm access
  services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminConsolePermissionsCalculatedTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminConsoleWhoAmILocaleTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#24305 Passkeys: Supporting WebAuthn Conditional UI
  common/src/main/java/org/keycloak/common/Profile.java
  docs/documentation/server_admin/images/passkey-conditional-ui-authentication.png
  docs/documentation/server_admin/images/passkey-conditional-ui-autofill.png
  docs/documentation/server_admin/images/passkey-conditional-ui-fallback-authentication.png
  docs/documentation/server_admin/images/passkey-conditional-ui-flow.png
  docs/documentation/server_admin/topics/authentication/passkeys.adoc
  services/src/main/java/org/keycloak/authentication/authenticators/browser/PasskeysConditionalUIAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/PasskeysConditionalUIAuthenticatorFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.authentication.AuthenticatorFactory
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/WebAuthnAuthenticatorsList.java
  testsuite/integration-arquillian/tests/other/webauthn/src/main/java/org/keycloak/testsuite/webauthn/pages/WebAuthnLoginPage.java
  themes/src/main/resources/theme/base/login/login-passkeys-conditional-authenticate.ftl
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/resources/js/passkeysConditionalAuth.js
  themes/src/main/resources/theme/base/login/resources/js/webauthnAuthenticate.js
  themes/src/main/resources/theme/base/login/webauthn-authenticate.ftl
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#29326 Fix user-facing typos in error messages
  common/src/main/java/org/keycloak/common/profile/PropertiesFileProfileConfigResolver.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/LDAPTransaction.java
  federation/sssd/src/main/java/org/freedesktop/dbus/ArrayFrob.java
  federation/sssd/src/main/java/org/freedesktop/dbus/connections/GlobalHandler.java
  federation/sssd/src/main/resources/en_US.properties
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/CreateCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/UpdateCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/registration/cli/commands/CreateCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/registration/cli/commands/UpdateCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/registration/cli/commands/UpdateTokenCmd.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/initializer/InfinispanCacheInitializer.java
  quarkus/config-api/src/main/java/org/keycloak/config/LoggingOptions.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  saml-core/src/main/java/org/keycloak/saml/common/DefaultPicketLinkLogger.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletSessionTimeoutTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29621 Add OpenAPI documentation for the Organization API
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationIdentityProvidersResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationMemberResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java
Labels: flaky-test

#29626 Add chmod to ADD examples in docs
  docs/guides/server/containers.adoc
  docs/guides/server/db.adoc
Labels: team/cloud-native

#29582 Fix CRL verification failing due to client cert not being in chain
  services/src/main/java/org/keycloak/utils/CRLUtils.java
  testsuite/integration-arquillian/servers/auth-server/common/keystore/client-ca.crt
  testsuite/integration-arquillian/servers/auth-server/common/keystore/client-ca.key
  testsuite/integration-arquillian/servers/auth-server/quarkus/pom.xml
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/AbstractX509AuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509SingleCertificateBrowserCRLTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29631 Fix errors when importing realms with the organization feature enabled
  model/storage-services/src/main/java/org/keycloak/exportimport/dir/DirImportProvider.java
  model/storage-services/src/main/java/org/keycloak/exportimport/util/ImportUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationEnabledExportImportTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29648 Add chmod to ADD examples in docs (24.0 backport)
  docs/guides/server/containers.adoc
  docs/guides/server/db.adoc
Labels: team/cloud-native

#28239 Remove Twitter workaround (#28232)
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28238 Remove Twitter workaround (#28232)
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java
Labels: team/cloud-native, flaky-test

#29584 Reflect changes in property names
  operator/pom.xml
  quarkus/runtime/src/main/resources/application.properties
  quarkus/server/src/main/resources/application.properties
Labels: team/cloud-native

#29646 Allow admin console whoami endpoint to applications that have a special attribute
  js/apps/keycloak-server/scripts/security-admin-console-v2.json
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminConsoleWhoAmILocaleTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#29691 Temporarily disable client_authorization_test
  js/apps/admin-ui/cypress/e2e/client_authorization_test.spec.ts
Labels: team/ui

#29710 Skip failing test for now.
  js/apps/admin-ui/cypress/e2e/realm_settings_user_profile_enabled.spec.ts
Labels: team/ui

#29645 add value of unmanagedAttributePolicy to the form
  js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
Labels: team/ui

#29618 Added save function in UserForm.tsx
  js/apps/admin-ui/src/user/UserForm.tsx
Labels: team/ui

#29739 Translations for loa-condition-level and loa-max-age
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#29733 Use admin console correctly in KeycloakIdentity
  js/apps/admin-ui/cypress/e2e/client_authorization_test.spec.ts
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UIRealmsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java
Labels: team/ui

#29337 Update KeysListTab.tsx
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/keys/KeysListTab.tsx
Labels: team/ui

#29705 Provide an additional endpoint to allow sending both invitation and r…
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationMembersResource.java
  services/src/main/java/org/keycloak/email/freemarker/FreeMarkerEmailTemplateProvider.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationInvitationResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationMemberResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java
  themes/src/main/resources/theme/base/email/html/org-invite.ftl
  themes/src/main/resources/theme/base/email/messages/messages_en.properties
  themes/src/main/resources/theme/base/email/text/org-invite.ftl
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#29571 Support unmanaged attributes for service accounts and make sure they are only managed through the admin api
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/UserResource.java
  js/apps/admin-ui/cypress/e2e/users_test.spec.ts
  js/apps/admin-ui/src/components/users/resource.ts
  js/apps/admin-ui/src/user/EditUser.tsx
  js/libs/keycloak-admin-client/src/resources/users.ts
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AdminExtResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UserResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UsersResource.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java
  services/src/main/java/org/keycloak/userprofile/LegacyAttributes.java
  services/src/main/java/org/keycloak/userprofile/ServiceAccountAttributes.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ServiceAccountUserProfileTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#29706 Client type OIDC base read only defaults
  common/src/main/java/org/keycloak/common/util/CollectionUtil.java
  core/src/main/java/org/keycloak/representations/idm/ClientTypeRepresentation.java
  server-spi-private/src/main/java/org/keycloak/client/clienttype/ClientType.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  services/src/main/java/org/keycloak/services/clienttype/client/TypeAwareClientModelDelegate.java
  services/src/main/java/org/keycloak/services/clienttype/client/TypedClientAttribute.java
  services/src/main/java/org/keycloak/services/clienttype/impl/DefaultClientType.java
  services/src/main/java/org/keycloak/services/clienttype/impl/DefaultClientTypeProvider.java
  services/src/main/resources/keycloak-default-client-types.json
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientTypesTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29544 Protocol now is mandatory during client scope creation.
  services/src/main/java/org/keycloak/services/resources/admin/ClientScopeResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientScopesResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/ClientScopeTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#28386 Upgrade owasp-java-html-sanitizer from 20220608.1 to 20240325.1
  distribution/api-docs-dist/pom.xml
  pom.xml
  quarkus/runtime/pom.xml
  services/pom.xml
  services/src/main/java/org/keycloak/authentication/forms/AbstractRegistrationRecaptcha.java
  services/src/main/java/org/keycloak/authentication/forms/RegistrationRecaptcha.java
  services/src/main/java/org/keycloak/authentication/forms/RegistrationRecaptchaEnterprise.java
  services/src/main/java/org/keycloak/credential/WebAuthnCredentialProvider.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialIssuer.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialsOffer.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/OID4VCClient.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/Role.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/SupportedCredentialConfiguration.java
  services/src/main/java/org/keycloak/theme/KeycloakSanitizerPolicy.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UmaGrantTypeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/MutualTLSClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/saml/ArtifactBindingTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509OCSPResponderFailOpenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509OCSPResponderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29013 Use SessionExpirationUtils for validate user and client sessions. Check client session is valid in TokenManager.
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/AuthenticatedClientSessionAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/MergedUpdate.java
  server-spi/src/main/java/org/keycloak/models/AuthenticatedClientSessionModel.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/util/UserSessionUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29628 Issue 29627: Expose Authorization Server Metadata Endpoint under /.well-known/oauth-authorization-server to comply with rfc8414
  services/src/main/java/org/keycloak/protocol/oauth2/OAuth2WellKnownProviderFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.wellknown.WellKnownProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuth2WellKnownProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AbstractWellKnownProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCWellKnownProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29377 Allow migration of non-persistent sessions to persistent sessions
  docs/documentation/release_notes/topics/25_0_0.adoc
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/JpaChangesPerformer.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/SessionUpdatesList.java
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo25_0_0.java
  server-spi/src/main/java/org/keycloak/models/UserSessionProvider.java
  testsuite/model/pom.xml
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionPersisterProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29776 Require external Infinispan be of version 15 or greater
  docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc
  docs/guides/high-availability/bblocks-active-passive-sync.adoc
  docs/guides/high-availability/deploy-infinispan-kubernetes-crossdc.adoc
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
Labels: team/cloud-native

#29774 Fix for Issue #29773, Community keycloak-saml-adapter-galleon-pack shouldn't require to be resolved from channel
  distribution/galleon-feature-packs/saml-adapter-galleon-pack/pom.xml
Labels: flaky-test

#29453 Fix deprecated wizards
  js/apps/admin-ui/cypress/e2e/clients_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/CreateClientPage.ts
  js/apps/admin-ui/src/clients/add/NewClientForm.tsx
  js/apps/admin-ui/src/user-federation/UserFederationKerberosWizard.tsx
  js/apps/admin-ui/src/user-federation/UserFederationLdapWizard.tsx
Labels: team/ui

#29593 Enhance StartDevCommandDistTest to detect problems with URI scheme on Windows
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartDevCommandDistTest.java
Labels: team/cloud-native, flaky-test

#29785 Move organization authenticators into conditional subflows in the defa…
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProviderFactory.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/broker/IdpOrganizationAuthenticatorFactory.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticatorFactory.java
Labels: flaky-test

#28419 Make required actions configurable (#28400)
  core/src/main/java/org/keycloak/representations/idm/RequiredActionConfigInfoRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/RequiredActionConfigRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/RequiredActionProviderRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/RequiredActionProviderSimpleRepresentation.java
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/AuthenticationManagementResource.java
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_CN.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/authentication/RequiredActions.tsx
  js/apps/admin-ui/src/authentication/components/DraggableTable.tsx
  js/apps/admin-ui/src/authentication/components/RequiredActionConfigModal.tsx
  js/libs/keycloak-admin-client/src/defs/requiredActionConfigInfoRepresentation.ts
  js/libs/keycloak-admin-client/src/defs/requiredActionConfigRepresentation.ts
  js/libs/keycloak-admin-client/src/resources/authenticationManagement.ts
  js/libs/keycloak-admin-client/test/authenticationManagement.spec.ts
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedRealm.java
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AuthenticationManagementResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/ConfigurableRequiredActionProviderRepresentation.java
  server-spi-private/src/main/java/org/keycloak/authentication/RequiredActionContext.java
  server-spi-private/src/main/java/org/keycloak/authentication/RequiredActionFactory.java
  server-spi-private/src/main/java/org/keycloak/events/admin/ResourceType.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RealmModelDelegate.java
  server-spi-private/src/main/java/org/keycloak/userprofile/ValidationException.java
  server-spi-private/src/main/java/org/keycloak/utils/RequiredActionHelper.java
  server-spi-private/src/test/java/org/keycloak/broker/provider/util/IdentityBrokerStateTestHelpers.java
  server-spi/src/main/java/org/keycloak/models/RealmModel.java
  server-spi/src/main/java/org/keycloak/models/RequiredActionConfigModel.java
  services/src/main/java/org/keycloak/authentication/RequiredActionContextResult.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdatePassword.java
  services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/actions/DummyConfigurableRequiredActionFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/resources/META-INF/services/org.keycloak.authentication.RequiredActionFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/RequiredActionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/AdminEventPaths.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#28956 Always order required actions by priority (regardless of context)
  server-spi-private/src/main/java/org/keycloak/events/Details.java
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  server-spi/src/main/java/org/keycloak/models/UserModel.java
  server-spi/src/main/java/org/keycloak/sessions/AuthenticationSessionModel.java
  services/src/main/java/org/keycloak/authentication/requiredactions/VerifyUserProfile.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/admin/ApiUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionResetPasswordTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionPriorityTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/VerifyProfileTest.java
  testsuite/integration-arquillian/tests/other/webauthn/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnRegisterAndLoginTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29767 OAuth 2.0 Device Polling Interval - Realms settings/Token Tab +- to change value not working
  js/apps/admin-ui/src/realm-settings/TokensTab.tsx
Labels: team/ui

#29414 [#29412] DB Allocator removal - dependency cleanup.
  docs/tests-db.md
  testsuite/db-allocator-plugin/pom.xml
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/AllocateDBMojo.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/Constants.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/ReleaseDBMojo.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/client/BackoffRetryPolicy.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/client/DBAllocatorServiceClient.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/client/data/AllocationResult.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/client/data/EraseResult.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/client/data/ReleaseResult.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/client/exceptions/DBAllocatorException.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/client/exceptions/DBAllocatorUnavailableException.java
  testsuite/db-allocator-plugin/src/main/java/org/keycloak/testsuite/dballocator/client/retry/IncrementalBackoffRetryPolicy.java
  testsuite/db-allocator-plugin/src/test/java/org/keycloak/testsuite/dballocator/client/DBAllocatorServiceClientTest.java
  testsuite/db-allocator-plugin/src/test/java/org/keycloak/testsuite/dballocator/client/mock/MockResponse.java
  testsuite/db-allocator-plugin/src/test/java/org/keycloak/testsuite/dballocator/client/retry/IncrementalBackoffRetryPolicyTest.java
  testsuite/db-allocator-plugin/src/test/resources/db-allocator-response.properties
  testsuite/db-allocator-plugin/src/test/resources/log4j.properties
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29792 Entry 999.0.0 in MIGRATION_MODEL prevents future migrations of the da…
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultMigrationManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/MigrationDeniedTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29597 Clear entries in remote caches and force events on the remote site
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java
Labels: flaky-test

#29811 Filter empty domains from OrganizationsRepresentation before running …
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationsResource.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29815 Add dependency on guava to keycloak-api-docs-dist
  distribution/api-docs-dist/pom.xml
Labels: flaky-test

#29810 Generate RESTART_AUTHENTICATION event on success
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultiFactorAuthenticationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#29588 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ka.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ka.properties
Labels: team/ui, flaky-test

#29795 Show a message when confirming an invitation link
  server-spi/src/main/java/org/keycloak/models/OrganizationModel.java
  services/src/main/java/org/keycloak/authentication/actiontoken/inviteorg/InviteOrgActionTokenHandler.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/services/messages/Messages.java
  services/src/main/java/org/keycloak/theme/beans/MessageFormatterMethod.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#27939 Optimize settings for Hibernate ORM
  model/jpa/src/main/java/org/keycloak/connections/jpa/PersistenceExceptionConverter.java
  model/jpa/src/main/resources/default-persistence.xml
Labels: flaky-test

#29823 MigrateTo25_0_0 does not complete within default transaction timeout
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/ClientScopeClientMappingEntity.java
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo25_0_0.java
  model/storage-private/src/main/java/org/keycloak/storage/ClientStorageManager.java
  server-spi/src/main/java/org/keycloak/models/ClientProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29806 Fix oid4vc mappers
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29333 Issue 29309
  core/src/main/java/org/keycloak/crypto/ECDSASignatureVerifierContext.java
  core/src/test/java/org/keycloak/sdjwt/TestSettings.java
  core/src/test/java/org/keycloak/sdjwt/sdjwtvp/SdJwtVPTest.java
  core/src/test/resources/sdjwt/s7.3-sdjwt.txt
  crypto/default/src/test/java/org/keycloak/crypto/def/test/DefaultCryptoSdJwtVPTest.java
  crypto/elytron/src/test/java/org/keycloak/crypto/elytron/test/ElytronCryptoSdJwtVPTest.java
Labels: flaky-test

#29517 JUnit 5 test framework PoC
  .github/workflows/ci.yml
  pom.xml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java
  test-poc/base/pom.xml
  test-poc/base/src/test/java/org/keycloak/test/base/CustomConfigTest.java
  test-poc/base/src/test/java/org/keycloak/test/base/DefaultConfig1Test.java
  test-poc/base/src/test/java/org/keycloak/test/base/DefaultConfig2Test.java
  test-poc/base/src/test/java/org/keycloak/test/base/ManagedResourcesTest.java
  test-poc/base/src/test/resources/logging.properties
  test-poc/framework/pom.xml
  test-poc/framework/src/main/java/org/keycloak/test/framework/KeycloakIntegrationTest.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/KeycloakIntegrationTestExtension.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/TestAdminClient.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/TestClient.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/TestRealm.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/admin/KeycloakAdminClientSupplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/injection/InstanceWrapper.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/injection/LifeCycle.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/injection/Registry.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/injection/Supplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/injection/SupplierHelpers.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/realm/ClientConfig.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/realm/ClientSupplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/realm/DefaultClientConfig.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/realm/DefaultRealmConfig.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/realm/RealmConfig.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/realm/RealmSupplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/server/DefaultKeycloakTestServerConfig.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/server/EmbeddedKeycloakTestServer.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/server/KeycloakTestServer.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/server/KeycloakTestServerConfig.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/server/KeycloakTestServerSupplier.java
  test-poc/framework/src/main/java/org/keycloak/test/framework/server/RemoteKeycloakTestServer.java
  test-poc/framework/src/main/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
  test-poc/framework/src/main/resources/META-INF/services/org.keycloak.test.framework.injection.Supplier
  test-poc/pom.xml
Labels: team/cloud-native, flaky-test

#29877 Fix: Added LDSigningServiceProvider entry for LD-Credentials/VCDM
  services/src/main/resources/META-INF/services/org.keycloak.protocol.oid4vc.issuance.signing.VCSigningServiceProviderFactory
Labels: flaky-test

#29344 #29266 Improve documentation on ClientRolemappingsRessource
  services/src/main/java/org/keycloak/services/resources/admin/ClientRoleMappingsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RoleMapperResource.java
Labels: flaky-test

#29819 Remove explicit flush from JPA user and client session handling
  model/jpa/src/main/java/org/keycloak/models/jpa/session/JpaUserSessionPersisterProvider.java
Labels: flaky-test

#29746 use authServerUrl when defined
  js/libs/ui-shared/src/context/KeycloakContext.tsx
Labels: team/ui

#29903 Remove Opera from supported web drivers
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/BrowserDriverUtil.java
Labels: area/testsuite, kind/eol, team/cloud-native, team/core-clients, team/core-iam

#29884 Upgrade old Keycloak version for DB migration tests
  .github/workflows/ci.yml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/migration-test/migration-realm-24.0.4.json
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29892 Ignore unused optional NPM dependencies
  package.json
  pnpm-lock.yaml
Labels: team/ui

#29685 Supporting OID4VCI AuthZCode flow:
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam
