Repository keycloak/keycloak, pull requests merged in 2024-09, with the labels that each got.

#32497 Unignore backchannel logout tests
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/stream/UserSessionPredicate.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractNestedBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/OidcBackchannelLogoutBrokerConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/BackchannelLogoutTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32524 document syslog app-name
  docs/guides/server/logging.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/LoggingOptions.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#32568 Upgrade PatternFly to latest version
  js/apps/account-ui/package.json
  js/apps/admin-ui/package.json
  pnpm-lock.yaml
Labels: team/ui, flaky-test

#32471 Make group filter case-insensitive
  js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx
Labels: team/ui

#32580 set login-otp autocomplete="one-time-code"
  themes/src/main/resources/theme/base/login/login-otp.ftl
Labels: team/ui, flaky-test

#32536 added fix for webauthn select
  themes/src/main/resources/theme/keycloak.v2/login/theme.properties
  themes/src/main/resources/theme/keycloak.v2/login/webauthn-authenticate.ftl
Labels: team/ui, flaky-test

#32608 Translations update from Hosted Weblate
  themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
Labels: team/ui, flaky-test

#32283 Update the welcome page to create a temporary admin user
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/WelcomePage.java
  themes/src/main/resources/theme/keycloak/welcome/index.ftl
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#32593 fix for finding execution by index
  js/apps/admin-ui/src/authentication/__tests__/ExecutionList.test.ts
  js/apps/admin-ui/src/authentication/execution-model.ts
Labels: team/ui

#32331 Add `didInitialize` to Keycloak typings
  js/libs/keycloak-js/dist/keycloak.d.ts
  js/libs/keycloak-js/src/keycloak.js
Labels: team/ui

#32414 added disable warning
  js/apps/admin-ui/cypress/e2e/users_enable_disable.spec.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/user/EditUser.tsx
Labels: team/ui

#32595 Trigger mass re-index of the sessions caches when the entity changes
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteInfinispanAuthenticationSessionProviderFactory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
Labels: team/cloud-native, flaky-test

#32587 Remove keycloak-core and keycloak-crypto-default from SAML galleon fe…
  adapters/saml/core/pom.xml
  adapters/saml/core/src/main/java/org/keycloak/adapters/saml/config/PemUtils.java
  adapters/saml/core/src/main/java/org/keycloak/adapters/saml/config/parsers/DeploymentBuilder.java
  core/pom.xml
  core/src/main/java/org/keycloak/jose/jwk/AbstractJWKParser.java
  core/src/main/java/org/keycloak/jose/jwk/JWKBuilder.java
  core/src/main/java/org/keycloak/jose/jwk/JWKParser.java
  core/src/main/java16/org/keycloak/jose/jwk/JWKBuilder.java
  core/src/main/java16/org/keycloak/jose/jwk/JWKParser.java
  crypto/default/pom.xml
  distribution/galleon-feature-packs/saml-adapter-galleon-pack/src/main/resources/modules/system/add-ons/keycloak/org/keycloak/keycloak-core/main/module.xml
  distribution/galleon-feature-packs/saml-adapter-galleon-pack/src/main/resources/modules/system/add-ons/keycloak/org/keycloak/keycloak-crypto-default/main/module.xml
  distribution/galleon-feature-packs/saml-adapter-galleon-pack/src/main/resources/modules/system/add-ons/keycloak/org/keycloak/keycloak-saml-adapter-core/main/module.xml
  services/src/test/java/org/keycloak/jose/jwk/ServerJWKTest.java
Labels: flaky-test

#31925 Add kc_action to redirect URI after a required action is cancelled (#31894)
  docs/documentation/server_admin/topics/users/con-aia.adoc
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  js/libs/keycloak-js/dist/keycloak.d.ts
  js/libs/keycloak-js/src/keycloak.js
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AbstractAppInitiatedActionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AbstractAppInitiatedActionUpdateEmailTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#32585 Binding brokering OIDC user sessions with the issuer of the ID Token to avoid looking up sessions by iterating over all brokers in a realm
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProviderConfig.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java
Labels: flaky-test

#32592 Remove version() projection from Ickle Queries
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/remote/updater/Updater.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/remote/updater/client/AuthenticatedClientSessionUpdater.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/remote/updater/loginfailures/LoginFailuresUpdater.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/remote/updater/user/UserSessionUpdater.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/query/ClientSessionQueries.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/query/UserSessionQueries.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/transaction/ClientSessionChangeLogTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/transaction/RemoteChangeLogTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/transaction/UserSessionChangeLogTransaction.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/InfinispanIckleQueryTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#29028 Introduce event types to update/remove credentials
  docs/documentation/release_notes/topics/26_0_0.adoc
  docs/documentation/server_admin/topics/admin-cli.adoc
  docs/documentation/server_admin/topics/events/login.adoc
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  js/apps/admin-ui/cypress/fixtures/partial-import-test-data/kcexport.json
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/add/__tests__/mock-serverinfo.json
  js/apps/admin-ui/src/context/server-info/__tests__/mock.json
  js/libs/keycloak-admin-client/src/defs/eventTypes.ts
  server-spi-private/src/main/java/org/keycloak/events/EventType.java
  services/src/main/java/org/keycloak/authentication/requiredactions/DeleteCredentialAction.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdatePassword.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateTotp.java
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnRegister.java
  services/src/main/java/org/keycloak/events/email/EmailEventListenerProviderFactory.java
  services/src/main/java/org/keycloak/services/resources/account/AccountCredentialResource.java
  services/src/main/java/org/keycloak/services/resources/account/Constants.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionDeleteCredentialTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionResetPasswordTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionTotpSetupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionMultipleActionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionPriorityTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionResetPasswordTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionTotpSetupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosStandaloneTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPProvidersIntegrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageOTPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LevelOfAssuranceFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/SSOTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnIdlessTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnRegisterAndLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/WebAuthnOtherSettingsTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/import/testrealm-keycloak-6146-error.json
  testsuite/integration-arquillian/tests/base/src/test/resources/import/testrealm-keycloak-6146.json
  themes/src/main/resources/theme/base/email/html/event-remove_credential.ftl
  themes/src/main/resources/theme/base/email/html/event-update_credential.ftl
  themes/src/main/resources/theme/base/email/messages/messages_en.properties
  themes/src/main/resources/theme/base/email/text/event-remove_credential.ftl
  themes/src/main/resources/theme/base/email/text/event-update_credential.ftl
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#32493 changed the size of the welcome logo
  themes/src/main/resources/theme/keycloak/welcome/index.ftl
  themes/src/main/resources/theme/keycloak/welcome/resources/css/welcome.css
Labels: team/ui, flaky-test

#32511 styling for username form added class to form tag
  themes/src/main/resources/theme/keycloak.v2/login/buttons.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-username.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login.ftl
  themes/src/main/resources/theme/keycloak.v2/login/theme.properties
Labels: team/ui, flaky-test

#32521 added some space on the required message
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
  themes/src/main/resources/theme/keycloak.v2/login/theme.properties
Labels: team/ui, flaky-test

#32572 added 'x' to clear value and fix required *
  js/apps/admin-ui/src/components/dynamic/ClientSelectComponent.tsx
  js/libs/ui-shared/src/controls/select-control/SingleSelectControl.tsx
  js/libs/ui-shared/src/controls/select-control/TypeaheadSelectControl.tsx
Labels: team/ui, flaky-test

#32487 fix: simplify / refine validation methods
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/BootstrapAdminPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ExportPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/FeaturePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ManagementPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ProxyPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TracingPropertyMappers.java
Labels: team/cloud-native, flaky-test

#32598 Deprecate old remote store
  common/src/main/java/org/keycloak/common/Profile.java
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
Labels: team/cloud-native, flaky-test

#32616 Avoid iterating through all mappers when running the config event lis…
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/InfinispanIdentityProviderStorageProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaIdentityProviderStorageProvider.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/AbstractConfigPropertySynchronizer.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/ConfigSyncEventListener.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/ConfigSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/GroupConfigPropertyByPathSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/RoleConfigPropertyByClientIdSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/RoleConfigPropertyByRoleNameSynchronizer.java
  server-spi/src/main/java/org/keycloak/models/IdentityProviderStorageProvider.java
  testsuite/integration-arquillian/tests/base/testsuites/database-suite
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32534 Show details for error messages where they were missing
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_pl.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_CN.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/client-scopes/ClientScopesSection.tsx
  js/apps/admin-ui/src/clients/authorization/AuthorizationExport.tsx
  js/apps/admin-ui/src/identity-providers/add/AddMapper.tsx
  js/apps/admin-ui/src/realm-settings/ClientProfileForm.tsx
  js/apps/admin-ui/src/realm-settings/LoginTab.tsx
  js/apps/admin-ui/src/realm-settings/NewClientPolicy.tsx
  js/apps/admin-ui/src/realm-settings/PoliciesTab.tsx
  js/apps/admin-ui/src/realm-settings/ProfilesTab.tsx
  js/apps/admin-ui/src/realm-settings/localization/RealmOverrides.tsx
  js/apps/admin-ui/src/sessions/RevocationModal.tsx
  server-spi-private/src/main/java/org/keycloak/email/EmailException.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java
  services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/FlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/error/UncaughtErrorPageTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#28312 Add information about token expiry to events
  server-spi-private/src/main/java/org/keycloak/events/Details.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
Labels: flaky-test

#32652 fix: mark slf4j as not optional for the operator
  operator/pom.xml
Labels: team/cloud-native, flaky-test

#32646 Remove adapter and misc boms
  boms/adapter/pom.xml
  boms/misc/pom.xml
  boms/pom.xml
Labels: flaky-test

#32347 Lightweight access tokens for Admin REST API
  docs/documentation/release_notes/topics/26_0_0.adoc
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo26_0_0.java
  services/src/main/java/org/keycloak/authorization/common/KeycloakIdentity.java
  services/src/main/java/org/keycloak/services/clientregistration/ClientRegistrationAuth.java
  services/src/main/java/org/keycloak/services/managers/RealmManager.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/AssertAdminEvents.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32661 some more ui fixes
  themes/src/main/resources/theme/keycloak.v2/login/buttons.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-config-totp.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-password.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-recovery-authn-code-config.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-recovery-authn-code-input.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-update-password.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-username.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login.ftl
  themes/src/main/resources/theme/keycloak.v2/login/register.ftl
  themes/src/main/resources/theme/keycloak.v2/login/resources/css/styles.css
  themes/src/main/resources/theme/keycloak.v2/login/select-authenticator.ftl
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
  themes/src/main/resources/theme/keycloak.v2/login/theme.properties
  themes/src/main/resources/theme/keycloak.v2/login/webauthn-authenticate.ftl
Labels: team/ui, flaky-test

#32649 Avoid NPE if realm configuration contains invalid required action configuration
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AuthenticationManagementResource.java
Labels: area/admin/api, team/ui, flaky-test, kind/regression

#32467 [quarkus-next] Align dependency versions before build
  .github/scripts/prepare-quarkus-next.sh
  quarkus/set-quarkus-version.sh
Labels: team/cloud-native, flaky-test

#32670 Handle ClientData parsing errors in SessionCodeChecks gracefully (#32515)
  server-spi-private/src/main/java/org/keycloak/protocol/ClientData.java
  server-spi-private/src/test/java/org/keycloak/broker/provider/util/IdentityBrokerStateTest.java
  services/src/main/java/org/keycloak/services/resources/SessionCodeChecks.java
Labels: flaky-test

#32666 Avoid releasing keycloak-authz-client-test artifact to maven reposito…
  authz/client/pom.xml
Labels: flaky-test

#32684 Optimize LogoutEndpoint.backchannelLogout endpoint
  services/src/main/java/org/keycloak/protocol/oidc/LogoutTokenValidationCode.java
  services/src/main/java/org/keycloak/protocol/oidc/LogoutTokenValidationContext.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java
Labels: flaky-test

#32667 Improve message for failing partial import of realm
  services/src/main/java/org/keycloak/partialimport/AbstractPartialImport.java
  services/src/main/java/org/keycloak/partialimport/ClientRolesPartialImport.java
  services/src/main/java/org/keycloak/partialimport/ErrorResponseException.java
  services/src/main/java/org/keycloak/partialimport/PartialImport.java
  services/src/main/java/org/keycloak/partialimport/PartialImportManager.java
  services/src/main/java/org/keycloak/partialimport/RolesPartialImport.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
Labels: flaky-test

#32665 Drop redundant index on client sessions
  model/jpa/src/main/resources/META-INF/jpa-changelog-26.0.0.xml
Labels: flaky-test

#32699 Fix parsing of broker user ID if it contains a dot
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java
Labels: flaky-test

#32316 Syslog: add necessary options to cover the major usability
  docs/guides/server/logging.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/LoggingOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/Configuration.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/LoggingConfigurationTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#32576 some italian translation
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_it.properties
Labels: team/ui, flaky-test

#32659 fix: refining v2 hostname validation
  services/src/main/java/org/keycloak/url/HostnameV2ProviderFactory.java
  services/src/test/java/org/keycloak/url/HostnameV2ProviderFactoryTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/url/HostnameV2Test.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32710 Fix ResetPasswordTest on chrome 128
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPage.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32660 Removing the extra two-minute Window for persistent user sessions
  docs/documentation/server_admin/topics/sessions/timeouts.adoc
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletSessionTimeoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32695 Set idle time the same as for the internal cache, but extend it for refreshes
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserLoginFailureProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java
Labels: flaky-test

#32656 Add caching when querying brokers by organization
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/IdentityProviderListQuery.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/InfinispanIdentityProviderStorageProvider.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/InfinispanOrganizationProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/cache/OrganizationCacheTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32412 changed to use serverBaseUrl instead
  js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
Labels: team/ui

#32642 Use help icon instead of help
  js/apps/admin-ui/src/components/dynamic/StringComponent.tsx
Labels: team/ui

#32735 Check refresh token flow response for offline based on refresh token request parameter
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExtendedEventTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#32398 Removing BOM character from SAML entity descriptor
  saml-core/src/main/java/org/keycloak/saml/processing/core/saml/v2/util/SAMLMetadataUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/admin-test/saml-idp-metadata_utf8_bom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32589 Include `rfc4648` in the import map for login v2
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
Labels: team/ui, flaky-test

#32733 Set idle time the same as for the internal cache, but extend it for refreshes
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserLoginFailureProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java
Labels: flaky-test

#32342 backport: better parsing of value and default value (#31110)
  js/apps/admin-ui/src/components/multi-line-input/MultiLineInput.tsx
Labels: team/ui

#32226 added dark mode to login theme
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
Labels: team/cloud-native, team/ui, flaky-test

#32625 Add a PasswordPoliciesBean to the FreeMarker context.
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/forms/login/freemarker/model/PasswordPoliciesBean.java
Labels: flaky-test

#32687 Propagate locale when using app initiated registration URL
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedRegistrationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32680 small fix to create project
  js/apps/create-keycloak-theme/create.js
  js/apps/create-keycloak-theme/templates/maven-resources/theme/my-account/account/index.ftl.mu
  js/apps/create-keycloak-theme/templates/pom.xml.mu
Labels: team/ui

#32631 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
Labels: team/ui, flaky-test

#32762 keep query parameters when changing routes
  js/apps/account-ui/src/root/PageNav.tsx
Labels: team/ui, flaky-test

#32783 Exclude `@noble/hashes` from Keycloak JS distribution
  js/libs/keycloak-js/rollup.config.ts
Labels: team/ui

#32738 Search Identity Providers by alias or display name
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaIdentityProviderStorageProvider.java
  server-spi/src/main/java/org/keycloak/models/IdentityProviderModel.java
  services/src/main/java/org/keycloak/services/resources/account/LinkedAccountsResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/LinkedAccountsRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32345 Allow brute force to have http request/response and send emails
  server-spi-private/src/main/java/org/keycloak/services/managers/BruteForceProtector.java
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
  services/src/main/java/org/keycloak/events/email/EmailEventListenerProviderFactory.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/managers/DefaultBlockingBruteForceProtector.java
  services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/client/resources/TestingResource.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/updaters/RealmAttributeUpdater.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AssertEvents.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
  themes/src/main/resources/theme/base/email/html/event-user_disabled_by_permanent_lockout.ftl
  themes/src/main/resources/theme/base/email/html/event-user_disabled_by_temporary_lockout.ftl
  themes/src/main/resources/theme/base/email/messages/messages_en.properties
  themes/src/main/resources/theme/base/email/text/event-user_disabled_by_permanent_lockout.ftl
  themes/src/main/resources/theme/base/email/text/event-user_disabled_by_temporary_lockout.ftl
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#32792 Remove @NoCache annotation in admin client interfaces
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientTypesResource.java
Labels: flaky-test

#32797 Ensure latest dependencies are installed before running pre-commit hook
  js/.husky/pre-commit
Labels: team/ui

#32727 Remove leftover code in login-passkeys-conditional-authenticate.ftl
  themes/src/main/resources/theme/base/login/login-passkeys-conditional-authenticate.ftl
Labels: team/ui, flaky-test

#32491 Add instructions for developing web UI
  js/apps/keycloak-server/README.md
Labels: team/ui, flaky-test

#32795 Remove @NoCache annotation in admin client interfaces
  integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/ClientTypesResource.java
Labels: flaky-test

#32813 Ensure realm attributes import happens before client import
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/ImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/model/acr-values-import-bug.json
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam, backport/25.0

#32809 fix: refining v2 hostname validation (#32659)
  services/src/main/java/org/keycloak/url/HostnameV2ProviderFactory.java
  services/src/test/java/org/keycloak/url/HostnameV2ProviderFactoryTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/url/HostnameV2Test.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32708 added more style fixes for the login.v2
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/login/DeleteAccountActionConfirmPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/login/LoginActions.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/login/OAuthGrant.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/login/OneTimeCode.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/page/LoginPasswordUpdatePage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPasswordResetPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPasswordUpdatePage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginTotpPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/OAuthGrantPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/saml/RequiredConsentBuilder.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BrowserFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
  themes/src/main/resources/theme/keycloak.v2/login/buttons.ftl
  themes/src/main/resources/theme/keycloak.v2/login/code.ftl
  themes/src/main/resources/theme/keycloak.v2/login/delete-account-confirm.ftl
  themes/src/main/resources/theme/keycloak.v2/login/delete-credential.ftl
  themes/src/main/resources/theme/keycloak.v2/login/field.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-oauth-grant.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-otp.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-reset-password.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-update-password.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-username.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login.ftl
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
  themes/src/main/resources/theme/keycloak.v2/login/terms.ftl
  themes/src/main/resources/theme/keycloak.v2/login/theme.properties
  themes/src/main/resources/theme/keycloak.v2/login/user-profile-commons.ftl
  themes/src/main/resources/theme/keycloak.v2/login/webauthn-register.ftl
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#32763 Remove `keycloak-test-helper` module
  misc/.travis/after.sh
  misc/keycloak-test-helper/pom.xml
  misc/keycloak-test-helper/src/main/java/org/keycloak/test/FluentTestsHelper.java
  misc/keycloak-test-helper/src/main/java/org/keycloak/test/TestsHelper.java
  misc/keycloak-test-helper/src/main/java/org/keycloak/test/builders/ClientBuilder.java
  misc/keycloak-test-helper/src/main/java/org/keycloak/test/builders/UserBuilder.java
  misc/keycloak-test-helper/src/main/java/org/keycloak/test/page/IndexPage.java
  misc/keycloak-test-helper/src/main/java/org/keycloak/test/page/LoginPage.java
  misc/keycloak-test-helper/src/main/java/org/keycloak/test/page/ProfilePage.java
  misc/log/LogTrimmer.java
  misc/logo/README.md
  misc/pom.xml
  pom.xml
Labels: flaky-test

#32814 Ensure realm attributes import happens before client import
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/ImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/model/acr-values-import-bug.json
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32825 Remove references of statically served Keycloak JS from documentation
  docs/documentation/authorization_services/topics/enforcer-js-adapter.adoc
  docs/documentation/server_admin/topics/identity-broker/suggested.adoc
  docs/documentation/upgrading/topics/upgrade_adapters.adoc
  docs/guides/securing-apps/javascript-adapter.adoc
  docs/guides/server/reverseproxy.adoc
Labels: team/cloud-native

#32831 Fix auto-complete and auto-focus for login v2 theme
  themes/src/main/resources/theme/base/login/register.ftl
  themes/src/main/resources/theme/keycloak.v2/login/field.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-otp.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-password.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-recovery-authn-code-input.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-reset-password.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-update-password.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-username.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login.ftl
  themes/src/main/resources/theme/keycloak.v2/login/register.ftl
Labels: team/ui, flaky-test

#32846 added client side check for trivial password policies
  themes/src/main/resources/theme/keycloak.v2/login/field.ftl
  themes/src/main/resources/theme/keycloak.v2/login/register.ftl
  themes/src/main/resources/theme/keycloak.v2/login/resources/js/password-policy.js
Labels: team/ui, flaky-test

#32872 Do not automatically re-import users if they already exist locally wh…
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPSearchForUsersPaginationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32715 Add a reload period for https material
  docs/documentation/release_notes/topics/26_0_0.adoc
  docs/guides/server/enabletls.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HttpDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#32555 Remove crd-generator-apt from operator
  operator/pom.xml
  pom.xml
Labels: team/cloud-native, flaky-test

#32779 Possibility to separately specify log levels for log handlers - basic
  docs/documentation/release_notes/topics/26_0_0.adoc
  docs/guides/server/logging.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/LoggingOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/LoggingConfigurationTest.java
  quarkus/runtime/src/test/resources/META-INF/keycloak.conf
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/OptionsDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesAutoBuildDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#32887 Do not automatically re-import users if they already exist locally when searching by attributes
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPSearchForUsersPaginationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#32886 Do not automatically re-import users if they already exist locally when searching by attributes
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPSearchForUsersPaginationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32597 Rename remote-cache Feature
  .github/workflows/ci.yml
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/main/java/org/keycloak/common/util/MultiSiteUtils.java
  core/src/main/java/org/keycloak/TokenVerifier.java
  model/infinispan/src/main/java/org/keycloak/infinispan/util/InfinispanUtils.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/infinispan/CacheManagerFactory.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/ExternalInfinispanTest.java
  server-spi-private/src/main/java/org/keycloak/cluster/ManagedCacheManagerProvider.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/session/LastSessionRefreshUnitTest.java
  testsuite/integration-arquillian/tests/base/testsuites/clusterless-suite
  testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/EmbeddedInfinispanSplitBrainTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/infinispan/FeatureEnabledTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32861 removed tabindex so that the natural is used
  themes/src/main/resources/theme/keycloak.v2/login/field.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-password.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-username.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login.ftl
  themes/src/main/resources/theme/keycloak.v2/login/webauthn-authenticate.ftl
Labels: team/ui, flaky-test

#32903 Script component was getting an array instead of a value
  js/apps/admin-ui/src/components/dynamic/ScriptComponent.tsx
  js/apps/admin-ui/src/page/PageHandler.tsx
Labels: team/ui

#32908 added table wrap to avoid data off screen
  js/apps/admin-ui/src/clients/authorization/Resources.tsx
Labels: team/ui

#32929 Fix a few typos
  services/src/main/java/org/keycloak/userprofile/config/UPConfigUtils.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/examples/providersoverride/CustomLoginFormsProviderFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/examples/providersoverride/CustomValidateUsername.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#32900 Honor turnOffChangeSessionIdOnLogin in SAML adapter
  adapters/saml/wildfly-elytron/src/main/java/org/keycloak/adapters/saml/elytron/ElytronSamlSessionStore.java
  testsuite/integration-arquillian/test-apps/servlets/src/main/java/org/keycloak/testsuite/adapter/servlet/InputServlet.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32858 Admin API with Lightweight access token and transient session
  services/src/main/java/org/keycloak/authorization/common/KeycloakIdentity.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32898 Improve error message when wrong KC profile is set
  common/src/main/java/org/keycloak/common/profile/PropertiesProfileConfigResolver.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
Labels: flaky-test

#32671 Propagate admin action lifespan to ResetCredentialDialog (#32547)
  js/apps/admin-ui/src/user/user-credentials/LifespanField.tsx
  js/apps/admin-ui/src/user/user-credentials/ResetCredentialDialog.tsx
Labels: team/ui

#32964 use users realm to edit admin user
  js/apps/admin-ui/src/realm-settings/EmailTab.tsx
  js/apps/admin-ui/src/utils/useCurrentUser.ts
Labels: team/ui

#32954 refresh realm after being changed
  js/apps/admin-ui/src/realm-settings/event-config/EventsTab.tsx
Labels: team/ui

#32822 Return 404 on invalid theme type
  services/src/main/java/org/keycloak/services/resources/ThemeResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/theme/ThemeResourceProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32980 Javadoc for the admin-client methods for the endpoints and parameters…
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/AuthenticationManagementResource.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientPoliciesPoliciesResource.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientTypesResource.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/GroupResource.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/IdentityProvidersResource.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationMemberResource.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationMembersResource.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationsResource.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/RealmResource.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/RoleResource.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/UserResource.java
Labels: flaky-test

#32855 Allowing maxAge=0 value to be forwarded in the url.
  js/libs/keycloak-js/src/keycloak.js
Labels: team/ui

#32969 Show OpenID4VCI Credential Issuer Metadata link in admin ui
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
  js/apps/admin-ui/src/utils/useIsFeatureEnabled.ts
Labels: team/ui

#33014 Update bootstrap admin client to use lightweight access token, and di…
  services/src/main/java/org/keycloak/services/managers/ApplianceBootstrap.java
Labels: flaky-test

#32999 Sort the IDPs in the admin console admin and organization tables by a…
  js/apps/admin-ui/src/identity-providers/IdentityProvidersSection.tsx
  js/apps/admin-ui/src/organizations/IdentityProviders.tsx
Labels: team/ui

#32928 Allow URIs without a hostname in KeycloakUriBuilder
  common/src/main/java/org/keycloak/common/util/KeycloakUriBuilder.java
  common/src/test/java/org/keycloak/common/util/KeycloakUriBuilderTest.java
Labels: flaky-test

#33002 Remove unnecessary AbstractConfigPropertySynchronizer class
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/AbstractConfigPropertySynchronizer.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/ConfigSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/GroupConfigPropertyByPathSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/RoleConfigPropertyByClientIdSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/RoleConfigPropertyByRoleNameSynchronizer.java
Labels: flaky-test

#32918 Add cache for IdentityProviderStorageProvider.getForLogin
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/InfinispanIdentityProviderStorageProvider.java
  server-spi/src/main/java/org/keycloak/models/IdentityProviderStorageProvider.java
  services/src/main/java/org/keycloak/organization/forms/login/freemarker/model/OrganizationAwareIdentityProviderBean.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/cache/OrganizationCacheTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#33022 Remove deprecated `setOrCreateChild()` method from Admin Client
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  js/libs/keycloak-admin-client/src/resources/groups.ts
  js/libs/keycloak-admin-client/test/groups.spec.ts
Labels: team/ui

#33016 Improve FolderThemeProvider
  services/src/main/java/org/keycloak/theme/FolderThemeProvider.java
Labels: flaky-test

#32404 Make the Organizations a default feature
  common/src/main/java/org/keycloak/common/Profile.java
  docs/documentation/release_notes/topics/26_0_0.adoc
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/ExecutionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/FlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/InitialFlowsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/ProvidersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/AuthenticationSessionProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/CompositeRolesModelTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/ConcurrentTransactionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/CredentialModelTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/MultipleRealmsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserConsentModelTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserConsentWithUserStorageModelTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserSessionProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AbstractWellKnownProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/account/OrganizationAccountTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationGroupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationThemeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationBruteForceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authz/OrganizationAdminPermissionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/OrganizationIdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/OrganizationOIDCBrokerSelfRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/OrganizationSAMLBrokerSelfRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/cache/OrganizationCacheTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/exportimport/OrganizationEnabledExportImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/exportimport/OrganizationExportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationOIDCProtocolMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationSAMLProtocolMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/member/OrganizationMemberTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/Infinispan.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/Jpa.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/SessionTimeoutsTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionConcurrencyTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionInitializerTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionPersisterProviderTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderModelTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderOfflineModelTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32893 Avoid using plain log messages in ServiceLogger
  services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpUsernamePasswordForm.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/UsernamePasswordForm.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/X509ClientAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/x509/AbstractX509ClientCertificateAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/x509/AbstractX509ClientCertificateAuthenticatorFactory.java
  services/src/main/java/org/keycloak/authentication/authenticators/x509/CertificateValidator.java
  services/src/main/java/org/keycloak/authentication/authenticators/x509/ValidateX509CertificateUsername.java
  services/src/main/java/org/keycloak/authentication/authenticators/x509/X509ClientCertificateAuthenticator.java
Labels: flaky-test

#32853 Sort order of updates for user properties
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/LDAPMappersComparator.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaIdentityProviderStorageProvider.java
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultUserProfile.java
  services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpCreateUserIfUniqueAuthenticator.java
  services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
Labels: flaky-test

#33035 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_de.properties
Labels: team/ui, flaky-test

#32866 added username field like suggested in issue comment
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LanguageComboboxAwarePage.java
  themes/src/main/resources/theme/keycloak.v2/login/field.ftl
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
  themes/src/main/resources/theme/keycloak.v2/login/theme.properties
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#32894 Implement invitation-only self-registration for realm users
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/OrganizationAdapter.java
  server-spi/src/main/java/org/keycloak/models/KeycloakContext.java
  services/src/main/java/org/keycloak/authentication/actiontoken/ActionTokenHandler.java
  services/src/main/java/org/keycloak/authentication/actiontoken/inviteorg/InviteOrgActionTokenHandler.java
  services/src/main/java/org/keycloak/authentication/forms/RegistrationPage.java
  services/src/main/java/org/keycloak/authentication/forms/RegistrationUserCreation.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationInvitationResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationsResource.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolService.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  services/src/main/java/org/keycloak/services/DefaultKeycloakContext.java
  services/src/main/java/org/keycloak/services/ErrorPageException.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/updaters/RealmAttributeUpdater.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32868 Redirect to relative-path from the root path
  docs/documentation/release_notes/topics/26_0_0.adoc
  docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc
  docs/guides/migration/migrating-to-quarkus.adoc
  docs/guides/server/management-interface.adoc
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/deployment/src/test/java/test/org/keycloak/quarkus/services/health/KeycloakPathConfigurationTest.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakRecorder.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ManagementDistTest.java
Labels: team/cloud-native, flaky-test

#33086 Action expired error occurs when accessing regular registration page …
  .github/workflows/operator-ci.yml
  js/apps/admin-ui/cypress/e2e/authentication_test.spec.ts
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/ArtifactResolutionService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/saml/ArtifactBindingWithResolutionServiceTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#33118 Disable broken operator test instead of entire suite
  .github/workflows/operator-ci.yml
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
Labels: team/cloud-native

#33119 fix: include debug logging for init
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LoginStatusIframeEndpoint.java
Labels: flaky-test

#33134 Make `QuarkusLiquibaseConnectionProvider` extending `DefaultLiquibase`…
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/CacheBuildSteps.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakRecorder.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaConnectionProviderFactory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/liquibase/QuarkusJpaUpdaterProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/liquibase/QuarkusJpaUpdaterProviderFactory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/liquibase/QuarkusLiquibaseConnectionProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/CacheManagerFactory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/QuarkusCacheManagerProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/QuarkusInfinispanConnectionFactory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/liquibase/QuarkusLiquibaseConnectionProvider.java
  quarkus/runtime/src/main/resources/META-INF/services/org.keycloak.cluster.ManagedCacheManagerProvider
  quarkus/runtime/src/main/resources/META-INF/services/org.keycloak.connections.infinispan.InfinispanConnectionProviderFactory
  quarkus/runtime/src/main/resources/META-INF/services/org.keycloak.connections.jpa.JpaConnectionProviderFactory
  quarkus/runtime/src/main/resources/META-INF/services/org.keycloak.connections.jpa.updater.JpaUpdaterProviderFactory
  quarkus/runtime/src/main/resources/META-INF/services/org.keycloak.connections.jpa.updater.liquibase.conn.LiquibaseConnectionProviderFactory
Labels: team/cloud-native, flaky-test

#33061 Set realm when importing users via keycloak-add-user.json
  services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java
Labels: flaky-test

#33101 Remove iframe version detection from Keycloak JS
  js/libs/keycloak-js/src/keycloak.js
Labels: team/ui

#32668 Remove the kc.org.broker.public attribute and use hideOnLogin in the …
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/organizations/IdentityProviderSelect.tsx
  js/apps/admin-ui/src/organizations/IdentityProviders.tsx
  js/apps/admin-ui/src/organizations/LinkIdentityProviderModal.tsx
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate26_0_0_IdentityProviderAttributesMigration.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaIdentityProviderStorageProvider.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  server-spi/src/main/java/org/keycloak/models/IdentityProviderModel.java
  server-spi/src/main/java/org/keycloak/models/IdentityProviderStorageProvider.java
  server-spi/src/main/java/org/keycloak/models/OrganizationModel.java
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProviderConfig.java
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProviderFactory.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/forms/login/freemarker/model/OrganizationAwareIdentityProviderBean.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/AbstractBrokerSelfRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/BrokerConfigurationWrapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/OrganizationIdentityProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/cache/OrganizationCacheTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationOIDCProtocolMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/member/OrganizationMemberTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#33121 Send UserRemovedEvent containing all user attributes
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserSessionProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#33142 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ka.properties
Labels: team/ui

#33136 Downgrade Java for client libraries to 8
  .github/workflows/ci.yml
  authz/client/pom.xml
  common/pom.xml
  common/src/main/java/org/keycloak/common/util/reflections/Reflections.java
  common/src/main/java/org/keycloak/common/util/reflections/SetAccessiblePrivilegedAction.java
  common/src/main/java/org/keycloak/common/util/reflections/UnSetAccessiblePrivilegedAction.java
  core/pom.xml
  core/src/main/java/org/keycloak/jose/jwk/JWKBuilder.java
  core/src/main/java/org/keycloak/jose/jwk/JWKParser.java
  core/src/main/java/org/keycloak/sdjwt/IssuerSignedJWT.java
  core/src/main/java/org/keycloak/sdjwt/SdJwtUtils.java
  core/src/main/java/org/keycloak/sdjwt/SdJwtVerificationContext.java
  core/src/main/java16/org/keycloak/jose/jwk/JWKBuilder.java
  core/src/main/java16/org/keycloak/jose/jwk/JWKParser.java
  core/src/test/java/org/keycloak/RSAVerifierTest.java
  core/src/test/java/org/keycloak/sdjwt/SdJwsTest.java
  core/src/test/java/org/keycloak/sdjwt/SdJwtVerificationTest.java
  core/src/test/java/org/keycloak/sdjwt/sdjwtvp/SdJwtVPVerificationTest.java
  integration/admin-client/pom.xml
Labels: flaky-test

#33056 BACKPORT: Avoid NPE if realm configuration contains invalid required action configuration (#32649)
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AuthenticationManagementResource.java
Labels: team/ui, flaky-test

#31771 Bugfix: "User Profile" attributes not available for Users Attribute search
  js/apps/admin-ui/cypress/e2e/client_scopes_test.spec.ts
  js/apps/admin-ui/cypress/e2e/users_attribute_search_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/ListingPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/components/PageObject.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/events/tabs/AdminEventsTab.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/events/tabs/UserEventsTab.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/UsersListingPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/UsersPage.ts
  js/apps/admin-ui/cypress/support/util/AdminClient.ts
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
  js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx
  js/apps/admin-ui/src/components/users/UserDataTableToolbarItems.tsx
  js/apps/admin-ui/src/context/auth/admin-ui-endpoint.ts
  js/apps/admin-ui/src/context/auth/uiRealmInfo.ts
  js/apps/admin-ui/src/user/details/SearchFilter.tsx
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UIRealmResource.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/model/UIRealmInfo.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UIRealmResourceTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#33120 Client Details: show redirect URIs w/ implicit flow
  js/apps/admin-ui/src/clients/add/LoginSettings.tsx
Labels: team/ui

#33114 Improve response time when displaying group members using LDAP Provider
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  js/apps/admin-ui/src/groups/Members.tsx
  js/libs/keycloak-admin-client/src/resources/groups.ts
Labels: team/ui, flaky-test

#33063 BACKPORT: add error to the console for debugging (#33041)
  js/apps/admin-ui/src/utils/useFetch.ts
Labels: team/ui

#32965 BACKPORT: added table wrap to avoid data off screen (#32908)
  js/apps/admin-ui/src/clients/authorization/Resources.tsx
Labels: team/ui

#33081 Sort the IDPs in the admin console admin and organization tables by a…
  js/apps/admin-ui/src/identity-providers/IdentityProvidersSection.tsx
Labels: team/ui

#32983 BACKPORT: refresh realm after being changed (#32954)
  js/apps/admin-ui/src/realm-settings/event-config/EventsTab.tsx
Labels: team/ui

#33048 Fix amr test
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AuthenticationMethodReferenceTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#33151 BACKPORT: Send UserRemovedEvent containing all user attributes
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserSessionProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#33083 Remove statically served Keycloak JS from the server
  common/src/main/java/org/keycloak/common/Profile.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  services/src/main/java/org/keycloak/services/resources/JsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java
  services/src/test/java/org/keycloak/services/resteasy/ResteasyKeycloakApplication.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/theme/ThemeResourceProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#32985 removed server side translation in favour of client side
  js/apps/account-ui/src/applications/Applications.tsx
  services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
Labels: team/ui, flaky-test

#33019 Fixed the types of Andreas original
  js/apps/account-ui/src/account-security/LinkedAccounts.tsx
  js/apps/account-ui/src/account-security/LinkedAccountsToolbar.tsx
  js/apps/account-ui/src/api/methods.ts
Labels: team/ui, flaky-test

#33178 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
Labels: team/ui

#33161 Add subgroup count to groupByPath
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
Labels: flaky-test

#33150 BACKPORT: Client Details: show redirect URIs w/ implicit flow (#33120)
  js/apps/admin-ui/src/clients/add/LoginSettings.tsx
Labels: team/ui

#33189 Improve handling for loopback redirect-uri validation (#195)
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  services/src/main/java/org/keycloak/protocol/oidc/utils/RedirectUtils.java
  services/src/test/java/org/keycloak/protocol/oidc/utils/RedirectUtilsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthRedirectUriTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#33190 Use references to obtain the signed elements in a signature (#188)
  saml-core/src/main/java/org/keycloak/saml/processing/core/saml/v2/util/AssertionUtil.java
  saml-core/src/main/java/org/keycloak/saml/processing/core/util/XMLSignatureUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SamlSignatureTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32988 Expand CodeQL coverage to all JavaScript and TypeScript
  .github/actions/conditional/action.yml
  .github/actions/conditional/conditions
  .github/workflows/codeql-analysis.yml
Labels: flaky-test

#33075 fix: Update fr community translation for account/ui
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_fr.properties
Labels: team/ui, flaky-test

#33196 Remove `keycloak-js-adapter-jar` artifact
  adapters/oidc/js/pom.xml
  adapters/oidc/pom.xml
  adapters/pom.xml
  dependencies/server-min/pom.xml
  pom.xml
  quarkus/runtime/pom.xml
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/pom.xml
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#33211 fix: expanding more on proxy-headers and hostname concerns
  docs/guides/server/hostname.adoc
  docs/guides/server/reverseproxy.adoc
Labels: team/cloud-native

#33145 Fix UserStorageManager.getGroupMembersStream potentially fetching all users
  model/storage-private/src/main/java/org/keycloak/storage/UserStorageManager.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/UserPropertyFileStorage.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#33070 Sort the IDPs in the admin console admin and organization tables by alias (#32999)
  js/apps/admin-ui/src/identity-providers/IdentityProvidersSection.tsx
  js/apps/admin-ui/src/organizations/IdentityProviders.tsx
Labels: team/ui

#32977 Resolve disabled options even at fast startup (#32245)
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java
Labels: team/cloud-native, flaky-test

#33237 revert part of change (#31055)
  js/apps/admin-ui/src/utils/client-url.test.ts
  js/apps/admin-ui/src/utils/client-url.ts
Labels: team/ui

#32883 Add status option to kcadm for validity checking
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/ConfigCredentialsCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/common/BaseConfigCredentialsCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/util/AuthUtil.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#33059 Run model tests with clusterless feature enabled
  testsuite/model/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#32911 Allow Embedded Cache sizes to be configured via the CLI
  docs/documentation/release_notes/topics/26_0_0.adoc
  docs/guides/server/caching.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/CachingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/CacheManagerFactory.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/tests/integration/src/test-providers/java/org/keycloak/it/resource/realm/TestRealmResource.java
  quarkus/tests/integration/src/test-providers/java/org/keycloak/it/resource/realm/TestRealmResourceFactory.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigKeepAliveDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#33155 Update Catalan translation.
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ca.properties
Labels: team/ui, flaky-test

#33167 Log model migration on INFO level
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultMigrationManager.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam
