Repository keycloak/keycloak, pull requests merged in 2025-09, with the labels that each got.

#42163 Check manage-account-links role for client initiated account linking
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerIdpLinkActionTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42181 Cache UserAgent parsing result
  services/pom.xml
  services/src/main/java/org/keycloak/device/DeviceRepresentationProviderFactoryImpl.java
  services/src/main/java/org/keycloak/device/DeviceRepresentationProviderImpl.java
Labels: flaky-test

#42140 Configure topology information in Infinispan
  docs/guides/high-availability/single-cluster/concepts.adoc
  docs/guides/server/caching.adoc
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/DefaultCacheEmbeddedConfigProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/JGroupsConfigurator.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/main/java/org/keycloak/operator/update/impl/BaseUpgradeLogic.java
Labels: team/cloud-native, flaky-test, team/sre

#42135 Disable peristent user session batching
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/JpaChangesPerformer.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/PersistentSessionsChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/PersistentSessionsWorker.java
Labels: flaky-test, team/sre

#42179 Show length validations in the admin UI
  js/libs/ui-shared/src/user-profile/utils.ts
Labels: team/ui

#42229 Experimental federated client authentication
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/main/java/org/keycloak/common/crypto/CryptoIntegration.java
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/identity-providers/add/AdvancedSettings.tsx
  js/apps/admin-ui/src/utils/useIsFeatureEnabled.ts
  server-spi-private/src/main/java/org/keycloak/broker/provider/ClientAssertionContext.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/ClientAssertionIdentityProvider.java
  server-spi-private/src/main/java/org/keycloak/models/utils/DefaultAuthenticationFlows.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/FederatedJWTClientAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProviderConfig.java
  services/src/main/resources/META-INF/services/org.keycloak.authentication.ClientAuthenticatorFactory
  test-framework/oauth/src/main/java/org/keycloak/testframework/oauth/OAuthIdentityProvider.java
  test-framework/oauth/src/main/java/org/keycloak/testframework/oauth/OAuthIdentityProviderSupplier.java
  test-framework/oauth/src/main/java/org/keycloak/testframework/oauth/OAuthTestFrameworkExtension.java
  test-framework/oauth/src/main/java/org/keycloak/testframework/oauth/annotations/InjectOAuthIdentityProvider.java
  tests/base/src/test/java/org/keycloak/tests/client/authentication/external/ClientAuthIdpServerConfig.java
  tests/base/src/test/java/org/keycloak/tests/client/authentication/external/FederatedClientAuthFromKeycloakTest.java
  tests/base/src/test/java/org/keycloak/tests/client/authentication/external/FederatedClientAuthTest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractHttpPostRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/Endpoints.java
Labels: team/ui

#42280 Retry duplicate exceptions to handle concurrent client sessions
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/PersistentSessionsChangelogBasedTransaction.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionConcurrencyTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, team/sre

#42240 fix: improve handling when expressions are disabled (#42189)
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Environment.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Build.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/ConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/DatasourcesConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/BuildCommandDistTest.java
Labels: team/cloud-native

#42253 Adding missing docs for 26.4 release notes
  docs/documentation/release_notes/topics/26_4_0.adoc
  docs/documentation/server_admin/topics/organizations/managing-organization.adoc
  docs/documentation/tests/src/test/java/org/keycloak/documentation/test/GuideTest.java
  docs/guides/high-availability/introduction.adoc
  docs/guides/high-availability/multi-cluster/concepts-memory-and-cpu-sizing.adoc
  docs/guides/high-availability/multi-cluster/introduction.adoc
  docs/guides/high-availability/single-cluster/concepts-threads.adoc
  docs/guides/high-availability/single-cluster/introduction.adoc
  docs/guides/observability/metrics-for-troubleshooting-clustering-and-network.adoc
  docs/guides/observability/metrics-for-troubleshooting-embedded-caches.adoc
  docs/guides/observability/metrics-for-troubleshooting-http.adoc
  docs/guides/server/logging.adoc
Labels: team/cloud-native, flaky-test, team/sre

#42299 Flaky realm role test
  js/apps/admin-ui/test/realm-roles/main.spec.ts
  js/apps/admin-ui/test/realm-roles/main.ts
Labels: team/ui

#41973 [OID4VCI]: Update OID4VCI error handling for draft 16 specification
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/ErrorType.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCJWTIssuerEndpointTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42003 [OID4VCI]: Enforce batch_size ≥ 2 validation for batch_credential_issuance
  server-spi-private/src/main/java/org/keycloak/constants/Oid4VciConstants.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerWellKnownProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerWellKnownProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#41440 Compliant with RFC8414, return server metadata at /.well-known/oauth-authorization-server/realms/{realm}
  services/src/main/java/org/keycloak/services/resources/RealmsResource.java
  services/src/main/java/org/keycloak/services/resources/ServerMetadataResource.java
  services/src/test/java/org/keycloak/services/resteasy/ResteasyKeycloakApplication.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RFC8414CompliantOAuth2WellKnownProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AbstractWellKnownProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42327 [Backport - 26.2] FIxing errors when building query conditions and resolution of members of a group
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/model/LDAPObject.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/UserRolesRetrieveStrategy.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#41771 fix: removing script logic for determining if a build is necessary
  quarkus/dist/src/main/content/bin/kc.bat
  quarkus/dist/src/main/content/bin/kc.sh
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Environment.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractStartCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractUpdatesCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Start.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PropertyMappingInterceptor.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
Labels: team/cloud-native, flaky-test

#41999 [OID4VCI]: Add DPoP nonce header support to OID4VCI nonce endpoint
  core/src/main/java/org/keycloak/OAuth2Constants.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java
  services/src/main/java/org/keycloak/services/util/DPoPUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/NonceEndpointTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42338 Show length validations in the admin UI
  js/libs/ui-shared/src/user-profile/utils.ts
Labels: team/ui

#42346 Lock the database before doing migrations
  model/jpa/src/main/java/org/keycloak/connections/jpa/DefaultJpaConnectionProviderFactory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaConnectionProviderFactory.java
Labels: team/cloud-native

#42353 fix: setting the built flag for embedded usage
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Environment.java
  quarkus/tests/junit5/src/main/java/org/keycloak/Keycloak.java
Labels: team/cloud-native

#42362 EdDSA support for DPoP
  core/src/main/java/org/keycloak/crypto/AsymmetricSignatureSignerContext.java
  core/src/main/java/org/keycloak/jose/jwk/ECPublicJWK.java
  core/src/main/java/org/keycloak/jose/jwk/JWK.java
  core/src/main/java/org/keycloak/jose/jwk/OKPPublicJWK.java
  core/src/main/java/org/keycloak/jose/jwk/RSAPublicJWK.java
  core/src/main/java/org/keycloak/util/DPoPGenerator.java
  core/src/main/java/org/keycloak/util/JWKSUtils.java
  core/src/main/java15/org/keycloak/jose/jwk/EdECUtilsImpl.java
  services/src/main/java/org/keycloak/keys/AbstractEddsaKeyProviderFactory.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/keybinding/AbstractProofValidator.java
  services/src/main/java/org/keycloak/services/util/DPoPUtil.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/KeyManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/DPoPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AbstractWellKnownProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ClientPoliciesUtil.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42379 Issue 42360 flaky ldap mapper test
  js/apps/admin-ui/test/user-federation/ldap-mapper.spec.ts
  js/apps/admin-ui/test/user-federation/ldap-mapper.ts
Labels: team/ui

#42218 fix: don't show the local access screen if a service account exists
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientsResource.java
  services/src/main/java/org/keycloak/services/managers/ApplianceBootstrap.java
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/PagesTest.java
  tests/base/src/test/java/org/keycloak/tests/welcomepage/WelcomePageTest.java
  tests/base/src/test/java/org/keycloak/tests/welcomepage/WelcomePageWithServiceAccountTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/url/HostnameV2Test.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42393 fix: allowing resolution of log color at build time
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
Labels: team/cloud-native

#41341 FAPI 2.0 Security Profile Final - Add FAPI 2.0 Final security profile as default profile of client policies
  docs/guides/securing-apps/partials/oidc/fapi-support.adoc
  services/src/main/resources/keycloak-default-client-profiles.json
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/AbstractFAPITest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPI1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPI2DPoPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPI2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExecutorTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42432 Use back keycloak-js instead of initiate login in the backend for account (26.3)
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/libs/ui-shared/src/context/ErrorPage.tsx
  js/libs/ui-shared/src/context/KeycloakContext.tsx
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountConsoleTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/TermsAndConditionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExecutorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/AccountConsoleTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#42443 Use back keycloak-js instead of initiate login in the backend for account (26.2)
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/libs/ui-shared/src/context/ErrorPage.tsx
  js/libs/ui-shared/src/context/KeycloakContext.tsx
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountConsoleTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/TermsAndConditionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExecutorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/AccountConsoleTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#42125 fix: moving multi-option validation to propertymappergrouping interface
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Messages.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ShortErrorMessageHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractAutoBuildCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractNonServerCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractUpdatesCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Export.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Import.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/OptimizedMixin.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Start.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/StartDev.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/BootstrapAdminPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/CachingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ClassLoaderPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ConfigKeystorePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/EventPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ExportPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/FeaturePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HealthPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpAccessLogPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ImportPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ManagementPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/MetricsPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapperGrouping.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ProxyPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/SecurityPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TracingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TransactionPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TruststorePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/VaultPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/BuildAndStartDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/BuildCommandDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FeaturesDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HelpCommandDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartAutoBuildDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/BasicDatabaseTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MariaDBDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MySQLDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/PostgreSQLDistTest.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/ServerOptions.java
Labels: team/cloud-native, flaky-test

#42434 Unbounded login_hint parameter Can Corrupt KC_RESTART Cookie
  docs/documentation/topics/templates/document-attributes.adoc
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCProviderConfig.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthzEndpointRequestParser.java
  test-framework/ui/src/main/java/org/keycloak/testframework/ui/page/LoginPage.java
  tests/base/src/test/java/org/keycloak/tests/forms/AuthzEndpointRequestParserCustomConfigTest.java
  tests/base/src/test/java/org/keycloak/tests/forms/AuthzEndpointRequestParserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/AuthzEndpointRequestParserTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42473 Unbounded login_hint parameter Can Corrupt KC_RESTART Cookie
  docs/documentation/topics/templates/document-attributes.adoc
  docs/documentation/upgrading/topics/changes/changes-26_2_9.adoc
  docs/documentation/upgrading/topics/changes/changes.adoc
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCProviderConfig.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthzEndpointRequestParser.java
  test-framework/ui/src/main/java/org/keycloak/testframework/ui/page/LoginPage.java
  tests/base/src/test/java/org/keycloak/tests/forms/AuthzEndpointRequestParserCustomConfigTest.java
  tests/base/src/test/java/org/keycloak/tests/forms/AuthzEndpointRequestParserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/AuthzEndpointRequestParserTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42489 Fix unstable user tests for admin console
  js/apps/admin-ui/test/clients/authorization.spec.ts
  js/apps/admin-ui/test/events/list.spec.ts
  js/apps/admin-ui/test/masthead/main.spec.ts
  js/apps/admin-ui/test/masthead/realm.spec.ts
  js/apps/admin-ui/test/realm-settings/i18n.spec.ts
  js/apps/admin-ui/test/support/testbed.ts
  js/apps/admin-ui/test/users/main.spec.ts
  js/apps/admin-ui/test/utils/AdminClient.ts
  js/apps/admin-ui/test/utils/login.ts
Labels: team/ui

#42435 Document tested and supported configurations for single-cluster deployments
  docs/documentation/upgrading/topics/intro.adoc
  docs/guides/high-availability/introduction.adoc
  docs/guides/high-availability/multi-cluster/deploy-keycloak-kubernetes.adoc
  docs/guides/high-availability/multi-cluster/introduction.adoc
  docs/guides/high-availability/partials/configuration-disclaimer.adoc
  docs/guides/high-availability/single-cluster/concepts.adoc
  docs/guides/high-availability/single-cluster/deploy-keycloak.adoc
  docs/guides/high-availability/single-cluster/introduction.adoc
Labels: team/sre

#42100 Add copy button to out-of-band code page
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
  themes/src/main/resources/theme/keycloak.v2/login/code.ftl
  themes/src/main/resources/theme/keycloak.v2/login/field.ftl
  themes/src/main/resources/theme/keycloak.v2/login/resources/css/styles.css
  themes/src/main/resources/theme/keycloak.v2/login/theme.properties
Labels: team/ui

#42472 Refactor JWTValidator to allow use both for self-signed and federated client assertions
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/QuarkusHttpRequest.java
  server-spi-private/src/main/java/org/keycloak/authentication/ClientAuthenticationFlowContext.java
  server-spi-private/src/main/java/org/keycloak/authentication/ClientAuthenticationFlowContextSupplier.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/ClientAssertionContext.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/ClientAssertionIdentityProvider.java
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/AbstractJWTClientValidator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/ClientAssertionState.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/FederatedJWTClientAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/FederatedJWTClientValidator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientSecretAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  services/src/main/java/org/keycloak/broker/spiffe/SpiffeIdentityProvider.java
  tests/base/src/test/java/org/keycloak/tests/client/authentication/external/FederatedClientAuthTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSecretSignedJWTTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#42522 [26.2] ClientSession timestamp not updated in the database
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/ClientSessionPersistentChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/JpaChangesPerformer.java
  model/storage-private/src/main/java/org/keycloak/models/session/PersistentAuthenticatedClientSessionAdapter.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionPersisterProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#42521 [26.3] ClientSession timestamp not updated in the database
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/ClientSessionPersistentChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/JpaChangesPerformer.java
  model/storage-private/src/main/java/org/keycloak/models/session/PersistentAuthenticatedClientSessionAdapter.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionPersisterProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#42169 [OID4VCI] Add support for credential_request_encryption in metadat
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerWellKnownProvider.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialRequestEncryptionMetadata.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialResponseEncryption.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialResponseEncryptionMetadata.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointEncryptionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerWellKnownProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCJWTIssuerEndpointDisabledTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCJWTIssuerEndpointTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtIssuingEndpointDisabledTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtIssuingEndpointTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42580 [OID4VCI] rename keyattestation+jwt to key-attestation+jwt
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/keybinding/AttestationValidatorUtil.java
Labels: flaky-test

#42573 fix: cleaning up dockerfile build warnings
  operator/Dockerfile
  quarkus/container/Dockerfile
Labels: team/cloud-native

#42614 Fix Chinese language names
  services/src/main/java/org/keycloak/theme/DefaultThemeManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/theme/DefaultThemeManagerTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36830 redirectToAuthentication if the request uses PAR to not lose the single object after a refresh
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/par/ParTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#42577 [OID4VCI] Adjust Credential Issuer Metadata endpoint, return issuer metadata at /.well-known/openid-credential-issuer/realms/{realm}
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerWellKnownProvider.java
  services/src/main/java/org/keycloak/services/resources/ServerMetadataResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerWellKnownProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42617 Validate wait_timeout parameter on MySQL and MariaDB
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
  docs/guides/server/db.adoc
  quarkus/README.md
  quarkus/config-api/src/main/java/org/keycloak/config/DatabaseOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/HttpOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/ManagementOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionsUtil.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaConnectionProviderFactory.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MariaDBDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MySQLDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBootstrapAdminService.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBootstrapAdminUser.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
Labels: team/cloud-native, team/sre

#41947 Automatic download and cache of the SAML client public keys
  core/src/main/java/org/keycloak/crypto/PublicKeysWrapper.java
  docs/documentation/release_notes/topics/26_4_0.adoc
  docs/documentation/server_admin/topics/clients/saml/proc-creating-saml-client.adoc
  docs/documentation/server_admin/topics/identity-broker/saml.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/add/SamlSignature.tsx
  js/apps/admin-ui/src/clients/keys/SamlKeys.tsx
  model/infinispan/src/main/java/org/keycloak/keys/infinispan/InfinispanPublicKeyStorageProvider.java
  model/infinispan/src/main/java/org/keycloak/keys/infinispan/InfinispanPublicKeyStorageProviderFactory.java
  saml-core/src/main/java/org/keycloak/saml/SPMetadataDescriptor.java
  saml-core/src/main/java/org/keycloak/saml/processing/core/saml/v2/util/SAMLMetadataUtil.java
  saml-core/src/main/java/org/keycloak/saml/processing/core/saml/v2/writers/SAMLMetadataWriter.java
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProviderConfig.java
  services/src/main/java/org/keycloak/protocol/saml/IDPMetadataDescriptor.java
  services/src/main/java/org/keycloak/protocol/saml/SamlAbstractMetadataPublicKeyLoader.java
  services/src/main/java/org/keycloak/protocol/saml/SamlClient.java
  services/src/main/java/org/keycloak/protocol/saml/SamlConfigAttributes.java
  services/src/main/java/org/keycloak/protocol/saml/SamlProtocol.java
  services/src/main/java/org/keycloak/protocol/saml/SamlProtocolFactory.java
  services/src/main/java/org/keycloak/protocol/saml/SamlProtocolUtils.java
  services/src/main/java/org/keycloak/protocol/saml/SamlService.java
  services/src/main/java/org/keycloak/validation/DefaultClientValidationProvider.java
  services/src/test/java/org/keycloak/protocol/saml/SamlMetadataKeyLocatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractKcSamlMetadataBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlMetadataSignedAndEncryptedBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlMetadataSignedBrokerTest.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam, team/sre

#42581 Client Authenticator configurable per client
  core/src/main/java/org/keycloak/representations/idm/ComponentTypeRepresentation.java
  js/apps/admin-ui/src/clients/credentials/Credentials.tsx
  js/libs/keycloak-admin-client/src/defs/componentTypeRepresentation.ts
  server-spi-private/src/main/java/org/keycloak/authentication/ClientAuthenticatorFactory.java
  server-spi/src/main/java/org/keycloak/provider/ConfiguredPerClientProvider.java
  services/src/main/java/org/keycloak/services/resources/admin/info/ServerInfoAdminResource.java
Labels: team/ui

#42322 refining http threads docs
  docs/guides/high-availability/partials/concepts/threads.adoc
Labels: team/sre

#42568 Replace UUID with composite key for client session cache
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
  model/infinispan/src/main/java/org/keycloak/marshalling/KeycloakModelSchema.java
  model/infinispan/src/main/java/org/keycloak/marshalling/Marshalling.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/AuthenticatedClientSessionAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/UserSessionAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/ClientSessionPersistentChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/JpaChangesPerformer.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/UserSessionPersistentChangelogBasedTransaction.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/AuthenticatedClientSessionEntity.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/EmbeddedClientSessionKey.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/SessionEntity.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/entities/UserSessionEntity.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remote/RemoteUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/stream/AuthClientSessionSetMapper.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/stream/UserSessionPredicate.java
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo26_4_0.java
  model/storage-private/src/main/java/org/keycloak/models/session/PersistentAuthenticatedClientSessionAdapter.java
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultMigrationManager.java
  server-spi/src/main/java/org/keycloak/models/AuthenticatedClientSessionModel.java
  server-spi/src/main/java/org/keycloak/models/UserSessionProvider.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionPersisterProviderTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionProviderModelTest.java
  testsuite/utils/src/main/java/org/keycloak/testsuite/util/cli/AbstractSessionCacheCommand.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam, team/sre

#42610 Add federated subject configuration option to federated-jwt authenticator
  js/apps/admin-ui/src/identity-providers/add/SpiffeSettings.tsx
  js/apps/admin-ui/test/identity-providers/main.ts
  js/apps/admin-ui/test/identity-providers/spiffe.spec.ts
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheManager.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaClientProviderFactory.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  model/storage-private/src/main/java/org/keycloak/storage/ClientStorageManager.java
  server-spi-private/src/main/java/org/keycloak/cache/AlternativeLookupProvider.java
  server-spi-private/src/main/java/org/keycloak/cache/AlternativeLookupProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/cache/AlternativeLookupSPI.java
  server-spi-private/src/main/resources/META-INF/services/org.keycloak.provider.Spi
  server-spi/src/main/java/org/keycloak/models/IdentityProviderModel.java
  server-spi/src/main/java/org/keycloak/storage/client/ClientLookupProvider.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/AbstractJWTClientValidator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/ClientAssertionState.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/FederatedJWTClientAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProviderConfig.java
  services/src/main/java/org/keycloak/broker/spiffe/SpiffeIdentityProvider.java
  services/src/main/java/org/keycloak/broker/spiffe/SpiffeIdentityProviderConfig.java
  services/src/main/java/org/keycloak/cache/ComputedKey.java
  services/src/main/java/org/keycloak/cache/DefaultAlternativeLookupProvider.java
  services/src/main/java/org/keycloak/cache/DefaultAlternativeLookupProviderFactory.java
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  services/src/main/resources/META-INF/services/org.keycloak.cache.AlternativeLookupProviderFactory
  services/src/test/java/org/keycloak/authentication/authenticators/client/FederatedJWTClientAuthenticatorTest.java
  services/src/test/java/org/keycloak/cache/ComputedKeyTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/client/ClientByAttributesTest.java
  tests/base/src/test/java/org/keycloak/tests/client/authentication/external/FederatedClientAuthFromKeycloakTest.java
  tests/base/src/test/java/org/keycloak/tests/client/authentication/external/FederatedClientAuthMappingTest.java
  tests/base/src/test/java/org/keycloak/tests/client/authentication/external/FederatedClientAuthTest.java
  tests/base/src/test/java/org/keycloak/tests/client/authentication/external/SpiffeClientAuthTest.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/HardcodedClientStorageProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam, team/sre

#42662 Adding CodeQL for GitHub Actions
  .github/actions/conditional/action.yml
  .github/actions/conditional/conditions
  .github/workflows/codeql-analysis.yml
Labels: flaky-test

#28887 Update federation-sssd-setup.sh to add ifp section
  quarkus/dist/src/main/content/bin/federation-sssd-setup.sh
Labels: team/cloud-native

#42720 Refactor and improve tests for federated client authentication
  services/src/main/java/org/keycloak/authentication/authenticators/client/AbstractJWTClientValidator.java
  test-framework/core/src/main/java/org/keycloak/testframework/events/EventAssertion.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/ManagedRealm.java
  tests/base/src/test/java/org/keycloak/tests/client/authentication/external/AbstractFederatedClientAuthTest.java
  tests/base/src/test/java/org/keycloak/tests/client/authentication/external/FederatedClientAuthFromKeycloakTest.java
  tests/base/src/test/java/org/keycloak/tests/client/authentication/external/FederatedClientAuthTest.java
  tests/base/src/test/java/org/keycloak/tests/client/authentication/external/IdentityProviderUpdater.java
  tests/base/src/test/java/org/keycloak/tests/client/authentication/external/SpiffeClientAuthTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42707 Incorrect scheme in the WWW-Authenticate when Authorization: DPoP used
  core/src/main/java/org/keycloak/OAuth2Constants.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/UserInfoEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/endpoints/BackchannelAuthenticationCallbackEndpoint.java
  services/src/main/java/org/keycloak/services/managers/AppAuthManager.java
  services/src/main/java/org/keycloak/utils/OAuth2Error.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/DPoPTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42665 Exclude invalid JavaScript files from CodeQL
  .github/actions/conditional/conditions
  .github/codeql/codeql-config-javascript.yml
  .github/codeql/codeql-config-typescript.yml
  .github/workflows/codeql-analysis.yml
Labels: flaky-test

#42648 Validation for immediate workflows
  server-spi-private/src/main/java/org/keycloak/models/workflow/Workflow.java
  services/src/main/java/org/keycloak/models/workflow/AdhocWorkflowEvent.java
  services/src/main/java/org/keycloak/models/workflow/WorkflowsManager.java
  services/src/main/java/org/keycloak/workflow/admin/resource/WorkflowResource.java
  tests/base/src/test/java/org/keycloak/tests/admin/model/workflow/AdhocWorkflowTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/model/workflow/AggregatedStepTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/model/workflow/WorkflowManagementTest.java
Labels: team/ui, flaky-test, team/sre

#42759 Update tested load numbers
  docs/guides/high-availability/multi-cluster/introduction.adoc
  docs/guides/high-availability/partials/tested-load.adoc
  docs/guides/high-availability/single-cluster/introduction.adoc
Labels: team/sre

#42763 Avoid double submit on opt login form
  themes/src/main/resources/theme/base/login/login-otp.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-otp.ftl
Labels: team/rh-iam, team/ui

#42679 Update docs to reflect that Operator ClusterRoleBinding contains hardcoded namespace
  docs/guides/operator/installation.adoc
  operator/src/main/kubernetes/kubernetes.yml
Labels: team/cloud-native

#42629 Automatically create external caches for MULTI_SITE deployments
  docs/documentation/release_notes/topics/26_4_0.adoc
  docs/guides/high-availability/examples/generated/keycloak-ispn.yaml
  docs/guides/high-availability/multi-cluster/deploy-infinispan-kubernetes-crossdc.adoc
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/CacheConfigurator.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/remote/DefaultCacheRemoteConfigProviderFactory.java
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/CachingPropertyMappers.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/ExternalInfinispanTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
  test-framework/core/src/main/java/org/keycloak/testframework/infinispan/InfinispanExternalServer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam, team/sre

#42772 Missing switch 'ID Token as detached signature' in the admin console …
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/AdvancedTab.tsx
  js/apps/admin-ui/src/clients/advanced/FineGrainOpenIdConnect.tsx
Labels: team/ui

#42684 [OID4VCI]: Remove format parameter from CredentialRequest
  services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialRequest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointEncryptionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCJWTIssuerEndpointTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42807 Missing switch 'ID Token as detached signature' in the admin console client settings
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/AdvancedTab.tsx
  js/apps/admin-ui/src/clients/advanced/FineGrainOpenIdConnect.tsx
Labels: team/ui

#42808 Missing switch 'ID Token as detached signature' in the admin console client settings
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/AdvancedTab.tsx
  js/apps/admin-ui/src/clients/advanced/FineGrainOpenIdConnect.tsx
Labels: team/ui

#42820 Fix problem with CredentialRequest#setFormat()
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCAuthorizationCodeFlowTestBase.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCAuthorizationDetailsFlowTestBase.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42761 Allow EdDSA keys in JWTClientCredentialsProvider
  core/src/main/java/org/keycloak/crypto/JavaAlgorithm.java
  core/src/main/java/org/keycloak/protocol/oidc/client/authentication/JWTClientCredentialsProvider.java
  services/src/main/java/org/keycloak/keys/loader/ClientPublicKeyLoader.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/AuthzClientCredentialsTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/authorization-test/keycloak-with-jwt-Ed25519-authentication.json
  testsuite/integration-arquillian/tests/base/src/test/resources/client-auth-test/keystore-client4.jks
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#42649 URL encode forwarded parameters
  services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerParameterForwardTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42623 fix: limiting what fields are hashed to identify compatible update jobs
  .github/workflows/ci.yml
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakServiceMonitorDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java
  operator/src/test/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResourceTest.java
Labels: team/cloud-native, flaky-test

#42766 Add missing Swedish translations for login theme
  themes/src/main/resources-community/theme/base/login/messages/messages_sv.properties
Labels: team/ui

#42896 [26.3] Upgrade to Quarkus 3.20.3 LTS
  pom.xml
Labels: team/cloud-native

#42840 Update upgrade guide about changes in how the parameter is propagated to OPs
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
Labels: team/cloud-native, team/core-clients, team/core-iam

#42909 Make it possible to check for permissions when deciding if a feature is enabled or not
  js/apps/admin-ui/src/utils/useIsFeatureEnabled.ts
Labels: team/ui

#42866 User session in LOGIN event
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
Labels: status/ready

#42923 Avoid invalidating the realm when managing client initial access
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
Labels: team/sre

#42903 Fix duplicate label when using password history
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserCredentialStore.java
  services/src/main/java/org/keycloak/credential/PasswordCredentialProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/policy/PasswordHistoryPolicyTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/account/WebAuthnSigningInTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42930 Do not skip dedicated client mapper when validating dynamic scopes in authorization or token requests
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OIDCProtocolMappersTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42651 Enable validate signature for SAML IdP to true when there are signing keys in the IdP metadata
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlParseIdPDescriptorTest.java
Labels: status/ready, team/cloud-native, flaky-test, team/core-clients, team/core-iam

#42853 Kubernetes Signed JWT Authenticator UI
  .github/workflows/js-ci.yml
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/identity-providers/add/AddKubernetesConnect.tsx
  js/apps/admin-ui/src/identity-providers/add/DetailSettings.tsx
  js/apps/admin-ui/src/identity-providers/add/KubernetesSettings.tsx
  js/apps/admin-ui/src/identity-providers/routes.ts
  js/apps/admin-ui/src/identity-providers/routes/IdentityProviderKubernetes.tsx
  js/apps/admin-ui/test/identity-providers/kubernetes.spec.ts
  js/apps/admin-ui/test/identity-providers/main.ts
  js/apps/keycloak-server/scripts/start-server.js
  services/src/main/java/org/keycloak/broker/kubernetes/KubernetesIdentityProvider.java
  services/src/main/java/org/keycloak/broker/kubernetes/KubernetesIdentityProviderConfig.java
  services/src/main/java/org/keycloak/broker/kubernetes/KubernetesIdentityProviderFactory.java
Labels: team/ui

#42819 [OID4VCI] Fix authorization_details generation and credential identifier mapping for conformance tests
  server-spi-private/src/main/java/org/keycloak/protocol/oidc/rar/AuthorizationDetailsProcessor.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCAuthorizationDetailsProcessor.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/AuthorizationCodeGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/OAuth2GrantTypeBase.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/PreAuthorizedCodeGrantType.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCAuthorizationCodeFlowTestBase.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCAuthorizationDetailsFlowTestBase.java
Labels: status/ready, team/cloud-native, team/core-clients, team/core-iam

#42857 Use JDK 25 Temurin in GHA CI
  .github/workflows/ci.yml
Labels: team/cloud-native

#42934 Add workflow condition that uses boolean expressions to combine and n…
  model/jpa/pom.xml
  model/jpa/src/main/antlr4/org/keycloak/models/workflow/conditions/expression/BooleanCondition.g4
  model/jpa/src/main/java/org/keycloak/models/workflow/conditions/ExpressionWorkflowConditionFactory.java
  model/jpa/src/main/java/org/keycloak/models/workflow/conditions/ExpressionWorkflowConditionProvider.java
  model/jpa/src/main/java/org/keycloak/models/workflow/conditions/GroupMembershipWorkflowConditionFactory.java
  model/jpa/src/main/java/org/keycloak/models/workflow/conditions/IdentityProviderWorkflowConditionFactory.java
  model/jpa/src/main/java/org/keycloak/models/workflow/conditions/RoleWorkflowConditionFactory.java
  model/jpa/src/main/java/org/keycloak/models/workflow/conditions/UserAttributeWorkflowConditionFactory.java
  model/jpa/src/main/java/org/keycloak/models/workflow/conditions/expression/BooleanConditionEvaluator.java
  model/jpa/src/main/java/org/keycloak/models/workflow/conditions/expression/ErrorListener.java
  model/jpa/src/main/java/org/keycloak/models/workflow/conditions/expression/PredicateConditionEvaluator.java
  model/jpa/src/main/resources/META-INF/services/org.keycloak.models.workflow.WorkflowConditionProviderFactory
  pom.xml
  server-spi-private/src/main/java/org/keycloak/models/workflow/WorkflowConditionProviderFactory.java
  services/src/main/java/org/keycloak/models/workflow/WorkflowsManager.java
  tests/base/src/test/java/org/keycloak/tests/admin/model/workflow/ExpressionConditionWorkflowTest.java
Labels: flaky-test

#42981 Update documentation to prefer CacheCR in multi-site
  docs/guides/high-availability/multi-cluster/deploy-infinispan-kubernetes-crossdc.adoc
Labels: team/sre

#42341 Support for EDB 17
  .github/actions/run-store-tests/action.yml
  .github/workflows/ci.yml
  docs/documentation/release_notes/topics/26_4_0.adoc
  docs/documentation/topics/templates/document-attributes.adoc
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
  docs/guides/server/db.adoc
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/PostgresPlusDatabase.java
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/conn/DefaultLiquibaseConnectionProvider.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-14.0.0.xml
  model/jpa/src/main/resources/META-INF/jpa-changelog-20.0.0.xml
  model/jpa/src/main/resources/META-INF/jpa-changelog-24.0.0.xml
  model/jpa/src/main/resources/META-INF/jpa-changelog-25.0.0.xml
  model/jpa/src/main/resources/META-INF/services/liquibase.database.Database
  pom.xml
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
  quarkus/runtime/src/main/resources/application.properties
  test-framework/bom/pom.xml
  test-framework/core/src/main/resources/org/keycloak/testframework/util/containers.properties
  test-framework/db-edb/container/Dockerfile
  test-framework/db-edb/container/init-and-start-db.sh
  test-framework/db-edb/pom.xml
  test-framework/db-edb/src/main/java/org/keycloak/testframework/database/EnterpriseDbDatabaseSupplier.java
  test-framework/db-edb/src/main/java/org/keycloak/testframework/database/EnterpriseDbTestDatabase.java
  test-framework/db-edb/src/main/java/org/keycloak/testframework/database/EnterpriseDbTestFrameworkExtension.java
  test-framework/db-edb/src/main/java/org/keycloak/testframework/database/KeycloakEnterpriseDbContainer.java
  test-framework/db-edb/src/main/resources/META-INF/services/org.keycloak.testframework.TestFrameworkExtension
  test-framework/pom.xml
  tests/base/pom.xml
  tests/base/src/test/java/org/keycloak/tests/db/CaseSensitiveSchemaTest.java
  tests/base/src/test/java/org/keycloak/tests/db/PreserveSchemaCaseLiquibaseTest.java
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/tests/base/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#43003 Fix deletion messages for workflows.
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/workflows/WorkflowsSection.tsx
Labels: team/ui

#42985 Mark Azure SQL as supported
  docs/documentation/release_notes/topics/26_4_0.adoc
  docs/guides/server/db.adoc
Labels: team/cloud-native, flaky-test

#38131 docs: Use BASH TCP redirect for HEALTHCHECK
  docs/guides/observability/health.adoc
Labels: team/sre

#43026 Reorder the release notes
  docs/documentation/release_notes/topics/26_4_0.adoc
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
  docs/guides/server/db.adoc
Labels: team/cloud-native
