Repository keycloak/keycloak, pull requests merged in 2025-02, with the labels that each got.

#36979 Add patch for keycloak for the French translation
  themes/src/main/resources-community/theme/base/login/messages/messages_fr.properties
Labels: team/ui

#36980 Update messages_fr.properties to fix grammar typo
  themes/src/main/resources-community/theme/base/login/messages/messages_fr.properties
Labels: team/ui

#36917 BACKPORT: fixed viewport scale for mobile
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
Labels: team/ui, flaky-test

#36864 Add default configuration for cache 'crl'
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/InfinispanUtil.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/CacheManagerFactory.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/DistributionKeycloakServer.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/EmbeddedKeycloakServer.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/KeycloakServerConfigBuilder.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/RemoteKeycloakServer.java
  tests/base/src/test/java/org/keycloak/tests/infinispan/InfinispanXMLBackwardCompatibilityTest.java
  tests/base/src/test/resources/embedded-infinispan-config/infinispan-xml-kc26.xml
Labels: team/cloud-native, flaky-test

#36971 Basic migration util for migrating tests from old testsuite to new
  tests/migration-util/migrate.sh
  tests/migration-util/pom.xml
  tests/migration-util/src/main/java/org/keycloak/test/migration/AddKeycloakIntegrationTestRewrite.java
  tests/migration-util/src/main/java/org/keycloak/test/migration/AddManagedResourcesRewrite.java
  tests/migration-util/src/main/java/org/keycloak/test/migration/AdminEventAssertRewrite.java
  tests/migration-util/src/main/java/org/keycloak/test/migration/ChangePackageRewrite.java
  tests/migration-util/src/main/java/org/keycloak/test/migration/MigrateTest.java
  tests/migration-util/src/main/java/org/keycloak/test/migration/RenameImportsRewrite.java
  tests/migration-util/src/main/java/org/keycloak/test/migration/TestRewrite.java
  tests/migration-util/src/main/java/org/keycloak/test/migration/UpdateAssertsRewrite.java
Labels: area/test-framework

#36967 Manage exceptions in waitForPageToLoad for chrome error in version 132
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/UIUtils.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/WaitUtils.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/webauthn/pages/WebAuthnLoginPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/webauthn/pages/WebAuthnRegisterPage.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#35845 fix: detecting provider changes when running start optimized
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/RealmImportTest.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
Labels: team/cloud-native

#37020 Manage exceptions in waitForPageToLoad for chrome error in version 132 (26.0)
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/UIUtils.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/WaitUtils.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/webauthn/pages/WebAuthnLoginPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/webauthn/pages/WebAuthnRegisterPage.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36978 Ensure LDAPStorageMapper.getGroupMembers is taking the fetch strategy…
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/UserRolesRetrieveStrategy.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapper.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/role/RoleLDAPStorageMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#36909 use own form context instead of client form
  js/apps/admin-ui/src/clients/keys/SamlImportKeyDialog.tsx
Labels: team/ui

#36911 added filter and sorting to dropdown
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
  js/libs/ui-shared/src/select/TypeaheadSelect.tsx
Labels: team/ui

#37027 Manage exceptions in waitForPageToLoad for chrome error in version 132 (24.0)
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/WaitUtils.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36989 Fixed typos in email theme.
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
  themes/src/main/resources/theme/base/email/messages/messages_en.properties
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#37007 Fix broken JavaScript CI
  .github/actions/pnpm-setup/action.yml
  .github/workflows/js-ci.yml
  js/apps/admin-ui/cypress/e2e/user_fed_ldap_test.spec.ts
Labels: team/ui

#37032 Fix broken JavaScript CI
  .github/actions/pnpm-setup/action.yml
  .github/workflows/js-ci.yml
  js/apps/admin-ui/cypress/e2e/user_fed_ldap_test.spec.ts
Labels: team/ui

#36966 made test more robust
  js/apps/admin-ui/cypress/e2e/realm_roles_test.spec.ts
Labels: team/ui

#36929 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ka.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ka.properties
Labels: team/ui, flaky-test

#36922 new realm selector based on the new design
  js/apps/admin-ui/cypress/support/pages/admin-ui/CreateRealmPage.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/SidebarPage.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/PageHeader.tsx
  js/apps/admin-ui/src/PageNav.tsx
  js/apps/admin-ui/src/components/realm-selector/RealmPanel.tsx
  js/apps/admin-ui/src/components/realm-selector/RealmSelector.tsx
  js/apps/admin-ui/src/context/RecentRealms.tsx
  js/apps/admin-ui/src/realm/add/NewRealmForm.tsx
  js/apps/admin-ui/src/realm/routes.ts
  js/apps/admin-ui/src/realm/routes/AddRealm.tsx
  js/apps/admin-ui/src/routes.tsx
Labels: team/ui

#37041 Ensure LDAPStorageMapper.getGroupMembers is taking the fetch strategy…
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/UserRolesRetrieveStrategy.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapper.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/role/RoleLDAPStorageMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37008 Support ECS for logs
  docs/documentation/release_notes/topics/26_2_0.adoc
  docs/guides/server/logging.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/LoggingOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/LoggingConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/OptionsDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#34247 only enable the when there are idp available
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/index.ftl
  js/apps/create-keycloak-theme/templates/maven-resources/theme/my-account/account/index.ftl.mu
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
Labels: team/ui, flaky-test

#35729 Update messages_ko.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ko.properties
Labels: area/translations, team/ui

#36914 added new endpoint that concatenates offline and regular sessions for clients
  js/apps/admin-ui/src/clients/ClientSessions.tsx
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/SessionsResource.java
Labels: team/ui

#36913 Document external port and address feature for JGroups
  docs/guides/server/caching.adoc
Labels: team/cloud-native

#37046 Fixed typos in email theme
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
  themes/src/main/resources/theme/base/email/messages/messages_en.properties
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#37045 Fixed typos in email theme
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
  themes/src/main/resources/theme/base/email/messages/messages_en.properties
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#37067 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_es.properties
Labels: team/ui

#37052 Certificate reloading does not work for the management interface
  docs/documentation/release_notes/topics/26_2_0.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/ManagementOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ManagementPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ManagementConfigurationTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
Labels: team/cloud-native

#36457 fix: narrow fix for creating single file import without a system prop
  model/storage-services/src/main/java/org/keycloak/exportimport/dir/DirImportProviderFactory.java
  model/storage-services/src/main/java/org/keycloak/exportimport/singlefile/SingleFileImportProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/exportimport/ImportProviderFactory.java
  services/src/main/java/org/keycloak/exportimport/ExportImportManager.java
  services/src/test/java/org/keycloak/exportimport/ExportImportManagerTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#36951 Use lightweight access token with transient session for client registration
  services/src/main/java/org/keycloak/services/clientregistration/ClientRegistrationAuth.java
  services/src/main/java/org/keycloak/services/clientregistration/ClientRegistrationTokenUtils.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientRegistrationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37106 Fix broken JavaScript CI
  .github/actions/pnpm-setup/action.yml
  .github/workflows/js-ci.yml
  js/apps/admin-ui/cypress/e2e/user_fed_ldap_test.spec.ts
Labels: team/ui, flaky-test

#37051 Document external port and address feature for JGroups
  docs/guides/server/caching.adoc
Labels: team/cloud-native

#36366 VERIFY_EMAIL as supported Application Initiated Action
  docs/documentation/server_admin/topics/users/con-aia.adoc
  services/src/main/java/org/keycloak/authentication/requiredactions/VerifyEmail.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/VerifyEmailPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionVerifyEmailTest.java
  themes/src/main/resources/theme/base/login/login-verify-email.ftl
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
  themes/src/main/resources/theme/keycloak.v2/login/resources/css/styles.css
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#36882 Feature flag: rolling-updates
  common/src/main/java/org/keycloak/common/Profile.java
  docs/guides/operator/advanced-configuration.adoc
  docs/guides/server/update-compatibility.adoc
  docs/guides/templates/kc.adoc
  operator/scripts/Dockerfile-custom-image
  operator/src/test/java/org/keycloak/operator/testsuite/integration/UpgradeTest.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractUpdatesCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/UpdateCompatibilityCheck.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/UpdateCompatibilityMetadata.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/compatibility/CompatibilityResult.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/UpdateCommandDistTest.java
Labels: status/hold, team/cloud-native, flaky-test

#37018 35505 token exchange more audiences - requester client used for clientSession and scopes
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/AbstractTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/AbstractStandardTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/ClientTokenExchangeAudienceAndScopesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/resources/token-exchange/testrealm-token-exchange-v2.json
Labels: team/cloud-native, team/core-clients, team/core-iam

#37101 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
Labels: team/ui

#37146 Simplify translations by removing leading blanks in strings
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/authorization/AuthorizationEvaluateResourcePolicies.tsx
Labels: team/ui

#36876 Ensure IDPs returned from infinispan provider are ordered by alias
  js/apps/admin-ui/src/identity-providers/IdentityProvidersSection.tsx
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/idp/InfinispanIdentityProviderStorageProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#37161 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
Labels: team/ui

#37152 Fix clear button for typeaheadMulti dropdowns.
  js/libs/ui-shared/src/controls/select-control/TypeaheadSelectControl.tsx
Labels: team/ui

#37125 Add factory to create custom admin clients
  test-framework/core/src/main/java/org/keycloak/testframework/CoreTestFrameworkExtension.java
  test-framework/core/src/main/java/org/keycloak/testframework/admin/AdminClientBuilder.java
  test-framework/core/src/main/java/org/keycloak/testframework/admin/AdminClientFactory.java
  test-framework/core/src/main/java/org/keycloak/testframework/admin/AdminClientFactorySupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/admin/AdminClientSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/annotations/InjectAdminClientFactory.java
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/AdminClientFactoryTest.java
Labels: area/test-framework

#37197 Ensure a sufficient virtual threads pool
  docs/documentation/release_notes/topics/26_1_0.adoc
  docs/guides/high-availability/concepts-threads.adoc
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java
Labels: team/cloud-native

#37212 Ensure a sufficient virtual threads pool
  docs/documentation/release_notes/topics/26_1_0.adoc
  docs/guides/high-availability/concepts-threads.adoc
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java
Labels: team/cloud-native

#37215 Upgrade Infinispan to 15.0.12.Final
  pom.xml
  testsuite/model/src/main/java/org/keycloak/testsuite/model/HotRodServerRule.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37204 Invalid migration export for empty database
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/LiquibaseJpaUpdaterProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/liquibase/QuarkusJpaUpdaterProvider.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/BasicDatabaseTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MariaDBDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MySQLDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/PostgreSQLDistTest.java
Labels: team/cloud-native

#37217 Invalid migration export for empty database
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/LiquibaseJpaUpdaterProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/liquibase/QuarkusJpaUpdaterProvider.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/BasicDatabaseTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MariaDBDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MySQLDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/PostgreSQLDistTest.java
Labels: team/cloud-native

#37216 Invalid migration export for empty database
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/LiquibaseJpaUpdaterProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/liquibase/QuarkusJpaUpdaterProvider.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/BasicDatabaseTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MariaDBDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/MySQLDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/PostgreSQLDistTest.java
Labels: team/cloud-native

#37157 Add Network Ports section for Keycloak < 26.1
  docs/guides/server/caching.adoc
Labels: area/docs, team/cloud-native, team/sre

#36880 Add Client resource type and its scopes to authorization schema and e…
  server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/AdminPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/ClientPermissionEvaluator.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/ClientPermissionsV2.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissionsV2.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/AbstractPermissionTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/PermissionClientTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/PermissionRESTTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypeEvaluationTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypePermissionTest.java
Labels: flaky-test

#37092 Migrate EventConfigTest to the new testsuite
  test-framework/core/src/main/java/org/keycloak/testframework/realm/RealmConfigBuilder.java
  tests/base/src/test/java/org/keycloak/tests/admin/event/EventConfigTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/event/EventConfigTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, area/test-framework

#37262 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
Labels: team/ui

#37201 Fix json editor scroll behavior
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
  js/apps/admin-ui/src/clients/authorization/policy/JavaScript.tsx
  js/apps/admin-ui/src/components/dynamic/ScriptComponent.tsx
  js/apps/admin-ui/src/components/json-file-upload/FileUploadForm.tsx
  js/apps/admin-ui/src/events/AdminEvents.tsx
  js/apps/admin-ui/src/realm-settings/PoliciesTab.tsx
  js/apps/admin-ui/src/realm-settings/ProfilesTab.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/JsonEditorTab.tsx
Labels: team/ui

#37278 Prevent RawKeycloakDistribution from resulting in hard to debug message
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
Labels: team/cloud-native

#37263 Rename operator strategy options
  docs/guides/operator/advanced-configuration.adoc
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/UpdateSpec.java
  operator/src/main/java/org/keycloak/operator/upgrade/UpdateStrategy.java
  operator/src/main/java/org/keycloak/operator/upgrade/UpgradeLogicFactory.java
  operator/src/main/java/org/keycloak/operator/upgrade/impl/ForceRecreateUpgradeLogic.java
  operator/src/main/java/org/keycloak/operator/upgrade/impl/RecreateOnImageChangeUpgradeLogic.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/UpgradeTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/CRSerializationTest.java
  operator/src/test/resources/test-serialization-keycloak-cr.yml
Labels: team/cloud-native

#37291 small refactor to better understand
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AddTranslationsDialog.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/TranslatableField.tsx
Labels: team/ui

#37038 Add Groups resource type and scopes to authorization schema and evalu…
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/BruteForceUsersResource.java
  server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/AdminPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/GroupPermissionEvaluator.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/GroupPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/GroupPermissionsV2.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissionsV2.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissionEvaluator.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissionsV2.java
  test-framework/core/src/main/java/org/keycloak/testframework/util/ApiUtil.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/GroupResourceTypeEvaluationTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/RealmAdminPermissionsConfig.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypeEvaluationTest.java
Labels: team/ui

#37206 added pem to saml dialog
  js/apps/admin-ui/src/clients/keys/SamlKeysDialog.tsx
Labels: team/ui

#37299 Use new OAuthClient in the StandardTokenExchangeV2Test
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37304 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
Labels: team/ui

#37305 Force login in reset-credentials to federated users (26.1)
  docs/documentation/release_notes/index.adoc
  docs/documentation/release_notes/topics/26_1_3.adoc
  docs/documentation/server_admin/images/reset-credential-email-config.png
  docs/documentation/server_admin/topics/login-settings/forgot-password.adoc
  docs/documentation/upgrading/topics/changes/changes-26_1_3.adoc
  docs/documentation/upgrading/topics/changes/changes.adoc
  services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37309 Force login in reset-credentials to federated users (26.0)
  docs/documentation/release_notes/topics/26_0_10.adoc
  docs/documentation/server_admin/images/reset-credential-email-config.png
  docs/documentation/server_admin/topics/login-settings/forgot-password.adoc
  docs/documentation/upgrading/topics/changes/changes-26_0_10.adoc
  docs/documentation/upgrading/topics/changes/changes.adoc
  services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37179 Prevent duplicate keys in message properties for themes
  js/pom.xml
  misc/theme-verifier/pom.xml
  misc/theme-verifier/src/main/java/org/keycloak/themeverifier/MessagePropertiesFilter.java
  misc/theme-verifier/src/main/java/org/keycloak/themeverifier/ThemeVerifierMojo.java
  misc/theme-verifier/src/main/java/org/keycloak/themeverifier/VerifyMessageProperties.java
  misc/theme-verifier/src/test/java/org/keycloak/themeverifier/VerifyMessagePropertiesTest.java
  misc/theme-verifier/src/test/resources/duplicate_keys.properties
  pom.xml
  themes/pom.xml
  themes/src/main/resources-community/theme/base/account/messages/messages_da.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_fi.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ru.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ko.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_tr.properties
Labels: team/ui

#37310 Refactor OAuth Client - part 2
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/AccessTokenRequest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/HttpClientManager.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/PasswordGrantRequest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/TokenExchangeRequest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminConsoleWhoAmILocaleTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/FineGrainAdminUnitTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/AbstractGroupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/EntitlementAPITest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UmaDiscoveryDocumentTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerNonceParameterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/AbstractClientRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPI1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPI2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/MutualTLSClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1ConfidentialClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1PublicClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AbstractClientAuthSignedJWTTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AccessTokenNoEmailLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/DPoPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuth2DeviceAuthorizationGrantTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthProofKeyForCodeExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenEndpointCorsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/hok/HoKTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/AbstractStandardTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/ClientTokenExchangeAudienceAndScopesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/ClientTokenExchangeSAML2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AbstractWellKnownProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCAdvancedRequestParamsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCPublicClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/UserInfoTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/ssl/TLSTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/url/HostnameV2Test.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37247 Perform some regular maintenance for JS
  .github/actions/pnpm-setup/action.yml
  .github/workflows/js-ci.yml
  js/apps/account-ui/package.json
  js/apps/admin-ui/package.json
  js/libs/ui-shared/package.json
  js/package.json
  js/pnpm-lock.yaml
  js/pom.xml
Labels: team/ui

#37292 BACKPORT small refactor to better understand (#37291)
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AddTranslationsDialog.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/TranslatableField.tsx
Labels: team/ui

#37296 Remove need to implement getAnnotationClass and getValueType in suppliers
  test-framework/core/src/main/java/org/keycloak/testframework/admin/AdminClientFactorySupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/admin/AdminClientSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/database/AbstractDatabaseSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/events/AdminEventsSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/events/EventsSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/events/SysLogServerSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/http/HttpClientSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/injection/ReflectionUtils.java
  test-framework/core/src/main/java/org/keycloak/testframework/injection/Supplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/ClientSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/RealmSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/UserSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/AbstractKeycloakServerSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/KeycloakUrlsSupplier.java
  test-framework/core/src/test/java/org/keycloak/testframework/injection/mocks/MockChildSupplier.java
  test-framework/core/src/test/java/org/keycloak/testframework/injection/mocks/MockParent2Supplier.java
  test-framework/core/src/test/java/org/keycloak/testframework/injection/mocks/MockParentSupplier.java
  test-framework/email-server/src/main/java/org/keycloak/testframework/mail/GreenMailSupplier.java
  test-framework/oauth-nimbus-poc/src/main/java/org/keycloak/testframework/oauth/nimbus/OAuthClientSupplier.java
  test-framework/remote/src/main/java/org/keycloak/testframework/remote/RemoteProvidersSupplier.java
  test-framework/remote/src/main/java/org/keycloak/testframework/remote/timeoffset/TimeOffsetSupplier.java
  test-framework/remote/src/main/java/org/keycloak/testframework/runonserver/RunOnServerSupplier.java
  test-framework/remote/src/main/java/org/keycloak/testframework/runonserver/TestClassServerSupplier.java
  test-framework/ui/src/main/java/org/keycloak/testframework/ui/page/PageSupplier.java
  test-framework/ui/src/main/java/org/keycloak/testframework/ui/webdriver/AbstractWebDriverSupplier.java
Labels: area/test-framework

#37277 Updates to test migration tool
  tests/migration-util/src/main/java/org/keycloak/test/migration/BeforeRewrite.java
  tests/migration-util/src/main/java/org/keycloak/test/migration/MigrateTest.java
  tests/migration-util/src/main/java/org/keycloak/test/migration/RenameImportsRewrite.java
  tests/pom.xml
Labels: area/test-framework

#37282 BACKPORT: Fix json editor scroll behavior (#37201)
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
  js/apps/admin-ui/src/clients/authorization/policy/JavaScript.tsx
  js/apps/admin-ui/src/components/dynamic/ScriptComponent.tsx
  js/apps/admin-ui/src/components/json-file-upload/FileUploadForm.tsx
  js/apps/admin-ui/src/events/AdminEvents.tsx
  js/apps/admin-ui/src/realm-settings/PoliciesTab.tsx
  js/apps/admin-ui/src/realm-settings/ProfilesTab.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/JsonEditorTab.tsx
Labels: team/ui

#37294 Show error message only in the username field for the login.ftl
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/updaters/RealmAttributeUpdater.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java
  themes/src/main/resources/theme/keycloak.v2/login/field.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login.ftl
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#37065 Revert "[Backport] Snyk report to identify branches impacted by a CVE"
  .github/scripts/snyk-report.sh
  .github/workflows/snyk-analysis.yml
Labels: team/security

#37064 Revert "Move Snyk reports from GitHub Security tab to GitHub issues"
  .github/scripts/snyk-report.sh
  .github/workflows/snyk-analysis.yml
Labels: team/security

#37274 Migrate AuthenticatorConfigTest
  test-framework/core/src/main/java/org/keycloak/testframework/util/ApiUtil.java
  tests/base/pom.xml
  tests/base/src/test/java/org/keycloak/tests/admin/authentication/AuthenticatorConfigTest.java
Labels: area/test-framework

#37350 Show error message only in the username field for the login.ftl (26.0)
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/updaters/RealmAttributeUpdater.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java
  themes/src/main/resources/theme/keycloak.v2/login/field.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login.ftl
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#37345 Show error message only in the username field for the login.ftl (26.1)
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/updaters/RealmAttributeUpdater.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java
  themes/src/main/resources/theme/keycloak.v2/login/field.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login.ftl
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#37235 Only set organization to client session when re-authenticating if user is member of the mapped organization
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationMembershipMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationOIDCProtocolMapperTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37342 Trivy workflow is not reporting issues on other branches [26.0]
  .github/workflows/trivy-analysis.yml
Labels: team/security

#37333 Remove warnings adding checkout [main]
  .github/workflows/trivy-analysis.yml
Labels: team/security

#37336 Trivy workflow is not reporting issues on other branches [26.1]
  .github/workflows/trivy-analysis.yml
Labels: team/security

#37335 Trivy workflow is not reporting issues on other branches [24.0]
  .github/workflows/trivy-analysis.yml
Labels: team/security

#37358 [Backport] - Only set organization to client session when re-authenticating if user is member of the mapped organization
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationMembershipMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationOIDCProtocolMapperTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37359 [Backport] Only set organization to client session when re-authenticating if user is member of the mapped organization
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationMembershipMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationOIDCProtocolMapperTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37364 CVE-2024-47072 - XStream is vulnerable to a Denial of Service attack due to stack overflow from a manipulated binary input stream [26.1]
  pom.xml
Labels: team/security

#37353 Filter scopes in token exchange v2 based on requested audience
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProvider.java
  services/src/main/java/org/keycloak/services/util/DefaultClientSessionContext.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/ClientTokenExchangeAudienceAndScopesTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/token-exchange/testrealm-token-exchange-v2.json
Labels: team/cloud-native, team/core-clients, team/core-iam

#37361 CVE-2024-47072 - XStream is vulnerable to a Denial of Service attack due to stack overflow from a manipulated binary input stream [24]
  pom.xml
Labels: team/security

#37088 Test logs for Quarkus IT are huge and cannot be viewed
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartDevCommandDistTest.java
  quarkus/tests/integration/src/test/resources/keystore
Labels: team/cloud-native

#37091 Stabilize QuarkusPropertiesDistTest for Windows in Quarkus IT
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java
Labels: team/cloud-native

#37080 Improve docs about JPA provider configuration for DB migration strategy
  docs/guides/attributes.adoc
  docs/guides/server/db.adoc
Labels: team/cloud-native

#37354 Reject token exchange request if the requested audience is not present
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProvider.java
  services/src/main/java/org/keycloak/services/util/DefaultClientSessionContext.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/ClientTokenExchangeAudienceAndScopesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/TokenExchangeTestUtils.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37096 doc: adding a full example of overriding the startup probe timeout
  docs/guides/operator/advanced-configuration.adoc
Labels: team/cloud-native

#37330 BACKPORT: Fix clear button for typeaheadMulti dropdowns. (#37152)
  js/libs/ui-shared/src/controls/select-control/TypeaheadSelectControl.tsx
Labels: team/ui

#37328 BACKPORT: Make hideOnLogin default to true on submit. (#36805)
  js/apps/admin-ui/src/organizations/LinkIdentityProviderModal.tsx
Labels: team/ui

#37327 BACKPORT: Don't require events enabled to view event tabs. (#36722)
  js/apps/admin-ui/cypress/e2e/clients_test.spec.ts
  js/apps/admin-ui/src/clients/ClientDetails.tsx
  js/apps/admin-ui/src/groups/GroupsSection.tsx
  js/apps/admin-ui/src/realm-roles/RealmRoleTabs.tsx
  js/apps/admin-ui/src/user/EditUser.tsx
Labels: team/ui

#37171 Migrate ClientSearchTest to the new testsuite
  test-framework/core/src/main/java/org/keycloak/testframework/realm/ClientConfigBuilder.java
  tests/base/src/test/java/org/keycloak/tests/admin/client/AbstractClientSearchTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/client/ClientSearchJpaTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/client/ClientSearchTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/ClientSearchTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, area/test-framework

#37300 Upgrade to Quarkus 3.18.2
  docs/documentation/tests/src/test/resources/ignored-links
  docs/documentation/upgrading/topics/changes/changes-26_2_0.adoc
  docs/documentation/upgrading/topics/changes/changes.adoc
  operator/src/main/java/org/keycloak/operator/ContextUtils.java
  operator/src/main/java/org/keycloak/operator/Utils.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakAdminSecretDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDiscoveryServiceDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngressDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakNetworkPolicyDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJobDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportSecretDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakServiceDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakStatus.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakStatusAggregator.java
  operator/src/main/java/org/keycloak/operator/upgrade/UpgradeLogicFactory.java
  operator/src/main/java/org/keycloak/operator/upgrade/impl/AutoUpgradeLogic.java
  operator/src/main/java/org/keycloak/operator/upgrade/impl/BaseUpgradeLogic.java
  operator/src/main/java/org/keycloak/operator/upgrade/impl/ForceRecreateUpgradeLogic.java
  operator/src/main/java/org/keycloak/operator/upgrade/impl/RecreateOnImageChangeUpgradeLogic.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/KeycloakControllerTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/CRAssert.java
  pom.xml
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ProxyHostnameV2DistTest.java
  test-framework/core/src/main/java/org/keycloak/testframework/LogHandler.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/UserPropertyFileStorage.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37265 Properties mapped in our property mappers are overridden
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/LoggingConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/MetricsDistTest.java
Labels: team/cloud-native

#37395 Ensure the group being joined is not an organization group in GroupLD…
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapper.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationMembersResource.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/util/LDAPTestUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/member/OrganizationMemberWithLdapTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#37338 Make sure resources are properly managed when updating permissions
  js/apps/admin-ui/src/permissions-configuration/permission-configuration/permission-type/Users.tsx
  server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java
  server-spi-private/src/main/java/org/keycloak/authorization/AuthorizationProvider.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/AdminPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissionsV2.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissionsV2.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/ClientResourceTypeEvaluationTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypeEvaluationTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypePermissionTest.java
Labels: missing/tests, team/ui

#37390 Properties mapped in our property mappers are overriden
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/Configuration.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/AbstractConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/LoggingConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/MetricsDistTest.java
Labels: team/cloud-native

#37414 Fix typo and alter dialog to be like all the others
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#37432 Password policies like NoUsername should compare in case-insensitive way
  server-spi-private/src/main/java/org/keycloak/policy/NotContainsUsernamePasswordPolicyProvider.java
  server-spi-private/src/main/java/org/keycloak/policy/NotEmailPasswordPolicyProvider.java
  server-spi-private/src/main/java/org/keycloak/policy/NotUsernamePasswordPolicyProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37446 Password policies like NoUsername should compare in case-insensitive way
  server-spi-private/src/main/java/org/keycloak/policy/NotContainsUsernamePasswordPolicyProvider.java
  server-spi-private/src/main/java/org/keycloak/policy/NotEmailPasswordPolicyProvider.java
  server-spi-private/src/main/java/org/keycloak/policy/NotUsernamePasswordPolicyProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37448 Password policies like NoUsername should compare in case-insensitive way
  server-spi-private/src/main/java/org/keycloak/policy/NotEmailPasswordPolicyProvider.java
  server-spi-private/src/main/java/org/keycloak/policy/NotUsernamePasswordPolicyProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37409 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ka.properties
Labels: team/ui

#37443 Password policies like NoUsername should compare in case-insensitive way
  server-spi-private/src/main/java/org/keycloak/policy/NotContainsUsernamePasswordPolicyProvider.java
  server-spi-private/src/main/java/org/keycloak/policy/NotEmailPasswordPolicyProvider.java
  server-spi-private/src/main/java/org/keycloak/policy/NotUsernamePasswordPolicyProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37444 Separate tests for standard token exchange v2
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/AbstractStandardTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/ClientTokenExchangeAudienceAndScopesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/resources/token-exchange/testrealm-token-exchange-v2.json
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#37394 Migrate InstallationTest to the new testsuite
  test-framework/core/src/main/java/org/keycloak/testframework/realm/ClientConfigBuilder.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/ManagedClient.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/ManagedClientCleanup.java
  tests/base/src/test/java/org/keycloak/tests/admin/client/InstallationTest.java
  tests/utils/src/main/java/org/keycloak/tests/utils/KeyUtils.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/client/resources/TestingResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/AbstractClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/InstallationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, area/test-framework

#36881 Deprecates X-XSS-Protection and put it behind feature flag.
  docs/documentation/release_notes/topics/26_2_0.adoc
  js/apps/admin-ui/cypress/e2e/realm_settings_tabs_test.spec.ts
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ka.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_pl.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_CN.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/security-defences/HeadersForm.tsx
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo26_2_0.java
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultMigrationManager.java
  operator/src/test/resources/example-realm.yaml
  operator/src/test/resources/test-serialization-realmimport-cr.yml
  operator/src/test/resources/token-test-realm.yaml
  server-spi-private/src/main/java/org/keycloak/models/BrowserSecurityHeaders.java
  server-spi-private/src/test/java/org/keycloak/models/BrowserSecurityHeadersTest.java
  services/src/main/java/org/keycloak/headers/DefaultSecurityHeadersProvider.java
  tests/base/src/test/java/org/keycloak/tests/admin/AdminHeadersTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/import/import-without-clients.json
  testsuite/integration-arquillian/tests/base/src/test/resources/import/import-without-roles.json
  testsuite/integration-arquillian/tests/base/src/test/resources/import/partial-import.json
  testsuite/integration-arquillian/tests/base/src/test/resources/import/testrealm-user-null-attr.json
  testsuite/integration-arquillian/tests/base/src/test/resources/model/acr-values-import-bug.json
  testsuite/integration-arquillian/tests/base/src/test/resources/token-exchange/testrealm-token-exchange-v2.json
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#37471 Upgrade to Quarkus 3.18.3 to address CVE issues
  pom.xml
Labels: team/cloud-native

#37408 fix: making the deadline override applicable to all remote tests
  .github/workflows/operator-ci.yml
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
Labels: team/cloud-native

#37484 [Test framework] Moving provider classes to specific package
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/RunOnServerTest.java
  test-framework/remote-providers/src/main/java/org/keycloak/testframework/remote/providers/timeoffset/TimeOffSetRealmResourceProvider.java
  test-framework/remote-providers/src/main/java/org/keycloak/testframework/remote/providers/timeoffset/TimeOffSetRealmResourceProviderFactory.java
  test-framework/remote-providers/src/main/resources/META-INF/services/org.keycloak.services.resource.RealmResourceProviderFactory
  test-framework/remote/src/main/java/org/keycloak/testframework/remote/RemoteTestFrameworkExtension.java
  test-framework/remote/src/main/java/org/keycloak/testframework/remote/runonserver/InjectRunOnServer.java
  test-framework/remote/src/main/java/org/keycloak/testframework/remote/runonserver/InjectTestClassServer.java
  test-framework/remote/src/main/java/org/keycloak/testframework/remote/runonserver/RunOnServerClient.java
  test-framework/remote/src/main/java/org/keycloak/testframework/remote/runonserver/RunOnServerSupplier.java
  test-framework/remote/src/main/java/org/keycloak/testframework/remote/runonserver/TestClassServer.java
  test-framework/remote/src/main/java/org/keycloak/testframework/remote/runonserver/TestClassServerSupplier.java
  test-framework/remote/src/test/java/org/keycloak/testframework/remote/runonserver/TestClassServerTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authentication/AuthenticatorConfigTest.java
Labels: area/test-framework

#37391 Make event metrics supported
  common/src/main/java/org/keycloak/common/Profile.java
  docs/guides/observability/event-metrics.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/EventOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionCategory.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HelpCommandDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
Labels: team/cloud-native

#37483 Remove public clients support for standard token exchange v2
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/AbstractTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/resources/token-exchange/testrealm-token-exchange-v2.json
Labels: team/cloud-native, team/core-clients, team/core-iam

#37489 Polishing support for id-token in standard token exchange
  core/src/main/java/org/keycloak/util/TokenUtil.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/AbstractTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/resources/token-exchange/testrealm-token-exchange-v2.json
Labels: team/cloud-native, team/core-clients, team/core-iam

#37494 Remove authorization settings from testrealm-token-exchange-v2.json
  testsuite/integration-arquillian/tests/base/src/test/resources/token-exchange/testrealm-token-exchange-v2.json
Labels: team/cloud-native, team/core-clients, team/core-iam

#37469 Replaces dagre dependency with @dagrejs/dagre.
  js/apps/admin-ui/package.json
  js/apps/admin-ui/src/authentication/components/diagram/auto-layout.ts
  js/pnpm-lock.yaml
Labels: team/ui

#37505 Set directAccessGrantsEnabled default value to false
  js/apps/admin-ui/src/clients/add/CapabilityConfig.tsx
  js/apps/admin-ui/src/clients/add/NewClientForm.tsx
Labels: team/ui

#37500 Supress the false positives reported by scorecards
  distribution/maven-plugins/osv-scanner.toml
  js/osv-scanner.toml
  testsuite/integration-arquillian/tests/other/webauthn/osv-scanner.toml
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam, team/security

#37329 BACKPORT: Fix redirect URL for linked accounts in account security section (#36…
  js/apps/account-ui/src/api/methods.ts
Labels: team/ui

#37221 Allow changing locale when using action tokens
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/RegisterPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37502 Specification parameters tests for standard token exchange v2
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/TokenExchangeRequest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37474 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
Labels: team/ui

#37524 Remove saml2 support for standard token exchange v2
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#37429 Add a HTML sanitizer for translated message resources
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_CN.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  misc/theme-verifier/pom.xml
  misc/theme-verifier/src/main/java/org/keycloak/themeverifier/VerifyMessageProperties.java
  misc/theme-verifier/src/test/java/org/keycloak/themeverifier/VerifyMessagePropertiesTest.java
  misc/theme-verifier/src/test/resources/changedAnchor_de.properties
  misc/theme-verifier/src/test/resources/changedAnchor_en.properties
  misc/theme-verifier/src/test/resources/duplicateKeys_en.properties
  misc/theme-verifier/src/test/resources/illegalHtmlTag_en.properties
  misc/theme-verifier/src/test/resources/noHtml_de.properties
  misc/theme-verifier/src/test/resources/noHtml_en.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_fi.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_lt.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_sk.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_sv.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_zh_CN.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_da.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_fa.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_hu.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_lt.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_nl.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_no.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_tr.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_uk.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ar.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_el.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fa.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fi.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_hr.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ko.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_lt.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_no.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_sk.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_sv.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_th.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_tr.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_uk.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_zh_CN.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_zh_TW.properties
  themes/src/main/resources/theme/base/admin/messages/messages_en.properties
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/ui

#37498 fix: allow ignored artifacts to find the default
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/IgnoredArtifacts.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/AbstractConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/IgnoredArtifactsTest.java
Labels: team/cloud-native

#37510 Add action token to the login action url
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37536 Add CLOMonitor Badge to the README
  README.md
Labels: team/security

#37541 Fix broken PNPM lockfile
  js/pnpm-lock.yaml
Labels: team/ui

#37445 Ensure LDAPStorageMapper.getGroupMembers is taking the fetch strategy…
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/UserRolesRetrieveStrategy.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapper.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/role/RoleLDAPStorageMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37561 Fixing unstable and flaky test
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationInvitationLinkTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#37572 Fixing flaky test
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionPriorityTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37576 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_de.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
Labels: team/ui

#37581 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
Labels: team/ui

#37534 Migrate ClientProtocolMapperTest, ClientScopeProtocolMapperTest to the new testsuite
  tests/base/src/test/java/org/keycloak/tests/admin/client/AbstractProtocolMapperTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/client/ClientProtocolMapperTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/client/ClientScopeProtocolMapperTest.java
Labels: team/cloud-native, flaky-test, area/test-framework

#37521 Move UserInfo request to AbstractOAuthClient
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/OAuthClientTest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractHttpGetRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/UserInfoRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/UserInfoResponse.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTransientSessionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1PublicClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/AbstractKerberosSingleRealmTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/DPoPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuth2DeviceAuthorizationGrantTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ServiceAccountTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#37553 The token exchange grant type not available in well-known endpoint wh…
  services/src/main/java/org/keycloak/protocol/oidc/OIDCWellKnownProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AbstractWellKnownProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#37550 Add client scope type option ANY to ClientScopesCondition
  services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientScopesCondition.java
  services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientScopesConditionFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesConditionTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#37501 Add switch to enable token-exchange to requester clients
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/add/CapabilityConfig.tsx
  js/apps/admin-ui/src/utils/useIsFeatureEnabled.ts
  server-spi-private/src/main/java/org/keycloak/protocol/oidc/OIDCConfigAttributes.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCAdvancedConfigWrapper.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/resources/token-exchange/testrealm-token-exchange-v2.json
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#37464 Add missing parent reference for theme-verifier-maven-plugin
  misc/theme-verifier/pom.xml
Labels: flaky-test

#37585 Autodetect RTL/LTR for email texts
  misc/theme-verifier/src/main/java/org/keycloak/themeverifier/VerifyMessageProperties.java
  services/src/main/java/org/keycloak/email/freemarker/FreeMarkerEmailTemplateProvider.java
  services/src/main/java/org/keycloak/theme/beans/LocaleBean.java
  services/src/test/java/org/keycloak/theme/beans/LocaleBeanTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/EmailTest.java
  themes/src/main/resources-community/theme/base/email/messages/messages_ar.properties
  themes/src/main/resources/theme/base/email/html/template.ftl
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#37463 fix: hardening to prevent usage of proxy-protocol with proxy-headers
  docs/guides/server/reverseproxy.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/ProxyOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ProxyPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#37583 Avoid surplus blanks in source strings
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
  js/apps/account-ui/src/resources/ShareTheResource.tsx
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  misc/theme-verifier/src/main/java/org/keycloak/themeverifier/VerifyMessageProperties.java
  misc/theme-verifier/src/test/java/org/keycloak/themeverifier/VerifyMessagePropertiesTest.java
  misc/theme-verifier/src/test/resources/blanks_en.properties
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/ui

#37492 Upgrade to Quarkus 3.19.0.CR1
  docs/documentation/upgrading/topics/changes/changes-26_2_0.adoc
  docs/guides/server/db.adoc
  pom.xml
  quarkus/config-api/src/main/java/org/keycloak/config/OptionBuilder.java
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/pom.xml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakRecorder.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ExecutionExceptionHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ShortErrorMessageHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/IgnoredArtifacts.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/liquibase/QuarkusJpaUpdaterProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/QuarkusCacheManagerProvider.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/AbstractConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/LoggingConfigurationTest.java
  quarkus/tests/integration/pom.xml
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FipsDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HttpDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/OracleTest.java
  quarkus/tests/junit5/pom.xml
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/CLIResult.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/KeycloakDistributionDecorator.java
  test-framework/db-oracle/pom.xml
  test-framework/db-oracle/src/main/java/org/keycloak/testframework/database/OracleDatabaseSupplier.java
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/servers/auth-server/quarkus/pom.xml
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/tracing/OTelTracingProviderTest.java
  testsuite/utils/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#37604 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_es.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ka.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_nl.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ka.properties
Labels: team/ui

#37012 Add support for Slovenian locale
  themes/src/main/resources-community/theme/base/account/messages/messages_sl.properties
  themes/src/main/resources-community/theme/base/account/theme.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_sl.properties
  themes/src/main/resources-community/theme/base/admin/theme.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_sl.properties
  themes/src/main/resources-community/theme/base/email/theme.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_sl.properties
  themes/src/main/resources-community/theme/base/login/theme.properties
  themes/src/main/resources/theme/base/email/messages/messages_en.properties
  themes/src/main/resources/theme/keycloak/login/theme.properties
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#36829 Return empty configProperties for CredentialBuilderFactory implementation
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/credentialbuilder/JwtCredentialBuilderFactory.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/credentialbuilder/LDCredentialBuilderFactory.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/credentialbuilder/SdJwtCredentialBuilderFactory.java
  services/src/test/java/org/keycloak/protocol/oid4vc/issuance/credentialbuilder/CredentialBuilderFactoryTest.java
Labels: missing/tests

#37609 Update default requested token-type and add switch for refresh token
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/advanced/OpenIdConnectCompatibilityModes.tsx
  server-spi-private/src/main/java/org/keycloak/protocol/oidc/OIDCConfigAttributes.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCAdvancedConfigWrapper.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/AbstractTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/resources/token-exchange/testrealm-token-exchange-v2.json
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#37462 Fix for importing Public Key PEM
  js/apps/admin-ui/src/clients/keys/ImportKeyDialog.tsx
Labels: team/ui

#37631 Fix broken lockfile + maintenance
  js/apps/account-ui/package.json
  js/apps/admin-ui/package.json
  js/libs/ui-shared/package.json
  js/package.json
  js/pnpm-lock.yaml
  js/pom.xml
Labels: team/ui, flaky-test

#37612 Support client policies for token exchange
  server-spi/src/main/java/org/keycloak/services/clientpolicy/ClientPolicyEvent.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/TokenExchangeGrantType.java
  services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientScopesCondition.java
  services/src/main/java/org/keycloak/services/clientpolicy/context/TokenExchangeRequestContext.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37646 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_de.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_es.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ka.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ka.properties
Labels: team/ui
