Repository keycloak/keycloak, pull requests merged in 2025-05, with the labels that each got.

#39383 BACKPORT: add translation for default locale (#39320)
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
Labels: team/ui

#39386 BACKPORT: value can also be a string when using default value (#39202)
  js/apps/admin-ui/src/components/client/ClientSelect.tsx
Labels: team/ui

#39387 BACKPORT: update client after import (#39056)
  js/apps/admin-ui/src/clients/ClientDetails.tsx
  js/apps/admin-ui/src/clients/keys/Keys.tsx
Labels: team/ui

#39388 BACKPORT: refresh when search is cleared (#39209)
  js/apps/admin-ui/src/groups/GroupTable.tsx
Labels: team/ui

#39389 BACKPORT: made the query paginated (#39060)
  js/apps/admin-ui/src/permissions-configuration/permission-configuration/ExistingPoliciesDialog.tsx
Labels: team/ui

#39390 BACKPORT: change readonly to disabled so that it differs from a normal field (#39016)
  js/libs/ui-shared/src/user-profile/TextComponent.tsx
Labels: team/ui

#39391 BACKPORT: changed home button to reload (#38967)
  js/apps/admin-ui/src/components/error/ErrorRenderer.tsx
Labels: team/ui

#39393 BACKPORT: clear form values before setting new one (#38805)
  js/apps/admin-ui/src/user-federation/UserFederationLdapSettings.tsx
Labels: team/ui

#39394 BACKPORT: refresh realm when policy changed (#38774)
  js/apps/admin-ui/src/authentication/policies/PasswordPolicy.tsx
Labels: team/ui

#39395 BACKPORT: use onDataChange instead of text changed (#38771)
  js/apps/admin-ui/src/clients/keys/GenerateKeyDialog.tsx
Labels: team/ui

#39396 BACKPORT: remove delete button when flow is in use (#38861)
  js/apps/admin-ui/src/authentication/FlowDetails.tsx
Labels: team/ui

#38835 Improve a11y by matching FormLabel `for` attribute with SingleSelectControl `id` attribute
  js/apps/admin-ui/test/clients/advanced.ts
  js/apps/admin-ui/test/clients/saml.ts
  js/apps/admin-ui/test/identity-providers/main.ts
  js/apps/admin-ui/test/identity-providers/saml.ts
  js/apps/admin-ui/test/organization/idp.ts
  js/libs/ui-shared/src/controls/FormLabel.tsx
  js/libs/ui-shared/src/controls/select-control/SingleSelectControl.tsx
  js/libs/ui-shared/src/controls/select-control/TypeaheadSelectControl.tsx
Labels: team/ui, flaky-test

#39343 Tests failing with embedded undertow due the infinispan
  testsuite/integration-arquillian/tests/base/src/test/resources/META-INF/keycloak-server.json
  testsuite/integration-arquillian/tests/pom.xml
  testsuite/utils/src/main/resources/META-INF/keycloak-server.json
  testsuite/utils/src/main/resources/cluster-test-ispn.xml
  testsuite/utils/src/main/resources/local-test-ispn.xml
Labels: team/cloud-native, team/core-clients, team/core-iam

#39363 Document how to configure Istio to allow for JGroups mTLS
  docs/documentation/upgrading/topics/changes/changes-26_2_0.adoc
  docs/guides/server/caching.adoc
Labels: team/cloud-native

#39413 fix: relaxing the ready=false reason to make the test less flaky
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
Labels: team/cloud-native

#39412 making the update reason and recreate annotations stable
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/UpdateTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/CRAssert.java
Labels: team/cloud-native

#39269 Reuse InfinispanClusterProvider instances in InfinispanClusterProviderFactory
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProvider.java
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanNotificationsManager.java
  testsuite/utils/src/main/resources/log4j.properties
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39382 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_es.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_fr.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
Labels: team/ui

#39421 Document how to configure Istio to allow for JGroups mTLS
  docs/documentation/upgrading/topics/changes/changes-26_2_0.adoc
  docs/guides/server/caching.adoc
Labels: team/cloud-native

#39430 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ka.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ka.properties
Labels: team/ui

#39196 Change JWKS header
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolService.java
  services/src/main/java/org/keycloak/utils/MediaType.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/JwksResponse.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AbstractWellKnownProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39446 Add option to log details in the JBossLoggingEventListenerProvider (#39361) (26.2)
  js/apps/admin-ui/src/realm-settings/event-config/EventConfigForm.tsx
  services/pom.xml
  services/src/main/java/org/keycloak/events/log/JBossLoggingEventListenerProvider.java
  services/src/main/java/org/keycloak/events/log/JBossLoggingEventListenerProviderFactory.java
  services/src/test/java/org/keycloak/events/log/JBossLoggingEventListenerProviderTest.java
  services/src/test/resources/log4j.properties
  services/src/test/resources/logging.properties
Labels: team/ui

#39141 improved valid check
  js/apps/admin-ui/src/clients/scopes/EvaluateScopes.tsx
Labels: team/ui

#39317 fix required check of groups picker
  js/apps/admin-ui/src/permissions-configuration/resource-types/GroupSelect.tsx
Labels: team/ui

#39318 only render logo property when it is set
  js/apps/admin-ui/src/realm-settings/themes/ThemesTab.tsx
Labels: team/ui

#39453 Fix outdated link to Infinispan docs
  docs/guides/server/caching.adoc
Labels: team/cloud-native

#39455 fix: removing ipv4 preference from quarkus auth servers
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
Labels: team/cloud-native, team/core-clients, team/core-iam

#39422 Clarify podman use
  docs/guides/server/containers.adoc
Labels: team/cloud-native

#39462 Clarify podman use
  docs/guides/server/containers.adoc
Labels: team/cloud-native

#39459 fix: don't treat quarkus property changes as hard errors
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
Labels: team/cloud-native

#38899 fix: excluding update commands from reaug
  docs/guides/server/bootstrap-admin-recovery.adoc
  docs/guides/server/importExport.adoc
  docs/guides/server/update-compatibility.adoc
Labels: team/cloud-native

#39432 feat: organization authenticator : bypass username form when login_hint is set
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39325 [FGAP] Refactor permission evaluation code for V2
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  server-spi-private/src/main/java/org/keycloak/models/AdminRoles.java
  server-spi-private/src/main/java/org/keycloak/models/ImpersonationConstants.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  services/src/main/java/org/keycloak/services/managers/RealmManager.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/ClientPermissionsV2.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/FineGrainedAdminPermissionEvaluator.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/GroupPermissionsV2.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/ModelRecord.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RealmAuth.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissionsV2.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissionsV2.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IllegalAdminUpgradeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ImpersonationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/ClientTokenExchangeSAML2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/TokenExchangeTestUtils.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39464 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
Labels: team/ui

#39481 take into account value request parameter in the claims request for a…
  services/src/main/java/org/keycloak/protocol/oidc/utils/AcrUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LevelOfAssuranceFlowTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39449 Return user session started time when client note is missing for offline
  server-spi/src/main/java/org/keycloak/models/AuthenticatedClientSessionModel.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39031 Disable social links after being clicked
  themes/src/main/resources/theme/base/login/login-username.ftl
  themes/src/main/resources/theme/base/login/login.ftl
  themes/src/main/resources/theme/base/login/template.ftl
  themes/src/main/resources/theme/keycloak.v2/login/social-providers.ftl
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
  themes/src/main/resources/theme/keycloak.v2/login/theme.properties
  themes/src/main/resources/theme/keycloak/login/theme.properties
Labels: team/ui

#38851 Log out other sessions including offline sessions on password change
  common/src/main/java/org/keycloak/common/Profile.java
  docs/documentation/upgrading/topics/changes/changes-26_3_0.adoc
  services/src/main/java/org/keycloak/authentication/AuthenticatorUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionResetPasswordTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39344 Prevent a log-and-throw situation where errors appear in the log that are handled
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/logging/KeycloakLogFilter.java
  quarkus/runtime/src/main/resources/application.properties
Labels: team/cloud-native, flaky-test

#39503 Update Job Pod is listed in the keycloak service
  operator/src/main/java/org/keycloak/operator/Constants.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/UpdateTest.java
Labels: team/cloud-native

#39470 Check if LDAP entry is still valid before validating duplicate emails
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/UserAttributeLDAPStorageMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPSyncTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39498 win-fix: improve process termination handling in RawKeycloakDistribut…
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
Labels: team/cloud-native

#39501 Prevent a log-and-throw situation where errors appear in the log that are handled
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/logging/KeycloakLogFilter.java
  quarkus/runtime/src/main/resources/application.properties
Labels: team/cloud-native

#39511 fix: removing ipv4 preference from quarkus auth servers
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
Labels: team/cloud-native, team/core-clients, team/core-iam

#39504 Return user session started time when client note is missing for offline (26.2)
  server-spi/src/main/java/org/keycloak/models/AuthenticatedClientSessionModel.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39510 Return user session started time when client note is missing for offline (26.0)
  server-spi/src/main/java/org/keycloak/models/AuthenticatedClientSessionModel.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39148 Fix scope validation for realm-level credential definitions in Authorization Code flow
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCJWTIssuerEndpointTest.java
Labels: team/cloud-native, area/oid4vc, team/core-clients, team/core-iam

#39495 Keycloak Admin UI : Incorrect tooltip over enabled features
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#39370 fix: performing inline user import for multi-file
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  model/storage-services/src/main/java/org/keycloak/exportimport/dir/DirImportProvider.java
  model/storage-services/src/main/java/org/keycloak/exportimport/util/ImportUtils.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  server-spi-private/src/main/java/org/keycloak/storage/ExportImportManager.java
  services/src/main/java/org/keycloak/services/managers/RealmManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/exportimport/OrganizationExportTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39548 Edit Operator Guide
  docs/guides/operator/advanced-configuration.adoc
  docs/guides/operator/customizing-keycloak.adoc
  docs/guides/operator/installation.adoc
  docs/guides/operator/rolling-updates.adoc
Labels: team/cloud-native

#39468 Skip partial evaluation if there is no realm bound to the session
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserPartialEvaluationProvider.java
  server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java
  server-spi-private/src/main/java/org/keycloak/authorization/PartialEvaluator.java
  services/src/main/java/org/keycloak/services/DefaultKeycloakContext.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39460 fix: removing KeycloakApplication usage of keycloak-add-user.json
  services/src/main/java/org/keycloak/services/ServicesLogger.java
  services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java
  test-framework/core/src/main/java/org/keycloak/testframework/config/Config.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/AbstractKeycloakServerSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/KeycloakServerConfigBuilder.java
  tests/base/src/test/java/org/keycloak/tests/welcomepage/WelcomePageTest.java
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/test/resources/keycloak-add-user.json
  testsuite/integration-arquillian/tests/other/pom.xml
  testsuite/integration-arquillian/tests/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#37916 Skip updating account controls if no control is set when enabling/disabling users
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/msad/MSADUserAccountControlStorageMapper.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/msad/UserAccountControl.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPMSADMapperTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39531 Do not show email during registation if user has no permission
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterWithUserProfileTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39565 Refresh back button for chrome 136
  .github/actions/install-chrome/action.yml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/UIUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BrowserButtonsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39591 Fix callouts
  docs/documentation/server_development/topics/providers.adoc
  docs/guides/operator/rolling-updates.adoc
  docs/guides/server/caching.adoc
Labels: team/cloud-native

#39593 Fix callouts
  docs/documentation/server_development/topics/providers.adoc
  docs/guides/operator/rolling-updates.adoc
  docs/guides/server/caching.adoc
Labels: team/cloud-native

#39579 Refresh back button for chrome 136 (26.2)
  .github/actions/install-chrome/action.yml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/UIUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BrowserButtonsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39603 Patch kubernetes stack with port_range=0
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/CacheManagerFactory.java
Labels: team/cloud-native

#39242 fixed style of textarea tag
  themes/src/main/resources/theme/keycloak.v2/login/user-profile-commons.ftl
Labels: team/ui

#39415 fetch already set values so the labels are known
  js/apps/admin-ui/src/clients/authorization/ResourcesPolicySelect.tsx
Labels: team/ui

#39444 add select all to event table
  js/apps/admin-ui/src/realm-settings/event-config/EventsTab.tsx
  js/apps/admin-ui/src/realm-settings/event-config/EventsTypeTable.tsx
Labels: team/ui

#39526 should re register as the tabs make it unmount
  js/apps/admin-ui/src/components/key-value-form/KeyValueInput.tsx
Labels: team/ui

#39632 added missing setup
  js/apps/admin-ui/src/authentication/policies/OtpPolicy.tsx
Labels: team/ui

#39555 added proper filtering and fixed onToggle
  js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx
Labels: team/ui

#39642 Return only manage permissions when listing users via administration console
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/BruteForceUsersResource.java
Labels: team/ui

#39584 fix: updating the examples to bind docker/podman 8080 only to localhost
  docs/guides/getting-started/templates/start-keycloak-container.adoc
  docs/guides/server/containers.adoc
Labels: team/cloud-native

#39534 Disable social links after being clicked (#39031) (26.0)
  themes/src/main/resources/theme/base/login/login-username.ftl
  themes/src/main/resources/theme/base/login/login.ftl
  themes/src/main/resources/theme/base/login/template.ftl
  themes/src/main/resources/theme/keycloak.v2/login/social-providers.ftl
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
  themes/src/main/resources/theme/keycloak.v2/login/theme.properties
  themes/src/main/resources/theme/keycloak/login/theme.properties
Labels: team/ui, flaky-test

#39409 Fix realm attributes example and correct HTTP method in OID4VCI docs
  docs/documentation/server_admin/topics/oid4vci/vc-issuer-configuration.adoc
Labels: area/oid4vc

#39652 More eagerly clear references to client sessions from the user session
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/UserSessionAdapter.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39601 Fix list design in the cache documentation
  docs/guides/server/caching.adoc
Labels: team/cloud-native

#39535 use the selected options in the render
  js/libs/ui-shared/src/controls/select-control/SelectControl.tsx
  js/libs/ui-shared/src/controls/select-control/SingleSelectControl.tsx
  js/libs/ui-shared/src/controls/select-control/TypeaheadSelectControl.tsx
Labels: team/ui, flaky-test

#39675 The transport stack defined in the cache XML should take precedence over internal jdbc-ping default
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
Labels: team/cloud-native

#39666 Reorder operations to put the slowest operation at the end
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
Labels: flaky-test

#39664 Remove redundant username error display logic
  themes/src/main/resources/theme/keycloak.v2/login/login-username.ftl
Labels: team/ui

#39688 More eagerly clear references to client sessions from the user session
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/UserSessionAdapter.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39690 Process locale param in expired page
  services/src/main/java/org/keycloak/services/util/AuthenticationFlowURLHelper.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginExpiredPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/LoginPageTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39696 Remove redundant username error display logic
  themes/src/main/resources/theme/keycloak.v2/login/login-username.ftl
Labels: team/ui

#31275 fix: persist refresh token for IDP token exchange
  model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAResourceServerStore.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39174 add description to groups
  core/src/main/java/org/keycloak/representations/idm/GroupRepresentation.java
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/groups/GroupTable.tsx
  js/apps/admin-ui/src/groups/GroupsModal.tsx
  js/apps/admin-ui/src/groups/GroupsSection.tsx
  js/apps/admin-ui/src/groups/components/GroupTree.tsx
  js/apps/admin-ui/test/groups/list.spec.ts
  js/apps/admin-ui/test/groups/list.ts
  js/libs/keycloak-admin-client/src/defs/groupRepresentation.ts
  js/libs/keycloak-admin-client/test/groups.spec.ts
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/GroupAdapter.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedGroup.java
  model/jpa/src/main/java/org/keycloak/models/jpa/GroupAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/GroupEntity.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-26.3.0.xml
  model/jpa/src/main/resources/META-INF/jpa-changelog-master.xml
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi-private/src/test/java/org/keycloak/models/KeycloakModelUtilsTest.java
  server-spi/src/main/java/org/keycloak/models/GroupModel.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/HardcodedGroupStorageProvider.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#39714 fix: keeping the image consistent for the recreate strategy
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/main/java/org/keycloak/operator/update/impl/RecreateOnImageChangeUpdateLogic.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/CRAssert.java
Labels: team/cloud-native

#39678 BACKPORT: should re register as the tabs make it unmount (#39526)
  js/apps/admin-ui/src/components/key-value-form/KeyValueInput.tsx
Labels: team/ui

#39679 BACKPORT: added missing setup (#39632)
  js/apps/admin-ui/src/authentication/policies/OtpPolicy.tsx
Labels: team/ui

#39680 BACKPORT: use the selected options in the render (#39535)
  js/libs/ui-shared/src/controls/select-control/SelectControl.tsx
  js/libs/ui-shared/src/controls/select-control/SingleSelectControl.tsx
  js/libs/ui-shared/src/controls/select-control/TypeaheadSelectControl.tsx
Labels: team/ui

#39681 BACKPORT: added proper filtering and fixed onToggle (#39555)
  js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx
Labels: team/ui

#39550 Inconsistency in User enabled status in Rest query results.
  docs/documentation/upgrading/topics/changes/changes-26_3_0.adoc
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39730 fix: keeping the image consistent for the recreate strategy
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/main/java/org/keycloak/operator/update/impl/RecreateOnImageChangeUpdateLogic.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/CRAssert.java
Labels: team/cloud-native

#39416 Make max auth age configurable for all required actions by default
  docs/documentation/server_admin/topics/users/con-aia.adoc
  docs/documentation/upgrading/topics/changes/changes-26_3_0.adoc
  server-spi-private/src/main/java/org/keycloak/authentication/RequiredActionFactory.java
  server-spi-private/src/main/java/org/keycloak/authentication/RequiredActionProvider.java
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  services/src/main/java/org/keycloak/authentication/requiredactions/DeleteAccount.java
  services/src/main/java/org/keycloak/authentication/requiredactions/RecoveryAuthnCodesAction.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdatePassword.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java
  tests/base/src/test/java/org/keycloak/tests/admin/authentication/RequiredActionsTest.java
  tests/custom-providers/src/main/java/org/keycloak/testsuite/actions/DummyConfigurableRequiredActionFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionResetPasswordTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39330 Redirect using client data when the session has expired
  services/src/main/java/org/keycloak/services/resources/SessionCodeChecks.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultipleTabsLoginTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39539 Fix account console for usage with secure-session client-policy (#37447)
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/TermsAndConditionsTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39733 Inconsistent "Forgot Password" behavior reveals user account information
  services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39702 use scroll into view instead of hash override
  js/libs/ui-shared/src/scroll-form/ScrollForm.tsx
Labels: team/ui

#39731 fix: adding a doc note about clean up
  docs/guides/operator/realm-import.adoc
Labels: team/cloud-native

#39706 Persist refresh token for IDP token exchange
  model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAResourceServerStore.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39754 BACKPORT: use scroll into view instead of hash override (#39702)
  js/libs/ui-shared/src/scroll-form/ScrollForm.tsx
Labels: team/ui

#39560 Persistent user session for client scopes evaluate function
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientResource.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientScopeEvaluateResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientScopeEvaluateResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/ClientScopeEvaluateTest.java
Labels: missing/tests, team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39647 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ca.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ca.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ja.properties
Labels: team/ui, flaky-test

#39764 do not query credentials when user disabled
  js/apps/admin-ui/src/user/UserCredentials.tsx
Labels: team/ui

#39406 in development mode use the message.properties as file
  js/apps/admin-ui/CONTRIBUTING.md
  js/apps/admin-ui/package.json
  js/apps/admin-ui/src/i18n/i18n.ts
  js/apps/admin-ui/vite.config.ts
  js/pnpm-lock.yaml
Labels: team/ui

#39767 fix: SAML certificate in UI not refreshed after keystore import
  js/apps/admin-ui/src/clients/keys/SamlImportKeyDialog.tsx
  js/apps/admin-ui/src/clients/keys/SamlKeys.tsx
Labels: team/ui

#37640 Add supported config options for additional datasources
  quarkus/config-api/src/main/java/org/keycloak/config/DatabaseOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/Option.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionBuilder.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionCategory.java
  quarkus/config-api/src/main/java/org/keycloak/config/TransactionOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/Configuration.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TransactionPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/WildcardPropertyMapper.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/AbstractConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/DatasourcesConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesAutoBuildDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/dist/DatasourcesDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBootstrapAdminService.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBootstrapAdminUser.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
Labels: team/cloud-native, flaky-test

#39778 fix: don't treat quarkus property changes as hard errors (#39459)
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
Labels: team/cloud-native

#39161 Migration util improvements
  tests/MANUAL_MIGRATION.md
  tests/MIGRATING_TESTS.md
  tests/MOVING_TESTS.md
  tests/migration-util/src/main/java/org/keycloak/test/migration/CommonStatementsRewrite.java
  tests/migration-util/src/main/java/org/keycloak/test/migration/MigrateTest.java
  tests/migration-util/src/main/java/org/keycloak/test/migration/RenameImportsRewrite.java
  tests/migration-util/src/main/java/org/keycloak/test/migration/TestRewrite.java
  tests/migration-util/src/main/java/org/keycloak/test/migration/UpdateAssertsRewrite.java
Labels: area/test-framework

#39775 Fix tests in CI when running with a proper browser
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/UpdateAccountInformationPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTransientSessionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/OidcClaimToUserSessionNoteMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/BackchannelLogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/AbstractBrokerSelfRegistrationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39840 Upgrade to Quarkus 3.20.1
  pom.xml
Labels: team/cloud-native

#39827 Revise DPoP Codes - refactor remove unused methods
  services/src/main/java/org/keycloak/services/util/DPoPUtil.java
Labels: flaky-test

#39825 Skip AIA for webauthn register if a crendential of the correct type already exists
  docs/documentation/release_notes/topics/26_3_0.adoc
  docs/documentation/server_admin/topics/authentication/webauthn.adoc
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnRegister.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/AppInitiatedActionWebAuthnSkipIfExistsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/AppInitiatedActionWebAuthnTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/passwordless/AppInitiatedActionPwdLessSkipIfExistsTest.java
Labels: missing/docs, team/cloud-native, team/core-clients, team/core-iam

#39774 introduce sharding
  .github/workflows/js-ci.yml
  js/apps/admin-ui/output-config.ts
  js/apps/admin-ui/playwright.config.ts
Labels: team/ui

#39763 Fix scope validation for realm-level credential definitions in Authorization Code flow (#39148)
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCJWTIssuerEndpointTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39856 Revise Client Policies Codes - AbstractClientPoliciesTest
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39895 reverted sharding #397774
  .github/workflows/js-ci.yml
  js/apps/admin-ui/output-config.ts
  js/apps/admin-ui/playwright.config.ts
Labels: team/ui

#39848 Login[v2]: use field.checkbox in password-commons
  themes/src/main/resources/theme/keycloak.v2/login/password-commons.ftl
Labels: team/ui

#39631 Moved PKCE Code Challenge Method to more prominent section
  js/apps/admin-ui/src/clients/add/CapabilityConfig.tsx
  js/apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
  js/apps/admin-ui/test/clients/advanced.spec.ts
  js/apps/admin-ui/test/clients/advanced.ts
  js/apps/admin-ui/test/clients/details.spec.ts
  js/apps/admin-ui/test/clients/details.ts
Labels: team/ui

#39884 Only reuse SMTP authentication data for testing endpoint when the same auth, host, port and user are passed (26.0)
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/SMTPConnectionTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39756 New UI Customization Guide
  docs/guides/images/ui-customization/account-console-with-avatar.png
  docs/guides/images/ui-customization/avatar-validation.png
  docs/guides/images/ui-customization/color-chooser.png
  docs/guides/images/ui-customization/custom-account-console.png
  docs/guides/images/ui-customization/device-activity-after.png
  docs/guides/images/ui-customization/device-activity-before.png
  docs/guides/images/ui-customization/easy-theme-find-color.png
  docs/guides/images/ui-customization/empty-user-federation-page.png
  docs/guides/images/ui-customization/keycloak_logo.png
  docs/guides/images/ui-customization/login-sunrise.png
  docs/guides/images/ui-customization/myPage.png
  docs/guides/images/ui-customization/picture-attribute-general-settings.png
  docs/guides/images/ui-customization/quick-theme-overview.png
  docs/guides/images/ui-customization/readonly-user-storage-provider-with-config.png
  docs/guides/images/ui-customization/simple-quick-theme-changes.png
  docs/guides/images/ui-customization/storage-provider-created.png
  docs/guides/images/ui-customization/user-federation-page.png
  docs/guides/pom.xml
  docs/guides/ui-customization/avatars.adoc
  docs/guides/ui-customization/creating-your-own-console.adoc
  docs/guides/ui-customization/index.adoc
  docs/guides/ui-customization/introduction.adoc
  docs/guides/ui-customization/localization.adoc
  docs/guides/ui-customization/quick-theme.adoc
  docs/guides/ui-customization/themes-react.adoc
  docs/guides/ui-customization/themes.adoc
  docs/guides/ui-customization/welcome-theme.adoc
Labels: team/ui

#39943 LDAP Edit mode option is required but not marked
  js/apps/admin-ui/src/user-federation/ldap/LdapSettingsSearching.tsx
Labels: team/ui

#39938 Remove duplicate success message
  js/apps/admin-ui/src/user-federation/shared/ExtendedHeader.tsx
Labels: team/ui

#39752 Avoid resolving a client scope if it was requested using the dynamic scope format
  server-spi/src/main/java/org/keycloak/models/ClientScopeModel.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationScope.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationOIDCProtocolMapperTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39892 Revise Client Policies Codes - ClientPoliciesConditionTest
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesConditionTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39914 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ja.properties
Labels: team/ui

#39972 Fix duplicated word in permissionPoliciesHelp message
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#39981 Revise Client Policies Codes - ClientPoliciesExecutorTest
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExecutorTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39873 Add example with TCPPING discovery protocol to documentation
  docs/guides/server/caching.adoc
Labels: team/cloud-native

#39842 [26.0] Upgrade to Quarkus 3.15.5
  pom.xml
Labels: team/cloud-native

#39751 Add experimental feature rolling-updates:v2 that allows rolling updat…
  common/src/main/java/org/keycloak/common/Profile.java
  docs/documentation/release_notes/topics/26_3_0.adoc
  docs/documentation/tests/src/test/resources/ignored-links
  docs/guides/server/update-compatibility.adoc
  model/infinispan/src/main/java/org/keycloak/infinispan/compatibility/CachingCompatibilityMetadataProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractUpdatesCommand.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/UpdateCommandDistTest.java
  server-spi-private/src/main/java/org/keycloak/compatibility/AggregatedCompatibilityResult.java
  server-spi-private/src/main/java/org/keycloak/compatibility/CompatibilityResult.java
  server-spi-private/src/main/java/org/keycloak/compatibility/ProviderIncompatibleResult.java
  server-spi-private/src/main/java/org/keycloak/compatibility/Util.java
  server-spi-private/src/main/java/org/keycloak/migration/ModelVersion.java
  services/src/main/java/org/keycloak/compatibility/KeycloakCompatibilityMetadataProvider.java
  services/src/test/java/org/keycloak/compatibility/KeycloakCompatibilityMetadataProviderTest.java
Labels: team/cloud-native, flaky-test

#40015 Revise Client Policies Codes - ClientPoliciesTest
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#40040 Use more concise PKCE method label in OIDC Client config
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#40063 [Keycloak CI] - Cookies Tests - KcOidcBrokerTokenExchangeTest
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#40051 Revise Client Policies Codes - OAuth 2.1 tests
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/AbstractFAPITest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1ConfidentialClientTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#40053 Revise Client Policies Codes - FAPI1Test
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPI1Test.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#40057 Revise Client Policies Codes - FAPICIBATest
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPICIBATest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#40075 Initialize the supported locales to empty set in RealmAttributeUpdater to revert back OK
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/updaters/RealmAttributeUpdater.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40089 Throw an exception if transport mTLS keystore or Truststore does not exist
  model/infinispan/src/main/java/org/keycloak/jgroups/certificates/DefaultJGroupsCertificateProviderFactory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/CachingPropertyMappers.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/CacheEmbeddedMtlsDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/UpdateCommandDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/Util.java
Labels: team/cloud-native
