Repository keycloak/keycloak, pull requests merged in 2025-08, with the labels that each got.

#41599 Move flaky test to top so it will run first.
  js/apps/admin-ui/test/user-federation/kerberos.spec.ts
Labels: team/ui

#41546 Adjust the test to dynamically remove all sessions
  js/apps/account-ui/test/account-security/device-activity.spec.ts
  js/apps/account-ui/test/realm.setup.ts
  js/apps/account-ui/test/realm.teardown.ts
Labels: team/ui

#41618 Utilise table to display Features
  docs/guides/server/features.adoc
  docs/guides/server/update-compatibility.adoc
  docs/guides/templates/features.adoc
Labels: team/cloud-native

#41240 Show transport media for WebAuthn authenticators in Account console
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
  services/src/main/java/org/keycloak/credential/WebAuthnCredentialProvider.java
Labels: team/ui

#41650 Re-enable test for setting the basic info in the account console
  js/apps/account-ui/test/personal-info/personal-info.spec.ts
Labels: team/ui

#41649 Using a different attrib name fixes flakiness
  js/apps/admin-ui/test/realm-settings/userprofile.spec.ts
Labels: team/ui

#41642 Ensure cache configuration has correct number of owners
  docs/guides/server/caching.adoc
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/CacheConfigurator.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/DefaultCacheEmbeddedConfigProviderFactory.java
Labels: team/cloud-native, flaky-test, team/sre

#41647 enhance: adding the ability to get the root config from a Scope
  core/src/main/java/org/keycloak/Config.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/DefaultCacheEmbeddedConfigProviderFactory.java
  quarkus/config-api/src/main/java/org/keycloak/config/MetricsOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/MicroProfileConfigProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/MetricsPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/ConfigurationTest.java
  server-spi-private/src/main/java/org/keycloak/component/ComponentModelScope.java
  server-spi/src/main/java/org/keycloak/provider/ProviderFactory.java
  services/src/main/java/org/keycloak/credential/PasswordCredentialProviderFactory.java
  services/src/test/java/org/keycloak/utils/JsonConfigProvider.java
  services/src/test/java/org/keycloak/vault/PlainTextVaultProviderFactoryTest.java
Labels: team/cloud-native, flaky-test, team/sre

#41627 feat(operator): add support for custom labels in ingress
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngressDependentResource.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/IngressSpec.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/IngressLogicTest.java
Labels: team/cloud-native

#41685 fix: ensuring the ordering of the providers
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerWellKnownProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#41689 Cannot use dev-file for additional datasources
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/DatasourcesConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/CustomJpaEntityProviderDistTest.java
Labels: team/cloud-native

#41360 [26.2] Upgrade to Quarkus 3.20.2
  pom.xml
Labels: status/hold

#41691 [26.3] Ensure cache configuration has correct number of owners
  docs/guides/server/caching.adoc
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/CacheConfigurator.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/DefaultCacheEmbeddedConfigProviderFactory.java
Labels: team/cloud-native

#41671 Allow forwarding parameters set as a client note in the authentication session
  docs/documentation/server_admin/topics/identity-broker/oidc.adoc
  services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerParameterForwardTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#41693 Allow setting the number of owners
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/InfinispanConnectionProvider.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/CacheConfigurator.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/DefaultCacheEmbeddedConfigProviderFactory.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigKeepAliveDistTest.java
Labels: team/cloud-native, team/sre

#41712 Assert correct message for base url
  js/apps/admin-ui/test/clients/saml.spec.ts
Labels: team/ui

#41702 Default to stretched clusters on Kubernetes when possible
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
  docs/guides/operator/advanced-configuration.adoc
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
Labels: team/cloud-native, team/sre

#41746 Add zh_Hant.properties file
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_Hant.properties
Labels: team/ui

#41749 Skip update email required action if email attribute is not writable
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateEmail.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateEmailTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#41727 Test framework config builders name unification
  test-framework/core/src/main/java/org/keycloak/testframework/realm/ClientConfigBuilder.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/Collections.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/RealmConfigBuilder.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/UserConfigBuilder.java
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/EmailTest.java
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/RealmSpecificAdminClientTest.java
  test-framework/oauth/src/main/java/org/keycloak/testframework/oauth/DefaultOAuthClientConfiguration.java
  tests/base/src/test/java/org/keycloak/tests/admin/AbstractPermissionsTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/AdminConsoleWhoAmILocaleTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/AuthzCleanupTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/ConsentsTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/ImpersonationTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/SMTPConnectionTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/UsersTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/AuthzClientConfig.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/RealmAdminPermissionsConfig.java
  tests/base/src/test/java/org/keycloak/tests/admin/client/InstallationTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/event/AdminEventAuthDetailsTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/event/EmailEventListenerTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/event/EventConfigTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/event/LoginEventsTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/group/GroupMappersTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/group/GroupTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/user/UserCredentialTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/user/UserGroupTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/user/UserSearchTest.java
Labels: area/test-framework

#41616 RejectImplicitGrantExecutor does not return an error when a PAR request includes Implicit or Hybrid response type
  services/src/main/java/org/keycloak/services/clientpolicy/executor/RejectImplicitGrantExecutor.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#41626 Login[v2]: "Update email" screen is not polished
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/auth/page/login/UpdateEmailPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/EmailUpdatePage.java
  themes/src/main/resources/theme/keycloak.v2/login/update-email.ftl
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#41660 Add Azerbaijani translations for login, email, and account themes
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_az.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_az.properties
  themes/src/main/resources-community/theme/base/account/theme.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_az.properties
  themes/src/main/resources-community/theme/base/email/theme.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_az.properties
  themes/src/main/resources-community/theme/base/login/theme.properties
Labels: team/ui

#41795 Backporting fix set on PR #41004
  services/src/main/java/org/keycloak/services/managers/ResourceAdminManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40268 Add workflows and utils to review stability of testsuite
  .github/workflows/stability-base-reruns.yml
  .github/workflows/stability-base.yml
  .github/workflows/stability-clustering.yml
  .github/workflows/stability-js-ci.yml
  misc/test-stability/.gitignore
  misc/test-stability/README.md
  misc/test-stability/download-logs.sh
  misc/test-stability/parse-logs.sh
  misc/test-stability/pom.xml
  misc/test-stability/schedule-runs.sh
  misc/test-stability/src/main/java/org/keycloak/test/logparser/GitHubRun.java
  misc/test-stability/src/main/java/org/keycloak/test/logparser/LogFailure.java
  misc/test-stability/src/main/java/org/keycloak/test/logparser/LogParser.java
  misc/test-stability/src/main/java/org/keycloak/test/logparser/MarkdownReportGenerator.java
  misc/test-stability/src/main/java/org/keycloak/test/logparser/PlaywrightLogParser.java
  misc/test-stability/src/main/java/org/keycloak/test/logparser/ReportGenerator.java
  misc/test-stability/src/main/java/org/keycloak/test/logparser/RunFailure.java
  misc/test-stability/src/main/java/org/keycloak/test/logparser/SureFireLogParser.java
  misc/test-stability/src/main/java/org/keycloak/test/logparser/TestFailure.java
  misc/test-stability/src/main/java/org/keycloak/test/logparser/TestReport.java
  misc/test-stability/src/main/java/org/keycloak/test/logparser/TextReportGenerator.java
  misc/test-stability/src/main/java/org/keycloak/test/logparser/Utils.java
  misc/test-stability/status.sh
Labels: flaky-test

#41841 Use Optional instead of getOrDefault for settings in testSMTPConnection (26.3)
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
Labels: status/ready

#41861 Fix unbalanced HTML tags in login form templates (#41860)
  themes/src/main/resources/theme/base/login/delete-account-confirm.ftl
  themes/src/main/resources/theme/base/login/login-update-password.ftl
  themes/src/main/resources/theme/base/login/login-update-profile.ftl
  themes/src/main/resources/theme/base/login/login-verify-email.ftl
  themes/src/main/resources/theme/base/login/update-email.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-config-totp.ftl
Labels: team/ui

#41857 fix: using the non-deprecated console color option
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
Labels: team/cloud-native

#41856 "linked-accounts" endpoint displays all Identity providers
  docs/documentation/release_notes/topics/26_4_0.adoc
  docs/documentation/server_admin/topics/identity-broker/configuration.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/identity-providers/add/AdvancedSettings.tsx
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaIdentityProviderStorageProvider.java
  server-spi/src/main/java/org/keycloak/models/IdentityProviderModel.java
  server-spi/src/main/java/org/keycloak/models/IdentityProviderShowInAccountConsole.java
  services/src/main/java/org/keycloak/services/resources/account/LinkedAccountsResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/LinkedAccountsRestServiceTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#41876 Adjust the test to dynamically remove all sessions
  js/apps/account-ui/test/account-security/device-activity.spec.ts
Labels: team/ui

#41815 Change naming for disabling additional datasource
  quarkus/config-api/src/main/java/org/keycloak/config/DatabaseOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/DatasourcesConfigurationTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBootstrapAdminService.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBootstrapAdminUser.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
Labels: team/cloud-native

#41768 fix: adding raw environment variables
  docs/guides/operator/advanced-configuration.adoc
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakSpec.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/CRSerializationTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
  operator/src/test/resources/test-serialization-keycloak-cr.yml
Labels: team/cloud-native

#40620 Show required fields when configuring protocol mappers
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
  js/apps/admin-ui/src/components/dynamic/StringComponent.tsx
  services/src/main/java/org/keycloak/protocol/oidc/mappers/OIDCAttributeMapperHelper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/UserSessionNoteMapper.java
Labels: team/ui

#41893 fix: ensuring streams are closed
  common/src/main/java/org/keycloak/common/util/KeystoreUtil.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/util/AuthUtil.java
Labels: team/cloud-native

#41715 Allow and control sending UTF-8 emails in the default email sender impl
  docs/documentation/server_admin/topics/realms/email.adoc
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/EmailTab.tsx
  operator/src/test/java/org/keycloak/operator/testsuite/integration/RealmImportTest.java
  server-spi-private/src/main/java/org/keycloak/email/EmailSenderProvider.java
  services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java
  services/src/main/java/org/keycloak/services/managers/RealmManager.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  services/src/main/java/org/keycloak/utils/SMTPUtil.java
  tests/base/src/test/java/org/keycloak/tests/admin/SMTPConnectionTest.java
Labels: team/cloud-native, team/ui

#41882 Upgrade to Quarkus 3.26.0.CR1
  .github/workflows/ci.yml
  pom.xml
  quarkus/deployment/pom.xml
Labels: team/cloud-native

#41875 Adjust the test to dynamically remove all sessions
  js/apps/account-ui/test/account-security/device-activity.spec.ts
  js/apps/account-ui/test/realm.setup.ts
  js/apps/account-ui/test/realm.teardown.ts
Labels: team/ui

#41931 Allow and control sending UTF-8 emails in the default email sender impl (26.3)
  docs/documentation/server_admin/topics/realms/email.adoc
  docs/documentation/upgrading/topics/changes/changes-26_3_3.adoc
  docs/documentation/upgrading/topics/changes/changes.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/EmailTab.tsx
  operator/src/test/java/org/keycloak/operator/testsuite/integration/RealmImportTest.java
  server-spi-private/src/main/java/org/keycloak/email/EmailSenderProvider.java
  services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java
  services/src/main/java/org/keycloak/services/managers/RealmManager.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  services/src/main/java/org/keycloak/utils/SMTPUtil.java
  tests/base/src/test/java/org/keycloak/tests/admin/SMTPConnectionTest.java
Labels: team/cloud-native, team/ui

#41878 URL encode forwarded parameters
  services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerParameterForwardTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#41955 Log applied cache configurations as part of debug logs
  docs/guides/server/caching.adoc
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java
Labels: team/cloud-native, team/sre

#41966 Check null for new keySize and validity parameters when generating certificates
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientAttributeCertificateResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AbstractClientAuthSignedJWTTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
Labels: status/ready, team/cloud-native, team/core-clients, team/core-iam

#41367 [26.0] Upgrade to Quarkus 3.15.6.1
  pom.xml
Labels: team/cloud-native, flaky-test

#41615 Ability to display 'authenticator provider' of the WebAuthn credential
  core/src/main/java/org/keycloak/representations/account/CredentialMetadataRepresentation.java
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
  js/apps/account-ui/src/account-security/SigningIn.tsx
  js/apps/account-ui/src/api/representations.ts
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi/src/main/java/org/keycloak/credential/CredentialMetadata.java
  server-spi/src/main/java/org/keycloak/credential/CredentialProvider.java
  server-spi/src/main/java/org/keycloak/models/credential/WebAuthnCredentialModel.java
  server-spi/src/main/java/org/keycloak/models/credential/dto/WebAuthnCredentialPresentationData.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/WebAuthnMetadataService.java
  services/src/main/java/org/keycloak/credential/WebAuthnCredentialProvider.java
  services/src/main/java/org/keycloak/credential/WebAuthnCredentialProviderFactory.java
  services/src/main/java/org/keycloak/credential/WebAuthnPasswordlessCredentialProvider.java
  services/src/main/java/org/keycloak/credential/WebAuthnPasswordlessCredentialProviderFactory.java
  services/src/main/java/org/keycloak/services/clientpolicy/ClientPoliciesUtil.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  services/src/main/java/org/keycloak/services/securityprofile/DefaultSecurityProfileProviderFactory.java
  services/src/main/java/org/keycloak/utils/FileUtils.java
  services/src/main/resources/keycloak-webauthn-metadata.json
  services/src/test/java/org/keycloak/authentication/authenticators/browser/WebAuthnMetadataServiceTest.java
Labels: team/ui

#41750 Define default topologySpreadConstraints
  docs/guides/high-availability/single-cluster/concepts.adoc
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
Labels: team/cloud-native, team/sre

#41847 enhance: add KC_ env variables for verbose and .sh options
  quarkus/dist/src/main/content/bin/kc.bat
  quarkus/dist/src/main/content/bin/kc.sh
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Main.java
Labels: team/cloud-native

#42007 Stabilize personal info tests in account console
  js/apps/account-ui/test/account-security/linked-accounts.spec.ts
  js/apps/account-ui/test/personal-info/personal-info.spec.ts
  js/apps/account-ui/test/support/actions.ts
Labels: team/ui

#42048 Skip configuring jdbc-ping stack in local mode
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/DefaultCacheEmbeddedConfigProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/JGroupsConfigurator.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java
Labels: team/cloud-native, team/sre

#42115 Align requirement settings for inputType and other annotations to not required
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeAnnotations.tsx
Labels: team/ui

#41849 add configuration option to automatically add recovery codes action
  docs/documentation/server_admin/topics/authentication/recovery-codes.adoc
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateTotp.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionTotpSetupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionTotpSetupTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#41800 fix: adds simple log scraping to error state detection
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/kubernetes/kubernetes.yml
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/CRAssert.java
Labels: team/cloud-native

#41796 enhance: adding the ability to set truststores via configmaps
  docs/guides/operator/advanced-configuration.adoc
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/Truststore.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakTruststoresTests.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/WatchedResourcesTest.java
Labels: team/cloud-native

#42227 Stabilize the client scope tests for the admin console
  js/apps/admin-ui/test/clients/scope.spec.ts
Labels: team/ui

#42232 fix: expands our warnings/notes around placeholder usage (#42151)
  docs/guides/operator/basic-deployment.adoc
  docs/guides/operator/realm-import.adoc
  docs/guides/server/importExport.adoc
Labels: team/cloud-native

#42231 fix: adding debug logging for the KeycloakRealmImport (#42102)
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportController.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
Labels: team/cloud-native

#42189 fix: improve handling when expressions are disabled
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Environment.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Build.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/ConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/DatasourcesConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/BuildCommandDistTest.java
Labels: team/cloud-native
