Repository keycloak/keycloak, pull requests merged in 2025-07, with the labels that each got.

#38514 consolidating profile logic and moving reaug related logic
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Environment.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractNonServerCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractStartCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractUpdatesCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Build.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Export.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Import.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Start.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/StartDev.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/UpdateCompatibilityCheck.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/UpdateCompatibilityMetadata.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/Configuration.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/jaxrs/QuarkusKeycloakApplication.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/AbstractConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/BuildAndStartDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#40839 Mark options for additional datasources as preview
  docs/documentation/upgrading/topics/changes/changes-26_3_1.adoc
  docs/documentation/upgrading/topics/changes/changes.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/OptionCategory.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBootstrapAdminService.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBootstrapAdminUser.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
Labels: team/cloud-native

#40840 [26.3.x] Mark options for additional datasources as preview
  docs/documentation/upgrading/topics/changes/changes-26_3_1.adoc
  docs/documentation/upgrading/topics/changes/changes.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/OptionCategory.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBootstrapAdminService.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBootstrapAdminUser.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
Labels: team/cloud-native

#40852 Upgrade to Infinispan 15.0.16.Final
  pom.xml
Labels: team/sre

#40168 Added new searchByAttributes function to UsersResource with the exact parameter
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
  docs/documentation/upgrading/topics/changes/changes.adoc
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/UsersResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40894 fix: detecting when we can set the serviceName
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/PodTemplateTest.java
Labels: team/cloud-native

#40384 Automatically connect to a writer instance of PostgreSQL
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
  docs/guides/server/db.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/DatabaseOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/ConfigurationTest.java
  tests/base/src/test/java/org/keycloak/tests/db/DbTest.java
  tests/base/src/test/java/org/keycloak/tests/suites/DatabaseTestSuite.java
Labels: team/cloud-native, flaky-test

#40943 fix: detecting when we can set the serviceName (#40894)
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/PodTemplateTest.java
Labels: team/cloud-native

#40690 Provide CLI Parameters for jgroups.* options
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
  docs/guides/server/caching.adoc
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/DefaultCacheEmbeddedConfigProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/JGroupsConfigurator.java
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/CachingPropertyMappers.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
Labels: team/cloud-native, flaky-test, team/sre

#40412 [OID4VCI] Remove interval property from Credential Offer
  services/src/main/java/org/keycloak/protocol/oid4vc/model/PreAuthorizedCode.java
Labels: flaky-test

#40835 Use MgmtPermissionsV2 by default
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/BruteForceUsersResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
  services/src/main/java/org/keycloak/services/resources/admin/fgap/AdminPermissions.java
  tests/base/src/test/java/org/keycloak/tests/admin/PermissionsTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/PermissionsTestV1.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IllegalAdminUpgradeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/ClientTokenExchangeSAML2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2WithLegacyTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/SubjectImpersonationTokenExchangeV1Test.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#40808 fix: streamlining the client scope update
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
Labels: flaky-test

#40787 Fix typo in consent scope
  core/src/main/java/org/keycloak/representations/account/ConsentScopeRepresentation.java
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
  js/apps/account-ui/src/api/representations.ts
Labels: team/ui

#40982 LDAP group mapper skips configured filter and imports all groups with…
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/UserRolesRetrieveStrategy.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperCustomMemberOfTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40974 Update documentation when no rolling update is performed
  docs/guides/server/update-compatibility.adoc
Labels: team/cloud-native

#40979 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ro.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ka.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_pt_BR.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ru.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_nl.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_pt_BR.properties
Labels: team/ui

#40740 Rework floating promises to avoid concurrency side effects
  js/apps/account-ui/src/account-security/AccountRow.tsx
  js/apps/account-ui/src/account-security/DeviceActivity.tsx
  js/apps/account-ui/src/account-security/SigningIn.tsx
  js/apps/account-ui/src/oid4vci/Oid4Vci.tsx
  js/apps/account-ui/src/resources/PermissionRequest.tsx
  js/apps/account-ui/src/utils/usePromise.ts
  js/apps/account-ui/test/account-security/signing-in.spec.ts
  js/apps/account-ui/test/admin-client.ts
  js/apps/admin-ui/src/authentication/FlowDetails.tsx
  js/apps/admin-ui/src/authentication/RequiredActions.tsx
  js/apps/admin-ui/src/clients/keys/GenerateKeyDialog.tsx
  js/apps/admin-ui/src/clients/keys/ImportKeyDialog.tsx
  js/apps/admin-ui/src/clients/keys/SamlImportKeyDialog.tsx
  js/apps/admin-ui/src/clients/keys/SamlKeys.tsx
  js/apps/admin-ui/src/clients/keys/SamlKeysDialog.tsx
  js/apps/admin-ui/src/context/realm-context/RealmContext.tsx
  js/apps/admin-ui/src/context/whoami/WhoAmI.tsx
  js/apps/admin-ui/src/permissions-configuration/permission-configuration/AssignedPolicies.tsx
  js/apps/admin-ui/src/permissions-configuration/permission-configuration/NewPermissionPolicyDialog.tsx
  js/apps/admin-ui/src/realm-settings/DefaultGroupsTab.tsx
  js/apps/admin-ui/src/realm-settings/LoginTab.tsx
  js/apps/admin-ui/src/realm-settings/NewClientPolicy.tsx
  js/apps/admin-ui/src/realm-settings/PartialImport.tsx
  js/apps/admin-ui/src/realm-settings/PoliciesTab.tsx
  js/apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
  js/apps/admin-ui/src/realm-settings/event-config/EventsTab.tsx
  js/apps/admin-ui/src/realm-settings/localization/RealmOverrides.tsx
  js/apps/admin-ui/src/realm-settings/themes/ImageUpload.tsx
  js/apps/admin-ui/src/realm-settings/themes/ThemeColors.tsx
  js/apps/admin-ui/src/realm-settings/themes/ThemesTab.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesGroupTab.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/AttributesTab.tsx
  js/apps/admin-ui/src/sessions/RevocationModal.tsx
  js/apps/admin-ui/src/user-federation/ldap/mappers/LdapMapperDetails.tsx
  js/apps/admin-ui/src/user/EditUser.tsx
  js/apps/admin-ui/src/user/UserCredentials.tsx
  js/apps/admin-ui/src/user/UserForm.tsx
  js/apps/admin-ui/src/user/user-credentials/ResetCredentialDialog.tsx
  js/apps/admin-ui/src/user/user-credentials/ResetPasswordDialog.tsx
  js/apps/admin-ui/src/utils/useQueryPermission.ts
  js/apps/admin-ui/test/identity-providers/main.ts
  js/apps/admin-ui/test/sessions/main.ts
  js/apps/admin-ui/test/users/main.ts
  js/apps/admin-ui/test/utils/sidebar.ts
  js/eslint.config.js
  js/libs/keycloak-admin-client/test/realms.spec.ts
Labels: team/ui

#40229 [OID4VCI]: Add a unique notification_id generation to OID4VCIssuerEndpoint used in CredentialResponse.
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialResponse.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCJWTIssuerEndpointTest.java
Labels: status/ready, team/cloud-native, flaky-test, team/core-clients, team/core-iam

#41004 Set client in the session context for logout token encode
  services/src/main/java/org/keycloak/services/managers/ResourceAdminManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java
Labels: status/ready, team/cloud-native, team/core-clients, team/core-iam

#40820 Changing default passwordless webauthn policy to follow recommended values in the documentation
  model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  server-spi-private/src/main/java/org/keycloak/models/WebAuthnPolicyPasswordlessDefaults.java
  server-spi-private/src/main/java/org/keycloak/models/WebAuthnPolicyTwoFactorDefaults.java
  services/src/main/java/org/keycloak/WebAuthnConstants.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/WebAuthnAuthenticator.java
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnRegister.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/webauthn/utils/PropertyRequirement.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/AppInitiatedActionWebAuthnTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnIdlessTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnPropertyTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/account/AbstractWebAuthnAccountTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/account/WebAuthnSigningInTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/passwordless/AppInitiatedActionPwdLessSkipIfExistsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/passwordless/AppInitiatedActionPwdLessTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/passwordless/PasskeysConditionalUITest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/passwordless/PasskeysOrganizationAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/passwordless/PasskeysUsernameFormTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/passwordless/PasskeysUsernamePasswordFormTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/ResidentKeyRegisterTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40749 [OID4VCI] : Update Credential Issuer Metadata Model for OID4VCI Draft-15
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerWellKnownProvider.java
  services/src/main/java/org/keycloak/protocol/oid4vc/model/CredentialIssuer.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerWellKnownProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#41025 Do not add steps if feature disabled in default flows Allow login if a step is disabled even the authenticator is not enabled by profile Closes #40954
  server-spi-private/src/main/java/org/keycloak/models/utils/DefaultAuthenticationFlows.java
  services/src/main/java/org/keycloak/authentication/DefaultAuthenticationFlow.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40007 Generate a UUID to be the JTI instead of reusing the nonce.
  services/src/main/java/org/keycloak/authentication/actiontoken/DefaultActionToken.java
Labels: status/ready

#40991 Run clustering compatibility tests on release/x.y branches
  .github/scripts/version-compatibility.sh
  .github/workflows/ci.yml
  test-framework/clustering/src/main/java/org/keycloak/testframework/server/ClusteredKeycloakServer.java
  tests/clustering/README.md
  tests/clustering/src/test/resources/keycloak-test.properties
Labels: team/sre

#41051 Increase timeout when publishing to Maven Central
  pom.xml
Labels: flaky-test

#40996 Fix #40995 avoid ModelException: At least one condition should be pr…
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/UserRolesRetrieveStrategy.java
Labels: flaky-test

#40312 Add generic update methods for builders
  test-framework/core/src/main/java/org/keycloak/testframework/realm/ClientConfigBuilder.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/RealmConfigBuilder.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/UserConfigBuilder.java
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/CustomConfigBuilderTest.java
Labels: area/test-framework

#41059 Add option 'Requires short state parameter' to OIDC IDP
  docs/documentation/server_admin/topics/identity-broker/oauth2.adoc
  docs/documentation/server_admin/topics/identity-broker/oidc.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/identity-providers/add/ExtendedNonDiscoverySettings.tsx
  js/apps/admin-ui/src/identity-providers/add/ExtendedOAuth2Settings.tsx
  services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
  services/src/main/java/org/keycloak/broker/oidc/OAuth2IdentityProviderConfig.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcMultipleTabsBrokerTest.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#41090 Selected client ID is a string and not an array
  js/apps/admin-ui/src/permissions-configuration/permission-evaluation/PermissionsEvaluationTab.tsx
Labels: team/ui

#41017 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
Labels: team/ui

#41113 Add option 'Requires short state parameter' to OIDC IDP
  docs/documentation/server_admin/topics/identity-broker/oidc.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/identity-providers/add/ExtendedNonDiscoverySettings.tsx
  services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
  services/src/main/java/org/keycloak/broker/oidc/OAuth2IdentityProviderConfig.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcMultipleTabsBrokerTest.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#41114 Add option 'Requires short state parameter' to OIDC IDP
  docs/documentation/server_admin/topics/identity-broker/oidc.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/identity-providers/add/ExtendedNonDiscoverySettings.tsx
  services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
  services/src/main/java/org/keycloak/broker/oidc/OAuth2IdentityProviderConfig.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcMultipleTabsBrokerTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#40279 Move PartialImportTest.java to the new testsuite
  test-framework/core/src/main/java/org/keycloak/testframework/realm/RealmConfigBuilder.java
  tests/base/pom.xml
  tests/base/src/test/java/org/keycloak/tests/admin/partialimport/AbstractPartialImportTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/partialimport/PartialImportClientTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/partialimport/PartialImportGroupTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/partialimport/PartialImportProvidersTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/partialimport/PartialImportRealmTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/partialimport/PartialImportRolesTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/partialimport/PartialImportUserTest.java
  tests/base/src/test/resources/org/keycloak/tests/admin/partialimport/sample-authz-partial-import.json
  tests/custom-scripts/pom.xml
  tests/custom-scripts/src/main/resources/META-INF/keycloak-scripts.json
  tests/custom-scripts/src/main/resources/scripts/default-policy.js
  tests/pom.xml
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/partialimport/PartialImportTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, area/test-framework

#40282 Move IllegalAdminUpgradeTest.java to the new testsuite
  tests/base/src/test/java/org/keycloak/tests/admin/IllegalAdminUpgradeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IllegalAdminUpgradeTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, area/test-framework

#40941 Update Traditional Chinese locale to latest version
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_zh_TW.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_zh_TW.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_zh_TW.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_zh_TW.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_zh_TW.properties
Labels: team/ui

#41142 fix: using unversioned key in docs
  docs/guides/server/features.adoc
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Features.java
Labels: team/cloud-native

#40867 Upgrade to the Quarkus 3.24.2 version
  model/jpa/src/main/java/org/keycloak/connections/jpa/util/JpaUtils.java
  pom.xml
  quarkus/deployment/pom.xml
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
Labels: team/cloud-native, flaky-test

#41144 fix: adding a release note for http-management-scheme
  docs/documentation/release_notes/index.adoc
  docs/documentation/release_notes/topics/26_4_0.adoc
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakServiceDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
Labels: team/cloud-native

#41143 Bug Fix: Blank Tab in Client Registration Access Policies
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/registration/ClientRegistrationList.tsx
Labels: team/ui

#41027 Allow Features to declare that they support Rolling upgrades
  common/src/main/java/org/keycloak/common/Profile.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/UpdateCommandDistTest.java
  services/pom.xml
  services/src/main/java/org/keycloak/compatibility/FeatureCompatibilityMetadataProvider.java
  services/src/main/resources/META-INF/services/org.keycloak.compatibility.CompatibilityMetadataProvider
  services/src/test/java/org/keycloak/compatibility/AbstractCompatibilityMetadataProviderTest.java
  services/src/test/java/org/keycloak/compatibility/FeatureCompatibilityMetadataProviderTest.java
  services/src/test/java/org/keycloak/compatibility/KeycloakCompatibilityMetadataProviderTest.java
Labels: team/cloud-native, flaky-test, team/sre

#41190 Password modification time attribute as an operational and read-only …
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPUtils.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPIdentityStore.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/msad/MSADUserAccountControlStorageMapper.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/msad/UserAccountControl.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/util/LDAPTestUtils.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/LDAPRule.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPAccountRestApiTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPBinaryAttributesTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#41198 Fix client scope assigned type test
  js/apps/admin-ui/src/clients/scopes/ClientScopes.tsx
  js/apps/admin-ui/test/client-scope/main.spec.ts
  js/apps/admin-ui/test/clients/scope.spec.ts
  js/apps/admin-ui/test/utils/table.ts
Labels: team/ui

#41213 DOC: Explain Containerfile usage and fix docker build example
  docs/guides/server/containers.adoc
Labels: team/cloud-native

#41212 Fix typo for MDC enabled property in logging guide
  docs/guides/server/logging.adoc
Labels: team/cloud-native

#41221 Document spi-user-sessions--infinispan--use-batches
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProviderFactory.java
Labels: team/sre

#41226 Only view svc acct users on exact search
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
Labels: team/ui

#41194 Improve handling of datasource name specified in `persistence.xml` files
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/deployment/src/test/java/org/keycloak/quarkus/deployment/PersistenceXmlDatasourcesTest.java
  quarkus/tests/integration/src/test-providers/resources/com/acme/provider/legacy/jpa/entity/persistence.xml
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/CustomJpaEntityProviderDistTest.java
Labels: team/cloud-native, flaky-test

#41218 Stabilize flow duplication modal to avoid test failures
  js/apps/admin-ui/src/authentication/AuthenticationSection.tsx
  js/apps/admin-ui/src/authentication/DuplicateFlowModal.tsx
  js/apps/admin-ui/src/authentication/FlowDetails.tsx
Labels: team/ui

#41133 FAPI 2.0 Final - only accept its issuer identifier value as a string in the aud claim received in client authentication assertions
  services/src/main/java/org/keycloak/services/clientpolicy/executor/SecureClientAuthenticationAssertionExecutor.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/SecureClientAuthenticationAssertionExecutorFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.services.clientpolicy.executor.ClientPolicyExecutorProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExecutorTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40989 Remove workaround for handling Syslog counting framing
  quarkus/config-api/src/main/java/org/keycloak/config/LoggingOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/Option.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionBuilder.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/LoggingConfigurationTest.java
Labels: team/cloud-native

#41258 Upgrade to Infinispan 15.0.18.Final
  pom.xml
Labels: flaky-test

#41247 Upgrade to Quarkus 3.24.4
  pom.xml
Labels: flaky-test

#41286 fix: refine test for rolling (#41254)
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/CRAssert.java
Labels: team/cloud-native

#39659 OpenTelemetry Tracing: Visualize JGroups communication
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
  model/infinispan/src/main/java/org/keycloak/infinispan/module/factory/InfinispanTelemetryFactory.java
  model/infinispan/src/main/java/org/keycloak/infinispan/module/factory/OpenTelemetryService.java
  model/infinispan/src/main/java/org/keycloak/infinispan/module/factory/OpenTelemetrySpan.java
  model/infinispan/src/main/java/org/keycloak/jgroups/header/TracerHeader.java
  model/infinispan/src/main/java/org/keycloak/jgroups/protocol/OPEN_TELEMETRY.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/DefaultCacheEmbeddedConfigProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/JGroupsConfigurator.java
  quarkus/config-api/src/main/java/org/keycloak/config/TracingOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/CachingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TracingPropertyMappers.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
Labels: team/cloud-native, flaky-test, team/sre

#40323 Move ConsentsTest.java to the new testsuite
  test-framework/core/src/main/java/org/keycloak/testframework/realm/ClientConfigBuilder.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/RealmConfigBuilder.java
  test-framework/ui/src/main/java/org/keycloak/testframework/ui/page/ConsentPage.java
  test-framework/ui/src/main/java/org/keycloak/testframework/ui/page/LoginPage.java
  tests/base/src/test/java/org/keycloak/tests/admin/ConsentsTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/user/UserRoleTest.java
  tests/custom-providers/src/main/java/org/keycloak/testsuite/events/TestEventsListenerProvider.java
  tests/custom-providers/src/main/java/org/keycloak/testsuite/events/TestEventsListenerProviderFactory.java
  tests/custom-providers/src/main/resources/META-INF/services/org.keycloak.events.EventListenerProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ConsentsTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, area/test-framework

#41234 Document configuration changes that prevent rolling updates
  docs/guides/server/update-compatibility.adoc
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Features.java
Labels: team/sre

#41329 Disable webauthn buttons after click
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/WaitUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/AuthAttachmentRegisterTest.java
  themes/src/main/resources/theme/base/login/login-passkeys-conditional-authenticate.ftl
  themes/src/main/resources/theme/base/login/passkeys.ftl
  themes/src/main/resources/theme/base/login/webauthn-authenticate.ftl
  themes/src/main/resources/theme/base/login/webauthn-register.ftl
  themes/src/main/resources/theme/keycloak.v2/login/webauthn-authenticate.ftl
  themes/src/main/resources/theme/keycloak.v2/login/webauthn-register.ftl
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#40906 fix: further refining logic and docs around import/export
  docs/guides/server/importExport.adoc
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportController.java
Labels: team/cloud-native, flaky-test

#41340 Fix add/del bundle test
  js/apps/admin-ui/test/realm-settings/localization.spec.ts
Labels: team/ui

#41361 Update MariaDB connector to 3.5.3
  pom.xml
Labels: priority/important, team/cloud-native

#41372 [26.3] MariaDB connector dependency is not properly overriden
  pom.xml
Labels: team/cloud-native

#40389 use user and client from form when on the events section (#35098)
  js/apps/admin-ui/src/events/UserEvents.tsx
Labels: team/ui

#41296 Avoid additional execution of Liquibase changelog lock table statement
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/lock/CustomLockService.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LiquibaseDistTest.java
Labels: team/cloud-native, flaky-test

#41126 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ja.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_nl.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_it.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_nl.properties
Labels: team/ui, flaky-test

#41375 Upgrade to Quarkus 3.24.5
  pom.xml
Labels: team/cloud-native, flaky-test

#41402 Setting 'write_data_on_find' to true to ensure merging of views
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/jgroups/impl/JGroupsJdbcPingStackConfigurator.java
Labels: team/cloud-native

#41377 fix: using localtest.me instead of nip.io
  .github/actions/update-hosts/action.yml
  .github/actions/update-hosts/hosts
  .github/actions/update-hosts/nipio-hosts
  tests/base/src/test/java/org/keycloak/tests/admin/AdminRootEdgeTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/AdminRootTest.java
  testsuite/integration-arquillian/HOW-TO-RUN.md
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cookies/DefaultCookieProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPSamlIdPInitiatedVaryingLetterCaseTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/url/HostnameV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ReverseProxy.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#41267 Migrate to zh-Hant / zh-Hans for Chinese language
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
  docs/guides/ui-customization/localization.adoc
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_zh_Hans.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_zh_Hant.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_Hans.properties
  services/src/main/java/org/keycloak/theme/ClassLoaderTheme.java
  services/src/main/java/org/keycloak/theme/DefaultThemeManager.java
  services/src/main/java/org/keycloak/theme/FileBasedTheme.java
  services/src/main/java/org/keycloak/theme/FolderTheme.java
  themes/src/main/resources-community/theme/base/account/messages/messages_zh_Hans.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_zh_Hant.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_zh_Hans.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_zh_Hant.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_zh_Hans.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_zh_Hant.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_zh_Hans.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_zh_Hant.properties
Labels: team/ui

#41457 Fix broken anchor for caching docs
  docs/guides/server/caching.adoc
  docs/guides/server/configuration-production.adoc
Labels: team/cloud-native

#41456 Fix broken anchor for caching docs
  docs/guides/server/caching.adoc
  docs/guides/server/configuration-production.adoc
Labels: team/cloud-native

#41389 Provide simple HTTP access logs
  docs/documentation/release_notes/topics/26_4_0.adoc
  docs/guides/server/logging.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/HttpAccessLogOptions.java
  quarkus/config-api/src/main/java/org/keycloak/config/OptionCategory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpAccessLogPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/main/resources/application.properties
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/LoggingConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBootstrapAdminService.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBootstrapAdminUser.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
Labels: team/cloud-native

#41470 Close spans in the exceptional path
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/KeycloakTracingCustomizer.java
Labels: team/cloud-native

#41087 Require setting DB kind for additional datasources
  quarkus/config-api/src/main/java/org/keycloak/config/DatabaseOptions.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/ValidatePersistenceUnitsBuildItem.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakRecorder.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/WildcardPropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/QuarkusJpaConnectionProviderFactory.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/DatasourcesConfigurationTest.java
  quarkus/tests/integration/src/test-providers/resources/com/acme/provider/legacy/jpa/entity/persistence.xml
  quarkus/tests/integration/src/test-providers/resources/com/acme/provider/legacy/jpa/entity/quarkus.properties
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/CustomJpaEntityProviderDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBootstrapAdminService.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBootstrapAdminUser.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBuildHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/CLIResult.java
Labels: team/cloud-native, flaky-test

#41438 Fix: prevent federated users from being listed on initial Users page load
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
Labels: team/ui, team/core-iam

#41490 Missing comment generated by Liquibase executor in the custom script
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/BasicDatabaseTest.java
Labels: team/cloud-native, flaky-test

#41364 fix: adjusting the startup of the local api server for ci
  operator/src/test/java/org/keycloak/operator/testsuite/apiserver/ApiServerHelper.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
Labels: team/cloud-native, flaky-test

#41485 Making IDs for configuration options unique
  docs/guides/server/all-config.adoc
  docs/guides/templates/options.adoc
Labels: team/cloud-native

#41484 Making IDs for configuration options unique
  docs/guides/server/all-config.adoc
  docs/guides/templates/options.adoc
Labels: team/cloud-native

#41291 Reduce likelihood of multiple coordinators on concurrent startup
  model/infinispan/pom.xml
  model/infinispan/src/main/java/org/keycloak/jgroups/protocol/KEYCLOAK_JDBC_PING2.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/JGroupsConfigurator.java
  model/infinispan/src/test/java/org/keycloak/jgroups/protocol/JdbcPing2Test.java
  model/infinispan/src/test/java/org/keycloak/jgroups/protocol/KEYCLOAK_JDBC_PING2_FOR_TESTING.java
  model/infinispan/src/test/resources/jdbc-h2.xml
  model/infinispan/src/test/resources/logging.properties
Labels: flaky-test, team/sre

#41500 Make fileChooser platform independent.
  js/apps/admin-ui/test/clients/main.spec.ts
  js/apps/admin-ui/test/utils/file-chooser.ts
Labels: team/ui

#41506 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_zh_Hant.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_zh_Hant.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_zh_Hant.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_zh_Hant.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_zh_Hant.properties
Labels: team/ui, flaky-test

#41368 Create a new condition for credential type
  docs/documentation/server_admin/topics/authentication/conditions.adoc
  server-spi-private/src/main/java/org/keycloak/models/utils/DefaultAuthenticationFlows.java
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
  services/src/main/java/org/keycloak/authentication/AuthenticatorUtil.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/UsernamePasswordForm.java
  services/src/main/java/org/keycloak/authentication/authenticators/conditional/ConditionalCredentialAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/conditional/ConditionalCredentialAuthenticatorFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.authentication.AuthenticatorFactory
  tests/base/src/test/java/org/keycloak/tests/admin/authentication/InitialFlowsTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authentication/ProvidersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionTotpSetupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/login/ConditionalCredentialAuthenticatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/FlowUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/passwordless/PasskeysDefaultBrowserFlowTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39508 Refresh token for an OAuth2 based IDP when retrieving the IDP token
  docs/documentation/server_admin/images/github-add-identity-provider.png
  docs/documentation/server_admin/topics/identity-broker/social/github.adoc
  docs/documentation/upgrading/topics/changes/changes-26_4_0.adoc
  services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  services/src/main/java/org/keycloak/social/github/GitHubIdentityProvider.java
  services/src/main/java/org/keycloak/social/github/GitHubIdentityProviderFactory.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractHttpResponse.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/FetchExternalIdpTokenRequest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcFirstBrokerLoginTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#41540 Getting error 405 'Method Not Allowed' when calling the 'certs' endpo…
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolService.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/broker/util/SimpleHttpDefault.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AbstractWellKnownProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#41536 Upgrade to Quarkus 3.25.0
  pom.xml
Labels: team/cloud-native
