Repository keycloak/keycloak, pull requests merged in 2025-04, with the labels that each got.

#38418 Only the version is needed to build the Docker image.
  quarkus/container/Dockerfile
  quarkus/container/README.md
Labels: team/cloud-native

#38561 Make some policy fields not mandatory.
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/authorization/policy/ClientScope.tsx
  js/apps/admin-ui/src/clients/authorization/policy/Group.tsx
  js/apps/admin-ui/src/clients/authorization/policy/Role.tsx
  js/apps/admin-ui/src/clients/authorization/policy/User.tsx
  js/apps/admin-ui/src/permissions-configuration/permission-configuration/NewPermissionPolicyDialog.tsx
Labels: team/ui

#38560 Fixing inconsistencies when evaluating permission in the evaluation tab
  core/src/main/java/org/keycloak/representations/idm/authorization/PolicyEvaluationRequest.java
  core/src/main/java/org/keycloak/representations/idm/authorization/PolicyEvaluationResponse.java
  core/src/main/java/org/keycloak/representations/idm/authorization/ResourceType.java
  js/apps/admin-ui/src/permissions-configuration/permission-evaluation/PermissionsEvaluationTab.tsx
  js/libs/keycloak-admin-client/src/defs/resourceEvaluation.ts
  server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java
  server-spi-private/src/main/java/org/keycloak/authorization/AuthorizationProvider.java
  server-spi-private/src/main/java/org/keycloak/authorization/FGAPDecision.java
  server-spi-private/src/main/java/org/keycloak/authorization/FGAPEvaluation.java
  server-spi-private/src/main/java/org/keycloak/authorization/FGAPPolicyEvaluator.java
  server-spi-private/src/main/java/org/keycloak/authorization/ResourceTypePolicyEvaluator.java
  server-spi-private/src/main/java/org/keycloak/authorization/UserResourceTypePolicyEvaluator.java
  server-spi-private/src/main/java/org/keycloak/authorization/model/ResourceWrapper.java
  server-spi-private/src/main/java/org/keycloak/authorization/permission/Permissions.java
  server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/AbstractDecisionCollector.java
  server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/DecisionPermissionCollector.java
  server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/DefaultEvaluation.java
  server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/DefaultPolicyEvaluator.java
  server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/Evaluation.java
  services/src/main/java/org/keycloak/authorization/admin/PolicyEvaluationService.java
  services/src/main/java/org/keycloak/authorization/admin/representation/FGAPPolicyEvaluationResponseBuilder.java
  services/src/main/java/org/keycloak/authorization/admin/representation/PolicyEvaluationResponseBuilder.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/AdminPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/ClientPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/ClientPermissionsV2.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/GroupPermissionsV2.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissionsV2.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissionsV2.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/GroupResourceTypeFilteringTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypeEvaluationSpecTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UmaRepresentationTest.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#38609 Commit delete and insert statements together when updating jgroups-jd…
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/jgroups/impl/JGroupsJdbcPingStackConfigurator.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/jgroups/impl/KEYCLOAK_JDBC_PING2.java
Labels: team/cloud-native

#38585 Define a max expiration window for Signed JWT client authentication
  docs/documentation/server_admin/images/client-credentials-jwt.png
  docs/documentation/server_admin/topics/clients/oidc/con-confidential-client-credentials.adoc
  docs/documentation/upgrading/topics/changes/changes-26_2_0.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/credentials/SignedJWT.tsx
  server-spi-private/src/main/java/org/keycloak/protocol/oidc/OIDCConfigAttributes.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCAdvancedConfigWrapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#38618 Set the correct revision number in stateful set
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
Labels: team/cloud-native

#38554 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ca.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_it.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ka.properties
Labels: team/ui

#38612 Change cookie type for KC_AUTH_SESSION_HASH
  server-spi-private/src/main/java/org/keycloak/cookie/CookieType.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cookies/DefaultCookieProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38446 Create recovery keys in user storage or local
  server-spi-private/src/main/java/org/keycloak/utils/CredentialHelper.java
  server-spi/src/main/java/org/keycloak/models/utils/RecoveryAuthnCodesUtils.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/RecoveryAuthnCodesFormAuthenticator.java
  services/src/main/java/org/keycloak/authentication/requiredactions/RecoveryAuthnCodesAction.java
  services/src/main/java/org/keycloak/forms/login/freemarker/model/RecoveryAuthnCodeInputLoginBean.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/BackwardsCompatibilityUserStorage.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/federation/BackwardsCompatibilityUserStorageFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/BackwardsCompatibilityUserStorageTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#38637 Define a max expiration window for Signed JWT client authentication (26.1)
  docs/documentation/server_admin/images/client-credentials-jwt.png
  docs/documentation/server_admin/topics/clients/oidc/con-confidential-client-credentials.adoc
  docs/documentation/upgrading/topics/changes/changes-26_1_5.adoc
  docs/documentation/upgrading/topics/changes/changes.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/credentials/SignedJWT.tsx
  server-spi-private/src/main/java/org/keycloak/protocol/oidc/OIDCConfigAttributes.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCAdvancedConfigWrapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#38640 Define a max expiration window for Signed JWT client authentication (26.0)
  docs/documentation/server_admin/images/client-credentials-jwt.png
  docs/documentation/server_admin/topics/clients/oidc/con-confidential-client-credentials.adoc
  docs/documentation/topics/templates/document-attributes.adoc
  docs/documentation/upgrading/topics/changes/changes-19_0_0.adoc
  docs/documentation/upgrading/topics/changes/changes-26_0_11.adoc
  docs/documentation/upgrading/topics/changes/changes.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/credentials/SignedJWT.tsx
  server-spi-private/src/main/java/org/keycloak/protocol/oidc/OIDCConfigAttributes.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCAdvancedConfigWrapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#38541 Add additional validations for placeholders in message properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ca.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_el.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_fi.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_hu.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_it.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ka.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_th.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_zh_CN.properties
  misc/theme-verifier/src/main/java/org/keycloak/themeverifier/VerifyMessageProperties.java
  misc/theme-verifier/src/test/java/org/keycloak/themeverifier/VerifyMessagePropertiesTest.java
  misc/theme-verifier/src/test/resources/doubleCurlyBraces_en.properties
  misc/theme-verifier/src/test/resources/singleCurlyBracesEnd_en.properties
  misc/theme-verifier/src/test/resources/singleCurlyBracesMiddle_en.properties
  misc/theme-verifier/src/test/resources/singleCurlyBracesStart_en.properties
Labels: team/ui

#38628 Set the mail.from to avoid looking up the local hostname
  services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/EmailTest.java
Labels: flaky-test

#38629 Set the mail.from to avoid looking up the local hostname
  services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/EmailTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#38627 Aligning partial evaluation with the outcome from regular evaluations
  core/src/main/java/org/keycloak/representations/idm/authorization/ResourceType.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserPartialEvaluationProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
  server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java
  server-spi-private/src/main/java/org/keycloak/authorization/PartialEvaluator.java
  server-spi-private/src/main/java/org/keycloak/authorization/policy/provider/PartialEvaluationContext.java
  server-spi-private/src/main/java/org/keycloak/authorization/policy/provider/PartialEvaluationStorageProvider.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypeEvaluationSpecTest.java
Labels: flaky-test

#38650 Revert "make whole row disabled (#38383)"
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
  js/libs/ui-shared/src/controls/table/KeycloakDataTable.tsx
Labels: team/ui

#38599 fix: removing extra logging - the operator sdk logs this as well
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportController.java
Labels: team/cloud-native

#38674 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
Labels: team/ui

#38608 Don't update the client session's timestamp when loading it from the database
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/ClientSessionPersistentChangelogBasedTransaction.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38669 Don't reset the form at start of form setup.
  js/apps/admin-ui/src/clients/ClientDetails.tsx
Labels: team/ui

#38595 Enhance logging for a missing provider factory dependency
  services/src/main/java/org/keycloak/services/DefaultKeycloakSessionFactory.java
Labels: flaky-test

#38466 Add idp option to redirect on any org domain match
  docs/documentation/server_admin/topics/organizations/managing-identity-providers.adoc
  js/apps/admin-ui/src/organizations/LinkIdentityProviderModal.tsx
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  server-spi/src/main/java/org/keycloak/models/OrganizationDomainModel.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/validator/OrganizationMemberValidator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/AbstractBrokerSelfRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/member/OrganizationMemberTest.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#38680 Review comments to align with style guide
  docs/guides/server/update-compatibility.adoc
Labels: team/cloud-native

#37803 Add OpenJDK 24 to matrix of tested JDKs
  .github/workflows/ci.yml
Labels: status/hold

#38505 Move ClientRolesTest to the new testsuite
  tests/base/src/test/java/org/keycloak/tests/admin/client/ClientRolesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/AbstractClientTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, area/test-framework

#38158 [Test framework] AdminConsoleWhoAmILocaleTest migration
  test-framework/core/src/main/java/org/keycloak/testframework/annotations/InjectAdminClient.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/RealmConfigBuilder.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/UserConfigBuilder.java
  test-framework/core/src/main/java/org/keycloak/testframework/util/ApiUtil.java
  test-framework/oauth/src/main/java/org/keycloak/testframework/oauth/OAuthClientSupplier.java
  test-framework/oauth/src/main/java/org/keycloak/testframework/oauth/annotations/InjectOAuthClient.java
  tests/base/src/test/java/org/keycloak/tests/admin/AdminConsoleWhoAmILocaleTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/DeclarativeUserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminConsoleWhoAmILocaleTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, area/test-framework

#38684 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_sl.properties
Labels: team/ui

#38630 Add webauthn tests for the passkeys conditional UI authenticator
  services/src/main/java/org/keycloak/authentication/authenticators/browser/WebAuthnAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/webauthn/authenticators/DefaultVirtualAuthOptions.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/passwordless/PasskeysConditionalUITest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38710 Export failing if the realm has FGAP enabled
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ExportDistTest.java
  quarkus/tests/integration/src/test/resources/fgap-realm.json
  server-spi-private/src/main/java/org/keycloak/authorization/PartialEvaluator.java
  services/src/main/java/org/keycloak/services/DefaultKeycloakContext.java
Labels: team/cloud-native

#38735 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
Labels: team/ui

#38613 Avoiding nip.io for stability
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cookies/DefaultCookieProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/saml/AbstractSamlTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ReverseProxy.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38723 Sorting the chapters of the HA guide
  docs/guides/high-availability/pinned-guides
  docs/guides/operator/basic-deployment.adoc
  docs/guides/operator/installation.adoc
  docs/guides/operator/realm-import.adoc
  docs/guides/server/vault.adoc
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Context.java
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Guide.java
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/GuideParser.java
Labels: team/cloud-native

#38743 [Backport 26.1] Added condition to check offlineSessionMaxLifespanEnabled on clearing
  model/jpa/src/main/java/org/keycloak/models/jpa/session/JpaUserSessionPersisterProvider.java
Labels: flaky-test

#38746 convert group to Id before setting the value
  js/apps/admin-ui/src/permissions-configuration/resource-types/GroupSelect.tsx
  js/apps/admin-ui/test/permissions/main.spec.ts
  js/apps/admin-ui/test/permissions/main.ts
Labels: team/ui

#38530 fixed flatten function
  js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx
Labels: team/ui

#38750 [26.1] OTelHttpClientFactory not configured properly when tracing enabled
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/tracing/OTelHttpClientFactory.java
Labels: team/cloud-native, flaky-test

#38652 [FGAP] Switch the feature from Experimental to Supported
  common/src/main/java/org/keycloak/common/Profile.java
  common/src/test/java/org/keycloak/common/ProfileTest.java
  model/storage-private/src/main/java/org/keycloak/storage/UserStorageManager.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FeaturesDistTest.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/EmbeddedKeycloakServer.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/KeycloakServerConfigBuilder.java
  tests/base/src/test/java/org/keycloak/tests/admin/FineGrainedPermissionsV1UsersTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/ClientResourceTypeEvaluationTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/ClientResourceTypeFilteringTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/ClientResourceTypePermissionTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/FeatureDisabledTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/FeatureV2EnabledTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/GroupResourceTypeEvaluationTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/GroupResourceTypeFilteringTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/GroupResourceTypePermissionTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/KeycloakAdminPermissionsServerConfig.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/PermissionRESTTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/RoleResourceTypeEvaluationTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/RoleResourceTypePermissionTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypeEvaluationSpecTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypeEvaluationTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypeFilteringTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypePermissionTest.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/rest/TestingResourceProvider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/client/KeycloakTestingClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/admin/permissions/ExportImportTestFGAPV2.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPProvidersIntegrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/AuthenticationSessionProviderTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/client/ClientModelTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/session/UserSessionInitializerTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#38749 OTelHttpClientFactory not configured properly when tracing enabled
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/tracing/OTelHttpClientFactory.java
  services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java
  tests/base/src/test/java/org/keycloak/tests/admin/tracing/TracingTest.java
Labels: team/cloud-native

#38666 fix: removing quarkus-devtools-common
  quarkus/deployment/pom.xml
Labels: team/cloud-native

#38772 Fix AvailableRoleMappingResource
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AvailableRoleMappingResource.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/AdminPermissionEvaluator.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/ClientPermissionEvaluator.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/ClientPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/ClientPermissionsV2.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissionEvaluator.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissionsV2.java
Labels: team/ui

#38776 Allow zero tracing-sampler-ratio
  docs/guides/observability/tracing.adoc
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/TracingSpec.java
  quarkus/config-api/src/main/java/org/keycloak/config/TracingOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TracingPropertyMappers.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/TracingDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
Labels: team/cloud-native

#38755 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ja.properties
Labels: team/ui

#38691 fix: improving the name of application.properties
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakConfigSourceProvider.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ShowConfigCommandDistTest.java
Labels: team/cloud-native

#38297 Document how Keycloak is upgraded when Operator is upgraded via OLM
  docs/guides/images/manual-approval-olm.png
  docs/guides/operator/installation.adoc
Labels: team/cloud-native

#38830 Make sure that there is single audience allowed by default in JWT tok…
  docs/documentation/release_notes/topics/26_2_0.adoc
  docs/documentation/upgrading/topics/changes/changes-26_2_0.adoc
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientSecretAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCProviderConfig.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OIDCJwksClientRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AbstractClientAuthSignedJWTTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38800 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ja.properties
Labels: team/ui, flaky-test

#38345 avoid missing css in attributes tab of realm roles #38162
  js/apps/admin-ui/src/components/key-value-form/AttributeForm.css
  js/apps/admin-ui/src/components/key-value-form/AttributeForm.tsx
  js/apps/admin-ui/src/components/roles-list/RolesList.css
Labels: team/ui

#38818 add option to the nginx x509 client cert lookup provider to not url-decode the passed client cert
  docs/guides/server/reverseproxy.adoc
  services/src/main/java/org/keycloak/services/x509/NginxProxySslClientCertificateLookup.java
  services/src/main/java/org/keycloak/services/x509/NginxProxySslClientCertificateLookupFactory.java
  services/src/main/java/org/keycloak/services/x509/NginxProxyTrustedClientCertificateLookup.java
Labels: team/cloud-native, flaky-test

#38738 Make whole row disabled when you don't have rights
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
  js/libs/ui-shared/src/controls/table/KeycloakDataTable.tsx
Labels: team/ui

#38768 make group select required when specific group is selected
  js/apps/admin-ui/src/clients/authorization/policy/Role.tsx
  js/apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
  js/apps/admin-ui/src/permissions-configuration/permission-evaluation/PermissionsEvaluationTab.tsx
  js/apps/admin-ui/src/permissions-configuration/resource-types/GroupSelect.tsx
  js/apps/admin-ui/src/permissions-configuration/resource-types/ResourceType.tsx
  js/apps/admin-ui/src/permissions-configuration/resource-types/RoleSelect.tsx
  js/apps/admin-ui/test/permissions/main.spec.ts
  js/apps/admin-ui/test/permissions/main.ts
Labels: team/ui

#38771 use onDataChange instead of text changed
  js/apps/admin-ui/src/clients/keys/GenerateKeyDialog.tsx
Labels: team/ui

#38774 refresh realm when policy changed
  js/apps/admin-ui/src/authentication/policies/PasswordPolicy.tsx
Labels: team/ui

#38805 clear form values before setting new one
  js/apps/admin-ui/src/user-federation/UserFederationLdapSettings.tsx
Labels: team/ui

#38831 add firefox to nightly admin e2e tests
  .github/workflows/js-ci.yml
  js/apps/admin-ui/playwright.config.ts
Labels: team/ui

#38860 align switch with dropdown
  js/apps/admin-ui/src/components/view-header/ViewHeader.tsx
Labels: team/ui

#38849 fix: preventing statefulset infinite reconciliation loop
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
Labels: team/cloud-native

#38820 added save as dialog
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/themes/FileNameDialog.tsx
  js/apps/admin-ui/src/realm-settings/themes/ThemeColors.tsx
  js/apps/admin-ui/src/realm-settings/themes/ThemesTab.tsx
Labels: team/ui

#38870 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ja.properties
Labels: team/ui

#38891 Enable quick-theme in dev mode
  js/apps/keycloak-server/scripts/start-server.js
Labels: team/ui

#38946 Enable logging of slow database operations
  model/jpa/src/main/resources/default-persistence.xml
  quarkus/runtime/src/main/resources/application.properties
Labels: team/cloud-native

#38794 fixed search on only one resource
  js/apps/admin-ui/src/permissions-configuration/resource-types/GroupSelect.tsx
  js/apps/admin-ui/src/permissions-configuration/resource-types/ResourceType.tsx
Labels: team/ui

#38861 remove delete button when flow is in use
  js/apps/admin-ui/src/authentication/FlowDetails.tsx
Labels: team/ui

#38839 make mouse select clear filter
  js/apps/admin-ui/test/realm-settings/events.ts
  js/libs/ui-shared/src/controls/select-control/TypeaheadSelectControl.tsx
Labels: team/ui

#38326 Add organizations count endpoint
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationsResource.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/InfinispanOrganizationProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/OrganizationEntity.java
  model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java
  server-spi/src/main/java/org/keycloak/organization/OrganizationProvider.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationsResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#38834 Sorting the chapters of the HA guide
  docs/guides/high-availability/pinned-guides
  docs/guides/operator/basic-deployment.adoc
  docs/guides/operator/installation.adoc
  docs/guides/operator/realm-import.adoc
  docs/guides/server/vault.adoc
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Context.java
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Guide.java
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/GuideParser.java
Labels: team/cloud-native, flaky-test

#38926 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_pt_BR.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ja.properties
Labels: team/ui

#38935 Generate random passwords for imported users in forms and webauthn tests
  .github/actions/install-chrome/action.yml
  .github/workflows/ci.yml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/TestContext.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/annotation/IgnoreBrowserDriver.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/decider/BrowserDriverIgnoreDecider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/RegisterPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/TermsAndConditionsPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractAuthTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractChangeImportedUserPasswordsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractTestRealmKeycloakTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AbstractAppInitiatedActionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/TermsAndConditionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/AbstractFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/AllowDenyAuthenticatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/AuthenticatorSubflowsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/AuthenticatorSubflowsTest2.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BrowserButtonsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BrowserFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ConditionalUserAttributeAuthenticatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/FlowOverrideTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LevelOfAssuranceFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginHotpTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTotpTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultiFactorAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultipleTabsLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/PasswordHashingTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RPInitiatedFrontChannelLogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ReAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RecoveryAuthnCodesAuthenticatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetCredentialsAlternativeFlowsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/SSOTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ScriptAuthenticatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/TransientSessionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/VerifyProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/AbstractWebAuthnVirtualTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/AppInitiatedActionWebAuthnTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnIdlessTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnPropertyTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnRegisterAndLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnTransportsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/account/AbstractWebAuthnAccountTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/account/WebAuthnSigningInTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/passwordless/PasskeysConditionalUITest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/PolicyJsInjectionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/WebAuthnOtherSettingsTest.java
  testsuite/integration-arquillian/tests/base/testsuites/forms-suite
Labels: team/cloud-native, team/core-clients, team/core-iam

#38953 Remove authentication session when deleting the account
  services/src/main/java/org/keycloak/authentication/requiredactions/DeleteAccount.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/DeleteAccountActionTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#38967 changed home button to reload
  js/apps/admin-ui/src/components/error/ErrorRenderer.tsx
Labels: team/ui

#38916 [FGAP] AvailableRoleMappings do not consider all-clients permissions
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AvailableRoleMappingResource.java
Labels: team/ui

#38980 Generate random passwords for imported users in forms and webauthn tests (26.2)
  .github/actions/install-chrome/action.yml
  .github/workflows/ci.yml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/TestContext.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/annotation/IgnoreBrowserDriver.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/decider/BrowserDriverIgnoreDecider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/RegisterPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/TermsAndConditionsPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractAuthTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractChangeImportedUserPasswordsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractTestRealmKeycloakTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AbstractAppInitiatedActionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/TermsAndConditionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/AbstractFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/AllowDenyAuthenticatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/AuthenticatorSubflowsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/AuthenticatorSubflowsTest2.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BrowserButtonsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BrowserFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ConditionalUserAttributeAuthenticatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/FlowOverrideTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LevelOfAssuranceFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginHotpTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTotpTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultiFactorAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultipleTabsLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/PasswordHashingTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RPInitiatedFrontChannelLogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ReAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RecoveryAuthnCodesAuthenticatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetCredentialsAlternativeFlowsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/SSOTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ScriptAuthenticatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/TransientSessionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/VerifyProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/AbstractWebAuthnVirtualTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/AppInitiatedActionWebAuthnTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnIdlessTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnPropertyTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnRegisterAndLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnTransportsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/account/AbstractWebAuthnAccountTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/account/WebAuthnSigningInTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/passwordless/PasskeysConditionalUITest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/PolicyJsInjectionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/WebAuthnOtherSettingsTest.java
  testsuite/integration-arquillian/tests/base/testsuites/forms-suite
Labels: team/cloud-native, team/core-clients, team/core-iam

#38987 [FGAP] AvailableRoleMappings do not consider all-clients permissions
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AvailableRoleMappingResource.java
Labels: team/ui

#39016 change readonly to disabled so that it differs from a normal field
  js/libs/ui-shared/src/user-profile/TextComponent.tsx
Labels: team/ui, flaky-test

#38986 skip tests that require clipboard permission on firefox
  js/apps/admin-ui/test/clients/authorization.spec.ts
  js/apps/admin-ui/test/clients/initial-access.spec.ts
Labels: team/ui

#38974 fixed when client select is a id instead of an clientId
  js/apps/admin-ui/src/components/client/ClientSelect.tsx
  js/libs/ui-shared/src/controls/select-control/SelectControl.tsx
  js/libs/ui-shared/src/controls/select-control/TypeaheadSelectControl.tsx
Labels: team/ui

#38998 Deprecate for removal Instagram Identity Broker
  common/src/main/java/org/keycloak/common/Profile.java
  docs/documentation/release_notes/topics/26_3_0.adoc
  docs/documentation/server_admin/topics/identity-broker/social/instagram.adoc
  docs/documentation/upgrading/topics/changes/changes-26_3_0.adoc
  services/src/main/java/org/keycloak/social/instagram/InstagramIdentityProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/SocialLoginTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38988 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_pt_BR.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ro.properties
Labels: team/ui

#38816 check for feature flags in Root.tsx's mapRoutes function
  js/apps/account-ui/src/root/Root.tsx
Labels: team/ui, flaky-test

#38952 Introducing IdpLinkAction as AIA to replace client-initiated account …
  docs/documentation/release_notes/topics/26_3_0.adoc
  docs/documentation/server_development/topics/identity-brokering/account-linking.adoc
  docs/documentation/upgrading/topics/changes/changes-26_3_0.adoc
  js/apps/account-ui/src/account-security/AccountRow.tsx
  js/apps/account-ui/src/api/methods.ts
  js/apps/account-ui/src/index.ts
  model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo26_3_0.java
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultMigrationManager.java
  server-spi-private/src/main/java/org/keycloak/authentication/RequiredActionContext.java
  server-spi-private/src/main/java/org/keycloak/broker/provider/IdentityProvider.java
  server-spi-private/src/main/java/org/keycloak/models/utils/DefaultRequiredActions.java
  services/src/main/java/org/keycloak/authentication/RequiredActionContextResult.java
  services/src/main/java/org/keycloak/broker/oidc/AbstractOAuth2IdentityProvider.java
  services/src/main/java/org/keycloak/broker/provider/IdpLinkAction.java
  services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
  services/src/main/java/org/keycloak/services/resources/account/LinkedAccountsResource.java
  services/src/main/java/org/keycloak/utils/BrokerUtil.java
  services/src/main/resources/META-INF/services/org.keycloak.authentication.RequiredActionFactory
  tests/base/src/test/java/org/keycloak/tests/admin/authentication/RequiredActionsTest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/IdpLinkActionPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerIdpLinkActionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport1903MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport198MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport255MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport343MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport483MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/JsonFileImport903MigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/MigrationTest.java
  themes/src/main/resources/theme/base/login/link-idp-action.ftl
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
  themes/src/main/resources/theme/keycloak.v2/login/link-idp-action.ftl
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#39019 Add config param disableTypeClaimCheck in order to validate external …
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/identity-providers/add/ExtendedNonDiscoverySettings.tsx
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProviderConfig.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeTest.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#39053 Unexpected AIA Cause Server Errors
  docs/documentation/server_admin/topics/users/con-aia.adoc
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39032 fix: adding imagePullSecret to update job
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java
Labels: team/cloud-native

#39068 fix: adding imagePullSecret to update job
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java
Labels: team/cloud-native

#39062 Document operator Auto update strategy when used with podTemplate
  docs/guides/operator/rolling-updates.adoc
Labels: team/cloud-native

#38827 added upload button and removed saving in realm
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/themes/ImageUpload.tsx
  js/apps/admin-ui/src/realm-settings/themes/ThemeColors.tsx
  js/apps/admin-ui/src/realm-settings/themes/ThemesTab.tsx
  js/apps/admin-ui/src/realm-settings/themes/UploadJar.tsx
Labels: team/ui

#39056 update client after import
  js/apps/admin-ui/src/clients/ClientDetails.tsx
  js/apps/admin-ui/src/clients/keys/Keys.tsx
Labels: team/ui

#39060 made the query paginated
  js/apps/admin-ui/src/permissions-configuration/permission-configuration/ExistingPoliciesDialog.tsx
Labels: team/ui

#39098 Fix test configuration for remote infinispan
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/remote/DefaultCacheRemoteConfigProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/test/resources/META-INF/keycloak-server.json
  testsuite/integration-arquillian/tests/pom.xml
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/RemoteInfinispan.java
  testsuite/utils/src/main/resources/META-INF/keycloak-server.json
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39054 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_pt_BR.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ka.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_pt_BR.properties
Labels: team/ui

#38716 Add feedback when user sync is triggered
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/user-federation/shared/ExtendedHeader.tsx
Labels: team/ui

#39069 Document operator Auto update strategy when used with podTemplate
  docs/guides/operator/rolling-updates.adoc
Labels: team/cloud-native

#39113 fix: preventing statefulset infinite reconciliation loop
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
Labels: team/cloud-native

#39129 fix: relaxing the ready=false reason to make the test less flaky
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
Labels: team/cloud-native

#39114 BACKPORT:make group select required when specific group is selected (#38768)
  js/apps/admin-ui/src/clients/authorization/policy/Role.tsx
  js/apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
  js/apps/admin-ui/src/permissions-configuration/permission-evaluation/PermissionsEvaluationTab.tsx
  js/apps/admin-ui/src/permissions-configuration/resource-types/GroupSelect.tsx
  js/apps/admin-ui/src/permissions-configuration/resource-types/ResourceType.tsx
  js/apps/admin-ui/src/permissions-configuration/resource-types/RoleSelect.tsx
  js/apps/admin-ui/test/permissions/main.spec.ts
  js/apps/admin-ui/test/permissions/main.ts
Labels: team/ui

#39115 backport 38794 26.2
  js/apps/admin-ui/src/permissions-configuration/resource-types/GroupSelect.tsx
  js/apps/admin-ui/src/permissions-configuration/resource-types/ResourceType.tsx
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#39117 BACKPORT: fixed when client select is a id instead of an clientId
  js/apps/admin-ui/src/components/client/ClientSelect.tsx
  js/apps/admin-ui/test/realm-settings/events.ts
  js/libs/ui-shared/src/controls/select-control/SelectControl.tsx
  js/libs/ui-shared/src/controls/select-control/TypeaheadSelectControl.tsx
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#39147 Fix JavaOptsScriptTest - regex update for Windows kc.home.dir path fo…
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JavaOptsScriptTest.java
Labels: team/cloud-native

#39143 Make distribution startup timeout configurable
  .github/workflows/ci.yml
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
Labels: team/cloud-native

#39149 [26.2] Make distribution startup timeout configurable
  .github/workflows/ci.yml
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
Labels: team/cloud-native, flaky-test

#39153 Fix JavaOptsScriptTest - regex update for Windows kc.home.dir path fo…
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/JavaOptsScriptTest.java
Labels: team/cloud-native

#38779 Fix range error when minimizing the string
  misc/theme-verifier/src/main/java/org/keycloak/themeverifier/VerifyMessageProperties.java
Labels: flaky-test

#38685 updated NL messages to complete missing translations and improve exist…
  themes/src/main/resources-community/theme/base/email/messages/messages_nl.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_nl.properties
Labels: team/ui

#39044 Hardcode nip.io test hosts to `/etc/hosts`
  .github/actions/integration-test-setup/action.yml
  .github/actions/update-hosts/action.yml
  .github/actions/update-hosts/nipio-hosts
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cookies/DefaultCookieProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ReverseProxy.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38947 using jenvtest for local operator testing
  .github/workflows/operator-ci.yml
  operator/README.md
  operator/pom.xml
  operator/src/test/java/org/keycloak/operator/testsuite/apiserver/ApiServerHelper.java
  operator/src/test/java/org/keycloak/operator/testsuite/apiserver/DisabledIfApiServerTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/CacheTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/ClusteringTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakNetworkPolicyTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/PodTemplateTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/RealmImportTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/TracingDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/UpdateTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/WatchedSecretsTest.java
  operator/src/test/resources/application.properties
Labels: team/cloud-native

#39189 Oracle driver problems in Keycloak 26.2.1
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
Labels: team/cloud-native

#39132 Recognize email verification during brokering from a separate auth session
  services/src/main/java/org/keycloak/authentication/actiontoken/idpverifyemail/IdpVerifyAccountLinkActionTokenHandler.java
  services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpCreateUserIfUniqueAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractFirstBrokerLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcFirstBrokerLoginTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39112 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_fr.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_nl.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_fr.properties
Labels: team/ui

#39140 Do the re-hash of password in a spearate transaction to continue login in case of model exception
  services/src/main/java/org/keycloak/credential/PasswordCredentialProvider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/HttpClientUtils.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/MutualTLSUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/concurrency/ConcurrentLoginTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39203 Fix for Better tooltip for Strategy to increase wait time in brute force settings <39198>
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/security-defences/BruteForceDetection.tsx
Labels: team/ui

#39162 fix: documenting known issues with docker
  docs/guides/server/containers.adoc
Labels: team/cloud-native

#39209 refresh when search is cleared
  js/apps/admin-ui/src/groups/GroupTable.tsx
Labels: team/ui

#39183 UserInfo request fails by using an access token obtained in Hybrid fl…
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/UserInfoTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39218 Make DateUtil convert the local dates into epoch in milliseconds
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  services/src/main/java/org/keycloak/services/util/DateUtil.java
  tests/base/src/test/java/org/keycloak/tests/admin/event/AdminEventTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/event/LoginEventsTest.java
Labels: flaky-test

#39230 Avoid using password policy for configuration of recovery codes warni…
  core/src/main/java/org/keycloak/representations/account/LocalizedMessage.java
  server-spi-private/src/main/java/org/keycloak/policy/RecoveryCodesWarningThresholdPasswordPolicyProviderFactory.java
  server-spi/src/main/java/org/keycloak/models/PasswordPolicy.java
  server-spi/src/main/java/org/keycloak/models/utils/RecoveryAuthnCodesUtils.java
  services/src/main/java/org/keycloak/authentication/requiredactions/RecoveryAuthnCodesAction.java
  services/src/main/java/org/keycloak/credential/RecoveryAuthnCodesCredentialProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AbstractRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RecoveryAuthnCodesAuthenticatorTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39126 Create CacheEmbeddedConfigProvider
  docs/documentation/upgrading/topics/changes/changes-26_3_0.adoc
  docs/guides/high-availability/deploy-infinispan-kubernetes-crossdc.adoc
  docs/guides/high-availability/examples/generated/keycloak-ispn.yaml
  docs/guides/high-availability/examples/generated/keycloak.yaml
  model/infinispan/pom.xml
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/InfinispanConnectionProvider.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/InfinispanUtil.java
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/TopologyInfo.java
  model/infinispan/src/main/java/org/keycloak/jgroups/JGroupsConfigurator.java
  model/infinispan/src/main/java/org/keycloak/jgroups/JGroupsUtil.java
  model/infinispan/src/main/java/org/keycloak/jgroups/impl/JGroupsJdbcPingStackConfigurator.java
  model/infinispan/src/main/java/org/keycloak/jgroups/impl/JpaJGroupsTlsConfigurator.java
  model/infinispan/src/main/java/org/keycloak/jgroups/protocol/KEYCLOAK_JDBC_PING2.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/CacheEmbeddedConfigProvider.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/CacheEmbeddedConfigProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/CacheEmbeddedConfigProviderSpi.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/CacheConfigurator.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/DefaultCacheEmbeddedConfigProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/JGroupsConfigurator.java
  model/infinispan/src/main/resources/META-INF/services/org.keycloak.provider.Spi
  model/infinispan/src/main/resources/META-INF/services/org.keycloak.spi.infinispan.CacheEmbeddedConfigProviderFactory
  quarkus/config-api/src/main/java/org/keycloak/config/MetricsOptions.java
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/CacheBuildSteps.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakRecorder.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/CachingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/MetricsPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/CacheManagerFactory.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/QuarkusCacheManagerProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/QuarkusInfinispanConnectionFactory.java
  quarkus/runtime/src/main/resources/META-INF/services/org.keycloak.connections.infinispan.InfinispanConnectionProviderFactory
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/AbstractConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/ExternalInfinispanTest.java
  server-spi-private/src/main/java/org/keycloak/cluster/ManagedCacheManagerProvider.java
  testsuite/integration-arquillian/HOW-TO-RUN.md
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/test/resources/META-INF/keycloak-server.json
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
  testsuite/integration-arquillian/tests/pom.xml
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/Infinispan.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/RemoteInfinispan.java
  testsuite/model/src/test/resources/test-ispn.xml
  testsuite/utils/src/main/resources/META-INF/keycloak-server.json
Labels: team/cloud-native, team/core-clients, team/core-iam

#39248 Fix duplicate users on searching attributes with multiple entries
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39197 Make sure LDAP connections are released when closing sessions
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPContextManager.java
  federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/SessionBoundInitialLdapContext.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39270 use `RETRY_COUNT` or 0
  js/apps/admin-ui/playwright.config.ts
Labels: team/ui

#39257 Add dependsOn implementation to RemoteLoadBalancerCheckProviderFactory
  model/infinispan/src/main/java/org/keycloak/connections/infinispan/remote/RemoteLoadBalancerCheckProviderFactory.java
Labels: flaky-test

#39311 Improve metadata for Recovery Codes
  js/apps/admin-ui/src/user/user-credentials/CredentialDataDialog.tsx
  js/apps/admin-ui/src/user/user-credentials/CredentialRow.tsx
  server-spi/src/main/java/org/keycloak/models/credential/RecoveryAuthnCodesCredentialModel.java
  server-spi/src/main/java/org/keycloak/models/credential/dto/RecoveryAuthnCodesCredentialData.java
  server-spi/src/main/java/org/keycloak/models/utils/RecoveryAuthnCodesUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RecoveryAuthnCodesAuthenticatorTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#39017 Make recovery codes supported
  common/src/main/java/org/keycloak/common/Profile.java
  docs/documentation/release_notes/topics/26_3_0.adoc
  docs/documentation/server_admin/topics/authentication/recovery-codes.adoc
  server-spi-private/src/main/java/org/keycloak/models/utils/DefaultRequiredActions.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/RecoveryAuthnCodesFormAuthenticator.java
  tests/base/src/test/java/org/keycloak/tests/admin/authentication/ProvidersTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authentication/RequiredActionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/feature/RecoveryAuthnCodesFeatureTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/BackwardsCompatibilityUserStorageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LevelOfAssuranceFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RecoveryAuthnCodesAuthenticatorTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39329 test improvements
  js/apps/admin-ui/src/components/help-enabler/HelpHeader.tsx
  js/apps/admin-ui/test/autentication/policies.ts
  js/apps/admin-ui/test/clients/registration-policies.spec.ts
  js/apps/admin-ui/test/identity-providers/saml.spec.ts
  js/apps/admin-ui/test/masthead/main.spec.ts
  js/apps/admin-ui/test/masthead/main.ts
  js/apps/admin-ui/test/realm-settings/email.spec.ts
Labels: team/ui

#39095 fix: relaxes the admin root redirect check
  docs/documentation/upgrading/topics/changes/changes-26_3_0.adoc
  server-spi/src/main/java/org/keycloak/urls/UrlType.java
  services/src/main/java/org/keycloak/services/resources/WelcomeResource.java
  services/src/main/java/org/keycloak/services/resources/admin/AdminRoot.java
  tests/base/src/test/java/org/keycloak/tests/admin/AdminRootEdgeTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/AdminRootTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/url/HostnameV2Test.java
  themes/src/main/resources/theme/keycloak/welcome/index.ftl
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#39328 Uncaught server error during organization update when name already ex…
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/OrganizationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37926 addresses slow import/export performance by limiting persistence context size
  docs/documentation/upgrading/topics/changes/changes-26_3_0.adoc
  docs/guides/server/importExport.adoc
  model/jpa/src/main/java/org/keycloak/connections/jpa/DefaultJpaConnectionProviderFactory.java
  model/jpa/src/main/java/org/keycloak/connections/jpa/PersistenceExceptionConverter.java
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  model/storage-services/src/main/java/org/keycloak/exportimport/dir/DirImportProvider.java
  model/storage-services/src/main/java/org/keycloak/exportimport/singlefile/SingleFileExportProvider.java
  model/storage-services/src/main/java/org/keycloak/exportimport/singlefile/SingleFileImportProvider.java
  model/storage-services/src/main/java/org/keycloak/exportimport/util/ExportImportSessionTask.java
  model/storage-services/src/main/java/org/keycloak/exportimport/util/ImportUtils.java
  model/storage-services/src/main/java/org/keycloak/exportimport/util/MultipleStepsExportProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/jpa/AbstractJpaConnectionProviderFactory.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ImportDistTest.java
  server-spi-private/pom.xml
  server-spi-private/src/main/java/org/keycloak/connections/jpa/support/EntityManagerProxy.java
  server-spi-private/src/main/java/org/keycloak/connections/jpa/support/EntityManagers.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  server-spi/src/main/java/org/keycloak/models/KeycloakSessionTask.java
  services/src/main/java/org/keycloak/exportimport/ExportImportConfig.java
  services/src/main/java/org/keycloak/services/managers/RealmManager.java
  services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/ClientModelTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39340 fix: adding a check for truncated last modified timestamps
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
Labels: team/cloud-native

#39215 fix: documenting known issues with docker (#39162)
  docs/guides/server/containers.adoc
Labels: team/cloud-native

#39337 fix: relaxes the admin root redirect check (#39095)
  services/src/main/java/org/keycloak/services/resources/WelcomeResource.java
  services/src/main/java/org/keycloak/services/resources/admin/AdminRoot.java
  tests/base/src/test/java/org/keycloak/tests/admin/AdminRootEdgeTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/AdminRootTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/url/HostnameV2Test.java
  themes/src/main/resources/theme/keycloak/welcome/index.ftl
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#39295 [Backport] Fix duplicate users on searching attributes with multiple entries
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39302 [Backport 26.2] Remove authentication session when deleting the account
  services/src/main/java/org/keycloak/authentication/requiredactions/DeleteAccount.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/DeleteAccountActionTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39224 Do the re-hash of password in a separate transaction to continue login in case of model exception (26.2)
  services/src/main/java/org/keycloak/credential/PasswordCredentialProvider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/HttpClientUtils.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/MutualTLSUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/concurrency/ConcurrentLoginTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39190 [26.2] Oracle driver problems in Keycloak 26.2.1
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
Labels: team/cloud-native

#39231 UserInfo request fails by using an access token obtained in Hybrid flow with offline_access scope
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/UserInfoTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39351 Make sure Cancel AIA does not remove required action from user
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/URLUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionResetPasswordTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionPriorityTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39169 Hardcode nip.io test hosts to `/etc/hosts`
  .github/actions/integration-test-setup/action.yml
  .github/actions/update-hosts/action.yml
  .github/actions/update-hosts/nipio-hosts
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cookies/DefaultCookieProviderTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/ReverseProxy.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39364 fix: adding a check for truncated last modified timestamps (#39340)
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
Labels: team/cloud-native

#39326 Partial backport of #34980 to upgrade creaper and https initialization for eap8 and wildfly
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/AppServerTestEnricher.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#39361 Add option to log details in the JBossLoggingEventListenerProvider
  js/apps/admin-ui/src/realm-settings/event-config/EventConfigForm.tsx
  services/pom.xml
  services/src/main/java/org/keycloak/events/log/JBossLoggingEventListenerProvider.java
  services/src/main/java/org/keycloak/events/log/JBossLoggingEventListenerProviderFactory.java
  services/src/test/java/org/keycloak/events/log/JBossLoggingEventListenerProviderTest.java
  services/src/test/resources/log4j.properties
  services/src/test/resources/logging.properties
Labels: team/ui, team/core-clients

#39366 fix: remove ANY mode modification of truststores
  docs/guides/server/keycloak-truststore.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/TruststoreOptions.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBootstrapAdminService.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testBootstrapAdminUser.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testExportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testImportHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
  services/src/main/java/org/keycloak/truststore/JSSETruststoreConfigurator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/ssl/TrustStoreEmailTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/keystore/email_invalid.jks
Labels: team/cloud-native, team/core-clients, team/core-iam

#39320 add translation for default locale
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
Labels: team/ui
