Repository keycloak/keycloak, pull requests merged in 2025-01, with the labels that each got.

#36169 Updated invalid URL in log message
  js/libs/keycloak-js/lib/keycloak.js
Labels: team/ui

#36046 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_es.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ja.properties
Labels: team/ui

#36206 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
Labels: team/ui

#36208 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_de.properties
Labels: team/ui

#35949 Re-calculate the organization scope when re-authenticating in the browser flow
  services/src/main/java/org/keycloak/authentication/authenticators/browser/CookieAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationMembershipMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationOIDCProtocolMapperTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#36209 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
Labels: team/ui

#36221 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
Labels: team/ui

#36173 "Remove role" alert text is wrong
  js/apps/admin-ui/cypress/e2e/clients_role.spec.ts
  js/apps/admin-ui/cypress/e2e/clients_test.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_roles_test.spec.ts
  js/apps/admin-ui/cypress/e2e/realm_user_registration.spec.ts
  js/apps/admin-ui/src/components/role-mapping/RoleMapping.tsx
Labels: team/ui

#36243 Fix NPE when exchanging external using the issuer value
  services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProviderResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36049 Add metric for password validations
  crypto/default/src/main/java/org/keycloak/crypto/hash/Argon2PasswordHashProvider.java
  docs/documentation/release_notes/topics/26_1_0.adoc
  docs/guides/high-availability/concepts-memory-and-cpu-sizing.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/MetricsOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/MetricsPropertyMappers.java
  server-spi/src/main/java/org/keycloak/credential/hash/PasswordHashProvider.java
  services/pom.xml
  services/src/main/java/org/keycloak/credential/PasswordCredentialProvider.java
  services/src/main/java/org/keycloak/credential/PasswordCredentialProviderFactory.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/DistributionKeycloakServer.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/EmbeddedKeycloakServer.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/KeycloakServer.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/KeycloakUrls.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/KeycloakUrlsSupplier.java
  test-framework/core/src/main/java/org/keycloak/test/framework/server/RemoteKeycloakServer.java
  tests/base/src/test/java/org/keycloak/test/admin/metric/PasswordValidationMetricCustomTagsTest.java
  tests/base/src/test/java/org/keycloak/test/admin/metric/PasswordValidationMetricTest.java
Labels: team/cloud-native

#35078 Upgrade to Quarkus 3.15.2
  pom.xml
  quarkus/pom.xml
  services/src/main/java/org/keycloak/services/resources/account/AccountLoader.java
  tests/base/src/test/java/org/keycloak/test/admin/AdminPreflightTest.java
Labels: team/cloud-native, flaky-test

#36250 Error when re-authenticating when organization is enabled
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36264 OTEL: merge Operator tracing test cases
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/TracingDeploymentTest.java
Labels: team/cloud-native

#36228 fix: remove the use of regex for determining local addresses
  services/src/main/java/org/keycloak/utils/SecureContextResolver.java
  services/src/test/java/org/keycloak/utils/SecureContextResolverTest.java
Labels: flaky-test

#36277 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_es.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_nl.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
Labels: team/ui

#36252 Unable to set '--log-syslog-max-length' property
  quarkus/config-api/src/main/java/org/keycloak/config/LoggingOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
Labels: team/cloud-native

#36302 KeycloakServer application not working
  testsuite/utils/pom.xml
Labels: team/cloud-native, team/core-clients, team/core-iam

#36281 Attribute is required only if the corresponding field in the metadata is set
  js/libs/ui-shared/src/user-profile/utils.ts
Labels: team/ui

#35404 WebAuthn registration now respects the configured extra origins policy
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnRegister.java
Labels: status/ready, team/core-clients

#36299 Incorrect manage permission for getting a specific execution
  services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/PermissionsTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36319 KerberosLdapCrossRealmTrustTest.test03SpnegoLoginUsernamePassword
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/KerberosLdapCrossRealmTrustTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36328 Add 26.1.0 release to release notes
  docs/documentation/release_notes/index.adoc
Labels: priority/blocker

#36324 fix: increasing the startup timeout to 1 hour
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
Labels: team/cloud-native

#36300 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
Labels: team/ui

#36238 fixed banner style
  js/apps/admin-ui/src/App.tsx
  js/apps/admin-ui/src/Banners.tsx
  js/apps/admin-ui/src/PageHeader.tsx
  js/apps/admin-ui/src/banners.module.css
  js/apps/admin-ui/src/index.css
Labels: team/ui

#36077 fix the empty state of the role mapper because clients is the default
  js/apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
Labels: team/ui

#36212 Add a full-stop to all admin UI help texts where it is missing
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#36260 fixed pagination
  js/apps/admin-ui/src/clients/ClientSessions.tsx
Labels: team/ui

#36357 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ca.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
Labels: team/ui

#36358 Revert "fix: increasing the startup timeout to 1 hour"
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
Labels: team/cloud-native

#36379 Avoid being rate-limited by LinkedIn in tests
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#36387 Exclude WebAuthn4J from Quarkus managed versions
  quarkus/set-quarkus-version.sh
Labels: team/cloud-native

#36283 fix: remove the use of regex for determining local addresses (#36228)
  services/pom.xml
  services/src/main/java/org/keycloak/utils/SecureContextResolver.java
  services/src/test/java/org/keycloak/utils/SecureContextResolverTest.java
Labels: status/ready

#36067 Fix content-type for content.json (#35971)
  common/src/main/java/org/keycloak/common/util/MimeTypeUtil.java
Labels: flaky-test

#35993 Failed to authenticate client with method client_secret_jwt when clie…
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientSecretAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSecretSignedJWTTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
Labels: status/ready, team/cloud-native, flaky-test, team/core-clients, team/core-iam

#35951 BACKPORT: Fix user attributes search: Fix the JS error when switching from "default search" to "attributes search"
  js/apps/admin-ui/src/components/users/UserDataTableAttributeSearchForm.tsx
Labels: team/ui

#35771 OTEL: Fix #podNamePropagation test for Operator
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
Labels: status/ready, team/cloud-native, flaky-test

#35792 Backport: fix issue re-ordering flows
  js/apps/admin-ui/src/authentication/execution-model.ts
Labels: team/ui

#35795 Typo in using custom Keycloak image for Operator guide
  docs/guides/operator/customizing-keycloak.adoc
Labels: status/ready, team/cloud-native

#35812 Improve the note about group synchronization in sssd (26.0)
  docs/documentation/server_admin/topics/user-federation/sssd.adoc
Labels: status/ready

#35805 Backport to fix showing events auth and representation
  js/libs/ui-shared/src/controls/table/KeycloakDataTable.tsx
Labels: team/ui, flaky-test

#35819 Adding retry when clicking on rememberMe checkbox on the loginPage during tests
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/UIUtils.java
Labels: status/ready, team/cloud-native, flaky-test, team/core-clients, team/core-iam

#35828 fix: removing doc that suggests using the config file for quarkus props
  docs/guides/server/configuration.adoc
Labels: status/ready, team/cloud-native

#35866 [Backport] Better path parameter names for organization and member APIs
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationMemberResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationsResource.java
Labels: flaky-test

#35898 fix: updating the partially dynamic url to not include path (#35831)
  docs/guides/server/hostname.adoc
Labels: status/ready, team/cloud-native

#35956 Fix GitHub Links to quickstarts in getting started guide (#35919)
  docs/guides/getting-started/getting-started-kube.adoc
  docs/guides/getting-started/getting-started-openshift.adoc
Labels: status/ready

#35992 Failed to authenticate client with method client_secret_jwt when clie…
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientSecretAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSecretSignedJWTTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
Labels: status/ready, team/cloud-native, flaky-test, team/core-clients, team/core-iam

#36204 [backport 26.0] Add default max-count for cache-local.xml file
  quarkus/runtime/src/main/resources/cache-local.xml
Labels: team/cloud-native, flaky-test

#36246 Upgrade to Quarkus 3.15.2
  pom.xml
  quarkus/pom.xml
  services/src/main/java/org/keycloak/services/resources/account/AccountLoader.java
Labels: status/ready, team/cloud-native, flaky-test

#36253 Unable to set '--log-syslog-max-length' property
  quarkus/config-api/src/main/java/org/keycloak/config/LoggingOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
Labels: status/ready, team/cloud-native, flaky-test

#36255 Remove ignored links from the documentation tests after KC 26 release
  docs/documentation/tests/src/test/resources/ignored-links
Labels: status/ready

#36275 Translations specified in the admin console do not override the trans…
  services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/LoginPageTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#36251 [Backport] Fix NPE when exchanging external using the issuer value
  services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java
  services/src/main/java/org/keycloak/services/resources/admin/IdentityProviderResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#36367 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
Labels: team/ui

#36078 Incomplete registration form when edit email is disabled and email is…
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java
  services/src/main/java/org/keycloak/forms/login/freemarker/model/AbstractUserProfileBean.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/RegisterPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UIRealmResourceTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#35234 Update UP via provider instead of going through the UserProfileResource
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UIRealmResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UserProfileResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UIRealmResourceTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#34436 Add Events tab to relevant objects in the UI
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/client-scopes/EditClientScope.tsx
  js/apps/admin-ui/src/client-scopes/routes/ClientScope.tsx
  js/apps/admin-ui/src/clients/ClientDetails.tsx
  js/apps/admin-ui/src/clients/routes/Client.tsx
  js/apps/admin-ui/src/events/AdminEvents.tsx
  js/apps/admin-ui/src/events/UserEvents.tsx
  js/apps/admin-ui/src/groups/GroupsSection.tsx
  js/apps/admin-ui/src/identity-providers/add/DetailSettings.tsx
  js/apps/admin-ui/src/identity-providers/routes/IdentityProvider.tsx
  js/apps/admin-ui/src/organizations/DetailOrganization.tsx
  js/apps/admin-ui/src/organizations/routes/EditOrganization.tsx
  js/apps/admin-ui/src/realm-roles/RealmRoleTabs.tsx
  js/apps/admin-ui/src/realm-roles/routes/RealmRole.tsx
  js/apps/admin-ui/src/user/EditUser.tsx
  js/apps/admin-ui/src/user/routes/User.tsx
Labels: team/ui

#36406 [Backport] Attribute is required only if the corresponding field in the metadata is set
  js/libs/ui-shared/src/user-profile/utils.ts
Labels: team/ui, flaky-test

#36415 [Backport] Re-calculate the organization scope when re-authenticating in the browser flow
  services/src/main/java/org/keycloak/authentication/authenticators/browser/CookieAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationMembershipMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationOIDCProtocolMapperTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36411 Show error when UI realm resource fails
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UIRealmResource.java
Labels: team/ui

#36068 Fix content-type for content.json (#35971)
  common/src/main/java/org/keycloak/common/util/MimeTypeUtil.java
Labels: flaky-test

#36404 Avoid being rate-limited by LinkedIn in tests
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36403 Avoid being rate-limited by LinkedIn in tests
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/IdentityProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#36352 FGA: Allow view users attached to one specific client role
  js/apps/admin-ui/src/clients/routes/ClientRole.tsx
Labels: team/ui

#36292 BACKPORT: add empty hidden input so that empty checkboxes get submitted (#35552)
  themes/src/main/resources/theme/keycloak.v2/login/user-profile-commons.ftl
Labels: team/ui

#36433 Fix Forgot Password?-button on the login-password page
  themes/src/main/resources/theme/keycloak.v2/login/login-password.ftl
Labels: team/ui

#36426 Make @EnableFeature to handle the case with added provider of current…
  services/src/main/java/org/keycloak/provider/ProviderManager.java
  services/src/main/java/org/keycloak/services/DefaultKeycloakSessionFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/util/FeatureDeployerUtil.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/util/TestsuiteProviderLoader.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientTypesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36472 Restrict access to environment variables when at the server runtime
  adapters/saml/core/src/main/java/org/keycloak/adapters/saml/config/parsers/KeyParser.java
  authz/client/src/main/java/org/keycloak/authorization/client/AuthzClient.java
  authz/client/src/main/java/org/keycloak/authorization/client/SystemPropertiesJsonParserFactory.java
  authz/client/src/test/java/org/keycloak/authorization/client/JsonParserTest.java
  authz/client/src/test/resources/keycloak.json
  common/src/main/java/org/keycloak/common/util/StringPropertyReplacer.java
  common/src/main/java/org/keycloak/common/util/SystemEnvProperties.java
  common/src/test/java/org/keycloak/common/util/StringPropertyReplacerTest.java
  core/src/main/java/org/keycloak/Config.java
  core/src/main/java/org/keycloak/util/JsonSerialization.java
  core/src/test/java/org/keycloak/JsonParserTest.java
  docs/documentation/upgrading/topics/changes/changes-26_0_8.adoc
  docs/guides/server/configuration.adoc
  model/jpa/src/main/java/org/keycloak/connections/jpa/DefaultJpaConnectionProviderFactory.java
  saml-core/src/main/java/org/keycloak/saml/common/util/StaxParserUtil.java
  services/src/main/java/org/keycloak/services/managers/ResourceAdminManager.java
  services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java
  services/src/main/java/org/keycloak/services/util/ResolveRelative.java
  services/src/main/java/org/keycloak/theme/DefaultThemeManager.java
  services/src/test/java/org/keycloak/utils/JsonConfigProvider.java
  services/src/test/java/org/keycloak/utils/ScopeUtil.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/AuthServerTestEnricher.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/DeploymentTargetModifier.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcSamlIdPInitiatedSsoTest.java
  testsuite/model/src/main/java/org/keycloak/testsuite/model/Config.java
  testsuite/utils/src/main/java/org/keycloak/testsuite/JsonConfigProviderFactory.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#35934 Add option to sign the IdP metadata for SAML
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/add/SamlSignature.tsx
  js/apps/admin-ui/src/realm-settings/GeneralTab.tsx
  saml-core/src/main/java/org/keycloak/saml/processing/core/saml/v2/util/SAMLMetadataUtil.java
  server-spi/src/main/java/org/keycloak/models/RealmModel.java
  services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java
  services/src/main/java/org/keycloak/protocol/saml/IDPMetadataDescriptor.java
  services/src/main/java/org/keycloak/protocol/saml/SamlService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java
Labels: status/ready, team/cloud-native, team/ui, team/core-clients, team/core-iam

#36348 fixed sidebar nav vertical scroll on smaller screens
  js/apps/admin-ui/src/App.tsx
  js/apps/admin-ui/src/page-nav.css
Labels: status/ready, team/ui

#36018 [FGAP] Design AdminPermissionEvaluator implementation for FGAP v2
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/permission/ScopePolicyProviderFactory.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaClientProviderFactory.java
  server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java
  server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  services/src/main/java/org/keycloak/services/managers/RealmManager.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/AdminPermissionManagement.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/AdminPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissionsV2.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RealmPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissionManagement.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissionsV2.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/UserConfigBuilder.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/AbstractPermissionTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/RealmAdminPermissionsConfig.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypeEvaluationTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypePermissionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientTokenExchangeSAML2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientTokenExchangeTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#36393 Update the documentation on how to run Keycloak IPv6 only
  docs/guides/server/caching.adoc
  docs/guides/server/configuration-production.adoc
Labels: team/cloud-native, team/ui

#36504 fix: adding the jgroups bind address for ipv6 support
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/CRAssert.java
Labels: team/cloud-native, flaky-test

#36461 Deployment artifacts for Quarkus extensions are not in deployment dir
  quarkus/server/pom.xml
Labels: team/cloud-native, flaky-test

#36488 Deployment artifacts for Quarkus extensions are not in deployment dir
  quarkus/server/pom.xml
Labels: team/cloud-native

#34345 CreatedResponseUtil.getCreatedId should expose server error message (#34343)
  integration/admin-client/src/main/java/org/keycloak/admin/client/CreatedResponseUtil.java
Labels: team/core-clients

#36466 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ja.properties
Labels: team/ui, flaky-test

#36407 Token exchange - added experimental token exchange V2 divided into mu…
  common/src/main/java/org/keycloak/common/Profile.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/TokenExchangeGrantTypeFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/AbstractTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/FederatedTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/FederatedTokenExchangeProviderFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProviderFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/SubjectImpersonationTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/SubjectImpersonationTokenExchangeProviderFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/V1TokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/V1TokenExchangeProviderFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.protocol.oidc.TokenExchangeProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeFederatedTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeV1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/AbstractStandardTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/AbstractSubjectImpersonationTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/ClientTokenExchangeSAML2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/SubjectImpersonationTokenExchangeV1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/SubjectImpersonationTokenExchangeV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/TokenExchangeTestUtils.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36523 Update the documentation on how to run Keycloak IPv6 only
  docs/guides/server/caching.adoc
  docs/guides/server/configuration-production.adoc
Labels: team/cloud-native

#34459 Fix social login tests
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social/InstagramLoginPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/social/TwitterLoginPage.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36536 Remove duplicate keys in email template message file
  themes/src/main/resources-community/theme/base/email/messages/messages_fa.properties
Labels: team/ui

#36436 [Backport] Error when re-authenticating when organization is enabled
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36528 CreatedResponseUtil.getCreatedId should expose server error message (#34343)
  integration/admin-client/src/main/java/org/keycloak/admin/client/CreatedResponseUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/FlowTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36350 Allow enforce that users are members of organizations when authenticating
  docs/documentation/server_admin/topics/organizations/authenticating-members.adoc
  docs/documentation/server_admin/topics/organizations/mapping-organization-claims.adoc
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticatorFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/FlowUtil.java
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#36542 Keycloak can only be built from source with JDK 21
  docs/building.md
Labels: status/ready

#36570 [Keycloak CI] - Cookies tests - KcOidcBrokerTokenExchangeTest
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36538 Change fill color of Authenticator icons to current font color
  themes/src/main/resources/theme/keycloak.v2/login/webauthn-authenticate.ftl
Labels: team/ui

#36602 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
Labels: team/ui

#36601 Extend REST API for login and admin events to support sync scenarios
  core/src/main/java/org/keycloak/representations/idm/AdminEventRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/EventRepresentation.java
  docs/documentation/release_notes/index.adoc
  docs/documentation/release_notes/topics/26_2_0.adoc
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/RealmResource.java
  model/jpa/src/main/java/org/keycloak/events/jpa/JpaAdminEventQuery.java
  model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventQuery.java
  server-spi-private/src/main/java/org/keycloak/events/EventQuery.java
  server-spi-private/src/main/java/org/keycloak/events/admin/AdminEventQuery.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  services/src/main/java/org/keycloak/services/util/DateUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/event/AdminEventTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/event/LoginEventsTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36610 BACKPORT: Change fill color of Authenticator icons to current font color (#36538)
  themes/src/main/resources/theme/keycloak.v2/login/webauthn-authenticate.ftl
Labels: team/ui

#36619 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
Labels: team/ui

#36613 Adding SAML adapter zip distribution back to the sources
  distribution/pom.xml
  distribution/saml-adapters/pom.xml
  distribution/saml-adapters/shared-cli/adapter-elytron-install-saml-offline.cli
  distribution/saml-adapters/shared-cli/adapter-elytron-install-saml.cli
  distribution/saml-adapters/shared-cli/adapter-install-saml-offline.cli
  distribution/saml-adapters/shared-cli/adapter-install-saml.cli
  distribution/saml-adapters/wildfly-adapter/pom.xml
  distribution/saml-adapters/wildfly-adapter/wildfly-adapter-zip/assembly.xml
  distribution/saml-adapters/wildfly-adapter/wildfly-adapter-zip/pom.xml
  distribution/saml-adapters/wildfly-adapter/wildfly-modules/assembly.xml
  distribution/saml-adapters/wildfly-adapter/wildfly-modules/build.xml
  distribution/saml-adapters/wildfly-adapter/wildfly-modules/lib.xml
  distribution/saml-adapters/wildfly-adapter/wildfly-modules/pom.xml
  distribution/saml-adapters/wildfly-adapter/wildfly-modules/src/main/resources/licenses/keycloak/licenses.xml
  pom.xml
Labels: flaky-test

#36620 Remove usage of deprecated thread_dumps_threshold configuration
  model/infinispan/src/main/resources/default-configs/default-keycloak-jgroups-udp.xml
  testsuite/model/pom.xml
  testsuite/model/src/main/resources/hotrod/hotrod1.xml
  testsuite/model/src/main/resources/hotrod/hotrod2.xml
Labels: team/cloud-native, team/core-clients, team/core-iam

#36414 Show error when validate email sending fails
  services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java
  services/src/main/java/org/keycloak/authentication/requiredactions/VerifyEmail.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/ssl/TrustStoreEmailTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36568 Allow using a custom scope name when mapping organization to tokens
  services/src/main/java/org/keycloak/authentication/authenticators/browser/CookieAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationMembershipMapper.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationScope.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationOIDCProtocolMapperTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36647 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ca.properties
Labels: team/ui

#36494 Fixing typos and grammar errors in the admin UI
  js/apps/admin-ui/cypress/e2e/client_scopes_test.spec.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/tabs/InitialAccessTokenTab.ts
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/RealmSettingsPage.ts
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#36454 fixed sorting of elements
  js/apps/admin-ui/src/components/realm-selector/RealmSelector.tsx
Labels: team/ui

#36674 BACKPORT: fix AccessContext in bundle (#36516)
  js/apps/admin-ui/src/App.tsx
  js/apps/admin-ui/src/index.ts
Labels: team/ui

#36688 Upgrade Infinispan to 15.0.12.Final
  pom.xml
  testsuite/model/src/main/java/org/keycloak/testsuite/model/HotRodServerRule.java
Labels: team/cloud-native, team/core-clients, team/core-iam, team/sre

#36693 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ca.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_nl.properties
Labels: team/ui

#36604 [Backport] Allow enforce that users are members of organizations when authenticating
  docs/documentation/server_admin/topics/organizations/authenticating-members.adoc
  docs/documentation/server_admin/topics/organizations/mapping-organization-claims.adoc
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticatorFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/FlowUtil.java
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#36603 [Backport] Allow enforce that users are members of organizations when authenticating
  docs/documentation/server_admin/topics/organizations/authenticating-members.adoc
  docs/documentation/server_admin/topics/organizations/mapping-organization-claims.adoc
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmAdapter.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticatorFactory.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/FlowUtil.java
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#36694 fixed viewport scale for mobile
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
Labels: team/ui

#36731 Check next update time for CRL in certificate validation (26.1)
  docs/documentation/release_notes/index.adoc
  docs/documentation/release_notes/topics/26_1_1.adoc
  docs/documentation/server_admin/topics/authentication/x509.adoc
  services/src/main/java/org/keycloak/authentication/authenticators/x509/AbstractX509ClientCertificateAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/x509/AbstractX509ClientCertificateAuthenticatorFactory.java
  services/src/main/java/org/keycloak/authentication/authenticators/x509/CertificateValidator.java
  services/src/main/java/org/keycloak/authentication/authenticators/x509/X509AuthenticatorConfigModel.java
  services/src/main/java/org/keycloak/utils/CRLUtils.java
  testsuite/integration-arquillian/servers/auth-server/common/keystore/empty-expired.crl
  testsuite/integration-arquillian/servers/auth-server/common/keystore/empty.crl
  testsuite/integration-arquillian/servers/auth-server/common/keystore/intermediate-ca.crl
  testsuite/integration-arquillian/servers/auth-server/common/pki/root/ca/intermediate/crlnumber
  testsuite/integration-arquillian/servers/auth-server/common/pki/root/ca/intermediate/crlnumber.old
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/AbstractX509AuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509BrowserCRLTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36730 Check next update time for CRL in certificate validation (26.0)
  docs/documentation/release_notes/index.adoc
  docs/documentation/release_notes/topics/26_0_10.adoc
  docs/documentation/server_admin/topics/authentication/x509.adoc
  services/src/main/java/org/keycloak/authentication/authenticators/x509/AbstractX509ClientCertificateAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/x509/AbstractX509ClientCertificateAuthenticatorFactory.java
  services/src/main/java/org/keycloak/authentication/authenticators/x509/CertificateValidator.java
  services/src/main/java/org/keycloak/authentication/authenticators/x509/X509AuthenticatorConfigModel.java
  services/src/main/java/org/keycloak/utils/CRLUtils.java
  testsuite/integration-arquillian/servers/auth-server/common/keystore/empty-expired.crl
  testsuite/integration-arquillian/servers/auth-server/common/keystore/empty.crl
  testsuite/integration-arquillian/servers/auth-server/common/keystore/intermediate-ca.crl
  testsuite/integration-arquillian/servers/auth-server/common/pki/root/ca/intermediate/crlnumber
  testsuite/integration-arquillian/servers/auth-server/common/pki/root/ca/intermediate/crlnumber.old
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/AbstractX509AuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/x509/X509BrowserCRLTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36680 fix incorrect statement about BC FIPS licences
  docs/guides/server/fips.adoc
Labels: team/cloud-native

#32922 Update realm: Remove browser security header attributes from the list of attributes to remove if missing
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#36681 [Backport - 26.0] Allow using a custom scope name when mapping organization to tokens
  services/src/main/java/org/keycloak/authentication/authenticators/browser/CookieAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationMembershipMapper.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationScope.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationOIDCProtocolMapperTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36682 [Backport 26.1] Allow using a custom scope name when mapping organization to tokens
  services/src/main/java/org/keycloak/authentication/authenticators/browser/CookieAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationMembershipMapper.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationScope.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/mapper/OrganizationOIDCProtocolMapperTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36741 Check client consents when audience is for the same client
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/AbstractTokenExchangeProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/AbstractStandardTokenExchangeTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36441 Select auth flow via acr using client policies
  docs/documentation/release_notes/topics/26_2_0.adoc
  docs/documentation/server_admin/topics/authentication/flows.adoc
  docs/documentation/server_admin/topics/clients/client-policies.adoc
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  server-spi-private/src/main/java/org/keycloak/models/utils/AuthenticationFlowResolver.java
  services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java
  services/src/main/java/org/keycloak/authentication/authenticators/util/AcrStore.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  services/src/main/java/org/keycloak/services/clientpolicy/condition/AcrCondition.java
  services/src/main/java/org/keycloak/services/clientpolicy/condition/AcrConditionFactory.java
  services/src/main/java/org/keycloak/services/clientpolicy/context/AuthorizationRequestContext.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/AuthenticationFlowSelectorExecutor.java
  services/src/main/java/org/keycloak/services/clientpolicy/executor/AuthenticationFlowSelectorExecutorFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.services.clientpolicy.condition.ClientPolicyConditionProviderFactory
  services/src/main/resources/META-INF/services/org.keycloak.services.clientpolicy.executor.ClientPolicyExecutorProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AcrAuthFlowTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36753 Avoid both logging an error and throwing an exception
  services/src/main/java/org/keycloak/transaction/JtaTransactionWrapper.java
Labels: flaky-test

#36719 [Backport 26.1] Support for the login_hint parameter in the identity-first login page
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#36718 [Backport 26.0] Support for the login_hint parameter in the identity-first login page
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#36765 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ca.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
Labels: team/ui

#36713 Remember the organization once selected when reloading pages
  services/src/main/java/org/keycloak/authentication/authenticators/browser/CookieAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationScope.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/AbstractBrokerSelfRegistrationTest.java
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#36481 New CLI command: update-compatibility
  docs/guides/server/pinned-guides
  docs/guides/server/update-compatibility.adoc
  docs/guides/templates/kc.adoc
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/ShortErrorMessageHandler.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractUpdatesCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/Main.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/UpdateCompatibility.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/UpdateCompatibilityCheck.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/UpdateCompatibilityMetadata.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/compatibility/CompatibilityComparator.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/compatibility/CompatibilityManager.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/compatibility/CompatibilityManagerImpl.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/compatibility/CompatibilityResult.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/compatibility/IncompatibleResult.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/compatibility/ServerInfo.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HelpCommandDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/UpdateCommandDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testDefaultToHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testHelpShort.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/RawKeycloakDistribution.java
Labels: team/cloud-native, flaky-test

#36742 stop adding content-type header to GET requests
  js/libs/keycloak-admin-client/src/resources/agent.ts
Labels: team/ui

#36791 [Backport 26.1] Remember the organization once selected when reloading pages
  services/src/main/java/org/keycloak/authentication/authenticators/browser/CookieAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationScope.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/AbstractBrokerSelfRegistrationTest.java
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#36790 [Backport 26.0] Remember the organization once selected when reloading pages
  services/src/main/java/org/keycloak/authentication/authenticators/browser/CookieAuthenticator.java
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/protocol/mappers/oidc/OrganizationScope.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/AbstractBrokerSelfRegistrationTest.java
  themes/src/main/resources/theme/base/login/messages/messages_en.properties
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#36759 Openshift conflict
  docs/guides/operator/basic-deployment.adoc
Labels: team/cloud-native

#36808 Openshift conflict
  docs/guides/operator/basic-deployment.adoc
Labels: team/cloud-native

#36807 Openshift conflict
  docs/guides/operator/basic-deployment.adoc
Labels: team/cloud-native

#36809 Openshift conflict
  docs/guides/operator/basic-deployment.adoc
Labels: team/cloud-native

#36104 Remove IDELauncher. Use org.keycloak.Keycloak
  quarkus/README.md
  quarkus/server/pom.xml
  quarkus/server/src/main/java/org/keycloak/quarkus/_private/IDELauncher.java
  quarkus/tests/junit5/src/main/java/org/keycloak/Keycloak.java
Labels: team/cloud-native, flaky-test

#36803 Add some common headers for the links check in docs (24.0)
  docs/documentation/server_admin/topics/authentication/password-policies.adoc
  docs/documentation/tests/src/test/java/org/keycloak/documentation/test/utils/HttpUtils.java
Labels: flaky-test

#36758 Upgrade to Quarkus 3.17.8
  pom.xml
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/Configuration.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KcEnvConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakConfigSourceProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakPropertiesConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PersistedConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/QuarkusPropertiesConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/AbstractConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/OptionsDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ShowConfigCommandDistTest.java
  test-framework/core/src/main/java/org/keycloak/testframework/config/Config.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/client/KeycloakTestingClient.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/AdminClientUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/servlet/SAMLServletAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ImpersonationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractAdvancedBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenRevocationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/hok/HoKTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#36857 Add support for .env-test file in new test framework
  .gitignore
  test-framework/README.md
  test-framework/core/src/main/java/org/keycloak/testframework/config/Config.java
Labels: flaky-test

#36712 New operator spec: upgrade strategy
  docs/guides/operator/advanced-configuration.adoc
  operator/src/main/java/org/keycloak/operator/ContextUtils.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/CRDUtils.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakSpec.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/UnsupportedSpec.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/UpdateSpec.java
  operator/src/main/java/org/keycloak/operator/upgrade/UpdateStrategy.java
  operator/src/main/java/org/keycloak/operator/upgrade/UpgradeLogic.java
  operator/src/main/java/org/keycloak/operator/upgrade/UpgradeLogicFactory.java
  operator/src/main/java/org/keycloak/operator/upgrade/UpgradeType.java
  operator/src/main/java/org/keycloak/operator/upgrade/impl/AlwaysRecreateUpgradeLogic.java
  operator/src/main/java/org/keycloak/operator/upgrade/impl/BaseUpgradeLogic.java
  operator/src/main/java/org/keycloak/operator/upgrade/impl/RecreateOnImageChangeUpgradeLogic.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/PodTemplateTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/UpgradeTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/CRSerializationTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/CRAssert.java
  operator/src/test/resources/test-serialization-keycloak-cr-invalid-update.yml
  operator/src/test/resources/test-serialization-keycloak-cr.yml
Labels: team/cloud-native, flaky-test

#36689 Avoid using docker hub for pulling images
  quarkus/tests/integration/pom.xml
  testsuite/integration-arquillian/pom.xml
Labels: team/cloud-native, team/core-clients, team/core-iam

#36714 Avoid using docker hub for pulling images
  quarkus/tests/integration/pom.xml
  testsuite/integration-arquillian/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#36835 docs: update JavaDoc for ImportSynchronization
  core/src/main/java/org/keycloak/representations/idm/ComponentTypeRepresentation.java
  model/storage-private/src/main/java/org/keycloak/storage/managers/UserStorageSyncManager.java
  model/storage/src/main/java/org/keycloak/storage/UserStorageProvider.java
  model/storage/src/main/java/org/keycloak/storage/user/ImportSynchronization.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/user/UserSyncTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36778 Add admin event assertions to new test framework
  test-framework/core/src/main/java/org/keycloak/testframework/events/AbstractEvents.java
  test-framework/core/src/main/java/org/keycloak/testframework/events/AdminEventAssertion.java
  test-framework/core/src/main/java/org/keycloak/testframework/events/AdminEvents.java
  test-framework/core/src/main/java/org/keycloak/testframework/events/AdminEventsSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/events/Events.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/RealmConfigBuilder.java
  test-framework/core/src/test/java/org/keycloak/testframework/events/AdminEventAssertionTest.java
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/AdminEventsTest.java
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/EventsTest.java
Labels: flaky-test

#36805 Make hideOnLogin default to true on submit.
  js/apps/admin-ui/src/organizations/LinkIdentityProviderModal.tsx
Labels: team/ui

#36722 Don't require events enabled to view event tabs.
  js/apps/admin-ui/cypress/e2e/clients_test.spec.ts
  js/apps/admin-ui/src/clients/ClientDetails.tsx
  js/apps/admin-ui/src/groups/GroupsSection.tsx
  js/apps/admin-ui/src/realm-roles/RealmRoleTabs.tsx
  js/apps/admin-ui/src/user/EditUser.tsx
Labels: team/ui

#35817 Run base tests in fixed order
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AbstractKeycloakTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36700 Check if fine grained is enabled
  js/apps/admin-ui/src/groups/GroupsModal.tsx
Labels: team/ui

#36772 Add primary key to avoid issues in some mysql 8 server but still keep…
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate25_0_0_MySQL_ConsentConstraints.java
Labels: flaky-test

#36797 Upgrade to Quarkus 3.15.3
  pom.xml
Labels: flaky-test

#36879 Add APIResponse annotations to GroupsResource.addTopLevelGroup
  services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
Labels: flaky-test

#36847 Avoid token issuance after denied consent in the Device Grant flow
  services/src/main/java/org/keycloak/protocol/oidc/grants/device/DeviceGrantType.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuth2DeviceAuthorizationGrantTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36795 Upgrade to Quarkus 3.8.6
  pom.xml
Labels: flaky-test

#36873 Remove duplicate message keys
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#36875 fix: refinements to comparison logic
  operator/src/main/java/org/keycloak/operator/upgrade/impl/BaseUpgradeLogic.java
Labels: team/cloud-native

#36655 fix: allow the keycloak instances to stop gracefully on deletion
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/K8sUtils.java
Labels: team/cloud-native

#36856 Provide an option to force login after reset credentials
  docs/documentation/release_notes/topics/26_1_1.adoc
  docs/documentation/server_admin/images/reset-credential-email-config.png
  docs/documentation/server_admin/topics/login-settings/forgot-password.adoc
  services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/InfoPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/InitialFlowsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#36340 fix: adding a check and documenting import naming conventions
  docs/guides/server/importExport.adoc
  model/storage-services/src/main/java/org/keycloak/exportimport/dir/DirImportProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#36877 fix: remove the transformation of health-enabled false
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HealthPropertyMappers.java
  quarkus/runtime/src/main/resources/application.properties
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
Labels: team/cloud-native, flaky-test

#36891 Provide an option to force login after reset credentials (26.1)
  docs/documentation/release_notes/topics/26_1_1.adoc
  docs/documentation/server_admin/images/reset-credential-email-config.png
  docs/documentation/server_admin/topics/login-settings/forgot-password.adoc
  services/src/main/java/org/keycloak/authentication/authenticators/resetcred/ResetCredentialEmail.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/InfoPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication/InitialFlowsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam
