Repository keycloak/keycloak, pull requests merged in 2025-06, with the labels that each got.

#39993 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ca.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ja.properties
Labels: team/ui, flaky-test

#39786 Cache the client session if it is missing from the cache
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/PersistentUserSessionProvider.java
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/changes/ClientSessionPersistentChangelogBasedTransaction.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40158 Add warning about using exec in custom entrypoint scripts
  docs/guides/server/containers.adoc
Labels: team/cloud-native

#39910 add missing id attributes on button elements
  themes/src/main/resources/theme/keycloak.v2/login/delete-account-confirm.ftl
  themes/src/main/resources/theme/keycloak.v2/login/field.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-update-password.ftl
  themes/src/main/resources/theme/keycloak.v2/login/register.ftl
Labels: team/ui

#40176 Add publishing plugin for Maven Central Repository migration
  .github/mvn-rel-settings.xml
  boms/pom.xml
  misc/theme-verifier/pom.xml
  pom.xml
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#39991 Add re-authentication when updating email via UPDATE_EMAIL feature
  server-spi-private/src/main/java/org/keycloak/authentication/RequiredActionFactory.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateEmail.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionUpdateEmailTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40179 updated the coding guidelines
  js/CODING_GUIDELINES.md
  js/README.md
  js/apps/keycloak-server/README.md
Labels: team/ui

#40205 Avoid unbalanced curly braces in message properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_el.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  misc/theme-verifier/src/main/java/org/keycloak/themeverifier/VerifyMessageProperties.java
  misc/theme-verifier/src/test/java/org/keycloak/themeverifier/VerifyMessagePropertiesTest.java
  misc/theme-verifier/src/test/resources/unbalancedCurlyBracesOneEnd_en.properties
  misc/theme-verifier/src/test/resources/unbalancedCurlyBracesOne_en.properties
  misc/theme-verifier/src/test/resources/unbalancedCurlyBracesTwoStart_en.properties
  misc/theme-verifier/src/test/resources/unbalancedCurlyBracesTwo_en.properties
Labels: team/ui

#40234 Make the checkbox "Sign out from other devices" unchecked by default
  docs/documentation/upgrading/topics/changes/changes-26_3_0.adoc
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionResetPasswordTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionResetPasswordTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionTotpSetupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateEmailTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateEmailTestWithVerificationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/BackwardsCompatibilityUserStorageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RecoveryAuthnCodesAuthenticatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/AppInitiatedActionWebAuthnTest.java
  themes/src/main/resources/theme/base/login/password-commons.ftl
  themes/src/main/resources/theme/keycloak.v2/login/password-commons.ftl
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#40093 fix: ensuring update job handles secrets when none exist in the cr
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakSpec.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
Labels: team/cloud-native

#40257 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
Labels: team/ui

#39951 Adjust capitalization in Catalan translation strings
  themes/src/main/resources-community/theme/base/account/messages/messages_ca.properties
Labels: team/ui

#39556 [OID4VCI] Fix creation of clientScopes with protocol oid4vc
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientScopeResource.java
  services/src/main/java/org/keycloak/services/resources/admin/ClientScopesResource.java
  tests/base/src/test/java/org/keycloak/tests/admin/client/ClientScopeTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#39564 [OID4VCI] Fix order of protocol-type selection in admin-ui
  services/src/main/java/org/keycloak/protocol/oid4vc/OID4VCLoginProtocolFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolFactory.java
  services/src/main/java/org/keycloak/protocol/saml/SamlProtocolFactory.java
  services/src/test/java/org/keycloak/protocol/ProtocolFactoryTest.java
Labels: flaky-test

#39967 removed unused message
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_pl.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_zh_CN.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: status/hold, team/ui

#39986 Revert "better filter and match the tabs that should be rendered dynamic (#38199)"
  js/apps/admin-ui/src/components/routable-tabs/RoutableTabs.tsx
Labels: team/ui

#40130 refactor the keyValue input to have a override component
  js/apps/admin-ui/src/components/dynamic/UserProfileAttributeListComponent.tsx
  js/apps/admin-ui/src/components/key-value-form/KeyValueInput.tsx
  js/apps/admin-ui/src/index.ts
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeAnnotations.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/KeySelect.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/ValueSelect.tsx
Labels: team/ui

#40236 Feed data in export format to the created user
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/PasswordHashingTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40201 Change discovery in Kubernetes to jdbc-ping
  docs/documentation/upgrading/topics/changes/changes-26_3_0.adoc
  docs/guides/server/caching.adoc
  operator/src/main/java/org/keycloak/operator/Constants.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
Labels: team/cloud-native, flaky-test, team/sre

#40276 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ru.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ru.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ru.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ru.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ru.properties
Labels: team/ui

#40204 Remove outdated tests in model/infinispan
  model/infinispan/src/test/java/org/keycloak/cluster/infinispan/TestCacheManagerFactory.java
  model/infinispan/src/test/java/org/keycloak/models/sessions/infinispan/initializer/ClusteredCacheBehaviorTest.java
  model/infinispan/src/test/java/org/keycloak/models/sessions/infinispan/initializer/ConcurrencyLockingTest.java
  model/infinispan/src/test/java/org/keycloak/models/sessions/infinispan/initializer/ConcurrencyVersioningTest.java
  model/infinispan/src/test/java/org/keycloak/models/sessions/infinispan/initializer/L1SerializationIssueTest.java
  model/infinispan/src/test/java/org/keycloak/models/sessions/infinispan/initializer/OutdatedTopologyExceptionReproducerTest.java
Labels: team/sre

#40224 Sequential transactions instead of nested transactions
  services/src/main/java/org/keycloak/credential/PasswordCredentialProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/PasswordHashingTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40244 Throw a ProviderConfigPropertyNameNotUniqueException in case of a duplicate ProviderConfigProperty.
  server-spi/src/main/java/org/keycloak/provider/ProviderConfigPropertyNameNotUniqueException.java
  server-spi/src/main/java/org/keycloak/provider/ProviderConfigurationBuilder.java
  server-spi/src/test/java/org/keycloak/provider/ProviderConfigurationBuilderTest.java
Labels: flaky-test

#40306 fix: avoid double-submission in password change and recovery code screens
  themes/src/main/resources/theme/base/login/login-recovery-authn-code-input.ftl
  themes/src/main/resources/theme/base/login/login-update-password.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-recovery-authn-code-input.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-update-password.ftl
Labels: team/ui

#40260 fix: adding docs about Keycloak CR security
  docs/guides/operator/basic-deployment.adoc
Labels: team/cloud-native

#40317 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ru.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_fr.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ru.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_fr.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ru.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ru.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_ru.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ru.properties
Labels: team/ui

#40322 fix: adding docs about Keycloak CR security (#40260)
  docs/guides/operator/basic-deployment.adoc
Labels: team/cloud-native

#40313 Rename "Browser - Conditional OTP" to "Browser - Conditional 2FA" in default browser flow
  js/apps/admin-ui/test/autentication/flows.spec.ts
  server-spi-private/src/main/java/org/keycloak/models/utils/DefaultAuthenticationFlows.java
  tests/base/src/test/java/org/keycloak/tests/admin/authentication/InitialFlowsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/custom/CustomAuthFlowOTPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionTotpSetupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionTotpSetupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPReadOnlyTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/login/ConditionalSubFlowExecutedAuthenticatorTest.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#39620 The spans created should be made current and then later closed
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/KeycloakTracingCustomizer.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/tracing/OTelTracingProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40319 Added WebAuthn and recovery codes as disabled in the First Broker Login Flow
  server-spi-private/src/main/java/org/keycloak/models/utils/DefaultAuthenticationFlows.java
  tests/base/src/test/java/org/keycloak/tests/admin/authentication/InitialFlowsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
Labels: status/ready, team/cloud-native, team/core-clients, team/core-iam

#40344 Keycloak fails to start on MySQL Cluster due to missing primary key i…
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/conn/CustomChangeLogHistoryService.java
Labels: flaky-test

#40349 fix: switching to the registry addon for olm testing (#40334)
  .github/workflows/operator-ci.yml
  operator/scripts/create-olm-test-catalog.sh
  operator/scripts/olm-testing.sh
Labels: team/cloud-native

#40352 Remove authentication session during logout if no valid user session is found
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40410 Set window size instead of maximize because it fails in chrome 137
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/account/AbstractWebAuthnAccountTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40404 [26.2] MigrationModel duplicate entry
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate26_2_6_RemoveDuplicateMigrationModelVersion.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-26.2.6.xml
  model/jpa/src/main/resources/META-INF/jpa-changelog-master.xml
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/MigrationDeniedTest.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/MigrationModelTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40414 Create a transient client session if the RPT is originating from a client session that does not exist in the user session
  services/src/main/java/org/keycloak/authorization/authorization/AuthorizationTokenService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/EntitlementAPITest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40433 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_pt_BR.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ca.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_pt_BR.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_pt_BR.properties
Labels: team/ui

#40437 Add tests for webauthn configuration AvoidSameAuthenticatorRegister
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/account/AbstractWebAuthnAccountTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/account/WebAuthnSigningInTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#38657 Implemented validation to ensure each OTP device has a unique label
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserCredentialStore.java
  model/jpa/src/main/java/org/keycloak/storage/jpa/JpaUserFederatedStorageProvider.java
  server-spi/src/main/java/org/keycloak/credential/CredentialModel.java
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateTotp.java
  services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionTotpSetupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/FederatedStorageExportImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/CredentialModelTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/account/AbstractWebAuthnAccountTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/account/WebAuthnSigningInTest.java
  themes/src/main/resources/theme/keycloak.v2/login/login-config-totp.ftl
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#40452 Remove duplicate definition of WebAuthnErrorPage in AbstractWebAuthnAccountTest
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/account/AbstractWebAuthnAccountTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40425 Highlight all types of features in the admin console
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/dashboard/Dashboard.tsx
Labels: team/ui

#40005 fix: adding a -- separator for spi options
  core/src/main/java/org/keycloak/Config.java
  docs/documentation/server_admin/topics/authentication/password-policies.adoc
  docs/documentation/server_admin/topics/events/admin.adoc
  docs/documentation/server_admin/topics/events/login.adoc
  docs/documentation/server_admin/topics/roles-groups/proc-managing-groups.adoc
  docs/documentation/server_admin/topics/sessions/offline.adoc
  docs/documentation/server_admin/topics/sso-protocols/con-oidc-auth-flows.adoc
  docs/documentation/server_admin/topics/sso-protocols/oidc.adoc
  docs/documentation/server_admin/topics/threat/auth-sessions-limit.adoc
  docs/documentation/server_admin/topics/threat/read-only-attributes.adoc
  docs/documentation/server_admin/topics/vault.adoc
  docs/documentation/server_development/topics/providers.adoc
  docs/documentation/server_development/topics/themes.adoc
  docs/documentation/server_development/topics/user-storage/simple-example.adoc
  docs/documentation/upgrading/topics/changes/changes-26_3_0.adoc
  docs/documentation/upgrading/topics/migrate_db.adoc
  docs/guides/observability/metrics-for-troubleshooting-keycloak.adoc
  docs/guides/operator/advanced-configuration.adoc
  docs/guides/server/configuration-provider.adoc
  docs/guides/server/configuration.adoc
  docs/guides/server/db.adoc
  docs/guides/server/fips.adoc
  docs/guides/server/outgoinghttp.adoc
  docs/guides/server/reverseproxy.adoc
  docs/guides/templates/options.adoc
  docs/guides/ui-customization/themes.adoc
  docs/guides/ui-customization/welcome-theme.adoc
  docs/maven-plugin/src/main/java/org/keycloak/guides/maven/Options.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/Configuration.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/MicroProfileConfigProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/CachingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/EventPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ExportPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnameV2PropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ImportPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/MetricsPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TruststorePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/VaultPropertyMappers.java
  quarkus/runtime/src/main/resources/application.properties
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/ConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappersTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/OptionsDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartCommandDistTest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/SpiProvidersSwitchingUtils.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#40117 support setting periodSeconds and failureThreashold in the Keyclock CR
  docs/guides/operator/advanced-configuration.adoc
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakSpec.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/ProbeSpec.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/CRSerializationTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
  operator/src/test/resources/test-serialization-keycloak-cr.yml
Labels: team/cloud-native, flaky-test

#40283 Add clustering tests to new test framework
  .github/workflows/ci.yml
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/DockerKeycloakDistribution.java
  quarkus/tests/junit5/src/main/java/org/keycloak/it/utils/Maven.java
  test-framework/bom/pom.xml
  test-framework/clustering/pom.xml
  test-framework/clustering/src/main/java/org/keycloak/testframework/ClusteringTestFrameworkExtension.java
  test-framework/clustering/src/main/java/org/keycloak/testframework/annotations/InjectLoadBalancer.java
  test-framework/clustering/src/main/java/org/keycloak/testframework/clustering/LoadBalancer.java
  test-framework/clustering/src/main/java/org/keycloak/testframework/clustering/LoadBalancerSupplier.java
  test-framework/clustering/src/main/java/org/keycloak/testframework/server/ClusteredKeycloakServer.java
  test-framework/clustering/src/main/java/org/keycloak/testframework/server/ClusteredKeycloakServerSupplier.java
  test-framework/clustering/src/main/resources/META-INF/services/org.keycloak.testframework.TestFrameworkExtension
  test-framework/core/src/main/java/org/keycloak/testframework/database/AbstractContainerTestDatabase.java
  test-framework/core/src/main/java/org/keycloak/testframework/database/AbstractDatabaseSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/AbstractKeycloakServerSupplier.java
  test-framework/pom.xml
  tests/clustering/README.md
  tests/clustering/pom.xml
  tests/clustering/src/test/java/org/keycloak/tests/compatibility/MixedVersionClusterTest.java
  tests/clustering/src/test/resources/keycloak-test.properties
  tests/pom.xml
Labels: team/cloud-native, flaky-test

#40471 fix(i18n): add missing comma before 'a' in Polish password reset message
  themes/src/main/resources-community/theme/base/login/messages/messages_pl.properties
Labels: team/ui

#40459 39429/OfflineSessionPersistenceTest testPersistenceMultipleNodesClientSessionsAtRandomNode
  docs/documentation/upgrading/topics/changes/changes-26_3_0.adoc
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/CacheConfigurator.java
Labels: flaky-test, team/sre

#40455 fix: removing lifecylce in initContainers
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java
Labels: team/cloud-native, flaky-test

#40495 Load new locale before showing the alert
  js/apps/account-ui/src/personal-info/PersonalInfo.tsx
Labels: team/ui

#40473 kyrgyz language support
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ky.properties
  js/apps/account-ui/test/personal-info/user-profile.json
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ky.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ky.properties
  themes/src/main/resources-community/theme/base/account/theme.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ky.properties
  themes/src/main/resources-community/theme/base/admin/theme.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_ky.properties
  themes/src/main/resources-community/theme/base/email/theme.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ky.properties
  themes/src/main/resources-community/theme/base/login/theme.properties
Labels: team/ui

#40435 Add `briefRepresentation` to get organizations from user
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationMemberResource.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationMembersResource.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationsMembersResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationMemberResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationsResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/member/OrganizationMemberTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/member/OrganizationMemberWithLdapTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40449 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ka.properties
Labels: team/ui

#40534 Clarify FIPS instructions
  docs/guides/server/fips.adoc
Labels: team/cloud-native

#39925 add labels and annotations to service (httpSpec)
  docs/guides/operator/advanced-configuration.adoc
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakServiceDependentResource.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/HttpSpec.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakServicesTest.java
Labels: team/cloud-native

#40522 Upgrade webauth4j to current release 0.29.3
  pom.xml
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnPasswordlessRegister.java
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnPasswordlessRegisterFactory.java
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnRegister.java
  services/src/main/java/org/keycloak/authentication/requiredactions/WebAuthnRegisterFactory.java
  services/src/main/java/org/keycloak/credential/WebAuthnCredentialProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/AttestationConveyanceRegisterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/registration/PubKeySignRegisterTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40544 Use computer language for createTimeout integer value
  themes/src/main/resources/theme/base/login/login-passkeys-conditional-authenticate.ftl
  themes/src/main/resources/theme/base/login/passkeys.ftl
  themes/src/main/resources/theme/base/login/webauthn-authenticate.ftl
  themes/src/main/resources/theme/base/login/webauthn-register.ftl
  themes/src/main/resources/theme/keycloak.v2/login/webauthn-authenticate.ftl
  themes/src/main/resources/theme/keycloak.v2/login/webauthn-register.ftl
Labels: team/ui

#40560 Mark user as disabled if reaching max login failures and permanent lockout is enabled
  core/src/main/java/org/keycloak/representations/idm/AbstractUserRepresentation.java
  core/src/main/java/org/keycloak/representations/idm/UserRepresentation.java
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
  server-spi-private/src/main/java/org/keycloak/userprofile/DefaultUserProfile.java
  services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40565 docs(caching): clarified wording for the jgroups fd port offset
  docs/guides/server/caching.adoc
Labels: team/cloud-native

#40567 chore(i18n): Sync Polish translation with English
  themes/src/main/resources-community/theme/base/login/messages/messages_pl.properties
Labels: team/ui

#40490 Preserve query parameters when redirecting requests
  services/src/main/java/org/keycloak/services/resources/ThemeResource.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/theme/ThemeResourceProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#40458 Additional Quarkus devtools dependencies in distribution
  quarkus/deployment/pom.xml
  quarkus/dist/check-dev-dependencies.sh
  quarkus/dist/pom.xml
Labels: team/cloud-native

#40610 [26.2.x] Additional Quarkus devtools dependencies in distribution
  quarkus/deployment/pom.xml
  quarkus/dist/check-dev-dependencies.sh
  quarkus/dist/pom.xml
Labels: team/cloud-native

#40615 Use offline time calculations when transient created from offline
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40624 Use offline time calculations when transient created from offline
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40671 Fix and enable account-ui tests
  .github/workflows/js-ci.yml
  js/apps/account-ui/test/account-security/linked-accounts.spec.ts
  js/apps/account-ui/test/applications.spec.ts
  js/apps/account-ui/test/personal-info/personal-info.spec.ts
  js/apps/account-ui/test/referrer.spec.ts
  themes/src/main/resources/theme/base/account/messages/messages_en.properties
Labels: team/ui

#40530 Use updated PostgresDatabase from Liquibase 4.32.0
  model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/UpdatedPostgresDatabase.java
  model/jpa/src/main/resources/META-INF/services/liquibase.database.Database
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
Labels: status/hold, team/cloud-native, flaky-test

#40674 Deprecate the original Passkeys Conditional UI Authenticator
  docs/documentation/release_notes/topics/26_3_0.adoc
  services/src/main/java/org/keycloak/authentication/authenticators/browser/PasskeysConditionalUIAuthenticator.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/PasskeysConditionalUIAuthenticatorFactory.java
Labels: flaky-test

#40450 shows what patching logic should look like
  core/src/main/java/org/keycloak/representations/admin/v2/BaseRepresentation.java
  core/src/main/java/org/keycloak/representations/admin/v2/ClientRepresentation.java
  rest/admin-api/src/main/java/org/keycloak/admin/api/FieldValidation.java
  rest/admin-api/src/main/java/org/keycloak/admin/api/client/ClientApi.java
  rest/admin-api/src/main/java/org/keycloak/admin/api/client/ClientsApi.java
  rest/admin-api/src/main/java/org/keycloak/admin/api/client/DefaultClientApi.java
  rest/admin-api/src/main/java/org/keycloak/admin/api/client/DefaultClientsApi.java
  server-spi-private/src/main/java/org/keycloak/models/mapper/ClientModelMapper.java
  server-spi/src/main/java/org/keycloak/services/client/ClientService.java
  services/src/main/java/org/keycloak/models/mapper/MapStructClientModelMapper.java
  services/src/main/java/org/keycloak/services/client/DefaultClientService.java
Labels: team/admin-api-wg

#36943 Forward LOGIN_HINT of authentication session with identity-provider-r…
  services/src/main/java/org/keycloak/authentication/authenticators/browser/IdentityProviderAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractDefaultIdpTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcDefaultIdpTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#40719 Allow passkeys login when user has no password credential
  services/src/main/java/org/keycloak/authentication/authenticators/browser/PasswordForm.java
  services/src/main/java/org/keycloak/authentication/authenticators/browser/UsernamePasswordForm.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/passwordless/PasskeysUsernameFormTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#40698 Resolve resources with same URI if the permission request is based on URI matching
  services/src/main/java/org/keycloak/authorization/authorization/AuthorizationTokenService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/EntitlementAPITest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#40723 fix: refinements for ipv6 only testing
  .github/actions/update-hosts/nipio-hosts
  testsuite/integration-arquillian/tests/base/pom.xml
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/SessionRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/AttributeTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
Labels: team/cloud-native, team/core-clients, team/core-iam

#40599 Set a unique fragment key to please React
  js/apps/account-ui/src/account-security/SigningIn.tsx
Labels: team/ui

#40732 Make rolling-updates-v2 preview feature
  common/src/main/java/org/keycloak/common/Profile.java
  docs/documentation/release_notes/topics/26_3_0.adoc
  docs/guides/server/update-compatibility.adoc
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FeaturesDistTest.java
Labels: team/cloud-native, flaky-test

#40743 Windows fixes for 26.0 branch (26.0)
  .github/actions/maven-cache/action.yml
  .github/workflows/ci.yml
Labels: flaky-test

#40724 Fixing how translatable fields are set and ignoring formatting for root user attributes
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AddTranslationsDialog.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/attribute/TranslatableField.tsx
Labels: team/ui

#40769 fix: switching to the registry addon for olm testing (#40334) (#40349)
  .github/workflows/operator-ci.yml
  operator/scripts/create-olm-test-catalog.sh
  operator/scripts/olm-testing.sh
Labels: team/cloud-native

#40766 make abstract class AbstractUserRoleMappingMapper public
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractUserRoleMappingMapper.java
Labels: flaky-test

#40771 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_de.properties
Labels: team/ui

#40757 Use POST binding for logout when REDIRECT url is not set and forced POST
  services/src/main/java/org/keycloak/protocol/saml/SamlProtocol.java
  services/src/test/java/org/keycloak/protocol/saml/SamlProtocolTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/saml/LogoutTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam
