Repository keycloak/keycloak, pull requests merged in 2025-03, with the labels that each got.

#37663 Move verify and parse tokens to AbstractOAuthClient
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/OAuthClientTest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/JwksRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/JwksResponse.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/KeyManager.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/TokensManager.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/SignatureSignerUtil.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AbstractClientAuthSignedJWTTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37632 [Test framework] AuthzCleanupTest
  tests/base/src/test/java/org/keycloak/tests/admin/AuthzCleanupTest.java
  tests/base/src/test/resources/org/keycloak/tests/admin/authz/acme-resource-server-cleanup-test.json
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AuthzCleanupTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, area/test-framework

#37712 Upgrade to Infinispan 15.0.14
  pom.xml
Labels: flaky-test

#35230 [Test framework MVP] SMTPConnectionTest + SMTPConnectionVaultTest
  test-framework/email-server/src/main/java/org/keycloak/testframework/mail/MailServer.java
  tests/base/src/test/java/org/keycloak/tests/admin/SMTPConnectionTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/SMTPConnectionVaultTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/partialexport/PartialExportTest.java
  tests/base/src/test/resources/org/keycloak/tests/admin/partialexport/partialexport-testrealm.json
  tests/base/src/test/resources/org/keycloak/tests/admin/vault/default_smtp__password
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/SMTPConnectionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/SMTPConnectionVaultTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, area/test-framework

#37724 Move DeclarativeUserTest.java to the new testsuite
  test-framework/core/src/main/java/org/keycloak/testframework/realm/RealmConfigBuilder.java
  tests/base/src/test/java/org/keycloak/tests/admin/DeclarativeUserTest.java
  tests/utils-shared/pom.xml
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/userprofile/UserProfileUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/AccountRestServiceWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/account/custom/CustomAuthFlowOTPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateProfileWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/adapter/AbstractAdapterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/group/GroupTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcFirstBrokerLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/exportimport/ExportImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPAccountRestApiTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPAdminRestApiTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPBinaryAttributesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/noimport/LDAPProvidersIntegrationNoImportTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ConditionalUserAttributeAuthenticatorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterWithUserProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/VerifyProfileTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OIDCProtocolMappersTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam, area/test-framework

#37707 Create transient session for TE if requester client session is missing
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProvider.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/util/UserSessionUtil.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/updaters/ClientAttributeUpdater.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37779 Remove doClientCredentialsGrantAccessTokenRequest(String clientSecret)
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/ServiceAccountClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/SAMLClientRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesConditionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExtendedEventTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ServiceAccountTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/hok/HoKTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/IdTokenEncryptionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37664 Allow a token to be revoked twice
  model/jpa/src/main/java/org/keycloak/models/jpa/session/JpaRevokedTokensPersisterProvider.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/singleUseObject/SingleUseObjectModelTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37706 Enable the TLS based JGroups encryption by default and update the docs
  .github/workflows/ci.yml
  docs/documentation/release_notes/topics/26_2_0.adoc
  docs/documentation/tests/src/test/resources/ignored-links
  docs/documentation/upgrading/topics/changes/changes-26_2_0.adoc
  docs/guides/server/caching.adoc
  model/infinispan/src/main/java/org/keycloak/infinispan/module/certificates/JGroupsCertificateHolder.java
  quarkus/config-api/src/main/java/org/keycloak/config/CachingOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/CachingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/jgroups/impl/JpaJGroupsTlsConfigurator.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/CacheEmbeddedMtlsDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartDevHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testStartOptimizedHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityMetadataHelpAll.approved.txt
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusConfiguration.java
  testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml
Labels: team/cloud-native, team/core-clients, team/core-iam

#37783 Remove doRefreshTokenRequest(., String clientSecret)
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/ConsentsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/concurrency/ConcurrentLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/realm/RealmTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/EntitlementAPITest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTransientSessionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/CIBATest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OIDCPairwiseClientRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExtendedEventTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/composites/CompositeRoleTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/crossdc/LastSessionRefreshCrossDCTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/crossdc/SessionExpirationCrossDCTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/crossdc/SessionsPreloadCrossDCTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/ClientStorageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/UserStorageFailureTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/CustomFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/TransientSessionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/keys/KeyRotationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/migration/AbstractMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/DPoPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuth2OnlyTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthDanceClientSessionExtensionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthProofKeyForCodeExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenMigrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ResourceOwnerPasswordCredentialsGrantTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ServiceAccountTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenEndpointCorsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenIntrospectionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/hok/HoKTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/par/ParTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCScopeTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37764 Remove ForceRecreate Operation
  docs/guides/operator/advanced-configuration.adoc
  operator/pom.xml
  operator/src/main/java/org/keycloak/operator/upgrade/UpdateStrategy.java
  operator/src/main/java/org/keycloak/operator/upgrade/UpgradeLogicFactory.java
  operator/src/main/java/org/keycloak/operator/upgrade/impl/ForceRecreateUpgradeLogic.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/UpgradeTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/CRSerializationTest.java
  operator/src/test/resources/test-serialization-keycloak-cr.yml
Labels: team/cloud-native

#37735 Polishing of token-exchange features. Remove TOKEN_EXCHANGE_FEDERATED…
  common/src/main/java/org/keycloak/common/Profile.java
  server-spi-private/src/main/java/org/keycloak/protocol/oidc/TokenExchangeContext.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/TokenExchangeGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/TokenExchangeGrantTypeFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/FederatedTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/FederatedTokenExchangeProviderFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProviderFactory.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/SubjectImpersonationTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/SubjectImpersonationTokenExchangeProviderFactory.java
  services/src/main/resources/META-INF/services/org.keycloak.protocol.oidc.TokenExchangeProviderFactory
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeV1WithStandardTEV2EnabledTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2WithLegacyTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/SubjectImpersonationTokenExchangeV1WithStandardV2EnabledTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37812 Allow a token to be revoked twice
  model/jpa/src/main/java/org/keycloak/models/jpa/session/JpaRevokedTokensPersisterProvider.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/singleUseObject/SingleUseObjectModelTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37813 Allow a token to be revoked twice
  model/jpa/src/main/java/org/keycloak/models/jpa/session/JpaRevokedTokensPersisterProvider.java
  testsuite/model/src/test/java/org/keycloak/testsuite/model/singleUseObject/SingleUseObjectModelTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37805 Improve events handling for TE
  server-spi-private/src/main/java/org/keycloak/events/Details.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ClientCredentialsGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/AbstractTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProvider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ServiceAccountTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/resources/token-exchange/testrealm-token-exchange-v2.json
Labels: team/cloud-native, team/core-clients, team/core-iam

#37830 Move doWellKnownRequest to AbstractOAuthClient
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/OAuthClientTest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/Endpoints.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/OpenIDProviderConfigurationRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/OpenIDProviderConfigurationResponse.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/ssl/TLSTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37852 [Operator] Make UpgradeTest stable
  operator/src/main/java/org/keycloak/operator/Constants.java
  operator/src/main/java/org/keycloak/operator/ContextUtils.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/CRDUtils.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakStatusAggregator.java
  operator/src/main/java/org/keycloak/operator/upgrade/impl/BaseUpgradeLogic.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/UpgradeTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/CRAssert.java
Labels: team/cloud-native, flaky-test

#37859 Move token introspection to AbstractOAuthClient
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/OAuthClientTest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractHttpResponse.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/IntrospectionRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/IntrospectionResponse.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UmaGrantTypeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTransientSessionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/CIBATest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1PublicClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OIDCPairwiseClientRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/keys/KeyRotationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/DPoPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OfflineTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ServiceAccountTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenIntrospectionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenRevocationCorsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenRevocationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/hok/HoKTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/AbstractSubjectImpersonationTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/NonceBackwardsCompatibleMapperTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#35899 Add Role resource type and its scopes to authorization schema
  server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissionsV2.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissionEvaluator.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissionsV2.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/RoleResourceTypeEvaluationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37868 Remove doTokenRevoke with tokenTypeHint and clientSecret parameters
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/TokenRevocationRequest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/CIBATest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/ClientRegistrationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1PublicClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/DPoPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ServiceAccountTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenRevocationCorsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenRevocationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37851 Upgrade to Quarkus 3.19.2
  operator/pom.xml
  pom.xml
  services/pom.xml
Labels: team/cloud-native, flaky-test

#37866 Remove doSocialLogin and findSocial from OAuthClient
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerNonceParameterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTransientSessionsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/OidcClaimToUserSessionNoteMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/BackchannelLogoutTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37873 Remove doRefreshTokenRequest(refreshToken, clientSecret) from OAuthClient
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37845 fix: Admin events: resource type filter does not work
  js/apps/admin-ui/src/events/AdminEvents.tsx
Labels: team/ui

#37888 Make JGroups with TLS startup more robust
  model/infinispan/src/main/java/org/keycloak/infinispan/module/certificates/CertificateReloadManager.java
  model/jpa/src/main/java/org/keycloak/storage/configuration/jpa/JpaServerConfigStorageProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/jgroups/impl/JpaJGroupsTlsConfigurator.java
Labels: team/cloud-native

#37841 Add Pairwise Subject Identifier Mapper to Logout tokens
  services/src/main/java/org/keycloak/jose/jws/DefaultTokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractPairwiseSubMapper.java
  services/src/main/java/org/keycloak/protocol/oidc/mappers/LogoutTokenMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37903 Refactor and move CIBA requests to AbstractOAuthClient
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/ciba/AuthenticationRequestAcknowledgement.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/ciba/BackchannelAuthenticationRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/ciba/BackchannelAuthenticationTokenRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/ciba/CibaClient.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/CIBATest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPICIBATest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37909 Refactor and move device requests to AbstractOAuthClient
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/device/DeviceAuthorizationRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/device/DeviceAuthorizationResponse.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/device/DeviceClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/device/DeviceTokenRequest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExtendedEventTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuth2DeviceAuthorizationGrantTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37905 Include JNA dependency for the SSSD in the keycloak server
  federation/sssd/src/main/java/org/keycloak/federation/sssd/impl/PAMAuthenticator.java
  quarkus/runtime/pom.xml
Labels: team/cloud-native

#37921 When testing/evaluating permissions UMA resources are not resolved properly
  services/src/main/java/org/keycloak/authorization/admin/PolicyEvaluationService.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UmaRepresentationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37837 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_it.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_it.properties
Labels: team/ui, flaky-test

#37914 Refactor and move PAR requests to AbstractOAuthClient
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractHttpPostRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/ParRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/ParResponse.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPI2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExecutorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RestartCookieTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/par/ParTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/par/ParWithDPoPTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37942 Backport: fix: Admin events: resource type filter does not work
  js/apps/admin-ui/src/events/AdminEvents.tsx
Labels: team/ui

#37932 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ca.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_it.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_nl.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ca.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_sl.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_nl.properties
Labels: team/ui

#37654 Migrate UserTests to the new framework
  tests/base/src/test/java/org/keycloak/tests/admin/FineGrainedPermissionsUsersTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/UsersTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UsersTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam, area/test-framework

#37960 Make OAuthClient kcAction, uiLocales, maxAge, and prompt fields parameters on login
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractUrlBuilder.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/LoginUrlBuilder.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/LogoutUrlBuilder.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/ParRequest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionDeleteCredentialTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AppInitiatedActionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionPriorityTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LevelOfAssuranceFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultipleTabsLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ReAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/EmailTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/LoginPageTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenEndpointCorsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/rar/AbstractRARParserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/IdTokenEncryptionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCAdvancedRequestParamsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCBackwardsCompatibilityTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCScopeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/authentication/OrganizationAuthenticationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/sessionlimits/UserSessionLimitsTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37788 Make NetworkPolicy supported and enabled by default
  docs/documentation/release_notes/topics/26_2_0.adoc
  docs/documentation/upgrading/topics/changes/changes-26_2_0.adoc
  docs/guides/operator/advanced-configuration.adoc
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/NetworkPolicySpec.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/NetworkPolicyLogicTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/K8sUtils.java
Labels: team/cloud-native, flaky-test

#37965 fix failing user test
  js/apps/admin-ui/cypress/support/pages/admin-ui/manage/users/UserGroupsPage.ts
Labels: team/ui

#37923 Refactor token exchange methods and move to AbstractOAuthClient
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/TokenExchangeRequest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/FineGrainAdminUnitTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/ClientTokenExchangeSAML2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37948 Fixing incorrectly cached role after update/rename
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RoleAdapter.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/RoleByIdResourceTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37496 A script to prepare commits for test migration
  tests/migration-util/commit-migration.sh
Labels: flaky-test, area/test-framework

#36931 Add APIResponse annotations to User resources
  services/src/main/java/org/keycloak/services/resources/admin/UserProfileResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
Labels: flaky-test

#37427 Avoid NPE in WebAuthnAuthenticator on unknown user
  services/src/main/java/org/keycloak/authentication/authenticators/browser/WebAuthnAuthenticator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/WebAuthnRegisterAndLoginTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37915 Auto-redirect when email from profile matches organization broker
  services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java
  services/src/main/java/org/keycloak/organization/utils/Organizations.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/admin/AbstractOrganizationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/broker/AbstractBrokerSelfRegistrationTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37820 Support revocation for standard token exchange
  server-spi-private/src/main/java/org/keycloak/events/Details.java
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenRevocationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/AbstractTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2WithLegacyTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/resources/token-exchange/testrealm-token-exchange-v2.json
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#37978 Make state and nonce passed on requests in AbstractOAuthClient
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/LoginUrlBuilder.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/ParRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/device/DeviceAuthorizationRequest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/concurrency/ConcurrentLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractBaseBrokerTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerNonceParameterTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/AbstractFAPITest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPI1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPI2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1ConfidentialClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1PublicClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesConditionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExecutorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/kerberos/AbstractKerberosTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultipleTabsLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RestartCookieTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AuthorizationCodeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuth2OnlyTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthRedirectUriStateTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RefreshTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/hok/HoKTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/par/ParTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AuthorizationTokenEncryptionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AuthorizationTokenResponseModeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/NonceBackwardsCompatibleMapperTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCAdvancedRequestParamsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/flows/AbstractOIDCResponseTypeTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37910 [Test framework] AdminEventAuthDetailsTest migration
  tests/base/src/test/java/org/keycloak/tests/admin/event/AdminEventAuthDetailsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/event/AdminEventAuthDetailsTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, area/test-framework

#37997 fix for issue 37136
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#37875 Avoid creating user sessions from the token exchange
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/advanced/OpenIdConnectCompatibilityModes.tsx
  js/libs/ui-shared/src/controls/select-control/SingleSelectControl.tsx
  services/src/main/java/org/keycloak/protocol/oidc/OIDCAdvancedConfigWrapper.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#37996 Make dpopJkt and dpopProof arguments on requests in OAuthClient
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractHttpPostRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AccessTokenRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/ClientCredentialsGrantRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/LoginUrlBuilder.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/ParRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/PasswordGrantRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/RefreshRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/TokenRevocationRequest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1ConfidentialClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1PublicClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/DPoPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/par/ParWithDPoPTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#37670 messages cs+sk
  themes/src/main/resources-community/theme/base/email/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_sk.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_cs.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_sk.properties
Labels: team/ui

#38002 Make PKCE arguments on requests in OAuthClient
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AccessTokenRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/LoginUrlBuilder.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/ParRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/PkceGenerator.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/device/DeviceAuthorizationRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/device/DeviceTokenRequest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/AbstractFAPITest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPI1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPI2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1ConfidentialClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1PublicClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LoginStatusIframeEndpointTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuth2DeviceAuthorizationGrantTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthProofKeyForCodeExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/LightWeightAccessTokenTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/PkceGenerator.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#37971 fix: ensure the https truststore type transforms correctly
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
Labels: team/cloud-native

#38007 Make claims parameter on login request in OAuthClient
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractUrlBuilder.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/LoginUrlBuilder.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/ParRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/ciba/BackchannelAuthenticationRequest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LevelOfAssuranceFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AcrAuthFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AuthenticationMethodReferenceTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38005 removed fallback to attribute name on placeholder
  js/libs/ui-shared/src/user-profile/TextComponent.tsx
Labels: team/ui

#37849 improved the style of the code editor and wrapped it
  js/apps/admin-ui/src/clients/authorization/policy/JavaScript.tsx
  js/apps/admin-ui/src/components/dynamic/ScriptComponent.tsx
  js/apps/admin-ui/src/components/form/CodeEditor.tsx
  js/apps/admin-ui/src/components/json-file-upload/FileUploadForm.tsx
  js/apps/admin-ui/src/events/AdminEvents.tsx
  js/apps/admin-ui/src/realm-settings/PoliciesTab.tsx
  js/apps/admin-ui/src/realm-settings/ProfilesTab.tsx
  js/apps/admin-ui/src/realm-settings/user-profile/JsonEditorTab.tsx
Labels: team/ui

#37831 added default option to locale select to use browser locale
  js/apps/admin-ui/src/user/CreateUser.tsx
  js/libs/ui-shared/src/user-profile/LocaleSelector.tsx
Labels: team/ui

#37828 removed automatic refresh and added refresh to empty state
  js/apps/admin-ui/src/events/AdminEvents.tsx
  js/apps/admin-ui/src/events/UserEvents.tsx
Labels: team/ui

#37808 optimize the look and feel of the realm selector
  js/apps/admin-ui/src/components/realm-selector/RealmSelector.tsx
  js/apps/admin-ui/src/components/realm-selector/realm-selector.css
Labels: team/ui

#38003 removed duplicate initial values
  js/apps/admin-ui/src/authentication/policies/OtpPolicy.tsx
Labels: team/ui

#38022 fix: ensure the https truststore type transforms correctly (#37971)
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HttpPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
Labels: team/cloud-native

#37984 Remove permissions and resources when their corresponding objects are…
  server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java
  server-spi-private/src/main/java/org/keycloak/authorization/store/AuthorizationStoreFactory.java
  server-spi-private/src/main/java/org/keycloak/authorization/store/syncronization/ClientApplicationSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/authorization/store/syncronization/GroupSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/authorization/store/syncronization/RoleSynchronizer.java
  server-spi-private/src/main/java/org/keycloak/authorization/store/syncronization/UserSynchronizer.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/ClientSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/UserSupplier.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/AbstractPermissionTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/ClientResourceTypePermissionTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/GroupResourceTypeEvaluationTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/GroupResourceTypePermissionTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/RoleResourceTypePermissionTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypeEvaluationTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypePermissionTest.java
Labels: flaky-test

#37987 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_it.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ca.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_it.properties
Labels: team/ui, flaky-test

#38018 Make request and requestUri parameters on requests and not fields on OAuthClient
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/LoginUrlBuilder.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/ParRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/ciba/BackchannelAuthenticationRequest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/AbstractFAPITest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/CIBATest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPI1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/FAPI2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExecutorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RestartCookieTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/par/ParTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/par/ParWithDPoPTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/OIDCAdvancedRequestParamsTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37969 Fixing incorrectly cached role after update/rename
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RoleAdapter.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/RoleByIdResourceTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38033 Remove clientSessionState and clientSessionHost fields on OAuthClient
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AccessTokenRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/PasswordGrantRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/RefreshRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/TokenExchangeRequest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RPInitiatedFrontChannelLogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutCorsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/LogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/OAuthDanceClientSessionExtensionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RPInitiatedLogoutTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenIntrospectionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenRevocationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/hok/HoKTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/UserInfoTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#37685 Accept deprecated Hibernate datasource settings property
  quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakRecorder.java
Labels: team/cloud-native

#37465 fix: adding a check if the proxy is trusted prior to using a cert header
  docs/documentation/upgrading/topics/changes/changes-26_2_0.adoc
  docs/guides/server/reverseproxy.adoc
  quarkus/config-api/src/main/java/org/keycloak/config/ProxyOptions.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ProxyPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/QuarkusHttpRequest.java
  quarkus/tests/integration/src/test-providers/java/org/keycloak/it/resource/realm/TestRealmResource.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ProxyHostnameV2DistTest.java
  server-spi/src/main/java/org/keycloak/http/HttpRequest.java
  services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java
  services/src/main/java/org/keycloak/services/x509/AbstractClientCertificateFromHttpHeadersLookup.java
  services/src/main/java/org/keycloak/services/x509/NginxProxySslClientCertificateLookup.java
  services/src/test/java/org/keycloak/services/resteasy/HttpRequestImpl.java
Labels: team/cloud-native, flaky-test

#38040 changed default value so first one is selected by default
  js/apps/admin-ui/src/clients/advanced/FineGrainOpenIdConnect.tsx
Labels: team/ui

#37787 added support fo the favicon
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/themes/ThemeColors.tsx
  js/apps/admin-ui/src/realm-settings/themes/ThemesTab.tsx
Labels: team/ui

#38032 Remove custom parameters on OAuthClient
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractHttpPostRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/LoginUrlBuilder.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/PasswordGrantRequest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/RegisterPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/AuthzEndpointRequestParserTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExecutorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/CustomFlowTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/TransientSessionTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38045 Final wrap-up of refactoring OAuthClient
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractHttpGetRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractHttpPostRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AbstractOAuthClient.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AccessTokenRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/AuthorizationEndpointResponse.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/OpenIDProviderConfigurationRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/PasswordGrantRequest.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/TokensManager.java
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/UserInfoRequest.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/AuthenticationRequestAcknowledgement.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/oauth/OAuthClient.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#37863 Set auth session cookies when re-authenticate using identity cookie
  services/src/main/java/org/keycloak/protocol/AuthorizationEndpointBase.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LevelOfAssuranceFlowTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38081 Use clickLink and upgrade arquillian/selenium for chrome 134
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPasswordUpdatePage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/PasswordPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/PushTheButtonPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/ResetOtpPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/SetupRecoveryAuthnCodesPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/VerifyProfilePage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/AuthenticatorSubflowsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/FlowOverrideTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/AppInitiatedActionWebAuthnTest.java
  testsuite/integration-arquillian/tests/pom.xml
Labels: team/cloud-native, team/core-clients, team/core-iam

#38010 [Test framework] AttackDetectionResourceTest migration
  test-framework/core/src/main/java/org/keycloak/testframework/realm/RealmConfigBuilder.java
  tests/base/src/test/java/org/keycloak/tests/admin/AttackDetectionResourceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AttackDetectionResourceTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, area/test-framework

#38044 Improve rest-api documentation for adding organization members and IDP
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationIdentityProvidersResource.java
  services/src/main/java/org/keycloak/organization/admin/resource/OrganizationMemberResource.java
Labels: flaky-test

#38079 Promote standard token-exchange V2 to supported by default
  common/src/main/java/org/keycloak/common/Profile.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeV1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeV1WithStandardTEV2EnabledTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/AbstractSubjectImpersonationTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2WithLegacyTokenExchangeTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/SubjectImpersonationTokenExchangeV1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/SubjectImpersonationTokenExchangeV1WithStandardV2EnabledTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/AbstractWellKnownProviderTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#38019 Remove hierarchicalUri in KeycloakUriBuilder and parse each URI part separately
  common/src/main/java/org/keycloak/common/util/KeycloakUriBuilder.java
Labels: flaky-test

#38080 Use token ID to detect lightweight access token
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
Labels: flaky-test

#38008 Update documentation for supported token-exchange
  docs/documentation/release_notes/topics/26_2_0.adoc
  docs/documentation/server_admin/topics/clients/con-client-scopes.adoc
  docs/documentation/server_admin/topics/clients/oidc/con-basic-settings.adoc
  docs/documentation/server_admin/topics/sessions.adoc
  docs/documentation/tests/src/test/resources/ignored-links
  docs/documentation/topics/templates/document-attributes.adoc
  docs/documentation/upgrading/topics/changes/changes-26_2_0.adoc
  docs/guides/images/token-exchange-switch-refresh.png
  docs/guides/images/token-exchange-switch.png
  docs/guides/securing-apps/token-exchange.adoc
Labels: flaky-test

#38070 fix: turning off default picocli behavior we don't want
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/ConfigCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/ConfigCredentialsCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/KcAdmCmd.java
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/common/Globals.java
  integration/client-cli/admin-cli/src/test/java/org/keycloak/client/admin/cli/commands/KcAdmCliTest.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/ConfigArgsConfigSource.java
Labels: team/cloud-native, flaky-test

#32349 Fix missing signature for SAML frontChannel Logout
  services/src/main/java/org/keycloak/protocol/saml/SamlProtocol.java
  services/src/main/java/org/keycloak/protocol/saml/SamlService.java
  services/src/test/java/org/keycloak/protocol/saml/SamlProtocolTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/saml/ArtifactBindingTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37989 Add the validated ID token and access token to the context so its claims can be used in mappers
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#38042 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_it.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_it.properties
Labels: team/ui, flaky-test

#37907 Operator: Implement an explicit update strategy
  docs/guides/operator/advanced-configuration.adoc
  operator/src/main/java/org/keycloak/operator/Constants.java
  operator/src/main/java/org/keycloak/operator/Utils.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/CRDUtils.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/UpdateSpec.java
  operator/src/main/java/org/keycloak/operator/upgrade/UpdateStrategy.java
  operator/src/main/java/org/keycloak/operator/upgrade/UpgradeLogicFactory.java
  operator/src/main/java/org/keycloak/operator/upgrade/impl/ExplicitUpgradeLogic.java
  operator/src/main/java/org/keycloak/operator/upgrade/impl/RecreateOnImageChangeUpgradeLogic.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/CRDTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/UpgradeTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/CRSerializationTest.java
  operator/src/test/resources/test-serialization-keycloak-cr.yml
Labels: team/cloud-native, flaky-test

#38144 Don't use Java's MessageFormat for messages evaluated in the front end
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#38015 Fix permissions for view-members and manage-members
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/AvailableRoleMappingResource.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/ClientPermissionEvaluator.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/ClientPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/ClientPermissionsV2.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/GroupPermissionsV2.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissionEvaluator.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/RolePermissionsV2.java
Labels: team/ui

#37677 Fix kc.home.dir by adding a trailing slash to the path
  quarkus/dist/src/main/content/conf/keycloak.conf
Labels: team/cloud-native

#37504 refinement of propertymapperinterceptor names
  quarkus/config-api/src/main/java/org/keycloak/config/Option.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/ConfigArgsConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/Configuration.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/IgnoredArtifacts.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KcEnvConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakPropertiesConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/NestedPropertyMappingInterceptor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PropertyMappingInterceptor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ConfigKeystorePropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/WildcardPropertyMapper.java
  quarkus/runtime/src/main/resources/META-INF/services/io.smallrye.config.ConfigSourceInterceptor
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/AbstractConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/runtime/src/test/resources/META-INF/keycloak.conf
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/FipsDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/StartDevCommandDistTest.java
Labels: team/cloud-native, flaky-test

#38142 Handle null values in parameters so that for example max length validation shows
  js/libs/ui-shared/src/user-profile/utils.ts
Labels: team/ui

#38136 DPoP: Refresh token created with DPoP can be refreshed without proof
  docs/documentation/server_admin/topics/clients/oidc/con-advanced-settings.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/services/util/DPoPUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/DPoPTest.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#38156 Translations update from Hosted Weblate
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
Labels: team/ui

#38154 Fix broken link to configuration for production
  docs/guides/server/reverseproxy.adoc
Labels: team/cloud-native

#38118 fix: separating api server tests, and splitting the operator tests
  .github/workflows/operator-ci.yml
  operator/pom.xml
  operator/src/test/java/org/keycloak/operator/testsuite/apiserver/CRDTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/BaseOperatorTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakNetworkPolicyTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/UpgradeTest.java
Labels: team/cloud-native

#37643 Ensure that the project’s automated workflows tokens are set to read-only by default
  .github/workflows/aurora-delete.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/documentation.yml
  .github/workflows/guides.yml
  .github/workflows/js-ci.yml
  .github/workflows/label.yml
  .github/workflows/operator-ci.yml
  .github/workflows/quarkus-next.yml
  .github/workflows/schedule-nightly.yml
  .github/workflows/snyk-analysis.yml
  .github/workflows/trivy-analysis.yml
  .github/workflows/weblate.yml
Labels: area/ci, team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam, team/security

#38088 Improve UXD
  js/apps/admin-ui/src/authentication/FlowDetails.tsx
  js/apps/admin-ui/src/authentication/components/AuthenticationProviderContext.tsx
  js/apps/admin-ui/src/authentication/components/FlowHeader.tsx
  js/apps/admin-ui/src/authentication/components/FlowRow.tsx
  js/apps/admin-ui/src/authentication/components/FlowTitle.tsx
  js/apps/admin-ui/src/authentication/components/flow-row.css
  js/apps/admin-ui/src/authentication/components/flow-title.css
Labels: team/ui

#37840 SPI for compatibility metadata
  model/infinispan/src/main/java/org/keycloak/infinispan/compatibility/CachingCompatibilityMetadataProvider.java
  model/infinispan/src/main/resources/META-INF/services/org.keycloak.compatibility.CompatibilityMetadataProvider
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractUpdatesCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/UpdateCompatibilityCheck.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/UpdateCompatibilityMetadata.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/compatibility/CompatibilityComparator.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/compatibility/CompatibilityManager.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/compatibility/CompatibilityManagerImpl.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/compatibility/IncompatibleResult.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/compatibility/ServerInfo.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/UpdateCommandDistTest.java
  server-spi-private/src/main/java/org/keycloak/compatibility/CompatibilityMetadataProvider.java
  server-spi-private/src/main/java/org/keycloak/compatibility/CompatibilityResult.java
  server-spi-private/src/main/java/org/keycloak/compatibility/ProviderCompatibleResult.java
  server-spi-private/src/main/java/org/keycloak/compatibility/ProviderIncompatibleResult.java
  server-spi-private/src/main/java/org/keycloak/compatibility/Util.java
  services/src/main/java/org/keycloak/compatibility/KeycloakCompatibilityMetadataProvider.java
  services/src/main/resources/META-INF/services/org.keycloak.compatibility.CompatibilityMetadataProvider
Labels: team/cloud-native, flaky-test

#38173 add name as id because global profiles have none
  js/apps/admin-ui/src/realm-settings/AddClientProfileModal.tsx
Labels: team/ui

#36896 Add APIResponse annotations to Realm resources
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmLocalizationResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmsAdminResource.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#38176 Logout session when closing the keycloak client
  integration/admin-client/src/main/java/org/keycloak/admin/client/Keycloak.java
  integration/admin-client/src/main/java/org/keycloak/admin/client/token/TokenManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminClientTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38185 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_sl.properties
Labels: team/ui, flaky-test

#38035 BACKPORT: removed duplicate initial values (#38003)
  js/apps/admin-ui/src/authentication/policies/OtpPolicy.tsx
Labels: team/ui

#38202 remove base url
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/index.ftl
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/index.ftl
Labels: team/ui, backport/26.1

#38216 Improve message when evaluating permission results
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/permissions-configuration/permission-evaluation/PermissionEvaluationResult.tsx
  services/src/main/java/org/keycloak/authorization/admin/representation/PolicyEvaluationResponseBuilder.java
Labels: team/ui

#37687 Refactor credential issuance to use scope-based approach
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java
  services/src/main/java/org/keycloak/protocol/oid4vc/issuance/mappers/OID4VCTargetRoleMapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCSdJwtIssuingEndpointTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38244 Updating a client with rollback in a test doesn't reset all values
  test-framework/core/src/main/java/org/keycloak/testframework/realm/ManagedClient.java
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/ClientRollbackTest.java
Labels: area/test-framework

#38123 Login[v2]: Keycloak logo is not fully visible
  themes/src/main/resources/theme/keycloak.v2/login/resources/css/styles.css
  themes/src/main/resources/theme/keycloak.v2/login/resources/img/keycloak-bg-darken.svg
Labels: team/ui

#38231 allowing wildcards only at the end of keys to allow for other characters
  quarkus/config-api/src/main/java/org/keycloak/config/Option.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/ConfigArgsConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KcEnvConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakPropertiesConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/NestedPropertyMappingInterceptor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/WildcardPropertyMapper.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/LoggingConfigurationTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ShowConfigCommandDistTest.java
Labels: team/cloud-native

#38255 fix: remove out-dated references to hostname v1 properties
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/ConstantsDebugHostname.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/DebugHostnameSettingsResource.java
  quarkus/runtime/src/main/resources/META-INF/keycloak.conf
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/AbstractQuarkusDeployableContainer.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38233 Initial support for partial evaluation
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/aggregated/AggregatePolicyProviderFactory.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/client/ClientPolicyProviderFactory.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/group/GroupPolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/group/GroupPolicyProviderFactory.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/js/JSPolicyProviderFactory.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/permission/ResourcePolicyProviderFactory.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/permission/ScopePolicyProviderFactory.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProviderFactory.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/time/TimePolicyProviderFactory.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/user/UserPolicyProvider.java
  authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/user/UserPolicyProviderFactory.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/authorization/StoreFactoryCacheSession.java
  model/jpa/src/main/java/org/keycloak/authorization/jpa/entities/PolicyEntity.java
  model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAPolicyStore.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/BruteForceUsersResource.java
  server-spi-private/pom.xml
  server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java
  server-spi-private/src/main/java/org/keycloak/authorization/AuthorizationProvider.java
  server-spi-private/src/main/java/org/keycloak/authorization/FGAPPolicyEvaluator.java
  server-spi-private/src/main/java/org/keycloak/authorization/PartialEvaluator.java
  server-spi-private/src/main/java/org/keycloak/authorization/identity/UserModelIdentity.java
  server-spi-private/src/main/java/org/keycloak/authorization/permission/evaluator/Evaluators.java
  server-spi-private/src/main/java/org/keycloak/authorization/permission/evaluator/IterablePermissionEvaluator.java
  server-spi-private/src/main/java/org/keycloak/authorization/permission/evaluator/UnboundedPermissionEvaluator.java
  server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/DefaultPolicyEvaluator.java
  server-spi-private/src/main/java/org/keycloak/authorization/policy/provider/PartialEvaluationPolicyProvider.java
  server-spi-private/src/main/java/org/keycloak/authorization/policy/provider/PartialEvaluationStorageProvider.java
  server-spi-private/src/main/java/org/keycloak/authorization/store/PolicyStore.java
  server-spi/src/main/java/org/keycloak/models/KeycloakContext.java
  services/src/main/java/org/keycloak/services/DefaultKeycloakContext.java
  services/src/main/java/org/keycloak/services/resources/admin/AdminRoot.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/ClientPermissionsV2.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissions.java
  services/src/main/java/org/keycloak/services/resources/admin/permissions/UserPermissionsV2.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/AbstractPermissionTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/RealmAdminPermissionsConfig.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypeEvaluationTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypeFilteringTest.java
Labels: team/ui

#38268 Improve message when evaluating permission results
  services/src/main/java/org/keycloak/authorization/admin/representation/PolicyEvaluationResponseBuilder.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/PolicyEvaluationCompositeRoleTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38207 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_de.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ka.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ro.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ka.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ro.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ka.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_ro.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ro.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_de.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_ro.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_es.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ro.properties
Labels: team/ui

#38203 re added search on admin ui
  js/apps/admin-ui/src/organizations/OrganizationsSection.tsx
  js/libs/ui-shared/src/controls/OrganizationTable.tsx
Labels: team/ui

#38199 better filter and match the tabs that should be rendered dynamic
  js/apps/admin-ui/src/components/routable-tabs/RoutableTabs.tsx
Labels: team/ui

#37531 Missing translation for INVITE_ORG event in admin console
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
Labels: team/ui

#38245 Recovery codes modifications to not tamper sent values
  services/src/main/java/org/keycloak/authentication/authenticators/browser/RecoveryAuthnCodesFormAuthenticator.java
  services/src/main/java/org/keycloak/authentication/requiredactions/RecoveryAuthnCodesAction.java
  services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/SetupRecoveryAuthnCodesPage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RecoveryAuthnCodesAuthenticatorTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38122 Remove deprecated TokenExchangeRequest.additionalParameters()
  tests/utils-shared/src/main/java/org/keycloak/testsuite/util/oauth/TokenExchangeRequest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/ClientTokenExchangeSAML2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV1Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38179 Finalizing release notes and documentation for initial rolling update
  common/src/main/java/org/keycloak/common/Profile.java
  docs/documentation/release_notes/topics/26_2_0.adoc
  docs/documentation/tests/src/test/resources/ignored-links
  docs/guides/operator/advanced-configuration.adoc
  docs/guides/operator/rolling-updates.adoc
  docs/guides/server/update-compatibility.adoc
  docs/guides/templates/kc.adoc
  operator/src/main/java/org/keycloak/operator/ContextUtils.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeploymentDependentResource.java
  operator/src/main/java/org/keycloak/operator/controllers/KeycloakUpdateJobDependentResource.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakSpec.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/KeycloakStatusAggregator.java
  operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/UpdateSpec.java
  operator/src/main/java/org/keycloak/operator/update/UpdateLogic.java
  operator/src/main/java/org/keycloak/operator/update/UpdateLogicFactory.java
  operator/src/main/java/org/keycloak/operator/update/UpdateStrategy.java
  operator/src/main/java/org/keycloak/operator/update/UpdateType.java
  operator/src/main/java/org/keycloak/operator/update/impl/AutoUpdateLogic.java
  operator/src/main/java/org/keycloak/operator/update/impl/BaseUpgradeLogic.java
  operator/src/main/java/org/keycloak/operator/update/impl/ExplicitUpdateLogic.java
  operator/src/main/java/org/keycloak/operator/update/impl/RecreateOnImageChangeUpdateLogic.java
  operator/src/test/java/org/keycloak/operator/testsuite/apiserver/CRDTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakDeploymentTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/integration/UpdateTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/unit/CRSerializationTest.java
  operator/src/test/java/org/keycloak/operator/testsuite/utils/CRAssert.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractUpdatesCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/UpdateCompatibilityCheck.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/UpdateCommandDistTest.java
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testDefaultToHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testHelpShort.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelp.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityCheckHelpAll.approved.txt
  quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help/HelpCommandDistTest.testUpdateCompatibilityHelp.approved.txt
  server-spi-private/src/main/java/org/keycloak/compatibility/ProviderIncompatibleResult.java
Labels: team/cloud-native

#38196 Managed resource not injected if a dependency is incompatible
  test-framework/core/src/main/java/org/keycloak/testframework/injection/AbstractInterceptorHelper.java
  test-framework/core/src/main/java/org/keycloak/testframework/injection/InstanceContext.java
  test-framework/core/src/main/java/org/keycloak/testframework/injection/Registry.java
  test-framework/core/src/main/java/org/keycloak/testframework/injection/RequestedInstance.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/RealmSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/AbstractKeycloakServerSupplier.java
  test-framework/core/src/test/java/org/keycloak/testframework/injection/RegistryTest.java
Labels: status/hold, area/test-framework

#37557 fix invalid scope http error code
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/endpoints/BackchannelAuthenticationEndpoint.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/CIBATest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#38234 User session lookup optimization and fixes
  server-spi-private/src/main/java/org/keycloak/events/Details.java
  server-spi-private/src/main/java/org/keycloak/models/Constants.java
  services/src/main/java/org/keycloak/authorization/common/KeycloakIdentity.java
  services/src/main/java/org/keycloak/authorization/protection/introspect/RPTIntrospectionProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/AccessTokenIntrospectionProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/RefreshTokenIntrospectionProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/encode/AccessTokenContext.java
  services/src/main/java/org/keycloak/protocol/oidc/encode/DefaultTokenContextEncoderProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenIntrospectionEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/UserInfoEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/AbstractTokenExchangeProvider.java
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProvider.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/resources/account/AccountLoader.java
  services/src/main/java/org/keycloak/services/util/UserSessionUtil.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/AdminClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/CIBATest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ServiceAccountTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/TokenIntrospectionTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/UserInfoTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#35075 Add config param disableTypeClaimCheck in order to validate external …
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/identity-providers/add/ExtendedNonDiscoverySettings.tsx
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java
  services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProviderConfig.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/KcOidcBrokerTokenExchangeTest.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#38283 Use clickLink and upgrade arquillian/selenium for chrome 134
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPasswordUpdatePage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/PasswordPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/PushTheButtonPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/ResetOtpPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/SetupRecoveryAuthnCodesPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/VerifyProfilePage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/AuthenticatorSubflowsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/FlowOverrideTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/AppInitiatedActionWebAuthnTest.java
  testsuite/integration-arquillian/tests/pom.xml
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#38100 Set CONFIGURE_OTP via auth session in ConditionalOtpFormAuthenticator
  services/src/main/java/org/keycloak/authentication/authenticators/browser/ConditionalOtpFormAuthenticator.java
Labels: flaky-test

#36665 Sending Mails via SMTP and XOAUTH2 authentication mechanism
  docs/documentation/release_notes/topics/26_2_0.adoc
  docs/documentation/server_admin/topics/realms/email.adoc
  docs/documentation/topics/templates/document-attributes.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/realm-settings/EmailTab.tsx
  js/apps/admin-ui/test/realm-settings/email.spec.ts
  js/apps/admin-ui/test/realm-settings/email.ts
  model/storage-private/src/main/java/org/keycloak/storage/datastore/DefaultExportImportManager.java
  pom.xml
  server-spi-private/src/main/java/org/keycloak/models/utils/StripSecretsUtils.java
  server-spi/src/main/java/org/keycloak/utils/KeycloakSessionUtil.java
  services/src/main/java/org/keycloak/email/DefaultEmailAuthenticator.java
  services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java
  services/src/main/java/org/keycloak/email/DefaultEmailSenderProviderFactory.java
  services/src/main/java/org/keycloak/email/EmailAuthenticator.java
  services/src/main/java/org/keycloak/email/PasswordAuthEmailAuthenticator.java
  services/src/main/java/org/keycloak/email/TokenAuthEmailAuthenticator.java
  services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/KeycloakUrls.java
  test-framework/email-server/pom.xml
  test-framework/email-server/src/main/java/org/keycloak/testframework/mail/MailServer.java
  tests/base/src/test/java/org/keycloak/tests/admin/SMTPConnectionTest.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/examples/providersoverride/CustomDefaultEmailSenderProvider1.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/examples/providersoverride/CustomDefaultEmailSenderProvider2.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/examples/providersoverride/CustomDefaultEmailSenderProviderFactory1.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/examples/providersoverride/CustomDefaultEmailSenderProviderFactory2.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam

#37318 changed it back to using full width buttons
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/i18n/LoginPageTest.java
  themes/src/main/resources/theme/keycloak.v2/login/resources/css/styles.css
  themes/src/main/resources/theme/keycloak.v2/login/social-providers.ftl
  themes/src/main/resources/theme/keycloak.v2/login/theme.properties
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#38314 added missing onDataChange handler
  js/apps/admin-ui/src/components/dynamic/FileComponent.tsx
Labels: team/ui

#38324 reverted change made to client select as it breaks
  js/apps/admin-ui/src/clients/authorization/policy/Client.tsx
  js/apps/admin-ui/src/components/client/ClientSelect.tsx
  js/apps/admin-ui/src/permissions-configuration/resource-types/ClientSelectComponent.tsx
  js/apps/admin-ui/src/permissions-configuration/resource-types/ResourceType.tsx
Labels: team/ui

#38276 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_it.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ro.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/admin/messages/messages_ca.properties
  themes/src/main/resources-community/theme/base/email/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ro.properties
Labels: team/ui

#38347 Use clickLink and upgrade arquillian/selenium for chrome 134 (26.0)
  testsuite/integration-arquillian/pom.xml
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginConfigTotpPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPasswordResetPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginPasswordUpdatePage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginTotpPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginUsernameOnlyPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LogoutSessionsPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/PasswordPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/PushTheButtonPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/ResetOtpPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/SetupRecoveryAuthnCodesPage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/VerifyProfilePage.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/OAuthClient.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/AuthenticatorSubflowsTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/FlowOverrideTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/ResetPasswordTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/webauthn/AppInitiatedActionWebAuthnTest.java
  testsuite/integration-arquillian/tests/pom.xml
Labels: team/cloud-native, team/core-clients, team/core-iam

#38219 Upgrade to Infinispan 15.0.14
  pom.xml
Labels: flaky-test

#38313 Add version column to credential table to avoid simultaneous recovery codes updates
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/CredentialEntity.java
  model/jpa/src/main/resources/META-INF/jpa-changelog-26.2.0.xml
  services/src/main/java/org/keycloak/authentication/authenticators/browser/RecoveryAuthnCodesFormAuthenticator.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/authentication/DelayedAuthenticator.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/authentication/DelayedAuthenticatorFactory.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/resources/META-INF/services/org.keycloak.authentication.AuthenticatorFactory
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/EnterRecoveryAuthnCodePage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AssertEvents.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RecoveryAuthnCodesAuthenticatorTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#37573 Add client OIDC compatibility mode setting for configuring the header type in access tokens.
  docs/documentation/release_notes/topics/26_2_0.adoc
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  js/apps/admin-ui/src/clients/AdvancedTab.tsx
  js/apps/admin-ui/src/clients/advanced/FineGrainOpenIdConnect.tsx
  operator/src/test/resources/test-serialization-realmimport-cr.yml
  operator/src/test/resources/token-test-realm.yaml
  server-spi-private/src/main/java/org/keycloak/protocol/oidc/OIDCConfigAttributes.java
  services/src/main/java/org/keycloak/jose/jws/DefaultTokenManager.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCAdvancedConfigWrapper.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/AccessTokenTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#38288 `PartialEvaluator` ignores `view-*` and `manage-*` roles
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/BruteForceUsersResource.java
  server-spi-private/src/main/java/org/keycloak/authorization/PartialEvaluator.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypeFilteringTest.java
Labels: team/ui

#38342 Fix Typescript error during build-lib.
  js/apps/account-ui/package.json
  js/apps/admin-ui/package.json
  js/apps/admin-ui/src/i18n/i18n.ts
  js/pnpm-lock.yaml
Labels: team/ui

#38322 Support partial evaluation for the group resource type
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheManager.java
  model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/RealmCacheSession.java
  model/jpa/src/main/java/org/keycloak/models/jpa/GroupAdapter.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/GroupEntity.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/UserGroupMembershipEntity.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/BruteForceUsersResource.java
  server-spi-private/src/main/java/org/keycloak/authorization/AdminPermissionsSchema.java
  server-spi-private/src/main/java/org/keycloak/authorization/PartialEvaluator.java
  server-spi-private/src/main/java/org/keycloak/authorization/policy/provider/PartialEvaluationStorageProvider.java
  services/src/main/java/org/keycloak/services/DefaultKeycloakContext.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java
  services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java
  services/src/main/java/org/keycloak/utils/GroupUtils.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/GroupResourceTypeFilteringTest.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypeFilteringTest.java
Labels: team/ui

#38229 Login[v2]: Improve login screens
  themes/src/main/resources/theme/keycloak.v2/login/field.ftl
  themes/src/main/resources/theme/keycloak.v2/login/footer.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-reset-password.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login.ftl
  themes/src/main/resources/theme/keycloak.v2/login/resources/css/styles.css
  themes/src/main/resources/theme/keycloak.v2/login/social-providers.ftl
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
  themes/src/main/resources/theme/keycloak.v2/login/theme.properties
Labels: team/ui

#38411 Upgrade to Quarkus 3.15.4
  pom.xml
Labels: flaky-test

#38343 Translations update from Hosted Weblate
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_it.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_de.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_es.properties
  js/apps/admin-ui/maven-resources-community/theme/keycloak.v2/admin/messages/messages_ja.properties
  themes/src/main/resources-community/theme/base/account/messages/messages_it.properties
  themes/src/main/resources-community/theme/base/login/messages/messages_ro.properties
Labels: team/ui

#38383 make whole row disabled
  js/apps/admin-ui/src/components/users/UserDataTable.tsx
  js/libs/ui-shared/src/controls/table/KeycloakDataTable.tsx
Labels: team/ui, flaky-test

#38300 fix: makes the configsources consistent wrt hidden properties
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/ConfigArgsConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PersistedConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
Labels: team/cloud-native

#38388 initial version of the test and some refactor
  .github/workflows/js-ci.yml
  js/apps/admin-ui/src/clients/authorization/SearchDropdown.tsx
  js/apps/admin-ui/src/components/users/UserSelect.tsx
  js/apps/admin-ui/src/permissions-configuration/PermissionsConfigurationSection.tsx
  js/apps/admin-ui/src/permissions-configuration/permission-configuration/PermissionsConfigurationTab.tsx
  js/apps/admin-ui/src/permissions-configuration/permission-evaluation/PermissionsEvaluationTab.tsx
  js/apps/admin-ui/src/permissions-configuration/resource-types/GroupSelect.tsx
  js/apps/admin-ui/src/permissions-configuration/resource-types/ResourceType.tsx
  js/apps/admin-ui/src/permissions-configuration/resource-types/SearchDropdown.tsx
  js/apps/admin-ui/test/organization/main.spec.ts
  js/apps/admin-ui/test/permissions/main.spec.ts
  js/apps/admin-ui/test/permissions/main.ts
  js/apps/admin-ui/test/permissions/policy.spec.ts
  js/apps/admin-ui/test/permissions/policy.ts
  js/apps/admin-ui/test/realm-roles/axe.spec.ts
  js/apps/admin-ui/test/realm-settings/client-policies.spec.ts
  js/apps/admin-ui/test/realm-settings/client-policies.ts
  js/apps/admin-ui/test/realm-settings/userprofile.spec.ts
  js/apps/admin-ui/test/realm-settings/userprofile.ts
  js/apps/admin-ui/test/user-federation/kerberos.spec.ts
  js/apps/admin-ui/test/utils/AdminClient.ts
  js/apps/keycloak-server/scripts/start-server.js
  js/libs/ui-shared/src/controls/select-control/SelectControl.tsx
  js/libs/ui-shared/src/controls/select-control/SingleSelectControl.tsx
Labels: team/ui, flaky-test

#38419 Login[v2]: WebAuthn/Passkeys screens are not polished
  themes/src/main/resources/theme/keycloak.v2/login/buttons.ftl
  themes/src/main/resources/theme/keycloak.v2/login/login-update-password.ftl
  themes/src/main/resources/theme/keycloak.v2/login/template.ftl
  themes/src/main/resources/theme/keycloak.v2/login/terms.ftl
  themes/src/main/resources/theme/keycloak.v2/login/theme.properties
  themes/src/main/resources/theme/keycloak.v2/login/webauthn-authenticate.ftl
  themes/src/main/resources/theme/keycloak.v2/login/webauthn-error.ftl
  themes/src/main/resources/theme/keycloak.v2/login/webauthn-register.ftl
Labels: team/ui

#38237 fix: refinements to minimize the config logic
  quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/Environment.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakConfigSourceProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KeycloakPropertiesConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/MicroProfileConfigProvider.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/NestedPropertyMappingInterceptor.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/QuarkusPropertiesConfigSource.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/CachingPropertyMappers.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMappers.java
  quarkus/runtime/src/main/resources/META-INF/keycloak.conf
  quarkus/runtime/src/main/resources/META-INF/services/quarkus.properties
  quarkus/runtime/src/main/resources/application.properties
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/AbstractConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/LoggingConfigurationTest.java
  quarkus/runtime/src/test/resources/conf/keycloak.conf
  quarkus/runtime/src/test/resources/conf/keystore
  quarkus/runtime/src/test/resources/conf/quarkus.properties
  quarkus/runtime/src/test/resources/providers/README
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ShowConfigCommandDistTest.java
  quarkus/tests/integration/src/test/resources/ShowConfigCommandTest/quarkus.properties
  quarkus/tests/junit5/src/main/java/org/keycloak/it/junit5/extension/CLITestExtension.java
  quarkus/tests/junit5/src/main/java/org/keycloak/quarkus/runtime/configuration/test/TestConfigArgsConfigSource.java
  quarkus/tests/junit5/src/main/java/org/keycloak/quarkus/runtime/configuration/test/TestKeycloakConfigSourceProvider.java
Labels: team/cloud-native, flaky-test

#38391 Re-add messages for recovery codes credential in the account console
  core/src/main/java/org/keycloak/representations/account/CredentialMetadataRepresentation.java
  core/src/main/java/org/keycloak/representations/account/LocalizedMessage.java
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ca.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_de.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_es.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_fr.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_hr.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_it.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_ka.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_nl.properties
  js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_pl.properties
  js/apps/account-ui/maven-resources/theme/keycloak.v3/account/messages/messages_en.properties
  js/apps/account-ui/src/account-security/SigningIn.tsx
  js/apps/account-ui/src/api/representations.ts
  server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java
Labels: team/ui

#38389 fix: validating derived option usage and show-config display
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
Labels: team/cloud-native

#38449 AgePasswordPolicy should not check password for registration
  server-spi-private/src/main/java/org/keycloak/policy/AgePasswordPolicyProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/policy/PasswordAgePolicyTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38367 Adding event type for client policy error #38366
  server-spi-private/src/main/java/org/keycloak/events/Details.java
  services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenIntrospectionEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenRevocationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/endpoints/UserInfoEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/AuthorizationCodeGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ClientCredentialsGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/OAuth2GrantTypeBase.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/RefreshTokenGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ResourceOwnerPasswordCredentialsGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/TokenExchangeGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/CibaGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/ciba/endpoints/BackchannelAuthenticationEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/device/DeviceGrantType.java
  services/src/main/java/org/keycloak/protocol/oidc/grants/device/endpoints/DeviceEndpoint.java
  services/src/main/java/org/keycloak/protocol/oidc/par/endpoints/ParEndpoint.java
  services/src/main/java/org/keycloak/protocol/saml/SamlService.java
  services/src/main/java/org/keycloak/services/clientregistration/AbstractClientRegistrationProvider.java
  services/src/main/java/org/keycloak/services/clientregistration/ClientRegistrationAuth.java
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/AssertEvents.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/CIBATest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1ConfidentialClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/OAuth2_1PublicClientTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/AbstractClientPoliciesTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesExecutorTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/policies/ClientPoliciesTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#38491 remove the use of namespace from the config
  js/apps/account-ui/src/i18n.ts
  js/apps/admin-ui/src/i18n/i18n.ts
Labels: team/ui

#38462 Allow users to unset their e-mail when the previous e-mail matches or…
  services/src/main/java/org/keycloak/organization/validator/OrganizationMemberValidator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/organization/member/OrganizationMemberTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam
