Repository keycloak/keycloak, pull requests merged in 2025-10, with the labels that each got.

#43116 Do not remove sid claim when the session is transient only for the client (26.4)
  services/src/main/java/org/keycloak/protocol/oidc/tokenexchange/StandardTokenExchangeProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/tokenexchange/StandardTokenExchangeV2Test.java
  testsuite/integration-arquillian/tests/base/src/test/resources/token-exchange/testrealm-token-exchange-v2.json
Labels: team/cloud-native, team/core-clients, team/core-iam

#43153 [26.4] Update Grafana dashboard version
  docs/guides/observability/grafana-dashboards.adoc
Labels: team/sre

#43097 Make sure the component state is updated when invoking sync on user storage providers
  js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
  model/storage-private/src/main/java/org/keycloak/storage/UserStorageManager.java
  model/storage-private/src/main/java/org/keycloak/storage/managers/UserStorageSyncManager.java
Labels: team/ui

#43130 Disable Secure Client-Initiated Renegotiation by default
  quarkus/dist/src/main/content/bin/kc.bat
  quarkus/dist/src/main/content/bin/kc.sh
Labels: team/cloud-native

#43170 Restarting an user session broken for persistent sessions
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/UserSessionAdapter.java
  model/storage-private/src/main/java/org/keycloak/models/session/PersistentUserSessionAdapter.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserSessionProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, team/sre

#43131 Prevent users configuring max-count=-1 for caches with a default upper-bound
  docs/guides/server/caching.adoc
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/CacheConfigurator.java
  model/infinispan/src/main/java/org/keycloak/spi/infinispan/impl/embedded/DefaultCacheEmbeddedConfigProviderFactory.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ClusterConfigDistTest.java
Labels: team/cloud-native, team/sre

#43172 fix: removing test os restriction (#41952)
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ImportRealmMixin.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
  quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/ImportAtStartupDistTest.java
Labels: team/cloud-native

#42462 [Test Migration] New testsuites: Clusterless, Multisite, VolatileSessions, migrated test: SessionTest
  .github/workflows/ci.yml
  test-framework/core/src/main/java/org/keycloak/testframework/realm/RealmConfigBuilder.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/KeycloakServerConfigBuilder.java
  test-framework/ui/src/main/java/org/keycloak/testframework/ui/page/LoginPage.java
  tests/base/src/test/java/org/keycloak/tests/admin/client/SessionTest.java
  tests/base/src/test/java/org/keycloak/tests/suites/ClusterlessTestSuite.java
  tests/base/src/test/java/org/keycloak/tests/suites/MultisiteTestSuite.java
  tests/base/src/test/java/org/keycloak/tests/suites/VolatileSessionsTestSuite.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client/SessionTest.java
  testsuite/integration-arquillian/tests/base/testsuites/clusterless-suite
  testsuite/integration-arquillian/tests/base/testsuites/volatile-sessions-suite
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam, area/test-framework

#43186 [26.4] Restarting an user session broken for persistent sessions
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/UserSessionAdapter.java
  model/storage-private/src/main/java/org/keycloak/models/session/PersistentUserSessionAdapter.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserSessionProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam, team/sre

#43187 [26.2] Restarting an user session broken for persistent sessions
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/UserSessionAdapter.java
  model/storage-private/src/main/java/org/keycloak/models/session/PersistentUserSessionAdapter.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserSessionProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#43188 [26.0] Restarting an user session broken for persistent sessions
  model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/UserSessionAdapter.java
  model/storage-private/src/main/java/org/keycloak/models/session/PersistentUserSessionAdapter.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/model/UserSessionProviderTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#42616 [Test Framework] Ability to run Keycloak test server with HTTPS
  test-framework/clustering/src/main/java/org/keycloak/testframework/server/ClusteredKeycloakServer.java
  test-framework/core/src/main/java/org/keycloak/testframework/CoreTestFrameworkExtension.java
  test-framework/core/src/main/java/org/keycloak/testframework/admin/AdminClientFactory.java
  test-framework/core/src/main/java/org/keycloak/testframework/admin/AdminClientFactorySupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/http/HttpClientSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/https/CertificatesSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/https/InjectCertificates.java
  test-framework/core/src/main/java/org/keycloak/testframework/https/ManagedCertificates.java
  test-framework/core/src/main/java/org/keycloak/testframework/https/ManagedCertificatesException.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/AbstractKeycloakServerSupplier.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/DistributionKeycloakServer.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/EmbeddedKeycloakServer.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/KeycloakServer.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/KeycloakServerConfigBuilder.java
  test-framework/core/src/main/java/org/keycloak/testframework/server/RemoteKeycloakServer.java
  test-framework/examples/tests/src/test/java/org/keycloak/test/examples/TlsEnabledTest.java
Labels: team/cloud-native, team/sre, area/test-framework

#43107 Expose scheduled tasks and start time
  server-spi-private/src/main/java/org/keycloak/timer/TimerProvider.java
  services/src/main/java/org/keycloak/timer/basic/BasicTimerProvider.java
  services/src/main/java/org/keycloak/timer/basic/BasicTimerProviderFactory.java
  services/src/main/java/org/keycloak/timer/basic/TimerTaskContextImpl.java
Labels: team/cloud-native, team/ui, team/core-clients, team/core-iam, team/sre

#43024 Hide read-only email attribute in update profile context with update … …email enabled
  docs/documentation/server_admin/topics/login-settings/update-email-workflow.adoc
  services/src/main/java/org/keycloak/authentication/requiredactions/UpdateEmail.java
  services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProviderFactory.java
  testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/LoginUpdateProfilePage.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/AbstractRequiredActionUpdateEmailTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateEmailTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/actions/RequiredActionUpdateEmailTestWithVerificationTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/user/profile/UserProfileTest.java
Labels: team/cloud-native, team/ui, flaky-test, team/core-clients, team/core-iam

#43239 Convert the wizard to create client in progressive to validate every step
  js/apps/admin-ui/src/clients/add/NewClientForm.tsx
Labels: team/ui

#42953 Ensure events are fully filled before success is called
  services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java
  services/src/main/java/org/keycloak/services/resources/LoginActionsService.java
  testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/events/TestEventsListenerProvider.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/broker/AbstractFirstBrokerLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/BruteForceTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/MultipleTabsLoginTest.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/RPInitiatedLogoutTest.java
Labels: team/cloud-native, team/core-clients, team/core-iam

#43268 fix: making picocli ansi handling match quarkus
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/Picocli.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/AbstractAutoBuildCommand.java
  quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java
  quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/cli/PicocliTest.java
Labels: team/cloud-native

#43276 fix: adds error handling for common redirect codes
  integration/client-cli/admin-cli/src/main/java/org/keycloak/client/cli/util/HttpUtil.java
Labels: team/cloud-native

#43089 CI pipeline breaks when there are no tags for a release branch yet
  .github/scripts/version-compatibility.sh
  .github/workflows/ci.yml
Labels: team/sre

#43283 Ensure conformance for Signed JWT Validation (backport) (#43269)
  services/src/main/java/org/keycloak/authentication/authenticators/client/JWTClientValidator.java
  testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientAuthSignedJWTTest.java
Labels: team/cloud-native, flaky-test, team/core-clients, team/core-iam

#43189 [FGAP] Make additional rest endpoints respect permissions
  model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java
  model/jpa/src/main/java/org/keycloak/models/jpa/entities/UserRoleMappingEntity.java
  rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/SessionsResource.java
  services/src/main/java/org/keycloak/services/resources/admin/RoleContainerResource.java
  test-framework/core/src/main/java/org/keycloak/testframework/realm/UserConfigBuilder.java
  tests/base/src/test/java/org/keycloak/tests/admin/authz/fgap/UserResourceTypeFilteringTest.java
Labels: team/ui

#43287 Adding attributes for section links so they work in upstream and downstream
  docs/documentation/topics/templates/document-attributes.adoc
  docs/guides/attributes.adoc
  docs/guides/server/db.adoc
Labels: team/cloud-native
